### ISSUE TITLE
Inability to enter data in Optional Fields

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#6901] opened 2020-09-10 18:58 UTC
Running the 5.2-linux-portable build of 2020-09-09. The optional fields tab has 2 columns on the left for data entry and a preview of the entire entry on the right. However, text cannot be entered in the right column and that whole window cannot be expanded to allow data entry.

The attached screen shot illustrates the situation. Notice in the right side window the volume number (8) at the end of the text. That number is not visible in the volume entry field on the right half of the display.

I kept trying to enter the volume and expand that window, but was unsuccessful. I noticed the string of volume numbers in the right side window and hit the delete key until only a single '8' was present.

This situation was in a previous release and fixed. Please fix again.

**Comment by rs-aesi** [comment] 2020-09-11 14:55
Update: this same problem exists with the stable 5.1 release (linux-portable-5.1).

**Comment by Siedlerchr** [comment] 2020-09-12 14:01
Yeah, it's a problem if the entry preview is shown as part of the entry editor.
You can only expand the colum if you move the preview to the right or you can tick the options show preview as own tab.

The code for calculating the column constraints and witths in the "compressed" mode is here:
https://github.com/JabRef/jabref/blob/1d2ecffa1b07d930c0ff936e2574d102aaf7255d/src/main/java/org/jabref/gui/entryeditor/FieldsEditorTab.java#L109-L120

**Comment by rs-aesi** [comment] 2020-09-12 16:45
On Sat, 12 Sep 2020, Christoph wrote:

> You can only expand the colum if you move the preview to the right or you
> can tick the options show preview as own tab.

Christoph,

I cannot move the preview further to the right. Setting the preview in its
own tab puts it at the leftmost tab position. Is there a way to display it
on the right side instead?

There's also a tab called 'LaTeX Citations'. I've no idea what it's for; I
have no need for whatever it does. Can this be removed?

Putting the preview in its own tab resolves one of my issues. I can live
with Alt-3 not opening the groups panel (another of my issues), but the
inability to define the Emacs keyboard shortcuts instead of Microsoft's CUA
keyboard shortcuts is a real stopper for me. I use emacs for ~90% of my
writing, LyX, and the small editor, joe, for the rest. All three use the
emacs keys and after 20+ years they are second nature for me.

The only other issue, minor but annoying, is that the entry editor window
for the first article in the database is always displayed with I invoke
JabRef. It shouldn't be.

Thanks for the advice on the preview.

Stay well,

Rich

**Comment by Siedlerchr** [comment] 2020-09-12 17:11
You can drag the preview a bit more to the right at that line
<img width="1569" alt="Bildschirmfoto 2020-09-12 um 19 08 21" src="https://user-images.githubusercontent.com/320228/93000958-bf4b3f80-f52b-11ea-8c9d-88110d641278.png">


@rs-aesi  Unfortunately, it's not possible to change the tab order.
However, you can disable the Related Articles Tab and the Latex Citations tab under Options -> Entry editor. 
The tab latex citations allows you to show where in a LaTeX document you have used your current reference. 

Regarding the emacs keybindings. Well it might be an issue for you, but apparently many others are happy with the defaults.  And the issue is still open. Maybe you can find someone who is interested in re-implementing it.

**Comment by JohanDelValleV** [comment] 2020-12-01 18:19
Is this issue still open? I'm looking for OP projects to contribute @Siedlerchr

**Comment by Siedlerchr** [comment] 2020-12-01 18:46
@JohanDelValleV Thanks your your interest! Yes, the issue is still available. And it would be really nice to have this issue fixed. 
 For getting started follow our contribution guide. 
Code wise the layout is calculated by the code I posted above. 

If you need any help, ask here or in our gitter channel 

 https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md

**Comment by Siedlerchr** [comment] 2021-12-04 16:10
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

Fixed by #8232

**Closed by Siedlerchr** 2021-12-04 16:10 UTC
Labels: type: bug 🐛, ui, entry-editor, good first issue
