### ISSUE TITLE
JabRef build 2022-09-25 20:56 does not start 

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#9176] opened 2022-09-26 07:39 UTC
### JabRef version

Other (please describe below)

### Operating system

Fedora 36 Linux

### Details on version and operating system

build from 2022-09-25 20:56

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

normal start via Gnome Desktop file does not work.

In shell I get an error, see below.

I am not aware of any relevant system/environment changes on my side. But of course, I regularly update my system.

The flatpak 5.7 works, however, at least gets me a JabRef window.

### Appendix

...
<details>

<summary>Log File</summary>

```
Sept 26, 2022 9:34:17 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
2022-09-26 09:34:17 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
INFO: Trust store path: /home/il/.local/share/JabRef/ssl/truststore.jks
2022-09-26 09:34:18 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2022-09-26 09:34:18 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Exception in Application start method
2022-09-26 09:34:19 [main] org.jabref.gui.FallbackExceptionHandler.uncaughtException()
ERROR: Uncaught exception occurred in Thread[main,5,main]: java.lang.RuntimeException: Exception in Application start method
	at org.jabref.merged.module@5.8.110/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalAccessError: class com.airhacks.afterburner.injection.Injector (in module org.jabref.merged.module) cannot access class jakarta.inject.Inject (in module jakarta.inject) because module org.jabref.merged.module does not read module jakarta.inject
	at org.jabref.merged.module@5.8.110/com.airhacks.afterburner.injection.Injector.injectMembers(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.airhacks.afterburner.injection.Injector.injectMembers(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.DefaultInjector.injectMembers(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.airhacks.afterburner.views.ViewLoader.lambda$controller$4(Unknown Source)
	at org.jabref.merged.module@5.8.110/javafx.fxml.FXMLLoader$ValueElement.processAttribute(Unknown Source)
	at org.jabref.merged.module@5.8.110/javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(Unknown Source)
	at org.jabref.merged.module@5.8.110/javafx.fxml.FXMLLoader$Element.processStartElement(Unknown Source)
	at org.jabref.merged.module@5.8.110/javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source)
	at org.jabref.merged.module@5.8.110/javafx.fxml.FXMLLoader.processStartElement(Unknown Source)
	at org.jabref.merged.module@5.8.110/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at org.jabref.merged.module@5.8.110/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at org.jabref.merged.module@5.8.110/javafx.fxml.FXMLLoader.load(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.airhacks.afterburner.views.ViewLoader.load(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.help.AboutDialogView.<init>(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.help.AboutAction.<init>(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.JabRefFrame.createMenu(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.JabRefFrame.initLayout(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.JabRefFrame.init(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.JabRefGUI.openWindow(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.JabRefGUI.<init>(Unknown Source)
	at org.jabref@5.8.110/org.jabref.gui.JabRefMain.start(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.8.110/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.8.110/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment] 2022-09-26 08:02
Thanks for the hint! This was probably caused by  #9168. Seems like the jpackage task needs an addtional tweak.

**Comment by Siedlerchr** [comment] 2022-09-27 18:09
Forget to link the issue. A fix was just merged 
Fixed by https://github.com/JabRef/jabref/pull/9183

**Closed by Siedlerchr** 2022-09-27 18:09 UTC
Labels: type: bug 🐛, build-system
