### ISSUE TITLE
can't generate bibtex for Chinese author

### ISSUE THREAD

**Issue by redleafnew** [JabRef/jabref#4169] opened 2018-07-05 07:09 UTC
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 

Steps to reproduce:

1. The rule for generate key is [auth][year] and  include Chinese authors  in author field such as 王, 阳 and 张, 家发 and 胡, 喜军 and 李, 保明
2. Ctrl+G to generate key
3. only year appear in the key.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by redleafnew** [comment] 2018-07-05 07:43
However, when the comma was removed in the author, it worked.

**Comment by redleafnew** [comment] 2018-07-10 09:56
thanks for your hard working, please let me know when the bug is fixed.

**Comment by ArrogantL** [comment] 2018-07-10 13:15
I have a question,we should split names with "and" ,why use comma？
And If the comma is Chinese comma，all goes well.

**Comment by Linzhuo16** [comment] 2018-07-10 13:44
the "and" is to distinguish between different people. the comma is used to distinguish between the first name and the last name.  and it is different from the space.  e.g. "lastname, firstname" or "firstname lastname"

**Comment by ArrogantL** [comment] 2018-07-30 06:04
Hi.I view src code carefully. The org.jabref.model.entry.AuthorListParser mainly responsible for this part.
But it seems that Jabref isdesigned for English user. Its format detection mainly apply to English.
We can use Chinese in some way but that's a coincidence.
The format detection are case sensitive. AuthorListParser use Character.isUpperCase()(line:397) to check 
however Chinese always return is-lower-case. This is the reason why Chinese name behave so strange.
And a single lastname like "A, b" wil get a warning, and "a, b" won't warn but keyGenetator ignore author and only contain year.

To resolve this question, maybe we need to rewrite AuthorListParser.

Futhermore, the problem is not only for Chinese, but also for other languages. So I think we may realize a plugin-style format detection, use Strategy Pattern.

**Comment by Siedlerchr** [comment] 2018-08-07 19:12
Thanks to @1160300208 the issues is now fixed in the latest master.

**Closed by Siedlerchr** 2018-08-07 19:12 UTC
Labels: bug, good first issue, keygenerator

**Comment by 1160300208** [comment] 2018-08-07 23:10
@redleafnew Now you can use fixed version from http://builds.jabref.org/master/

**Comment by xiaodongcentury** [comment] 2020-12-16 15:11
> thanks for your hard working, please let me know when the bug is fixed.

Hi, i am using JabRef (JabRef 5.2--2020-12-14--e9be339 Linux 5.9.0-4-amd64 amd64 Java 15.0.1) on Debian sid.
After importing the Chinese essay, manually insert a space or comma, such as 王, 阳 or 王 阳, the citationkey will generate successfully, but the Reference section of essay will display "王 阳"(there is a space between王 and 阳, not "王阳".
How could you resolve this problem, thanks!
![image](https://user-images.githubusercontent.com/20276890/102366744-f5e59a00-3ff3-11eb-9049-3bcd72bdc077.png)

**Comment by leeqifeng** [comment] 2021-07-07 07:35
> Thank you. I'll fix this bug.

nice try
