### ISSUE TITLE
Corresponding groups are sometimes not highlighted when clicking on entries

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3309] opened 2017-10-16 02:23 UTC
JabRef 4.1-dev--snapshot--2017-10-16--textendash--3bee26ead
Windows 10 10.0 amd64 
Java 1.8.0_144

Just as the following, the corresponding groups of each entry were not highlighted when clicking.

![jabref](https://user-images.githubusercontent.com/13306020/31592543-b8223fd0-b25b-11e7-91d7-6dd2ed48bb2d.gif)

**Comment by AEgit** [comment] 2017-10-16 08:20
Looks like a duplicate of https://github.com/JabRef/jabref/issues/2857 and/or https://github.com/JabRef/jabref/issues/3112

**Comment by tobiasdiez** [comment] 2017-10-16 10:43
Yes, its a duplicate of #3112 .

**Closed by tobiasdiez** 2017-10-16 10:43 UTC
Labels: groups
