### ISSUE TITLE
Fetchin article direcly to group

### ISSUE THREAD

**Issue by novak82** [JabRef/jabref#3088] opened 2017-08-09 08:50 UTC
JabRef version JabRef-4.0-dev--snapshot--2017-08-08--master--3acd1f8d0.jar on Windows 10

Steps to reproduce:

1. Select group that you want to add article in (on left side)
2. Fetch article by DOI

The article is added to selected group (the number of articles is increased by one in left table) but article is not shown in view. You have to select some other group and to came back to original group to see the fetched article.

**Comment by AEgit** [comment] 2017-08-09 12:15
Probably a duplicate of this (?):
https://github.com/JabRef/jabref/issues/1903

**Comment by lenhard** [comment] 2017-08-10 08:10
Yes, I agree. This is a specialization of #1903, hence I'll mark it as duplicate and close it. Progress will be tracked in the other issue.

**Closed by lenhard** 2017-08-10 08:10 UTC
Labels: duplicate
