### ISSUE TITLE
Downloading full texts for the whole database in JabRef v3.3 

### ISSUE THREAD

**Issue by envhyf** [JabRef/jabref#1436] opened 2016-05-22 13:17 UTC
JabRef version <3.3> on < Windows 10 >

Using JabRef v3.3, I can easily search the scientific papaer on the internet in save it into bibtex database. But when I try to download the full text for the whole database, I met some trouble.

By searching the Internet, I have been told than the LocalCopy as an external program as thethe full text downloader should be installed in the plugin ->Manage Plugins. But I can't find a way to install the .jar external program in the version 3.3(I couldn't find the plug-in option).

I use quality -> look up full texts document instead, but it seeems like I would only download one pdf per time.

So, how to download all the related files for one .bib database. Any advice would be appreciate!

**Comment by matthiasgeiger** [comment] 2016-05-23 06:36
Thanks for your report!
Plugins are no longer supported since version 3.0 - so you can't use the LocalCopy Plugin anymore.

As you already noticed the part regarding automated download for a whole database is a duplicate of #1323 - hence I close this issue here.

**Closed by matthiasgeiger** 2016-05-23 06:36 UTC
Labels: duplicate
