### ISSUE TITLE
Entry preview: error when saving new styles

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#6336] opened 2020-04-22 21:35 UTC
JabRef 5.1--2020-04-21--dc1e339
Linux 5.3.0-46-generic amd64 
Java 14.0.1

- [ x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Options/Preferences/Entry Preview
2. add some journal styles
3. hit "save".  Error popup, as shown below

![Screenshot from 2020-04-22 15-26-38](https://user-images.githubusercontent.com/762246/80036357-cefbb600-84ae-11ea-9e4e-7b7455843827.png)

and

![Screenshot from 2020-04-22 15-26-56](https://user-images.githubusercontent.com/762246/80036367-d4f19700-84ae-11ea-8ba0-8ea7815d1ac0.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment] 2020-04-23 16:51
Duplicate of #6198

**Closed by Siedlerchr** 2020-04-23 16:51 UTC
