### ISSUE TITLE
UTF8 - Korean characters not displayed in list

### ISSUE THREAD

**Issue by paulsputer** [JabRef/jabref#2503] opened 2017-01-31 15:28 UTC
Using v3.8.2 under Windows 10.

Korean characters encoded using UTF8 are shown correctly in the read-only entry preview but are not displayed in the list nor the editable entry preview.

**Comment by Siedlerchr** [comment] 2017-01-31 15:33
Refs #2500

**Comment by lenhard** [comment] 2017-02-01 07:23
@paulsputer: Could you please provide a few Korean characters or expressions that are you are having problems with? This would make testing so much easier.

**Comment by paulsputer** [comment] 2017-02-01 07:52
here we go @lenhard you can use the following lines in some of the fields.  Main fields of interest would be author, title, school and bibtexkey.  It's the whole character set that is not showing correctly when in edit mode.  They are however saved in the bibtex file correctly although some other text viewers fail to show due to JabRef not using UTF8+BOM - I can't seem to find this option

김 수한무
거북이와 두루미
삼촌갑차 동방삭

**Comment by matthiasgeiger** [comment] 2017-02-01 08:01
Mhmm... the problem is that these characters are not part of the standard font used by JabRef. If you switch for exampel to "Arial Unicode MS" (on a Windows System) the characters are properly displayed.

To change the font you need to open the `Options` -> `Preferences` -> `Appearance` dialog and hit the "Set Table font" button.

**Comment by paulsputer** [comment] 2017-02-01 08:20
Ah perfect - I was looking for that kind of option but eyes somehow missed that.

Well this is interesting, I don't seem to have _Arial Unicode MS_ but _Dialog_ works perfectly.  Yet I don't have a font called _Dialog_ installed.  It only appears in JabRef quick search and found [it is a built-in font of Java ](https://docs.oracle.com/javase/tutorial/2d/text/fonts.html) 

Perhaps this built-in font should be used as the default so that all platforms can show UTF8 characters without any config changes?

**Comment by matthiasgeiger** [comment] 2017-02-01 08:29
Interestingly "Dialog" is not showing the Korean characters at my Win10 machine :wink:

I'm not sure whether we really should touch the default configuration as - sorry - this is not an issue for most JabRef users. But I think an FAQ entry or a note in the help files that some special characters might require the change of the font should be added.

**Comment by mlep** [comment] 2017-02-01 08:31
@paulsputer In the FAQ (https://help.jabref.org/en/FAQgeneral), we have an item about Chinese characters. Is it valid for Korean too? If so, could you improve the answer, please?

**Comment by paulsputer** [comment] 2017-02-01 08:58
@matthiasgeiger how strange perhaps it has something to do with having the language specific IME installed too.  Java's logical fonts not being too logical 😆   I've tested with the CJK languages and all work though only have C & K IME's installed.  No worries, understand.

@mlep sure can do.  Is that via a pull request?

**Comment by mlep** [comment] 2017-02-01 09:06
@paulsputer . Yes. Click on the top right-hand corner of the help page. It will display the github interface. You can then edit the file by clicking on the pencil icon.

**Comment by paulsputer** [comment] 2017-02-02 20:05
Thanks opened PR JabRef/help.jabref.org/#156

**Comment by matthiasgeiger** [comment] 2017-02-02 21:37
PR is merged. Thus, this can be closed. :wink:

**Closed by matthiasgeiger** 2017-02-02 21:37 UTC
Labels: documentation
