### ISSUE TITLE
Drag and drop from one grop to another freezes Jabref

### ISSUE THREAD

**Issue by diravan** [JabRef/jabref#3102] opened 2017-08-14 09:41 UTC
JabRef version 4.0-beta2 on Ubuntu 17.04 with both openjdk and oracle JVM

Steps to reproduce:

1. Add entry to a group
2. Try to drag and drop to another group
3. Jabref freezes without anything been outputted on stdout 

I would like to add the event log but is impossible since Jabref freezes completely and even if I lunch it from terminal nothing is printed. Is just completely unresponsive until killed

**Comment by Siedlerchr** [comment] 2017-08-14 09:45
Duplicate of  #3036 
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Closed by Siedlerchr** 2017-08-14 09:45 UTC

**Comment by diravan** [comment] 2017-08-14 09:49
It works, thanks. Sorry for the duplicate, I looked before submitting somehow I missed that it was already closed.
