### ISSUE TITLE
Provide and advertise a chat for developers

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3586] opened 2017-12-28 16:11 UTC
The **bug tracker is often used as chat** (see #3382 and others), which is obviously not good.
I had a short search and found no IRC channel (or something similar), where new and old developers can simply discuss things which should not be archived together with the bug ticket.

Please create such a chat and advertise it on the related pages.

The head area of the project page would be a prominent place to advertise your chat. Even new contributors would see it:
![selection_430](https://user-images.githubusercontent.com/298682/34416788-789c85b8-ebf5-11e7-990a-2bf0d026578a.png)

**Comment by halirutan** [comment] 2017-12-28 16:31
I too prefer a chat what it comes to issues where a live discussion is helpful. We have an abandoned Gitter chat that you can find here:

https://gitter.im/JabRef/jabref

We had a similar discussion about a chat for IntelliJ Plugin Developers and there are many alternatives: Slack, Gitter, Discord, ... I much prefer Gitter because we are no large company where we need sub-channels and many features. Gitter can be used by everyone with his GitHub account. It supports markdown and has a panel for activities that happen on the repository. Screenshot sharing is as simple as dropping the image there. You can ping people or quote and reply to messages.

Everything else in Gitter is by far not as sophisticated as in Slack for instance, but it is absolutely sufficient IMO for the size fo the JabRef team.

Therefore, the answer to your question is, a chat exists and it only needs to be actively used.

**Comment by LinusDietz** [comment] 2017-12-28 17:43
https://jabref.slack.com/messages (;

**Comment by jonasstein** [comment] 2017-12-29 00:37
chat.freenode.net:6697 / non-SSL: 6667 
[irc://freenode/jabref(freenode:#jabref)
You could vote for it with thumbs up and see, which platform is most promising.

**Comment by tobiasdiez** [comment] 2017-12-29 01:03
> The bug tracker is often used as chat (see #3382 and others), which is obviously not good.

I really don't see a problem here. Most of the discussion was about the bug, how to reproduce it and where to find to find the code related to it. This is all useful information and good to have in clear connection to the issue (i.e. directly below it 😸 ). I do understand that such a discussion generates a bit of noise, but that also applies to a gitter/slack chat.

I added the slack chat to the [contributing FAQ](https://help.jabref.org/en/FAQcontributing) so that new programmers should be able to find it (yes, it is not as prominent as it could be, but should be sufficient until many new-comers break down our doors). I now play the dictator and simply close this issue 😈 .

**Closed by tobiasdiez** 2017-12-29 01:03 UTC

**Comment by halirutan** [comment] 2017-12-29 05:37
@LinusDietz @tobiasdiez Is Slack not strictly per invitation? So how is someone supposed to join the chat *easily*? 

![img](http://i.imgur.com/ByG5ucQ.png)

I don't have an email address on the `uni-stuttgart.de` server. So what is someone supposed to do?

**Comment by koppor** [comment] 2017-12-30 16:54
Just write me an email with your preferred email address and I'll invite you!

**Comment by koppor** [comment] 2017-12-30 17:00
2015, Slack was chosen instead of Gitter, because neither was hyped by the dev team and I personally have several other slacks, but no other Gitter. However, I love to see activity at https://gitter.im/JabRef/jabref. Maybe, we should point to there instead of Slack, since @halirutan and @tobiasdiez are active there? Otherwise, maybe we should point to the discourse forum? - I'll set it on the agenda of the next dev call.

**Comment by halirutan** [comment] 2017-12-31 06:21
@koppor Thank, I'll send you an email. This hurdle is exactly why I don't favor Slack beside its many features. Gitter is instantly accessible to anyone who uses GitHub, which is 100% of the people that try to contribute. JabRef doesn't have any company secrets we need to hide so it shouldn't be a problem that the chat is public.

@jonasstein I dislike IRC for something like that. In Gitter I can use markdown do quickly share code, I can drop images and we have a panel of all the issues and PR. In addition, IRC will always be a tool favored by Linux users and it might appear archaic to the unaccustomed Mac or Windows user. The access to a chat should be as easy as possible. Click and talk. I like IRC (and my `irssi`) very much but I believe for this purpose it is not the right tool.

**Comment by jonasstein** [comment] 2017-12-31 18:11
@halirutan The experience of IRC may vary with the used client. **There are clients with a GUI like Quassel** https://quassel-irc.org/image/tid/1 too. Optionally users can enter the chat via web interface https://webchat.freenode.net/ directly. It looks the same on Linux and Windows and Mac. 

I gave gitter a try two days ago. In my opinion the interface was not optimized for productivity but for eyecandy and it was difficult to find any user settings. I did not understand the multitude chat features there to embed, link and what ever do with code and external objects. The interface was like a smartphone on drugs with all objects flying around from all sides of the screen ;-). It was not clear to me, how gitter connects to github intertnally, I did not understand the data privacy agreement and it is not possible to delete an account as user. I had to ask the support to delete my account, but got no reply since then. 

I agree, that IRC is less colourful, but much easier to use and runs on all platforms. 
Please also keep in mind that you can switch some platforms easily, and others are difficult to switch, if you are not satisfied in 2 years, because the platform places annoying advertising on the website.

**Comment by koppor** [comment] 2018-01-12 13:56
Devcall decision: We discontinue our Skype Chat "JabRef developers [extended]" in favor of https://gitter.im/JabRef/jabref. We see it as try-out hoping that we won't be work-overloaded.
