### ISSUE TITLE
[Enhancement] Move the toolbar to the left

### ISSUE THREAD

**Issue by homocomputeris** [JabRef/jabref#5499] opened 2019-10-22 13:14 UTC
Somewhat relevant to #5498 

The toolbar (with the New article, New entry, Copy, Paste, etc. buttons) should stick to the right because:
1. It is the de facto standard for those who read and write left-to-right
2. It disappears (» is shown instead) in QHD when the window is _half the screen width_ (e.g. it's snapped to one side):
![jabref_where_are_the_buttons](https://user-images.githubusercontent.com/7422433/67289214-8acb3100-f4de-11e9-94d7-85f051d99b39.png)

- The latest dev version is used.
- This happens on a 2.5K 27-inch display in Linux and and a 27-inch 4K display in Windows 10
- Intel Iris Graphics 540

**Comment by AEgit** [comment] 2019-10-22 15:01
Can you specify what you mean by "toolbar"? Do you mean the groups panel? The menu buttons in the first row? The menu buttons in the second row (= toolbar in JabRef manual: see http://help.jabref.org/en/BaseFrame)?

Probably the best thing would be to provide another screenshot with the "toolbar" marked.

**Comment by homocomputeris** [comment] 2019-10-22 15:08
> The menu buttons in the second row (= toolbar in JabRef manual: see http://help.jabref.org/en/BaseFrame)?
This.

**Comment by homocomputeris** [comment] 2019-10-22 15:19
The toolbar is also hidden in Windows 10 in 4k:
<img width="960" alt="Capture2" src="https://user-images.githubusercontent.com/7422433/67301661-fff33200-f4ef-11e9-9c50-038297116b9e.PNG">
:

**Comment by AEgit** [comment] 2019-10-22 15:33
JabRef 5.0.0-dev--2019-10-21----0f0dce621
Windows 10 10.0 amd64 
Java 12.0.2

Hmmm, I have a 40' screen (3840*2160) and the complete toolbar is shown. But I remember, that I saw similar problems like you mentioned (maybe it was on my Linux installation - I don't remember) so I am not completely sure, whether your problem can or cannot be reproduced.

![Untitled](https://user-images.githubusercontent.com/12767489/67302676-2497db80-f4e9-11e9-8e31-85b78d1fae4e.png)

Having said that, though, I agree, that it is a bit annoying, that the toolbar elements do not stick together but are separated from each other (part 1: three elements + part 2: search bar + part 3: other toolbar elements). So even when the complete toolbar is shown, the way the different elements are separated from each other seems like a waster of space and forces the user to longer mouse paths to reach all the toolbar elements.

**Comment by homocomputeris** [comment] 2019-10-22 15:35
As far as I can see, your window in maximized. Snap it to one edge or just make it half of the screen's width.

**Comment by AEgit** [comment] 2019-10-22 15:37
Same window, same monitor, same resolution, but now just using 1/4 of the screen. The toolbar is still completely visible:
![quarter](https://user-images.githubusercontent.com/12767489/67303331-39c13a00-f4ea-11e9-809d-94c0ebf0553e.png)

**Comment by homocomputeris** [comment] 2019-10-22 15:41
Thanks, then it's a bug not a request.

**Comment by AEgit** [comment] 2019-10-22 15:43
Which version of JabRef are you using? It could be a Linux-only bug (maybe I will have time later on to test it on my Linux installation), but it is strange, that I cannot replicate your problem on my Windows machine when you report the same problem for Windows.
Maybe it is tied to the size of the screen? What size is your display?

**Comment by homocomputeris** [comment] 2019-10-22 15:50
> It could be a Linux-only bug (maybe I will have time later on to test it on my Linux installation)

It appears in my Windows 10.

> Maybe it is tied to the size of the screen? What size is your display?

Well, that would be strange. Might depend on GPU.

**Comment by AEgit** [comment] 2019-10-22 15:55
What JabRef version are you running on Windows 10? Go Help -> About JabRef -> Copy Version and paste it here. If you have the same version as I do, then it is really strange.

**Comment by tobiasdiez** [comment] 2019-10-22 19:50
Duplicate of #4907

**Closed by tobiasdiez** 2019-10-22 19:50 UTC
