### ISSUE TITLE
JabRef freezes when importing unlinked PDF files into Database

### ISSUE THREAD

**Issue by onewiki** [JabRef/jabref#2309] opened 2016-11-22 23:29 UTC
JabRef version  on  3.7

Steps to reproduce:

1. .Quality - Find unlinked files
2. Apply to the selected files (PDF)
3. Shows "Importing into Database" and the program freezes

```
Put the excerpt of the log file here
```

**Comment by koppor** [comment] 2016-11-23 06:46
We had a similar issue #410

**Comment by stefan-kolb** [comment] 2016-12-07 13:45
Thank you for your report :smile:
I can reproduce the behavior and we will work on a fix for this issue. Stay tuned.

**Comment by stefan-kolb** [comment] 2016-12-07 14:01
@lenhard Maybe a problem caused by the chnages in the thread executor? Code where this functionality here happens is in `FindUnlinkedFilesDialog.java` starting from line 523

**Comment by stefan-kolb** [comment] 2016-12-07 14:05
If I debug this and set a breakpoint in line 550 the dialog is enabled again afterwards, so this should be some timing problem with the threads.

**Comment by stefan-kolb** [comment] 2016-12-07 14:11
If I remove the invokeLater  commands it works for me, so there exists some scheduling problem here?
```
        JabRefExecutorService.INSTANCE.execute(() -> {
            List<String> errors = new LinkedList<>();
            creatorManager.addEntriesFromFiles(fileList, databaseContext.getDatabase(), frame.getCurrentBasePanel(),
                    entryType, checkBoxWhyIsThereNoGetSelectedStupidSwing, new ChangeListener() {

                        int counter;

                        @Override
                        public void stateChanged(ChangeEvent e) {
                            counter++;
                            progressBarImporting.setValue(counter);
                            progressBarImporting.setString(Localization.lang("%0 of %1", Integer.toString(counter),
                                        Integer.toString(progressBarImporting.getMaximum())));
                        }
                    }, errors);
            importFinishedHandler(errors);
        });
```

**Comment by lenhard** [comment] 2016-12-07 14:48
@stefan-kolb The threading changes were merged last Friday, whereas this issue was reported 15 days ago, so the changes in the threading PR cannot be the cause.

I can confirm that this is a threading issue. Sometimes the import works fine, sometimes it blocks. I does not make a difference if you execute it on the EDT (what the `SwingUtilities.invokeLater()` did) or not. It is likely a bug inside `FindUnlinkedFilesDialog`, since this class implements thread scheduling istelf (seach for `threadState`). My guess is that the class always had this issue.

Since this class is a good example of terrible engineering, a rewrite would probably be the least painful fix.

**Comment by stefan-kolb** [comment] 2016-12-13 11:41
@JabRef/developers This one is a blocker for v3.8

**Comment by stefan-kolb** [comment] 2016-12-13 11:59
For me, the first file always works. And then the second one "freezes" the dialog.

**Comment by lenhard** [comment] 2016-12-16 15:25
@stefan-kolb As discussed in private chat: no it is not.

Unfortunately, we cannot find your commit on master (or any other branch), otherwise we would have merged it. Therefore, we are moving this to 4.0

**Comment by andrewufrank** [comment] 2017-01-18 08:42
i would appreciate to be informed if there is a new fix in a new build for this problem. i am happy to run it with the debug option. i have currently JabRef-3.8.2-dev--snapshot--2017-01-16--master--9e48a5ff8.jar
. anything better to test? any workaround possible?
thank you for this feature - it will be very useful when it works reliably.

**Closed** 2017-01-20 17:34 UTC
Labels: bug, devcall

**Comment by koppor** [comment] 2017-01-20 17:38
@andrewufrank Please try again the latest build from https://builds.jabref.org/master/
