### ISSUE TITLE
Jabref 4.0 stable version is memory consuming on Windows

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3283] opened 2017-10-10 13:09 UTC
JabRef version 4.0 on Windows 10

I made `JabRef` stay open for about half day long, and it occupied more than 1GB of memory (see screenshot of memory usage). But if you close it and reopen, the memory cost is just acceptable 300MB.

![memory-jabref](https://user-images.githubusercontent.com/13306020/31388005-2c534018-adff-11e7-8fbc-ca9684420096.png)

**Comment by AEgit** [comment] 2017-10-10 13:21
Looks like a duplicate of https://github.com/JabRef/jabref/issues/3113

**Comment by lenhard** [comment] 2017-10-10 13:26
Jep, that's a duplicate.

**Closed by lenhard** 2017-10-10 13:26 UTC
