### ISSUE TITLE
JabRef steals the focus on multiple occasions

### ISSUE THREAD

**Issue by alexn11** [JabRef/jabref#977] opened 2016-03-16 15:35 UTC
- JabRef version:3.2
- Operating system and version: Arch Linux, Kernel release 4.4.5-1-ARCH (GNOME Shell 3.18.4, Java: jre8-openjdk 8.u74-1)
- Steps to reproduce:
  Two examples:
- Example 1
  1. Find and launch JabRef in Gnome application menu
  2. Go to another windows while it is loading

JabRef will steal the focus.
- Example 2
1. Launch JabRef
2. Hit F5 (web research)
3. Choose ArXiv.org in the engine list
4. Type "some text" in the search edit entry and launch the search
5. Switch to another application

After a while JabRef steals the focus from the application to display a message box reporting the failure of the request ("Malformed identifier `oai:arXiv.org:some')
1. Switch back to the other application

After a while (15-20 sec.) JabRef steals the focus from the application again to display another message box reporting the failure of the request ("Malformed identifier `oai:arXiv.org:text').

**Comment by stefan-kolb** [comment] 2016-03-20 13:36
@JabRef/developers Can someone reproduce this, so we can tag it as a bug?

**Comment by koppor** [comment] 2016-03-20 14:00
I can confirm Example 1: The opening of the JabRef main window steals the focus of another focused window. Streps to reproduce: Focus Firefox. Open command line. Enter `java -jar jabref.jar`. Press ENTER. Press ALT-TAB to switch to Firefox. Wait. JabRef opens and has the focus.

I can confirm Example 2. Once has to quickly switch to the second application **before** the window "ArXiv.org" appears:

![grabbed_20160320-145721](https://cloud.githubusercontent.com/assets/1366654/13904783/0f311c94-eeac-11e5-8b46-374e744b05b0.png)

**Comment by matthiasgeiger** [comment] 2016-03-31 09:18
Sorry... but is this really a "bug"? 

When clicking a "search" button, why should I switch to another application half a second later instead of awaiting the result of the "click"? 
And even if this might be sensible in some cases it is questionable if the quick notification that something has failed is a "feature" and not a bug :wink:

Regarding the first example: When I start JabRef using the Windows start menu it does not bring itself to the front/does not get the focus after completing the startup.

I would not put some effort in this and classify this still as an enhancement...

**Comment by lenhard** [comment] 2016-03-31 09:23
I aggree with @matthiasgeiger There is not really a functional error (== bug) here.

**Comment by oscargus** [comment] 2016-03-31 09:31
We have the FocusRequester class that is probably the cause of this
feature/bug. From my perspective the main problem with that class is the
number of warnings generated in Eclipse that an unused object is generated.
;-)

**Comment by koppor** [comment] 2016-04-08 05:44
Both example are for the impatient users: :innocent: 

Context Example 1: I have a slow machine which takes more than 10 seconds to load JabRef. In this time, I can finish a sentence in my paper or comment on a GitHub issue. I don't want to be disturbed during writing.

Context Example 2: Searching for entries sometimes takes more than 5 seconds. In this time, I can switch to Skype to my developer chat. I start typing something, but JabRef steals the focus, so my typing gets lost.

**Comment by stefan-kolb** [comment] 2017-02-22 10:42
Can this really be fixed or should it be fixed? Otherwise please let us close this for now and defer to JavaFX.

**Comment by lenhard** [comment] 2017-02-22 11:09
Agreed. It does not seem that we are attempting to work on this any time soon. I'll close it and add the on-hold label to make @koppor happy.

Let us hope that JavaFX brings some improvement here out-of-the-box.

**Closed by lenhard** 2017-02-22 11:09 UTC
Labels: enhancement, help-wanted, ui
