### ISSUE TITLE
dash should not be reported as illegal BibTeX-Key

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#6295] opened 2020-04-16 10:14 UTC
> JabRef 5.1--2020-03-23--67daf36
> Windows 10 10.0 amd64 
> Java 14

BibTeX-Key conaining dashes are reported as illegal BibTeX-Key
![Screenshot 2020-04-16 12 09 28](https://user-images.githubusercontent.com/15687581/79444408-6bb7e280-7fdb-11ea-9c28-32cca6ad8202.png)

But according to @Siedlerchr in https://github.com/JabRef/jabref/issues/4709#issuecomment-468700259
> Well, dash is a perfectly legal char in a bibtex/biblatex key: Forbidden are only these symbols: `" # % ' ( ) , = { }`

**Comment by Siedlerchr** [comment] 2020-04-16 10:47
Duplicate of #6252 and refs  #6257

**Comment by koppor** [comment] 2020-04-16 20:51
It was introduced in https://github.com/JabRef/jabref/pull/4713, and released in JabRef 5.0.

**Closed** 2020-05-06 13:27 UTC
Labels: type: bug 🐛
