### ISSUE TITLE
Cannot import non-XML preferences, cannot import BibTeX key generator preferences

### ISSUE THREAD

**Issue by jkulesza** [JabRef/jabref#2021] opened 2016-09-20 17:32 UTC
JabRef version 3.6 on Mac OSX 10.11.6

Steps to reproduce:

1. Install JabRef 3.6 in a different location than JabRef 3.5.

The Preferences -> BibTeX key generator preferences appear lost.

2. Import preferences -> browse to preferences location.
3. Select file format: "All Files" and the format does NOT change (it remains XML file).

Renaming my preferences file from jabref.prefs to jabref.prefs.xml allows it to be selected/imported and I am told to restart JabRef for changes to take effect.  When I restart, the BibTeX key generator preferences have not been changed.

**Comment by matthiasgeiger** [comment] 2016-09-21 07:16
I'll have a look.

**Comment by matthiasgeiger** [comment] 2016-09-24 18:14
The keypattern part should be fixed for version 3.6... (see #1704) 

@jkulesza Are you using the "portable mode" of JabRef, i.e., your prefs are always saved in an XML file?

Normally JabRef 3.6 should automatically use (and convert) the preferences from earlier versions without manual import as the prefs are stored in a system file/registry.

**Comment by jkulesza** [comment] 2016-09-24 19:15
@matthiasgeiger, No, I'm not (knowingly) using JabRef in "portable mode."  I originally installed it, imported my saved preferences (exported on another computer), and then they are loaded on each launch with no action on my part.  Only after performing the upgrade did I have a problem.

From your comment, it seems like everything "should just work." However, I assure you that things are as I reported.  What can I do to test / help you debug (I'll be in my office tomorrow to try whatever you suggest)?

**Comment by matthiasgeiger** [comment] 2016-09-26 14:59
Okay I was able to solve the problem regarding the automatic preference migration. This is now fixed in the current development builds. 

However, this automatic conversion is only performed once (at the first startup of JabRef 3.6 or 3.7dev) - so it will not be executed for you @jkulesza 

**Please make a backup before any changes** and if you have any trouble please upload the prefs file here or send it us privately to developers@jabref.org. 

To reenable the automatic migration you'll have to remove a "node" in the preferences stored at `~/Library/Preferences/` - there should be a JabRef related file (sorry I don't have a Mac and I don't know how exactly the file is named). In this file you'll have to remove the `\net\sf\jabref\bibtexkeypatterns` entry (again I do not exactly know how this is stored at your Mac)

Note for windows users: Remove the node `HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\net\sf\jabref\bibtexkeypatterns` using `regedit` to reenable the automatic migration

**Comment by matthiasgeiger** [comment] 2016-09-26 15:05
Ah... regarding your second problem: Changing the filefilter from `*.xml` to `All files` is working for me... Is this problem specific for the preferences import dialog or are all file dialogs affected? (e.g. "File" -> "import into current database")

**Comment by jkulesza** [comment] 2016-09-28 21:01
@matthiasgeiger Sorry for the slow reply; I've been away at a conference.

I've downloaded and installed:
 JabRef 3.7dev--snapshot--2016-09-28--master--555944f
mac os x 10.11.6 x86_64 
Java 1.8.0_102

Some remarks:

1. For other users' reference, opening $HOME/Library/Preferences/net.sf.jabref.plist within Xcode and removing the entry cited (bibtexkeypatterns) allowed the preferences to be brought in.  Thank you!
2. Changing from *.xml to All Files appears to only be an issue within the preferences.  When I try File -> Import into Current Database, I can change file types as expected.  Are there other dialogs I can test against?
3. Renaming my preferences file to ...xml and importing still does not work (though, with Point #1, this is moot).

**Comment by jkulesza** [comment] 2016-09-28 21:25
It's worth noting that I can also not *export* my preferences in a format other than XML.

**Comment by matthiasgeiger** [comment] 2016-09-29 08:12
Well... The content of the preferences file is always XML-Code - so exporting it only as an XML file is sensible. However, import should be possible regardless of the file extension I think...

@Siedlerchr and @stefan-kolb: Can you investigate the file dialog problem? Should be caused by #1771, #1774 or #1737

**Comment by stefan-kolb** [comment] 2016-09-29 08:31
I cannot reproduce this behavior on the current `master`. Import and export is working as expected.

**Comment by matthiasgeiger** [comment] 2016-09-29 08:40
Mac specific problem? 
@chochreiner Can you reproduce this one? :wink:

**Comment by Siedlerchr** [comment] 2016-09-29 09:19
Regarding the file dialog, I am not sure, but I think that only XML is set as File Filter. Not sure if you can switch to All files.

**Comment by stefan-kolb** [comment] 2016-09-29 09:20
You can, I tested it.

**Comment by chochreiner** [comment] 2016-09-29 10:15
I can reproduce this bug on MacOS 10.12 on the master

**Closed** 2016-10-14 08:52 UTC
Labels: keygenerator, waiting-for-feedback
