### ISSUE TITLE
web search: MathSciNet error (network error?) 

### ISSUE THREAD

**Issue by the-dino-girl** [JabRef/jabref#10261] opened 2023-08-31 16:30 UTC
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to web search
2. Select MathSciNet 
3. Enter any search term e.g. "dinosaur"
4. The following error occurs

![afbeelding](https://github.com/JabRef/jabref/assets/143431619/8e44a91d-7490-49ed-9526-3b25ac5706d1)

When you want to search on the website https://mathscinet.ams.org/mathscinet/publications-search
there is an account asked to log in. Is this causing the network error maybe?

Problem present in:

JabRef 5.10--2023-08-30--c303db5
Windows 10 10.0 amd64 
Java 21-internal 
JavaFX 20+19

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by calixtus** [comment] 2023-08-31 19:15
Duplicate of #10025 

Please check an issue first with the latest development version. Should just be fixed yesterday.

**Closed by calixtus** 2023-08-31 19:15 UTC
