### ISSUE TITLE
Many NullPointerExceptions shown on the console when running find duplicates

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#4271] opened 2018-08-15 10:25 UTC
- [x ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version  on 
Using JabRef-5.0-dev--snapshot--2018-08-14--master--7d4b2ae0f.jar

Steps to reproduce:

1. Start jabref
2. Click "Find duplicates"
3. Watch one exception after the other appear on the console

<details>
  <summary>Log File</summary>
  
  ```
12:23:17.505 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.mergeentries.MergeEntries.updateAll(MergeEntries.java:443) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.initialize(MergeEntries.java:206) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.<init>(MergeEntries.java:113) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.init(DuplicateResolverDialog.java:70) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.<init>(DuplicateResolverDialog.java:50) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.askResolveStrategy(DuplicateSearch.java:126) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.lambda$verifyDuplicates$1(DuplicateSearch.java:118) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.DefaultTaskExecutor.lambda$runAndWaitInJavaFXThread$0(DefaultTaskExecutor.java:74) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
12:23:21.645 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.mergeentries.MergeEntries.updateAll(MergeEntries.java:443) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.initialize(MergeEntries.java:206) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.<init>(MergeEntries.java:113) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.init(DuplicateResolverDialog.java:70) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.<init>(DuplicateResolverDialog.java:50) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.askResolveStrategy(DuplicateSearch.java:126) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.lambda$verifyDuplicates$1(DuplicateSearch.java:118) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.DefaultTaskExecutor.lambda$runAndWaitInJavaFXThread$0(DefaultTaskExecutor.java:74) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
12:23:24.986 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.mergeentries.MergeEntries.updateAll(MergeEntries.java:443) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.initialize(MergeEntries.java:206) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.<init>(MergeEntries.java:113) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.init(DuplicateResolverDialog.java:70) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.<init>(DuplicateResolverDialog.java:50) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.askResolveStrategy(DuplicateSearch.java:126) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.lambda$verifyDuplicates$1(DuplicateSearch.java:118) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.DefaultTaskExecutor.lambda$runAndWaitInJavaFXThread$0(DefaultTaskExecutor.java:74) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
12:23:25.492 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.mergeentries.MergeEntries.updateAll(MergeEntries.java:443) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.initialize(MergeEntries.java:206) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.<init>(MergeEntries.java:113) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.init(DuplicateResolverDialog.java:70) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.<init>(DuplicateResolverDialog.java:50) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.askResolveStrategy(DuplicateSearch.java:126) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.lambda$verifyDuplicates$1(DuplicateSearch.java:118) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.DefaultTaskExecutor.lambda$runAndWaitInJavaFXThread$0(DefaultTaskExecutor.java:74) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
12:23:25.662 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.mergeentries.MergeEntries.updateAll(MergeEntries.java:443) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.initialize(MergeEntries.java:206) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.<init>(MergeEntries.java:113) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.init(DuplicateResolverDialog.java:70) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.<init>(DuplicateResolverDialog.java:50) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.askResolveStrategy(DuplicateSearch.java:126) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.lambda$verifyDuplicates$1(DuplicateSearch.java:118) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.DefaultTaskExecutor.lambda$runAndWaitInJavaFXThread$0(DefaultTaskExecutor.java:74) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
12:23:26.320 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.mergeentries.MergeEntries.updateAll(MergeEntries.java:443) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.initialize(MergeEntries.java:206) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.<init>(MergeEntries.java:113) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.init(DuplicateResolverDialog.java:70) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.<init>(DuplicateResolverDialog.java:50) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.askResolveStrategy(DuplicateSearch.java:126) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.lambda$verifyDuplicates$1(DuplicateSearch.java:118) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.DefaultTaskExecutor.lambda$runAndWaitInJavaFXThread$0(DefaultTaskExecutor.java:74) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
12:23:28.609 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.mergeentries.MergeEntries.updateAll(MergeEntries.java:443) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.initialize(MergeEntries.java:206) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.<init>(MergeEntries.java:113) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.init(DuplicateResolverDialog.java:70) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.<init>(DuplicateResolverDialog.java:50) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.askResolveStrategy(DuplicateSearch.java:126) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.lambda$verifyDuplicates$1(DuplicateSearch.java:118) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.DefaultTaskExecutor.lambda$runAndWaitInJavaFXThread$0(DefaultTaskExecutor.java:74) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
12:23:29.016 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
	at org.jabref.gui.mergeentries.MergeEntries.updateAll(MergeEntries.java:443) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.initialize(MergeEntries.java:206) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.mergeentries.MergeEntries.<init>(MergeEntries.java:113) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.init(DuplicateResolverDialog.java:70) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateResolverDialog.<init>(DuplicateResolverDialog.java:50) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.askResolveStrategy(DuplicateSearch.java:126) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.DuplicateSearch.lambda$verifyDuplicates$1(DuplicateSearch.java:118) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.DefaultTaskExecutor.lambda$runAndWaitInJavaFXThread$0(DefaultTaskExecutor.java:74) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_172]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
...
...
  ```
</details>

**Comment by tobiasdiez** [comment] 2018-08-15 10:53
Duplicate of #4233

**Closed by tobiasdiez** 2018-08-15 10:53 UTC
