### ISSUE TITLE
Error logged after adding new entry if autosave is disabled

### ISSUE THREAD

**Issue by jmkeil** [JabRef/jabref#4466] opened 2018-11-07 12:22 UTC
JabRef version JabRef-5.0-dev--snapshot--2018-11-06--master--5548f8f04 on Windows 8.1

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. disable autosave
2. create a new library
3. save the new library using "save as" (filename test.bib)
    * file created (as expected)
4. add an entry
    * error (see details) appears on console (not expected)
5. save the library again using "save"
    * file updated (as expected)
    * test.bib.sav appears
    * test.bib.bak appears

<details>
  <summary>Log File</summary>
  
  ```
  13:16:16.926 [pool-7-thread-1] ERROR org.jabref.logic.autosaveandbackup.BackupManager - Error while saving to fileE:\test.bib.sav
java.nio.file.AccessDeniedException: E:\test.bib.sav.bak
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source) ~[?:1.8.0_191]
	at java.nio.file.Files.deleteIfExists(Unknown Source) ~[?:1.8.0_191]
	at org.jabref.logic.exporter.AtomicFileOutputStream.close(AtomicFileOutputStream.java:209) ~[JabRef-5.0-dev--snapshot--2018-11-06--master--5548f8f04.jar:?]
	at sun.nio.cs.StreamEncoder.implClose(Unknown Source) ~[?:1.8.0_191]
	at sun.nio.cs.StreamEncoder.close(Unknown Source) ~[?:1.8.0_191]
	at java.io.OutputStreamWriter.close(Unknown Source) ~[?:1.8.0_191]
	at org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(BibDatabaseWriter.java:204) ~[JabRef-5.0-dev--snapshot--2018-11-06--master--5548f8f04.jar:?]
	at org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(BibDatabaseWriter.java:143) ~[JabRef-5.0-dev--snapshot--2018-11-06--master--5548f8f04.jar:?]
	at org.jabref.logic.autosaveandbackup.BackupManager.performBackup(BackupManager.java:124) ~[JabRef-5.0-dev--snapshot--2018-11-06--master--5548f8f04.jar:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_191]
	at org.jabref.logic.autosaveandbackup.BackupManager.lambda$new$1183(BackupManager.java:49) ~[JabRef-5.0-dev--snapshot--2018-11-06--master--5548f8f04.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
  ```
</details>
<details>
  <summary>test.bib</summary>
  
  ```
% Encoding: UTF-8

@Article{,
  timestamp = {2018-11-07},
}

@Comment{jabref-meta: databaseType:biblatex;}

  ```
</details>
<details>
  <summary>test.bib.sav</summary>
  
  ```
% Encoding: UTF-8

@Article{,
  timestamp = {2018-11-07},
}

@Comment{jabref-meta: databaseType:biblatex;}

  ```
</details>
<details>
  <summary>test.bib.bak</summary>
  
  ```
% Encoding: UTF-8

@Comment{jabref-meta: databaseType:biblatex;}

  ```
</details>

**Comment by Siedlerchr** [comment] 2018-11-07 12:42
Do you have autosave enabled? Might be a Duplicate of #4352

**Comment by jmkeil** [comment] 2018-11-07 13:07
Autosave was disabled. Enabling autosave causes other similar errors in the log.

However, I notices, that the log entry already appears after creating the new entry and before "save as".

**Comment by Siedlerchr** [comment] 2019-01-03 14:56
I can no longer reproduce this. 
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2019-01-03 14:56 UTC

**Comment by jmkeil** [comment] 2019-01-16 09:10
I have retested it with JabRef-5.0-dev--snapshot--2019-01-13--master--a051e1b08.jar and was not longer able to reproduce this. Thank you.
