### ISSUE TITLE
Import: only one entry imported from a pubmed-export-file 

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#1267] opened 2016-04-21 04:50 UTC
JabRef version <2.10b2> on <Kubuntu 14.04.3 LTS 32bit>

Steps to reproduce:

1. Expoort some entrys from Pubmed with "Send to" -> "File" -> "Format: MEDLINE" (should be kind of RIS-format I think)
2. Use "Import into new database" with "Format: RIS" or "Format: All Types"

Only the first entry of this file is used for JabRef. All other entries are ignored.

**Comment by koppor** [comment] 2016-04-21 06:57
@mairdl Since you work on Medline (#547), could you create a test case and test whether this issue is still valid in JabRef 3.3 / current development version?

**Comment by mairdl** [comment] 2016-04-21 09:56
i will give it a try for sure.

Note: There's a typo in the headline

**Comment by stefan-kolb** [comment] 2016-05-19 09:18
Whats the current status for this issue?

**Comment by mairdl** [comment] 2016-06-06 09:57
I tried to recreate the bug, but it wasn't possible. I think i could add a file to the RISImporterTest that would prove it.

**Comment by koppor** [comment] 2016-06-06 21:32
@tschechlovdev Is currently rewriting the Medline importer using JAX-B instead of self-written parsing. Reason: the StAX-based parsing at #1479 was also difficult and there is some XSD for the medline things available.

**Comment by mairdl** [comment] 2016-06-29 11:58
This bug couldn't be reproduced, also @tschechlovdev is revising the MedlineImporter. I'd suggest to close this issue.

**Comment by matthiasgeiger** [comment] 2016-06-29 12:22
I think the problem is that there are at least two different medline formats. Our "Medline" and "Medline Plain" importer used in JabRef expects an XML format. However, if you export in MEDLINE format [at pubmed](http://www.ncbi.nlm.nih.gov/pubmed/?term=some+obscure+disease) you'll get something like [this](https://www.nlm.nih.gov/bsd/disted/pubmedtutorial/030_080.html) (as @buhtz has said this looks more like a RIS dialect) - and yes, if such a file contains more than one entry only the first one gets imported. But this is not a problem of the medline, but of the RIS importer which handles this incorrectly.

**Comment by matthiasgeiger** [comment] 2016-06-29 12:25
@buhtz However, to solve you problem you have to change your workflow slightly: If you export not to "medline" but to "XML" format you'll be able to import more than one entry correctly using the "Medline" or "All Formats" importer.

**Comment by mairdl** [comment] 2016-07-04 11:41
I tested the RISImporter if it only imports one entry, but it correctly imports all entries. The RISImporter seems to work fine. I talked to @obraliar about the RISImporter and he mentioned that there is no "Medline RIS" format.

**Comment by koppor** [comment] 2016-07-16 14:53
@mairdl: Is there a test case for the importing of all entries? -> Please provide a reference.

@mairdl: @matthiasgeiger Provided a reference to a file at https://github.com/JabRef/jabref/issues/1267#issuecomment-229340023. Is a variant (with pseudo abstract field - if there is an abstract) of that file tested?

:+1: for renaming. @zellerdev Could you do that? And probably dive into the difference issue again. I think @tschechlovdev started a comparison and could provide some insights at http://help.jabref.org, since not every user is familiar with the different formats.

**Comment by zellerdev** [comment] 2016-07-21 16:53
When using the current Version of JabRef (3.5) the issue shouldn't be reproducible. Because it is not possible to import a .txt file with the RIS importer anymore.
Furthermore, you selected "MEDLINE" as the format. So you should use MedlinePlain to import the file. Unfortunately, there is a bug hidden in the MedlinePlain importer. See #1612 for more details. We are working on it.

**Closed** 2016-08-03 12:04 UTC
Labels: stupro
