### ISSUE TITLE
Entry is not being generated from DOI

### ISSUE THREAD

**Issue by jamal919** [JabRef/jabref#2898] opened 2017-06-09 08:14 UTC
JabRef version 3.8.2 on Windows 8.1 and CentOS 7.1

Steps to reproduce:

1. Add a new entry
2. ID based entry generator
3. ID Type "DOI" and give a DOI - say 10.1007/s00704-014-1101-7
4. Press Generate

An error message appear saying - "Error while fetching from DOI. Invalid URL".

I usually add entry by pasting the DOI in the main window. This feature is broken also. 

Tested with a bunch of DOIs, same result every time. DOI url opens fine in the web browser. The feature got broken without any update, so I guess it has something to do with the DOI service.

**Comment by tobiasdiez** [comment] 2017-06-09 08:29
This should be fixed in the [current development version](http://builds.jabref.org/master/). Please be aware that this version of JabRef is still has some rough edges and thus it is recommended to make a backup of your database.

**Comment by ninfito** [comment] 2017-06-10 19:52
If you do not want to use dev-version, try `www.doi2bib.org` until version 3.8.x can be updated.

**Comment by AEgit** [comment] 2017-06-11 10:22
Alternatively you can use JabFox:
https://addons.mozilla.org/en-US/firefox/addon/jabfox/

**Comment by moritzlell** [comment] 2017-06-13 13:59
This looks like a duplicate of #2879. It has been fixed for 4.0.0. See [this pull request](https://github.com/JabRef/jabref/pull/2889). There, a fix is mentioned for 3.8.2 also, which is replacing the class DOI.java by a version provided there.

**Closed** 2017-08-10 12:04 UTC
Labels: bug, fixed-in-devBuilds

**Comment by jamal919** [comment] 2017-08-31 05:40
Thanks @ninfito and @AEgit . I was out of the network for some time. Anyway, doi2bib and google scholar are two services which I am using currently. I have a large repository of unsorted journal papers, and I wanted to sort them out. This doi feature helped me a lot with it. I am really waiting for the next release build.

**Comment by matthiasgeiger** [comment] 2017-08-31 06:48
Hi @jamal919 !
If you don't want to wait you can also use the beta3 version we released two weeks ago: https://github.com/JabRef/jabref/releases/tag/v4.0-beta3

We won't add any more features until the version 4.0 release - and the overall stability should also be acceptable. The only important aspect is, that with 4.0 there are some changes in the group storage, which are not backwards compatible. That means, that after saving your bib database with a 4.0beta version you won't be able to see the groups in older 3.X versions.
