### ISSUE TITLE
Entries with hash symbos ('#') are processed incorrectly

### ISSUE THREAD

**Issue by sauliusg** [JabRef/jabref#7553] opened 2021-03-20 12:29 UTC
JabRef version 5.3, master commit 049acb9e9 on Linuxmint-20.1

JabRef 100.0.0
Linux 5.8.0-45-generic amd64 
Java 14.0.2 
JavaFX 16+8

- [x ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When a new entry is created that contains two hash symbols ('#') and a comma between them, such entry when saved produces incorrect bibtex file that can not be parsed again.

1. Start a new JabRef process (my JabRef is configured not to open old libraries, so the window is empty);
2. Create a new database and a new entry in it;
3. In the "Abstract" tab of the new entry, type the following text: `This is an article about C# programs. It has a comma between the two hashes, and mentions C# for the second time.`;
4. Save the new library as 'new.bib' (a variant of this file is provided in the attached .zip);
5. Close the JabRef;
6. Open JabRef, passing the saved file name on the command line, e.g. `./gradlew run --args ~/src/jabref/bugs/entries-with-hashes-are-processed-incorrectly/new.bib`. The file triggers a syntax error message:
![Screenshot from 2021-03-20 13-09-31](https://user-images.githubusercontent.com/10668420/111869205-e2e1bd80-8986-11eb-8484-dc68e2ed6f14.png)
7. Alternatively, start JabRef without a command line argument and open the saved 'new.bib' library using 'File|Open...' dialog. No error message is produced, but the entry is silently skipped:
![Screenshot from 2021-03-20 13-17-41](https://user-images.githubusercontent.com/10668420/111869244-17ee1000-8987-11eb-8aca-0a151e7adabd.png)
8. The comma between two hashes influences the behaviour; if we delete the comma (see 'new-without-comma.bib' in the submitted 'biblio.zip' file), the error is not triggered but the entry is parsed incorrectly:
![Screenshot from 2021-03-20 13-16-10](https://user-images.githubusercontent.com/10668420/111869304-61d6f600-8987-11eb-92f2-7312cb7e60e8.png)
9. In a somewhat different setting, when reading old entries (produced by older JabRef versions, or by external software) that contain hashes, a similar parsing bug is triggered if the entry is modified before saving. Sometimes the modification happens silently, e.g. when the old entry contains 'timestamp' fields (see 'Wilkinson2006.bib' in the attached 'biblio.zip', which, when read in and just saved as 'Wilkinson2006-saved.bib', can not be read back correctly and triggers parsing error when specified on the command line). 

An unexpected corruption of the database when automatically changing time stamps is yet another argument against automatically converting them to 'creationdate' fields, in addition to problems mentioned in the issue #7527.

Below are short BibTeX files used for testing:

[biblio.zip](https://github.com/JabRef/jabref/files/6175527/biblio.zip)

The issue might be related to #7010.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment] 2021-03-21 19:21
This is a duplicate of #7010. JabRef tries to interpret # as bibtex macro

**Closed by Siedlerchr** 2021-03-21 19:21 UTC

**Comment by sauliusg** [comment] 2021-03-22 06:32
> This is a duplicate of #7010. JabRef tries to interpret # as bibtex macro

The #7010 reports that a markdown disappears from comments, which is not nice but you an still live with it. In the #7553 I reported *corruption* of the database, which is IMHO much more serious.

Of course if fixing #7010 will also fix #7553, all the better :)
