### ISSUE TITLE
the left column size is too large after exiting from full windows (after resize the window)

### ISSUE THREAD

**Issue by digdig** [JabRef/jabref#5920] opened 2020-02-04 14:27 UTC
JabRef version  on 

JabRef 2020-02-04 windows version

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1.  open jabref
2.  resize the window by click the second button on the top right corner(resize button)
3.  see the effects of the left column

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment] 2020-02-04 14:37
Duplicate of #5872

**Closed by Siedlerchr** 2020-02-04 14:37 UTC
