### ISSUE TITLE
The import window in Windows does give rise to a separate item in the task bar

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4304] opened 2018-08-30 14:38 UTC
all JabRef versions so far

Steps to reproduce:

1. Open Jabref in Windows
2. Type something in the search window (Medline/Pubmed) and start the search
3. The search window opens but the taskbar doesnot indicate a second Jabref window. This is different from the "About JabRef" window which shows such a second item. 

Such a feature would be very welcome when importing e.g. via JabFox. In previous versions the import window did not get the focus of the display but remained in the background. Showing that there would be an extra window would enable to target this window by clicking the item, and one would not have to search via alt-tab.

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment] 2018-08-30 14:41
The import inspection window is still an old swing dialog which is not yet converted. There are still a couple of dialogs to convert. See #3861

**Comment by tobiasdiez** [comment] 2018-08-30 15:47
This will be resolved as soon as the other dialogs are converted to JavaFX (and this is the only way to fix this issue). Hence I'll close as duplicate of https://github.com/JabRef/jabref/issues/3861.

**Closed by tobiasdiez** 2018-08-30 15:47 UTC
Labels: build-system, enhancement
