### ISSUE TITLE
New entry in subgroup is not shown

### ISSUE THREAD

**Issue by mpele** [JabRef/jabref#3793] opened 2018-03-02 11:10 UTC
JabRef version JabRef-4.2-dev--snapshot--2018-02-28--master--2b5815b83.jar

Steps to reproduce:

1. Select existing group
2. Add new entry by using dialog (Ctrl-N)

The new entry is added to group, the number is of items in subgroup is increased, but the entry is not shown in the main table. New entry is visible after selecting some other group and reselecting the first group.

**Comment by Siedlerchr** [comment] 2018-03-02 16:06
This should be fixed in the latest development version. Could you please check the build from https://builds.jabref.org/maintable-beta/. Thanks! Note this version is in a very early beta stage and might not work as expected. See #3621 for further details.

**Comment by AEgit** [comment] 2019-09-08 13:20
JabRef 5.0-dev
Linux 5.0.0-27-generic amd64 
Java 1.8.0_222

I cannot reproduce this issue. I reckon, this has been fixed as suggested by @Siedlerchr .

**Closed** 2019-09-08 13:24 UTC
Labels: waiting-for-customer-feedback
