### ISSUE TITLE
Low loading/searching-as-you-type performance with large (1000+ entries) DBs

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#6044] opened 2020-02-28 17:50 UTC
JabRef 5.0-pull-5945-merge.440--2020-02-19--fcaeef1
Linux 5.4.19-050419-generic amd64 
Java 13.0.2

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open a large BIB file (say 1000-2000+ entries)
2. You might have to wait up to 2-3 seconds. The issue gets a real one once you have 5-6 files from the last session that altogether form several 1000 entries to be loaded.
3. Type keyword into search field, you might be required to wait a bit after each letter entered

Loading a larger DB (1000+ entries) takes unusually long (even on my i7 8th gen laptop).
JR5 to me shows to be significantly slower than JR3/4, which was faster even on my old machine, an i7 4th gen. This way, search renders to be difficult to use because typed-in letters don't show in the text field before the search procedure has returned.

JabRef 3/4 still had the option to enter the search term and hit enter to start the search.

Hence, it would be highly useful to at least have a switch to toggle between "old-school" and "as-you-type" search.

My observation might be linked to [that issue](https://github.com/JabRef/jabref/issues/5071).

**Comment by AEgit** [comment] 2020-02-29 18:26
As mentioned by @ytzemih this might be a duplicate of:
https://github.com/JabRef/jabref/issues/5071

See also https://github.com/JabRef/jabref/issues/5735 and https://github.com/JabRef/jabref/issues/5510#issuecomment-590564792 for possibly related performance problems.

**Closed** 2020-04-12 11:37 UTC
Labels: search, t: performance, ui

**Comment by tobiasdiez** [comment] 2020-04-12 11:40
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by ytzemih** [comment] 2020-04-13 17:54
@tobiasdiez Thanks for the fix. I tried 
JabRef 5.1--2020-04-12--771af5d
Linux 5.4.19-050419-generic amd64 
Java 14
with a file having >3500 entries and search-as-you-type works now much more smoothly.
