### ISSUE TITLE
Entry Editor removes entries when in souce-code-field

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#4764] opened 2019-03-15 15:23 UTC
JabRef version 5.0-dev on Ubuntu 18.04

JabRef 5.0-dev--snapshot--2019-03-15--master--7ed15bc4a
Linux 4.15.0-46-generic amd64 
Java 1.8.0_201

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open [4764.bib](https://github.com/JabRef/jabref/files/2840910/4633.bib.txt)
2. double click on "Rechnergestütze Simulation von Anfahrversuchen nach EN 1317"
3. go to "BibTeX-source code" (in the newest dev-version be aware of the workaround [#4762#issue-421323351](https://github.com/JabRef/jabref/issues/4762#issue-421323351), but "my bug" also ocours in a february-version)
4. click anywhere into the source-code-field
5. click on "Misc"-"DNA-Dennis"-"CoulombsLaw.svg pblished under CC-BY 3.0"
6. save
7. check [output.bib.txt](https://github.com/JabRef/jabref/files/2971747/output.bib.txt)  (the "Misc"-"DNA-Dennis"-"CoulombsLaw.svg pblished under CC-BY 3.0" disapeared)

<details>
<summary>Detail information:</summary>

```
Can only load style files: Preview
Can only load style files: Preview
Can only load style files: Preview
Can only load style files: Preview
Can only load style files: Preview
```

</details>

<details>
  <summary>Terminal</summary>

`java -jar -Djavafx.embed.singleThread=true /home/jkalliau/prgm/JabRef/JabRef--master--latest.jar 4633.bib `
  
  ```
16:17:39.557 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: 4633.bib
16:17:39.803 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/jkalliau/ownCloud/PhDJK/LaTeX/Style/LiteratureJK.bib
16:17:40.907 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
16:17:40.982 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
16:17:47.312 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Can only load style files: Preview
  ```
</details>

**Comment by Siedlerchr** [comment] 2019-03-16 11:45
Confirmed: when I click in the source field and then select another entry in the table, the bib entry codes changes to  the first selected one.
Log informs about autosave:
```
12:44:23.668 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.706 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.717 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.737 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.749 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.797 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.808 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.820 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.838 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.879 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.928 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.952 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:23.994 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.060 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.077 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.140 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.175 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.380 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.402 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.653 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.710 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
12:44:24.725 [JavaFX Application Thread] DEBUG org.jabref.logic.autosaveandbackup.BackupManager - Rejecting while another backup process is already running. -  
```

**Comment by CaptainDaVinci** [comment] 2019-03-16 20:15
I think this is because when the `sourceTab` is out of focus (when another entry is selected), the [storeSource](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/entryeditor/SourceTab.java#L166) is called with the previous _sourceText_ but the `currentEntry` is updated with the second entry and the field values of first one are copied.

**Comment by Siedlerchr** [comment] 2019-03-28 08:05
Thanks to @CaptainDaVinci  this should be fixed in the latest master.  https://builds.jabref.org/master

**Closed** 2019-03-28 08:04 UTC
Labels: bug, entry-editor, ui
