### ISSUE TITLE
Should JabRef run on a single instance?

### ISSUE THREAD

**Issue by instantname** [JabRef/jabref#3534] opened 2017-12-15 03:30 UTC
When double-clicking on a .bib file to open it (with JabRef, of course), if another instance of JabRef is running, an new instance will be started. This is particularly annoying because when the "Open last edited databases at startup" option is checked, double-clicking on the .bib file will reopen many other databases. There are two problems I see with that behavior. First, in the second instance, it can potentially display "Backup file found" of databases that are other than the one the user tries to open (because of .bak files created by the first instance). Second, having the same databases open in multiple instances of JabRef is a recipe for disaster overwriting of changes.

Perhaps, double-clicking on a file should open that file in the already running JabRef instance. Or, at least, double-clicking on a file should not reopen all other databases.

Jabref version 3.8.2, Windows 10

**Comment by tobiasdiez** [comment] 2017-12-15 08:41
There exists an option in the "Advanced" tab in the preferences to enable single-instance-mode.

@JabRef/developers Should we enable this setting by default?

**Comment by lenhard** [comment] 2017-12-15 08:50
That option is already enabled by default:
https://github.com/JabRef/jabref/blob/d6c7241dd534b08e6a77c7387a9a7970966de955/src/main/java/org/jabref/preferences/JabRefPreferences.java#L714

So either @instantname disabled it (then this issue is invalid) or there's a bug (then we need a description on how to reproduce it). If I double-click a second bib file it opens in the already running JabRef instance as it should, so I don't see a bug for now.

**Comment by instantname** [comment] 2017-12-17 01:31
As @tobiasdiez suggested, the box to check if other instances are not running was disabled. I am however not sure if I unchecked it myself.

**Comment by matthiasgeiger** [comment] 2017-12-17 08:52
If you are an longterm user the preference might have been disabled because you already had the setting to "disabled" before we changed the default value to "enabled"...

However, does it work now as expected @instantname?

**Comment by instantname** [comment] 2017-12-17 09:45
@matthiasgeiger Yes, it is true I have updated my JabRef installation many times. To be sure, that everything works fine on a fresh install, can you let me know where the preferences are stored (on Windows) so that I can test what happens when I delete them?

**Comment by matthiasgeiger** [comment] 2017-12-17 13:15
The preferences are stored in the Windows Registry. Thus, you should be careful and know what you do!

In order to manually delete the preferences you need to remove the node `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\org\jabref` from the registry (there might also be another node from older version which should be removed, too: `Computer\HKEY_CURRENT_USER\Software\JavaSoft\Prefs\net\sf\jabref`)

![grafik](https://user-images.githubusercontent.com/676652/34079771-9466e38e-e334-11e7-89e0-e501b074e49a.png)

If you do not want to mess with the Windows registry, you can also reset the preferences to the defaults in the JabRef preferences dialog: 

![grabbed_20171217-141440](https://user-images.githubusercontent.com/676652/34079779-af547864-e334-11e7-83ca-3bdfe7c8834f.png)

**Comment by instantname** [comment] 2017-12-18 00:59
I had both the old and new registry folders. Deleting them gives the intended behavior (a single instance), so I don't think there is any issue. Thanks for your help.

**Comment by halirutan** [comment] 2017-12-18 02:22
I'm closing it then.

**Closed by halirutan** 2017-12-18 02:22 UTC
Labels: question, waiting-for-feedback
