### ISSUE TITLE
URL/Eprint/DOI - Dropdown in main table not working

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#7803] opened 2021-06-07 13:19 UTC
```
JabRef 5.3--2021-06-07--62969da
Linux 5.11.22-100.fc32.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8
```

- [ x ] I have tested the latest development version from http://builds.jabref.org/main and the problem persists

1. open [Bug.bib.txt](https://github.com/JabRef/jabref/files/6609139/Bug.bib.txt)
2. click on the linked identifier of the article
3. in about 8 out of 9 cases it opens the URL(wrong), otherwise it opens the dropdown-menu (right)

However the dropdown for the linked files seems to always work.

**Comment by mlep** [comment] 2021-06-07 14:06
I can confirm this bug: a left click opens the URL.
The drop-down menu is displayed for a very short time. This does not allow for selecting one of the identifiers.

JabRef 5.3--2021-06-07--62969da
Linux 4.19.0-16-amd64 amd64 
Java 16.0.1 
JavaFX 16+8

**Comment by Siedlerchr** [comment] 2021-06-13 20:01
I can confirm this issue also on mac

**Comment by JoKalliauer** [comment] 2021-07-16 18:12
I can confirm this issue also on Win 11

```
Edition	Windows 11 Home
Version	21H2
Installiert am	‎16.‎07.‎2021
Betriebssystembuild	22000.71
Leistung	Windows Feature Experience Pack 421.18201.0.3
```

![JabRef](https://user-images.githubusercontent.com/15687581/125991149-c7f34104-66f2-4068-b42b-3c2a73057dd0.png)

**Comment by LIM0000** [comment] 2022-06-20 03:33
Is this duplicate of #8832 #8802 ?

**Comment by ThiloteE** [comment] 2022-06-20 11:32
I think so :-) Closing this. 

@JoKalliauer please try the latest development version, this issue should be fixed. You can download it from here: https://builds.jabref.org/main/

If you think this is not fixed, you can reopen.

**Closed by ThiloteE** 2022-06-20 11:32 UTC
Labels: type: bug 🐛, ui, maintable

**Comment by ThiloteE** [comment] 2022-06-20 11:34
When clicking on DOI, it opens the URL instead?

**Comment by JoKalliauer** [comment] 2022-06-21 17:47
@ThiloteE I can Confirm fix

![JabRefList](https://user-images.githubusercontent.com/15687581/174865168-998f00ee-f046-43c0-bb35-e30e04d6106c.png)

on
```
JabRef 5.7--2022-06-20--41edd28
Linux 5.18.5-200.fc36.x86_64 amd64 
Java 18.0.1 
JavaFX *unknown*
```
