### ISSUE TITLE
Freeze when New Entry clicked | Mac OS Sierra 

### ISSUE THREAD

**Issue by adcox** [JabRef/jabref#3296] opened 2017-10-12 23:47 UTC
Steps to reproduce:

1. Open JabRef
2. Click the "New Entry" button (dialog bubble with a plus sign)
3. Select one of the options; I've tried MastersThesis and Article, both result in the same behavior
4. Cue spinning wheel of death for several minutes; eventually responds.

Mac OS Sierra 10.12.6

**Comment by adcox** [comment] 2017-10-13 00:09
In fact, most interactions with buttons in the software are slow. Just tried clicking the button to link a file to a reference and had to wait at least 20 - 30 seconds. After a file is selected, the program freezes yet again (the wheel is still spinning after about 10 minutes).

Also for reference, from the about dialog:
JabRef 4.0
Mac OS X 10.12.6 x86_64 
Java 1.8.0_144

**Comment by lenhard** [comment] 2017-10-13 07:29
This is a duplicate of #3236 Please have a looked at that. A description to a potential fix is also linked in the issue.

**Closed by lenhard** 2017-10-13 07:29 UTC
Labels: duplicate
