### ISSUE TITLE
month fields in braces results in a warning

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2012] opened 2016-09-19 20:41 UTC
JabRef 3.6
windows 7 6.1 amd64 
Java 1.8.0_66

Steps to reproduce:
1. load the pubmed/medline entry ID 27623067
2. make sure that the % signs in the abstract are escaped to \%
3. the compilation with the actual biber gives a warning:
   Utils.pm:164> WARN - month field 'Sep' in entry 'PRR+16' is not an integer - this will probably not sort properly

This is due to (from texexchange):

Such month abbreviations are BibTeX macros and if you protect them in braces, they are not parsed as macros but as literal strings. You need, in your example:
MONTH = Sep
and not
MONTH = {Sep}

While all entries in Jabref are now in braces, this one should be not.

Removing the braces did the job. but how to do this in a 1800 entry bib-file

```

```

**Comment by grimes2** [comment] 2016-09-19 21:14
> Removing the braces did the job. but how to do this in a 1800 entry bib-file

With Quality > Cleanup entries
The field formatter is month: Normalize month.

**Comment by Siedlerchr** [comment] 2016-09-19 21:29
Thanks for your report! I can confirm the behavior. The cleanup as proposed by @grimes2  does the job.

As the cleanup works, I would suggest adding a case for the Integrity Checker, according to BibLaTeX manual, [section 2.3.9](http://ftp.fau.de/ctan/macros/latex/contrib/biblatex/doc/biblatex.pdf)

> The month feld is an integer feld. The bibliography style converts the month to
> a language-dependent string as required. For backwards compatibility, you may
> also use the following three-leter abbreviations in the month feld: jan, feb, mar,
> apr, may, jun, jul, aug, sep, oct, nov, dec. Note that these abbreviations are
> BibTeX strings which must be given without any braces or quotes

**Comment by grimes2** [comment] 2016-09-20 03:12
I would like to do the MonthChecker.

**Comment by tobiasdiez** [comment] 2016-09-20 06:14
Perfect!
And the month-cleanup should be performed automatically for the pubmed fetcher. @zellerdev are you willing to have a look at this and rewrite the MedlineFetcher using the new framework (no need to ask the user how much entries he wants to fetch, just take the default value from the API).

**Comment by bernhard-kleine** [comment] 2016-09-20 06:52
with the cleanup the warnings are gone.

**Comment by lenhard** [comment] 2016-09-23 13:50
If I understand all the comments here correctly, the issue is fixed with #2015 and we can close it.

**Comment by tobiasdiez** [comment] 2016-09-23 15:03
Not quite fixed yet; the medline fetcher still produces "wrong" month fields. @zellerdev will take care of it.

**Comment by simonharrer** [comment] 2016-12-05 14:11
@zellerdev is this issue fixed now?

**Comment by zellerdev** [comment] 2016-12-09 15:05
It looks like I missed it in my PR. The braces are still produced. I will investigate it.

**Comment by lenhard** [comment] 2016-12-09 15:17
Ok, then we wait for your fix.

**Comment by stefan-kolb** [comment] 2016-12-10 13:13
@bernhard-kleine Does the recent PR solve the Medline fetcher issue? Please try the latest build from https://builds.jabref.org/master/

**Closed** 2016-12-10 13:13 UTC
Labels: enhancement, fetcher, stupro

**Comment by bernhard-kleine** [comment] 2017-02-16 21:17
Sorry, I did not see it earlier. the field is now #dec#, seems ok.
