### ISSUE TITLE
Bring back floation mode in search

### ISSUE THREAD

**Issue by calixtus** [JabRef/jabref#6724] opened 2020-07-29 19:22 UTC
Some users and core developers asked to bring back floatation mode on search (non-fitting entries are greyed out instead of not being shown at all).
By converting the UI to JavaFX had to be temporarily removed to continue on reworking the ui, since seemed to be quite complicated to implement in JavaFX. So there is possbily some research on this matter needed before an implementation can be done.

**Comment by tobiasdiez** [comment] 2020-07-29 19:32
Duplicate of https://github.com/JabRef/jabref/issues/4237

**Closed by tobiasdiez** 2020-07-29 19:32 UTC
Labels: search, type: enhancement, ui

**Comment by calixtus** [comment] 2020-07-30 05:24
Oh, did not see that. Sorry
