### ISSUE TITLE
citation counts

### ISSUE THREAD

**Issue by Yery** [JabRef/jabref#6153] opened 2020-03-22 11:28 UTC
Hi, 

i am not sure whether this is possible, but it would be very cool to have JabRef import citation counts (e.g. from google scholar or scopus), and display this info as an extra column in Jabref.

Regards,
Yery

**Comment by koppor** [comment] 2020-03-22 12:03
This is a duplicate of https://github.com/JabRef/jabref/issues/5849, please provide additional input there.

**Closed by koppor** 2020-03-22 12:03 UTC
