### ISSUE TITLE
total count of entries - UI misses pixels

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#2803] opened 2017-04-28 11:01 UTC
JabRef 4.0.0-beta
Linux 4.10.11-200.fc25.x86_64 amd64
Java 1.8.0_131

UI Design issue - missing a few pixels: now that my database contains 10k entries, the 5 digit number is not shown fully.

![screenshot fri apr 28 2017 12 59 14 gmt 0200 cest 409x100](https://cloud.githubusercontent.com/assets/20518297/25526164/ab663de8-2c12-11e7-8dda-71daeccdf166.png)

**Comment by AEgit** [comment] 2017-04-28 11:14
Cannot confirm this issue with:
JabRef 4.0.0-dev--snapshot--2017-04-24--master--4e25cc642
Windows 10 10.0 amd64 
Java 1.8.0_131

My database has >11k entries.

If this is not related to the version you are using, it might be a Linux-specific problem.

**Comment by stefan-kolb** [comment] 2017-05-03 07:31
Maybe it's caused by the configuration in `GroupsTree.fxml`:
```xml
                <TreeTableColumn fx:id="numberColumn" maxWidth="60.0" minWidth="40.0" prefWidth="50.0"
                                 styleClass="numberColumn"/>
```

@lynyus Can you check this on Linux and adapt or remove the max width for the number column?

**Comment by lynyus** [comment] 2017-05-04 11:00
yeah also happens for me
![5digitgroups](https://cloud.githubusercontent.com/assets/1254003/25700789/790a6106-30c9-11e7-805f-54df95b15c8e.png)

**Comment by tobiasdiez** [comment] 2017-05-04 13:15
@
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Closed by tobiasdiez** 2017-05-04 13:15 UTC
Labels: beginner, enhancement, groups, linux, ui
