### ISSUE TITLE
"Main file directory" should be relative to the bib file

### ISSUE THREAD

**Issue by vogler** [JabRef/jabref#1324] opened 2016-04-29 15:45 UTC
If I set "Preferences > File> Main file directory" to "lit", then the default "Link" after "Look up full text document" will be "/Applications/JabRef.app/Contents/java/app/lit/some.pdf" instead of "/path/to/bib/lit/some.pdf"

Version 3.3

**Comment by Siedlerchr** [comment] 2016-04-29 19:24
I can not really reproduce this in the current master: 1aa214510eee23cc586aad116780e4a875538e00
Please try again with v3.3 or the latest development snapshot from http://builds.jabref.org/master/

My settings are as follows: 
 1.  Open bib databse e.g . `\JabRef\Data\myBibs\test.bib`
 2.  Set Main file directory to "lit"  (so the relative path is `myBibs\lit` )
 3.  **Check "Allow file links relative to bib"** <- Maybe you did not check that?
 4. Auto ink files with names starting with bibtex keys 
 5. Select an entry in the database -> File -> Auto

And now the file is attached using its relative path:
![jabrefrelativefilepath](https://cloud.githubusercontent.com/assets/320228/14927147/867888c8-0e50-11e6-8218-bc5f4593802d.png)

**Comment by vogler** [comment] 2016-04-29 20:22
Same settings, same behavior with the current snapshot.
Linking files works. The only problem is that the path-prefix in the "Look up full text document" dialog is set to wherever the jar-file is, instead of where the bib-file is. E.g. now it is "/Users/voglerr/Downloads/lit/foo.pdf" instead of "/Users/voglerr/paper/lit/foo.pdf".

**Comment by Siedlerchr** [comment] 2016-04-29 20:47
@vogler  Ah yes. Now I understand what you mean.  You are referring to the Quality-> Lookup fulltext document dialog.
Yes, I  could reproduce  that behavior. I will look into that. I think I know where to look.

Could someone add bug label and assign it to me?

**Comment by JabFabi** [comment] 2016-05-24 11:44
Hi, I'm not sure if this is related to the issue you are working on, but as you mentioned the option "Allow file links relative to bib":
I would like to enable this option (as I had in an older version) but whenever I do so, it gets reset to the disabled state after restarting JabRef 3.3.
I had a look into the exported settings XML file and compared it to the old one; the corresponding entry is simply missing and it seems to be missing in the Windows registry as well. Also, I didn't find any entry for this option in the "View settings" dialog.
Let me know if you need further details.

Greetings and thanks for the great job!
Fabi

**Comment by stefan-kolb** [comment] 2016-06-05 18:44
@JabFabi Please open a new issue for this behavior.

**Comment by koppor** [comment] 2016-08-09 18:17
@vogler Work around: Set the relative directory for each bibtex database. Please report if that works for you.

![grabbed_20160809-201655](https://cloud.githubusercontent.com/assets/1366654/17528115/42ef24e0-5e6e-11e6-90ed-437014292b1f.png)

**Comment by Siedlerchr** [comment] 2016-08-09 18:21
@koppor  This issue is fixed in #1336 (Working directoy)

**Closed** 2016-08-10 16:36 UTC
Labels: bug

**Comment by Siedlerchr** [comment] 2016-08-10 17:22
@vogler  Fixed. Please try out the latest dev build from:
http://builds.jabref.org/master/
