### ISSUE TITLE
Entry editor: Toggle journal abbreviation roundtrip does not work

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#9370] opened 2022-11-12 18:51 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

mac os 11.7 big sur

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.  Create a new article, set journal or journaltitle to  `Comm. Pure Appl. Math.`
2.  Click on the Toggle abbreviation button next to the field
<img width="1115" alt="grafik" src="https://user-images.githubusercontent.com/320228/201489853-9bdf34b2-fe5d-4c04-b68c-1df926667ca9.png">
 
4. A dotless abbreviation is now in the field (Medline abbrev)
5. The field now shows `Comm Pure Appl Math`
6. Click again on the Toggle abbrevation button.
7. Nothing happens

=> Here the full journal name should be visible

## Hints on the code

For anyone looking into this:
The problem is that both methods [isKnownName](https://github.com/JabRef/jabref/blob/a1f2d5181ce1d99674c30bbd4894158f9b3d1437/buildSrc/src/copied/java/org/jabref/logic/journals/JournalAbbreviationRepository.java#L50)
 and https://github.com/JabRef/jabref/blob/a1f2d5181ce1d99674c30bbd4894158f9b3d1437/buildSrc/src/copied/java/org/jabref/logic/journals/JournalAbbreviationRepository.java#L77

do not consider a dotless abbreviation.

Solution could be to replace spaces with dots before checking. 

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by manu-vaillant-afk** [comment] 2022-11-18 10:36
Hello, are you sure that it is the expected behavior ? 
For me, when you set journal to `Comm. Pure Appl. Math.` and click on the Toggle abbreviation button, it should switch to full abbreviation which is `Communications on Pure and Applied Mathematics`  and vice versa when putting the button ?

**Comment by K5qu4r3d** [comment] 2022-11-30 04:02
> Hello, are you sure that it is the expected behavior ? For me, when you set journal to `Comm. Pure Appl. Math.` and click on the Toggle abbreviation button, it should switch to full abbreviation which is `Communications on Pure and Applied Mathematics` and vice versa when putting the button ?

Going off of @Siedlerchr's comment, I assume it's supposed to change from `Comm Pure Appl Math` to `Communications on Pure and Applied Mathematics` when clicking the "Toggle abbreviation" button. I believe `Comm. Pure Appl. Math.` -> `Comm Pure Appl Math` is the intended behavior.

**Comment by LeRobertDePoche** [comment] 2022-12-30 14:14
The very same issue seems to persist for me in the latest version of JabRef, even though it should have been fixed.
Using JabRef 5.8 (up to date) on Windows 11.
Another example which does not work: switching with the toggle button gives successively

- Physical Review B
- Phys. Rev. B
- Phys Rev B (MEDLINE)

and then stops, instead of going again to full journal name.

Any clue ?

**Comment by Siedlerchr** [comment] 2022-12-31 15:03
@LeRobertDePoche  Hi, yes I could reproduce this. The problem is that JabRef internally stores the abbreviations with and for medline the dots are removed and JabRef can no longer find the journal name. There was a fix which tried to solve this, but seems like it missed some edge cases.

**Comment by K5qu4r3d** [comment] 2023-04-06 17:14
> The very same issue seems to persist for me in the latest version of JabRef, even though it should have been fixed. Using JabRef 5.8 (up to date) on Windows 11. Another example which does not work: switching with the toggle button gives successively
> 
> * Physical Review B
> * Phys. Rev. B
> * Phys Rev B (MEDLINE)
> 
> and then stops, instead of going again to full journal name.
> 
> Any clue ?

I just tried to reproduce this error on a few different environments:
- JabRef 5.9, Windows 10
- JabRef 5.9, Windows 11
- JabRef 5.9, Ubuntu 22.04

I don't get the stop error in each environment when going from "Phys Rev B" to "Physical Review B".

@Siedlerchr Was this issue fixed in the time since the posting of @LeRobertDePoche's comment? I haven't touched my branch since my initial pull request on 2022-12-15.

**Comment by Siedlerchr** [comment] 2023-04-06 19:44
I think this issue was solved in the meantime. You should try always the latest development Version

**Comment by koppor** [comment] 2023-04-07 13:57
I tried with JabRef 5.9 - and could successfully "circle around":

![image](https://user-images.githubusercontent.com/1366654/230620945-55d94552-79dc-41a3-bba1-18b0cc4a9170.png)

![image](https://user-images.githubusercontent.com/1366654/230620964-9c16fc3d-5815-4907-afd7-bd7a6b9ca62a.png)

![image](https://user-images.githubusercontent.com/1366654/230620980-d3b71c87-7ad6-44bf-87e6-5e3731a4e31c.png)

@LeRobertDePoche Please raise your voice if the issue persists at your side.

**Closed by koppor** 2023-04-07 13:57 UTC
Labels: type: bug 🐛, entry-editor, good first issue

**Comment by LeRobertDePoche** [comment] 2023-04-07 13:59
I confirm it works fine now, thank you for your answers.
