### ISSUE TITLE
Still freezes on macOS High Sierra

### ISSUE THREAD

**Issue by jimjianghk** [JabRef/jabref#3995] opened 2018-04-28 19:49 UTC
Steps to reproduce:
1. Open Jabref
2. File - Import into new library
3. Choose file and click "open"
4. Freezes

Same thing happens when importing into current library. Tried the hostname solution, no luck.

JabRef 4.2
Mac OS X 10.13.4 x86_64 
Java 1.8.0_172

**Comment by Siedlerchr** [comment] 2018-04-30 19:56
Try to change the Look and Feel, we recently had many problems + freeze reports with the GTK Look and Feel.

**Comment by urielz** [comment] 2018-04-30 21:38
Is there a way to list the available look and feel themes in the system?

I tried editing ~/Library/Preferences/com.apple.java.util.prefs

for Jabref shows:

```
<key>lookAndFeel</key>
<string>com.apple.laf.AquaLookAndFeel</string>
```

I tried `javax.swing.plaf.metal.MetalLookAndFeel` and `javax.swing.plaf.metal.SynthLookAndFeel` but in both cases it reverts back to the default look and feel...

**Comment by Siedlerchr** [comment] 2018-04-30 22:13
Normally you should be able to switch it in JabRef, as the FAQ says, you have to change the Look and Feel in JabRef.
It should list all available styles.

**Comment by urielz** [comment] 2018-05-01 01:51
That's strange. On macOS there's no _"Options -> Appearance"_, the closest would be _"Options -> Preferences --> Appearance"_, and these are all the options available, I don't see any way to change the look and feel:

![jref_options](https://user-images.githubusercontent.com/11670888/39458155-857bbb24-4cc0-11e8-8985-fc9648e60810.jpeg)

**Comment by yangmqglobe** [comment] 2018-05-01 07:15
Got this issue, too. Setup on JabRef 4.2, macOS 10.13.4 and Java build 1.8.0_172
Is there any way to download the older version? I am in a hurry...

**Comment by Siedlerchr** [comment] 2018-05-01 08:29
@LinusDietz can you take a look?
Old versions can be found here https://github.com/JabRef/jabref/releases

**Comment by PUKK** [comment] 2018-05-01 10:43
Same problem on OpenSuse 42.3. Jabref 4.1 works, version 4.2 freezes on import of bibentries, same for the latest development version.

**Comment by yangmqglobe** [comment] 2018-05-01 10:55
Thanks, I fond it. It is really tricky that there was not the release panel when you are in the issue panel on GitHub.

**Comment by Siedlerchr** [comment] 2018-05-01 11:08
@PUKK  Do you get any errors in the log? At which point does it freeze? Opening the file dialog? Showing the import inspection window?

@urielz  Could you please try out this version to change the style? 
https://builds.jabref.org/removeGTK/

I found out that for some reason the look and feel selection was disabled on OSX

**Comment by PUKK** [comment] 2018-05-01 11:33
There  seems to be a problem with Jabref completely crashing (no GUI coming up) if it does not find some fonts.

This also happens in the default look-and-feel. I went to "override default font setting" and increased "menu and lable font size" from 13 to 14. One has to restart for the changes to take effect and then Jabref does not start (which is nasty since one does not get access to the preferences menu anymore). Output in the terminal:
[AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ClassCastException: java.awt.Font cannot be cast to javax.swing.plaf.FontUIResource
        at org.jabref.JabRefGUI.setLookAndFeel(JabRefGUI.java:288) ~[JabRef-4.Xdev.jar:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:87) ~[JabRef-4.Xdev.jar:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:60) ~[JabRef-4.Xdev.jar:?]
        at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:182) ~[JabRef-4.Xdev.jar:?]
        at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:1.8.0_162]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:1.8.0_162]
        at java.awt.EventQueue.access$500(Unknown Source) ~[?:1.8.0_162]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_162]
        at java.awt.EventQueue$3.run(Unknown Source) ~[?:1.8.0_162]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:1.8.0_162]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_162]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_162]
        at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_162]

**Comment by Siedlerchr** [comment] 2018-05-01 11:39
I could confirm this on my linux VM. will try to fix this asap

**Comment by urielz** [comment] 2018-05-01 13:04
> @urielz Could you please try out this version to change the style?
https://builds.jabref.org/removeGTK/

> I found out that for some reason the look and feel selection was disabled on OSX

@Siedlerchr Thanks for looking into this. I can change the look and feel with that version, unfortunately the problem still persists. I tried all four options but Jabref still hangs when importing.

**Comment by urielz** [comment] 2018-05-01 14:24
@Siedlerchr It shows the File Open Dialog, but it hangs right after I tried to open a file (bib, ris, etc).

If there's a way to run JabRef in debug mode I can give it a try.

**Comment by Siedlerchr** [comment] 2018-05-01 14:31
You can try it from command line
java -jar JabRef.jar
Any errors should be printed out on the console

**Comment by urielz** [comment] 2018-05-01 14:38
I tried that before and it gives me an error along the lines "Unsupported major.minor version". Maybe related to the fact that I don't have JDK? or the correct Java version? I'll try to look into this later today.

**Comment by Siedlerchr** [comment] 2018-05-01 14:54
You might have java 9 or an older version than 8 of Java installed. I am sorry, I don't own a mac, so I can't help you any further. Maybe @halirutan  or @LinusDietz  can help you any further

**Comment by urielz** [comment] 2018-05-01 15:11
@Siedlerchr No worries!, thanks for looking into this.

**Comment by jimjianghk** [comment] 2018-05-04 17:17
Sorry, but is this supposed to have been fixed? I downloaded the latest dev snapshot (JabRef 4.3-dev--snapshot--2018-05-04--master--18011fcab) and the issue persists.

**Comment by Siedlerchr** [comment] 2018-05-04 21:01
@jimjianghk  Well, it should have been a Look and Feel Problem with the GTK Look and Feel.
From the answers before, it seeemed to be working when you change the Look and Feel to a non GTK one,

**Comment by Glenbeulah** [comment] 2018-05-05 07:55
@Siedlerchr I have tried all of the above and changing the Look and Feel doesn't solve this JabRef problem. It still freezes after I click on "open" as described in the first post, no matter what Look and Feel I use.

JabRef 4.3-dev--snapshot--2018-05-02--removeGTK--74c7b8e59
Mac OS X 10.13.4 x86_64 
Java 1.8.0_172

**Comment by Siedlerchr** [comment] 2018-05-06 11:13
@Glenbeulah  The only option I have in mind that you might have an older bundled JRE in Jabref itself, also the system one is newer. We had this issue with someone before. 
Could you please uninstall JabRef first and (additionally, if not removed) remove the sub folder "jre" from the JabRef installation directory?
And then install the latest dev version of JabRef.

**Comment by Glenbeulah** [comment] 2018-05-06 12:12
@Siedlerchr not sure where to find the sub folder "jre". Do you have a hint for me? I uninstalled JabRef via AppCleaner which deletes the application and every other item connected to it. See below:
~/Library/Application Support/CrashReporter/JavaApplicationStub_8D16F21C-0625-5D17-9745-A05607371D91.plist
~/Library/Application Support/JabRef
~/Library/Saved Application State/com.install4j.0034-7691-1464-4754.23.savedState
also went to the java application to see which version is installed but besides "Java 1.8.0_172" I couldn't  find any other entry.
A fix for this Problem isn't urgent for me since I found the DOI entry generator which is really handy for single entry imports.

**Comment by Siedlerchr** [comment] 2018-05-06 14:25
@Glenbeulah  You could try downloading and running the latest jar file directly (not the dmg) into some folder and see if that works fine. Then we know that the install/uninstall process is somewhere wrong.

For reference, that was the other issue in which we found out that JabRef uninstall is required first https://github.com/JabRef/jabref/issues/3587 

As a workaround, you can always paste/copy bibtex code directly on the maintable. And new files can be imported by drag and drop on the table as well

**Comment by Glenbeulah** [comment] 2018-05-06 15:29
@Siedlerchr I had the same problem which they discussed in #3587  and after uninstall/install it worked but than I ran into our current error.
Apparently the .jar-file has the same error... As you said I uninstalled Jabref than downloaded https://builds.jabref.org/master/JabRef-4.3-dev--snapshot--2018-05-05--master--b8ea55bc2.jar
and ran it directly but no luck.

**Comment by Glenbeulah** [comment] 2018-05-06 15:40
oh and "drag and drop" works fine

**Comment by halirutan** [comment] 2018-05-07 08:39
@Glenbeulah I just tried it on MacOSX HighSierra 10.13.4 with Java 8u172 like you. It works. If you like, then ping me @halirutan in our [developer chat](https://gitter.im/JabRef/jabref) and we try to fix this thing for you.

**Comment by droseger** [comment] 2018-08-01 20:29
Are you sure the GTK style freezes Jabref? I had to downgrade to Jabref 4.1 because the GTK version properly scales fonts and icons for my HDPI screen (and doesn't look as bad as Nimbus). I have not witnessed a single freeze. Also, people still seem to have crashes even with the GTK theme disabled.

**Comment by Siedlerchr** [comment] 2018-08-29 15:57
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2018-08-29 15:57 UTC
Labels: macOS, waiting-for-feedback

**Comment by urielz** [comment] 2018-08-29 16:32
I can confirm that the dev version works on my end (macOS 10.13.6). Thanks!

**Comment by koji33** [comment] 2018-11-09 00:55
BTW, look and feel is set to default on Mac: com.apple.laf.AquaAndFeel. I tried some other availabilities in vain.

On the other hand, direct importing from the command line works well.

> \# java -jar /Applications/JabRef.app/Contents/java/app/JabRef-4.3.1.jar -i Downloads/some.ris 
Importing in unknown format: Downloads/some.ris
Format used: RIS
File: grouptree.fxml not found, attempting with camel case
File: grouptree.css not found, attempting with camel case

**Comment by CharlesVilliers** [comment] 2018-11-20 15:48
After I updated macOS High Sierra to Mojave, my perfectly running JabRef 4.2 freezes, not when opening a library file, but as soon as I want to open the entry editor.
The latest development version of JabRef 5 looks really good but is slow and unresponsive, the entry editor takes five seconds to show another entry.

**Comment by retorquere** [comment] 2019-07-30 18:13
I'm on Mojave, JabRef 4.3.1 (just installed) freezes after start.

**Comment by egarpor** [comment] 2019-10-09 09:26
Mojave, JabRef 4.3.1 just installed. I try to save a database, it freezes.

**Comment by Siedlerchr** [comment] 2019-10-09 09:29
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by tdupu** [comment] 2019-11-19 02:09
Still a problem for me. 
Mac OS X 10.14.6 Mojave.

**Comment by egarpor** [comment] 2019-11-20 10:17
> Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.
> 
> We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

This worked, version

> JabRef 5.0.0-dev--2019-10-20----dfad2fdea
> Mac OS X 10.14.6 x86_64 
> Java 12.0.2

However, it is quite slow when adding an entry or making an edit to an existing entry.

**Comment by Siedlerchr** [comment] 2019-11-20 10:31
@egarpor Please try to remove the old JabRef installation before installing the latest snapshot
