### ISSUE TITLE
Menus from the menu bar close immediately after left click is let go of if the menu bar was clicked in its top half

### ISSUE THREAD

**Issue by douglasrizzo** [JabRef/jabref#5867] opened 2020-01-25 15:32 UTC
JabRef 5.0-beta.362--2020-01-25--ac90ad2
Linux 5.4.13-3-manjaro amd64 
Java 13.0.2

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

- [x] I have built the latest master branch from source (commit ac90ad29b4302e0287f53af456bd1cb37521833a) and also observed this issue in the current beta release.

1. Click on any item in the menu bar (File, Edit, Library, Quality, Tools, View, Options or Help), above the text line (anywhere in the orange area in the image below, colors were added by me to help explain the problem).
2. Try to select anything from the submenu that opens.

![Untitled](https://user-images.githubusercontent.com/2209364/73123340-dc67d980-3f6d-11ea-930c-496444a7c966.png)

Expected behavior:
* The corresponding submenu should stay open after clicking in its title.

Actual behavior:
* If the user clicks the top half of the menu bar (orange area in the image), the submenu that opens closes immediately after the left mouse button is let go of. If you maintain the left mouse button pressed, the menu stays open, but nothing can be selected while the left mouse button stays pressed.
* If the submenu is clicked in its bottom half (blue area in the image), everything works as expected.

**Comment by sambo57u** [comment] 2020-01-26 14:06
Perhaps this is the same but if you left click on a menu and try to scroll down to menu items they are not highlughted and cannot be selected. However, if you repeat the same
thing the second time the menu items become selectable.

**Comment by douglasrizzo** [comment] 2020-01-27 11:51
I don't know if this is related, but when I open a menu from the menu bar, there is a gap between the menu bar and the menu. I don't know if that's the default behavior of the application, or if this is not supposed to happen.

![Untitled](https://user-images.githubusercontent.com/2209364/73172177-3046ff80-40e1-11ea-94bb-6cf2eb2656aa.png)

**Comment by nujabse** [comment] 2020-02-29 12:28
Can confirm that the problem still persisits in Manjaro Linux, i3 wm, seems to be related to i3 wm issue.  The problem got solved when I switched to xfce4 wm, where the menus in the menu bar became clickable again.

**Comment by douglasrizzo** [comment] 2020-03-03 12:58
If it is relevant, I also did my tests on a tiling window manager (bspwm), so it may be a problem on these kinds of WMs...

**Comment by sambo57u** [comment] 2020-03-03 13:45
I am on KDE Plasma 5

**Comment by Siedlerchr** [comment] 2020-03-03 18:48
Maybe this is related to this issue? #5526

**Comment by douglasrizzo** [comment] 2020-03-03 22:08
I am not sure, as we are dealing with floating menus here and not dialog windows.

* Currently, JabRef dialog windows behave as regular windows and take up half of the screen when they open, as is common in tiling window managers.
* The floating menus keep their intended size. They just aren't interactive in some cases.

But maybe fixing #5526 also fixes this one, who knows.

**Comment by Etherealflux** [comment] 2020-05-07 14:28
I'm also experiencing this under i3wm.

**Comment by krummja** [comment] 2020-08-24 04:35
Having the same issue in i3wm.

**Comment by gonced8** [comment] 2020-08-31 08:21
Having the same issue in i3wm also

**Comment by Jayanth-kumar5566** [comment] 2020-09-02 07:03
same issue with i3wm

**Comment by Siedlerchr** [comment] 2020-09-02 22:25
I searched around and it seems to be an issue in the javafx version 14:
https://bugs.openjdk.java.net/browse/JDK-8251240

**Comment by MaciekChudek** [comment] 2020-10-06 19:27
Based on the the [javafx issue](https://bugs.openjdk.java.net/browse/JDK-8251240), running with environment variable GDK_DISPLAY=1 fixes this issue under XMonad (another tiling window manager).

**Comment by MaciekChudek** [comment] 2020-10-08 19:50
> Based on the [javafx issue](https://bugs.openjdk.java.net/browse/JDK-8251240) cited above, running with environment variable GDK_DISPLAY=1 fixes this issue under XMonad (another tiling window manager).

This seemed to work yesterday, but I cannot replicate the workaround today. Not sure what changed, please disregard.

However, here is another workaround that seems to work and might help diagnose the issue. Click and hold on menu (e.g. "file"), drag cursor out of JabRef window (e.g., into neighbouring tiled window, status bar, etc.). Release and menu stays open. 

Alt then cursor keys also work for navigating the menus, but this is not a fix.

**Comment by gonced8** [comment] 2020-10-08 20:13
I believe someone already mentioned this, but you're able to use the buttons if you click on the bottom half of the button

**Comment by hemker** [comment] 2021-02-04 13:07
Still persistent on Regolith Linux (Ubuntu 20.04 with i3wm)

**Comment by ploedige** [comment] 2021-05-25 15:30
I have the same problem on Arch with Qtile.
The workaround of @hemker works for me.

**Comment by ahmedelhori** [comment] 2021-06-25 00:36
The issue is still there on arch i3wm

**Comment by bear-jordan** [comment] 2021-07-08 03:28
Work around is good for me too. I am running Arch with KWin though.

**Comment by jpmvferreira** [comment] 2022-01-05 21:53
Using Manjaro with i3WM and jabref from the AUR, everything up to date, issue still stands.

Working on the lower part of the menu does seem to be a valid workaround.

**Comment by 00riddle00** [comment] 2022-03-03 18:54
ditto (Arch + i3wm).

**Comment by Adriankhl** [comment] 2022-05-04 02:42
Same issue in swaywm + openSUSE

**Comment by Da-Va** [comment] 2022-09-21 14:17
awesomewm + Xubuntu works

**Comment by HakonHarnes** [comment] 2022-10-19 20:04
Setting the java option -Djdk.gtk.version=2 fixed the issue for me on i3wm.

**Comment by Da-Va** [comment] 2022-10-24 09:27
> Setting the java option -Djdk.gtk.version=2 fixed the issue for me on i3wm.

Thank you. Verified this and it works!

**Comment by Siedlerchr** [comment] 2022-10-24 14:25
@Da-Va  @HakonHarnes  Thanks for your solution! Can you please add a section as well to the troubleshooting here?
https://docs.jabref.org/installation

**Comment by HakonHarnes** [comment] 2022-10-25 06:55
> @Da-Va @HakonHarnes Thanks for your solution! Can you please add a section as well to the troubleshooting here? https://docs.jabref.org/installation

See my PR.

**Comment by Adriankhl** [comment] 2022-10-25 15:54
This is a newer issue of javafx: https://bugs.openjdk.org/browse/JDK-8292298

**Comment by HakonHarnes** [comment] 2022-10-25 16:41
I've installed JabRef via flatpak and the workaround does not seem to work. I also tried to downgrade JabRef to an earlier version that uses an older version of JavaFX. Running it from the terminal it does seem to run with gtk version 2, but it still doesn't work.

**Comment by HakonHarnes** [comment] 2022-10-25 18:03
After debugging some more, it seems like flatpak is not using GTK 2, even when specified with ```-Djdk.gtk.version=2```. Running the flatpak version of JabRef we get: 

```
Picked up _JAVA_OPTIONS: -Djdk.gtk.version=2

WARNING: A command line option has enabled the GTK 2 library
WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release
```

Which indicates GTK 2 is indeed being used. However, there is also this message: 

```
Gtk-Message: 19:33:33.990: Failed to load module "canberra-gtk-module"
``` 

Which I suspect causes flatpak to instead use GTK 3, because the following error is specific to GTK 3 (See https://stackoverflow.com/questions/55446534/how-to-fix-java22494-gdk-warning): 

```
Gdk-WARNING **: 19:33:36.010: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
``` 

So it seems when it doesn't find ```canberra-gtk-module``` it reverts back to using GTK 3. I would assume this would have to be fixed in ```org.jabref.jabref.yaml``` by somehow adding ```cranberry-gtk-module``` to the build stage or by using the GTK 2 shared module provided by flathub (See https://docs.flatpak.org/en/latest/manifests.html#shared-modules).

**Comment by Siedlerchr** [comment] 2022-10-25 19:46
@LyzardKing any thoughts on this? Do we need to modify the flatpak build script?

**Comment by LyzardKing** [comment] 2022-10-26 08:46
There might be another issue that is DE dependent, since on most other distros (non tiling window managers) it works as is.
I would also prefer to avoid using gtk2, which isn't maintained any more, if at all possible.

I wonder if in a flatpak it is possible to have conditional dependencies, but I imagine it is best to fix the issue in the window manager (or javafx)

**Comment by HakonHarnes** [comment] 2022-10-26 09:25
The Flatpak wouldn't use gtk2 by default, but at least support it so that the ```-Djdk.gtk.version=2``` workaround is still possible. I don't think you need the entire [gtk2 module](https://github.com/flathub/shared-modules/tree/master/gtk2), just the [libcanberra module](https://github.com/flathub/shared-modules/tree/master/libcanberra) since that is the library that is missing. I'm imagining this won't increase the size of the Flatpak by too much. 

I do agree, it should ideally be fixed in the window manager or JavaFX. However, that patch doesn't exist yet and I think you should at least provide a workaround until then. Personally, I refrained from using JabRef for quite some time due to this issue.

**Comment by LyzardKing** [comment] 2022-10-26 11:24
I think we shouldn't ignore the fact that the gtk2 JavaFX library is deprecated, and will be removed in future releases.
A quick search brings me to think that the issue is in how some tiling window managers deal with the menu bar.

Just out of curiosity, does adding this env variable work? `GDK_DISPLAY=1`

**Comment by LyzardKing** [comment] 2022-10-26 11:27
Another quick question for @HakonHarnes 
How much space does the installed package take? You can see it by running `flatpak info org.jabref.jabref`

**Comment by HakonHarnes** [comment] 2022-10-26 11:46
> I think we shouldn't ignore the fact that the gtk2 JavaFX library is deprecated, and will be removed in future releases. A quick search brings me to think that the issue is in how some tiling window managers deal with the menu bar.
> 
> Just out of curiosity, does adding this env variable work? `GDK_DISPLAY=1`

I agree, it's not an optimal solution but at least it allows for a workaround for the time being. `GDK_DISPLAY=1` does not work for me. 

> Another quick question for @HakonHarnes How much space does the installed package take? You can see it by running `flatpak info org.jabref.jabref`

The original Flathub installation without gtk2 takes 218.3 MB. My patched version with gtk2 takes 225.3 MB.

**Comment by LyzardKing** [comment] 2022-10-26 12:52
Ok, so it's not a big difference in size. That's good.
I wonder if it is possible to add the command conditionally

**Comment by HakonHarnes** [comment] 2022-10-26 21:20
> Ok, so it's not a big difference in size. That's good.
> 
> I wonder if it is possible to add the command conditionally

YAML is just a way of formatting text, not a programming language. Thus, it does not inherently support conditional statements. 

Nonetheless I don't think the increased size is a problem.

**Comment by HakonHarnes** [comment] 2022-10-28 07:52
> For my case: swaywm + flatpak version of `jabref`, `-Djdk.gtk.version=2` does not work.

@Adriankhl Can you confirm this works on your system?

```
flatpak install --user https://dl.flathub.org/build-repo/115982/org.jabref.jabref.flatpakref
```

```
flatpak run --branch=test org.jabref.jabref  
```

Make sure `-Djdk.gtk.version=2` is set.

**Comment by Adriankhl** [comment] 2022-10-28 11:44
@HakonHarnes Doesn't seem like it is working

```
Picked up _JAVA_OPTIONS: -Djdk.gtk.version=2
Oct 28, 2022 1:41:53 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
WARNING: A command line option has enabled the GTK 2 library
WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release
2022-10-28 13:41:53 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
INFO: Trust store path: /home/dlshcbmuipmam/.var/app/org.jabref.jabref/data/JabRef/ssl/truststore.jks
2022-10-28 13:41:53 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2022-10-28 13:41:53 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Oct 28, 2022 1:41:54 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "" not found.
```

**Comment by HakonHarnes** [comment] 2022-10-28 13:05
@Adriankhl That output looks correct to me. Could you please post the output of: 

```
flatpak run --branch=stable org.jabref.jabref 
```

```
flatpak run --branch=test org.jabref.jabref 
```

**Comment by Adriankhl** [comment] 2022-10-28 15:35
`_JAVA_OPTIONS="-Djdk.gtk.version=2" flatpak run --branch=stable org.jabref.jabref` gives:

```
Picked up _JAVA_OPTIONS: -Djdk.gtk.version=2
Oct 28, 2022 5:33:32 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
WARNING: A command line option has enabled the GTK 2 library
WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release
2022-10-28 17:33:33 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
INFO: Trust store path: /home/dlshcbmuipmam/.var/app/org.jabref.jabref/data/JabRef/ssl/truststore.jks
2022-10-28 17:33:33 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2022-10-28 17:33:33 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}

(JabRef:2): Gdk-WARNING **: 17:33:34.275: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
Oct 28, 2022 5:33:34 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "" not found.
```

While `_JAVA_OPTIONS="-Djdk.gtk.version=2" flatpak run --branch=test org.jabref.jabref` gives:

```
Picked up _JAVA_OPTIONS: -Djdk.gtk.version=2
Oct 28, 2022 5:34:43 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
WARNING: A command line option has enabled the GTK 2 library
WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release
2022-10-28 17:34:43 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
INFO: Trust store path: /home/dlshcbmuipmam/.var/app/org.jabref.jabref/data/JabRef/ssl/truststore.jks
2022-10-28 17:34:43 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2022-10-28 17:34:43 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Oct 28, 2022 5:34:44 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "" not found.
```

**Comment by HakonHarnes** [comment] 2022-10-28 16:48
It seems like it is indeed using GTK 2. I'm not sure why it doesn't resolve your issue; it does for me. 

Could you also try the older gnome runtime?

```
flatpak install runtime/org.gnome.Sdk/x86_64/3.24
```

```
flatpak run --runtime=org.gnome.Sdk --runtime-version=3.24 --branch=stable org.jabref.jabref
```

**Comment by Adriankhl** [comment] 2022-10-28 18:00
Still no, at this point, I am not sure if this problem is hardware dependent or wayland-dependent

```
Picked up _JAVA_OPTIONS: -Djdk.gtk.version=2
Oct 28, 2022 7:57:57 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
libGL error: pci id for fd 10: 1002:164c, driver (null)
libGL error: No driver found
libGL error: failed to load driver: (null)
WARNING: A command line option has enabled the GTK 2 library
WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release
2022-10-28 19:57:58 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
INFO: Trust store path: /home/dlshcbmuipmam/.var/app/org.jabref.jabref/data/JabRef/ssl/truststore.jks
2022-10-28 19:57:58 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2022-10-28 19:57:58 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Oct 28, 2022 7:57:59 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "" not found.
```

**Comment by Siedlerchr** [comment] 2022-11-29 15:24
There's currently a PR at opendjk in progress which will fix several problems and this as well https://github.com/openjdk/jfx/pull/915

**Comment by raffaem** [comment] 2022-12-17 08:46
> To fix the issue permanently set the following system property: `java -Djdk.gtk.version=2`.
> 
> This can be done globally by adding `_JAVA_OPTIONS="-Djdk.gtk.version=2"` to `/etc/environment`, or by setting the environment variable in your shell (e.g. `~/.bashrc`) It can also be set locally by editing `JabRef.cfg` in your installation folder (possibly located at `/opt/JabRef/lib/app/JabRef.cfg`) and add the line `-Djdk.gtk.version=2` in the `[JavaOptions]` section.

I'm on Hyprland and this doesn't fix the issue for me.

I have installed both murrine engine and the adwaita theme.

Here is the stdout:

```
❯ ./JabRef
Picked up _JAVA_OPTIONS: -Djdk.gtk.version=2
Dec 17, 2022 9:43:22 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
WARNING: A command line option has enabled the GTK 2 library
WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release
2022-12-17 09:43:23 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
INFO: Trust store path: /home/raffaele/.local/share/JabRef/ssl/truststore.jks
2022-12-17 09:43:24 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2022-12-17 09:43:24 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
Dec 17, 2022 9:43:25 AM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "" not found.
Dec 17, 2022 9:43:27 AM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "" not found.
```

**Comment by HakonHarnes** [comment] 2022-12-17 10:44
> > To fix the issue permanently set the following system property: `java -Djdk.gtk.version=2`.
> 
> > 
> 
> > This can be done globally by adding `_JAVA_OPTIONS="-Djdk.gtk.version=2"` to `/etc/environment`, or by setting the environment variable in your shell (e.g. `~/.bashrc`) It can also be set locally by editing `JabRef.cfg` in your installation folder (possibly located at `/opt/JabRef/lib/app/JabRef.cfg`) and add the line `-Djdk.gtk.version=2` in the `[JavaOptions]` section.
> 
> 
> 
> I'm on Hyprland and this doesn't fix the issue for me.
> 
> 
> 
> I have installed both murrine engine and the adwaita theme.
> 
> 
> 
> Here is the stdout:
> 
> 
> 
> ```
> 
> ❯ ./JabRef
> 
> Picked up _JAVA_OPTIONS: -Djdk.gtk.version=2
> 
> Dec 17, 2022 9:43:22 AM com.sun.javafx.application.PlatformImpl startup
> 
> WARNING: Unsupported JavaFX configuration: classes were loaded from 'module org.jabref.merged.module', isAutomatic: false, isOpen: true
> 
> WARNING: A command line option has enabled the GTK 2 library
> 
> WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release
> 
> 2022-12-17 09:43:23 [JavaFX Application Thread] org.jabref.logic.net.ssl.TrustStoreManager.createTruststoreFileIfNotExist()
> 
> INFO: Trust store path: /home/raffaele/.local/share/JabRef/ssl/truststore.jks
> 
> 2022-12-17 09:43:24 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
> 
> INFO: Not updating theme because it hasn't changed
> 
> 2022-12-17 09:43:24 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
> 
> INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
> 
> Dec 17, 2022 9:43:25 AM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
> 
> WARNING: Resource "" not found.
> 
> Dec 17, 2022 9:43:27 AM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
> 
> WARNING: Resource "" not found.
> 
> ```

Seems like the gtk2 workaround doesn't work on wayland. Let's just hope the openjdk PR fixes the issue permanently.

**Comment by gokberkgunes** [comment] 2023-05-08 10:02
Just a heads up, the suggested workaround, which recommends using GTK 2, doesn't work on Xorg, not just on Wayland.

**Comment by HakonHarnes** [comment] 2023-05-08 10:21
> Just a heads up, the suggested workaround, which recommends using GTK 2, doesn't work on Xorg, not just on Wayland.

@gokberkgunes Still works for me on Xorg. Are you by chance using the Flatpak version of JabRef?

**Comment by gokberkgunes** [comment] 2023-05-08 10:40
I was using the binary version from the releases page. When the environment variable changed, I could see that the mouse theme got changed to a different theme so probably GTK2 worked. I am receiving the same error message as others posted earlier. Do you also get same warnings when you run the `jabref` through the terminal, @HakonHarnes?

**Comment by HakonHarnes** [comment] 2023-05-08 10:44
@gokberkgunes I get this output when running jabref: 

```
Picked up _JAVA_OPTIONS: -Dsun.java2d.uiScale=2 -Djdk.gtk.version=2
WARNING: A command line option has enabled the GTK 2 library
WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release

(java:19824): Gtk-WARNING **: 12:43:04.930: Unable to locate theme engine in module_path: "clearlooks",

(java:19824): Gtk-WARNING **: 12:43:04.930: Unable to locate theme engine in module_path: "clearlooks",
2023-05-08 12:43:05 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.addStylesheetToWatchlist()
INFO: Watching css /usr/share/java/jabref/resources/main/org/jabref/gui/Base.css for live updates
2023-05-08 12:43:05 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Not updating theme because it hasn't changed
2023-05-08 12:43:05 [JavaFX Application Thread] org.jabref.gui.theme.ThemeManager.updateThemeSettings()
INFO: Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{file:/usr/share/java/jabref/resources/main/org/jabref/gui/Base.css}
2023-05-08 12:43:05 [JavaFX Application Thread] org.jabref.gui.StateManager.setActiveDatabase()
INFO: No open database detected
May 08, 2023 12:43:05 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "" not found.
2023-05-08 12:43:06 [pool-1-thread-1] org.jabref.gui.JabRefDialogService.notify()
INFO: Opening: '/home/hakon/project-thesis/references.bib'
May 08, 2023 12:43:06 PM com.sun.javafx.css.StyleManager loadStylesheetUnPrivileged
WARNING: Resource "" not found.
2023-05-08 12:43:07 [JavaFX Application Thread] org.jabref.model.database.BibDatabaseContext.getFulltextIndexPath()
INFO: Index path for /home/hakon/project-thesis/references.bib is /home/hakon/.local/share/JabRef/lucene94
[WARN] PDType1Font - Using fallback font LiberationSans for base font Symbol
[WARN] PDType1Font - Using fallback font LiberationSans for base font ZapfDingbats
[WARN] PDSimpleFont - No Unicode mapping for negationslash (54) in font BBXQZT+CMSY10
[WARN] PDSimpleFont - No Unicode mapping for lessmuch (28) in font BBXQZT+CMSY10
2023-05-08 12:43:08 [pool-1-thread-5] org.jabref.logic.pdf.search.indexing.PdfIndexer.writeToIndex()
```

**Comment by gokberkgunes** [comment] 2023-05-09 02:06
Installed i3 and menus worked without an issue. It seems like java has issues with window managers, and the one I use is one of them. [Here](https://www.reddit.com/r/suckless/comments/wvips4/drop_down_menus_in_java_applications_do_not_work/) is a conversation about the menu issue; however, suggested solutions do not work.

**Comment by HakonHarnes** [comment] 2023-05-09 08:51
> Installed i3 and the menus worked without an issue. It seems like Java has issues with some window managers, and the one I use is one of them. [Here](https://www.reddit.com/r/suckless/comments/wvips4/drop_down_menus_in_java_applications_do_not_work/) is a conversation about the menu issue; however, the suggested solutions do not work.

Interesting. I'm also using i3. Does GTK3 work on i3 without any issues for you? It doesn't for me - I have to use GTK2.

**Comment by Siedlerchr** [comment] 2023-08-05 17:29
There is another PR from the jdk team in the making https://github.com/openjdk/jfx/pull/1173 
But I don't know if this will be backported to javafx 21

**Comment by tsayao** [comment] 2023-09-03 15:32
> There is another PR from the jdk team in the making [openjdk/jfx#1173](https://github.com/openjdk/jfx/pull/1173) But I don't know if this will be backported to javafx 21

I did the [openjdk/jfx#915](https://github.com/openjdk/jfx/pull/915) PR, and it fixed the i3wm for a brief time, but I ended fixing another issue and breaking the i3wm fix.

 [openjdk/jfx#1173](https://github.com/openjdk/jfx/pull/1173) should fix it back.

**Comment by Siedlerchr** [comment] 2023-11-07 17:37
@tsayao  Do I see this right that the bug is not fixed in Jfx 21.01 but in jfx22? No backport?

**Comment by tsayao** [comment] 2023-11-07 18:30
Yes, it is in 22. I'm an independent contributor, so I cannot say if it's going to be backported, but probably not.

**Comment by Siedlerchr** [comment] 2023-11-08 17:45
@tsayao  Maybe you can ask for a backport? If we are lucky it gets into the next update, probably in January. or so.

**Comment by tsayao** [comment] 2023-11-23 11:25
Fix will be on 21.0.2.

**Comment by Siedlerchr** [comment] 2024-01-20 19:16
Can you all please test this version ? https://builds.jabref.org/pull/10808/merge 
It shoudl now contain the i3wm fix

**Comment by HakonHarnes** [comment] 2024-01-20 19:49
Happy to report that it works for me on i3wm!

**Closed** 2024-01-21 11:17 UTC
Labels: ui, os: linux, status: depends-on-external

**Comment by nuthub** [comment] 2024-01-21 12:01
I'm happy to confirm that the JabRef-5.12 version linked above also solved this issue for me in _sway_ (running JabRef via XWayland). Thank you!

**Comment by Siedlerchr** [comment] 2024-04-05 20:31
@tsayao As you worked on this menu items fix for i3 (thanks again!), do you have any idea about this missing menu entries behavior in javafx 22?
https://github.com/JabRef/jabref/issues/11140
