### ISSUE TITLE
JabRef GUI blank after Ubuntu wakes up from sleep

### ISSUE THREAD

**Issue by antonkarl** [JabRef/jabref#638] opened 2016-01-04 16:58 UTC
When my monitor goes out and Ubuntu goes to sleep and I log in again, the user interface looks like that, all grey. It does not recover by minimizing and maximizing but individual GUI elements become visible by using the mouse on them.

![jabrefbug](https://cloud.githubusercontent.com/assets/288033/12095041/1858b8a6-b304-11e5-9b20-d8f509be7ea1.png)

**Comment by alefa** [comment] 2016-01-04 18:58
I have the exact same problem in Debian 8 (Jessie) with Gnome. The JabRef version in Debian is an older one (2.10), though. I'll test with the newest version when I have a bit of time.

**Comment by teertinker** [comment] 2016-01-04 20:01
I can confirm this bug. For 3.1, Ubuntu 14.04. 64 bit 

    On Monday, January 4, 2016 7:58 PM, Gita Benadi <notifications@github.com> wrote:
 

 I have the exact same problem in Debian 8 (Jessie) with Gnome. The JabRef version in Debian is an older one (2.10), though. I'll test with the newest version when I have a bit of time.—

**Comment by oscargus** [comment] 2016-01-05 00:50
What JDK are you running? (And possibly look-and-feel?)

(I've never noticed this as I recall on:
`Linux urkua 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux` (CentOS)

```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```
but will check it explicitly once back to the office. No idea how to solve it though...
)

**Comment by alefa** [comment] 2016-01-05 10:14
My Java version:

    openjdk version "1.8.0_66-internal"
    OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
    OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

I'm using the GTK look-and-feel of JabRef.

**Comment by oscargus** [comment] 2016-01-08 12:51
I can just confirm that I do not have this problem on my Linux machine. While there are quite a few potential reasons for the problem (windows manager etc), it would be interesting to know if OpenJDK is a common factor or not.

**Comment by koppor** [comment] 2016-01-09 14:12
Refs #184 and #425. Maybe this is really a duplicate of #425?

**Comment by antonkarl** [comment] 2016-01-12 08:34
Java version:

java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+95-2015-12-02-052152.javare.3968.nc)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+95-2015-12-02-052152.javare.3968.nc, mixed mode)

**Comment by antonkarl** [comment] 2016-01-12 08:39
Oh, and GTK look-and-feel. JabRef version 3.1. Ubuntu 15.10, 64-bit.

**Comment by koppor** [comment] 2016-01-12 09:59
Could you change the L&F to something else? Refs #393.

**Comment by teertinker** [comment] 2016-01-12 14:06
I can't reproduce the bug anymore. I used to have windows look and feel in my preferences. And it was loaded when I upgraded from 2.11 to 3. I think this was when the bug appeared. In the meantime I switched to GTK L&F. There the problem does not exist and switching back to Windows L&F raises an error message (couldn't find L&F), so I can't test it.

**Comment by stefan-kolb** [comment] 2016-03-20 13:54
> My problem in Stuttgart was caused when using OpenJDK and GTKLookAndFeel. In my case when I want to open a file and navigate through the filechooser the GUI freezes. When using the Oracle JDK it works normal. Another way to solve it is to use MetalLookAndFeel with OpenJDK.
Does this change help in your case?

**Comment by alefa** [comment] 2016-03-23 09:33
After installing Oracle JDK the issue seems to be gone. I haven't seen it in several days. So it probably is a bug in OpenJDK. It's also not specific to JabRef, I have previously seen similar graphics glitches after suspend in another Java app I use (NetLogo).

**Comment by stefan-kolb** [comment] 2016-03-23 09:39
Have you tried another Look&Feel with OpenJDK than GTK, e.g., Metal?
Seems like its the combination of OpenJDK and GTKLookAndFeel.

**Comment by alefa** [comment] 2016-03-23 14:41
I just came back to my computer and JabRef showed the same partly blank GUI as before. So apparently it's not just OpenJDK. I will try a different Look-and-Feel now.

**Comment by stefan-kolb** [comment] 2016-04-05 07:37
@alefa Did a ddifferent L&F solve your issue?

**Comment by Siedlerchr** [comment] 2016-04-05 10:32
It would be interesting to know if that happens ot other java programs which use GTK as L+F

**Comment by alefa** [comment] 2016-04-05 12:40
@stefan-kolb So far it seems that the issue does not appear with the Metal Look+Feel. Though it looks pretty ugly, I must say.

**Comment by stefan-kolb** [comment] 2016-04-05 21:58
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813143

**Comment by alefa** [comment] 2016-04-06 06:47
@stefan-kolb Thanks for the link to the Debian bug report! I don't think this is the same bug, though. The bug reporter mentions that commenting out a specific line in /etc/openjdk-8/accessibility.properties solves the issue. On my system, this line is already commented out.

**Comment by stefan-kolb** [comment] 2016-04-06 09:34
Related/Duplciate of #393. Not much we can about this as the problem seems to be on the OpenJDK end. We keep #393 open for reference.

**Closed by stefan-kolb** 2016-04-06 09:34 UTC
Labels: bug, duplicate, linux, ui
