### ISSUE TITLE
Edit search cursor stays at the beginning

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4482] opened 2018-11-14 20:10 UTC
JabRef 5.0-dev--snapshot--2018-11-11--master--50875f967
Windows 10 10.0 amd64 
Java 1.8.0_172

Often when I hit the search bar if there is already a text, it expands visually, however, the search cursor is at the beginning of the bar and is not moving. On double-click it does not select the whole phrase, I have to use Delete to individually delete all the search text - Backspace is not working obviously. After this is done, I can search again with an empty search bar.

It would be desirable to 
- get rid of the visual UI of search bar expansion - steals half a second from searching every single time
- be able to quickly select the whole search and delete everything in the search bar
- fix the bug of a not moving cursor at the beginning of the search bar

**Comment by Ali96kz** [comment] 2018-11-15 04:17
Can't reproduce bug.
1) type text in a search bar.
2) clicked to row in a table 
3) Clicked to search bar 
Cursor is at the end. By double clicking select whole text.

Also you can use `Ctrl + F` that will automatically select whole text.

**Comment by DOFfactory** [comment] 2018-11-15 08:15
![jabref](https://user-images.githubusercontent.com/10846169/48539226-d761c180-e8b6-11e8-8dd5-4687bfb98534.png)

I don't know but at my end it shows me this ... the cursor stays _constantly_ at the beginning - does not move while I type.

**Comment by Ali96kz** [comment] 2018-11-15 08:20
I am new contributor. Can you say how did you open that search bar.
![jabref](https://user-images.githubusercontent.com/15236829/48539531-a1860280-e8e1-11e8-9c13-dcd615033554.png)

**Comment by Ali96kz** [comment] 2018-11-15 09:49
I reproduced issue. I will fix it.

**Comment by tobiasdiez** [comment] 2018-11-15 15:03
Just as a guess: the reason for this bug is the manual binding. If this is the case, then it should be easy to fix by using bindBidirectional

**Comment by DOFfactory** [comment] 2019-01-03 10:20
![search](https://user-images.githubusercontent.com/10846169/50632858-80d54300-0f49-11e9-9037-ecddb061977e.png)
Any updates on this? Still not working, moreover, some strange elements pop-up...

**Comment by tobiasdiez** [comment] 2019-10-07 18:27
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed by tobiasdiez** 2019-10-07 18:27 UTC
Labels: bug, search, ui
