### ISSUE TITLE
Automatic groups do not reflect changes to entries

### ISSUE THREAD

**Issue by juanmduran** [JabRef/jabref#2776] opened 2017-04-21 08:22 UTC
Hi everybody,

   In a previous thread I mentioned a few issues on crating Groups and adding references to those groups. I'll try to be more detailed here. 

I'm using JabRef 4.0.0-dev on OSX 10.12.4

So, I mentioned three issues:

Ok guys, so a little work on the groups shows the following issues:

A. The groups are not saved after quitting. Restarting JabRef means creating the groups again. Mind you that the entry "groups" in a given reference remains.

B. For "automatically create groups" (e.g., by keyword), it does not "automatically" add a new reference when a new keyword is added to that reference.

C. Working with groups seems to randomly freeze JabRef. I can't figure out in what specific situations. E.g., I just double clicked and it is now freeze.

Although I have not have any more point C issues, I do still have A and B. 

As for point A, here are some step by step procedure (@tobiasdiez)

1. Make any group (Static, dynamic or automatic)
2. Add a ref to the group
3. Save the DB and quit
4. Open JabRef. The groups are gone. HOWEVER....
      4.1 If you check any of the reference, in the "Group" field, they have assigned the right group. In fact, if you add the same group again, then all references appear in the group immediately. 

To me, the problem boils down to the Groups view that is not refreshing (or saving the groups).

As for point B, here is another step by step procedure + @tobiasdiez workaround

1. Make an automatic group by keyword
2. Instead of standard "drag and drop" (as I did in point 1), in the Keywords field of the selected reference, add a keyword (different from or identical to the keywords already in the group). 
3. Doing 1 and 2, I'd expect the new reference to show up in my newly created automatic group. But it does not. It only appears if I repeat point 1. 

@tobiasdiez suggested a workaround: "Your second problem is a known issue. You can switch to a second db and then back to your first and the subgroups are refreshed (as a workaround)."

I've tried this, but it messed things up. Call my main library X. While I keep open X, I add a new, blank library Y. What happens is three things: a) all the groups in X disappear (so not really a workaround, so I have the idea that I'm doing something wrong); b) the counter of entries "All entires" in X goes to 0; and c) the counter of entires "All entries" in Y has the right number of entries (that I should have in X). The only thing that remains the same are the entries in X and Y. While X remains with all the entires, Y is still blank.

Does this make any sense to you guys? I can make a video if I'm not sufficiently clear.

All the best,

**Comment by tobiasdiez** [comment] 2017-04-23 18:11
You point A seems to be a duplicate of https://github.com/JabRef/jabref/issues/2779, thus we will this issue to keep progress in your point B.

**Comment by lenhard** [comment] 2017-10-04 11:13
@juanmduran There have been quite some changes to the grouping code in the meantime. Can you please check if the error is still present in the newly released JabRef 4.0?

**Comment by lenhard** [comment] 2017-12-05 15:29
Since there has been no action for quite a while, I am closing this now. Feel free to reopen if you can confirm that the problem is still present.

**Closed by lenhard** 2017-12-05 15:29 UTC
Labels: enhancement, groups, waiting-for-feedback
