### ISSUE TITLE
Umlaute while adding entries via DOI

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5900] opened 2020-01-31 08:00 UTC
Please try to add an entry by DOI with 10.1007/s16024-020-00337-5 and look in the title.

The `ä` in "Technikaffinität" is misshandeld and appears as a black ? in JabRef (dev version 5.* on Windows 10).

**Comment by Siedlerchr** [comment] 2020-01-31 08:40
Seems like a similar problem to #5899

**Comment by AEgit** [comment] 2020-01-31 09:37
Yes, I think this issue is a duplicate of https://github.com/JabRef/jabref/issues/5899. See also https://github.com/JabRef/jabref/issues/5899#issuecomment-580658891

**Closed** 2020-01-31 20:54 UTC

**Comment by Siedlerchr** [comment] 2020-02-09 17:46
Could you please try the latest snapshot?
http://builds.jabref.org/master/

**Comment by AEgit** [comment] 2020-02-09 18:58
JabRef 5.0-beta.409--2020-02-09--6a9c915
Windows 10 10.0 amd64 
Java 13.0.2

The issue persists.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment] 2020-02-09 21:07
On Debian 10 the issue seams to be fixed.
