### ISSUE TITLE
Dragging an entry to a groupe stops jabref completely.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3057] opened 2017-07-29 09:09 UTC
JabRef version JabRef-4.0-beta2 on Windows 7 64

Steps to reproduce:

1. any entry
2. try to drag it to a group
3. JR goes into Nirvana

JR needs to be closed by the Task manager. Any reaction further. Serious
![grafik](https://user-images.githubusercontent.com/9216487/28743625-440667ac-744e-11e7-88f6-d9d0aae18a4a.png)
dragged Deutsch et al. to Kap10.

**Comment by lenhard** [comment] 2017-07-30 09:05
I think this is a duplicate of #3036

**Closed by lenhard** 2017-07-30 09:05 UTC
