### ISSUE TITLE
PDF Downloader downloads HTML source code instead if no access

### ISSUE THREAD

**Issue by Krzmbrzl** [JabRef/jabref#7452] opened 2021-02-17 11:42 UTC
JabRef 5.2--2020-12-24--6a2a512
Linux 5.4.0-59-generic amd64 
Java 15.0.1

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Import an entry via Browser extension for which one does not have acces rights for the PDF (e.g. https://onlinelibrary.wiley.com/doi/abs/10.1002/0470862106.ia615)
2. JabRef automatically downloads the PDF (or rather it tries to do so)
3. Instead of the PDF it downloads the HTML webpage that would pop up if I was to try to download the paper manually. Thus my "PDF" now only contains HTML source code

I have encountered this a few times by now and in all cases the downloaded "PDF" was a plain text file containg the HTML source code.
My suggestion for a mitigation would be to check the downloaded file and if it starts with plain text `<!DOCTYPE html>`, then assume the download has failed and remove the "PDF" again (restoring the file link with the download URL in JabRef).

**Comment by grundb** [comment] 2021-02-26 17:41
Me and a few friends, @kittytinythai, @keivanm, @binsu-kth and @Kayi1500, would like to resolve this issue for a course project in DD2480 Software Engineering Fundamentals at KTH Royal Institute of Technology. Do you have any suggestions or things we need to know before we get started?

**Comment by Siedlerchr** [comment] 2021-02-26 17:53
Welcome to JabRef! As a starting point make sure to follow our [conribution](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md)

Codewise the functionality of file downloading is handled here 
https://github.com/JabRef/jabref/blob/60cc355b0d397011ff475a947f2ee43dd5e3f4c2/src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java#L416

**Comment by BJaroszkowski** [comment] 2021-02-26 20:39
I have looked into this and I can confirm that there is an issue with how downloading files via URL is handled. Basically, `FileDownloadTask` does not throw an exception if the destination extension does not match the type of the file to be downloaded and not even when the URL is valid but does not exist. In the latter case `URLDownload` returns an empty input stream which is then copied to a destination file leaving us with an empty file in the file system.

The question is how to deal with that. The proposed solution would lead to the cases when after mistyping the URL the download process would fail silently without informing the user about what happened. A quick and dirty fix that I have implemented is to do a check within the `FileDownloadTask` that looks something like:

```
        URLDownload download = new URLDownload(source);
        if (!download.canBeReached() || (destination.toString().endsWith(".pdf") && !download.isPdf()) ) {
            throw new IOException("The provided URL is inaccessible or does not exist");
        }
```

This of course would only work for downloading files with .pdf extension. I think a better idea would be to do a similar check within `prepareDownloadTask` method of `LinkedFileViewModel` where we actually detect file extension. I can work on that but I would rather have one of the devs weigh in first.

**Comment by Siedlerchr** [comment] 2021-02-27 17:46
>I think a better idea would be to do a similar check within prepareDownloadTask method of LinkedFileViewModel where 
we actually detect file extension. I can work on that but I would rather have one of the devs weigh in first.

Thanks for looking into it, UrlDownload has a method for detecting the mime type of the file. Maybe you can use that in addition for checking with the empty File stream. Having empty files is not useful. It could be checked if a) is reachable and maybe give a warning if the mime type is HTML
But keep in mind that some users might want to save a snapshot of a website (e.g. for online sources from websites).

**Comment by grundb** [comment] 2021-02-28 15:57
We have now produced a draft PR for this (#7474), and we would appreciate any feedback. It seems much of the logic for saving the file as an html file was already implemented, but the problem was that the `getExternalFileTypeByMimeType` method ignored the optional parameter part of the mime type string:   https://github.com/JabRef/jabref/blob/1f775d7c5585bf7d9036e4fe55ebd2fb99b1e22a/src/main/java/org/jabref/gui/externalfiletype/ExternalFileTypes.java#L51-L64
This solution does not deal with the case of empty files as discussed by @BJaroszkowski, but this could of course be included (or addressed in a separate issue). We plan to add appropriate unit tests before a merge.

**Closed** 2021-03-14 22:13 UTC
Labels: fetcher, good first issue, import, type: enhancement
