### ISSUE TITLE
JabRef 3.3 file links containing blanks are broken if non-default viewer is set

### ISSUE THREAD

**Issue by gh-mike** [JabRef/jabref#1381] opened 2016-05-11 10:36 UTC
JabRef version 3.3 on Windows 10. After upgrading from version 3.1 all the file links containing blanks are broken when using Sumatra PDF. When trying to open a pdf file containing blanks, the pdf reader consider each piece of the file name as an independent file (each piece meaning each non-blank piece). This worked fine in 3.1. Tried to place quotes around the file name without success.

Steps to reproduce:
1. Install Sumatra PDF
2. Configure Sumatra PDF as the pdf reader (Options -> External programs -> Manage external file type -> edit pdf and set up Summatra PDF). Alternatively you can set up Sumatra as the defaul pdf reader in your system
3. Link a pdf file containing blanks in the name (for example "my example pdf file.pdf") under the entry editor -> General -> File -> +
4. Try to open the file and Summatra PDF will try to open four files (my, example, pdf, and file.pdf).

Ideally can configure Jabref to place quotes around the file name, when invoking the external reader.

**Comment by matthiasgeiger** [comment] 2016-05-11 11:08
Thanks for your report!

Confirmed if a PDF viewer is set manually in the "Manage external file type" dialog (not only sumatra but also other PDF viewers).

System default works with whitespace in the file names.

**Comment by Siedlerchr** [comment] 2016-05-11 12:58
Seems to be a problem with the settings than, because I worked on a fix for this in the opening methods.
Will look into that.

**Comment by stefan-kolb** [comment] 2016-05-12 12:36
Thank you for your report :+1:
This should be fixed in `blank-file-links`. Please try the latest build from http://builds.jabref.org/blank-file-links.

**Comment by matthiasgeiger** [comment] 2016-05-12 12:44
:+1: works for me.

**Closed** 2016-05-12 13:23 UTC
Labels: bug, windows
