### ISSUE TITLE
Import from CLI fails sometimes

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#7359] opened 2021-01-17 21:16 UTC
JabRef 5.2--2020-12-14--e9be339
Windows 10 10.0 amd64 
Java 14.0.2

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Go to https://arxiv.org/abs/1109.0517
2. Send to JabRef using Browser Extension
3. Get following error: 

> Importing in unknown format: curves Error opening file 'curves': Could not find a suitable import format. Importing in unknown format: with Error opening file 'with': Could not find a suitable import format. Importing in unknown format: complemetary Error opening file 'complemetary': Could not find a suitable import format. Importing in unknown format: series} Error opening file 'series}': Could not find a suitable import format. Importing in unknown format: url Error opening file 'url': Could not find a suitable import format. Importing in unknown format: = Error opening file '=': Could not find a suitable import format. %d [%thread] %-5level %logger - %msg%n java.nio.file.InvalidPathException: Illegal char <:> at index 5: {http://arxiv.org/abs/1109.0517} 	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?] 	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?] 	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?] 	at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:?] 	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:?] 	at java.nio.file.Path.of(Unknown Source) ~[?:?] 	at org.jabref.cli.ArgumentProcessor.importFile(Unknown Source) ~[org.jabref:?] 	at org.jabref.cli.ArgumentProcessor.importAndOpenFiles(Unknown Source) ~[org.jabref:?] 	at org.jabref.cli.ArgumentProcessor.processArguments(Unknown Source) ~[org.jabref:?] 	at org.jabref.cli.ArgumentProcessor.<init>(Unknown Source) ~[org.jabref:?] 	at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?] 	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?] 	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?] 	at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?] 	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?] 	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?] 	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[org.jabref.merged.module:?] 	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source) ~[org.jabref.merged.module:?] 	at java.lang.Thread.run(Unknown Source) [?:?]

For some reason, JabRef tries to find the import format although we call it with "--importBibtex".

**Comment by Siedlerchr** [comment] 2021-01-17 21:18
I think this is the same underlying bug as in https://github.com/JabRef/jabref/pull/7347
>egal char <:> at index 5: {http://arxiv.org/abs/1109.0517} at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?] at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:

**Comment by LyzardKing** [comment] 2021-01-18 08:36
I can't reproduce this issue on Linux.
Both the snap and flatpak import the reference correctly.

**Comment by tobiasdiez** [comment] 2021-01-18 13:25
Thanks, that's good to know. Than it might be a problem with the powershell script that is used as the communication bridge between Firefox and JabRef.

**Comment by Siedlerchr** [comment] 2021-01-18 18:47
The bibtex I receive on mac looks like this: The error in your stacktrace is coming from importFile, but that is never called when I import when debugging.

```bibtex
@article{matheus_explicit_2012,
	title = {Explicit {Teichm}{\textbackslash}"uller curves with complemetary series},
	url = {http://arxiv.org/abs/1109.0517},
	abstract = {We construct an explicit family of arithmetic Teichm{\textbackslash}"uller curves \${\textbackslash}mathcal\{C\}\_\{2k\}\$, \$k{\textbackslash}in{\textbackslash}mathbb\{N\}\$, supporting \${\textbackslash}textrm\{SL\}(2,{\textbackslash}mathbb\{R\})\$-invariant probabilities \${\textbackslash}mu\_\{2k\}\$ such that the associated \${\textbackslash}textrm\{SL\}(2,{\textbackslash}mathbb\{R\})\$-representation on \$L{\textasciicircum}2({\textbackslash}mathcal\{C\}\_\{2k\}, {\textbackslash}mu\_\{2k\})\$ has complementary series for every \$k{\textbackslash}geq 3\$. Actually, the size of the spectral gap along this family goes to zero. In particular, the Teichm{\textbackslash}"uller geodesic flow restricted to these explicit arithmetic Teichm{\textbackslash}"uller curves \${\textbackslash}mathcal\{C\}\_\{2k\}\$ has arbitrarily slow rate of exponential mixing.},
	urldate = {2021-01-18},
	journal = {arXiv:1109.0517 [math]},
	author = {Matheus, Carlos and Weitze-Schmithüsen, Gabriela},
	month = aug,
	year = {2012},
	note = {arXiv: 1109.0517},
	keywords = {Mathematics - Dynamical Systems},
	annote = {Comment: 46 pages, 10 figures. Final version (based on the referee report). To appear in Bulletin SMF},
	file = {arXiv Fulltext PDF:https\://arxiv.org/pdf/1109.0517.pdf:application/pdf}
}
```

And from your stacktrace I see why it fails:
https://github.com/JabRef/jabref/blob/e66f5be7d82c7a7618fe327fe958ec57a25ea598/src/main/java/org/jabref/cli/ArgumentProcessor.java#L99-L118

**Comment by Siedlerchr** [comment] 2021-07-19 18:25
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2021-07-19 18:25 UTC
Labels: cli, import, os: windows, type: bug 🐛
