### ISSUE TITLE
Command+C from some fields in the "required fields" does not get what I want

### ISSUE THREAD

**Issue by iTao8** [JabRef/jabref#2842] opened 2017-05-15 11:37 UTC
JabRef 4.0.0-dev--snapshot--2017-05-14--master--d6b6235a4
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

Steps to reproduce:
1. open the .bib file
2. select an entry
3. select the journal name
4. Command +C
5. Command +V into an text file, but I get the whole source file, including authors, title, journal name, pages, url and so on

PS, the entry editor still does not display properly.

**Comment by tobiasdiez** [comment] 2017-05-19 13:19
I close this as a duplicate of #2855 (as the underlying problem is the same: the keybindings associated to the main table take priority over the entry editor).

**Closed by tobiasdiez** 2017-05-19 13:19 UTC
Labels: osx
