### ISSUE TITLE
Some confusion about rename PDFs in cleanup entries

### ISSUE THREAD

**Issue by tangjie1992** [JabRef/jabref#2434] opened 2016-12-27 02:12 UTC
JabRef version 3.8  on Windows 7, Mac OS X 10.12.1 and CentOS 6.5 

Steps to reproduce:
When use cleanup entries, I found that there is a difference across platform. Usually  I want to rename PDFs to given filename format pattern
1. Windows and Mac OS have filename format pattern: \bibtexkey
2. CentOS 6.5 have filename format patter: \bibtexkey\begin{title}-\format{RemoveBrackets}{\title}\end{title}
Due to the difference, I have to copy all my PDFs to another platform to rename them.
Is there some thing I can do more convenient and efficient.

```
Put the excerpt of the log file here
```

**Comment by matthiasgeiger** [comment] 2016-12-27 07:52
Sorry if I miss something but why don't you just change the settings of your CentOS machine to the same pattern `\bibtexkey`?

**Comment by AEgit** [comment] 2016-12-27 13:41
As a follow-up to matthiasgeiger see here:
http://help.jabref.org/en/BibtexKeyPatterns

**Comment by tangjie1992** [comment] 2016-12-29 04:22
@matthiasgeiger  
Thank you for you kind help. Can you give me some further advice?
For CentOS 6.5, 
![screenshot](https://cloud.githubusercontent.com/assets/13535079/21536670/a9f6a1d8-cdc0-11e6-8df8-bd855e126132.png)

For macOS
![screen shot 2016-12-29 at 11 19 34](https://cloud.githubusercontent.com/assets/13535079/21536671/b00cd4f2-cdc0-11e6-90e4-40589baf64e6.png)

I prefer the filename format pattern on macOS
How can i change the filename format pattern on CentOS to match that on macOS.

**Comment by tangjie1992** [comment] 2016-12-29 04:27
@matthiasgeiger 
Sorry to bother you, but I think I have found the solution to my confusion.
Thank you so much
![screen shot 2016-12-29 at 12 24 29](https://cloud.githubusercontent.com/assets/13535079/21536771/11a2700e-cdc2-11e6-93ab-8fd89c1af716.png)

**Comment by matthiasgeiger** [comment] 2016-12-29 06:28
Right this is the setting I meant :wink: 

As this is no bug I close this issue.

**Closed by matthiasgeiger** 2016-12-29 06:28 UTC

**Comment by koppor** [comment] 2016-12-29 08:27
Yes, @tangjie1992 should reset his preferences to get the same behavior on MacOSX.

I think, this refs https://github.com/koppor/jabref/issues/166. @tangjie1992 I assume on MacOSX, the icon on the left in the toolbar shows emacs, not texstudio, am I right?

**Comment by tangjie1992** [comment] 2016-12-29 12:24
@koppor  Sorry, I think I have not get what you mean?
Is it this one?

![screen shot 2016-12-29 at 20 20 37](https://cloud.githubusercontent.com/assets/13535079/21543768/4ff7972a-ce04-11e6-8e85-635ebc52a506.png)

**Comment by koppor** [comment] 2016-12-29 12:32
Yes, it is that one. It seems, you really hit https://github.com/koppor/jabref/issues/166 on Mac OSX, too. We currently do not know how to fix it. Please reset your preferences to ensure that everything works as intended 😇 

![grabbed_20161229-133213](https://cloud.githubusercontent.com/assets/1366654/21543948/3f296fc4-cdcb-11e6-93c9-6bbfd2cad8f3.png)
