### ISSUE TITLE
New entry, select type, is crippled

### ISSUE THREAD

**Issue by HainesB** [JabRef/jabref#1120] opened 2016-04-06 16:05 UTC
JabRef version <version as shown in the about box> on <Windows 10|Ubuntu 14.04|Mac OS X 10.8|...>
Hint: If you use a [development version](http://builds.jabref.org/master/), ensure that you use the latest one.

Steps to reproduce:

1. ...
2. ...
3. ...

If applicable, excerpt of the bibliography file, screenshot, and excerpt of log (available in the error console)

**Comment by HainesB** [comment] 2016-04-06 16:08
C-n opens new entry, with Article button selected. Cannot do ENTER to open new article entry and cannot use arrow keys to change default selection. Mouse click is only way to open an entry type.

**Comment by simonharrer** [comment] 2016-04-07 07:48
Seems to be a duplicate of #615

**Closed** 2016-04-07 07:48 UTC
Labels: duplicate
