### ISSUE TITLE
[Workaround in comments] ESC removes information from entry editor

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#10764] opened 2024-01-10 07:11 UTC
### JabRef version

5.12 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I am on JabRef 5.12--2023-12-24--4233bad
Linux 6.6.10-200.fc39.x86_64 amd64 
Java 21.0.1 
JavaFX 21.0.1+6

1. type some notes in a field in the entry editor, and then press `ESC`. 
2. The information in the field disappears 
3. cannot be brought back with `CTRL+Z`

That is sad because the user, at least I, might accidentally press `ESC`.

I consider this a bug because I think this is not intended. But am happy to revise thi as a feature request if you think so.

**Comment by Siedlerchr** [comment] 2024-01-10 07:38
Does this also occur in the 5.13 were we downgraded javafx again?

**Comment by Siedlerchr** [comment] 2024-01-10 08:33
you can use latest main we merged it into main

**Comment by ilippert** [comment] 2024-01-10 09:06
Thanks,

on 

JabRef 5.13--2024-01-09--01c3e15
Linux 6.6.10-200.fc39.x86_64 amd64 
Java 21.0.1 
JavaFX 20+19

it is still the case

**Comment by HoussemNasri** [comment] 2024-01-10 18:06
I haven't found the reason behind this behavior or a way to fix it but found a workaround.

**Workaround**: click on the entry again to remove the focus from the entry editor and press `Ctrl+Z` or press the undo button above in the main toolbar.

**Comment by Siedlerchr** [comment] 2024-01-13 19:40
I can confirm the same behavior under macOS. To me it seems like some javafx thingy default behavior. No idea though

**Comment by ror3d** [comment] 2024-03-18 14:36
Just stumbled into this with a more recent version (I use vim a lot and I have the pressing Esc is kind of automatic)

Sadly I don't know javafx enough to easily look into it

**Comment by JEANPRBT** [comment] 2024-04-09 17:41
Hi, I can try to tackle that issue if you wish ! I was able to reproduce this behavior.

**Comment by Siedlerchr** [comment] 2024-04-09 18:07
@JEANPRBT  I think this more a javafx standard behavior.

**Comment by JEANPRBT** [comment] 2024-04-09 18:43
> @JEANPRBT  I think this more a javafx standard behavior. 

Maybe we can close this issue then. :)

**Comment by ilippert** [comment] 2024-04-09 18:53
Then, I'd tag it as depending on external...
But maybe checking, communicating this upstream and reporting here where the issue is placed would be good.

Sorry, am not of much help these weeks.
--

**Comment by ThiloteE** [comment] 2024-04-09 18:56
I would suggest to leave it open, as a kind of "documentation", as "undo" is an important feature, but since issue might depend on external and there is also a workaround I would set the priority to low.

**Comment by koppor** [comment] 2024-04-11 09:58
> Hi, I can try to tackle that issue if you wish ! I was able to reproduce this behavior.

We need a minimal working example to report to the JavaFX community.

Maybe fork https://github.com/Siedlerchr/javafxreproducer and just add a text field @JEANPRBT . Maybe with a label above the text field with the steps a user should make to reproduce the behavior and what is the accepted behavior.

I know, this is kind of trivial intended behavior. However, the JavaFX implementors are in their JavaFX world and we need to get close to their world to explain.

**Comment by JEANPRBT** [comment] 2024-04-11 12:57
Hi, I can do that but what should I do next ? Should I file an issue on official Open JFX [issue tracker](https://bugs.openjdk.org/browse/JDK-8322251?filter=39543) with a link to my fork ?

**Comment by Siedlerchr** [comment] 2024-04-11 13:57
You can only submit a bug report via https://bugreport.java.com/bugreport/ if you can reproduce it

**Comment by JEANPRBT** [comment] 2024-04-13 11:46
I tried to reproduce the bug using a minimalistic example, you can see [here](https://github.com/JEANPRBT/minimaljavafx). However, using the original `javafx.scene.control.TextField`the bug does not appear. Any idea how is JabRef implementing its field editors ?

**Comment by koppor** [comment] 2024-04-13 12:25
@JEANPRBT Thank you for building the reproducer and reporting that is a JabRef issue.

Now, I could narrow it down. Will submit a fix soon. This comment is only to prevent anyone else to work on this now. Focus on other things.

>  Any idea how is JabRef implementing its field editors ?

Let's look at org.jabref.gui.fieldeditors.FieldEditors?

I tested it. It occurres in all kinds of editors. ESC just clears the field.

No special code.

Then, let's investiage KeyBinding.java.

ESC appears twice. One unused. One used. Used in ALL txt fields (See TextInputKeyBindings). Introduced at https://github.com/JabRef/jabref/pull/8829.

**Closed** 2024-04-15 20:32 UTC
Labels: bug, entry-editor, keybinding
