### ISSUE TITLE
Automatic Bug Report - 20170707161031

### ISSUE THREAD

**Issue by b-sipos** [JabRef/jabref#2979] opened 2017-07-07 14:16 UTC
JabRef 4.0.0-beta
Windows 7 6.1 amd64 
Java 1.8.0_112

Steps to reproduce:

1. Try get Bibtex data from DOI

Paste your log details here.
<details>
<summary>Detail information:</summary>

```
Opening: Z:\Sales\Product information\Applications\Publications\JabRef\Pub-list-attocube-dev.bib
Info cannot be found
org.jabref.logic.importer.FetcherException: Connection error
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:65)
	at org.jabref.gui.mergeentries.FetchAndMergeWorker.doInBackground(FetchAndMergeWorker.java:47)
	at org.jabref.gui.mergeentries.FetchAndMergeWorker.doInBackground(FetchAndMergeWorker.java:22)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1007%2F978-3-319-19231-4_2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:152)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:166)
	at org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(DoiFetcher.java:55)
	... 8 more
Caused by: java.io.IOException: Server returned HTTP response code: 406 for URL: https://data.crossref.org/10.1007%2F978-3-319-19231-4_2
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:294)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:302)
	... 11 more

```

</details>

**Comment by koppor** [comment] 2017-07-07 14:24
This is a duplicate of https://github.com/JabRef/jabref/issues/2898.

**Closed by koppor** 2017-07-07 14:24 UTC
Labels: fixed-in-devBuilds
