### ISSUE TITLE
Choose installation folder in Windows

### ISSUE THREAD

**Issue by jorgman1** [JabRef/jabref#5617] opened 2019-11-15 21:31 UTC
**Is your suggestion for improvement related to a problem? Please describe.**
The new installation script in windows (.msi) installs JabRef directly without asking the destination folder.

**Describe the solution you'd like**
It would be nice, to choose the destination.

**Comment by AEgit** [comment] 2019-11-15 21:55
Duplicate of https://github.com/JabRef/jabref/issues/5580

**Closed** 2019-11-16 05:30 UTC
