### ISSUE TITLE
Improve DOI import failure dialog. Do not show exception in the gui

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8743] opened 2022-05-01 20:20 UTC
### JabRef version

5.6 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. DOI in question: `10.1109/REW.2016.24`
2. Try to get bibliography data from it
3. `Lookup DOI` gives `10.1109/rew.2016.039` which works

### Appendix

![grafik](https://user-images.githubusercontent.com/6171135/166163043-d4f1d6a4-b337-4efb-a4bd-e7e43742ac8b.png)

<details>

<summary>Log File</summary>

```
org.jabref.logic.importer.FetcherException: No DOI data exists
	at org.jabref@5.7.19/org.jabref.logic.importer.fetcher.DoiFetcher.performSearchById(Unknown Source)
	at org.jabref@5.7.19/org.jabref.gui.mergeentries.FetchAndMergeEntry.lambda$fetchAndMerge$0(Unknown Source)
	at org.jabref@5.7.19/org.jabref.gui.util.BackgroundTask$1.call(Unknown Source)
	at org.jabref@5.7.19/org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source)
	at org.jabref.merged.module@5.7.19/javafx.concurrent.Task$TaskCallable.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: https://doi.org/10.1109/REW.2016.24
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at org.jabref@5.7.19/org.jabref.logic.net.URLDownload.asString(Unknown Source)
	at org.jabref@5.7.19/org.jabref.logic.net.URLDownload.asString(Unknown Source)
	... 11 more
Caused by: java.io.FileNotFoundException: https://doi.org/10.1109/REW.2016.24
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at org.jabref@5.7.19/org.jabref.logic.net.URLDownload.openConnection(Unknown Source)
	... 13 more
```

</details>

**Comment by claell** [comment] 2022-05-01 20:21
I guess, the DOI was wrongly imported from the PDF document. However, it should not result in an unhandled exeception, I'd assume.

**Comment by ThiloteE** [comment] 2022-05-03 16:13
JabRef's unhandled exceptions look very ugly, but they provide valuable information for maintainers, people that handle the code and sometimes it also holds information that can be understood by users.

In this one you can see that "No DOI data exists" is right at the top of the exception, which is pretty straight forward: You should check if the DOI you entered is correctly written, or if the server JabRef queries DOI data from is working correctly (that would be doi.org, which in turn queries crossref). A few days back, I tried your first DOI `10.1109/REW.2016.24` manually at doi.org and it did not return data and therefore there is a high chance, this DOI does not exist as compared to an error in JabRef's DOI fetcher code.

I don't know how you ended up with these DOI's but if you imported them from PDF, that would explain things: 1. Somebody could have attached wrong metadata to the PDF. Mistakes happen. 2. If you use Grobid, it's machine learning techniques are not yet perfected and should be taken as a rough guess about the data. Currently, I would strongly advise Grobid users to manually correct the imported data and not take it for its face value.

**Comment by Siedlerchr** [comment] 2022-05-03 16:59
Solution: In the DOI Fetcher check if the content type of the server response is HTML or better, the HTTP status is 404, then add a meaningful message, e.g. DOI not found.  It's not the ideal solution, but nonetheless throw the FetcherException.
LOG the exception in the event log, but do not show it to the users.

Related code: 
https://github.com/JabRef/jabref/blob/2929900640a9051328a578317acc1fca2bbb1266/src/main/java/org/jabref/logic/importer/fetcher/DoiFetcher.java#L76-L85

**Comment by zkl-ai** [comment] 2022-05-04 12:31
Hello, could you assign this to me?  I think this issue is quite interesting.

**Comment by zkl-ai** [comment] 2022-05-04 15:11
OK, I will try it early

**Comment by zkl-ai** [comment] 2022-05-08 09:12
> check if the content type of the server response is HTML

Hi, I have reproduced this exception dialog. But I haven't understood the first part of the solution which is check if the content-type  of the server response is HTML or better you mentioned. Can you explain this to me? I‘m a little confused about the `download.addHeader("Accept", MediaTypes.APPLICATION_BIBTEX); ` and the content-type. Are they the same thing?

**Comment by Siedlerchr** [comment] 2022-05-08 10:20
@zkl-ai  Yes, the Accept Header says: I want to get content in this format. Ideally, the server responds in this format.
The problem is that the UrlDownload.asString just gets whatever the serer provides. It does not check the statusCode or the content-type of the returned response.  So you need to modify that part to check for stauts code 404

**Comment by zkl-ai** [comment] 2022-05-08 10:24
> @zkl-ai Yes, the Accept Header says: I want to get content in this format. Ideally, the server responds in this format. The problem is that the UrlDownload.asString just gets whatever the serer provides. It does not check the statusCode or the content-type of the returned response. So you need to modify that part to check for stauts code 404

Thank you for your prompt reply. Your explanation is very clear! I need to think carefully about how to realize this requirement.

**Comment by claell** [comment] 2022-05-09 10:06
Also, possibly one can differentiate between DOI data not found and DOI server not available (if not already done so).

**Comment by zkl-ai** [comment] 2022-05-10 06:07
> Also, possibly one can differentiate between DOI data not found and DOI server not available (if not already done so).

I will think about it

**Comment by zkl-ai** [comment] 2022-05-19 10:35
@Siedlerchr I have found that the `asString(StandardCharsets.UTF_8)` is as below when the doi is `10.1109/REW.2016.24`
![image](https://user-images.githubusercontent.com/72965042/169269983-d6a1f4a4-8de9-40b2-abc6-507dcf0ea1d2.png)
The exception is actually `java.io.FileNotFoundException` in ` private URLConnection openConnection() throws IOException ` and this exception will be caught in the `IOException e`
![image](https://user-images.githubusercontent.com/72965042/169270418-c2266ca9-6b14-46af-bf02-873b5cf07112.png)
But I haven't found a method to check the statusCode or the content-type of `download.asString()`.  I noticed that you have mentioned "maybe use Unirest.get for this", I have tried this method like `Unirest.get()` and this method is to get the httpRequest, and I actually want is to get the httpResponse. Is that means I need to construct a http connection according to this httpRequest? I'm not sure. I think this way is quite slow and lower the performance. Can you give me some advice?

**Comment by Siedlerchr** [comment] 2022-05-19 19:14
@zkl-ai  Have a look at the UrlDownload class, it already does this internally. You need to check there in openConnection

**Comment by zkl-ai** [comment] 2022-05-21 11:43
@Siedlerchr @claell  I have figured out the logic. Now, I plan to modify the exception by this way. First, check the status code in the `URLDownload.openConnection` (in which it only check the 3xx status code). In the openConnection Method, if the status code is 4xx then throw  an IOException with localization message "Client Error 4xx" and if the status code is 5xx then throw an IOException with localization message "Server Error 5xx". And dispatch these exceptions when show them. If it is "Client Error 4xx" show user "DOI data not found" and if it is "Server Error 5xx" show user "DOI server not available". Is this plan OK?

**Comment by Siedlerchr** [comment] 2022-05-21 13:38
@zkl-ai  Yes this sounds good!

**Comment by ThiloteE** [comment] 2022-05-21 23:35
This is the picture that pops into my mind. Not sure if you were thinking of something different or if it is even technically possible with javafx. Just posting for inspiration :)

![grafik](https://user-images.githubusercontent.com/73715071/169672203-2c9bf49e-9470-4c3c-8e90-7c74f6c6d796.png)

**Comment by zkl-ai** [comment] 2022-05-22 04:52
> DOI server not available

@ThiloteE I have checked the `private final DialogService dialogService`. The title `Lookup DOI` and content `DOI data not found` of information service it supports can be edited, there is no such field likes `Show Details` . I implement this with two methods. 
- first
![image](https://user-images.githubusercontent.com/72965042/169679018-a1e09de1-bd24-43b3-bb3a-b85d854328e6.png)

- second 
![image](https://user-images.githubusercontent.com/72965042/169679278-ddd4a289-a2f7-4e0d-b58c-7029072ca82b.png)

which one do you think is better?

**Comment by zkl-ai** [comment] 2022-05-22 13:00
@Siedlerchr @ThiloteE I want to construct a test to test the 5xx http status code, but I tried many ways can not the a http response with 5xx status code? Can you give me some advice?

**Comment by zkl-ai** [comment] 2022-05-22 13:14
> @Siedlerchr @ThiloteE I want to construct a test to test the 5xx http status code, but I tried many ways can not the a http response with 5xx status code? Can you give me some advice?

I found a very useful website to simulate any status code. http://httpstat.us/503 this will return 503 status code

**Comment by Siedlerchr** [comment] 2022-05-22 14:27
Ah that's cool! THe dialog in the PR looks good so far!

**Closed** 2022-08-06 19:44 UTC
Labels: ui, import, good first issue, Logging
