### ISSUE TITLE
Adding a file link leads to a freeze

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#2820] opened 2017-05-04 19:08 UTC
JabRef version 

- JabRef-4.0.0-dev--snapshot--2017-05-03--master--a16e6123d.jar
- running with Linux Mint 18.1, with file manager Nemo 3.2.2

- java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Steps to reproduce:

1. In the editor, select "General" tab
2. In the File field, press + to attach a file link
3. The file dialogue opens, and JabRef freezes
4. JabRef and the file dialogue window have to be closed with "Force Quit"

**Comment by tobiasdiez** [comment] 2017-05-04 22:11
I cannot reproduce this problem.
Can you please open the error console before you press the plus button and see if an error is reported there. Thanks.

**Comment by wujastyk** [comment] 2017-05-04 23:31
Moved the cursor to "General" tab, and have not yet pressed "+":


​
​
Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
at com.sun.javafx.text.PrismTextLayout.reuseRuns(PrismTextLayout.java:969)
at com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1019)
at
com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:223)
at com.sun.javafx.text.PrismTextLayout.getLines(PrismTextLayout.java:228)
at com.sun.javafx.scene.control.skin.Utils.getLineHeight(Utils.java:114)
at
com.sun.javafx.scene.control.skin.TextAreaSkin.updateFontMetrics(TextAreaSkin.java:1019)
at
com.sun.javafx.scene.control.skin.TextAreaSkin.<init>(TextAreaSkin.java:517)
at
org.jabref.gui.fieldeditors.EditorTextArea$1.<init>(EditorTextArea.java:48)
at
org.jabref.gui.fieldeditors.EditorTextArea.addToContextMenu(EditorTextArea.java:48)
at org.jabref.gui.fieldeditors.SimpleEditor.<init>(SimpleEditor.java:25)
at
org.jabref.gui.fieldeditors.FieldEditors.getForField(FieldEditors.java:55)
at
org.jabref.gui.entryeditor.EntryEditorTab.setupPanel(EntryEditorTab.java:156)
at org.jabref.gui.entryeditor.EntryEditorTab.<init>(EntryEditorTab.java:82)
at
org.jabref.gui.entryeditor.EntryEditor.addGeneralTabs(EntryEditor.java:349)
at
org.jabref.gui.entryeditor.EntryEditor.setupFieldPanels(EntryEditor.java:328)
at org.jabref.gui.entryeditor.EntryEditor.<init>(EntryEditor.java:234)
at org.jabref.gui.BasePanel.getEntryEditor(BasePanel.java:1496)
at
org.jabref.gui.maintable.MainTableSelectionListener.editSignalled(MainTableSelectionListener.java:189)
at
org.jabref.gui.maintable.MainTableSelectionListener.mouseClicked(MainTableSelectionListener.java:230)
at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
at java.awt.Component.processMouseEvent(Component.java:6536)
at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
at java.awt.Component.processEvent(Component.java:6298)
at java.awt.Container.processEvent(Container.java:2236)
at java.awt.Component.dispatchEventImpl(Component.java:4889)
at java.awt.Container.dispatchEventImpl(Container.java:2294)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4534)
at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
at java.awt.Container.dispatchEventImpl(Container.java:2280)
at java.awt.Window.dispatchEventImpl(Window.java:2746)
at java.awt.Component.dispatchEvent(Component.java:4711)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
at java.awt.EventQueue$4.run(EventQueue.java:731)
at java.awt.EventQueue$4.run(EventQueue.java:729)
at java.security.AccessController.doPrivileged(Native Method)
at
java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
at
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
at
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
at
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
​

**Comment by Siedlerchr** [comment] 2017-05-05 19:12
I just got the same Exception, but from a different action, the problem is most likely that there is still some Fx stuff called in the Swing Thread: http://stackoverflow.com/questions/18434540/nullpointerexception-when-using-javafx

```
21:08:59.707 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
	at com.sun.javafx.text.PrismTextLayout.reuseRuns(PrismTextLayout.java:969) ~[jfxrt.jar:?]
	at com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1019) ~[jfxrt.jar:?]
	at com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:223) ~[jfxrt.jar:?]
	at com.sun.javafx.text.PrismTextLayout.getLines(PrismTextLayout.java:228) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.Utils.getLineHeight(Utils.java:114) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.TextAreaSkin.updateFontMetrics(TextAreaSkin.java:1019) ~[jfxrt.jar:?]
	at com.sun.javafx.scene.control.skin.TextAreaSkin.<init>(TextAreaSkin.java:517) ~[jfxrt.jar:?]
	at org.jabref.gui.fieldeditors.EditorTextArea$1.<init>(EditorTextArea.java:48) ~[bin/:?]
	at org.jabref.gui.fieldeditors.EditorTextArea.addToContextMenu(EditorTextArea.java:48) ~[bin/:?]
	at org.jabref.gui.fieldeditors.SimpleEditor.<init>(SimpleEditor.java:25) ~[bin/:?]
	at org.jabref.gui.fieldeditors.FieldEditors.getForField(FieldEditors.java:55) ~[bin/:?]
	at org.jabref.gui.entryeditor.EntryEditorTab.setupPanel(EntryEditorTab.java:156) ~[bin/:?]
	at org.jabref.gui.entryeditor.EntryEditorTab.<init>(EntryEditorTab.java:82) ~[bin/:?]
	at org.jabref.gui.entryeditor.EntryEditor.addOtherTab(EntryEditor.java:383) ~[bin/:?]
	at org.jabref.gui.entryeditor.EntryEditor.setupFieldPanels(EntryEditor.java:324) ~[bin/:?]
	at org.jabref.gui.entryeditor.EntryEditor.<init>(EntryEditor.java:234) ~[bin/:?]
	at org.jabref.gui.BasePanel.getEntryEditor(BasePanel.java:1496) ~[bin/:?]
	at org.jabref.gui.maintable.MainTableSelectionListener.listChanged(MainTableSelectionListener.java:124) ~[bin/:?]
```

**Comment by tobiasdiez** [comment] 2017-05-18 14:38
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Closed by tobiasdiez** 2017-05-18 14:38 UTC
Labels: entry-editor, waiting-for-feedback
