### ISSUE TITLE
Cutting some of the bibtexkey raises error: Bale13 -> Bal13

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#5708] opened 2019-12-03 20:07 UTC
JabRef 5.0.0-dev--2019-11-28----ce0e8870c
Windows 7 6.1 amd64 
Java 13.0.1

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. I imported an entry via zotero (since jabfox doesnot work
2. the resulting bibtexkey has been e.g. Bale13 or Heinrich87
3. These I reduce to Bal13 or Hei87. 
4. Immediately an java error is shown.
5. Once the error is clicked away, a second attempt to change bixtexkey works flawlessly.

<details>
  <summary>Log File</summary>
  
  ```
  java.lang.StringIndexOutOfBoundsException: begin 3, end 8, length 5
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl$2.computeValue(Unknown Source)
	at org.jabref.merged.module/javafx.beans.binding.StringBinding.get(Unknown Source)
	at org.jabref.merged.module/javafx.beans.binding.StringBinding.get(Unknown Source)
	at org.jabref.merged.module/javafx.beans.binding.StringExpression.getValue(Unknown Source)
	at org.jabref.merged.module/javafx.beans.binding.StringExpression.getValue(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.StringPropertyBase.get(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.ReadOnlyStringWrapper$ReadOnlyPropertyImpl.get(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.ReadOnlyStringWrapper$ReadOnlyPropertyImpl.get(Unknown Source)
	at org.jabref.merged.module/javafx.beans.binding.StringExpression.getValue(Unknown Source)
	at org.jabref.merged.module/javafx.beans.binding.StringExpression.getValue(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.ReadOnlyStringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.ReadOnlyStringWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module/javafx.beans.property.StringPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.beans.binding.StringBinding.invalidate(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.markInvalid(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl.lambda$new$0(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextField$TextFieldContent.delete(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceText(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl.updateContent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceText(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceText(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl.replaceSelection(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.TextInputControl.deleteNextChar(Unknown Source)
	at org.jabref.merged.module/javafx.scene.control.skin.TextFieldSkin.deleteChar(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextFieldBehavior.deleteChar(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.deleteNextChar(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$new$14(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$KeyHandler.process(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene.processKeyEvent(Unknown Source)
	at org.jabref.merged.module/javafx.scene.Scene$ScenePeerListener.keyEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.handleKeyEvent(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.View.notifyKey(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
  ```
</details>

**Comment by Siedlerchr** [comment] 2019-12-04 07:39
Cannot reproduce this under Windows 10

**Comment by tobiasdiez** [comment] 2019-12-04 11:36
I also had this. It's not restricted to the bibtex key and also occurs for other fields.

**Comment by tobiasdiez** [comment] 2019-12-23 09:37
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by bernhard-kleine** [comment] 2019-12-23 20:48
Unfotunately, it is not.
JabRef 5.0-beta.30--2019-12-23--51d6986 -- Windows 7 6.1 amd64  -- Java 13.0.1
I had an almost empty library with 1 empty and a second entry:
![grafik](https://user-images.githubusercontent.com/9216487/71379941-a2ea2a00-25cd-11ea-8af6-c9a4555d9583.png)

- I change Gu09 to Gune2019
- I saved the library
- I changed Gune2019 to Gu09.
- When ending the delete, the original error occured again.

**Comment by tobiasdiez** [comment] 2019-12-24 08:55
@koppor Apparently the workaround does not fix the original issue. I would propose to temporarily disable the X11 support until your fix is merged into the jdk. What do you think?

**Comment by koppor** [comment] 2019-12-24 10:09
I tried to select some text and then press Ctrl+X. It worked with my fix. What else do I need to replicate the issue?

**Comment by koppor** [comment] 2019-12-24 10:12
Well, OK for me to get JabRef usable... - Maybe, I'll have time at this year to work on that again.

**Comment by tobiasdiez** [comment] 2019-12-24 12:53
It does not happen always, I need to try a few times before I trigger this bug. Especially now that there is some non-async going on because of the `Platform.invokeLater`.

**Comment by bernhard-kleine** [comment] 2020-02-11 11:51
As of today and the snapshot from 2020-02-29, there is only the "library has been changed ...." error, no java error AFAICS. After clicking "dismiss", the error does not occur any futher.  Can be closed in my humble opinion.

**Closed** 2020-02-11 11:59 UTC
Labels: bug 🤹‍♂️, entry-editor

**Comment by koppor** [comment] 2020-02-12 05:32
I don't see any PR referenced here. Does this relate to https://github.com/openjdk/jfx/pull/73?
