### ISSUE TITLE
Ignore initial unprotected uppercase in translated titles

### ISSUE THREAD

**Issue by ryan-carpenter** [JabRef/jabref#10459] opened 2023-10-07 13:17 UTC
Some databases store translated titles in the `title` field, surrounded by square brackets like this.

`title = {[Entry with a translated title]}`

Because the title phrase begins at the second position of the title string JabRef warns that the initial uppercase letter needs to be protected. To avoid matching this pattern, the regex could include something like `[A-Z](?<!^\[.)` or `(?<^!\[)[A-Z]`.

![image](https://github.com/JabRef/jabref/assets/23321102/b02629f3-ac7c-4eb7-8cae-dcd2452f7e09)

![image](https://github.com/JabRef/jabref/assets/23321102/fe7e3c32-f4d2-4ac6-921d-ff2b5501898e)

**Comment by ryan-carpenter** [comment] 2023-10-07 13:32
https://github.com/JabRef/jabref/blob/ca00d64af64cecc4a36a3a2219299bc86cc4ccee/src/main/java/org/jabref/logic/integrity/TitleChecker.java#L14

https://github.com/JabRef/jabref/blob/ca00d64af64cecc4a36a3a2219299bc86cc4ccee/src/main/java/org/jabref/logic/integrity/TitleChecker.java#L15

https://github.com/JabRef/jabref/blob/ca00d64af64cecc4a36a3a2219299bc86cc4ccee/src/main/java/org/jabref/logic/integrity/TitleChecker.java#L16

**Comment by Siedlerchr** [comment] 2023-10-08 17:21
I added this to the project board, I think it's a valid issue. 
Additional requirement: Write/Enhance Unit test

**Comment by michalfarago** [comment] 2023-10-08 18:36
Hello, I'd like to inquire about this issue.

If I've understood it correctly, you are talking about the following code:

https://github.com/JabRef/jabref/blob/ca00d64af64cecc4a36a3a2219299bc86cc4ccee/src/main/java/org/jabref/logic/integrity/TitleChecker.java#L54-L63

You'd like to handle this scenario by modifying the pattern and create unit test. Correct?

**Comment by Siedlerchr** [comment] 2023-10-08 18:47
FIrst create a test case for the behavior.
Then adjust the pattern/code etc to take this into account
The test could also be converted to a [parameterized test](https://www.baeldung.com/parameterized-tests-junit-5)

**Comment by ManaMatrix** [comment] 2023-10-09 05:22
Hey team I'm new to open-source contributing, I'd love to work on this issue if it is still free to take. Thank you

**Comment by michalfarago** [comment] 2023-10-09 05:49
Hello, I've already started working on this. Could you please assign this to me instead?

**Comment by ThiloteE** [comment] 2023-10-09 06:55
@ManaMatrix please check out our other [good first issues](https://github.com/orgs/JabRef/projects/5/views/1?filterQuery=Free+to+take).

**Comment by michalfarago** [comment] 2023-10-10 13:40
Hello, I'd like to double-check the following:
---
Titles like: **_title        = {Folding kinetics of a polymer [corrigendum]},_** are supported and don't raise a warning.

From the issue description, it's clear that the following should also not raise a warning: **_title        = {[Translated title]},_** 

My question is whether the following should raise a warning: **_title        = {[Translated title] Original title},_**

I've checked the resource folder, but didn't find any entry of that format, so I suspect that it should raise a warning. Let me know if I'm mistaken.

Thank you.

**Comment by Siedlerchr** [comment] 2023-10-11 16:59
@michalfarago  Good question, I think it should still raise a warning. It's at least unusual do have both in the same entry
Maybe @ryan-carpenter has a preference here as well?

**Closed** 2023-10-19 20:06 UTC
Labels: type: enhancement, good first issue

**Comment by Siedlerchr** [comment] 2023-10-21 12:41
@ryan-carpenter  The issue is now fixed in the latest development version
