### ISSUE TITLE
Window entry editor width not respected

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#4566] opened 2019-01-03 16:54 UTC
JabRef version 
JabRef 5.0-dev--snapshot--2018-12-31--master--a4e735b38
Windows 10 10.0 amd64 
Java 1.8.0_172
on 
Windows 10

1. Options -> Preferences -> Entry Table Columns -> I set the widths -> Click both Update to current column width as well as current column order. I have enabled rank, relevance, quality.
2. Put computer to sleep, or change to different window.
3. When I re-open JabRef, the pixels of the entry table are slightly off, making, e.g. the read status almost invisible (see attached screenshot).
4. When I correct it, after switching off and coming back to JabRef the issue is back again.

![jabref_pixels](https://user-images.githubusercontent.com/10846169/50650351-71252100-0f80-11e9-91da-dd2e54e52aae.png)

**Comment by Siedlerchr** [comment] 2019-01-03 17:00
That's a known issue and this is currently in the process of beeing fixed in #4546

**Comment by DOFfactory** [comment] 2019-01-03 17:54
Oh, ok, sorry for the new report

**Comment by tobiasdiez** [comment] 2019-01-05 16:20
Duplicate of #4437

**Closed by tobiasdiez** 2019-01-05 16:20 UTC
