### ISSUE TITLE
Search autofilled author name prevents certain searches

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#3166] opened 2017-08-29 21:18 UTC
When I hit Ctrl-f and type a string in the search field, an autocomplete fills in the author name and first initial.  But this is sometimes not the search string I want to match e.g. I may want to match a bibtex key which contains only a part of the author's name.  But I cannot find a way to get rid of the autocompleted author name.

See screenshot showing an autofilled name.  If I hit the escape key, the autofilled names do disappear but no matches are found, even though they exist in the bibtex file.

JabRef version  on 
JabRef 4.0-dev--snapshot--2017-08-28--master--fd9e67420
Windows 10 10.0 amd64 
Java 1.8.0_121

![image](https://user-images.githubusercontent.com/3851891/29844338-3d5709a0-8d0f-11e7-8648-f92d92a2f02f.png)

**Comment by stefan-kolb** [comment] 2017-09-14 11:40
Hitting escape works for me. Although I think this is a bug, as even if i hit enter after my string to prvent the auto completion it just takes the auto-completed find.

**Comment by tobiasdiez** [comment] 2017-10-20 08:31
I cannot reproduce the original issue reported above in the newest devolpment version (it should already be fixed in the released 4.0). @notuntoward can you double-check pls and/or provide more details how to reproduce this issue. Thanks.

@stefan-kolb isn't "enter" the usual way to accept an autocompletion suggestion (at least it works like this in google).

**Comment by stefan-kolb** [comment] 2017-10-20 08:49
I think enter should search for the term, I also don't like how Google behaves and need to redo the query all the time because it just appens an autosuggestion I don't want to have.

**Comment by notuntoward** [comment] 2017-10-20 09:46
Yes, thanks, autocompletion no longer gets in the way.  

But one strange thing still there is that the autocomplete result has two names, which are identical, so there's no way to look at them and know which one to pick.  

![image](https://user-images.githubusercontent.com/3851891/31815154-295a5772-b58c-11e7-875c-9f1814069b33.png)

**Comment by tobiasdiez** [comment] 2017-10-20 09:56
Yes that's a known issue which we can't resolve at the moment (they are actually not the same authors...e.g. once it was `Bengjo` and another time `Bengjo, A.` - which look different to JabRef but render the same since the initials are ignored).

**Closed by tobiasdiez** 2017-10-20 09:56 UTC
Labels: bug, waiting-for-feedback
