### ISSUE TITLE
Add launcher for Linux

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1263] opened 2016-04-20 21:01 UTC
Starting JabRef via the jar file is sometimes not possible on Linux, see https://github.com/JabRef/JabFox/issues/19 and https://github.com/JabRef/JabFox/issues/20.

We should add a launch script during install, analogously to 

```
#!/bin/bash
java -jar /my/target/to/JabRef.jar "$@"
```

**Comment by RKBK** [comment] 2016-04-23 17:53
This also seems necessary on Mac OSX, at least it was on my macbook pro.

**Comment by tobiasdiez** [comment] 2016-05-27 09:02
Can this please be included in the 3.4 release.

**Comment by koppor** [comment] 2016-05-27 14:06
How? Just as separate artifact of the release?

**Comment by tobiasdiez** [comment] 2016-05-27 15:03
Yeah, as a simple (executable) file in the same folder as the JabRef.jar file.

**Comment by stefan-kolb** [comment] 2016-05-30 15:40
@tobiasdiez Maybe this is just a file permission problem?! I can set the file permissions for the JabRef.jar inside the install4j script. What permissions do we need? Just +x? What are the current default permissions afetr the installler? Do they differ when problems arise?

**Comment by stefan-kolb** [comment] 2016-05-30 15:49
For me, the executable bit was missing when downloading the latest stable version.

**Comment by koppor** [comment] 2016-06-01 07:18
I think, the `+x` flag is not preserved while downloading.

I would offer the `.sh` script alongside at the release. No need for a separate archive.

The script should include a detection of the current directory instead using `/my/target/to/JabRef.jar`.

**Comment by stefan-kolb** [comment] 2016-06-01 07:23
I'm trying to evaluate the root cause of this problem. If it is just the exec bit (which I think it is) it's actually a user failure. @koppor If the +x is not preserved while downloading, why should it be for the sh script? Maybe we can also use an installer on Linux and set the appropriate permissions?

**Comment by koppor** [comment] 2016-06-01 07:30
Possibly an average linux user knows that `+x` is needed for `.sh`, but he is unaware in the case of `.jar`. A first glimpse on Google results for "execute jar" and "jar does not start" does not show the `+x` possibility.

**Comment by tobiasdiez** [comment] 2016-06-01 09:15
I have no idea why running the JabRef.jar didn't worked in the first place. Some user reported it worked, for some it didn't. So maybe it is worth a try to just set `+x` and then let these users reevaluate if linking the jar works.

**Comment by stefan-kolb** [comment] 2016-10-19 14:54
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Comment by tobiasdiez** [comment] 2016-10-19 15:49
The problem is still there (because we didn't changed anything, right?). For some user's starting jabref via the jar file does not work. So we have the following options:
- Fix the root problem (this is hard, since apparently nobody of the developers can reproduce the issue)
- At least include the workaround sh file for download and in the best case bundle everything as an installer (which also could make sure that +x is set).

**Comment by stefan-kolb** [comment] 2016-10-19 15:52
I closed it because we have to guess it is a user error.

**Comment by koppor** [comment] 2017-03-09 16:10
Someone could try to check Install4J's linux option: https://www.ej-technologies.com/products/install4j/features.html However, we think that an executable `jar` should be enough for linux.

**Comment by tobiasdiez** [comment] 2017-03-09 16:12
Not necessary as soon as we implement #1284 using native messaging.

**Closed** 2017-03-09 16:11 UTC
Labels: build-system, devcall, linux, osx
