### ISSUE TITLE
JabRef V5.9 still corrupts my BIB file.

### ISSUE THREAD

**Issue by MHFrey** [JabRef/jabref#9926] opened 2023-05-19 20:39 UTC
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. .Install JabRef v5.9 portable
2. Open my bib file, MHF.bib
3. Save the file
4. try to reopen the file
5. you get an error of no records
6. edit the file in text editor.  It is all binary, not text.

This is the same problem as 
#8895.  This has been broken since version 5.6.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```
compressed version of my original file.

[MHF - Copy.zip](https://github.com/JabRef/jabref/files/11520347/MHF.-.Copy.zip)

</details>
![image](https://github.com/JabRef/jabref/assets/107273819/641abe1e-654c-49ef-ac56-932d9d8c5ced)

**Comment by ThiloteE** [comment] 2023-05-19 22:03
Have you tried converting your library file's encoding to UTF-8?

**Comment by Siedlerchr** [comment] 2023-05-19 22:06
Thanks for the provided bib file and your detailed report. 
I could partially reproduce this and noticed the following issues with the latest dev version:
It's still this weird case of UTF16 and UTF16-BE. 

1. Opening the file for the first works
2. Saving the file in JabRef now modifies the header from `% Encoding: UTF-16` to `% Encoding: UTF-16BE` 
3. Closing JabRef
4. Reopening JabRef " No records found "  Notice the modified header

Further investigation resolved that your file starts with a BOM character.
And I think this is the issue. That JabRef cannot read the encoding line because it starst at the wrong offset.
Currently testing a fix

**Closed** 2023-05-20 13:47 UTC
Labels: type: bug 🐛, bib(la)tex
