### ISSUE TITLE
Cleanup urls/eprint fields to remove/encode "+" and other signs

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#389] opened 2015-11-25 14:05 UTC
Hi, 

I am having the following bibtex entry which generates an error on compiling in LaTex with biber:

My bibtex style setup:
```
\usepackage[american]{babel}
\usepackage[style=apa,backend=biber]{biblatex}
\DeclareLanguageMapping{american}{american-apa} %Literaturverzeichnis american-apa style
\addbibresource{Literaturverzeichnis.bib}
```

**! Undefined control sequence.**
<recently read> \mathplus 

I did the auto cleanup of the entry, but however the url/eprint field seems not to be touched. So I suggest auto-cleanup url fields too

```
@Article{JinxinLin1996,
  Title                    = {A Requirement Ontology for Engineering Design},
  Author                   = {Jinxin Lin, and Fox, Mark S. and Bilgic, Taner},
  Journal                  = {Concurrent Engineering},
  Year                     = {1996},
  Number                   = {3},
  Pages                    = {279--291},
  Volume                   = {4},
  Abstract                 = {We present an ontology for representing requirements that supports a generic requirements management process in engineering design domain The requirement ontology we propose is a part of a more general ontology to capture engineering design knowledge Objects included in this general ontology are parts features requirements and constraints We define a generic requirements management process and raise issues that any requirement representation must address like communication, traceability, completeness consistency document creation and managing change We use first order logic to define the objects and their attributes and identify the axioms capturing the constraints and relationships among the objects We show how the axioms can be used in answering the issues raised},
  Doi                      = {10.1177/1063293X9600400307},
  Eprint                   = {http://cer.sagepub.com/content/4/3/279.full.pdf+html},
  Timestamp                = {2015.11.12},
  Url                      = {http://cer.sagepub.com/content/4/3/279.abstract}
}
```

**Comment by Siedlerchr** [comment] 2015-12-15 09:41
Additionally abstract fields should also be normalized and encoded properly.
I had an abstract containing % Symbols. I had to manually escape them, otherwise I got a compile error with biber.

:2620: parser error : Premature end of data in tag section line xxxxx^ :2620: parser error : Premature end of data in tag controlfile line 2 ^

**Comment by oscargus** [comment] 2015-12-15 15:57
What do you think the + should be converted to? As far as I can tell, it is biber that replaces the + with \mathplus and that probably should check if it is inside an equation. {\textplus}?

% is another biber thing. Of course it can be escaped as \%, but this is really only because biber use % for commenting (I'd hope that biber honors \%). In bibtex there are no comments (although everything outside an entry is ignored).

**Comment by koppor** [comment] 2015-12-16 08:29
The `\mathplus` is not appearing in your example. I think, the issue is not with this entry, but with entires from Springer:

Springer sometimes adds the `mathplus` in the `publisher` field. See http://tex.stackexchange.com/q/212644/9075.

So, the solution is IMHO to replace `\mathplus{}` by `+`  during cleanup, isn't it?

**Comment by Siedlerchr** [comment] 2015-12-16 11:18
@koppor Seems like I got the wrong entry, yes, I encountered this with Springer:
Replacing the mathplus with a simple +  works fine. See example code

@oscargus  Yes, encoding the percentage with \% worked fine for biber

```
@Book{Pan2013,
  Title                    = {Ontology-Driven Software Development},
  Editor                   = {Jeff Z. Pan and Steffen Staab and Uwe A{\ss}mann and J\"{u}rgen Ebert and Yuting Zhao},
  Publisher                = {Springer Science $\mathplus$ Business Media},
  Year                     = {2013},
  DOI                      = {10.1007/978-3-642-31226-7},
  Timestamp                = {2015.11.14}
}
```

**Comment by stefan-kolb** [comment] 2016-02-23 13:49
If we encode anything in the URL field the URL might break.

**Comment by tobiasdiez** [comment] 2016-02-27 16:54
@oscargus is there a converter which converts \mathplus to "+" ?

**Comment by stefan-kolb** [comment] 2016-04-13 19:09
So this issue has shifted from a discussion about the URL field to other fields?! Imho, we can close this as we cannot reasonably strip anything inside URL fields without potentially breaking inks.

**Comment by koppor** [comment] 2016-04-13 19:16
@Siedlerchr I don't see any `%` in your examples or am I blind?

**Comment by Siedlerchr** [comment] 2016-04-13 20:06
Öhm, not sure if this is still relevant

**Closed** 2016-04-13 20:21 UTC
Labels: asking-for-a-pull-request, enhancement
