### ISSUE TITLE
Uncaught Exception in GroupsTreeViewModel

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#2619] opened 2017-03-06 13:49 UTC
JabRef 4.0.0-dev--snapshot--2017-03-06--master--dd29a189e
Windows 10 10.0 amd64 
Java 1.8.0_121

I don't have a clue what happend - just found this exception in the log as I was investigating another problem... :wink:

```
Uncaught exception Occurred in Thread[JavaFX Application Thread,5,main]
java.lang.RuntimeException: A bound value cannot be set.
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:142)
	at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:69)
	at org.jabref.gui.groups.GroupTreeViewModel.lambda$onActiveDatabaseChanged$6(GroupTreeViewModel.java:92)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.groups.GroupTreeViewModel.onActiveDatabaseChanged(GroupTreeViewModel.java:91)
	at org.jabref.gui.groups.GroupTreeViewModel.lambda$new$0(GroupTreeViewModel.java:37)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.beans.property.ObjectProperty.setValue(ObjectProperty.java:69)
	at org.jabref.gui.JabRefFrame.lambda$init$0(JabRefFrame.java:603)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Siedlerchr** [comment] 2017-03-06 16:14
I can now more or less reproduce this behaviour: 
Open 2 databases both contain groups. Switch from one db to another. 

```
  /**
     * Gets invoked if the user changes the active database.
     * We need to get the new group tree and update the view
     */
    private void onActiveDatabaseChanged(Optional<BibDatabaseContext> newDatabase) {

```

**Comment by Siedlerchr** [comment] 2017-03-07 16:02
@tobiasdiez  Ich mach mal nen fix hierfür

**Comment by Siedlerchr** [comment] 2017-03-07 16:33
Okay, I give up as I have no deep knowledge of the javafx binding stuff.
The problem is that the property in this case is already bound.
From what I read it has to be unbound and then rebound. 
The unbinding is clear, but no idea how to rebind it.


`stateManager.getSelectedGroup(newDatabase.get()).ifPresent(

                    selectedGroup -> {
                        System.out.println(this.selectedGroup.isBound());
                        if (this.selectedGroup.isBound()) {
                            this.selectedGroup.unbind(); //Works but then the filtering doesnt work 

                        }
                        this.selectedGroup
                                .setValue(new GroupNodeViewModel(newDatabase.get(), stateManager, selectedGroup));
                    });`

**Comment by tobiasdiez** [comment] 2017-03-08 01:15
Thanks for having a look at it. I think the problem is indeed the binding. For some reason it also doesn't work if the binding is changed to a two way binding. Probably its best to resort to simple listeners in this case.

**Comment by tobiasdiez** [comment] 2017-03-16 16:37
Should be fixed in the master (at least in a few minutes)

**Closed by tobiasdiez** 2017-03-16 16:37 UTC
Labels: groups
