### ISSUE TITLE
IndexOutOfBoundsException Exception

### ISSUE THREAD

**Issue by Jean-Roc** [JabRef/jabref#1469] opened 2016-06-01 09:25 UTC
Hi, we get this kind of errors with :

* JabRef-3.4dev--snapshot--2016-06-01--master--bd7e23f.jar
* Windows 7 32 and 64bit
* java portable 1.8.0_77

1. JabRef is launched using this command :

> java.exe" -Xmx1024M -Xms1024M -jar "D:\jabref.jar"

2. On opening any of our files :

```
Exception in thread "JabRef CachedThreadPool" java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at net.sf.jabref.gui.maintable.MainTable.setWidths(MainTable.java:304)
        at net.sf.jabref.gui.maintable.MainTable.<init>(MainTable.java:180)
        at net.sf.jabref.gui.BasePanel.createMainTable(BasePanel.java:1400)
        at net.sf.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1526)
        at net.sf.jabref.gui.BasePanel.<init>(BasePanel.java:237)
        at net.sf.jabref.importer.OpenDatabaseAction.addNewDatabase(OpenDatabaseAction.java:323)
        at net.sf.jabref.importer.OpenDatabaseAction.openTheFile(OpenDatabaseAction.java:277)
        at net.sf.jabref.importer.OpenDatabaseAction.lambda$openFiles$0(OpenDatabaseAction.java:168)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```
3. Or simply creating a new file

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at net.sf.jabref.gui.maintable.MainTable.setWidths(MainTable.java:304)
        at net.sf.jabref.gui.maintable.MainTable.<init>(MainTable.java:180)
        at net.sf.jabref.gui.BasePanel.createMainTable(BasePanel.java:1400)
        at net.sf.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1526)
        at net.sf.jabref.gui.BasePanel.<init>(BasePanel.java:237)
        at net.sf.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1638)
        at net.sf.jabref.gui.actions.NewDatabaseAction.actionPerformed(NewDatabaseAction.java:35)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
        at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by Jean-Roc** [comment] 2016-06-01 09:41
The same behaviour is encountered with Jabref 3.3

**Comment by tobiasdiez** [comment] 2016-06-01 09:53
You should be able to fix this issue by resetting the preferences or maybe by changing the column widths under Options -> Preferences -> Entry Table Columns.

**Comment by matthiasgeiger** [comment] 2016-06-01 10:20
Before resetting the preferences: can you please export them and post them here this might help us to find the reason for this bug.
Thanks!

**Comment by Jean-Roc** [comment] 2016-06-01 11:47
@tobiasdiez thank you, this seems to be the solution
@matthiasgeiger here is the [reg export](https://gist.github.com/Jean-Roc/6dfb190cdb9c6a1e312a50405a67e185), _column/Widths_ and _number/Col/Width_ were not defined

**Comment by matthiasgeiger** [comment] 2016-06-01 12:21
Thanks again.

The trouble is caused by an inconsistency between columnNames and columnWidths: You have defined extra columns in columnNames (resulting in 9 columns) - but the columnWidths are still the default (only 6 width values available). Using the UI to add additional columns this should not happen... (in the Preferences dialog, tab "Entry table columns")

What JabRef version have you used previously that generates this inconsistent preferences? (I assume that you have not edited the preferences by hand...)

**Comment by Jean-Roc** [comment] 2016-06-01 12:44
These preferences are (at least) 6 years old and were used with jabref 2.x, I got these errors while trying to upgrade our version to 3.x. Manual editing may have been done for the custom fields but their creator is long gone so no certainties.

**Comment by matthiasgeiger** [comment] 2016-06-01 12:50
Okay. I think we can close this issue then as resetting the preferences allows you to start JabRef and this seems to be an edge case which will not occur very often.

**Closed by matthiasgeiger** 2016-06-01 12:50 UTC
