### ISSUE TITLE
Superfluous error message: File has been externally modified while adding to the group tree

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3625] opened 2018-01-10 08:28 UTC
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 on Windows 7

Steps to reproduce:

1. Open Jabref
2. show the group tree
3. add a group/modify a group

![grafik](https://user-images.githubusercontent.com/9216487/34762482-406da4ae-f5e8-11e7-8899-625645d0754b.png)

The only thing I did Adding the PPAR group, gave the message, and sorting the subgroups, raised another similar message.

<details>
 
  ```
  Copying Files failed.
java.nio.file.FileSystemException: C:\Users\bk\AppData\Local\Temp\jabref7632365861494016785.bib: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
	at java.nio.file.Files.copy(Unknown Source)
	at org.jabref.logic.util.io.FileUtil.copyFile(FileUtil.java:164)
	at org.jabref.gui.collab.DatabaseChangeMonitor.copyToTemp(DatabaseChangeMonitor.java:156)
	at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:148)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.BasePanel.updateTimeStamp(BasePanel.java:1987)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator.evaluate(SpinOffEvaluator.java:120)
	at spin.ProxyFactory.evaluteInvocation(ProxyFactory.java:85)
	at spin.JDKProxyFactory$SpinInvocationHandler.invoke(JDKProxyFactory.java:102)
	at com.sun.proxy.$Proxy36.run(Unknown Source)
	at org.jabref.gui.BasePanel.runWorker(BasePanel.java:258)
	at org.jabref.gui.exporter.SaveDatabaseAction.runCommand(SaveDatabaseAction.java:285)
	at org.jabref.gui.autosaveandbackup.AutosaveUIManager.listen(AutosaveUIManager.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.jabref.logic.autosaveandbackup.AutosaveManager.lambda$listen$0(AutosaveManager.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Copying Files failed.
java.nio.file.FileSystemException: C:\Users\bk\AppData\Local\Temp\jabref7632365861494016785.bib: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
	at java.nio.file.Files.copy(Unknown Source)
	at org.jabref.logic.util.io.FileUtil.copyFile(FileUtil.java:164)
	at org.jabref.gui.collab.DatabaseChangeMonitor.copyToTemp(DatabaseChangeMonitor.java:156)
	at org.jabref.gui.collab.DatabaseChangeMonitor.lambda$markAsSaved$3(DatabaseChangeMonitor.java:148)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markAsSaved(DatabaseChangeMonitor.java:143)
	at org.jabref.gui.collab.DatabaseChangeMonitor.markExternalChangesAsResolved(DatabaseChangeMonitor.java:139)
	at java.util.Optional.ifPresent(Unknown Source)
	at org.jabref.gui.BasePanel.markExternalChangesAsResolved(BasePanel.java:1834)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:163)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator.evaluate(SpinOffEvaluator.java:120)
	at spin.ProxyFactory.evaluteInvocation(ProxyFactory.java:85)
	at spin.JDKProxyFactory$SpinInvocationHandler.invoke(JDKProxyFactory.java:102)
	at com.sun.proxy.$Proxy36.run(Unknown Source)
	at org.jabref.gui.BasePanel.runWorker(BasePanel.java:258)
	at org.jabref.gui.exporter.SaveDatabaseAction.runCommand(SaveDatabaseAction.java:285)
	at org.jabref.gui.autosaveandbackup.AutosaveUIManager.listen(AutosaveUIManager.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:87)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:144)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:72)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:67)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:108)
	at com.google.common.eventbus.EventBus.post(EventBus.java:212)
	at org.jabref.logic.autosaveandbackup.AutosaveManager.lambda$listen$0(AutosaveManager.java:51)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Side pane component 'class org.jabref.gui.collab.FileUpdatePanel' unknown.
  ```
</details>

**Comment by bernhard-kleine** [comment] 2018-01-10 10:33
I know this. But the release is barely 3 weeks old which confirms my lamentation about quality control in the other thread. In addition to the problem shown here, the group tree disappeared from the display while the entries had still the group field. Upon closing jabref without saving and re-opening everything was fine again, and groups could be added and sorted without any error. As this seems to be related to file saving of temporary bib files (at least the error log suggests that) I have not changed anything in the appdata folder. 
Did you have changed between the 4.1 release and the current snapshot related to accessing the temporary file?

**Comment by tobiasdiez** [comment] 2018-01-10 10:58
Did you tried restarting your computer?
> Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
Is telling you that JabRef cannot access the file...a priori this is not a bug with JabRef since the file operation is prevented by the OS.

**Comment by bernhard-kleine** [comment] 2018-01-10 11:01
no, I did not restart my computer, and I wander about the citation, too. I only restarted Jabref. The OS war not restarted.

**Comment by lenhard** [comment] 2018-01-10 16:56
I might have been a bit quick in adding the bug label here. I cannot reproduce this on current master as well. As long as we can't do that, there's no chance of fixing it.

As @tobiasdiez wrote, the error indicates a problem on the OS-level. The only reason I could image would be that the file is opened somewhere in JabRef and not closed properly. However, the operation that triggers the exception `Files.copy` automatically takes care of closing the resource properly (that's more or less the whole point of using this API).

By the way, virus scanners are famous for causing troubles such as this one.

**Closed** 2018-01-10 17:11 UTC
Labels: export / save, waiting-for-feedback

**Comment by koppor** [comment] 2018-01-24 21:46
Maybe we should switch the way we write files.

If I remember correctly, we write another file and then copy it over to `.bib` to prevent corruption of the `.bib` file if the saving routine crashes. However, we did not encounter any crash there. Maybe, we should change this behavior?
