### ISSUE TITLE
The Group Panel is not updated when switching between certain libraries

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3142] opened 2017-08-20 15:47 UTC
JabRef 4.0-beta3
Windows 7 6.1 amd64 
Java 1.8.0_131

Steps to reproduce:

1. open Jabref with multiple libraries
2. switch between the libraries
3. the updating of the Group Panel is extremely slow and not always correct-

I have the following screenshots to show that behaviour: when I switch from chapter04.bib to  EndokrinologieKunde20170513VS4.0.0.bib and vice versa the group panel is not updated, while switching to FatMetabolism20170608VS4.0.0.bib it is updated and then back to either chapter04.bib or EndokrinologieKunde... it is. Chapter04 has 275 entries, FatMetabolism has 900 and Endokrinologiekunde has 1991 entries 
![grafik](https://user-images.githubusercontent.com/9216487/29496199-335bab42-85ce-11e7-90a1-8c90b3354cf5.png)
![grafik](https://user-images.githubusercontent.com/9216487/29496206-57ad39fc-85ce-11e7-870a-b03504b3dfe2.png)
![grafik](https://user-images.githubusercontent.com/9216487/29496212-705daf72-85ce-11e7-8b85-0f8d237bc4e9.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by lenhard** [comment] 2017-08-20 17:19
Refs #2690

**Comment by lenhard** [comment] 2017-08-28 10:58
This can be reproduced in the following way:
 - Start JabRef with two bib files and the the groups side pane open
 - Create a new database
 - JabRef will switch to the new database, but the groups side pane will display the tree of the last selected database

If tracked the problem down to this part:
https://github.com/JabRef/jabref/blob/6a26798aa88d49e72977cfbc464324baa73c9d0d/src/main/java/org/jabref/gui/groups/GroupSidePane.java#L131-L133

Here the groups side pane should repaint, but the `JFXPanel` does not necessarily do that. The only way  I found (and I tried many ways) to force it was by re-creating the completed pane, i.e. by putting this code into the conditional:
```
            StackPane root = new StackPane();
            root.getChildren().addAll(new GroupTreeView().getView());
            Scene scene = new Scene(root);
            groupsPane.setScene(scene);
```
But that leads to an ugly flicker in the UI. Resetting the scene with a newly created instance is the key. Without that, no change happens.

@tobiasdiez How can I force the `groupsPane` to refresh without having to rebuild all its contents? There has to be some way to do this.

**Comment by tobiasdiez** [comment] 2017-09-11 11:16
@lenhard I cannot reproduce the issue with the steps you describe with the latest master. For me, an empty groups tree is displayed for the new database. 

Codewise, it (should) work as follows: The statemanager is notified about the new database https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/JabRefFrame.java#L617 and propagates the event to the group tree view https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java#L55.
There the tree is updated https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java#L121, which triggers a repaint of the tree due to the binding https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/groups/GroupTreeController.java#L99

**Comment by lenhard** [comment] 2017-09-11 15:11
@tobiasdiez Hm, you use Win10, right? if you cannot reproduce this, maybe the problem is related to Win7. Because for me it is no problem to reproduce and I have the same setting as @bernhard-kleine 

We might need more help tracking this down from other people that use different settings.

**Comment by tobiasdiez** [comment] 2017-09-11 15:29
Yes, I'm on Win10. Can you please verify that https://github.com/JabRef/jabref/blob/007a534d0db7032a77260aa492e15523d44512d9/src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java#L113 is invoked (with the proper empty database as argument), when you create a new database.

**Comment by lenhard** [comment] 2017-09-12 08:16
I debugged this and the method is invoked with the empty database. This is the case for BibTeX and biblatex, but unfortunately the group tree doesn't get updated properly.

**Comment by stefan-kolb** [comment] 2019-08-26 21:28
Can reproduce exactly as described by Jörg (maybe you need to switch between the bibs a bit):
![image](https://user-images.githubusercontent.com/2141507/63724884-2a5ea100-c859-11e9-92f7-3b53db3be1a3.png)
![image](https://user-images.githubusercontent.com/2141507/63724895-32b6dc00-c859-11e9-8539-93266741fa9e.png)

**Comment by tobiasdiez** [comment] 2019-09-16 19:22
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed** 2019-09-16 19:22 UTC
Labels: bug, groups
