### ISSUE TITLE
Install of jabref.5.0.0.msi is flawed and to complicated

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#5657] opened 2019-11-21 12:15 UTC
JabRef 5.0.0-dev--2019-11-21----eb79ebad6
Windows 7 6.1 amd64 
Java 13.0.1

- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. The installation does not automatically remove a previous version but asks the users to use the Systemsteuerung (system control) to do it themselves.
2. The installation does provide an desktop icon to start the program but does not add the program and its directory or and link to it unto the start menu (directory).
3. This is a regression from previous x64-exe files.

**Comment by AEgit** [comment] 2019-11-21 13:23
The first point is a duplicate of:
https://github.com/JabRef/jabref/issues/5399#issuecomment-554775210

**Comment by jorgman1** [comment] 2019-11-22 10:22
To point 2:

I would suggest adding two checkboxes in the installation menu. Hence, the user could decide whether he wants the folder in the start menu and the desktop shortcut.

**Comment by Siedlerchr** [comment] 2019-11-22 10:39
1. It should already be possible to overinstall (aka replace the previous version with the newer)

**Comment by bernhard-kleine** [comment] 2019-11-22 11:41
@Siedlerchr , actually it is not for unknown reasons.
3. The program should know to which directory the previous version has been installed and offer that dir for overinstalling.

**Comment by bernhard-kleine** [comment] 2019-11-28 20:12
@tobiasdiez: I wonder why the file size of jabref.5.0.0.msi during update is shown as the final size, not the actual one. I was irritated since downlaoding of a partial file is without use.

**Comment by tobiasdiez** [comment] 2019-12-04 11:44
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed** 2019-12-04 11:43 UTC
Labels: installation

**Comment by AEgit** [comment] 2019-12-04 14:16
@tobiasdiez There are currently two .msi installers on the Master website. They were uploaded at different times and one of them appears to have a size of 0 Bytes. Which one is the correct one to download?

**Comment by tobiasdiez** [comment] 2019-12-04 18:50
Thanks. There was a problem with the upload. I retriggered the script, there should be working version in about 30 min. https://builds.jabref.org/master/JabRef-5.0.msi

@koppor could you please cleanup the build/master folder? Thanks!

**Comment by AEgit** [comment] 2019-12-05 09:29
@tobiasdiez All master builds have now disappeared, i. e. there is no build at all at the moment, that can be downloaded. Are you aware of this, i. e. is something being uploaded at the moment and just not visible or is there a problem?

**Comment by Siedlerchr** [comment] 2019-12-05 09:42
I am triggering a new build now. Will take 30minutes or so.

**Comment by AEgit** [comment] 2019-12-05 10:32
@Siedlerchr Thank you very much!

JabRef 5.0-alpha--2019-12-04--5dcb565
Windows 10 10.0 amd64 
Java 13.0.1

I can confirm that this issue has been fixed in the current dev version. Thanks to everyone involved!

**Comment by bernhard-kleine** [comment] 2019-12-05 10:53
confirmed! Thanks a lot!
