### ISSUE TITLE
This exception happens whenever the latest development version starts

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3525] opened 2017-12-13 07:27 UTC
JabRef 4.1-dev--snapshot--2017-12-08--master--6f39151a7
Windows 10 10.0 amd64 
Java 1.8.0_151

The error log:

```java
Opening: C:\Users\zlgsa\OneDrive\Documents\JabRefBibs\MyFullResearch.bib
Opening: C:\Users\zlgsa\OneDrive\Documents\JabRefBibs\seminar.bib
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException
	at org.jabref.gui.search.GlobalSearchBar.lambda$new$5(GlobalSearchBar.java:196)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by tobiasdiez** [comment] 2017-12-13 10:00
Thanks for the report! This should be fixed since yesterday evening but our builds are broken at the moment so that https://builds.jabref.org/master/ does not offer the new downloads.

**Comment by sambo57u** [comment] 2017-12-19 14:55
I can confirm that it is fixed with 12-19 devel version.

**Closed** 2017-12-19 15:15 UTC
Labels: bug, fixed-in-devBuilds, search
