### ISSUE TITLE
Entry preview sometimes shows other article

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10456] opened 2023-10-07 09:29 UTC
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Have a library with two entries.
2. Click on the first one, it is properly shown in the entry editor and in the preview (the html panel next to editor)
3. Click on the second entry. The entry editor is updated but the preview stays the same.

It's hard to replicate reliably, but in essence its the above. I had the impression that if you switch tabs in the entry editor in between then the issue occurs more reliably. In fact, I even managed to have one preview shown in the required fields tabs, while another preview is shown in the optional fields tab.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment] 2023-10-07 09:36
Duplicate of #9172

**Closed by Siedlerchr** 2023-10-07 09:36 UTC
Labels: bug, entry-preview

**Comment by tobiasdiez** [comment] 2023-10-07 10:04
Thanks missed that one
