### ISSUE TITLE
Automatic Bug Report - 20170803121908 - Import preferences from file not working

### ISSUE THREAD

**Issue by moldt** [JabRef/jabref#3072] opened 2017-08-03 10:27 UTC
In Jabref I click on the menu entry "Options", then "Preferences". In the dialog window I click on "Import Preferences". Nothing happens.

JabRef 4.0-beta2 (the 32bit version)
Windows 7 6.1
Java 1.8.0_91

<details>
<summary>Detail information:</summary>

This is my event log:
```
Opening: D:\Dateien\Promotion\Literatur\sfbliterature.bib
Uncaught exception Occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at java.nio.file.Files.provider(Unknown Source)
	at java.nio.file.Files.exists(Unknown Source)
	at org.jabref.gui.util.FileDialogConfiguration$Builder.withInitialDirectory(FileDialogConfiguration.java:83)
	at org.jabref.gui.util.FileDialogConfiguration$Builder.withInitialDirectory(FileDialogConfiguration.java:93)
	at org.jabref.gui.preftabs.PreferencesDialog.lambda$new$4(PreferencesDialog.java:168)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

</details>

**Comment by Siedlerchr** [comment] 2017-08-03 10:38
Duplicate of #3064 
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Closed by Siedlerchr** 2017-08-03 10:38 UTC

**Comment by moldt** [comment] 2017-08-03 12:41
Thanks for quick reply and sorry for the hassle. I searched for the bug but must have searched with the is:open flag or something like that and therefore didn't find the earlier report.

**Comment by moldt** [comment] 2017-08-03 12:50
I downloaded a development build from the link you have given and indeed the bug is fixed. The dialog window to choose an xml file works. For testing purposes I imported an xml file where I had changed the "owner name" field and indeed this change was applied after restarting Jabref. (BTW thanks for the dialog window that asks me to restart, I found that out the hard way once.)

**Comment by Siedlerchr** [comment] 2017-08-03 12:52
Thanks for the feedback! I am glad it worked out for you. I just closed this bug so fast, because I just yesterday fixed it, so I still had it in mind ;)
