### ISSUE TITLE
Library Preferences => Save Order is not followed when saving

### ISSUE THREAD

**Issue by Sethur** [JabRef/jabref#3924] opened 2018-04-04 11:49 UTC
Issue was tested on latest dev master and persists.

JabRef version 4.1 on Windows 7 and Java 8 x64 version 8 update 162

Steps to reproduce:

1. Goto File => Library Properties. Select sort order First: Year, Second: Author, Third: Journal as in screenshot

![image](https://user-images.githubusercontent.com/2142589/38305863-bd9d187a-380e-11e8-9b1d-06d680b7294c.png)

2. Save database
3. Articles will not be sorted as selected (not even by year)

**Comment by stefan-kolb** [comment] 2018-04-16 15:54
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`.
@JabRef/developers Can someone please double check this before I close it as invalid?

**Comment by tobiasdiez** [comment] 2018-09-13 19:44
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Closed by tobiasdiez** 2018-09-13 19:44 UTC
Labels: waiting-for-feedback
