### ISSUE TITLE
bottom menu items not visible

### ISSUE THREAD

**Issue by AdamWysokinski** [JabRef/jabref#11140] opened 2024-04-03 21:30 UTC
### JabRef version

5.13 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Debian

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Bottom menu items are not visible after upgrading to 5.13, see attached screenshot.

![scrot](https://github.com/JabRef/jabref/assets/42808557/d8521e77-9bbd-4984-ba21-3461dc088c9d)

**Comment by Siedlerchr** [comment] 2024-04-03 22:02
That is weird! Which desktop environment are you using? Gnome? Kde?  
Does a version from here (with newer JavaFX https://builds.jabref.org/jdk-ea/ work correctly ?)

**Comment by AdamWysokinski** [comment] 2024-04-03 22:09
That's i3. The issue is the same in the newer JavaFX version. Changing the menu items padding (in theme css) does not help.

**Comment by HoussemNasri** [comment] 2024-04-03 22:54
@AdamWysokinski What version of JabRef did you upgrade from? From what I can see it looks like a rendering issue with JavaFX, did you try to restart the computer? Maybe when the window manager gets reinitialized, it will fix itself. Also, did you notice the problem in other menus or just the File one?

**Comment by duguyipiao** [comment] 2024-04-04 01:13
I have the same issue under manjaro xfce. I tried both [jabref](https://aur.archlinux.org/packages/jabref) and  [jabref-bin](https://aur.archlinux.org/packages/jabref-bin) from aur. I also tried to restart the computer. It happens to all menus and also the contextual menu.

Btw, I don't know whether it is related, but the `override default font size` setting is not functional for the bib entries after restarting jabref.

**Comment by AdamWysokinski** [comment] 2024-04-04 18:57
> @AdamWysokinski What version of JabRef did you upgrade from? From what I can see it looks like a rendering issue with JavaFX, did you try to restart the computer? Maybe when the window manager gets reinitialized, it will fix itself. Also, did you notice the problem in other menus or just the File one?

Interestingly, after restarting the system, this issue disappears. However, a new one has occurred: https://github.com/JabRef/jabref/issues/11142

**Comment by HoussemNasri** [comment] 2024-04-04 23:45
@AdamWysokinski What version of JabRef did you upgrade from?

**Comment by AdamWysokinski** [comment] 2024-04-05 06:36
In JabRef 5.13-PullRequest10808.81--2024-01-20--34082ca menus work fine.

**Comment by AdamWysokinski** [comment] 2024-04-05 13:57
It is also present in 5.14 from https://builds.jabref.org/main/

**Comment by Siedlerchr** [comment] 2024-04-05 16:30
@AdamWysokinski  can you also test the 5.14 with jfx23 https://builds.jabref.org/jdk-ea/ variant here? (portable is probably fine enough)

**Comment by HoussemNasri** [comment] 2024-04-05 18:55
Also, please test https://builds.jabref.org/pull/11155/merge/. It uses JavaFX 21.0.2 which is the same version used in 
JabRef 5.13-PullRequest10808.81--2024-01-20--34082ca.

**Comment by AdamWysokinski** [comment] 2024-04-05 18:57
> @AdamWysokinski can you also test the 5.14 with jfx23 https://builds.jabref.org/jdk-ea/ variant here? (portable is probably fine enough)

No change, same issue.

**Comment by AdamWysokinski** [comment] 2024-04-05 19:00
> Also, please test https://builds.jabref.org/pull/11155/merge/. It uses JavaFX 21.0.2 which is the same version used in JabRef 5.13-PullRequest10808.81--2024-01-20--34082ca.

No change, same issue.

**Comment by tsayao** [comment] 2024-04-06 15:17
That's very weird, since the menu is a popup window and has it's own rendering. The fact that the rendering glitch is not a rectangle is even weirder.

**Comment by tsayao** [comment] 2024-04-06 15:37
It it i3/Xorg or Sway/Wayland ?

**Comment by AdamWysokinski** [comment] 2024-04-06 15:38
> It it i3/Xorg or Sway/Wayland ?

i3/Xorg. Same issue with NVidia and AMD cards.

**Comment by tsayao** [comment] 2024-04-06 16:52
It's a sizing issue - but only happens on i3 according to my tests.

**Comment by Siedlerchr** [comment] 2024-04-06 17:34
@tsayao  Thank you very much for your investigation!

**Comment by tsayao** [comment] 2024-04-06 17:36
Proposed a fix here:
https://github.com/openjdk/jfx/pull/1437

**Comment by ytzemih** [comment] 2024-04-10 11:37
I can indeed confirm that on i3 on JR 5.13 and 5.14, but I've not had this issue with JR 5.12, see my screenshoots:
![jr-cutoff-menus](https://github.com/JabRef/jabref/assets/25365609/3d1f6cdf-b609-4842-9ef4-598e3e0e7f43)
![jr-cutoff-menus2](https://github.com/JabRef/jabref/assets/25365609/6937eb72-04d0-48d2-9952-83654e70f539)


Generally, on i3, I've had JavaFX layouting problems for years, but fortunately never some missing menu items.

Hope there is an easy fix as it did still work on JR 5.12.

**Comment by ytzemih** [comment] 2024-04-10 11:40
Thanks, @tsayao for having had a go on this.

**Comment by AdamWysokinski** [comment] 2024-05-21 17:24
It seems that I have solved the problem: compton (Linux xorg compositor was not running). After re-enabling it menus look fine. Will test more and report.

**Comment by Siedlerchr** [comment] 2024-05-21 17:44
@AdamWysokinski  @ytzemih 
The fix for i3 was merged a couple of days ago into javafx 23, so you can try out this version here with the new javafx:

https://builds.jabref.org/jdk-ea/

**Comment by AdamWysokinski** [comment] 2024-05-21 18:37
Thanks, that one is perfect!

**Comment by ytzemih** [comment] 2024-05-22 05:54
That one works for me as well. Thanks a lot for finding a fix.

**Comment by ytzemih** [comment] 2024-06-20 12:20
Hi, when is this fix going to be included in the main branch? Just wondering, today I updated to the last nightly build and the issue is still there. Are there further things to be checked? Thanks a lot for a comment.

**Comment by Siedlerchr** [comment] 2024-06-20 13:04
@ytzemih  We have to wait for the new javafx release around July. You can use the variant from the jdk ea build folder here https://builds.jabref.org/jdk-ea/  
They will inlcude the latest jabref code combined with newer jdk versions, but are not build everytime

**Comment by ytzemih** [comment] 2024-06-20 13:22
Thanks, @Siedlerchr, for the clarification and the update. Much appreciated.

**Comment by ytzemih** [comment] 2024-09-24 07:38
With JabRef 5.16--2024-09-20--5ac788c, this issue seems to be solved for me now. Thanks.

**Closed** 2024-09-24 08:06 UTC
Labels: os: linux, status: depends-on-external

**Comment by AdamWysokinski** [comment] 2024-09-24 08:27
The issue is still present in the most recent Linux jdk22 javafx24 and 24-09-2024 builds
