### ISSUE TITLE
Exporting to MS Office 2007 XML fails

### ISSUE THREAD

**Issue by juanerasmoe** [JabRef/jabref#1395] opened 2016-05-13 09:40 UTC
JabRef version 3.2 on Ubuntu 15.04

Steps to reproduce:
1. Select any bib entry
2. Select "File > Export selected entries"
3. Choose "MS Office 2007 (.xml)" in the Filter section, enter a file name and click OK
4. JabRef will reply with a "Could not save file. Stream closed" message

The console shows the following
`java.io.IOException: Stream closed
	at net.sf.jabref.exporter.MSBibExportFormat.performExport(MSBibExportFormat.java:70)
	at net.sf.jabref.exporter.ExportFormats$1ExportAction$1.run(ExportFormats.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Thread.java:745)
`

The same operation works well in JabRef 2.10b

**Comment by stefan-kolb** [comment] 2016-05-14 10:11
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by stefan-kolb** [comment] 2016-05-14 10:11
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`. Can you please try the latest build from http://builds.jabref.org/master.

**Comment by stefan-kolb** [comment] 2016-06-14 08:13
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Closed by stefan-kolb** 2016-06-14 08:13 UTC
Labels: waiting-for-feedback
