### ISSUE TITLE
Field width too small

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#6830] opened 2020-09-01 15:10 UTC
JabRef version 5.1--2020-08-30--e023aa0 on Debian GNU/Linux 10 Buster

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Start JabRef
2. Select a bibitem
3. Select a tab, for ex. "Optional fields"
4. Look at the width of fields (I attach a screenshot)

![jabref](https://user-images.githubusercontent.com/1306260/91869305-060c8000-ec76-11ea-81a0-5480414f7889.png)

Many thanks in advance,
Domenico Cufalo

**Comment by Siedlerchr** [comment] 2020-09-01 15:13
You can change the setting of the preview to be a separate tab. You can also resize the pane in the middle

**Comment by Doc73** [comment] 2020-09-01 15:20
@Siedlerchr 
If I resize the panel in the center, only the fields on the left enlarge. The only solution, it seems, is to set the preview on a separate tab, but it is not very elegant

**Comment by Siedlerchr** [comment] 2020-09-01 15:58
And I noticed this issue has already been reported before. Duplicate of #6097

**Closed by Siedlerchr** 2020-09-01 15:58 UTC
