### ISSUE TITLE
severe problem destroys database

### ISSUE THREAD

**Issue by piggy00wiggy** [JabRef/jabref#3782] opened 2018-02-27 06:40 UTC
- [yes] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1  on  windows 10 and Mac OS 10.13.3

Steps to reproduce:

1. create a new entry and copy into the source information from google scholar
2. drag pdf file onto the entry
3. so many other entries are lost and converted to the duplicates of some one (as shown in pic)

> 
![untitled](https://user-images.githubusercontent.com/7113010/36714213-2dc1bed0-1bcc-11e8-867b-0d4c8f2bfc7c.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by stefan-kolb** [comment] 2018-02-27 10:09
I tried it with a small test bib and attached the PDF to the new entry and could not reproduce this issue.

**Comment by anassal** [comment] 2018-02-27 11:48
This seems to be related to #3501 which has been hopefully fixed in the recent development versions. 

@piggy00wiggy Did this happen in the stable version version 4.1 (as your reported), the latest master version (`JabRef-4.2-dev--snapshot--2018-02-27--master--a51fff8e0.jar`), or both?

**Comment by piggy00wiggy** [comment] 2018-03-04 07:05
Hi @anassal I met it in jabref 4.1, now I have turned back to jabref 3.8.2 which works well

**Comment by tobiasdiez** [comment] 2018-03-04 10:05
This should indeed be fixed in the most recent development version.

**Closed by tobiasdiez** 2018-03-04 10:05 UTC
Labels: waiting-for-feedback
