### ISSUE TITLE
Uncaught exception occurred in Tread[#36,JavaFX Application Thread,5,main]

### ISSUE THREAD

**Issue by VegemiteEnjoyer** [JabRef/jabref#9644] opened 2023-03-01 06:44 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

macOS

### Details on version and operating system

macOS Ventura 13.2.1 (M1)

### Checked with the latest development build

- [x] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Issue persists from 5.9 to main development version 5.10. 

Steps to reproduce:
1. Open library
2. Right click "All Entries" 
3. "Add subgroup"

Log attached

### Appendix

...
<details>

<summary>Log File</summary>
java.lang.StringIndexOutOfBoundsException: Range [1, 2) out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.glass.ui.mac.MacAccessible.accessibilityAttributeValueForParameter(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoopImpl(Native Method)
	at org.jabref.merged.module@5.10.202/com.sun.glass.ui.mac.MacApplication._enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.glass.ui.Application.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.glass.ui.EventLoop.enter(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.stage.Stage.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.scene.control.HeavyweightDialog.showAndWait(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.scene.control.Dialog.showAndWait(Unknown Source)
	at org.jabref@5.10.202/org.jabref.gui.JabRefDialogService.showCustomDialogAndWait(Unknown Source)
	at org.jabref@5.10.202/org.jabref.gui.groups.GroupTreeViewModel.lambda$addNewSubgroup$7(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.10.202/org.jabref.gui.groups.GroupTreeViewModel.addNewSubgroup(Unknown Source)
	at org.jabref@5.10.202/org.jabref.gui.groups.GroupTreeView.lambda$createContextMenuForGroup$26(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.10.202/com.sun.glass.ui.mac.MacView.notifyMouse(Unknown Source)
</details>

**Comment by Siedlerchr** [comment] 2023-03-01 19:49
Hm,

this seems like it's some javafx bug. I have a 16" MacBook M1,  with Ventura 13.2.1 and that works fine. 
Do you have some accessibility thing like VoiceOver or any other related thing enabled?  Or Keyboard? See #7459

I stumbled across this bug here https://bugs.openjdk.org/browse/JDK-8235989?attachmentViewMode=gallery 


<img width="1125" alt="grafik" src="https://user-images.githubusercontent.com/320228/222248262-4dad3ac6-2dca-4551-9747-d7aa44853b43.png">

**Comment by VegemiteEnjoyer** [comment] 2023-03-02 02:31
Good catch: I've been using an on screen keyboard to figure out a different language layout.
After I closed it, JabRef has been working fine. Thanks for that!

**Comment by Siedlerchr** [comment] 2023-03-06 20:21
Duplicate of #7459

**Comment by calixtus** [comment] 2023-03-06 20:21
Marked as duplicate Thanks for your interest in JabRef!

**Closed by Siedlerchr** 2023-03-06 20:21 UTC
Labels: status: duplicate, os: macOS
