### ISSUE TITLE
Articles can no longer be assigned to groups via drag'n'drop

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2098] opened 2016-09-29 18:56 UTC
JabRef 3.7dev--snapshot--2016-09-29--latex-free-fields--93e665e
windows 10 10.0 amd64 
Java 1.8.0_101

1. Select an item and try to drag'n'drop it onto an existing group
2. Nothing happens
3. Adding the groups name manually to the "Groups" field of the item does work, however, and assigns the item to the group

(see also: https://github.com/JabRef/jabref/issues/1993)

**Comment by AEgit** [comment] 2016-09-30 14:40
This bug is still present in:

JabRef 3.7dev--snapshot--2016-09-30--latex-free-fields--0ee1d17

**Comment by AEgit** [comment] 2016-10-03 10:59
The bug is also present in the current master build:
JabRef 3.7dev--snapshot--2016-10-03--master--565676c

**Comment by koppor** [comment] 2016-10-03 12:01
Thank you for constantly checking. You see pull requests listed here as soon as someone starts working in it. We currently have no money to pay someone for that. Thus, it depends on our free time. - If you can spend some more time, we would like to encourage you to check https://help.jabref.org/en/FAQcontributing - especially the part asking for improvement of our help pages <https://help.jabref.org/en/>. We have plenty of open issues there: https://github.com/JabRef/help.jabref.org/issues/

**Comment by AEgit** [comment] 2016-10-03 13:09
@koppor: When rereading my comments I realize that it may sound as I was blaming the development team for not having fixed the issue already. I'm sorry if I came across like this, that was never my intention! I've just reported the presence of this bug in the master build, because previously it was just present in one of the other branches and I wanted to make sure, that everyone knew it was now also present in the master branch.
Thanks again for this great piece of software! I shall see, whether I can devote some time to improve the help pages!

**Comment by lenhard** [comment] 2016-10-03 14:31
@AEgit Nevermind :-) We need good and reproducible issue reporting. Our main problem is that we currently do not have the man power to keep up with issue fixing. As long as you do not get angry when the issue lies around unfixed, we won't be angry as well.

Having said that, you *do appear* as someone who would like to contribute. If so, this will be very welcome! Even if you cannot produce code, there are many ways in which you could help. Many things should be updated or documented and we will be very grateful if you help for instance with the web pages. @mlep is sort of our managing director for localization and documentation, I am sure he can provide a few more pointers.

**Comment by AEgit** [comment] 2016-10-03 14:54
@lenhard : No worries, I will definitely not get angry. Most bugs I report, are just small things - it would be nice, if they were fixed, but they are no show-stoppers. I just tend to report a bug, when I come across it.
If there ever was a show-stopper that couldn't be fixed in time I would either have to a) learn Java and try to fix it on my own or b) look for an alternative to Jabref. But there should never be any hard feelings, as Jabref is a free and open source project - no reason for the users to "demand" something.

Thanks also for pointing out, how I could further contribute to the project! I'll see what I can do about it!

**Comment by mlep** [comment] 2016-10-03 15:17
@AEgit: Since you seem a heavy user of JabRef, you may know in details some of its features.
Currenly, part of JabRef help is outdated (e.g. https://help.jabref.org/en/FileLinks) or in the state of a stub (e.g. https://help.jabref.org/en/CleanupEntries). So your knowledge of JabRef could be quite helpful!

I suggest you to browse through the help (https://help.jabref.org/en/), to pick up an item to work on, and to create an Issue (https://github.com/JabRef/help.jabref.org/issues) to signal what is being done (so that somebody else does not start improving the same item...).

Additionally:
- as you could see, there are already a list open issues you can pick up from (https://github.com/JabRef/help.jabref.org/issues).
- if you are fluent in a language other than English, you could also help in translating the interface or the help).

**Comment by AEgit** [comment] 2016-10-04 07:43
@mlep: Thank you very much for the information! I shall have a look at it. I might be able to help with the translation to German and Italian.

@lenhard: I've seen you've added the labels "enhancement", "groups" and "ui". Shouldn't there also be "bug"? Because this functionality was present in previous versions - indeed, this is actually a regression.
Furthermore, this issue seems to also affect the group assignment: It is not possible anymore to drag'n'drop one group to another to create a group-subgroup relationship.

**Comment by lenhard** [comment] 2016-10-04 08:40
@AEgit You are correct, thanks for pointing out!

**Comment by matthiasgeiger** [comment] 2016-10-14 07:26
Just merged a fix to `master`, i.e., the new dev builds should work again.

**Closed by matthiasgeiger** 2016-10-14 07:26 UTC
Labels: bug, groups, ui

**Comment by AEgit** [comment] 2016-10-14 07:51
Thanks a lot!

I can confirm that this bug has been fixed in:
JabRef 3.7dev--snapshot--2016-10-14--master--fb0990d

I've just noticed one new behaviour with this fix compared to older versions, which did not exhibit this bug. Previously, when you reassigned an item/article to a new group, the format of the added lines in the "Groups" field would be as follows:

OldGroup_1, OldGroup_2, NewGroup_1, NewGroup_2

With the new fixed version, the new groups NewGroup_1 and NewGroup_2 are added as follows:

OldGroup_1, OldGroup_2,NewGroup_1,NewGroup2

i.e., in the new fixed version, there's no space between the commas separating the new entries. I just wanted to report this, as I'm not sure whether this is an intended change and/or whether this new behaviour causes any issues.

**Comment by matthiasgeiger** [comment] 2016-10-14 07:58
Thanks for the feedback.

@tobiasdiez Is this intended? Or can this cause some trouble?

**Comment by AEgit** [comment] 2016-10-20 17:50
Can we reopen this? Or should I create a new ticket? The problem itself is fixed, but I just wanted to make sure, that the different/new behaviour does not cause any other issues - see posts above.

**Comment by tobiasdiez** [comment] 2016-10-21 00:54
This behavior is not intended. @AEgit can you open a new issue please.

**Comment by AEgit** [comment] 2016-10-21 07:32
Done. See here:
https://github.com/JabRef/jabref/issues/2184
