### ISSUE TITLE
Jabref no longer compatible with latest Java ?

### ISSUE THREAD

**Issue by raslebol** [JabRef/jabref#293] opened 2015-11-05 14:19 UTC
For a few days now, Jabref will erratically close, as I switch back to it, after having used other apps.
As this seems to correspond with the latest Java update, I wonder if it is still compatible ? If this is so, older Java version are not easy to install (very often, just a zipped folder with no obvious setup), so a fixing would be desirable for lambda users as I am.

Thanks

**Comment by koppor** [comment] 2015-11-05 14:28
Which java version do you run  (`java -version` on command line)? Which JabRef version do you use? Here at `1.8.0_66`, it runs perfectly.

**Comment by lenhard** [comment] 2015-11-05 15:22
This is very very very unlikely. Backwards compatibility is one of Java's most important goals and the only event where I ever ran into such problems were security permission issues with certificates or dynamic class loading in RMI. Whatever the reason for such an error, I'll bet it is not a Java update. 

Also, I cannot reproduce this bug (I still have `1.8.0_65`, though)

**Comment by raslebol** [comment] 2015-11-05 17:21
It states "Version 8 Update 65". Concerning backwards compatibility, it could well be not as complete as expected: since this update, I have been signaled other new problems by colleagues. I would like to stress that Jabref does run with no error, until it will suddendly stop. This is the only ap (I currently use several others at the same time) with does so.

**Comment by koppor** [comment] 2015-11-05 17:26
Which JabRef version do you use?  

----- Ursprüngliche Nachricht -----
Von: "raslebol" <notifications@github.com>
Gesendet: ‎05.‎11.‎2015 18:21
An: "JabRef/jabref" <jabref@noreply.github.com>
Cc: "Oliver Kopp" <koppdev@googlemail.com>
Betreff: Re: [jabref] Jabref no longer compatible with latest Java ? (#293)

It states "Version 8 Update 65". Concerning backwards compatibility, it could well be not as complete as expected: since this update, I have been signaled other new problems by colleagues. I would like to stress that Jabref does run with no error, until it will suddendly stop. This is the only ap (I currently use several others at the same time) with does so.

**Comment by raslebol** [comment] 2015-11-05 17:32
latest 2.10. 
I have made some tests since then. Could some Adobe program be the cause, if one considers that I call pdf documents, using links from Jabref ? I have removed "Adobe community help", and did encounter the problem since then ...

**Comment by koppor** [comment] 2015-11-06 09:55
Yes. External programs could cause issues. I will close the issue as you seem to have resolved the issue by changing the Acrobat Reader configuration.

**Closed by koppor** 2015-11-06 09:55 UTC
