### ISSUE TITLE
Search term highlighted even without having focus

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#1293] opened 2016-04-25 11:42 UTC
JabRef version 3.3 on Ubuntu 14.04

Steps to reproduce:

1. Search for something in the database e.g. "Doe"
2. Hit enter
3. Search performs correctly
4. Switch tab to another bib file
5. Switch back to tab with "Doe" entries.

-> "Doe" gets highlighted in the search field, suggesting that it has the focus to enter a new search term, similar to the behavior of web-browsers. However, in contrast to browsers, a keyboard input is not recognized by the search bar.
![image](https://cloud.githubusercontent.com/assets/8830305/14782697/28fcf048-0aeb-11e6-8ad0-85acd69f4e76.png)

Expected behavior:
- either the search field should get the focus, so a new search term can be typed immediately
- or: the search term should be highlighted only after the user clicked into the search bar.

**Comment by simonharrer** [comment] 2016-04-25 11:56
Hm, cannot reproduce on my machine. The search bar does not get the focus here.

**Comment by teertinker** [comment] 2016-04-25 12:20
No, the search bar does not have the focus, but the search term is highlighted as if it had the focus. In the screenshot, "Dodd" in the search bar is highlighted, similar to the browser address-bar, after a left-click. From my perspective the jabref behavior is irritating, because i see the highlighted "Dodd" and I am inclined to type my new search term immediately, but jabref has the focus somewhere else. 

May be this is intended and I have to get used to it. But I think many search bars work differently: a highlighted search term means: the search bar has the focus and you can enter a new search term
for example the search bar in:
http://www.dict.cc/?s=dodd

**Comment by simonharrer** [comment] 2016-04-25 12:28
Maybe this is an OS issue? On windows, I cannot reproduce. 

When switching back, the search term should not be focused/selected.

**Comment by matthiasgeiger** [comment] 2016-04-25 12:28
It is not marked/highlighted on my windows machine. Even when I mark it and switch the tabs the marking disappears...

**Comment by teertinker** [comment] 2016-04-25 12:42
Indeed, on my windows machine, it doesn't happen.

As a matter of fact, after switching the tab, my search term is always selected (and the search field never has focus). My first idea was, this could be related to the highlighting function, that marks the search term in the preview windows and the entry editor and somehow applies its highlighting also to the search field. But than it shouldn't be Linux only.

**Comment by teertinker** [comment] 2016-04-25 15:07
This issue is already present in JabRef 2.10. With a search bar at the left, however, one didn't notice the bug, because the search term was not tab specific and changed at switching tab.

**Comment by simonharrer** [comment] 2016-05-09 15:06
@koppor maybe something for the stupro as some of them have linux systems?

**Comment by stefan-kolb** [comment] 2016-05-16 16:08
This might be caused by some preference settings. Could you please export your settings and reset the the defaults afterwards? If this solves your issue please upload your exported preferences for further investigation!

**Comment by teertinker** [comment] 2016-05-18 16:30
I did reset to default. The same behavior still exists. 

    On Monday, May 16, 2016 6:08 PM, Stefan Kolb <notifications@github.com> wrote:
 

 This might be caused by some preference settings. Could you please export your settings and reset the the defaults afterwards? If this solves your issue please upload your exported preferences for further investigation!—

**Comment by stefan-kolb** [comment] 2016-08-12 10:33
I can reproduce this issue on Ubuntu.

**Comment by oscargus** [comment] 2016-08-12 11:02
And I can reproduce it on CentOS (not surprisingly).

**Comment by oscargus** [comment] 2016-08-12 11:07
If you type text in Web search and select it while in the other tab, the search text will not be highlighted when you return (first time). It is even enough to select it once and then leave the cursor in that field (but not if you do not select it first).

**Comment by bartsch-dev** [comment] 2016-09-22 10:40
With the new searchbar I cannot reproduce this, can anyone else?

**Comment by koppor** [comment] 2016-09-23 00:25
@teertinker We think, that is already fixed in our development version.
Please use a development build from http://builds.jabref.org/master
The fix will be included in the next release.

**Closed by koppor** 2016-09-23 00:25 UTC
Labels: bug, linux, search, stupro, ui
