### ISSUE TITLE
Warning Message for Moving Attached Open Files

### ISSUE THREAD

**Issue by Hosein-Rahnama** [JabRef/jabref#10121] opened 2023-07-27 20:41 UTC
Suppose that you attach a file to an entry. Then, using a cleanup you want to move that file to the General File Directory of the library. If the attached file is open, the file is not moved but no warning message is shown. It would be nice to have such a message to let the user know what just happened.

**Comment by ThiloteE** [comment] 2023-07-29 19:00
Agreed

**Comment by DohaRamadan** [comment] 2023-08-29 08:35
Can i work on this?

**Comment by ThiloteE** [comment] 2023-08-29 08:49
Sure, go ahead :-)

**Comment by koppor** [comment] 2024-04-08 22:20
- `org.jabref.gui.DialogService#notify` should be called at the place
- `Logger.warn(...)` should be issued
- Challange: Pass `DialogService` down to the class where the issue is send...

**Comment by Simran-Sunil** [comment] 2024-05-17 02:03
Can I work on this issue?

**Comment by HrithikPadavala** [comment] 2024-06-08 23:55
I want to grab this issue if it is still open and no one is working on it

**Comment by koppor** [comment] 2024-06-09 10:48
@Simran-Sunil I didn't see any activity for three weeks, thus, I assigned @HrithikPadavala .

**Comment by HrithikPadavala** [comment] 2024-06-23 00:26
Hi @koppor , I have spotted that the corresponding function and added log warning as you can see in the attached picture but unable to instantiate DialogServive/JabRefDialogService variable inside MoveFileCleanup.java to call notify method. Could you please tell me how can I create and call notify method
![Untitled](https://github.com/JabRef/jabref/assets/71377534/bbb1fd49-b3a3-489a-acae-e2d3aab71bcd)

**Comment by HrithikPadavala** [comment] 2024-06-23 00:29
Should I call notify from within CleanupAction.java only??

**Comment by koppor** [comment] 2024-06-24 20:09
Please use the common logging practices:

```diff
- LOGGER. warn (exception. toString());
+ LOGGER. warn ("Could not move file", exception);
```

**Comment by koppor** [comment] 2024-06-24 20:10
@HrithikPadavala Use `org.jabref.gui.DialogService#notify`. Pass `Localization.lang("Could not move file.")` as parameter. If `dialogService` is not available, get it passed via the constructor.

**Comment by HrithikPadavala** [comment] 2024-06-27 16:02
Hi @koppor , solved the issue and opened a PR

**Comment by koppor** [comment] 2024-06-27 18:47
> Hi @koppor , solved the issue and opened a PR

@HrithikPadavala The PR doesn't seem to link the this issue (as required in the PR description template). Otherwise, I would see a link to it here. 

I am on my mobile and cannot check the PR list....

**Comment by HrithikPadavala** [comment] 2024-06-28 23:17
Updated everything as required and committed too. Someone please check and confirm. Thanks.

**Comment by koppor** [comment] 2024-07-02 15:22
> Updated everything as required and committed too. Someone please check and confirm. Thanks.

Please look at the pull request. The automatic checks show errors:

![image](https://github.com/JabRef/jabref/assets/1366654/6cb2c1e6-5da3-42b3-8ac4-4c6a65eac6c3)

See https://github.com/JabRef/jabref/pull/11438. Scroll down. Click on "details" at each failing test.

After you fixed them, we can have a detailed look. Otherwise our brains are too distracted by issues obvious to us.

**Comment by HrithikPadavala** [comment] 2024-07-11 15:46
Opened another PR with branch other than main this time to resolve merge issues please review

**Comment by koppor** [comment] 2024-07-11 16:30
> Opened another PR with branch other than main this time to resolve merge issues please review

Please resolve the merge conflicts so that the CI can run. First, all checkstyle issues should be solved. This enables us to focus on the content.

**Comment by HrithikPadavala** [comment] 2024-07-11 20:23
@koppor Resolved all issues but something related to changelog is not getting resolved. This is the only file need to be reviewed. So that this issue can be closed.

**Comment by koppor** [comment] 2024-07-11 20:31
> @koppor Resolved all issues but something related to changelog is not getting resolved. This is the only file need to be reviewed. So that this issue can be closed.

Please try to keep context in comments. Comments on PR issues should go to PRs. I replied at https://github.com/JabRef/jabref/pull/11484#issuecomment-2223871387.

**Comment by juliusalberto** [comment] 2024-10-07 02:57
Hi, can I work on this issue? Thanks!

**Comment by juliusalberto** [comment] 2024-10-10 01:57
Hi - it seems like that I cannot recreate the issue in my environment. Is it something to do with how Mac filesystem works? When I tried to cleanup things - even though the file is open somewhere else (e.g. Microsoft Word), it won't throw any IOException, it just moves it effortlessly. 

Do you think I should try it with a Windows machine? Thanks

**Comment by koppor** [comment] 2024-10-10 13:51
> Do you think I should try it with a Windows machine? Thanks

You can "quickly" fire up a Windows 10 VM using Vagrant as described at https://github.com/JabRef/jabref/tree/main/scripts/vms. https://github.com/JabRef/jabref/tree/main/scripts/vms/windows10 proived the `Vagrantfile` for Windows 10.

**Closed** 2024-10-25 13:33 UTC
Labels: type: enhancement, ui, good first issue, Logging, FirstTimeCodeContribution, 📍 Assigned
