### ISSUE TITLE
Some input fields are unusably narrow (macOS)

### ISSUE THREAD

**Issue by szhorvat** [JabRef/jabref#6844] opened 2020-09-02 11:53 UTC
JabRef 5.1--2020-08-30--e023aa0
Mac OS X 10.14.6 x86_64 
Java 15

Some of the fields to enter optional BibTeX fields are unusably narrow unless JabRef's window is made very wide. Here's a screenshot:

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/1212871/91977801-7a512d00-ed23-11ea-8cef-9ed0c0c0a07a.png">

I do not recall seeing this problem in 5.0. I assume it is new in 5.1.

**Comment by Siedlerchr** [comment] 2020-09-02 11:56
Duplicate of #6097 
You can also change the entry preview setting to have it as an extra tab.

**Closed by Siedlerchr** 2020-09-02 11:56 UTC
