### ISSUE TITLE
export sort order: use specified order

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10157] opened 2023-08-10 23:27 UTC
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Go to preferences
2. Go to Import and export
3. Select Use specified order
4. Remove the last sort order by using the "-" button
5. Click Save
6. Exception occurs

![afbeelding](https://github.com/JabRef/jabref/assets/141878924/feb0393f-a1ce-4f41-a745-2e530452348b)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment] 2023-08-11 17:31
Can you please try with the latest development version? https://builds.jabref.org/main/
There have been many fixes since the release and I think this was also touched

**Comment by thedino-girl** [comment] 2023-08-11 17:39
As written in the bug report "I have tested the latest development version and the problem persists"
The bug is present in the latest dev version too!

Why is the font text color everywhere much brighter then in version 5.9 (I think it's white)?
The same dark theme is chosen...
Was the dark theme changed in 5.10?
How can I get the font text color as in 5.9 (see exception font color) for the dark theme?

![afbeelding](https://github.com/JabRef/jabref/assets/141878924/20e24f04-8f4f-420a-aaea-a3ff1c6b7f93)

**Comment by Siedlerchr** [comment] 2023-08-11 17:55
Sorry I could now reproduce this as well

**Comment by thedino-girl** [comment] 2023-08-11 21:11
> Why is the font text color everywhere much brighter then in version 5.9 (I think it's white)? The same dark theme is chosen... Was the dark theme changed in 5.10? How can I get the font text color as in 5.9 (see exception font color) for the dark theme?

Do you know this?

**Comment by papatekken** [comment] 2023-08-30 09:14
I can only found Export screen but not Import in Preferences.
Seems it is hardcoded and it throws exception when less than 3 sort orders are available. 
Please assign to me and I will investigate further.

**Comment by the-dino-girl** [comment] 2023-09-03 00:44
> I can only found Export screen but not Import in Preferences. 

Yes, I used 5.9 at the time I tested it. The preferences menu changed in 5.10

**Closed** 2023-09-10 16:31 UTC
Labels: bug, preferences
