### ISSUE TITLE
Linked files are badly aligned

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2941] opened 2017-06-24 22:51 UTC
The text in form fields is badly aligned and has sometimes a grey background.

JabRef 4.0.0-dev--snapshot--2017-06-18--master--c0ca85e07
Linux 4.9.16-gentoo+ amd64 
Java 1.8.0_131

![selection_302](https://user-images.githubusercontent.com/298682/27512441-f960f09c-593f-11e7-89ac-a0e419b2501c.png)

**Comment by tobiasdiez** [comment] 2017-06-25 13:29
The display of linked files is also not ideal on Windows. I already tried a few days ago to fix these alignment problems but wasn't successful (all text fields and other controls in the editor appear to have a negative top margin - no idea why). If somebody else wants to play around, he is happily invited to do so. For the moment, I wouldn't assign it to the 4.0 milestone since it is not critical (the information is readable, just not as nice as is could be).

**Comment by sauliusg** [comment] 2017-07-21 17:14
I can confirm the bug on:
JabRef 4.0-dev--snapshot--2017-07-21--master--46f58d6
LinuxMint-18.1
Java 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11
Sure, not critical, but important to attract new users ;)
Cheers,
Saulius

**Comment by lenhard** [comment] 2017-08-11 13:52
Since this is not a functional error, but UI polishing, I'll relabel it from "bug" to "enhancement".

**Comment by lenhard** [comment] 2017-08-21 12:58
@jonasstein @sauliusg  Could you perhaps try out this version http://builds.jabref.org/increase-textarea-size/ It assigns a minimum height to all text fields, so hopefully file attachments should be more readable. It just means that you might have to scroll in the general tab. Do you think that's better? Would you want an even bigger minimum size or a smaller one?

**Comment by lenhard** [comment] 2017-08-25 12:33
We consider this fixed thanks to #3141, so I am closing this issue.

**Closed by lenhard** 2017-08-25 12:33 UTC
Labels: enhancement, entry-editor, ui
