### ISSUE TITLE
Group counters cut off large numbers when default font setting is changed

### ISSUE THREAD

**Issue by juejung** [JabRef/jabref#9341] opened 2022-11-02 14:14 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04 with Gnome 42.4

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open JabRef 5.8--2022-10-31--e7c8535
2. Change Font size to size 14 under Preferences --> Appearance
3. Turn on Group side panel
4. The "All entries" counter should read 4106 but cuts off number and shows as 106 because the number field is not expanded with the font size

![Screenshot from 2022-11-02 10-10-21](https://user-images.githubusercontent.com/1740639/199511348-2c0a8e83-a9f2-42dc-850f-db5ed5c67d6e.png)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by mlep** [comment] 2022-11-02 14:25
Looks similar to https://github.com/JabRef/jabref/issues/8797

**Comment by Siedlerchr** [comment] 2022-11-02 20:21
Duplicate of #8797

**Closed by Siedlerchr** 2022-11-02 20:21 UTC
