### ISSUE TITLE
Mac OS X: Pasting bibtex entry creates duplicate entries

### ISSUE THREAD

**Issue by angoodkind** [JabRef/jabref#4699] opened 2019-02-25 01:10 UTC
JabRef version: 5.0-dev

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When copying and pasting a bibtex entry into jabref, it creates duplicate entries for the citation. This occurs regardless of if I have All Entries open, or am just viewing a group or subgroup.

<details>
  <summary>Log File</summary>
Opening: /Users/adamg/Dropbox/adam.bib
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
Can only load style files: Preview
Opening: /var/folders/8w/wfth0jx51l960l8mgcjlxn580000gn/T/jabref7386437712883599037.bib
Opening: /Users/adamg/Dropbox/adam.bib
Opening: /var/folders/8w/wfth0jx51l960l8mgcjlxn580000gn/T/jabref7386437712883599037.bib
Opening: /Users/adamg/Dropbox/adam.bib
Opening: /var/folders/8w/wfth0jx51l960l8mgcjlxn580000gn/T/jabref7386437712883599037.bib
Opening: /Users/adamg/Dropbox/adam.bib
Opening: /var/folders/8w/wfth0jx51l960l8mgcjlxn580000gn/T/jabref7386437712883599037.bib
Opening: /Users/adamg/Dropbox/adam.bib
Can only load style files: Preview  
</details>

**Comment by CaptainDaVinci** [comment] 2019-03-07 14:46
I tried copy pasting a _BibTex_ entry into _JabRef_ but it did not create duplicates, am I missing something?

**Comment by angoodkind** [comment] 2019-03-07 15:10
Nope, that's exactly what I did too.

**Comment by CaptainDaVinci** [comment] 2019-03-07 17:00
I am not able to reproduce it, I am copying an entry and pasting it back in the same library.

**Comment by angoodkind** [comment] 2019-03-07 17:25
I've been copying the entries from elsewhere, usually Google Scholar. It seems to happen when I've had the application open for a while and done multiple additions. It doesn't happen the first time.

**Comment by johannes-manner** [comment] 2019-03-28 14:31
Can you provide a detailed description which steps are needed to reproduce this bug?

**Comment by angoodkind** [comment] 2019-03-28 16:26
I'm not sure what other details I can provide. I copy the bibtex from google scholar in Chrome. I then paste it into the main window in jabref, and it creates two duplicate entries.

**Comment by AEgit** [comment] 2019-03-29 14:18
Can you reproducibly generate this behaviour by copying certain entries and a certain number of (ordered?) entries from Google Scholar?
If so, can you please:

1. Provide links to the entries that cause the issue.
2. Provide the number of entries that is necessary to reproduce the issue.
3. Detail in which order you copied the entries from Google Scholar to JabRef.

**Comment by angoodkind** [comment] 2019-04-13 17:39
This time it occurred when copying just the 2nd entry.

Using [this query](https://scholar.google.com/scholar?hl=en&as_sdt=1%2C14&q=nlp+healthcare&btnG=), I copied the first entry into jabref without issue. But copying the bibtex of the 2nd and 3rd entries created duplicates.

**Comment by matthiasgeiger** [comment] 2019-04-13 18:35
Can you please tell us which OS you are using? 
We had some reports of duplicated execution of some commands in Mac OS X...

**Comment by angoodkind** [comment] 2019-04-13 18:36
I am also on OS X, v. 10.14.4

**Comment by matthiasgeiger** [comment] 2019-04-15 05:25
Thank you for the feedback!

So it is most likely the same underlying problem as in #4845 and #4836

**Comment by Siedlerchr** [comment] 2019-08-24 10:56
Thanks to @LinusDietz  and @stefan-kolb  this issue is now fixed in the latest master!

**Comment by LinusDietz** [comment] 2020-04-28 06:17
This behavior is present again in current master build on MacOS.

**Comment by Siedlerchr** [comment] 2020-05-03 10:38
I think this code was recently reversed in #6313 that could explain it 
@calixtus

**Comment by koppor** [comment] 2020-05-12 05:36
@Gena928 Cannot reproduce the issue. Maybe, it would help to have a screen recording of this issue?

Would it be possible to add a [Loom](https://www.loom.com/) video here? Maybe visualizing key strokes using [KeyCastr](https://alternativeto.net/software/keycastr/) also helps to understand what's going on?

**Comment by koppor** [comment] 2020-06-09 06:46
Try of @Siedlerchr:

- `master` branch used
- `setupKeyBindings` in MainTable removed

Next step:

- Do this change in this PR.
- Test on Win, Mac, Linux
   1. key binding of copy change to `Ctrl+Shift+Alt+Q`
   2. key binding of paste change to `Ctrl+Shift+Alt+P`
   3. try to paste in entry editor
   4. try to paste in main table
   - paste: bibtex entry 
   - paste: plain text

**Closed** 2020-08-02 11:40 UTC
Labels: os: macOS, type: bug 🐛
