### ISSUE TITLE
JabRef does not open database with groups

### ISSUE THREAD

**Issue by CharlesVilliers** [JabRef/jabref#3864] opened 2018-03-19 12:34 UTC
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1 on Mac OS X 10.13.3

In my database, I automatically created groups using the keywords field. After a minute browsing around, the fan started running very loudly and I quit JabRef. I wanted to start it again and it asked whether I wanted to restore the backup file. No matter whether I clicked Yes or No the file was not opened. I renamed the bak or sav files but none of these would be opened, even after a restart of the computer. I then removed the last lines of the file:

@Comment{jabref-meta: grouping:
0 AllEntriesGroup:;
1 AutomaticKeywordGroup:Keywords\;0\;keywords\;\;\;>\;1\;\;\;\;;
}

Afterwards, the file was opened flawlessly.

This error is reproducable. It only seems to occur when I choose ; instead of , as separator.

**Comment by tobiasdiez** [comment] 2018-03-19 13:32
I think this is a duplicate of https://github.com/JabRef/jabref/issues/3646 and should be fixed in the latest [development version](http://builds.jabref.org/master/).

**Closed** 2018-03-19 13:33 UTC
Labels: duplicate, groups, waiting-for-feedback

**Comment by CharlesVilliers** [comment] 2018-03-19 14:06
Should have searched beforehand.
