### ISSUE TITLE
irregularly losing ability to edit data in biblatex source tab

### ISSUE THREAD

**Issue by NRJank** [JabRef/jabref#6936] opened 2020-09-23 18:20 UTC
JabRef 5.2--2020-09-21--0da0f0c
Windows 10 10.0 amd64 
Java 14.0.2
[Yes ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Having difficulty identifying trigger to reproduce problem.  

When adding to / editing database, I sometimes lose the ability to edit any of the data in the biblatex source tab.  I can switch to the tab, highlight / copy anything in the tab, switch to other tabs and make entries in the different entry fields.  those changes show up in the biblatex source tab, but no cursor appears when clicking into the the source tab text field.  things that are highlighted can't be deleted.  the only way to get direct editing ability back is by closing Jabref.  Upon restarting, everything works as expected. can go in and manually edit within the source tab.  

realize this one might have to sit until somehow able to reliably reproduce, but wanted to document it here. 

<details>
Log file always blank, nothing to copy.

contents of console below, but I'm not certain any of the messages are related. The StatusLogger messages appear on start, and the immediately following ANTLR messages all appear the first time sort the list or edit an item in it:

```
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8%d [%thread] %-5level %logger - %msg%n%d [%thread] %-5level %logger - %msg%nANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8%d [%thread] %-5level %logger - %msg%n java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at de.undercouch.citeproc.csl.internal.format.HtmlFormat.doFormatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.csl.internal.format.BaseFormat.formatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitations(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitation(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStylePreviewLayout.generatePreview(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.preview.PreviewViewer.lambda$update$3(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.BackgroundTask$1.call(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source) ~[org.jabref:?]
        at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[org.jabref.merged.module:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
%d [%thread] %-5level %logger - %msg%n java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at de.undercouch.citeproc.csl.internal.format.HtmlFormat.doFormatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.csl.internal.format.BaseFormat.formatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitations(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitation(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStylePreviewLayout.generatePreview(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.preview.PreviewViewer.lambda$update$3(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.BackgroundTask$1.call(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source) ~[org.jabref:?]
        at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[org.jabref.merged.module:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
%d [%thread] %-5level %logger - %msg%n java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at de.undercouch.citeproc.csl.internal.format.HtmlFormat.doFormatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.csl.internal.format.BaseFormat.formatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitations(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitation(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStylePreviewLayout.generatePreview(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.preview.PreviewViewer.lambda$update$3(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.BackgroundTask$1.call(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source) ~[org.jabref:?]
        at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[org.jabref.merged.module:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
%d [%thread] %-5level %logger - %msg%n java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at de.undercouch.citeproc.csl.internal.format.HtmlFormat.doFormatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.csl.internal.format.BaseFormat.formatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitations(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitation(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStylePreviewLayout.generatePreview(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.preview.PreviewViewer.lambda$update$3(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.BackgroundTask$1.call(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source) ~[org.jabref:?]
        at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[org.jabref.merged.module:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
%d [%thread] %-5level %logger - %msg%n java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at de.undercouch.citeproc.csl.internal.format.HtmlFormat.doFormatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.csl.internal.format.BaseFormat.formatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitations(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitation(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStylePreviewLayout.generatePreview(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.preview.PreviewViewer.lambda$update$3(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.BackgroundTask$1.call(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source) ~[org.jabref:?]
        at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[org.jabref.merged.module:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
%d [%thread] %-5level %logger - %msg%n java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.util.ArrayList.get(Unknown Source) ~[?:?]
        at de.undercouch.citeproc.csl.internal.format.HtmlFormat.doFormatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.csl.internal.format.BaseFormat.formatBibliographyEntry(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at de.undercouch.citeproc.CSL.makeBibliography(Unknown Source) ~[org.jabref.merged.module:?]
        at org.jabref.logic.citationstyle.CSLAdapter.makeBibliography(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitations(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStyleGenerator.generateCitation(Unknown Source) ~[org.jabref:?]
        at org.jabref.logic.citationstyle.CitationStylePreviewLayout.generatePreview(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.preview.PreviewViewer.lambda$update$3(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.BackgroundTask$1.call(Unknown Source) ~[org.jabref:?]
        at org.jabref.gui.util.DefaultTaskExecutor$1.call(Unknown Source) ~[org.jabref:?]
        at javafx.concurrent.Task$TaskCallable.call(Unknown Source) ~[org.jabref.merged.module:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
```
</details>

**Comment by calixtus** [comment] 2020-09-29 22:43
@NRJank Thanks for this bug report. I'm actually a bit curious, why the antlr parser is complaining. Please report back, if you can find a way to reproduce the bug.

**Comment by NRJank** [comment] 2020-09-29 23:10
haven't found anything consistent yet. couple other times it happens I tried repeating the previous few actions after reopening and it didn't happen. since I'm not always working in that biblatex source tab, its hard to tell when the problem kicks in.

regarding the ANTLR error in the log, consistently the first time I open Jabref I get the Statuslogger errors.  just clicking on any item in the database (no editing, sorting, anything, just clicking on one of the items), Jabref pauses for 5 seconds or so (other clicks do nothing during this time) after which the following appears in the console:

`ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8`

after that, it's fully responsive and doesn't do this again.  I don't usually get the much longer set of messages as in the original report.  not sure what created those.

**Comment by calixtus** [comment] 2020-09-30 18:50
Thank you for the quick response. I believe we need to wait, until some regular reproducibility can be seen or another user is affected by this issue. We'll keep it open.
The antlr issue seems to be another problem. I'll ask @tobiasdiez , if hes got an idea, since he is - I believe - the most experienced one of us with the external dependency resolution in github.

**Comment by tobiasdiez** [comment] 2020-10-01 15:06
The antlr dependency is defined in 
https://github.com/JabRef/jabref/blob/18371b51187890fca1437a8382b806f4c3c27f6c/build.gradle#L137-L138
and it looks like 4.8 should be used for the generation as well as for the runtime. Anyway, I don't think this warning is really related to this issue, and I also wouldn't spent time fixing ANTLR 4 since this only used for the search syntax and we wanted to switch to lucene for this anyway.

(ANTLR 3 should also be removed along with the BST feature, but then we have to look for a new Vorsitzender, @koppor 🦊 )

**Comment by mlep** [comment] 2020-10-01 18:06
I have noticed the same thing with my BibTeX database.
It is a recent problem. It happens from time to time (like one an hour)
Nothing in the log.

JabRef 5.2--2020-09-29--8a44d41
Linux 4.9.0-13-amd64 amd64 
Java 15

**Comment by magsilva** [comment] 2020-10-03 14:12
I have also noticed this problem since JabRef 5.0. I think I could create an example to reproduce the error.

1. Select an entry. You may access the "BibTeX source" tab to verify that you can edit the entry.
2. Modify any field, adding some symbol that would make the entry invalid. For instance, you can add a '{' in any field.
3. Save the database. An error will be shown (as expected).
4. Fix the error (by removing the invalid symbol). 
5. Save the database.
6. Access the "BibTeX source" tab. You cannot edit its content anymore.

Looking at the source code, I believe the problem is at SourceTab.updateCodeArea(). This is the only method that changes the codeArea status (codeArea.setEditable(false). It's kinda trick to run updateCodeArea: any error done when directly editing the code in the "BibTeX source" tab is captured by "SourceTab.storeSource()". To trigger the method 'updateCodeArea', we must create an event that will trigger its listeners (entry.typeProperty() and entry.getFieldsObservable()). That's why I forced an invalid symbol in step 2.

**Comment by magsilva** [comment] 2020-10-03 15:02
This patch seems to do the trick. It re-enables codeArea as editable if the source code is correct (we cannot fix the error introduced in step 2 in the source area, but we can fix it by editing the field, which will trigger the listener and call the 'updateCodeArea()' method, which will enable the codeArea if the source of the BibTeX entry is syntactically correct).

```
diff --git a/src/main/java/org/jabref/gui/entryeditor/SourceTab.java b/src/main/java/org/jabref/gui/entryeditor/SourceTab.java
index aba1aca53..d16fe52e6 100644
--- a/src/main/java/org/jabref/gui/entryeditor/SourceTab.java
+++ b/src/main/java/org/jabref/gui/entryeditor/SourceTab.java
@@ -224,6 +224,7 @@ public class SourceTab extends EntryEditorTab {
             codeArea.clear();
             try {
                 codeArea.appendText(getSourceString(currentEntry, mode, fieldWriterPreferences));
+                codeArea.setEditable(true);
                 highlightSearchPattern();
             } catch (IOException ex) {
                 codeArea.setEditable(false);
```

**Comment by Siedlerchr** [comment] 2020-10-03 15:13
@magsilva  Would you be so kind to submit a PR? That would be really great!

**Comment by calixtus** [comment] 2020-10-03 15:15
I don't understand yet, why the code area is disabled at all...

**Comment by Siedlerchr** [comment] 2020-10-04 18:02
Thanks to @magsilva  this issue should now be resolved in the latester development version (currently building).

**Closed by Siedlerchr** 2020-10-04 18:02 UTC
Labels: entry-editor, status: waiting-for-customer-feedback, ui

**Comment by mlep** [comment] 2020-10-13 12:58
After using JabRef for several days, the issue did not occur. So, I guess it is solved! ;-)
Thank you @magsilva!
