### ISSUE TITLE
Groups: numbers of entries not displayed, but group name can be truncated.

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1320] opened 2016-04-29 07:10 UTC
JabRef-3.4dev--snapshot--2016-04-29--master--2575753.jar 
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
Linux Mint LMDE2

Abstract: if "Show numbers of elements contains in each group" is not selected before group creation/modification, once selected, numbers of entries is not displayed, and name can be truncated.

1) Create a new database
2) In the group settings, UNselect "Show numbers of elements contains in each group"
3) Create a new group named "New group"
4) In the group settings, select "Show numbers of elements contains in each group"
==> The number of entries is not displayed, and the name is truncated (only "New" is displayed) ==> 2 problems.
5) Edit the group (just open the window, and then click on ok without changing the group name)
==> The number of entries is  displayed (0), and the name is properly displayed  ==> OK
6) In the group settings, UNselect "Show numbers of elements contains in each group"
==> The number of entries is not  displayed, and the name is properly displayed ==> OK
7) Edit the group (just open the window, and then click on ok without changing the group name)
8) Go back to step 4
==> The number of entries is not displayed, and the name is truncated (only "New" is displayed) ==> 2 problems.

**Comment by tobiasdiez** [comment] 2016-04-29 18:03
I couldn't reproduce the truncation of the name "New group" but the number think should be fixed with #1326.

**Comment by mlep** [comment] 2016-04-30 17:19
I have just tried with JabRef-3.4dev--snapshot--2016-04-30--master--6542348.jar .
No change (steps described above led to the same results)

**Comment by simonharrer** [comment] 2016-05-24 09:35
Could this be fixed in the current master branch? @mlep @tobiasdiez

**Comment by stefan-kolb** [comment] 2016-06-14 08:15
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Closed by stefan-kolb** 2016-06-14 08:15 UTC
Labels: waiting-for-feedback
