### ISSUE TITLE
Automatic Bug Report-20170220153505

### ISSUE THREAD

**Issue by clccc** [JabRef/jabref#2571] opened 2017-02-20 07:36 UTC
JabRef 4.0.0-dev--snapshot--2017-02-18--master--e36a99e92
Windows 7 6.1 amd64 
Java 1.8.0_102

<details>
<summary>Detail information:</summary>

```
Migrating old preferences.
Opening: G:\abcd\asdfs\xx.bib
runCommand error: Braces don't match.
java.lang.IllegalArgumentException: Braces don't match.
	at org.jabref.logic.bibtex.LatexFieldFormatter.checkBraces(LatexFieldFormatter.java:277)
	at org.jabref.logic.bibtex.LatexFieldFormatter.formatWithoutResolvingStrings(LatexFieldFormatter.java:170)
	at org.jabref.logic.bibtex.LatexFieldFormatter.format(LatexFieldFormatter.java:80)
	at org.jabref.logic.bibtex.BibEntryWriter.writeField(BibEntryWriter.java:152)
	at org.jabref.logic.bibtex.BibEntryWriter.writeRequiredFieldsFirstRemainingFieldsSecond(BibEntryWriter.java:124)
	at org.jabref.logic.bibtex.BibEntryWriter.write(BibEntryWriter.java:53)
	at org.jabref.logic.exporter.BibtexDatabaseWriter.writeEntry(BibtexDatabaseWriter.java:168)
	at org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(BibDatabaseWriter.java:198)
	at org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(BibDatabaseWriter.java:150)
	at org.jabref.gui.exporter.SaveDatabaseAction.saveDatabase(SaveDatabaseAction.java:189)
	at org.jabref.gui.exporter.SaveDatabaseAction.run(SaveDatabaseAction.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at spin.Invocation.evaluate(Invocation.java:175)
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108)
	at java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by koppor** [comment] 2017-02-20 10:34
There seems to be an issue with your bib file.

What steps did you do to get this exception? Can you check your bib file? How large is it?

**Comment by stefan-kolb** [comment] 2017-02-20 14:27
See  #2561?

**Comment by stefan-kolb** [comment] 2017-02-22 00:55
@clccc Can you please add more information?

**Comment by clccc** [comment] 2017-02-23 02:12
Yes, I had modify my .bib file manually.  The size of  bib file is 715KB.  There are similar errors happened when I marking manly entities with specific color with version JabRef 4.0.0-dev--snapshot--2017-02-18--master--e36a99e92 or JabRef 3.8.2 in Win7 and Ununtu 14.04. 
But the older version of jabref 2.10b2  which installed by apt-get install in ubuntu 14.04 works well. so I have to use 2.10b2 now.

**Comment by stefan-kolb** [comment] 2017-02-23 11:54
@clccc Can you send us the Bib file or give a minimal example here on how to reproduce the issue?

**Comment by clccc** [comment] 2017-02-24 01:00
OK, I will send one copy to you.





At 2017-02-23 19:54:13, "Stefan Kolb" <notifications@github.com> wrote:


@clccc Can you send us the Bib file or give a minimal example here on how to reproduce the issue?

**Comment by stefan-kolb** [comment] 2017-02-27 14:10
@clccc I didn't receive anything, but can you please try http://builds.jabref.org/fixExcept/ if it fixes your problem?

**Comment by clccc** [comment] 2017-03-09 07:16
I have sent to notifications@github.com on Feb 24.  Could you give me a new mail address?
Sorry, the newest fix does not work well also.





At 2017-02-27 22:10:34, "Stefan Kolb" <notifications@github.com> wrote:


@clccc I didn't receive anything, but can you please try http://builds.jabref.org/fixExcept/ if it fixes your problem?

**Comment by stefan-kolb** [comment] 2017-03-09 08:41
@clccc The Github adress is just a forwarder from Github 😄 Please send to developers@jabref.org

**Comment by clccc** [comment] 2017-03-15 01:14
⊙﹏⊙b , I am sorry. The bib file have been sent to you.







在 2017-03-09 16:41:08，"Stefan Kolb" <notifications@github.com> 写道：


@clccc The Github adress is just a forwarder from Github 😄 Please send to developers@jabref.org

**Comment by tobiasdiez** [comment] 2017-03-16 22:16
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Closed** 2017-03-16 22:15 UTC
Labels: waiting-for-feedback
