### ISSUE TITLE
Error adding discovered CitationStyles

### ISSUE THREAD

**Issue by EmilVogt** [JabRef/jabref#5304] opened 2019-09-11 08:57 UTC
JabRef 5.0-alpha
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft

Steps to reproduce:

1. start Jabref
2. go to options -> preferences
3. error message appears

The error message only appears after a fresh start of Jabref and when going to the preferences the first time.

Paste your log details here.

<details>
<summary>Detail information:</summary>

```
Something went wrong while adding the discovered CitationStyles to the list. 
java.nio.file.FileSystemAlreadyExistsException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:344)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
	at org.jabref.logic.citationstyle.CitationStyle.discoverCitationStyles(CitationStyle.java:147)
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:46)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:122)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

**Comment by Siedlerchr** [comment] 2019-09-11 09:05
Duplicate of #5246

**Closed by Siedlerchr** 2019-09-11 09:05 UTC
