### ISSUE TITLE
Add entry table column for last author

### ISSUE THREAD

**Issue by joelostblom** [JabRef/jabref#5893] opened 2020-01-29 14:07 UTC
Last author is useful in some disciplines for indicating which research group/lab an article/entry is from. I tried adding `field:authorLast` in the preferences similar to how last author is added in the the bib key, but it shows up as an empty column.

**Comment by calixtus** [comment] 2020-01-29 19:02
Hi @joelostblom , thanks for the note. Please use the gitter channel and the forums about JabRef functionality in the future, and please include the information of the JabRef version etc. as it is delivered in the issue template. Otherwise it's really complicated for everybody to figure out the cause of the issue.

About your question: the field-column is in fact very simple by design. It just prints out the name of the bib(la)tex field with the given field name. "authorLast" is not one, but a fieldformatter pattern (I think) and not implemented as a column-title. It's maybe worth discussing to include this.

**Comment by calixtus** [comment] 2020-01-29 19:02
*for questions about

**Comment by joelostblom** [comment] 2020-01-29 19:43
Sorry about that, I considered the forums but thought this would fall under "smaller suggestions for improvements". I will use the forums or gitter from now on for issues like these!

> "authorLast" is not one, but a fieldformatter pattern (I think) and not implemented as a column-title. It's maybe worth discussing to include this.

Ah ok, thanks for clarifying that. I initially thought that any field that can be used to create a bibtex key could also be used in the columns. I found a workaround that is sufficient for my purpose, I create bibtex keys with the authorLast first in the key and then sort on the key column.

```
# System info
JabRef 5.0-beta.388--2020-01-29--eb988b6
Linux 5.4.15-arch1-1 amd64 
Java 13.0.2
```

**Comment by calixtus** [comment] 2020-01-29 20:19
Oh, this was probably a misunderstanding on my side. Sorry for that. Thanks for the follow-up, I'll put that on the list for smaller enhancements. ;-)

**Comment by tobiasdiez** [comment] 2020-02-01 16:04
A naive implementation of this feature would come with a very high performance cost (as every field value has to be routed through the formatter every time it is displayed or there are changes to an entry). Thus, this would require major restructuring of the code to be implemented properly.

On the other hand, the feature has only a narrow use case. I do understand your particular case, but I guess not many people would use it.

Thus, I'll close this issue for now - with the option to reopen it if more users echo your wish.

**Closed by tobiasdiez** 2020-02-01 16:04 UTC
