### ISSUE TITLE
Groups invisible and scrolling does not work (Regression 3.8)

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2404] opened 2016-12-19 19:14 UTC
JabRef 3.8

This is a regression that was introduced between JabRef 3.7 and JabRef 3.8-dev--snapshot--2016-12-12--master--59d9e35. It is still present in the release version of JabRef 3.8.

1. Open a large JabRef database (>9,000 entries, several hundred groups). The "Groups panel" needs to be visible.
2. Scroll down in the "Groups panel" by leftcklicking onto the scrollbar in the panel and dragging it to the bottom. You've reached the bottom of the "Groups panel".
3. Now scroll upwards in the "Groups panel" without using the scrollbar. Instead, use the mouse wheel. You can scroll upwards up to a certain group. When this group has been reached, it is no longer possible to scroll further upwards using the mouse wheel (even though there are still many groups above that issue-causing group). If you click onto the scrollbar and drag it further upwards, however, it is possible to move further upwards in the groups panel. It is not possible, however, to do that by using the mouse wheel. The upward scrolling reproducibly always stops at the same group.
Furthermore, a couple of groups are invisible above the group which causes/shows (?) the scrolling error. These groups are displayed in JabRef 3.7, but in JabRef 3.8 these groups remain invisible (these might be the actual issue-causing groups???). This means, that in JabRef 3.8 an empty row appears in the group panel instead of the actual group name.

I'm able to reproduce this behaviour with my database. But, I'm not sure, whether it is possible to do that with another database with similar dimensions - I guess, it has something to do with the issue-causing groups, but I can't figure out how the differ from the other groups. If needed, I can provide you with my database, but I would like to not upload it here and rather send it via email/pm (i. e., the database should not be made public).

**Comment by matthiasgeiger** [comment] 2016-12-19 19:25
Do the erratic groups contain some special characters? There was a problem with those which has been fixed lately (see #2394) - as this has been fixed you could check the latest builds at https://github.com/JabRef/jabref/issues/2394. 

If it is not yet fixed we would gladly use your database for debugging purposes. You can send it to developers@jabref.org

**Comment by AEgit** [comment] 2016-12-19 21:34
@matthiasgeiger : Tried the latest build, but the problem persists. I've sent you my database (as mentioned, please don't make it available to the public).

Thank you so much for your help!

**Comment by matthiasgeiger** [comment] 2016-12-21 12:44
Okay I can't really explain why the UI is behaving as described by you, however the underlying reason is that there are some duplicates of group names in the same hierarchy level in the file you sent us. For example "Procynosuchidae" is defined twice (line 251987 and 
252012) - and at exactly this position scrolling stops.

So actually this bug could help you to clean up your quite impressing structure :wink: - however, we, @JabRef/developers, still should investigate how to deal with problems like this...

**Comment by AEgit** [comment] 2016-12-21 15:17
Thank you so much! After clearing those duplicate names, everything was fine.

Should I close the bug report or keep it open for your discussions?

P. S.: Regarding the group structure - thanks for the praise ;)
Indeed, due to the size of my group structure I'm really looking forward to the new JavaFX implementation, which will also allow to search for different group names (see feature request here: https://github.com/JabRef/jabref/issues/1904). Thanks again to all JabRef developers for your hard work!

**Comment by tobiasdiez** [comment] 2016-12-21 15:35
@AEgit I finally found a bit of time to further work on the JavaFX version. I would really appreciate it if you could try the new version http://builds.jabref.org/groupsRework/ and give feedback at https://github.com/JabRef/jabref/pull/2412 (I'm aware that right now a lot of essential features don't work but it's a start.) 

@Topic: I mark this issue as "after-migration-to-javafx" and close it for now as the problem is not mega important and should be resovled in the JavaFX version (thus in the next release after 3.8.1). Moreover, I have no idea to fix the issue in the current Swing implementation. Of course, if somebody feels like he wants to fix this issue, go for it 😃

**Closed by tobiasdiez** 2016-12-21 15:35 UTC
Labels: groups

**Comment by AEgit** [comment] 2016-12-21 16:31
@tobiasdiez: Will do that - thanks a lot! For comments see: https://github.com/JabRef/jabref/pull/2412

**Comment by tobiasdiez** [comment] 2017-02-02 20:00
This bug should be indeed fixed with the new JavaFX version (http://builds.jabref.org/master/). 
Thus I simply remove the "after-migration-to-javafx" tag and leave the issue closed. Please report back if the problem resurfaces.

**Comment by lenhard** [comment] 2017-02-03 18:02
@AEgit: We are currently trying to optimize our conversion from latex to unicode. We have a promising library for that which needs performance optimization, see: #2465 and https://github.com/tomtung/latex2unicode/issues/1

The author of the library wants to optimize and data for testing would be helpful. Would it be ok for you if I send him your gigantic bibfile, so that he can use it for benchmarking?

**Comment by AEgit** [comment] 2017-02-03 18:24
@lenhard: That would fine for me. Just please tell him to not make public the database.
Thanks again for your great work!
