### ISSUE TITLE
Entry type settings not saved

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#11951] opened 2024-10-13 16:38 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Kernel: 6.8.0-45-generic arch: x86_64 bits: 64   Desktop: Cinnamon v: 6.2.9 Distro: Linux Mint 22 Wilma

### Checked with the latest development build (copy version output from About dialog)

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 6.0--2024-10-13--4644e8d
Linux 6.8.0-45-generic amd64 
Java 21.0.2 
JavaFX 23+29

1.  open preferences
2. select "entry types" and "article" (or any record type)
3. de-select "multiline"
4. save
5. re-open prefs
6. multiline is selected again.  The de-selection wasn't saved.

https://github.com/user-attachments/assets/636a0f78-42d1-45ed-876c-fff018e60fb0

**Comment by ChengPuPu** [comment] 2024-10-13 19:59
Hello, I am interested in this issue, could you assign this to me?

**Comment by HoussemNasri** [comment] 2024-10-13 20:06
Hello @ChengPuPu, the issue is yours. This class serves as a good starting point to tackle the issue:

https://github.com/JabRef/jabref/blob/7d480508632b4619cb662d4b9f5a1078990da827/src/main/java/org/jabref/gui/preferences/PreferenceTabViewModel.java#L6

**Comment by Siedlerchr** [comment] 2024-10-13 21:14
This looks like a duplicate of https://github.com/JabRef/jabref/issues/11897  where @PressJump is working on

**Comment by HoussemNasri** [comment] 2024-10-13 23:14
> This looks like a duplicate of https://github.com/JabRef/jabref/issues/11897 where @PressJump is working on

Confirmed, closing this as duplicate.

**Closed by HoussemNasri** 2024-10-13 23:14 UTC
Labels: preferences, good first issue

**Comment by wujastyk** [comment] 2024-10-13 23:56
My apologies for not finding the earlier report, #11897.  I did do a keyword search before reporting, but I didn't find it.

**Comment by HoussemNasri** [comment] 2024-10-14 00:05
No worries, I updated the issue's title to mention entry types.
