### ISSUE TITLE
Quality / Resolve Bibtex Duplicate keys throws an error

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#4630] opened 2019-02-05 21:25 UTC
Apologies, I just saw that this is the same as #4614

JabRef version 

JabRef 5.0-dev--snapshot--2019-02-04--master--a0c2e04ea
Linux 4.15.0-45-generic amd64 
Java 1.8.0_201

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Select Quality / Resolve Bibtex Duplicate keys 
2. I get the attached popup error window.

![screenshot from 2019-02-05 14-27-40](https://user-images.githubusercontent.com/762246/52305403-41d44c00-2952-11e9-9439-e89134493f91.png)

3. error text appended below.
4. Duplicates are not identified or resolved.

<details>
  <summary>Log File</summary>
  
  ```
java.lang.IllegalStateException: Not on FX application thread; currentThread = AWT-EventQueue-0
	at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:279)
	at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
	at javafx.scene.web.WebEngine.checkThread(WebEngine.java:1243)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:879)
	at javafx.scene.web.WebEngine.<init>(WebEngine.java:868)
	at javafx.scene.web.WebView.<init>(WebView.java:273)
	at org.jabref.gui.PreviewPanel.<init>(PreviewPanel.java:105)
	at org.jabref.gui.bibtexkeypattern.ResolveDuplicateLabelDialog.<init>(ResolveDuplicateLabelDialog.java:61)
	at org.jabref.gui.bibtexkeypattern.SearchFixDuplicateLabels.resolveDuplicates(SearchFixDuplicateLabels.java:46)
	at org.jabref.gui.bibtexkeypattern.SearchFixDuplicateLabels.lambda$null$1002(SearchFixDuplicateLabels.java:39)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

  ```
</details>

**Comment by tobiasdiez** [comment] 2019-02-05 23:22
Duplicate of #4614

**Closed by tobiasdiez** 2019-02-05 23:22 UTC
