### ISSUE TITLE
External URL links are not displayed on mouse click – no way to select the second link

### ISSUE THREAD

**Issue by sauliusg** [JabRef/jabref#8802] opened 2022-05-16 13:34 UTC
### JabRef version

5.6 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Linuxmint-20.1

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

When an entry has both DOI and URL, left-clicking and holding on the "link" icon in the entry list does not activate the drop-down menu. When the mouse button is released, the first Web link in the link list is activated immediately, and there is not way to select another link from the list that appears afterwards. This problem appeared in at least JabRef 5.5 and persist through the 5.7 into the latest commut (main branch, commit c38d18b "Fix notifications that overlap task bar (#8775)").

To reproduce:

1. Start JabRef with the provided minimal library (from the provided `doi-and-url.zip`):
```
~/install/jabref/JabRef-5.7/bin/JabRef ~/doi-and-url.bib &
```
2. Left click the mouse on the "linked-chain" URL link icon. The drop-down list does *not* appear, contrary to what was expected:
![screenshot_2022-05-16_16-23-37](https://user-images.githubusercontent.com/10668420/168604069-029e3d81-3d82-464c-bc09-a629f67f2eff.png)
4. Release the left mouse button. The first link is opened on a browser, and only then the drop-down list appears (but no selection is possible).
[doi-and-url.zip](https://github.com/JabRef/jabref/files/8700417/doi-and-url.zip)

### Appendix

<details>
@Article{Azurmendi2002,
  author    = {Hugo F. Azurmendi and C. Allen Bush},
  journal   = {Journal of the American Chemical Society},
  title     = {Tracking Alignment from the Moment of Inertia Tensor ({TRAMITE}) of Biomolecules in Neutral Dilute Liquid Crystal Solutions},
  year      = {2002},
  month     = {feb},
  number    = {11},
  pages     = {2426--2427},
  volume    = {124},
  doi       = {10.1021/ja017524z},
  file      = {:by-author/A/Azurmendi/2002_Azurmendi_2426.pdf:PDF},
  keywords  = {biophysics; inertia tensor; liquid crystals; PDB; molecule alignment; bioinformatics},
  owner     = {saulius},
  publisher = {American Chemical Society ({ACS})},
  timestamp = {2022.05.16},
  url       = {https://userpages.umbc.edu/~bush/glycogroup/papers/Hugo/jacs124_2426.pdf},
}
</details>

**Comment by ThiloteE** [comment] 2022-05-16 13:40
Duplicate of #8758

**Comment by Rifat951** [comment] 2022-05-17 09:49
Hello,
I think the issue is solved and i am able to switch between doi and url.
![test](https://user-images.githubusercontent.com/31892050/168783106-e32a1dac-5d61-443c-87e1-0c565fd4fcf8.png)

**Comment by Rifat951** [comment] 2022-05-17 09:52
> Hello,
I think i have found a way to solve it. Please have a look at the screenshot. I am able to select url and doi.
![Uploading test.png…]()

**Closed** 2022-05-17 16:58 UTC
Labels: status: duplicate, ui, maintable

**Comment by Siedlerchr** [comment] 2022-05-17 17:06
Thanks to @Rifat951  this issue is now fixed in the latest development version:

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by sauliusg** [comment] 2022-05-18 14:35
> Thanks to @Rifat951 this issue is now fixed in the latest development version:
> 
> We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

Yes, on my computer it now works as expected – both from the `JabRef-5.7-portable_linux.tar.gz` archive [1] and compiled locally from the main branch commit 82aad89.

Thank you very much for the fix!

Ref.:
[1] JabRef-5.7-portable_linux.tar.gz, downloaded from https://builds.jabref.org/main/JabRef-5.7-portable_linux.tar.gz on 2022-05-18T17:34+03:00.
```
saulius@tasmanijos-velnias jabref/ $ ls -l ~/down/JabRef-5.7/JabRef-5.7-portable_linux.tar.gz 
-rw-rw-r-- 1 saulius saulius 191275104 2022-05-18 17:28 /home/saulius/down/JabRef-5.7/JabRef-5.7-portable_linux.tar.gz
saulius@tasmanijos-velnias jabref/ $ sha1sum ~/down/JabRef-5.7/JabRef-5.7-portable_linux.tar.gz 
43eeb9fe81e55387b359e1c9e857d2d350fc0910  /home/saulius/down/JabRef-5.7/JabRef-5.7-portable_linux.tar.gz

**Comment by sauliusg** [comment] 2022-05-18 15:35
UPDATE:

the original bug was fixed, but it seems that a new bug has been introduced: in the patched version it is now impossible to click external links on entries that have only *one* url...

How to reproduce:
1. load any library that has only one external link (URL or DOI) attached to some entry, or remove the 'url =' line from the "doi-and-url.bib" from this entry and load it;
2. left click on the web-link ("chained-link") icon;

The link is not opened in a browser.
