### ISSUE TITLE
Citation Relations should be aware of existing papers

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10414] opened 2023-09-25 19:00 UTC
Open `jabref-authors.bib`.

Click on paper 1.

This references paper 2 at position 3. The paper at 3 should be marked in light green (to indicate that it already exists). Additionally, at button 4, the duplicate check should be called (which then warns about possible duplicates).

![image](https://github.com/JabRef/jabref/assets/1366654/280a0ad7-940e-405c-9b63-36aa5004e477)

In the example, I added the paper resulting in paper marked at 5.

**Comment by vimalJD** [comment] 2023-09-25 21:46
### Is this project is ongoing? Let me know further (DOCS) to contribute on it as "good first issue".

**Comment by ThiloteE** [comment] 2023-09-25 21:57
Yes, this project (JabRef) is still ongoing and this issue is free to take. I will assign you.

**Comment by JannCamilo** [comment] 2023-11-22 08:40
Is this project free? , we are a group of university students and we are interested in this contribution

**Comment by ThiloteE** [comment] 2023-11-22 09:59
@vimalJD are you still on it or have you given up on this?

**Comment by supernoob00** [comment] 2024-02-22 23:02
I would like to work on this. Is it still unresolved? 

Also, I was trying to figure out where the code is that determines the appearance for the entries table. For example, let's say I wanted to change the color of the selected entry to green for whatever reason, where would I go to change that?

![Screenshot from 2024-02-22 17-56-37](https://github.com/JabRef/jabref/assets/119147724/35dd1fb1-8eca-4401-a588-eeb644d9a080)

**Comment by AbdAlRahmanGad** [comment] 2024-02-23 01:35
Hi, can I work on this issue?

**Comment by calixtus** [comment] 2024-02-23 07:49
You will have to add a styleclass to the entry that matches. This can be done by configuring the ViewModelTableCellFactory or ViewModelListCellFactory. The css can be added to base.css

**Comment by calixtus** [comment] 2024-02-23 07:54
In the citations relations tab this would be somewhere here:
https://github.com/JabRef/jabref/blob/14d95025d462bad367118a8b47b694ac14f00e32/src/main/java/org/jabref/gui/entryeditor/citationrelationtab/CitationRelationsTab.java#L194

**Comment by supernoob00** [comment] 2024-02-24 01:56
So, after digging through the code for a while pressing the button (marked as 4 in @koppor 's image in the original post) calls the importEntries method of the ImportHandler class. However, the logic that we want is in the importEntries method of the ImportEntriesViewModel class. I am wondering what the best way to approach this is. Creating a new instance of the ImportEntriesViewModel just to access that method does not seem like a good choice. Should I try to move some of that logic to the ImportHandler class?

**Comment by AbdAlRahmanGad** [comment] 2024-02-26 07:05
@supernoob00 Hi, are still working on the issue?

**Comment by ThiloteE** [comment] 2024-02-26 11:44
Assigned @supernoob00 because of first come, first serve.
@AbdAlRahmanGad Please have a look at other issues that are not yet reserved or assigned. You can see that in the top right corner of GitHub.
![image](https://github.com/JabRef/jabref/assets/73715071/7b6c293c-3592-4722-abf5-2c03256f5bdc)

But yes, if an issue has not been worked on for more than 4 weeks or some months and the assigned person is not responding then you may ask to work on it. Our policy is to usually only assign one student per issue or one group of students from the same course to avoid trouble with grading down the road.

**Comment by koppor** [comment] 2024-02-29 00:46
@supernoob00 Difficult question. Doesn't the dialog know the bibdatabasecontext and thus the entries? There is a duplicate checker. And that also is in use in the import dialog. And can say if an entry exists. We recently worked on that at https://github.com/JabRef/jabref/pull/10914... But you are at a different place in the code. No import, but citation relations. But maybe you get inspirations. Maybe @HoussemNasri can also give hints?

**Comment by HoussemNasri** [comment] 2024-03-02 15:36
Hi @supernoob00, thanks for digging into this,

> Creating a new instance of the ImportEntriesViewModel just to access that method does not seem like a good choice. 

I totally agree that using view models wouldn't be a great idea here. Usually, each UI component has its own view model, but it's possible to use the same one for components that have the same state. Take Android apps, for example. They can run on all sorts of devices, from phones to TVs to watches. You might tweak the design of the UI pages to fit different screen sizes, but you can still keep the state consistent.

> Should I try to move some of that logic to the ImportHandler class, maybe with a new method?

Have you looked into `ImportHandler#importEntriesWithDuplicateCheck`? It is the same method called when you paste an entry into JabRef.

**Comment by ror3d** [comment] 2024-03-13 11:07
From what I see in the code, there might already be something to try to handle this better, in `CitationRelationsTab.java:styleFetchedListView` there's this block that looks like might be trying to show that an entry is already in the library:

```java
 if (entry.isLocal()) {
    Button jumpTo = IconTheme.JabRefIcons.LINK.asButton();
    jumpTo.setTooltip(new Tooltip(Localization.lang("Jump to entry in library")));
    jumpTo.getStyleClass().add("addEntryButton");
    jumpTo.setOnMouseClicked(event -> {
        libraryTab.showAndEdit(entry.entry());
        libraryTab.clearAndSelect(entry.entry());
        citingTask.cancel();
        citedByTask.cancel();
    });
    hContainer.getChildren().addAll(entryNode, separator, jumpTo);
}
```

The problem is, currently in `CitationRelationsTab.java:onSearchForRelationsSucceed` there's this block:

```java
 private void onSearchForRelationsSucceed(BibEntry entry, CheckListView<CitationRelationItem> listView,
                                             Button abortButton, Button refreshButton,
                                             CitationFetcher.SearchType searchType, Button importButton,
                                             ProgressIndicator progress, List<BibEntry> fetchedList,
                                             ObservableList<CitationRelationItem> observableList) {
        hideNodes(abortButton, progress);

        observableList.setAll(fetchedList.stream().map(entr -> new CitationRelationItem(entr, false))
                                         .collect(Collectors.toList()));
```

where the new `CitationRelationItem` is initialized to `isLocal = false` and I don't think there's code to change it to true if the entry is duplicate.

**Comment by HoussemNasri** [comment] 2024-04-06 00:16
Hi @supernoob00, are you still working on this?

**Comment by AbdAlRahmanGad** [comment] 2024-04-09 21:36
@HoussemNasri can I work on this?

**Comment by HoussemNasri** [comment] 2024-04-09 21:40
Sure!

**Closed as completed** 2024-04-12 08:14 UTC
Labels: good first issue
