### ISSUE TITLE
Last display and sort order not maintained when shutting down and reopening JabRef

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4782] opened 2019-03-19 09:44 UTC
JabRef 5.0-dev--snapshot--2019-03-18--master--52696f04b
Windows 7 6.1 amd64 
Java 1.8.0_201

- [+] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I prefer to sort the main table on the timestamp key. However, this sorting is not maintained. Somewhere in the snapshots it worked but was removed for unknown reason. It seems this is the time to ask again for maintaining the sorting upon closing und re-opening Jabref.

1. sort on timestamp
2. close jabref
3. reopend jabref
4. sortorder not maintained

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by Siedlerchr** [comment] 2019-03-19 09:50
Duplicate of #4224  (the original issue, still open)
I had to remove the code applying the sort order at startup because it was caussing massive performance problems at startup when loading a bib file. I have not yet had time to find a better solution.

**Closed by Siedlerchr** 2019-03-19 09:50 UTC
