### ISSUE TITLE
Button presses only work in lower part of hitbox

### ISSUE THREAD

**Issue by Christoph-Neumann-1** [JabRef/jabref#8393] opened 2022-01-05 19:14 UTC
### JabRef version

5.4 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Archlinux, dwm

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Open a fresh installation of jabref
2. Attempt to click any button in the title bar
3. If you click in the upper 3/4 of the button the menu will immediately vanish, making it impossible to select anything

Clicking in the lower quarter of the hitbox makes the pop-up appear normally

**Comment by Siedlerchr** [comment] 2022-01-05 22:19
Duplicate of https://github.com/JabRef/jabref/issues/5867 ?

**Closed by Siedlerchr** 2022-01-05 22:19 UTC
