### ISSUE TITLE
Group Panel always goes down to the bottom

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#10514] opened 2023-10-17 08:41 UTC
### JabRef version

5.10 (latest release)

### Operating system

Windows

### Details on version and operating system

Win 10

### Checked with the latest development build (copy version output from About dialog)

- [ ] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

I am not really sure what triggers the behavior, because it does not happen always
1. Go to view-> Show groups
2. Have manys groups (e.g. 100) that do not fit into the group panel
3. Expected: I can use scrollbar to go to the first group
4. What happends: The Srollbar automatically goes straight down to the last group.
5. (In case this helps: I observed that the group panel works properly again after closing the entry-editor)

A screencast:
https://github.com/JabRef/jabref/assets/8830305/217f5d89-d827-4a68-9468-4026dcf749e0

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Raylyyyy** [comment] 2023-10-17 08:56
Hi all, I am new to this repo, I can investigate and working on this issue. Please assign this issue to me.

**Comment by koppor** [comment] 2023-10-17 09:03
@teertinker Please try the latest build <https://builds.jabref.org/> and try if the issue persists.

**Comment by koppor** [comment] 2023-10-17 09:03
@Raylyyyy This is not a good first issue. Please try for something else.

**Comment by ThiloteE** [comment] 2023-10-17 09:08
@Raylyyyy if I may ask, how did you find this issue and JabRef?
We collect [good first issues](https://github.com/orgs/JabRef/projects/5) at our projects page.

**Comment by Raylyyyy** [comment] 2023-10-17 09:10
Ah, I am just constantly browsing issues and just I saw this pop up. My friend introduced me to this repo.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AEgit** [comment] 2023-10-22 11:28
JabRef 5.12--2023-10-22--b1abe02
Windows 10 10.0 amd64 
Java 21.0.1 
JavaFX 20.0.2+3

I cannot reproduce this issue with the current developer version. Maybe this problem has been solved with the different changes applied to the groups panel (?).

**Comment by ThiloteE** [comment] 2023-10-22 11:47
Let's close it then. Feel free to reopen, if you can still reproduce.

**Closed by ThiloteE** 2023-10-22 11:47 UTC
