### ISSUE TITLE
uninstalling JabRef leaves traces in the Win registry

### ISSUE THREAD

**Issue by donovaly** [JabRef/jabref#1490] opened 2016-06-10 01:34 UTC
JabRef adds now the registry entries 
HKCU\Software\JabRef
and
HKLM\Software\JabRef
as I requested in #1362

However, when uninstalling JabRef 3.4 these registry paths were not removed.

**Comment by stefan-kolb** [comment] 2016-06-10 09:06
Thank you for your report :+1:
This should be fixed in `clean-regedit`. Please try the latest build from http://builds.jabref.org/clean-regedit.

**Comment by simonharrer** [comment] 2016-06-13 15:58
Does the fix solves your issue? @donovaly

**Comment by donovaly** [comment] 2016-06-13 22:42
> Please try the latest build from http://builds.jabref.org/clean-regedit.

Thanks Stefan. I tested this version and this bug is fixed. BUT there is a regression: when installing as admin for all users of the PC, the registry entry
HKLM\Software\JabRef
is no longer there. But this is what I need, see my initial post.

**Comment by stefan-kolb** [comment] 2016-06-14 13:28
@donovaly Hm, this is not really a regression bug, but #1362 never really worked as I expected it to work. Maybe you can help me to define what is actually the expected outcome:

1. A user may run the installer as Administrator by right-clicking and elevating the whole installer application.
-> Currently, the script writes a key inside HKLM\Software\JabRef which is what I expect it to do.

2. A user just elevates the installer helper process by granting the rights after opening the installer and accepting the Windows dialog that it may alter the system.
-> Currently, the script only writes a key inside HKCU\Software\JabRef which I don't expect it to do. In the previous PR you did not mention that this is not the intended behavior, maybe you just call the installer as in 1.? The problem here is, I don't know why the system behaves like that, as it should have full admin rights right now. Surprisingly, the same configuration works well for the deletion of the registry keys but not the addition...Maybe it's even an install4J bug?

3. If we cannot elevate the installer process or reject the windows dialog it should write to HKCU which it actually does imho.

**Comment by donovaly** [comment] 2016-06-14 23:02
Point 1. is correct as it should be.

But if the user has Win admin privileges there is no need to elevate anything. In this case there should also be an entry HKLM\Software\JabRef. That this is not the case is what I miss. (to write in this case also HKCU\Software\JabRef is optional but in my opinion not necessary/superfluous)

If the user has no admin privileges and the installer is not run elevated there can and must only be HKCU\Software\JabRef.

**Comment by stefan-kolb** [comment] 2016-06-15 06:23
The problem is that the installer does not behave like it is configured...

**Comment by stefan-kolb** [comment] 2016-07-13 14:12
@donovaly This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Closed** 2016-07-13 14:12 UTC
Labels: bug, build-system
