### ISSUE TITLE
Automatically set file links

### ISSUE THREAD

**Issue by hudcap** [JabRef/jabref#170] opened 2015-09-17 19:06 UTC
When I click "Automatically set file links," the status window it opens no longer closes automatically after it sets the links.
This seems to have surfaced in beta4 - I did not have this issue in beta3.

**Comment by matthiasgeiger** [comment] 2015-09-17 20:37
Duplicate of #103 - should be fixed since yesterday :wink:

Thanks for the report!

**Closed** 2015-09-21 21:38 UTC
Labels: duplicate
