### ISSUE TITLE
Clicking on .bib files won't open them in JabRef

### ISSUE THREAD

**Issue by thanaset** [JabRef/jabref#6540] opened 2020-05-27 15:49 UTC
JabRef version 5.0 on Windows 10

Opening .bib files from within JabRef is fine but clicking on a .bib file in Windows Explorer results in a blank page on JabRef.

1. Double click on a .bib file icon.

**Comment by Siedlerchr** [comment] 2020-05-27 16:28
Duplicate of #6487 
Could you also add your findings there?

**Closed by Siedlerchr** 2020-05-27 16:28 UTC
