### ISSUE TITLE
JabRef suddenly warns the file has changed on disk and requires review of changes (dropbox)

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#4143] opened 2018-06-19 16:31 UTC
This happened with version 4.3.1 on a Linux system: I added a few dozen new entries, saving the database after each new added entry, when suddenly the GUI told me that the database has changed on disk and forced me to review the changes, showing me the changes I have just made myself!
I am pretty sure no other process has actually updated the database on disk. 
I know that there is nothing to review and I do not care if for some reasons the file modification date is not what jabref expects, I just want it to save and override the file on disk, but Jabref apparentlly does not allow that. This is very annoying.
So what I have to do is kill/abort jabref (losing the entry I was in the process of adding) and start it again.

**Comment by johann-petrak** [comment] 2018-06-19 16:37
In that situation, when the "Review changes" button is shown in the left pane of the GUI, clicking the "x" icon to close the program brings up a dialog "Please wait..." / "Waiting for save operation to finish" which is then shown forever. 
The only way to exit the program is to kill it.

**Comment by Siedlerchr** [comment] 2018-06-20 23:11
DO you have autosave feature enabled? That could be causing issues in your case

**Comment by johann-petrak** [comment] 2018-06-21 09:34
If you mean the option "Autosave local libraries" in Options - File, then no, this was not checked.

However, I just noticed that there is a setting that may have made this a bit less frustrating: under "Library properties" there is the option "Refuse to save the library before external changes have been reviewed" which appears to have been set by default. Unsetting this will at least let me simply save the library even when JabRef incorrectly thinks for some reason it has been modified on the disk.

**Comment by johann-petrak** [comment] 2018-06-21 17:02
OK, turns out enabling the saving is not working as expected either: JabRef now allows the save button to get pressed, but after this the GUI becomes unresponsive and I still have to kill the program and start over and it turns out the latest version of the database was not saved.
This makes JabRef completely unusable for me I am going to downgrade to a previous version.

**Comment by Siedlerchr** [comment] 2018-06-21 21:43
HI, sorry to hear this. 
 Could you please out if the issue is resolved in the latest master?
https://builds.jabref.org/master 
Please remember to make a backup of your library before trying-out this version.

**Comment by burrbull** [comment] 2018-06-25 03:13
I confirm an error. It is reproduced since version 4.1 to current master.

**Comment by bernhard-kleine** [comment] 2018-06-25 16:39
This is nothing special to Linux, I have Windows 7 and the same issues which I have ignored because it is not critical. And yes, I have the autosave feature enabled.

**Comment by ilippert** [comment] 2018-07-05 16:55
I experience the same problem at JabRef 5.0-dev--snapshot--2018-07-02--master--aed7712bc
Linux 4.17.3-200.fc28.x86_64 amd64 
Java 1.8.0_172

**Comment by bernhard-kleine** [comment] 2018-07-14 10:12
With the screenshot from yesterday, the problem is still there.

**Comment by bernhard-kleine** [comment] 2018-07-30 19:31
I am sorry to bring this up again. There was a reaction to the waiting for feedback already some time ago. At least remove the label "waiting for feedback", please.

**Comment by wujastyk** [comment] 2018-08-28 17:37
I confirm the error in 4.3.1 and in the current development snapshot.  It's very annoying when one is trying to work seriously and sometimes leads to data loss.  

Screenshot from development snapshot:
  

![screenshot from 2018-08-26 11-36-12](https://user-images.githubusercontent.com/762246/44739970-73e5a600-aab6-11e8-9087-d354153d2b40.png)


Screenshots from 4.3.1:

![screenshot from 2018-08-26 12-31-06](https://user-images.githubusercontent.com/762246/44740016-924ba180-aab6-11e8-9209-51e8a5f38190.png)
![screenshot from 2018-08-12 22-29-07](https://user-images.githubusercontent.com/762246/44739935-64665d00-aab6-11e8-9126-f899cb977965.png)

![screenshot from 2018-08-12 22-00-55](https://user-images.githubusercontent.com/762246/44739925-5adcf500-aab6-11e8-82f5-2f6591677720.png)

**Comment by Siedlerchr** [comment] 2018-08-28 18:00
As you seem to encounter this more often, could you please add some information and or upload your preferences? (you can export them). 
The problem is that this is hard to reproduce and therefore to find the root cause

**Comment by wujastyk** [comment] 2018-08-28 18:16
I have no idea what activities precede this "file updated externally" message.  I have tried to think of trigger situations, and I can't.  I am editing a record: that's a common feature.  Otherwise <shrug>.

I do have Dropbox running on all my machines.  So Dropbox is periodically copying my bib files to the cloud.  I've often wondered if that's the issue.  It shouldn't be, but....


Here are my preferences (I have in the past had "autosave" turned on; I just turned it off today):

[jabref431-preferences.txt](https://github.com/JabRef/jabref/files/2329334/jabref431-preferences.txt)

**Comment by Siedlerchr** [comment] 2018-08-28 18:30
Dropbox could indeed be an issue. If I remember correctly, saving causes JabRef to make a temporary copy of the db and then replacing the original file. So it could be that during that copying process dropbox kicks in with synchronizing the changes before the copy finished which would explain the review changes messages 

The save logic is still a relict of old times when saving was unreliable. As far as I know @stefan-kolb  already took a look at that.  Maybe he can shed some light on that issue here

**Comment by wujastyk** [comment] 2018-08-28 18:41
Does that mean that turning off "autosave" should prevent the problem?
johann-petrak reported having autosave off, but still encountering the
problem.

**Comment by tobiasdiez** [comment] 2018-09-13 19:37
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed by tobiasdiez** 2018-09-13 19:37 UTC
Labels: bug, export / save

**Comment by johann-petrak** [comment] 2019-06-28 12:36
I regularly update to the latest development version and I have not seen this happening for a while now. 
Sorry, I since this was an intermittent problem I cannot tell if it actually was fixed or I was just lucky and if it was fixed, since when ;)

**Comment by ilippert** [comment] 2019-06-28 12:53
yes, still/again present in current snap version - I am reporting this as a new issue
