### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by nhamilton1980** [JabRef/jabref#2553] opened 2017-02-16 04:24 UTC
I have recently upgraded Jabref. I am not sure what my previous version was, but it was the version prior to the major revamp in the GUI appearance (different iconset etc...)

Anyway, now, there seems to be a major performance issue when opening pdf files, when a pdf file is associated with the entry. 

Also, similarly a performance issue is present when I click 'get fulltext', where a search is conducted for a XYZ.pdf file, where XYZ is the same as the bibtexkey.

Both of these functions used to respond almost instantaneously, and now they do not, taking up to 10 seconds to execute.

Opening DOI / URL links still performs as expected (ie instant response in browser).

My database is quite large, 1400+ records. The same performance hindrance is not witnessed for a database containing only few records, leading me to conclude that there is some O(N+) operation happening, based on the size of the database.

I am happy to revert, if someone could let me know what the last version was prior to the most recent major GUI upgrade, I am more concerned with performance rather than pretty modern icons.

**Comment by koppor** [comment] 2017-02-16 08:42
Thank you for your report. We are certainly not focusing on modernizing the UI, but on fixing issues. See our CHANGELOG at https://github.com/JabRef/jabref/blob/master/CHANGELOG.md. The update of the icons happend from 2.x to 3.x.

It would be nice if you tried out some versions in the 3.x series.

Since you seem to have to knowledge in analyzing, could you perform a git bisect using the repository and find out the commit from which it got slower?

**Comment by nhamilton1980** [comment] 2017-02-16 08:51
OK, I'll try and pinpoint the version that causes the issue. 

The version I am currently using is 3.8.1

**Comment by matthiasgeiger** [comment] 2017-02-16 08:59
Just a short question: How do you open the linked PDF?

**Comment by nhamilton1980** [comment] 2017-02-16 09:04
Ah usually by clicking on the icon in the grid.

**Comment by matthiasgeiger** [comment] 2017-02-16 09:06
Okay... this still opens the pdf instantaneously for me...

**Comment by nhamilton1980** [comment] 2017-02-16 09:08
The version I installed that is problematic, I installed from .dmg for mac. I am presently trying all the .jar files, and they seem to be fine so far, halfway through 3.x versions. So perhaps the issue is with the mac compiler or whatever you use to produce dmg files.

**Comment by matthiasgeiger** [comment] 2017-02-16 09:21
Is the 3.8.2 jar file also fine?

**Comment by nhamilton1980** [comment] 2017-02-16 09:23
No it is not. Just tried. 3.8.2 and 3.8.1 show the problem. I am downloading and working back.

**Comment by lenhard** [comment] 2017-02-16 09:28
We made changes to the executable for OSX yesterday as part of fixing  #2470. Could you please check if the current development version available at http://builds.jabref.org/master/ changes anything?

**Comment by nhamilton1980** [comment] 2017-02-16 09:37
Ok so I have downloaded and tried every version (.jar) from 3.X (and also late 2.X), and I have isolated and conclude the following:

Everything up to, and including 3.3, pdf open instantly.
Everything from 3.4 and beyond show the problem.

So I guess it doesn't take a rocket scientist to determine that some change between 3.3 and 3.4 is the culprit.

Do you still need me to check the latest OSX, I am personally happy to revert to 3.3 for the moment.

**Comment by nhamilton1980** [comment] 2017-02-16 09:45
3.3 installed from .dmg works fine too.

**Comment by stefan-kolb** [comment] 2017-02-16 10:42
We checked the diff between v3.3 and 3.4 and cannot see any changes that might impact this.
@chochreiner Can you reproduce this? If not, unfortunately we cannot really do anything about this for now.

**Comment by AEgit** [comment] 2017-02-16 17:10
It either has to do with the setup of nhamilton1980 or with the OSX build. I'm using a database that is an order of magnitude larger than that of nhamilton and get instant response on both Windows and Linux.

**Comment by stefan-kolb** [comment] 2017-02-16 22:13
Hm, we didn't change anything in the OSX build. @nhamilton1980 Did you explicitely set an application in external file types for PDF?

**Comment by nhamilton1980** [comment] 2017-02-16 22:20
No I didn't. Right now, If I use the 3.3 version (Jar or .dmg build), everything works fine, very responsive. If I use the 3.4 version, there is a huge lag. I haven't changed any of the default settings or external applications, the file opens with Adobe Reader, which is the default application on my system for mimetype 'application/pdf'.

**Comment by nhamilton1980** [comment] 2017-02-16 22:28
Guys I think you can close this. I have just tried 3.8.2 again, and it is now performing as expected. Very Weird.

**Comment by stefan-kolb** [comment] 2017-02-16 22:37
👍

**Comment by nhamilton1980** [comment] 2017-02-17 10:09
Sorry to continue with this. I noticed that when I came home, the lag in opening pdf files was present again. 

Where I am staying, the internet has a very poor ping, sometimes being completely painful to use, particularly during wet weather.

Earlier today, when I suggested this issue should be closed, I was at the university which has a lightning fast connection.

This made me think that perhaps the internet has something to do with this issue.

So now, at home with my pathetic internet connection, if I turn the internet off, the file opens instantly, but if the internet is connected, the file experiences the lag. I am wondering if some call is being made to the internet, which is creating a bottleneck? 

I have tried using wireshark, there is quite a bit of activity before the file opens, but I am not sure how to isolate anything meaningful, or whether this is a Jabref issue, or whether it is adobe or something else.

**Comment by AEgit** [comment] 2017-02-17 10:13
Have you tried using a different PDF viewer? That could at least help in deciphering whether it is directly related to the Adobe or not.

**Comment by nhamilton1980** [comment] 2017-02-17 10:17
Ah, good point. I just tried using preview, and there is no delay with internet off, and a few second delay when internet is on.

**Comment by AEgit** [comment] 2017-02-17 10:19
Hmmm, ok, so if you get the same delay as with the Adobe Reader it is probably not related to Adobe. Then it is either the internals of JabRef causing the issue or something related to MacOS X itself.

**Comment by nhamilton1980** [comment] 2017-02-17 10:21
Well. If I try to open a pdf file directly from the filesystem (terminal or in Finder), there is no delay at all. How does Jabref instruct the file to be opened?

**Comment by AEgit** [comment] 2017-02-17 10:24
I'm afraid, I do not belong to the JabRef development team, I'm just someone who uses JabRef quite extensively ^^. So I can't answer your question, but I guess current evidence puts it indeed as if JabRef is causing the issue. I suggest to reopen the issue.

**Comment by nhamilton1980** [comment] 2017-02-17 10:29
I don't have the permissions to re-open.

**Comment by tobiasdiez** [comment] 2017-02-17 12:08
If I understand [our code correctly](https://github.com/JabRef/jabref/blob/ebbeb1d249edf7134abf92d24c2031ae54d19881/src/main/java/org/jabref/gui/desktop/os/OSX.java#L28), then it just invokes `/usr/bin/open <filepath>`.
Could you please try and run this command from the command line and see if the delay occurs there too. Thanks!

**Comment by nhamilton1980** [comment] 2017-02-17 12:11
It doesn't. I use that command ALL the time on a daily basis when looking at pdf files.

**Comment by stefan-kolb** [comment] 2017-02-17 16:18
I could not identify any web calls inside the code. Also checked it inside a car with limited WIFI. 😞

**Comment by nhamilton1980** [comment] 2017-02-17 23:46
FML. Ok. Sorry for wasting everyones time...

**Comment by stefan-kolb** [comment] 2017-02-19 11:13
Sorry for not being able to track this down.

**Comment by stefan-kolb** [comment] 2017-02-20 14:25
@JabRef/developers Anyone has an idea here? Otherwise we need to close this if we don't find any new information.

**Comment by lenhard** [comment] 2017-02-20 14:55
I vote for closing. 

Although I have tackled a few performance-related issues before, I simply cannot do this for OSX. We need a core contributor who uses this operating system, otherwise there is hardly a chance.

**Comment by chochreiner** [comment] 2017-02-20 15:07
I've tried to reproduce this problem, but I could not reproduce the problem with different network speeds.

**Closed** 2017-02-20 15:08 UTC
Labels: osx, waiting-for-feedback
