### ISSUE TITLE
Add dropdown list to autocompletion - Feature request

### ISSUE THREAD

**Issue by ajbelle** [JabRef/jabref#885] opened 2016-02-28 14:45 UTC
* JabRef version (available in the About box): 3.0
* Operation system and version: Win7
* Steps to reproduce:   Attempt to use autocompletion in allocating keywords, but only one of similar words is accessible.

eg: Water waterjet waterplane  and it fails completely with hypenations eg: Wall-bounded Wall-pressure Wall-shear

Could the down arrow  or a dropdown list be added to autocompletion select between word offering. The functionality suggested exists in the LyX source code with the settings accessible in LyX|Tools>Preferences>[Editing-Input Completion].

See [thread](https://sourceforge.net/p/jabref/discussion/318825/thread/cfceb67c/?limit=25) for the origin of this issue.

**Comment by tobiasdiez** [comment] 2016-02-28 15:12
I think this is a duplicate of #497.

**Comment by ajbelle** [comment] 2016-03-01 04:22
Yes, sorry it seems so:my searching was poor. [#497](https://github.com/JabRef/jabref/issues/497) seems a better technical explanation, but the above notes a good reason for implementing it.

**Closed** 2016-03-01 11:14 UTC
Labels: feature

**Comment by simonharrer** [comment] 2016-03-01 12:52
Hm, now both, this and the 497 issue are closed. Was this the intention @tobiasdiez ?

**Comment by tobiasdiez** [comment] 2016-03-01 13:14
#497 was closed because it was marked as "after-migration-to-fx". I now removed this tag and reopend the other issue, based on our discussion via skype.
