### ISSUE TITLE
JabRef "File" pane not looking in correct directory when BIB location is primary directory

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2985] opened 2017-07-09 07:10 UTC
When my bib location is set as the primary file directory, the new auto paper finder doesn't find pdf files, and clicking the "+" icon (General tab, next to "File") sends me to a random directory, not the primary file directory.

*Details*

1.  I have put into my "papers" directory a pdf with the same name as a new entry's bibtex key.  "papers" is a directory immediately below where my .bib file is.  
2. In File->Library properties->General file directory, I have entered "papers".  
3. In Options->Preferences->File, I have clicked"Use the BIB file location as primary file directory."

*Version*

JabRef 4.0.0-dev--snapshot--2017-07-07--master--eaf53f75d
Windows 7 6.1 amd64 
Java 1.8.0_131

**Comment by koppor** [comment] 2017-07-11 11:08
Documentation for the feature: http://help.jabref.org/en/FileLinks - Maybe needed to be adapted?

**Comment by notuntoward** [comment] 2017-07-18 06:23
I'm not sure what's being proposed so I thought I'd try to clarify a bit.

I'm using the primary file directory feature as a way to avoid a bibtex file that contains a full, machine-specific path the files directory -- a full path doesn't work when the bibtex file is checked out on different machines or by different users  (#2930).  Specifying a primary file directory does get around that problem but it causes the one I'm mentioning in this issue.  

So, as the beta stands right now, JabRef 4.0 is considerably more annoying to use (in this regard) than JabRef 3.x.  

It doesn't seem to me that there's a documentation fix for this.  But maybe there's something I don't understand.

**Comment by Siedlerchr** [comment] 2017-08-23 13:45
I think there are some things to clarify:
In main file directory you can't enter a relative directory. This is not possible, because JabRef does not know to which file/directory the relative path should be calculated.

Bib file location as main file directory **precedes** all other values, no matter what you entered elsewhere. And it works correctly, even with bib files in different folders.
Relative file directories obviously only work in the library properties fo a bib file, e.g. ` a.bib -> Library properties -> General file directory ->  papers`

I have two bib files: `a.bib , b.bib`
`a.bib `lies on` C:\a.bib ` and `b.bib` lies on` X:\b.bib`
And when I click on the + icon in the general Tab of file a.bib, it is correctly opened in the directory `C:\papers `(assuming papers is a directory in the same folder where a.bib resides)

To conclude: It works all as expected and I don't see any problem here - except from adapting the documentation a bit

**Comment by koppor** [comment] 2017-09-04 07:41
I updated http://help.jabref.org/en/FileLinks today. Maybe, it helps?

**Comment by notuntoward** [comment] 2017-09-10 08:50
Yes, the explanation does help.  

One thing that still doesn't work, though, is the automatic file link setter -- if I have an entry with the Bibtexkey 'bob' and if there is a file ./papers/bob.pdf, then the pdf is not found, either after hitting F7 or after clicking on the "Automatically set file links..." icon on the left side of the General tab.

**Comment by notuntoward** [comment] 2017-10-27 07:42
The problem is still there: #3346

**Comment by Siedlerchr** [comment] 2017-10-28 20:55
This is not a bug. The settings "Use the BIB file location as primary file directory." overrides all other directory settings and will be used as directory for opening the new file dialog.
If you uncheck that option it works as expected. 
Regarding AutoSetFile LInks, that is handled in the other issue, so I close this

**Closed by Siedlerchr** 2017-10-28 20:55 UTC
Labels: bug, entry-editor
