### ISSUE TITLE
Unecessary library modification notifications when removing a group

### ISSUE THREAD

**Issue by thiagocferr** [JabRef/jabref#9345] opened 2022-11-03 06:48 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Manjaro with GNOME 42.4, JabRef 5.8 (portable linux) and main branch, commit 7367ee5

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a group;
2. Remove it by right-clicking it and selecting `Remove group`, with or without entries on it;
3. Save library, and a popup should appear, with change entries `Metadata changed` and `Modified groups tree`.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment] 2023-04-15 19:03
I cannot reproduce this issue anylonger

Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2023-04-15 19:03 UTC
Labels: groups
