### ISSUE TITLE
Adding keywords for new entries only possible when clicking on the top left corner of the field

### ISSUE THREAD

**Issue by teertinker** [JabRef/jabref#11177] opened 2024-04-10 07:46 UTC
### JabRef version

5.13 (latest release)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

JabRef 5.13--2024-04-01--6bdcf63
Linux 6.5.0-26-generic amd64 
Java 21.0.2 
JavaFX 22+30

1. Import or create a new entry without keywords
2. Try to enter a keyword
3. nothing happens

In contrast for entries with preexisting Keywords, I can add a new keyword without problems.

[May be of relevance: I have a wordlist saved for keywords (selector_keywords)]

My current workaround: Enter a new line for keywords directly in the bibtex of the entry with one new keyword.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Siedlerchr** [comment] 2024-04-10 08:25
Yeah it's kind of disabled until you enter something in another field

**Comment by teertinker** [comment] 2024-04-10 09:16
Thank you for your helpful comment. I realised that the behavior is the same for other fields. For example "crossref" also seems to be locked until i enter something in another field. 

Hopefully this helps to narrow down the source of the problem.

**Comment by koppor** [comment] 2024-04-10 12:47
@LoayGhreeb maybe you can have a look?

**Comment by LoayGhreeb** [comment] 2024-04-10 13:43
> maybe you can have a look?

I can't reproduce the issue I tested it on windows 11.

1. create a new library
2. add a new entry
3. add a keyword, and it works as expected
4. also tried with and without the content selectors, and with and without auto-completion

https://github.com/JabRef/jabref/assets/52158423/5438d946-e385-448d-a6d6-6f89cbf62fb7

**Comment by teertinker** [comment] 2024-04-10 17:12
Hi there, 
I have been testing 5.13 on my Windows machine and have been able to narrow down the issue. It seems that this is not a real bug as it first appeared. 
It seems to be a "user error": I can only fill in the keywords field if I click on the very first line of the field. By accident, I have sometimes clicked somewhere in the keywords field (as it is multiline) and thought the field was locked. This happens on both my Linux and Windows machines. Also, unlike other fields, the keywords field (and crossref) does not get a coloured frame when it is activated.
This does not seem to be a real bug, but it may irritate other users. 

The same behaviour can be seen in the crossref field.

**Comment by LoayGhreeb** [comment] 2024-04-10 17:16
Refs https://github.com/JabRef/jabref/pull/10910#issuecomment-1977525490

**Comment by Siedlerchr** [comment] 2024-04-10 17:20
Yeah, this still feels weird. By contrast, if I click on the comment field somewhere in the middle, the first line will be focused 
Maybe we can report it upstream to the gemsfx repo

**Comment by calixtus** [comment] 2024-04-10 17:53
I will take a look. Im not sure if this is about gemsfx but our buggy entry editor. I believe the inner control does not fit the size of the outer field editor border. I believe we had the issue discussed before. I will look into it.

**Comment by LoayGhreeb** [comment] 2024-04-10 18:31
I think yes, maybe it's not related to GemsFx, because when I tried what you suggested in https://github.com/JabRef/jabref/pull/10910#issuecomment-1977601858 it works fine, but there was an issue with binding. Will give it a try.

**Comment by LoayGhreeb** [comment] 2024-04-11 04:53
I tried the GemsFx demo and can confirm that the issue is not related to them.
Here is how it looks in their demo:

![image](https://github.com/JabRef/jabref/assets/52158423/a6842e5d-bbc6-40ea-93ef-0862c4a69a70)

**Comment by ryan-carpenter** [comment] 2024-05-02 00:48
> Yeah it's kind of disabled until you enter something in another field

Pressing `Tab` or `Shift + Tab` allows me to move ahead or back to the 'disabled' Keywords field. I need to enter the other field first, as you mentioned, but do not need to enter data in the other field to 'enable' Keywords. It's great that you have enhanced the keyword functionality. :1st_place_medal:

**Comment by tobiasdiez** [comment] 2024-09-18 10:10
This is highly irritating and made me believe the keywords field didn't accepted any input. Would be nice if this could be addressed in the next release.

Might be relatively easy to fix by adding a click listener (to either the field or the whole entry editor) that then correctly switches to edit mode/calls "focus".

**Closed** 2024-09-20 15:52 UTC
Labels: bug, ui, keywords, entry-editor
