### ISSUE TITLE
Jabref 4.x does not show recent changes or new entries, needs reload

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#2974] opened 2017-07-06 09:46 UTC
How to reproduce:

1. Select a group with N members
2. add a new entry (for example via doi import)
3. the **group shows N+1 members**, but does **not list the new entry**.
4. open another group, then open the old group again and the entry is displayed.

```
JabRef 4.0.0-dev--snapshot--2017-07-03--master--6897b10fb
Linux 4.4.0-78-generic amd64 
Java 1.8.0_131
```

**Comment by lenhard** [comment] 2017-07-07 08:45
possibly related: #2787

**Comment by AEgit** [comment] 2017-07-10 09:32
Maybe a duplicate of this (?):
https://github.com/JabRef/jabref/issues/1903

**Comment by lenhard** [comment] 2017-07-10 10:35
@AEgit Indeed, I agree. Thanks for pointing this out! It seems that the problem well before the rewrite of the grouping code, but was also not solved during the rewrite.

I'll close this one as a duplicate, but I'll leave a comment at the older issue that confirms that this is not solved even in the newer versions.

**Closed by lenhard** 2017-07-10 10:35 UTC
Labels: bug, groups, maintable
