### ISSUE TITLE
Respect localization for main directory (e.g., `~/Dokkumente`)

### ISSUE THREAD

**Issue by starsareintherose** [JabRef/jabref#8010] opened 2021-08-21 11:06 UTC
### JabRef version

5.3 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

ArchLinux linux-lts

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

~1. Open the `preference~
~2. change any option~
~3. bug shows~
~4. ![2021-08-21 18-13-16屏幕截图](https://user-images.githubusercontent.com/37733075/130318628-c0d5db47-1861-4f5d~b7fd-cd78e2dbcd76.png)~

See https://github.com/JabRef/jabref/issues/8010#issuecomment-1531526339

### Appendix

...
<details>
<summary>Log File</summary>
```
Paste an excerpt of your log file here
```
</details>

**Comment by Siedlerchr** [comment] 2021-08-21 17:48
As the error mesage says you need to check the main file directory in the preferences. It has to be a valid absolute path

**Comment by starsareintherose** [comment] 2021-08-21 18:31
I solved it by export my reference and set the reference as default and then put the old reference into it. It works, that's so strange.

**Comment by kvnptl** [comment] 2022-12-29 07:07
Facing the same issue on version 5.8.
@Siedlerchr could you please mention where to set the main file directory in the preference?

**Comment by Siedlerchr** [comment] 2022-12-29 08:58
@kvnptl  Hi, the setting for the main file directory is now under Linked Files 
<img width="717" alt="grafik" src="https://user-images.githubusercontent.com/320228/209927975-48c2005f-9816-48b1-b842-a1252ed58734.png">

**Comment by kvnptl** [comment] 2022-12-29 09:11
Thanks. It was pointing to `snap/jabref/2209/Documents`, which was not there. Now, I changed it, and the error message is gone.

**Comment by HoussemNasri** [comment] 2023-02-17 16:14
I think this should stay open, the error message is misleading.

**Comment by Siedlerchr** [comment] 2023-02-18 19:35
It seems like the issue here is that the native default fallback directory is invalid inside a snap

**Comment by HoussemNasri** [comment] 2023-02-18 19:44
This is the path I got by default "/home/houssem/snap/jabref/2265/Documents". The problem here is that "Documents" folder doesn't exist under "2265".
## Environnement
snap    2.58.2
snapd   2.58.2
series  16
ubuntu  22.04
kernel  5.15.0-52-generic

**Comment by Siedlerchr** [comment] 2023-02-18 20:01
Yes, this is correct. The home dir is set via this property. 

https://github.com/JabRef/jabref/blob/98c9cbb85bfb2714d767769a7707f46f906f16ac/snap/snapcraft.yaml#LL54C37-L54C37

And the directory is coming from here:
https://github.com/JabRef/jabref/blob/98c9cbb85bfb2714d767769a7707f46f906f16ac/src/main/java/org/jabref/gui/desktop/os/Linux.java#L173 

So I think we need to check if the path contains "snap" and then either create the subdirectory (don't know if possible) or just return "home" or set it to another env var: https://snapcraft.io/docs/environment-variables

Can you attach files outside the snap directory?

**Comment by HoussemNasri** [comment] 2023-02-18 20:14
![image](https://user-images.githubusercontent.com/21198231/219890359-3794b7a9-8f00-4b01-abef-70be57bd78f6.png)

**Comment by koppor** [comment] 2023-05-02 22:30
It is because, we hard-coded "Documents" at [Linux.java](https://github.com/jabref/jabref/blob/5bc359fa5f572c40ac3f05551e5eecd8126845d8/src/main/java/org/jabref/gui/desktop/os/Linux.java#L176-L176)

    System.getProperty("user.home") + "/Documents")

This code was introduced in https://github.com/JabRef/jabref/pull/9222.

Does your XDG environment have the environement variable `XDG_DOCUMENTS_DIR` set?

I tried to craft a fix at https://github.com/JabRef/jabref/pull/9835

Can you try the portable edition from https://github.com/JabRef/jabref/actions/runs/4866174963?

(I could not upload it to builds.jabref.org - hope the link above works)

**Comment by calixtus** [comment] 2023-05-03 13:33
> It is because, we hard-coded "Documents" at [Linux.java](https://github.com/jabref/jabref/blob/5bc359fa5f572c40ac3f05551e5eecd8126845d8/src/main/java/org/jabref/gui/desktop/os/Linux.java#L176-L176)
> 
> ```
> System.getProperty("user.home") + "/Documents")
> ```

The hardcoded variant is just the fallback option, if no XDG_DOCUMENTS_DIR can be found. 

```
return Path.of(Objects.requireNonNullElse(
                System.getenv("XDG_DOCUMENTS_DIR"),
                System.getProperty("user.home") + "/Documents")
        );
```

So this could be a bigger problem with resolving enviroment variables.
Maybe we can introduce some test cases?

**Comment by Siedlerchr** [comment] 2023-05-03 14:14
We need to be aware that in snaps this can look different or at least the vars are mapped to internal dirs 
https://snapcraft.io/docs/environment-variables

**Comment by dermalikmann** [comment] 2023-05-03 14:29
Sorry for the delayed response

@calixtus
a) no, i use the AUR version (source, not -bin)
b) my ~/.config/user-dirs.dir is fine, i already checked it. there might be something else tho, see blow
c) see even further below

in regards to the ENV:

```
$ env |grep XDG | cut -d'=' -f1
XDG_SESSION_TYPE
XDG_RUNTIME_DIR
XDG_DATA_DIRS
XDG_SESSION_DESKTOP
XDG_CURRENT_DESKTOP
XDG_SESSION_CLASS
XDG_MENU_PREFIX
```
it seems that the user-dirs dont get sourced by my default env. AFAIK, this usually should happen through /etc/profile(.d/), but it seems that it in fact does not. @calixtus if you are running arch too, could you check if you have any script in there that access the user dirs conf?

\\

@koppor I have problems clean up my JabRef configuration 🤔 I deleted ~/.local/share/JabRef and ~/.local/share/jabref, bun when i run the portable version, it still loads my configuration. Am i missing something?

**Comment by koppor** [comment] 2023-05-03 15:18
@HoussemNasri I think, the title changed wrong to "Refer to the Documents directory by Environnement variable e.g., XDG_DOCUMENTS_DIR instead of hardcoding it", because this is the way it is currently implemented:

https://github.com/JabRef/jabref/blob/5bc359fa5f572c40ac3f05551e5eecd8126845d8/src/main/java/org/jabref/gui/desktop/os/Linux.java#L175

See also https://github.com/JabRef/jabref/pull/9835#issuecomment-1532539677 😅

The issue is that this variable is sometimes empty. We are investigating why this could be the case.

Moreover, we should check on non-English macOS if everything works. Not sure if we will manage that...

**Comment by HoussemNasri** [comment] 2023-05-03 15:34
@koppor Hmm I see, feel free to change it to something more precise.

**Comment by calixtus** [comment] 2023-05-03 15:42
Interestingly, the XDG_DOCUMENTS_DIR does also not show up when i look it up in my env vars, only by calling `xdg-user-dir DOCUMENTS`

**Comment by calixtus** [comment] 2023-05-03 16:30
The longer i think about it, I realize calling calling `xdg-user-dir` is the way it's meant to be, because the basedir specification from freedesktop.org does not mention XDG_DOCUMENT_DIR, but only the manual on the tool `xdg-user-dir` does (https://freedesktop.org/wiki/Software/xdg-user-dirs/). Good news is, every modern desktop environment should have xdg-user-dir installed on default.

Silly us for looking in the system environment vars for that XDG_DOCUMENT_DIR...

**Comment by dermalikmann** [comment] 2023-05-03 18:06
> @koppor I have problems clean up my JabRef configuration thinking I deleted ~/.local/share/JabRef and ~/.local/share/jabref, bun when i run the portable version, it still loads my configuration. Am i missing something?

Thx for the info with ~/.java/.userPrefs
I tired it, and now it defaults to my Home `/home/$USER`

**Comment by koppor** [comment] 2023-05-10 19:05
@dermalikmann Please try the build at https://builds.jabref.org/pull/9837/merge/. JabRef should also display the path at "Help -> View Event Log"

**Comment by dermalikmann** [comment] 2023-05-11 09:44
@koppor  please see my comment in #9837 

if that gets fixed, i think this issue can be closed

**Closed** 2023-05-18 20:16 UTC
Labels: os: linux, external files
