### ISSUE TITLE
Boolean special fields are not uppdated immediately

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1049] opened 2016-03-27 09:14 UTC
JabRef version Current Dev on Windows 10
Steps to reproduce:

1. Click on the quality assured or printed field of an entry in the main table
2. Nothing happens
3. Click on a new entry and observe that now the status of the previous entry changes.

**Comment by oscargus** [comment] 2016-03-28 07:21
The same thing (sort of) happens when automatically fetching and attaching a file.

**Comment by simonharrer** [comment] 2016-05-12 15:13
Cannot be reproduced with debugging - debugging seems to solve this issue. Maybe it has something to do with the focus.

**Comment by matthiasgeiger** [comment] 2016-05-13 08:23
I don't have a clue and I was not able to track it down by now... Has been introduced between release 3.2. and 3.3...

I'll try to find the problematic commit later...

**Comment by matthiasgeiger** [comment] 2016-05-23 19:10
Okay... this already required some time... 
The problem has been introduced in b3aee00bae8b589aa1252ef182f8b3293d06bd69 as the "VetoableChangeListener" has been removed by @tobiasdiez see https://github.com/JabRef/jabref/commit/b3aee00bae8b589aa1252ef182f8b3293d06bd69#diff-fb7038da77cd0b0cfa8958fd90ffc896L632

So basically, a change in the bibdatabase does no longer trigger an update in the main table...

Honestly I do not have any clue how this has worked before, why this has been removed and why it is (somehow) working now... If someone else is already firm in this - help and comments are appreciated ;-)

Perhaps the newly introduced event bus should be used here as an alternative of restoring the VetoableChangeListener?

**Comment by matthiasgeiger** [comment] 2016-05-31 08:17
I tried to dig into it yesterday, but it currently works on `master`... Tested it with three different machines, starting from the jar or directly from the IDE: works fine.

I still do not know what actually has happened that it was not working properly so I'm not sure whether the issue is really solved. Maybe the timing on the eventbus is problematic - but this is really hard to debug...

However, I close this for now - feel free to reopen if the problem shows up again.

**Closed by matthiasgeiger** 2016-05-31 08:17 UTC
Labels: bug, ui
