### ISSUE TITLE
Group view > All entries updates with wrong count

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#5129] opened 2019-07-14 15:13 UTC
JabRef version 5.0-dev on Arch

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When opening Jabref, the number of items in one of my libraries is 115, after changing libraries force and back the count has increased to 1920, but the number of items is still 115.

**Comment by tobiasdiez** [comment] 2019-07-16 07:54
Duplicate of #4441

**Closed by tobiasdiez** 2019-07-16 07:54 UTC
