### ISSUE TITLE
temporary Jabref-files in the /Appdata/local/temp directory are not removed once jabref is closed.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4862] opened 2019-04-07 16:00 UTC
Jabref since at least two years.
- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Today I checked the temporary temp directory where jabref temporary files are stored. I was surprised that files from at least two years were still stored there and using disk space. This behaviour is unacceptable and has to be changed as soon as possible. Temporary files should be temporary and not stored for eternity.

1. ...
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by tobiasdiez** [comment] 2019-05-11 08:24
@LakminiSenanayake wants to work on this issue, but she was not able to reproduce it. Can you please provide detailed steps. Moreover, please make sure that the temporary files were recently created and do not stem from previous versions (as there were previously some problems with closing JabRef which could have resulted in these remaining temporary files).

**Comment by bernhard-kleine** [comment] 2019-05-11 09:13
The problem seems have resolved, since the Jabreffile from today is removed upon closing. Thanks a lot.

![grafik](https://user-images.githubusercontent.com/9216487/57567677-3ffca780-73dd-11e9-8ada-94b93da6f2e1.png)

![grafik](https://user-images.githubusercontent.com/9216487/57567708-b00b2d80-73dd-11e9-8447-f46f66e3250b.png)

**Closed** 2019-05-11 10:08 UTC
Labels: external files, waiting-for-customer-feedback
