### ISSUE TITLE
Delete entry should ask to delete linked files

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#10509] opened 2023-10-16 17:17 UTC
**Is your suggestion for improvement related to a problem? Please describe.**
If you have an entry with a linked file and you delete the entry, then most likely you also want to remove the linked files to keep your pdfs in sync with your entries.

**Describe the solution you'd like**
If there is a linked file, ask the user to also delete it.

**Context**
https://github.com/JabRef/jabref/blob/4e79f1a531a2110f521f29bccf8f0bb0aaebbf79/src/main/java/org/jabref/gui/LibraryTab.java#L454-L456

**Comment by shawn-jj** [comment] 2023-10-16 22:36
Hi there,

I'd like to help with this issue. Could you please assign it to me? I'll take a look and work on resolving the problem. If you have any specific information or steps you'd like me to follow, please feel free to share them.

Thank you!

**Comment by ThiloteE** [comment] 2023-10-16 22:56
Maybe it is possible to implement this as preference? +1 for Pop-ups are evil.

**Comment by 1911-revo** [comment] 2023-10-17 06:24
Hi @shawn-jj, do you mind if I take a try locally as I am aslo interested in this issue ?

**Comment by ThiloteE** [comment] 2023-10-17 08:15
@1911-revo Usually, we try to only have one student (or one group of students that know each other) working on one issue at a time to prevent issues with grading. You might wanna check out our [good first issues](https://github.com/orgs/JabRef/projects/5/views/1) projects page.

**Comment by ThiloteE** [comment] 2023-10-17 08:17
It is already possible to delete the file via right-click in the general tab. Maybe it is possible to re-use parts of the code.
![image](https://github.com/JabRef/jabref/assets/73715071/f4577ad5-16d9-4f05-b7d5-53f9df7155b0)

**Comment by koppor** [comment] 2023-10-17 08:26
> Maybe it is possible to implement this as (non-default) preference? +1 for Pop-ups are evil.

First time delete of entry:

1. Show popup. 
   - Title "Delete attached files"
   - Content: List of attached files
   - BONUS: In case an attached file is linked at another entry, gray it out
   - Buttons "Never delete attached files", "Keep attached files", "Delete attached files"
 2. In case button "Never delete attached files" is pressed, store in preference, that pop up is not shown

Second time deletion of entry:

1. Check preference for deletion of attached files
2. If "Never" break
3. Continue above at step 1

The preference should also be shown in JabRef's preference dialog.

**Comment by shawn-jj** [comment] 2023-10-17 10:19
> Hi @shawn-jj, do you mind if I take a try locally as I am aslo interested in this issue ?

I'm sorry that I cannot share this issue with you😔 (guess you are also on comp2100 assignment?)

**Comment by AEgit** [comment] 2023-10-17 20:25
Note, that this issue might be connected to the first problem described here:
https://github.com/JabRef/jabref/issues/9731

**Comment by koppor** [comment] 2023-10-23 13:39
@shawn-jj Please also try to craft JUnit test cases. Even without them, is there a timeline you can share with us?

**Comment by shawn-jj** [comment] 2023-10-24 05:06
> @shawn-jj Please also try to craft JUnit test cases. Even without them, is there a timeline you can share with us?

I sincerely apologize for the recent slowdown in progress.

I have been occupied with other assignments last week, but I've successfully completed them. As a result, I can now put my full attention to resolving this issue. My goal is to have it resolved within the next week or two, and I will also add JUnit tests. I want to express my gratitude for your patience during this time.🥺

Thank you!

**Comment by koppor** [comment] 2023-10-24 06:53
@shawn-jj Sure thing. I'll be on vacation from Thursday onwards (for three weeks), let's see, how it goes. Others are still around 😅.

An example test was crafted at https://github.com/u74981018/jabref/blob/issue_9798/src/test/java/org/jabref/AutomaticRelinkTest.java (as part of https://github.com/JabRef/jabref/pull/10526).

**Comment by Dalvishubham** [comment] 2024-01-23 05:16
@koppor  can you please explore more about this issue

**Comment by koppor** [comment] 2024-01-24 22:52
@Dalvishubham Maybe you are not familiar with GitHub's UI. On the right side you see two things: a) the issue is reserved and b) there is already a PR on that. The PR is nearly done. Thus, no need to work here.

**Closed** 2024-02-26 19:21 UTC
Labels: type: enhancement, external files, good first issue, FirstTimeCodeContribution
