### ISSUE TITLE
Method in Author model to capitalize first letter of the name

### ISSUE THREAD

**Issue by jackesfonseca** [JabRef/jabref#8646] opened 2022-04-05 11:46 UTC
Looking at the code, I see there could be a method inside the author's model to capitalize the first letter of the string.

**Comment by Siedlerchr** [comment] 2022-04-05 11:51
Is this a question or an issue? Please clarify before you open an issue
Duplicate of #8627

**Closed by Siedlerchr** 2022-04-05 11:51 UTC
