### ISSUE TITLE
Library: add new entry on particular ISBN fails

### ISSUE THREAD

**Issue by ghost** [JabRef/jabref#10123] opened 2023-07-28 18:03 UTC
### JabRef version

5.9 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10 22H2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create a new database
2. Click Library -> New Entry
3. Enter following ISBN: 1-84013-404-6 (from book: Encyclopedia of Minerals Descriptions of over 600 Minerals from around the world.)
4. Click generate
5. See JabRef doesn't respond anymore

![afbeelding](https://github.com/JabRef/jabref/assets/139498085/7736d20c-342c-4348-a5a4-435dfeebb842)

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by dino-girl** [comment] 2023-07-29 18:13
Another ISBN that also makes JabRef not respond anymore.

ISBN: 9781440340741 (from book: The Great Hall of Dinosaurs An Artist’s Exploration Into the Jurassic World)

**Comment by ThiloteE** [comment] 2023-07-29 19:11
Can reproduce. When waiting a little, the following error gets triggered:

![image](https://github.com/JabRef/jabref/assets/73715071/34606512-7696-4387-bd58-be879d0c178b)

So, i guess it's not JabRef, which is faulty, but the database we fetch from.

**Comment by ThiloteE** [comment] 2023-07-29 19:12
503 Service Unavailable

The HyperText Transfer Protocol (HTTP) 503 Service Unavailable server error response code indicates that the server is not ready to handle the request.

Common causes are a server that is down for maintenance or that is overloaded. This response should be used for temporary conditions and the [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) HTTP header should, if possible, contain the estimated time for the recovery of the service.

Note: together with this response, a user-friendly page explaining the problem should be sent.

Caching-related headers that are sent along with this response should be taken care of, as a 503 status is often a temporary condition and responses shouldn't usually be cached.

**Comment by Siedlerchr** [comment] 2023-07-29 20:06
Did you try the latest developments version? There was a fix for this
freezing

ThiloteE ***@***.***> schrieb am Sa., 29. Juli 2023, 21:12:

**Comment by ThiloteE** [comment] 2023-07-29 21:16
Tried the newest development version (via git pull) and it still fails to import the entry, but at least the freezing is gone.

**Comment by ThiloteE** [comment] 2023-07-29 21:20
Ebook.de is down, right? Do we already have a replacement?

**Comment by dino-girl** [comment] 2023-07-29 21:43
I also saw, when imported correctly using ISBN, sometimes some data is wrong.
For example the year is "2010" while the correct year is "2000" (see ISBN below)
Is this also not a JabRef bug but a wrong data in the database?

Example: 

ISBN: 978-0-30743467-8

**Comment by ThiloteE** [comment] 2023-07-29 21:50
Probably.

What you can do is
- to import via DOI, if there is any.
- always crosscheck, if imported data is plausible. There is lots of wrong metadata out there.

**Closed** 2023-08-27 11:10 UTC
Labels: fetcher

**Comment by Siedlerchr** [comment] 2023-08-27 11:12
The first ISBN was a bit weird, 1-84013-404-6 I could not really find any metadata for it, however, it turns out it's available under a different isbn:
978-0-9836323-9-9
