### ISSUE TITLE
It is better if ignoring the group name when searching

### ISSUE THREAD

**Issue by idadoudou** [JabRef/jabref#7393] opened 2021-01-28 06:36 UTC
**Is your suggestion for improvement related to a problem? Please describe.**

1. I have many groups for records. 
2. When I searching, if the keyword is equal to a group name, then all records in the group is selected. 
3. If I want to select the group, I can directly click the group name. 

**Describe the solution you'd like**

**Additional context**

**Comment by mlep** [comment] 2021-01-28 07:55
Actually, this is a feature: if you search for "cloud", JabRef with display all entries containing "cloud" in any of their fields. If you are looking for the entries containing "cloud" as a keyword, you have to state it by typing in the search field "keywords=cloud".

**Comment by Siedlerchr** [comment] 2021-02-05 19:14
Closing this, because it's intended behaviour.

**Closed by Siedlerchr** 2021-02-05 19:14 UTC
