### ISSUE TITLE
Auto BibTeX key generator removes colons

### ISSUE THREAD

**Issue by MBradbury** [JabRef/jabref#4101] opened 2018-06-05 09:55 UTC
I have a default pattern of "[auth]:[year]:[shorttitle]", but when autogenerating keys rather than obtaining "Wei:2017:modelingunderstandingvehicle" the following is entered "Wei2017modelingunderstandingvehicle".

JabRef version 4.3.1 on Windows 10 x64

Steps to reproduce:

1. Create a bib file with the entry at the end of this report
2. Modify the BibTeX Key Generator default settings to contain "[auth]:[year]:[shorttitle]" (without quotes)
3. Press the Autogenerate BibTeX keys button
4. Observe that the key does not contain colons as expected

@InProceedings{00001,
  author    = {M. Wei and Z. Lu and W. Wang},
  title     = {On Modeling And Understanding Vehicle Evacuation Attacks In Vanets},
  booktitle = {2017 Ieee International Conference On Communications (icc)},
  year      = {2017},
  pages     = {1--7},
  month     = may,
}

**Comment by tobiasdiez** [comment] 2018-06-05 17:07
Duplicate of #4010

**Closed by tobiasdiez** 2018-06-05 17:07 UTC

**Comment by tobiasdiez** [comment] 2018-06-05 17:08
As discussed in #4010, if you want colons in your key you need to disable the option "Enforce legal keys " in the preferences.

**Comment by MBradbury** [comment] 2018-06-05 17:19
Would it be possible to update the documentation at https://help.jabref.org/en/BibtexKeyPatterns to specify disabling that options?

**Comment by tobiasdiez** [comment] 2018-06-05 17:24
Yes and it would be a great help if you would update it yourself. Just click on the "github icon" in the upper right corner (or go to https://github.com/JabRef/help.jabref.org/blob/gh-pages/en/BibtexKeyPatterns.md) and click on the "edit" button (the pencil). Then submit your changes. Thanks!
