### ISSUE TITLE
CanonicalBibtexEntryTest fails locally

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#493] opened 2015-12-09 16:32 UTC
For me the test fails locally but runs on the CI server

Expected
```  
@article{key,[]
  author = {abc},
 ...
```

Actual

```  
@article{key,[
]
  author = {abc},
 ...
```

Newline problem inside canonical formatter?

**Comment by tobiasdiez** [comment] 2015-12-09 16:55
I have this too, with a dozen of other tests failing too. As far as I can see, they are all caused by my customized preferences.

**Comment by simonharrer** [comment] 2015-12-10 08:23
Hm, canonical should be independent from preferences...

**Comment by simonharrer** [comment] 2015-12-13 22:17
Should be fixed in e98c7db01df954ddd6082ca46bb9ef275d546baa

**Closed** 2015-12-15 14:16 UTC
Labels: testing
