### ISSUE TITLE
Syntax check complaining about standalone backslash+curly brace

### ISSUE THREAD

**Issue by jannick0** [JabRef/jabref#678] opened 2016-01-17 09:39 UTC
The syntax checker complains about a standalone \\\{ , i.e. without a coupling \\\} . This happens, e.g., in the abstract section where many of the downloaded texts have a standalone \\\{.

**Comment by lenhard** [comment] 2016-01-17 15:32
I may be mistaken, but isn't that exactly what the syntax check should do? Detecting unmatched braces? 

Could you please state what your actual issue is? Do you think the syntax check should not complain in this situation? Why?

**Comment by oscargus** [comment] 2016-01-18 22:07
Because it is escaped?

**Comment by lenhard** [comment] 2016-01-18 22:48
And we don't want to check unmatched escaped braces? (Seriously, I don't care that much. We should just decide something reasonable)

Anyway, we should probably find out what part of the program complains exactly and what the effect is.

**Comment by oscargus** [comment] 2016-01-19 07:51
I'm thinking that { is a LaTeX construct that should be matched with } to make sense while \{ is just a character. I have no idea what @jannick0's abstracts looks like and cannot really figure out a good example myself to motivate it, but there still seems to be a fundamental difference between { and \{.

**Comment by jannick0** [comment] 2016-01-19 09:46
I went back to my jabref db and tried to find out what is going on here. Ultimately I am not sure any more if this is really an issue: The pattern in the math formulae of my ref items jabref is complaining about looks like this:

             $\{B}bb{L}$

which for whatever reason had apparently been converted to from the (syntactically correct) pattern

             $\Bbb{L}$

After applying the latter expression to all of my ill refs everything is just fine. So I guess this not an issue any more, since jabref appears to be complaining about the (first) closing brace which doesn't see any matching **unescaped** opening brace.

Appreciate your support, guys.

**Comment by oscargus** [comment] 2016-01-19 09:51
Ahh, OK! Then I guess it is an issue caused by automatically adding braces to capitals on save. I am a bit sceptic to this feature in general, so I guess this is another argument for me. ;-)

**Comment by jannick0** [comment] 2016-01-19 10:05
Are you saying that upon save jabref encloses each and every capital letter in curly braces - regardless if the it is within a formula or - outside of a formula - is preceeded by a backslash? ... then my issue was caused by jabref and not by my colleague I have the refs from and I wanted to blaim for? :)

**Comment by oscargus** [comment] 2016-01-19 10:13
I'd say it can be both alternatives. :-) It depends on if your colleague set the abstract field as one of the fields to do this on (which somehow is his fault) or if he did it by hand. JabRef will not automatically do this to a field, fortunately, but it must be configured to do so.

**Comment by jannick0** [comment] 2016-01-19 10:19
Great - understand. Better I will release my colleague from jail now. ;)

I leave it with you guys to close this ticket since you are in a far better position to decide on that.

Thanks again!

**Comment by lenhard** [comment] 2016-01-19 10:33
@oscargus Is this resolved from your point of view, or is there something remaining that we should do? (If not, we can close it) 

Also, are there other open issues regarding auto bracing?

**Comment by oscargus** [comment] 2016-01-19 10:47
@lenhard I think that this can be closed as the reason is established.

Regarding the auto bracing, I think this shows that one should check if e.g. $\Alpha$ is braced correctly, and if the checks are valid then. The bigger auto-bracing issue is on a different level and a discussion I've tried several times. :-) However, I do not really enjoy the behaviour that the braces are removed upon loading and added back on saving. Adding braces can be good to avoid manual work, but there's a big risk that they are added where they shouldn't and by not showing the behaviour to the user they will never understand what braces does and we will end up with incorrectly formatted reference lists.

Somehow, hiding things from users and forcing them to behave correctly is good, but then it must be 100% correct and I do not think braces around capitals can ever be added automatically based on the fact that they are capitals... Automatic identification of abbreviations would be one thing though.

I may better add this discussion elsewhere...

**Closed by oscargus** 2016-01-19 10:47 UTC
Labels: question
