### ISSUE TITLE
Administrator priviledge problem with preferences

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#141] opened 2015-09-03 14:31 UTC
``` 
Sep 03, 2015 4:25:30 PM java.util.prefs.WindowsPreferences <init>
WARNUNG: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
```

Haven't evaluated yet what consequences this has...

**Comment by koppor** [comment] 2015-09-03 14:41
Stackoverflow discussion. http://stackoverflow.com/q/16428098/873282. Shows a manual solution only.

**Comment by ambro2** [comment] 2015-09-13 16:09
Same warnings here with versions 2.11b4, 2.10 and 2.9.2 (Windows 7 64bit, Java 1.8.0_60 64bit).
The Stackoverflow discussions refer to the **HKEY_LOCAL_MACHINE**\Software\JavaSoft\Prefs key which is already in place in my system. However JabRef preferences are stored in **HKEY_CURRENT_USER**\Software\JavaSoft\Prefs.
Hope it heps figuring out and fixing the problem.

**Comment by matthiasgeiger** [comment] 2015-09-24 08:03
... I just wanted to try to fix this issue... but at my machine the warning does not occur anymore. :hushed:
 Can you confirm this?

**Comment by koppor** [comment] 2015-09-24 08:48
@matthiasgeiger Has this something to do with #132? Did the JRE change the way, preferences are stored?

**Comment by matthiasgeiger** [comment] 2015-09-24 08:57
Okay... the reason seems to be that one Java Application requesting UAC admin rights during installation setted the `HKEY_LOCAL_MACHINE\Software\JavaSoft\Prefs` folder/key - after removing this the warning comes back.

The actual reason for the warning is described [here at stackoverflow](http://stackoverflow.com/questions/18559000/reading-and-writing-from-to-java-preferences-fails-on-fresh-windows-8): 
> It turned out that the culprit is this static member variable: WindowsPreferences.systemRoot

> Looks like Java tries to initialize WindowsPreferences.systemRoot just in case it is used later on by the program, and that initialization obviously fails if the program is not ran as administrator.

> Since you're using Preferences.userNodeForPackage(), you will never need the systemRoot, therefore you can safely ignore that warning.

So I do not think this is related to #132 (especially we are storing the prefs in `HKEY_CURRENT_USER\Software\JavaSoft\Prefs`)

As this behavior is caused by the used JDK this is won't fix and should be closed.

**Closed** 2015-09-24 13:25 UTC
Labels: windows, wontfix
