### ISSUE TITLE
Groups: Union/Intersection: needs re-selection of groups to take effect

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6998] opened 2020-10-09 19:01 UTC
JabRef 5.2--2020-10-07--4b1b7b4
Linux 4.9.0-13-amd64 amd64 
Java 15

The group pane allows to choose between an intersection and a union when selecting several groups.

- [x] Groups: Union/Intersection: need restart of groups to take effect

   Issue: When clicking on the Intersection/Union button, an information message is displayed, but the list of entries in the table of entries is not changed. A restart of JabRef is needed for the selected mode to become active. A restart should not be needed.

   
  1. Open the file jabref-authors.bib (https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/jabref-authors.bib)
  2. Select the groups "By status" and "By rating"
       Here you should have 1 entry displayed (if you are in intersection mode) or 48 entries displayed (if you are in union mode)
  3. Click once on the Union/Intersection button
       An information message at the bottom of the window confirms the change, 
       but the number of displayed entries is still the same.
  4. Close and restart JabRef
  5. Reselect the 2 groups
      If you had one entry displayed, you now get 48, and vice-versa.

    Note 1: when clicking on the union/intersection button, the aspect of the button is not always changed
    Note 2: the hovering message ("Toggle union" or "Toggle intersection") can contradict the information message. E.g. hovering message is "Toggle union", and after the click, the information message is "Group view mode set to intersection".
    Note 3: resetting the preferences did not change the behavior.
    Note 4: In the preferences, the "Groups" tab has two radio buttons: "Display only entries belonging to all selected groups" and "Display all entries belonging to one or more of the selected entries". This seems equivalent to Intersection and Union, respectively. What is their use?

**Edit:** Meanwhile some progress has been made. What is left to do:

- [ ] Groups: Union/Intersection: needs re-selection of groups to take effect

**Comment by Siedlerchr** [comment] 2020-10-09 19:22
Good observation, guess it's related to the fact
 that the selected mode is stored in the preferences and not immediately saved/persisted and reloaded 

The information message shows the current mode. The toggle button hover should always show the next mode.
Might be a timing thing related to the preference

**Comment by mlep** [comment] 2020-10-12 09:23
@Siedlerchr  In the preferences, do the two radio buttons "Display only entries belonging to all selected groups" and "Display all entries belonging to one or more of the selected entries" could be removed? (what is their use?)

**Comment by Siedlerchr** [comment] 2020-10-30 08:25
I looked ab bit more into this.
The problem is that the groupViewMode is only used in the MainTableDataModel read from the preferences and passed to the  matcher in groups.

https://github.com/JabRef/jabref/blob/fcf61462ae3867cb4bcfe75466772db63726a8bb/src/main/java/org/jabref/gui/maintable/MainTableDataModel.java#L46-L56 

Here the value is used.
https://github.com/JabRef/jabref/blob/fcf61462ae3867cb4bcfe75466772db63726a8bb/src/main/java/org/jabref/gui/maintable/MainTableDataModel.java#L74-L80

A solution would be to add another property to the stateManager, e.g. `activeGroupViewModeProperty` and bind it to the toggle switch or just set the value here.
https://github.com/JabRef/jabref/blob/8777c16a99bd83e4a30ddafc859c0c2208b68733/src/main/java/org/jabref/gui/groups/GroupSidePane.java#L64-L65

This property needs then to be passed to the above listed group matcher

**Comment by AEgit** [comment] 2020-12-18 10:48
Note, that this issue appears to (indirectly) be related to the problem that there is still not floating mode available for the main table in JabRef 5 (https://github.com/JabRef/jabref/issues/4237; see also comment here: https://github.com/JabRef/jabref/issues/4237#issuecomment-433863717).

Implementing the floating mode might (?) solve some of the groups issues mentioned here by design. Sorry for keeping pointing to that issue, but as long as it is not implemented I cannot switch from JabRef 3.8.2 to the new version 5.

**Comment by bjhamilton** [comment] 2021-01-14 14:44
> Issue: When clicking on the Intersection/Union button, an information message is displayed, but the list of entries in the table of entries is not changed. A restart of JabRef is needed for the selected mode to become active. A restart should not be needed.

I can replicate this. Looking forward to this bugfix.

**Comment by calixtus** [comment] 2021-09-22 19:49
Can maybe solved with the new preferences model we started to implement. See https://github.com/JabRef/jabref/pull/8047

**Comment by HoussemNasri** [comment] 2022-07-22 15:39
I can't reproduce this in the latest development version. Now, Union/Intersection will take effect after reselecting the groups.

**Comment by ThiloteE** [comment] 2022-07-22 17:04
True.

Closing this :)

**Comment by ThiloteE** [comment] 2022-07-22 17:06
One could make the argument though, that no re-selection of groups should be necessary for the change to take effect. Maybe worthy of being a Koppor issue.

**Comment by AEgit** [comment] 2022-07-23 18:09
Agree - having to reselect the groups is not intuitive.

**Closed** 2022-07-26 08:09 UTC
Labels: type: bug 🐛, groups
