### ISSUE TITLE
More users, more feedback, more developers, ...

### ISSUE THREAD

**Issue by simonharrer** [JabRef/jabref#1303] opened 2016-04-26 13:23 UTC
As discussed with @stefan-kolb  and @matthiasgeiger, we want more users, and more feedback, and also more developers. 

What can help:
- use JabRef as a case study during courses, e.g., UX, Java, Architecture, Programming, Open source, ...
- use JabRef as a tool for tutorials about literature management, scientific work, etc.
- make sure your university library provides courses about JabRef in addition to other popular tools
- make sure your university lists JabRef next to the other tools on their homepage or wikis

We should
- write down what has already been done
- and try to get evangelists which may help with the above points in their university

Feel free to add any comments or suggestions what can be done and also what you would be willing to do.

**Comment by mlep** [comment] 2016-04-26 14:55
About new developers:
Users may also be developers. Example: During the "Translation challenge", while asking only for translation (i.e. no programming skills), I got in touch unexpectedly with 2 java developers and one graphic designer (@koppor has their emails). So, they are developers around! Hence, I believe the issue is more about how to make them contribute. Suggestion:
- send emails to the mailing list to ask for specific developments, or for specific skills (e.g. GUI design). Post on blog too? I can help in writing them down.

About more feedback from users:
- Advertise that X issues reported by users have been solved in the last Y days (to show that it is worth to report issues). I can help in writing them down.
- When a new feature is implemented, advertise it on the blog and mailing list, asking for testing. That will also improve the overall quality of JabRef (more bugs found).  I can help in writing them down.
- Open discussions on the mailing list about JabRef. Currently, the development team mostly reply to users' emails. The development team could (should?) also send emails to the mailing to ask users for feedback and initiate discussion (e.g. redesign of the menus, preferred keyboard shortcuts).

About more users:
- Write "case studies", showing how JabRef is used in everyday life in a library, a research team, etc. We could contact people who have already written about JabRef for a specific piece of text (search the web for it).  Could be written by users (ask them for contribution on the mailing list).
- Show that JabRef is already widely used, by publishing the download statistics, the list of donations, etc.
- Get (recent versions of) JabRef in the main Linux distributions.
- Show that previous drawbacks of JabRef are gone (list of drawbacks in the survey). Each time one is overcome, advertise it.
- Drive the development based on the needs of numerous users (i.e. not only solving reported issues). I do not mean that it is not done at the moment; I mean that this should be made more explicit.

**Comment by Siedlerchr** [comment] 2016-04-26 17:43
I really like the idea! In fact I got into Jabref as a user, because the department I chose to write a paper, recommended JabRef. 
And I know that other departments/professors at my university (University Paderborn) use JabRef.

> Use JabRef as a tool for tutorials about literature management, scientific work, etc.
> make sure your university library provides courses about JabRef in addition to other popular tools
> make sure your university lists JabRef next to the other tools on their homepage or wikis

I am sure that this would be a nice idea. 
My university is already providing several courses for topics going from traditonal  MS Office to LaTex, Photoshop etc.. I like the idea 

Mabye it would also be nice to get some  kind of  official "certificate" for your CV, for developing/contributing to JabRef.

**Comment by matthiasgeiger** [comment] 2016-04-27 08:02
To encourage universities and libraries to use JabRef (or at least link to us) in their tutorials on scientifc work and literature management it might be helpful to provide some "reference tutorials" or a set of free presentation slides introducing JabRef and its main features.

> Mabye it would also be nice to get some kind of official "certificate" for your CV, for developing/contributing to JabRef. 

And of course some JabRef shirts, mugs, buttons and stickers :wink:

**Comment by tobiasdiez** [comment] 2016-04-27 08:17
I also think we need to provide more resources to help users and librarians with JabRef (I mean even we developer discover "hidden" features which are only documented in the code). Looking at this [comparison of bibliographic manager (in German)](https://mediatum.ub.tum.de/doc/1271693/1271693.pdf) the only clear disadvantage of JabRef is exactly in the outreach. See Citavi for example

> Kurzanleitung (quick start tutorial)
> Handbuch (manual)
> Handbuch zum wissenschaftlichen Arbeiten (manual about working scientifically)
> Filme und Animationen (films and animations)
> sehr gute kontextsensitive Hilfe (anpassbar / editierbar) (contexted base help)
> Forum
> Ticket-System
> Chat
> Trainier-Netzwerk

**Comment by koppor** [comment] 2016-04-27 10:20
We have a German user manual. Should we integrate it into the help (refs https://github.com/JabRef/jabref-usermanuals/issues/1)? Should we convert it into slides? - We could use [odpdown](https://github.com/thorstenb/odpdown) if we are too lazy to use PowerPoint or [latex-beamer](https://www.ctan.org/pkg/beamer).

**Comment by simonharrer** [comment] 2016-05-19 13:38
Next semester the library of University of Bamberg, Germany, will also provide a tutorial on scientific writing with JabRef. We hopefully can publish the material of this course as a tutorial on jabref.org

**Comment by koppor** [comment] 2016-07-07 06:44
We are currently trying to focus on other things. :fire:
We will come back later to this topic, therefore closing adding [on-hold label](https://github.com/JabRef/jabref/issues?utf8=%E2%9C%93&q=label%3Aon-hold+) and closing the issue for now.

**Closed by koppor** 2016-07-07 06:44 UTC
Labels: on-hold

**Comment by koppor** [comment] 2016-07-15 15:11
Revent forks can be investigated at http://forked.yannick.io/JabRef/jabref. There seem to be courses taking place for increasing test coverage of JabRef -> https://github.com/gabrielmldantas/jabref/pulls. I commented on both PRs whether they want to integrate their tests at our code base.
