### ISSUE TITLE
Import window is displayed in background

### ISSUE THREAD

**Issue by Ede123** [JabRef/jabref#210] opened 2015-10-05 11:34 UTC
I'm using JabRef 2.11b4 on Windows 7 x64 with Java 8 Update 60.

I have set Firefox to open .bib files with JabRef (JabRef.exe in JabRef directory to be specific).

If JabRef is already opened in background an import window is shown for the new entry.
The problem is that this import window is not brought to the foreground (i.e. the window is not focused). Therefore the import window is always hidden behind the browser window. Since the import window is not shown in task bar either, it seems as if the import had failed (unless one "digs" for the import window with Alt+Tab).

**Comment by stefan-kolb** [comment] 2015-10-09 14:24
@Ede123 Can you reproduce this issue with the current master branch?

**Comment by Ede123** [comment] 2015-10-09 15:28
I have  to check. Are there somewhere pre-built versions available or do I have to build from source?

**Comment by koppor** [comment] 2015-10-09 16:28
The build artifacts are only available via deep link: https://circle-artifacts.com/gh/JabRef/jabref/674/artifacts/0/home/ubuntu/jabref/build/releases/JabRef-2.80dev--snapshot--2015-10-09--8fe4c28.jar and https://circle-artifacts.com/gh/JabRef/jabref/674/artifacts/0/home/ubuntu/jabref/build/releases/JabRefSetup-2.80dev--snapshot--2015-10-09--8fe4c28.exe

**Comment by lenhard** [comment] 2015-11-16 18:49
Closing, since @Ede123 seems to have lost interest.

Feel free to reopen if the problem reappears.

**Closed by lenhard** 2015-11-16 18:49 UTC
Labels: ui
