### ISSUE TITLE
5.1 (10 March 03:25): Optional fields tab does not expand right side

### ISSUE THREAD

**Issue by rs-aesi** [JabRef/jabref#6097] opened 2020-03-11 00:25 UTC
This issue appeared (and was fixed) in an earlier 5.0 release. Now it's back in today's 5.1 snapshot.

The attached jabref-compressed.png shows the optional fields as they appear when the reference is selected. The left side has two columns but the right column cannot be seen or used. Expanding the tab moves the left column to the right but leaves the right column the same size (jabref-expanded.png). The expansion should be between these two columns of the optional tab rather than between the optional tab and the text on the right side of the compressed image.

![jabref-compressed](https://user-images.githubusercontent.com/18408428/76370416-fed26e00-62f3-11ea-9b2a-561ba2a885a1.png)

![jabref-expanded](https://user-images.githubusercontent.com/18408428/76370428-07c33f80-62f4-11ea-8e33-12f9183de40c.png)

Thanks in advance,

Rich

**Comment by Siedlerchr** [comment] 2020-03-11 07:58
As a workaround you can make the entry preview a separate tab (somewhere in the preferences is a setting)  so you should be able to see the fields again

**Comment by rs-aesi** [comment] 2020-03-11 12:43
On Wed, 11 Mar 2020, Christoph wrote:

> As a workaround you can make the entry preview a separate tab (somewhere
> in the preferences is a setting) so you should be able to see the fields
> again

Christoph,

I'll rummage around in the preferenes for that setting. I don't need to see
the entire entry in that right-most window. If the Optional Fields tab can
use all available space that works better for me.

Thanks,

Rich

**Comment by rs-aesi** [comment] 2020-03-11 13:31
On Wed, 11 Mar 2020, Christoph wrote:

> As a workaround you can make the entry preview a separate tab (somewhere
> in the preferences is a setting)  so you should be able to see the fields
> again

Christoph,

I looked in Options -> Preferences. There are three items mentioning entry:
Entry table, Entry table columns, Entry preview. I did not recognize an
option in any of the dialog boxes that would be appropriate. A pointer would
be helpful.

Regards,

Rich

**Comment by mlep** [comment] 2020-03-11 13:57
Well, it is in the item "Entry Preview". There, check the box "Show preview as a tab in entry editor".

Tip: when you are looking for something in the Preferences, there is an helpful search field at the upper-left corner of the preference window.

**Comment by rs-aesi** [comment] 2020-03-11 15:43
On Wed, 11 Mar 2020, MLEP wrote:

> Well, it is in the item "Entry Preview". There, check the box "Show
> preview as a tab in entry editor".

MLEP,

Mea culpa! I saw that check box and didn't realize what it meant so I
scanned the list below and left that page. I didn't realize the display I
wanted to remove was the entry preview.

> Tip: when you are looking for something in the Preferences, there is an
> helpful search field at the upper-left corner of the preference window.

Good to know ... as long as I know what I'm seeking is called. :-)

Many thanks,

Rich

**Comment by mlep** [comment] 2020-03-11 15:51
No problem. Because @Siedlerchr mentioned "entry preview", I thought you would be looking for it.

**Comment by rs-aesi** [comment] 2020-03-11 16:00
On Wed, 11 Mar 2020, MLEP wrote:

> No problem. Because @Siedlerchr mentioned "entry preview", I thought you
> would be looking for it.

I missed that when I read the message.

Rich

**Comment by stefan-kolb** [comment] 2020-03-14 18:00
I cannot reproduce that behavior. It works for me. Both input fields expand simultaneously.

**Comment by koppor** [comment] 2020-04-14 07:04
@stefan-kolb Did you try the dark theme

@rs-aesi Could you try the light theme, please?

**Comment by stefan-kolb** [comment] 2020-04-14 07:06
No only light theme.

**Comment by rs-aesi** [comment] 2020-04-14 14:51
On Tue, 14 Apr 2020, Oliver Kopp wrote:

> @rs-aesi Could you try the light theme, please?

Oliver,

I will when I learn where the switch is located. I looked in Options ->
Prefernces, then all menus and missed seeing where the themes are shown.

Regards,

Rich

**Comment by leitianjian** [comment] 2020-04-16 04:42
We try to reproduce this bug but failed both on dark and light theme at the newest master branch.

And I don't quite understand the usage of the "show preview as a tab in entry editor". Because there seems no differences between enable the function and disable the function.

**Comment by AEgit** [comment] 2020-04-18 10:08
@leitianjian: Note, that the full change related to "Show preview as a tab in entry editor" only takes effect after JabRef has been restarted: https://github.com/JabRef/jabref/issues/5464

**Comment by koppor** [comment] 2020-04-28 06:19
- [ ] Document "show preview as a tab in entry editor" in https://docs.jabref.org (Preferences -> Preview)
- [ ] @JabRef/developers Try to reproduce. We think it could be because of our calculation of the width of the first/second column.

@rs-aesi Could you write us the screen resolution you chose? Two developers could not repoduce it. Maybe, they have large screens...

**Comment by rs-aesi** [comment] 2020-04-28 12:32
On Mon, 27 Apr 2020, Oliver Kopp wrote:

> - [ ] Document "show preview as a tab in entry editor" in https://docs.jabref.org (Preferences -> Preview)
> - [ ] @JabRef/developers Try to reproduce. We think it could be because of our calculation of the width of the first/second column.
>
> Could you write us the screen resolution you chose? Two developers could
> not repoduce it. Maybe, they have large screens...

1280 x 1024

Both desktop monitors are HP/Compaq LA1951g, 19", almost square.

HTH,

Rich

**Comment by rs-aesi** [comment] 2020-12-08 20:20
On Tue, 8 Dec 2020, github-actions[bot] wrote:

> This issue has been inactive for half a year. Since JabRef is constantly
> evolving this issue may not be relevant any longer and it will be closed
> in two weeks if no further activity occurs.

There's a work-around so this no longer needs anyone's time.

Thanks,

Rich

**Comment by Siedlerchr** [comment] 2020-12-08 20:23
Closing in favor of https://github.com/JabRef/jabref/issues/6901#issuecomment-691493493 which contains some hints on where the code is located for fixing this

**Closed by Siedlerchr** 2020-12-08 20:23 UTC
Labels: entry-editor, type: bug 🐛, ui
