### ISSUE TITLE
Group field not visible in the editor when no group has been entered before.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3213] opened 2017-09-13 09:24 UTC
JabRef 4.0-beta3
Windows 7 6.1 amd64 
Java 1.8.0_144

Trying to enter a group for an entry in the editor is not possible, when there  no former group has been defined for that entry, since the group field is not shown.

This is a omission since in some situation it is easier and faster to type a group in the editor than using the group panel. 

Adding the group using the bibtex source, added the group field to the editor, but not the newly created group to the group panel, even after closing Jabref and reopening it. 
(I checked the closed subgroups for any occurrence of "evolution" and found any)
![grafik](https://user-images.githubusercontent.com/9216487/30370450-ef6b351c-9877-11e7-9022-d265815a3ad8.png)

**Comment by lenhard** [comment] 2017-09-13 15:27
That is by design and was implemented in #3097.

Some users were annoyed by having a Other fields tab, when they did not actually use other fields. That's why we now only display the tab when there's actual content.

@JabRef/developers We won't make everyone happy. My personal suggestion would be to mark this issue as "won't fix".  Before we refactored grouping, the group tree was the only way to do assignment anyway. Alternatively, we could move the groups field somewhere else (since it might be more important than "other" other fields)

**Comment by bernhard-kleine** [comment] 2017-09-13 16:50
The empty/missing field when a group has not been assigned I can accept, but the other thing, when a group is not properly shown in the group panel, is not acceptable. That should be fixed. 

It is the almost same problem when a JR3.8 database is opened in JR4.0 and any groups are not shown which has already been mentioned several times before. Why not use in that case the rudimentary tree taken from the group field information? 

I always thought an update would deal with prior versions of the software. And the group in 3.8 file is there, but not translated to 4.0. The burden of this should be on the shoulder of the programmer(s), not of the user. You know for quite some time that the group interface has changed, but dared to do anything about it. If this sound harsh, I have to admit that I like jabref, but the policy in this regard is faulty.

**Comment by koppor** [comment] 2017-09-13 17:12
+1 for moving groups from "Other" to "General"

Am 13.09.2017 17:27 schrieb "Jörg Lenhard" <notifications@github.com>:

**Comment by tobiasdiez** [comment] 2017-09-13 20:07
@bernhard-kleine Migration of groups from 3.8 to 4.0 should work without a problem, if not then this is a bug! What does not work is the converse: if you open a database created with 4.0 in 3.8, then the group tree is not shown properly and/or not all entries are properly assigned to the groups. But it is understandable that new versions might break backwards-compatibility is such a way.

**Comment by tobiasdiez** [comment] 2017-11-07 03:34
The field now went to the general tab and should be always visible there (you may need to reset to the default entry editor layout under Options > Set up general fields).

It would be nice to have a proper interface to add groups directly. This will be tracked in https://github.com/JabRef/jabref/issues/2899 but is not likely to happen in the near future (which is why the issue is put on-hold for now).

**Closed by tobiasdiez** 2017-11-07 03:34 UTC
Labels: enhancement, entry-editor, groups, ui

**Comment by bernhard-kleine** [comment] 2017-11-07 19:53
@tobiasdiez is it a snapshot where this is included Now?

**Comment by tobiasdiez** [comment] 2017-11-08 02:04
Yes it is in the current master; you can try the build from http://builds.jabref.org/master/
