### ISSUE TITLE
Copy paste from preview 

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#3992] opened 2018-04-27 13:34 UTC
I just downloaded 4.2 and noticed that copy from the preview screen has a few bugs.

- [ ] Firstly, selecting the preview, and clicking right + copy preview does not behave like its shortcut shift-control-c. The former copies the html code rather than the text only. 

- [ ] Secondly, after having copied a preview entry, returning to the preview box makes Jabref crash (window just closes abruptly). This is reproducible. 

(JabRef 4.2 Windows 10 10.0 amd64  Java 1.8.0_171)

**Comment by stefan-kolb** [comment] 2018-04-27 15:09
Can confirm the behavior for v4.2.
However, I cannot reproduce this behavior on the current `master`. 
At least not in the development environment, although we did not make any changes to the code since then...except the Guava upgrade.
Can you please try the latest build from http://builds.jabref.org/master.

**Comment by tobiasdiez** [comment] 2018-04-28 09:31
Can you please try out the version from https://builds.jabref.org/maintable-beta/ and check if it is fixed there.

**Comment by lc9275** [comment] 2018-04-28 14:31
This version works fine for me (and with the previous behavior that control-c just copies the text as displayed). Thanks a lot!

**Comment by tobiasdiez** [comment] 2018-04-29 22:04
ok, thanks for the quick feedback.

Since this concerns not a major feature, I don't think we need to backport the fix to 4.* and hence close this issue.

**Closed by tobiasdiez** 2018-04-29 22:04 UTC
Labels: bug
