### ISSUE TITLE
Out of bounds Error after import and clicking on group. Btw. Event Log doesn't record.

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#7881] opened 2021-07-04 21:16 UTC
JabRef 5.3--2021-07-02--eed637a
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

**Description of bug:**

Error message, Out of bound read.

**Steps to reproduce the behavior:**
1. Import my .ris file (that was created by citavi 6.
2. click select an entry in the main field, move around with the arrow keys on your keyboard. On my first iteration this was enough to trigger the error. When i tried to reproduce, it did not work, but it happened in step 3.
3. click on another group within the database. It is sufficient if there are no entries in that group.
4. Error.

I could imagine that the error is somehow connected to "?" symbols in the url entries. Some websites use "?", for example google books.

Here the .bib file:
[Bugtestlibrary 2.txt](https://github.com/JabRef/jabref/files/6760578/Bugtestlibrary.2.txt)

Here the imported .ris file:
[20210420 S4 SS2021 (Referat) IPÖ Fröhlich - Keynes & Monetarismus - Kopie.txt](https://github.com/JabRef/jabref/files/6760592/20210420.S4.SS2021.Referat.IPO.Frohlich.-.Keynes.Monetarismus.-.Kopie.txt)

i can't paste more log files, because in the event log there is nothing recorded. Is this normal?. This is what i got from the error message:

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here

java.util.NoSuchElementException: java.lang.IndexOutOfBoundsException
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@5.3.428/org.jabref.gui.maintable.MainTable.getSelectedEntries(Unknown Source)
	at org.jabref@5.3.428/org.jabref.gui.LibraryTab.lambda$createMainTable$15(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearSelection(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ListExpressionHelper$Generic.notifyListeners(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ListExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.property.ReadOnlyListPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.property.ReadOnlyListWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.property.ListPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.property.ListPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.MapListenerHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ObservableMapWrapper.callObservers(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ObservableMapWrapper.put(Unknown Source)
	at org.jabref@5.3.428/org.jabref.gui.StateManager.setSelectedGroups(Unknown Source)
	at org.jabref@5.3.428/org.jabref.gui.groups.GroupTreeViewModel.lambda$onSelectedGroupChanged$3(Unknown Source)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at org.jabref@5.3.428/org.jabref.gui.groups.GroupTreeViewModel.onSelectedGroupChanged(Unknown Source)
	at com.tobiasdiez.easybind@2.2/com.tobiasdiez.easybind.EasyBind.lambda$subscribe$1(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ListExpressionHelper$Generic.notifyListeners(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ListExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.binding.ListExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.property.ListPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.property.ListPropertyBase.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ModifiableObservableListBase.setAll(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.beans.binding.ListExpression.setAll(Unknown Source)
	at org.jabref@5.3.428/org.jabref.gui.groups.GroupTreeView.updateSelection(Unknown Source)
	at org.jabref@5.3.428/org.jabref.gui.util.BindingsHelper$BidirectionalListBinding.onChanged(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.TreeTableView$TreeTableViewArrayListSelectionModel.clearAndSelect(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.simpleSelect(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.behavior.TableCellBehaviorBase.doSelect(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.behavior.CellBehaviorBase.mousePressed(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.428/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException
	at org.jabref.merged.module@5.3.428/javafx.collections.transformation.SortedList.get(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.TableView$TableViewSelectionModel.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.3.428/javafx.scene.control.MultipleSelectionModelBase$1.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.3.428/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.get(Unknown Source)
	... 143 more

	... 143 more


</details>

**Comment by ilippert** [comment] 2021-09-24 12:28
JabRef 5.4--2021-09-22--e9d845b
Linux 5.13.16-200.fc34.x86_64 amd64 
Java 16.0.2 
JavaFX 17+18

I think I experienced a similar error when searching for a citekey

<details>
<summary>Log File</summary>
```
java.util.NoSuchElementException:`` java.lang.IndexOutOfBoundsException
	at java.base/java.util.AbstractList$Itr.next(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@5.4.219/org.jabref.gui.maintable.MainTable.getSelectedEntries(Unknown Source)
	at org.jabref@5.4.219/org.jabref.gui.LibraryTab.lambda$createMainTable$15(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList._endChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.scene.control.MultipleSelectionModelBase$SelectedIndicesList._endChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.scene.control.ControlUtils.updateSelectedIndices(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.scene.control.TableView$TableViewArrayListSelectionModel.fireCustomSelectedCellsListChangeEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.scene.control.TableView$TableViewArrayListSelectionModel.clearSelection(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.scene.control.TableView$TableViewArrayListSelectionModel.updateDefaultSelection(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.scene.control.TableView$TableViewArrayListSelectionModel.lambda$new$2(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ListChangeBuilder.commit(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ListChangeBuilder.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ObservableListBase.endChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.transformation.SortedList.sourceChanged(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.transformation.TransformationList.lambda$getListener$0(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.WeakListChangeListener.onChanged(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.ObservableListBase.fireChange(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.transformation.FilteredList.refilter(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.collections.transformation.FilteredList$1.invalidated(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.beans.property.ObjectPropertyBase$Listener.invalidated(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.beans.binding.ObjectBinding.invalidate(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.binding.BindingHelperObserver.invalidated(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.beans.property.ObjectProperty.setValue(Unknown Source)
	at org.jabref@5.4.219/org.jabref.gui.StateManager.setSearchQuery(Unknown Source)
	at org.jabref@5.4.219/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.4.219/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.4.219/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException
	at org.jabref.merged.module@5.4.219/javafx.collections.transformation.SortedList.get(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.scene.control.TableView$TableViewSelectionModel.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.4.219/javafx.scene.control.MultipleSelectionModelBase$1.getModelItem(Unknown Source)
	at org.jabref.merged.module@5.4.219/com.sun.javafx.scene.control.SelectedItemsReadOnlyObservableList.get(Unknown Source)
	... 79 more`

</details>

**Comment by ThiloteE** [comment] 2021-09-24 13:16
Update: It don't think it was the `?` in the url field anymore. That error has been found and been dealt with here: #7882

**Comment by ThiloteE** [comment] 2021-09-24 13:33
For some reason I can't reproduce my error with the files that i uploaded in my first post here.

**Closed** 2022-04-25 23:21 UTC
