### ISSUE TITLE
Words specified as italic in title (Latex command) only appear as squares

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#2784] opened 2017-04-23 10:31 UTC
JabRef 4.0.0-dev--snapshot--2017-04-22--master--059f805e6
Windows 10 10.0 amd64 
Java 1.8.0_121

1. Format a word in the title field as being italic using the appropriate Latex command: `\textit{Wordinitalic}`
You can directly test this with the following example article entry:

```
@Article{Joe2018_Wordinitalic,
  author  = {Joe, E. I. AND Joe, O. A.},
  title   = {\textit{Wordinitalic}--and normal sentences},
  journal = {MyJournal},
  year    = {2018},
  volume  = {10},
  number  = {4},
  pages   = {118--121},
}
```

2. In the "main table/database view" the word in italic is replaced by squares. It is, however, properly displayed in the entry preview.

**Comment by Siedlerchr** [comment] 2017-04-23 11:52
Confirmed.  Btw, you have a` "{"` too much in the title

**Comment by AEgit** [comment] 2017-04-23 11:53
Ah yes, I've modified it accordingly - thanks for the heads up!

**Comment by lynyus** [comment] 2017-04-23 18:58
while this quite sure has to do with https://github.com/JabRef/jabref/pull/2752, I cannot confirm it under linux.

**Comment by Siedlerchr** [comment] 2017-04-23 19:46
I think it depends on the font and the style

Am 23.04.2017 8:58 nachm. schrieb "Linus Dietz" <notifications@github.com>:

while this quite sure has to do with #2752
<https://github.com/JabRef/jabref/pull/2752>, I cannot confirm it under
linux.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/JabRef/jabref/issues/2784#issuecomment-296479661>, or mute
the thread

**Comment by lynyus** [comment] 2017-05-04 11:38
So what should we do with this? Can we somehow narrow down on which configurations the problem occurs?

**Comment by AEgit** [comment] 2017-05-12 09:25
The problem still persists in:
JabRef 4.0.0-dev--snapshot--2017-05-09--master--78185153b
Windows 10 10.0 amd64 
Java 1.8.0_131

@lynyus : Can you tell me which configuration details you would need?

**Comment by lenhard** [comment] 2017-07-13 08:16
Sorry for not noticing this earlier.

I am all for reverting your changes in #2752 @lynyus It's not a fix if it breaks another feature. Before that change, you could have italics in the main table with the right font. Now, I can't find one that supports it.

We should find another of supporting ordinals, not one that breaks another feature.

**Comment by lynyus** [comment] 2017-07-13 14:06
Check my answer at the PR: https://github.com/JabRef/jabref/pull/2752#issuecomment-315086952

**Comment by stefan-kolb** [comment] 2018-02-06 15:29
Fixed in maintable-beta.

**Closed by stefan-kolb** 2018-02-06 15:29 UTC
Labels: bug, maintable, ui

**Comment by AEgit** [comment] 2018-02-06 15:48
I can confirm that this issue has been fixed in:

JabRef 4.2-dev--snapshot--2018-02-06--maintable-beta--40a9df31e
Windows 10 10.0 amd64 
Java 1.8.0_161

**Comment by bwakkie** [comment] 2022-10-26 08:26
Still the case in 5.8

**Comment by ThiloteE** [comment] 2022-10-26 10:38
follow up is #8522, please continue discussion over there.
