### ISSUE TITLE
Entry preview journal formats have disappeared

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5611] opened 2019-11-14 20:25 UTC
JabRef 5.0.0-dev--2019-11-14----8f7188d2d
Linux 5.3.0-23-generic amd64 
Java 13.0.1

1. Options/Preferences/Entry Preview
2. all the journal formats have disappeared (the "Available" window is empty)

![Screenshot from 2019-11-14 11-43-49](https://user-images.githubusercontent.com/762246/68893311-19982b80-06e2-11ea-8300-7e773b983fcd.png)

**Comment by Siedlerchr** [comment] 2019-11-18 13:22
They are still there, they just a moment to load and therefore to appear

**Comment by wujastyk** [comment] 2019-11-18 15:08
No, for me they do not appear even after several minutes.  The "Available"
window remains blank for as long as I am willing to wait.

**Comment by bernhard-kleine** [comment] 2019-12-12 17:00
JabRef 5.0-alpha--2019-12-07--673e53b
Windows 7 6.1 amd64 
Java 13.0.1

I do confirm the issue!

**Comment by Siedlerchr** [comment] 2020-02-20 15:34
Duplicate of #5622  (more info on the underlying problem there)
Only "Preview" works.
Currently the other citation styles only work when running JabRef from code and not when using the "built" version.

**Closed by Siedlerchr** 2020-02-20 15:34 UTC
Labels: entry-preview
