### ISSUE TITLE
"doct" in the bibtex key is converted to "d-{10}"

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3453] opened 2017-11-23 04:44 UTC
JabRef 4.1-dev--snapshot--2017-11-22--master--dd524ea06
Linux 4.10.0-40-generic amd64 
Java 1.8.0_151

This is extremely weird, and I don't know if it's me, JabRef or something else.

I have a standard way of building my bibtex keys: "first 4 chars of author"-"first four chars of title".  Thus, _Hamlet_ would have the bibtex key "shak-haml".

Many years ago I used to catalogue using the OCLC system, and their search key for a publication was this: four letters of author and four letters of title.  It's simple and works amazingly well as a unique identifier.  

I have a number of bib items that have "-doct" as the second part of their bibtex key.  

All these specific entries have been changed to "-d{10}", and the preceding entry type has been deleted.  

E.g.,

**@incollection{heil-doct,**
  author     = {Dory Heilijgers-Seelen},
  title      = {The Doctrine of the {Ṣaṭcakra} According to the {Kubjikāmata}},
  booktitle  = {The {Sanskrit} Tradition and Tantrism},
  date       = {1990},
  pages      = {56--65},
  crossref   = {goud-sans},
}

now appears in my file as 

**{heil-d{10},**
  author     = {Dory Heilijgers-Seelen},
  title      = {The Doctrine of the {Ṣaṭcakra} According to the {Kubjikāmata}},
  booktitle  = {The {Sanskrit} Tradition and Tantrism},
  date       = {1990},
  pages      = {56--65},
  crossref   = {goud-sans},
}

(bold highlighting by me).  

I said it was weird.  :-)

**Comment by lenhard** [comment] 2017-11-23 08:45
That sounds interesting :-) I tried, but cannot reproduce it on my machine. This will probably not happen during normal usage, but do you have any save actions with specific formatters enabled? But regardless of the replacement in the key, what should not happen is that the entry type is being removed. 

I guess we need more info on when this happens, otherwise it'll be hard to do anything. We also need more evidence that it was actually JabRef that has done this.

**Comment by Siedlerchr** [comment] 2017-11-23 09:34
Thething happening seems to be that Oct is interpreted as month and therefore replaced with 10 
Maybe it's a date formatter which is run on the bibtex key?

**Comment by Siedlerchr** [comment] 2017-11-23 16:02
Okay, I tried around with several cleanup ops and could not reproduce this behavior. So we need some more details. Maybe you could send us your bibfile to developers@jabref.org ?

**Comment by wujastyk** [comment] 2017-11-23 17:15
Yes I recently did do some experiments with Library Properties and "save
actions".  I didn't have success any of my attempts, for example to
reformat months (chars to numbers) or to capitalize titles.  So I gave up.
Jabref would just go into processing mode forever.

​

**Comment by Siedlerchr** [comment] 2017-11-29 17:18
I tried around with your bibfile and my sample file and I could not really reproduce this.
Regarding the save actions in general, you can also use the Cleanup actions, they are the same

**Comment by wujastyk** [comment] 2017-11-29 20:40
Thanks!
​

**Comment by matthiasgeiger** [comment] 2017-11-30 05:41
As it is not really reproducible, I suspect the problem occurred by the accidentially wrong usage of save actions. 

Thus I'll close this issue. Feel free to reopen if the problem occurs again.

**Closed by matthiasgeiger** 2017-11-30 05:41 UTC
Labels: waiting-for-feedback
