### ISSUE TITLE
Fonts are too small to read, inconsistent across the UI

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2885] opened 2017-06-05 14:18 UTC
The fonts used for entry table and entry editor editor are too small to read on my MS surface pro 4.  However, other fonts are bigger, and while still too small, are readable.  See screenshot

This is on JabRef 4.0.0-dev

![jr4tinyfonts](https://cloud.githubusercontent.com/assets/3851891/26787516/8f69b94c-4a0a-11e7-9f3d-aa1beea878ee.png)

**Comment by tobiasdiez** [comment] 2017-06-05 20:58
Unfortunately, there is not much we can do about this issue currently as we are in the process of switching to modern UI techniques and the current mix with the old code makes it hard to fix. Closed as a duplicate of https://github.com/JabRef/jabref/issues/2770.

**Closed by tobiasdiez** 2017-06-05 20:58 UTC
Labels: after-migration-to-javafx, enhancement, ui

**Comment by tobiasdiez** [comment] 2017-06-17 22:37
For Windows 10, there is work-around to get a workable resolution (I wouldn't call it nice through):

- Find and Right click `JabRef.exe` in the installation folder -> Properties
- Go to `Compatibility` tab
- Check `Override high DPI scaling behavior.`
- Choose `System` for `Scaling performed by`

**Comment by notuntoward** [comment] 2017-06-18 09:09
Thanks very much.  This makes the beta usable!
