### ISSUE TITLE
DOI import from Physical Review C missing page number

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#1603] opened 2016-07-18 23:38 UTC
JabRef version  on  3.5

Steps to reproduce:

1. click on world icon to import from DOI to BibTeX
2. Choose any DOI e.g. 10.1103/PhysRevC.93.064002
3. Click Fetch

Everything is imported except the article number. Physical review no longer has regular page numbers but an article number, which is used in place of page number in citing articles.
Thanks for the great program.

**Comment by lenhard** [comment] 2016-07-19 10:10
Thanks for your report! 

However, I think that the problem is on the side of the journal and not on JabRef. When I follow the DOI you gave above, I arrive at the following bibtex entry on export:
```
@article{PhysRevC.93.064002,
  title = {Testing semilocal chiral two-nucleon interaction in selected electroweak processes},
  author = {Skibi\ifmmode \acute{n}\else \'{n}\fi{}ski, R. and Golak, J. and Topolnicki, K. and Wita\l{}a, H. and Epelbaum, E. and Krebs, H. and Kamada, H. and Mei\ss{}ner, Ulf-G. and Nogga, A.},
  journal = {Phys. Rev. C},
  volume = {93},
  issue = {6},
  pages = {064002},
  numpages = {14},
  year = {2016},
  month = {Jun},
  publisher = {American Physical Society},
  doi = {10.1103/PhysRevC.93.064002},
  url = {http://link.aps.org/doi/10.1103/PhysRevC.93.064002}
}
```
In BibTeX, an article number is stored in the `number` field. If the journal exports data in the wrong BibTeX fields, there is nothing we can do.

Can a second person please re-check and close on confirmation?

**Comment by tobiasdiez** [comment] 2016-07-19 10:44
I can confirm the problem. If you fetch via JabRef's "DOI to BibTeX" then the pages field is empty. As @lenhard said if you go directly to the publisher website you get `pages = {064002}` (which is probably the expected format for PhysRevC)

**Comment by matthiasgeiger** [comment] 2016-07-19 11:22
I'm not big DOItoBibTeXFetcher expert but there is no bug here, as JabRef does not access the information provided at the page that is resolved after clicking the DOI but directly gets the BibTeX data from a the dx.doi.org service.

For the given DOI the result is this one:
```
$ curl -v -H "Accept: application/x-bibtex" http://data.crossref.org/10.1103%2FPhysRevC.93.064002
*   Trying 208.254.38.85...
* Connected to data.crossref.org (208.254.38.85) port 80 (#0)
> GET /10.1103%2FPhysRevC.93.064002 HTTP/1.1
> User-Agent: curl/7.41.0
> Host: data.crossref.org
> Accept: application/x-bibtex
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: X-Requested-With, Accept, Accept-Encoding, Accept-Charset, Accept-Language, Accept-Ranges, Cache-Control
< Access-Control-Expose-Headers: Link
< Link: <http://dx.doi.org/10.1103/physrevc.93.064002>; rel="canonical", <http://link.aps.org/article/10.1103/PhysRevC.93.064002>; rel="item"; version="vor", <http://link.aps.org/licenses/aps-default-license>; rel="license"; version="vor"
< Content-Type: application/x-bibtex
< Content-Length: 509
< Server: http-kit
< Date: Tue, 19 Jul 2016 11:20:05 GMT
< Connection: close
<
@article{Skibi_ski_2016,
        doi = {10.1103/physrevc.93.064002},
        url = {http://dx.doi.org/10.1103/PhysRevC.93.064002},
        year = 2016,
        month = {jun},
        publisher = {American Physical Society ({APS})},
        volume = {93},
        number = {6},
        author = {R. Skibi{\'{n}}ski and J. Golak and K. Topolnicki and H. Wita{\l}a and E. Epelbaum and H. Krebs and H. Kamada and Ulf-G. Mei{\ss}ner and A. Nogga},
        title = {Testing semilocal chiral two-nucleon interaction in selected electroweak processes},
        journal = {Phys. Rev. C}
}* Closing connection 0
```

-> No pages information

**Comment by sambo57u** [comment] 2016-07-19 13:50
Yes and no....I looked at the raw data for the article at crossref.org and it is somehow resolved incorrectly.
For example the raw data has "issue":"6" but had no "number" field. The issue shows up as number
in the curl pull. There is no "pages" field but a "article-number":"064002" field that is used as page in
citing. 

I will report this to the journal if you can clarify to me where the problem is. Thanks.
The raw data is below:

==========================
{"status":"ok","message-type":"work","message-version":"1.0.0","message":{"indexed":{"date-parts":[[2016,6,23]],"date-time":"2016-06-23T16:40:29Z","timestamp":1466700029974},"reference-count":63,"publisher":"American Physical Society (APS)","issue":"6","license":[{"content-version":"vor","delay-in-days":0,"start":{"date-parts":[[2016,6,22]],"date-time":"2016-06-22T00:00:00Z","timestamp":1466553600000},"URL":"http:\/\/link.aps.org\/licenses\/aps-default-license"}],"funder":[{"award":[],"doi-asserted-by":"publisher","name":"Chinese Academy of Sciences","DOI":"10.13039\/501100002367"},{"award":["SFB\/TR 16"],"doi-asserted-by":"publisher","name":"Deutsche Forschungsgemeinschaft","DOI":"10.13039\/501100001659"},{"award":["DEC-2013\/10\/M\/ST2\/00420","DEC-2013\/11\/N\/ST2\/03733"],"doi-asserted-by":"publisher","name":"Narodowe Centrum Nauki","DOI":"10.13039\/501100004281"}],"DOI":"10.1103\/physrevc.93.064002","type":"journal-article","created":{"date-parts":[[2016,6,23]],"date-time":"2016-06-23T15:05:18Z","timestamp":1466694318000},"source":"CrossRef","title":["Testing semilocal chiral two-nucleon interaction in selected electroweak processes"],"prefix":"http:\/\/id.crossref.org\/prefix\/10.1103","volume":"93","author":[{"affiliation":[],"family":"Skibi\u0144ski","given":"R."},{"affiliation":[],"family":"Golak","given":"J."},{"affiliation":[],"family":"Topolnicki","given":"K."},{"affiliation":[],"family":"Wita\u0142a","given":"H."},{"affiliation":[],"family":"Epelbaum","given":"E."},{"affiliation":[],"family":"Krebs","given":"H."},{"affiliation":[],"family":"Kamada","given":"H."},{"affiliation":[],"family":"Mei\u00dfner","given":"Ulf-G."},{"affiliation":[],"family":"Nogga","given":"A."}],"member":"http:\/\/id.crossref.org\/member\/16","published-online":{"date-parts":[[2016,6,22]]},"container-title":["Phys. Rev. C","Physical Review C"],"link":[{"intended-application":"syndication","content-version":"vor","content-type":"unspecified","URL":"http:\/\/link.aps.org\/article\/10.1103\/PhysRevC.93.064002"}],"deposited":{"date-parts":[[2016,6,23]],"date-time":"2016-06-23T15:11:18Z","timestamp":1466694678000},"score":1.0,"subtitle":[],"issued":{"date-parts":[[2016,6,22]]},"URL":"http:\/\/dx.doi.org\/10.1103\/physrevc.93.064002","ISSN":["2469-9985","2469-9993"],"article-number":"064002"}}

**Comment by matthiasgeiger** [comment] 2016-07-19 14:04
The "problem" is the conversion of the stored raw metadate you posted above to BibTeX. 

This conversion is not performed by JabRef, but by crossref itself. We are just querying the generated BibTeX for a DOI (which is the one posted by me above - you can also see the result directly in the web at http://search.crossref.org/?q=10.1103%2FPhysRevC.93.064002 after hitting the "Actions" -> "Cite" button).

The data is in most cases "good enough". Thus, (I think) we do not plan to implement an own solution to convert the crossref metadata to BibTeX.

**Comment by sambo57u** [comment] 2016-07-19 14:20
Thanks for the info.

**Comment by lenhard** [comment] 2016-07-19 14:28
We had this discussion on other occasions as well (Google scholar fetcher): We have to rely on publishers and indexing services to supply us with proper BibTeX entries.

If we start with screen scraping and implement custom solutions for certain publishers, we end up nowhere. Such code would certainly not be stable and we would have to fix it every time a publisher makes tiny changes to its format.

@sambo57u Thanks for following up! I will close this issue for now, since it is really a problem at crossref, and we are not going to tackle it at JabRef. But feel free to update the conversation, if you get a reply from crossref / the journal. It would be interesting to see if they intend to do something.

**Closed by lenhard** 2016-07-19 14:28 UTC
Labels: bug
