### ISSUE TITLE
Import into current libarary issues wrong message

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#6266] opened 2020-04-09 14:35 UTC
This is with version 5.1 (current).

When one chooses "import into current libary" from File-->Import menu and opens a
new bib file and go ahead with import you first get a message "import cancelled" and
a few seconds later "import complete". Import is done properly but the erreneous
message "import cancelled" should not be there.

**Comment by jcampbell11245** [comment] 2020-04-10 15:28
Hey! I am a first-time contributor. I have successfully reproduced this issue. May I take a stab at it?

**Comment by Siedlerchr** [comment] 2020-04-10 16:52
This is a duplicate of #4841. However, there is already a possible solution outlined in the combined:
of https://github.com/JabRef/jabref/issues/4841#issuecomment-486271379
@jcampbell11245  So feel free to take it! Please read the  [Contribution guidelines](https://github.com/JabRef/jabref/blob/master/CONTRIBUTING.md)

**Comment by jcampbell11245** [comment] 2020-04-10 17:02
Will do. Thank you!

**Comment by jcampbell11245** [comment] 2020-04-10 18:01
I attempted to implement the outlined solution but I believe changing the return type would require modifying the Dialog.java class, which I am unable to do because it is read-only.

**Comment by Siedlerchr** [comment] 2020-04-10 18:29
The idea is to modify the the return type of the importer class. You can modify the parameter in the extends clause

**Comment by jcampbell11245** [comment] 2020-04-10 18:54
Oh ok, I see now. Thank you.

**Closed** 2020-04-13 15:11 UTC
Labels: good first issue, import, t: bug 🐛, ui
