### ISSUE TITLE
Dark theme: Visibility problems with current colouring scheme (group colouring and scroll bars)

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#5522] opened 2019-10-26 21:30 UTC
JabRef 5.0.0-dev--2019-10-26----9fd49bcb2
Windows 10 10.0 amd64 
Java 12.0.2

The current colour scheme employed for the Dark Theme, has a few problems (see also https://github.com/JabRef/jabref/issues/5516). Among those are that the group colouration (indicating that the selected item was assigned to the coloured group) makes it sometimes impossible to see the number of assigned group items: Basically the green colour makes it impossible to see the underlying greyish to whitish colour of the item number.

Furthermore, the better visibility of scroll bars which was recently introduced (https://github.com/JabRef/jabref/issues/5374; https://github.com/JabRef/jabref/pull/5515) does not apply to the current dark theme (again due to the colouring scheme used for the scroll bars).

The following screenshots exemplify both problems. Maybe it would be worthwhile to have a separate label for problems that specifically just relate to the dark theme (since I reckon many users might not even be affected by them, since they use the default light theme).

![Untitled](https://user-images.githubusercontent.com/12767489/67626158-5093c380-f83f-11e9-860e-343469364b18.png)

![Untitled1](https://user-images.githubusercontent.com/12767489/67626176-9cdf0380-f83f-11e9-9a23-a89a80dac849.png)

**Comment by Siedlerchr** [comment] 2019-10-28 17:21
Preview Panel in OpenOffice styles needs also to be adapted.  Refs #5463 
Select  View -> OpenOffice/LibreOfice  ->  Select style

![grafik](https://user-images.githubusercontent.com/320228/67701004-6d4f0900-f9af-11e9-94e2-b08e0ed7de62.png)

**Comment by Siedlerchr** [comment] 2019-11-01 19:28
Preview in the preferences is also affected:

![grafik](https://user-images.githubusercontent.com/320228/68050724-12d2e700-fce6-11e9-9566-13f7458c6082.png)

**Comment by Siedlerchr** [comment] 2019-11-01 19:29
And there is another issue: Some textfields show the text with black color, but only white on hovering.
e.g. in the import tab

**Comment by tobiasdiez** [comment] 2019-11-24 19:02
Thanks to @ageofadz this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment] 2019-11-24 20:04
JabRef 5.0.0-dev--2019-11-24----8780a5632
Windows 10 10.0 amd64 
Java 13.0.1

While there have been changes, these have not addressed the issues reported here (completely):

1) The group colouration (indicating that the selected item was assigned to the coloured group) makes it still impossible to see the number of assigned group items. The colour has changed from green to greyish-white, but since the font colour is white, the numbers are still barely visible.

2) Similarly, the scroll bar is still basically invisible.

For 1) and 2) see:
![Untitled](https://user-images.githubusercontent.com/12767489/69500702-60153380-0ef5-11ea-8007-a0d833dd11f2.png)


3) The problem reported in https://github.com/JabRef/jabref/issues/5522#issuecomment-548920940 also persists.


It should be relatively (?) straight-forward to fix problem (1) and (2): Just use a different colour for the group colouration and the scroll bars and the problem should be solved. Problem (3) might involved a bit more coding (?).

**Comment by AEgit** [comment] 2019-11-24 20:10
Note, that there is another colouring problem. When you try to assign an item to a new group, using drag'n'drop, the respective group is coloured in pink, which also makes it nearly impossible to see the name of the group.

![Untitled2](https://user-images.githubusercontent.com/12767489/69500820-78398280-0ef6-11ea-8cda-6a753557b3b7.png)

**Comment by AEgit** [comment] 2019-11-25 19:40
@tobiasdiez I think this issue needs to be re-opened (see problems reported above).

**Comment by tobiasdiez** [comment] 2019-11-25 19:42
@ageofadz do you have time to create a follow-up PR, which also fixes the remaining issues? That would be great! Let me know in case you are hitting a wall and need help navigating the code (although by now you should know where to look more or less).

**Comment by calixtus** [comment] 2020-02-21 17:05
An overview of the solved problems:
fixed:
- merge dialog
- group indicator in the groups list
- preview panel in OO style selection

not yet fixed:
- OO manage citations dialog
- entry preview in preferences
- [textfields black/only on hover](https://github.com/JabRef/jabref/issues/5522#issuecomment-548921233)
- scrollbars (maybe on purpose not fixed?)
- drag'n'drop text on pink background

**Comment by mlep** [comment] 2020-02-21 17:30
Since you are in the process of improving the dark theme, you may also consider issue #5699.

**Comment by calixtus** [comment] 2020-02-21 17:42
No, I wasn't really fixing the dark theme right now, I was just doing a little bit housekeeping. Try'n'error with JavaFX CSS gives me always a headache.
But thanks for the note on the other glitch with the dialogs. This is probably a bit more complicated to fix.

**Comment by calixtus** [comment] 2020-02-21 17:45
@mlep If you like, you can give it a shot. If you are quick, we can probably include the fix in the 5.0 release.

**Comment by mlep** [comment] 2020-02-21 17:47
I would need to learn Java very quickly!  :wink:

**Comment by sambo57u** [comment] 2020-03-22 12:53
I love the dark theme but cannot use it since the scroll bar slider is not visible at all. This is with 5.0 and 5.1 (daily updated). Is this very hard to fix? Is there a way to define colors
for window elements externally? Thanks

**Comment by sambo57u** [comment] 2020-04-19 21:06
Still persists...such a pitty that the beautiful dark theme is unusable due to the invisible scroll bar. I am not a java programmer but is this really that difficult to fix?

**Comment by Siedlerchr** [comment] 2020-04-19 21:16
@sambo57u You don't have to be a java programmer. It's just styling via css. The base theme:
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/Base.css

The dark theme:
https://github.com/JabRef/jabref/blob/eccfb577b7dc29e55ece8acbfe02bf6895408e39/src/main/java/org/jabref/gui/Dark.css

CSS Reference Guide.
https://openjfx.io/javadoc/13/javafx.graphics/javafx/scene/doc-files/cssref.html

**Comment by sambo57u** [comment] 2020-04-20 12:53
Sorry, I am 62 year old user. All this stuff is unfamiliar to me. I had seen a related issue to
this earlier #5646.

**Comment by tobiasdiez** [comment] 2020-04-28 12:25
Thanks to @MootezSaaD the dark theme got some love and many issues are now fixed. In particular, the scrollbar should be now more visible. 

I've updated https://github.com/JabRef/jabref/issues/5522#issuecomment-589744221 accordingly.

**Comment by Siedlerchr** [comment] 2020-06-13 13:36
Thanks to @dextep  the Preview in the preference is now also fixed. 
From the comment this leaves us with:
 
- [ ] OO manage citations dialog 
- [ ] [textfields black/only on hover](https://github.com/JabRef/jabref/issues/5522#issuecomment-548921233)

**Comment by dextep** [comment] 2020-06-13 14:02
> And there is another issue: Some textfields show the text with black color, but only white on hovering.
> e.g. in the import tab

Can you explain how to reproduce this issue?

**Comment by dextep** [comment] 2020-06-13 14:14
OO manage citations dialog seems to be also done

![image](https://user-images.githubusercontent.com/20928760/84570990-de9dc980-ad90-11ea-9583-98824acb5fdf.png)

**Comment by Siedlerchr** [comment] 2020-06-13 14:18
@dextep  Yes, thanks, the style selection was probably fixed with your preview changes.

The only other dialog is Manage citations:
1. Open new Libre Office writer document
2 Connect to LibreOffice from JabRef
3. Insert some citations/references
4.Open Manage citations

The relevant code is here:
https://github.com/JabRef/jabref/blob/8520833e684aa9e305dd8745e45696ffd6d984fb/src/main/java/org/jabref/gui/openoffice/ManageCitationsDialogView.java#L79-L91



![grafik](https://user-images.githubusercontent.com/320228/84571005-0c830e00-ad91-11ea-8f97-3bb436ccb06a.png)

**Comment by AEgit** [comment] 2020-06-13 14:39
JabRef 5.1--2020-06-13--be30871
Windows 10 10.0 amd64 
Java 14.0.1

Cheers for the improvements. Well done!

Note, however, that the issue with the group coloration and the item number persists, if an item is assigned to a new group (https://github.com/JabRef/jabref/issues/5522#issuecomment-557922759), i. e. you get a grey background colour with a white item count.

Furthermore, the current chosen colour to reflect group assignment (which works, if items are NOT assigned to new groups), is difficult to discern in the dark theme, especially if the item count is turned off. You basically have an olive-brownish colour indicating group assignment on a dark background. While I appreciate this was done to follow certain style guidelines (?), it makes it difficult to see whether an item belongs to a group or not. A more prominent colour should be chosen instead.

**Comment by dextep** [comment] 2020-06-13 17:55
@Siedlerchr unfortunately I can't connect JabRef with OpenOffice, because connecting process doesn't stop.

**Comment by Siedlerchr** [comment] 2020-06-13 18:04
You need at least Version 5.x or newer of Libre Office. And you need to open a (new). document in writer 
For Linux you need libre office common Java library

**Comment by calixtus** [comment] 2020-06-13 18:05
refs #6353 #6562

**Comment by dextep** [comment] 2020-06-14 21:51
@Siedlerchr i have question, how should i set text color here? via .setStyle() and check if the black theme is enabled from `JabRefPreferences` ? 


https://github.com/JabRef/jabref/blob/8520833e684aa9e305dd8745e45696ffd6d984fb/src/main/java/org/jabref/gui/openoffice/ManageCitationsDialogView.java#L79-L91

**Comment by AEgit** [comment] 2020-12-17 16:10
JabRef 5.2--2020-12-14--e9be339
Windows 10 10.0 amd64 
Java 14.0.2

The issues mentioned in https://github.com/JabRef/jabref/issues/5522#issuecomment-643632385 persist in the current dev version.

**Closed** 2021-03-17 11:50 UTC
Labels: good first issue, ui

**Comment by AEgit** [comment] 2021-03-17 15:29
JabRef 5.3--2021-03-17--d190268
Windows 10 10.0 amd64 
Java 14.0.2 
JavaFX 16+8

As far as I can tell, all issues mentioned in https://github.com/JabRef/jabref/issues/5522#issuecomment-643632385 have been fixed. Well done!

Note, however, that the issue mentioned in https://github.com/JabRef/jabref/issues/5522#issuecomment-643632385 still persists:

>Furthermore, the current chosen colour to reflect group assignment (which works, if items are NOT assigned to new groups), is difficult to discern in the dark theme, especially if the item count is turned off. You basically have an olive-brownish colour indicating group assignment on a dark background. While I appreciate this was done to follow certain style guidelines (?), it makes it difficult to see whether an item belongs to a group or not. A more prominent colour should be chosen instead.

Below a provide a screenshot to visualize this problem:
![Untitled](https://user-images.githubusercontent.com/12767489/111493567-f6e6ae80-873d-11eb-9b8c-05cfcd3e4057.png)
