### ISSUE TITLE
Group selection underline not immediate

### ISSUE THREAD

**Issue by HainesB** [JabRef/jabref#1122] opened 2016-04-06 16:22 UTC
In  older versions, when I put a new entry into a group, the group name was immediately underlined. Now to get the underline and thus assurance the item was in fact entered into the group, I have to click on that group and then All Entries. The older behavior is much preferable.

**Comment by simonharrer** [comment] 2016-05-10 11:30
Ah, I think mistook it as a duplicate of #934, but I now think this was wrong. 

Steps to reproduce this issue
1. add an entry to a group
2. groups window does not show membership (is not being updated)

**Closed** 2016-05-19 09:50 UTC
Labels: bug, ui
