### ISSUE TITLE
Incorrect count entry number

### ISSUE THREAD

**Issue by Ali96kz** [JabRef/jabref#4441] opened 2018-10-31 10:16 UTC
1. File -> (New Bibtex library) or (New Biblatex library)
2. Add some entry 
Number of entry will be 0. 
![image](https://user-images.githubusercontent.com/15236829/47781510-0ceba400-dd28-11e8-9293-dab196344bc5.png)

**Comment by AEgit** [comment] 2018-11-01 18:54
Is it always an incorrect number, or does this only happen the first time you assign a item to a new group? I noticed this behaviour before, but as far as I remember you get the correct numbers of items contained in a group, if you save and close JabRef and then reopen it.
This is still, obviously, a bug, but a less serious one, I guess - it is basically the updating process of the groups panel, that does not work properly (which I think is also responsible for some other issues we see with the groups panel).

**Comment by Siedlerchr** [comment] 2018-11-02 21:48
Sometimes the number update if you switch to another db and then back again.

**Comment by CaptainDaVinci** [comment] 2019-03-21 14:02
However, on switching to another library, group count shows count of previous library.

**Comment by tobiasdiez** [comment] 2019-03-22 10:25
Thanks for investigating this issue. This is how it is supposed to work:
- Whenever a library get's the focus, convert the group tree to a tree of `GroupNodeViewModel`s.
https://github.com/JabRef/jabref/blob/6c61664a8f715e4011064ddca5cb0ace0b803131/src/main/java/org/jabref/gui/groups/GroupTreeView.java#L108-L113
- Bind the value of the `hit` property to the text field
https://github.com/JabRef/jabref/blob/6c61664a8f715e4011064ddca5cb0ace0b803131/src/main/java/org/jabref/gui/groups/GroupTreeView.java#L137
- Whenever there are changes to the library, update the hit count (which should then propagate to the text label through the above binding)
https://github.com/JabRef/jabref/blob/6c61664a8f715e4011064ddca5cb0ace0b803131/src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java#L86-L87
https://github.com/JabRef/jabref/blob/6c61664a8f715e4011064ddca5cb0ace0b803131/src/main/java/org/jabref/gui/groups/GroupNodeViewModel.java#L216-L218

So it sound's reasonable that there is a problem with the binding of the text label to the correct hits property.

**Comment by samiyac** [comment] 2019-03-22 22:31
I think the problem might also be concerned with `databaseContext.getDatabase().getEntries().addListener(this::onDatabaseChanged); `
I added a print statement inside the function `onDatabaseChanged` and it didn't print anything after a few entries were added.

This is also related to issue [#4679](https://github.com/JabRef/jabref/issues/4679). I found that the same problems occurs when I added entries by dragging them.

**Comment by samiyac** [comment] 2019-03-24 15:21
@tobiasdiez and @Siedlerchr Why do we have the All Entries group available when no library has been opened in JabRef? It doesn't seem to serve any function.

**Comment by tobiasdiez** [comment] 2019-03-25 23:00
You are right the "All Entries group" should only be shown when there is an open library.

**Comment by stefan-kolb** [comment] 2019-06-11 22:34
The value should also be updated if the library is closed which also does not happen right now.

**Comment by stefan-kolb** [comment] 2019-08-26 21:35
See https://github.com/JabRef/jabref/issues/3142. Will probably fix both of the issues.

**Comment by tobiasdiez** [comment] 2019-09-16 19:22
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed** 2019-09-16 19:22 UTC
Labels: bug, groups, ui

**Comment by AEgit** [comment] 2019-09-17 08:47
JabRef 5.0-dev--snapshot--2019-09-16--master--1bec5efd3
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft

As far as I can tell, this issue appears to be fixed in the current developer version of JabRef. Thank you very much!

What I do note, however, is that assigning articles to new groups creates a massive CPU workload (always around 95%-100% CPU workload on a 6-core Core i7). This CPU workload takes several minutes to disappear. I do not know, however, whether this issue is related to the current fix or if it is just related to the general performance problems, that JabRef has at the moment (see https://github.com/JabRef/jabref/issues/5071).

**Comment by AEgit** [comment] 2019-09-17 08:56
Follow-up: Note also, that the group entry count number is updated immediately, when an item is assigned to a new group. But the colour indicating the group assignment is not. The colouring of the group affinities is only updated if you select another item in the main table or another group in the panel and then re-select the newly assigned item.
As you can see, this is not a major issue, but I wanted to report it (see also here: https://github.com/JabRef/jabref/issues/3112#issuecomment-433878012).

**Comment by tobiasdiez** [comment] 2019-09-17 09:59
Thanks for the feedback. I'll try to improve the performance in the coming weeks but first I wanted to fix as much bugs as possible. Please open another issue for the coloring problem.

**Comment by AEgit** [comment] 2019-09-17 10:47
I just realised that I had reported the colouring issue before. See here:
https://github.com/JabRef/jabref/issues/3112

and (similar but not the same) here:
https://github.com/JabRef/jabref/issues/2857

Thank you very much for your continuous work on JabRef!

**Comment by Siedlerchr** [comment] 2019-09-17 13:30
@AEgit Did you encounter by chance this issue after the latest fix? #5327

**Comment by AEgit** [comment] 2019-09-17 17:04
@Siedlerchr Sorry for taking so long. See my reply here: https://github.com/JabRef/jabref/issues/5327#issuecomment-532310470

No, I cannot reproduce the issue you reported.

**Comment by Siedlerchr** [comment] 2019-09-17 18:29
Okay thanks for the info. Will test it again on another computer
