### ISSUE TITLE
Opening BibTex file (doubleclick) from Folder with spaces not working

### ISSUE THREAD

**Issue by cpsychal** [JabRef/jabref#6487] opened 2020-05-16 17:37 UTC
When double click a BibTeX file in the file browser, then JabRef opens with message “File not found”.
The file opens only through the menu of Jabref: File–> Open…
That happens after the last upgrade.

**Comment by mrjoposranchik** [comment] 2020-05-18 14:03
Same problem, Windows 10, Jabref v5.0 cannot open .bib files with double-click. Only "File->Open" or drag-n-drop*.
Surprisingly, double-click always works if file is located on desktop (discovered by accident)!
Not opening behaviour depends on whether JabRef application was already launched or not when trying to open with double click:
1) not launched => I get an error message 
"Error opening file 'filename.bib'. 
File not found"
2) launched => I get NO error message and TWO tabs appear:
first one called "untitled", second called "filename.bib", but both are empty ("no content in table")

(*) Maybe this should be a separate issue, but opening by drag-n-drop also has a problem, it works only if I drag file in the panel with tabs (see the screenshot below):
![image](https://user-images.githubusercontent.com/18900780/82221065-c8caef00-991f-11ea-81c3-95d3e6f899e4.png)
It means that I need to have at least one file already opened, otherwise there is no panel with tabs and this method will not work. 
![image](https://user-images.githubusercontent.com/18900780/82221552-72aa7b80-9920-11ea-9209-91fee71ede32.png)

**Comment by RickVandoorne** [comment] 2020-05-19 12:13
I have the exact same problem. I am also running Windows 10 and have the same behaviour as @mrjoposranchik and @cpsychal.

**Comment by Siedlerchr** [comment] 2020-05-19 12:25
Regarding Drag and Drop: I think the Drag and drop listener is installed on the tab bar. That would explain at least the opening of files.  Must be probably moved to JabRefFrame or so.

**Comment by Siedlerchr** [comment] 2020-05-19 16:39
Doube clicking on a bib file works and opens JabRef fine in the latest development version
@cpsychal  Can you please give us a bit more details, e.g. which OS you are using and if you have tested the latest development version?

**Comment by cpsychal** [comment] 2020-05-19 16:46
JabRef 5.0--2020-03-06--2e6f433

Windows 10 10.0 amd64 

Java 13.0.2

 �

 �

**Comment by RickVandoorne** [comment] 2020-05-19 19:28
> Doube clicking on a bib file works and opens JabRef fine in the latest development version
> @cpsychal Can you please give us a bit more details, e.g. which OS you are using and if you have tested the latest development version?

The behaviour I experience is that JabRef opens but it gives an error message. One can close this error message and the application does not close, but it does not load the bib file. One then has to go and open the bib file from within JabRef.

![Error](https://user-images.githubusercontent.com/41417622/82369460-5a695800-9a17-11ea-8505-e17980804a1f.png)

**Comment by Siedlerchr** [comment] 2020-05-21 17:57
The drag and drop should be fixed by @MootezSaaD  now in the latest development version:
https://builds.jabref.org/master/

Please remember to make a backup of your library before trying out the new version.

**Comment by mrjoposranchik** [comment] 2020-05-21 18:33
> Doube clicking on a bib file works and opens JabRef fine in the latest development version
> @cpsychal Can you please give us a bit more details, e.g. which OS you are using and if you have tested the latest development version?

I was checking the previous dev version for 5 minutes when a new update appeared.
In the previous version double click opened a .bib file for me once, but only for the case when app was not started. After that with running app double click resulted in a single "untitled" tab. (I didn't investigate much)
In the latest development version double click doesn't work. If app was not running - empty JabRef window opens. If app was already running - "untitled" tab.
If file is on the desktop - it works in both cases! (Why? Is it true for other people with the same issue?)

Drag and drop works well now! Thank you, @MootezSaaD !

**Comment by Siedlerchr** [comment] 2020-05-21 19:06
Could you please completey uninstall JabRef and then reinstall the new version? It might that the file asociation is somewhat broken

**Comment by RickVandoorne** [comment] 2020-05-21 19:20
I have completely uninstalled JabRef and installed the latest development version at   [https://builds.jabref.org/master/](url). This is the behaviour I get now:

- If I double click on a .bib file while JabRef is NOT running then JabRef opens (it no longer gives me the error message). However, it does not open the file which I double clicked.

- If I double click on a .bib file while JabRef is running it opens a new library called "untitled" but not the file I double clicked.

- If I open JabRef first and then open a file using "File" → "Open library" it works fine.

**Comment by mrjoposranchik** [comment] 2020-05-21 19:29
> I have completely uninstalled JabRef and installed the latest development version at [https://builds.jabref.org/master/](url). This is the behaviour I get now:
> 
> * If I double click on a .bib file while JabRef is NOT running then JabRef opens (it no longer gives me the error message). However, it does not open the file which I double clicked.
> * If I double click on a .bib file while JabRef is running it opens a new library called "untitled" but not the file I double clicked.
> * If I open JabRef first and then open a file using "File" → "Open library" it works fine.

It seems that we have exactly the same symptoms. However, I didn't try to reinstall from scratch yet. May I kindly ask you to try to place a .bib file on Desktop and open it with double-click to confirm or disprove that Desktop location is somewhat special?

**Comment by RickVandoorne** [comment] 2020-05-22 06:29
I tried opening a .bib file directly on the desktop but the behaviour I get is exactly the same as with a .bib file placed elsewhere on the system. So I don't seem to get the special behaviour you described @mrjoposranchik .

**Comment by thanaset** [comment] 2020-05-27 16:53
Same issue here. 

JabRef version 5.0 on Windows 10

Opening .bib files from within JabRef is fine but clicking on a .bib file in Windows Explorer results in a blank page on JabRef.

Steps to reproduce the behaviour: double click on a .bib file icon.

**Comment by ihesham** [comment] 2020-06-03 15:37
> Same issue here.
> 
> JabRef version 5.0 on Windows 10
> 
> Opening .bib files from within JabRef is fine but clicking on a .bib file in Windows Explorer results in a blank page on JabRef.
> 
> Steps to reproduce the behaviour: double click on a .bib file icon.

Same issue above

**Comment by Siedlerchr** [comment] 2020-06-03 16:32
I have exported my Windows 10 registry settings for the file association and open with application.
While I have the dev version installed it should theoretically also work with the 5.0
It assumes that JabRef is installed under C:\Program Files\JabRef 
Just remove the .txt file extension and execute it 

WARNING: TRY AT YOUR OWN RISK
[jabref_fileassociation.reg.txt](https://github.com/JabRef/jabref/files/4724736/jabref_fileassociation.reg.txt)

**Comment by mr-j-s** [comment] 2020-06-03 17:42
> I have exported my Windows 10 registry settings for the file association and open with application.
> While I have the dev version installed it should theoretically also work with the 5.0
> It assumes that JabRef is installed under C:\Program Files\JabRef
> Just remove the .txt file extension and execute it
> 
> WARNING: TRY AT YOUR OWN RISK
> [jabref_fileassociation.reg.txt](https://github.com/JabRef/jabref/files/4724736/jabref_fileassociation.reg.txt)

Tried that, didn't fix the issue with double-click.

**Comment by mr-j-s** [comment] 2020-06-03 18:10
I think I noticed something important:
double-click works for me not only from Desktop, but also from D:\biblio.bib and even e.g. D:\1\biblio.bib or D:\a\biblio.bib
BUT
if I try to open "D:\1 1\biblio.bib", it fails as usual (there is a space in the folder name)
I tried to replace al the spaces with underscores in the path to one of my .bib files and it also started to work.
Finally, I renamed it from "biblio.bib" to "bib lio.bib" and it started to fail again.
So any space in the path to file breaks it.

I hope this info will help to fix the issue!

**Comment by RickVandoorne** [comment] 2020-06-10 05:56
I did a test and got the same behavior as @mr-j-s . 

If the file path to the ".bib" file has any spaces in it at any point, then when double clicking on the ".bib" file JabRef opens to a blank page, but it does not open the ".bib" file itself.

If there are no spaces in the file path. Then JabRef opens the ".bib" file as would be expected.

This file path did **not** work: "D:\New Folder\References.bib"
This file path did work: "D:\References.bib"

**Comment by RickVandoorne** [comment] 2020-06-10 05:58
> I tried opening a .bib file directly on the desktop but the behaviour I get is exactly the same as with a .bib file placed elsewhere on the system. So I don't seem to get the special behaviour you described @mrjoposranchik .

I have a space in the path to my desktop which explains why this did not work for me earlier.

**Comment by Siedlerchr** [comment] 2020-06-10 06:29
I could reproduce this as well using a space in the folder. I checked the registry,, there the open with is correctly wrapped in spaces. Maybe an issue with our commandline parser

**Comment by zongxian** [comment] 2020-07-10 07:44
If the path contains Chinese characters, it will have the same error.

**Comment by sbubin** [comment] 2021-01-05 04:35
Same issue. Jabref 5.2 on Windows 10. Cannot open a bib file by double clicking on it when the full path of that file contains spaces. If is is copied to a location with no spaces in the path then it works fine. I hope this bug gets fixed soon as I remember experiencing this annoying behavior of Jabref for quite some time.

**Comment by XDZhelheim** [comment] 2021-03-17 10:41
I'm trying to fix this. Got some clues already.

**Comment by tobiasdiez** [comment] 2021-03-19 12:27
Thanks to @XDZhelheim this should now finally be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed** 2021-03-19 12:26 UTC
Labels: good first issue, type: bug 🐛
