### ISSUE TITLE
Open pdf file when clicking pdf icon

### ISSUE THREAD

**Issue by BTWS** [JabRef/jabref#498] opened 2015-12-10 09:55 UTC

**Comment by lenhard** [comment] 2015-12-10 10:17
... is working fine.

Seriously, you expect us to invest our time for free on something, but don't bother to provide more description than a single sentence? If you can't be bothered with error diagnosis, why should we?

**Comment by BTWS** [comment] 2015-12-10 10:32
I'm sorry. I enabled the "Show PDF/PS- column" in "Entry table columns". In "General" under "File", I add my pdf document. This shows a pdf icon with a magnifying glass in it. When i click this icon the pdf file doesn't open. I also can't sort on files with/without pdf file attached.

**Comment by lenhard** [comment] 2015-12-10 10:47
Thanks, that is something we can work with.

Do you mean the icon marked here?
<img src="https://cloud.githubusercontent.com/assets/1515701/11713287/c025a9b2-9f32-11e5-8748-8c85b4a573e3.png" width="200" height="400" />
As the tooltip says, this is not supposed to open the pdf file, but tries searching for it. You can open the pdf by clicking the pdf icon in the entry table.

**Comment by BTWS** [comment] 2015-12-11 11:03
I mean the symbol next to "InProc..." and "Article" in your image. I enabled the "Show one letter heading for icon columns" and the icon is under the letter "P". The tooltip says "Open PDF".

![image](https://cloud.githubusercontent.com/assets/16107991/11742288/f8a1a454-9ffe-11e5-85e8-ee2837c20ff9.png)

The icon becomes selected, but the pdf doesn't open.

**Comment by lenhard** [comment] 2015-12-11 11:23
Thanks, I can reproduce this. Propably, this is due to pdf/ps fields being no longer supported, but not yet fully banished from the UI. This will be fixed with #452

Could you try to select Options -> Preferences -> Entry Table Colums -> Check "Show file column"?
Then, another column should appear with the PDF icon and this should open on click (at least it does for me). If it does, you could even deselect "Show PDF/PS column" in the preferences.

**Comment by BTWS** [comment] 2015-12-11 11:29
Selecting **Show file column** instead of *Show PDF/PS-column* solved my issue. Thank you.

**Comment by lenhard** [comment] 2015-12-11 11:40
Good to hear! I'll leave this issue open as a reminder until we have resolved the UI.

**Closed** 2015-12-15 10:39 UTC
Labels: bug, ui
