### ISSUE TITLE
Automatically set file links not working

### ISSUE THREAD

**Issue by PierreMarchand20** [JabRef/jabref#3629] opened 2018-01-11 11:12 UTC
I am on macOS with JabRef 4.1 and automatically setting file links is not working anymore. I noticed it since I have done the last update. There is nothing appearing in the event log when I click on the button "Automatically set file links for this entry".

**Comment by lenhard** [comment] 2018-01-11 12:50
Probably related #3626

**Comment by felker** [comment] 2018-02-15 19:28
The functionality seems to work well on macOS High Sierra with JabRef 3.8.2 and JDK build 1.8.0_162-b12. 

My current workflow for managing my BibTex database involves switching from JabRef 3.8.2 to "Automatically set file links", to JabRef 4.1 or 4.2 to add new entries via DOI since #2879 was never patched in 3.8.2.

**Comment by lenhard** [comment] 2018-02-16 08:03
Just to make sure that there are no misunderstandings here: We are definitely not going to backport functionality to old releases. The effort for this is simply not justifiable given the size of the development team and the amount of work to do.

You can do it yourself, of course, after all JabRef is open source.

**Comment by felker** [comment] 2018-02-16 14:12
@lenhard yes of course. I am waiting until 4.2 fixes the "Automatically set file links" and then I will just use that. 

I have been getting acquainted with the JabRef codebase over the last mont since switching from Mendeley, and I am definitely planning to contribute when my Java gets up to speed!

**Comment by bruot** [comment] 2019-04-25 08:13
What is the status of this issue? It does not work for me with the latest snapshot and just keeps showing the "Searching for files" progress window:

Steps to reproduce the behavior:
1. java -jar JabRef-5.0-dev--snapshot--2019-04-22--master--8e0ffe11d.jar --prdef all -n
2. Set the main file directory to a folder containing a file "file.pdf".
3. Create a DB, add an entry and set its key to "file".
4. Select the entry and press F7.

The problem exists for all the search file options: "Autolink files with names starting with the BibTeX key", "Autolink only files that match the BibTeX key" and "Use regular expression search" (with the default regexp).

JabRef version 5.0-dev--snapshot--2019-04-22--master--8e0ffe11d on Windows 7 6.1 amd64 with Java 1.8.0_211

**Comment by stefan-kolb** [comment] 2019-08-24 23:31
Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Closed by stefan-kolb** 2019-08-24 23:31 UTC
Labels: macOS

**Comment by PierreMarchand20** [comment] 2019-08-25 14:50
How can I run the lastest build ? I have the last version of JDK, but I get
```
Error: Could not find or load main class org.jabref.JabRefMain
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

**Comment by Siedlerchr** [comment] 2019-08-25 14:52
You need still Java 8 to run the build.
Java 11 support is nearly ready

**Comment by PierreMarchand20** [comment] 2019-08-25 14:54
So I have to downgrade java ? My version:
```
java version "12" 2019-03-19
Java(TM) SE Runtime Environment (build 12+33)
Java HotSpot(TM) 64-Bit Server VM (build 12+33, mixed mode, sharing)
```

**Comment by Siedlerchr** [comment] 2019-08-25 15:00
Yes. You need Java 8 or you wait until Java 11 support (see the Pull request) is merged.
