### ISSUE TITLE
Group badges don't update after assignment

### ISSUE THREAD

**Issue by Krzmbrzl** [JabRef/jabref#5561] opened 2019-11-03 11:40 UTC
JabRef 5.0.0-dev--2019-10-25----681d6aa6f
Linux 5.0.0-32-generic amd64 
Java 12.0.2

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Add new entry that is not in any group
2. Manually assign a group to the entry via drag&drop onto an existing group
3. In the entry list, the groups-column is not updated for the newly grouped entry. I have to explicitly switch the displayed group in order for the entry list to refresh and show the group badges (the color stripes) for the new entry. Alternatively a restart does the same.

Thus the entry gets added to that group just fine. It's just the entry list that doesn't get updated on this

**Comment by calixtus** [comment] 2020-02-16 14:20
I have tested this behaviour, the group badge updates after about one second.
@Krzmbrzl, would you please do me the favor to test this issue in JabRef with the latest dev version again and to tell, if something changed?

**Comment by Krzmbrzl** [comment] 2020-02-17 11:52
I don't have my Linux system at hand right now, so I tested it on Windows using
```
JabRef 5.0-beta.421--2020-02-14--ec93ad3
Windows 7 6.1 amd64 
Java 13.0.2
```
and the problem persists.

What does get updated is the number next to the group indicating how many members are in it, but the color-badge in the entry list does not get updated until I switch the displayed group so that the entry list gets updated.

Here are some screenshots illustrating what I mean.
Before switching the displayed group:
![Jabref_Group_notShown](https://user-images.githubusercontent.com/12751591/74651500-3bdb9280-5184-11ea-9754-546ded1b8d58.png)

and after having switched the displayed group (I also switched back but the badge appears on the first switching):
![Jabref_Group_shown](https://user-images.githubusercontent.com/12751591/74651541-50b82600-5184-11ea-833f-7ec208208088.png)

**Comment by calixtus** [comment] 2020-02-17 11:54
Thank you for clearifying. Im looking into this issue.

**Comment by calixtus** [comment] 2020-02-20 22:50
I root of the problem is somewhat similar to what is fixed in #5925. But not quite exactly.
The dataset is updated correctly, but the maintable is not updated. Affects both the groups column and the uri column. I did not test the file column, but I'd bet on it. @tobiasdiez as a good insight in the JabRef data model. Maybe he's got an idea?

**Comment by tobiasdiez** [comment] 2020-02-21 12:04
I think the problem is in this method:
https://github.com/JabRef/jabref/blob/cc94cca00d48004e3678ff4603f361129cdd9e23/src/main/java/org/jabref/gui/maintable/BibEntryTableViewModel.java#L66-L81
A observable value is returned, but this one is static and doesn't change if the underlying data in the entry changed (or the groups for that matter).

**Comment by tobiasdiez** [comment] 2020-02-22 13:59
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed** 2020-02-22 13:59 UTC
Labels: groups, maintable, ui

**Comment by Krzmbrzl** [comment] 2020-02-22 14:50
The problem persists in
```
JabRef 5.0-beta.457--2020-02-22--d38f813
Windows 7 6.1 amd64 
Java 13.0.2
```

**Comment by calixtus** [comment] 2020-02-22 15:02
It's possible you were too quick for us. 😄 After merging, the build server takes about an hour to upload the latest build to builds.jabref.org.

**Comment by Krzmbrzl** [comment] 2020-02-22 15:31
I was too quick at first. Then I waited for the CI to complete and downloaded it again. Also you can see from the commit-hash that it is indeed the build that is currently up-to-date with the master-branch :)
