### ISSUE TITLE
custom entry types can not be added/edited

### ISSUE THREAD

**Issue by DrFelder** [JabRef/jabref#5099] opened 2019-07-03 09:03 UTC
JabRef version JabRef-5.0-dev [(current build)](https://builds.jabref.org/master/JabRef-5.0-dev--snapshot--2019-07-01--master--a50cb3497.jar)  on  macOS Mojave 10.14.4

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists (actually, the standard build works just fine in this regard)

The option that lets the user add/edit custom entry types is missing.
The expected behaviour is described in http://help.jabref.org/en/CustomEntryTypes

1. download [the current build](https://builds.jabref.org/master/JabRef-5.0-dev--snapshot--2019-07-01--master--a50cb3497.jar)
2. try to add/edit custom entry types, follow [the instructions](http://help.jabref.org/en/CustomEntryTypes)

Is there a way to "quick-fix" this issue? I need my custom types to work, and I had to switch to the 5.0 version, bc the current 4.3 build is extremely slow and has some very annoying problems (that are already described in other issues).
Are the custom file types saved to a file or something, where I can edit them manually?

**Comment by tobiasdiez** [comment] 2019-07-03 10:22
Duplicate of #4719 

You can use an older JabRef version (e.g. 3.4.1) to customize the entry types and then use the customized types in the new 5.0 version (only the customization dialog was temporarily removed, not the functionality). Sorry for the inconvenience.

**Closed by tobiasdiez** 2019-07-03 10:22 UTC

**Comment by DrFelder** [comment] 2019-07-03 11:34
Sorry for the duplicate, I searched through the issues but didnt find it.
How can I re-use the customized entries? Are they only defined in the .bib file?
My file contains the line `@Comment{jabref-entrytype: Url: req[author;title;note;year;url] opt[]}` but I still don't have the option to create a URL entry.
Do I need to use the macOS-Application or will this work with the .jar?
