### ISSUE TITLE
Google Scholar search randomly stopped working

### ISSUE THREAD

**Issue by jeremyherbert** [JabRef/jabref#2156] opened 2016-10-12 10:21 UTC
JabRef version 1.8.0_101 on OSX Yosemite. All google scholar search requests fail. The log shows that a 503 occurred at the following URL:

    http://ipv4.google.com/sorry/index?continue=http://scholar.google.com/scholar...

If you go to this URL, it asks you to fill in the captcha, then goes to the scholar page. Is there any way that this page can be shown to the user, so that they can just enter the captcha and continue working?

FWIW, I haven't used jabref in a few weeks, so I'm pretty sure something that jabref is doing is directly triggering the problem. Scholar works fine on all of my browsers otherwise. #2046 says that MAC addresses are banned, but this doesn't seem to be the case; you just need to fill the captcha. Also, as I mentioned before, I haven't used jabref in a while so I'm not sure how they proactively blacklisted my IP/MAC ;)

**Comment by matthiasgeiger** [comment] 2016-10-12 11:06
Hi!
I suppose that you are using the version 3.6 (or earlier) of JabRef.
Due to changes at the side of google the fetcher does no longer work with this versions (an invalid page is accessed which causes the blocking). See also #1886 for an older issue report regarding this issue.

The problem is fixed in current development builds which you can get here: https://builds.jabref.org/master

**Closed by matthiasgeiger** 2016-10-12 11:06 UTC
Labels: duplicate
