### ISSUE TITLE
Can't write precomposed greek characters (and maybe of other languages too)

### ISSUE THREAD

**Issue by Doc73** [JabRef/jabref#3108] opened 2017-08-16 07:53 UTC
JabRef 4.0-dev--snapshot--2017-08-15--master--b468d8349
Linux 4.11.0-0.bpo.1-amd64 amd64 
Java 1.8.0_141
Debian 9 Stretch

Steps to reproduce:

1. add or edit an entry
2. set greek keyboard
3. write something, like ἐτυμολογία (in linux, to obtain **ί**, you should hit ALTGR+; (but I'm not sure about the right combination, because I have an italian keyboard; please, check yourself) and then "i")
4. It doesn't work
5. Test the same combination in another software, like Libreoffice, and it works

**Comment by lenhard** [comment] 2017-08-16 09:07
This is a duplicate of #3028

It's actually a bug in OpenJDK, the Java runtime environment for Linux. There's not really something we can do but wait for a fix on their side. But as it seems the team is working on a fix: https://bugs.openjdk.java.net/browse/JDK-8185792

As a workaround, right now you can type the characters elsewhere and copy them into JabRef.

**Closed by lenhard** 2017-08-16 09:07 UTC
