### ISSUE TITLE
Synchronize File Links dialog does not open

### ISSUE THREAD

**Issue by Tscott531** [JabRef/jabref#990] opened 2016-03-18 03:15 UTC
* JabRef version (available in the About box): JabRef version 3.2
* Operating system and version: Windows 10 (64 bit)
* Steps to reproduce:
  1. Open database
  2. Tools > Synchronize File Links
  3. No dialog box opens
In error console:
Output tab: (blank)
Exceptions tab: "No exceptions have occurred."
Log tab:
Mar 17, 2016 10:04:12 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: C:\<directory>\references

Hi everyone, I'm unable to open the synchronize file links dialog in Windows 10 (64 bit) with the 32 bit or 64 bit version of JabRef 3.2. It's as if the button has no function (nothing on the screen changes). "Find unlinked files" and "Automatically set links" both work as expected. Restarting windows does not fix the problem.

Any ideas?

**Comment by tobiasdiez** [comment] 2016-03-18 10:05
This is a duplicate of #680 and is fixed in the recent development version (which should be soon released as 3.4)

**Closed by tobiasdiez** 2016-03-18 10:05 UTC
