### ISSUE TITLE
Incorrect handling of escape sequence for  the character ø

### ISSUE THREAD

**Issue by HarryEClarke** [JabRef/jabref#7099] opened 2020-11-15 15:10 UTC
In the author field, if the Latex sequence \o is entered, this results in JabRef ignoring the rest of the name, but displays subsequent names OK in the formatted box. For example M\olgaard is displayed as just M. JabRef allows the file to be saved, but Bibtex does not accept the sequence, although Latex does.

If the latex sequence \{o} is entered, this results in the character ø being displayed For example M\{o}lgaard is displayed as Mølgaard. However, in attempting to save the file, JabRef reports 
Error in field 'AUTHOR of entry ABC: Braces don't match.

The only entry that works correctly is if the character ø is entered. This results in the correct display in the formatted box, allows the file to be saved, and Bibtex to process the entry

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-11-16 14:19
Hello @HarryEClarke , which version of JabRef are you using?

`M\olgaard` is incorrect BibTeX (I'd guess `M{\o}lgaard`?), I don't have a good reference, but there are a [couple of discussions on stackexchange](https://tex.stackexchange.com/questions/57743/how-to-write-%C3%A4-and-other-umlauts-and-accented-letters-in-bibliography). Perhaps the warning box next to the author field should be displayed regarding this?

> displays subsequent names OK in the formatted box.

Would you mind sharing a screenshot of this? I don't know which box that is. This is how it looks like to me,
<img width="444" alt="Skärmavbild 2020-11-16 kl  09 09 57" src="https://user-images.githubusercontent.com/2598631/99262118-9412f400-27eb-11eb-9ecc-c391991eb0e6.png">
and also, what settings do you have in "JabRef Preferences" -> "Entry table" -> "Format of author and editor names" ?

**Comment by HarryEClarke** [comment] 2020-11-16 15:08
I am using version 5.1 of JabRef, running under Windows 10
The Format of Author and Editor names is set to NatBib
Enclosed is a screen shot of a test author
![JabRef2](https://user-images.githubusercontent.com/23401969/99268752-778faf80-281d-11eb-84c0-f97d8d4d4ad2.png)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-11-16 19:14
1. Regarding the part to the right in your screenshot, I believe it is the preview, in which case it is **incorrectly(?)** identified as a latex command that JabRef can't handle (which is also why everything afterwards is ignored)
https://github.com/JabRef/jabref/blob/1dc91ca3083a25e69516a1d0c71fc876ddb665aa/src/main/java/org/jabref/logic/layout/format/HTMLChars.java#L142-L151
2. Regarding the saving issue, I am not 100% sure, but I believe it is because `test\{o}ab` is treated as BibTeX when you are saving, which means you have an escaped brace `\{` (treated as text) followed by an unescaped one `}` (treated as a command).

Does `M{\o}lgaard` work for you or does this also cause problems?

**Comment by HarryEClarke** [comment] 2020-11-17 10:51
I agree, that when saving it is treating \{ as an escaped brace, which is different behaviour to what is displayed in 

I can confirm that M{\o}lgaard  does work for me, in both saving the file, and with Bibtex.

**Comment by Siedlerchr** [comment] 2020-11-22 14:58
Reading this I think the issue can be closed as JabRef works here as intended.

**Closed by Siedlerchr** 2020-11-22 14:58 UTC
