### ISSUE TITLE
Width of some fields in the "Optional fields" tab are too narrow,

### ISSUE THREAD

**Issue by dbitouze** [JabRef/jabref#7632] opened 2021-04-15 15:12 UTC
JabRef version 5.2 on Linux Mageia 8:

- JabRef 5.2--2020-12-24--6a2a512
- Linux 5.10.27-desktop-1.mga8 amd64 
- Java 15.0.1

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

As shown by the following screenshot, the width of some fields in the "Optional fields" tab are too narrow: it is impossible to check what has been entered in these fields.

1. Open JabRef.
2. File → New library
2. <kbd>Ctrl</kbd> + <kbd>N</kbd> then "Book".
3. Click on "Optional fields" tab.
4. Look at the 2nd column ("Editora", etc.)

![image](https://user-images.githubusercontent.com/1032633/114892574-307a0a80-9e0d-11eb-99a2-4ffdcafa2609.png)

**Comment by Siedlerchr** [comment] 2021-04-15 17:23
Thanks for the report. This is a duplicate of #6901 
There is a workaround https://github.com/JabRef/jabref/issues/6901#issuecomment-691518479 
You an also display Preview as new tab

**Closed by Siedlerchr** 2021-04-15 17:23 UTC
