### ISSUE TITLE
Copy cite command should respect preferences

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10615] opened 2023-11-02 22:23 UTC
https://github.com/JabRef/jabref/pull/10303 introduced a new cite command:

![image](https://github.com/JabRef/jabref/assets/73715071/27416b86-c661-4a40-84b5-9ecf85e0c63a)

It is parsed at `org.jabref.gui.push.AbstractPushToApplication#dissectCiteCommand`.

However, in `org.jabref.gui.edit.CopyMoreAction#copyCiteKey`, this pattern is not used. 

This leads to `\cite{key1,key2}{Khalaf2007}` for key `Khalaf2007`.

![284869839-992b6afe-6efc-4a6d-811f-0641c392a50d](https://github.com/JabRef/jabref/assets/1366654/ba29cfde-3531-4822-8be4-3083e21a429d)

## Implementation

1. Rename `org.jabref.logic.citationkeypattern.CitationKeyPatternPreferences` to `CitationKeyGenerationPreferences`.
1. Modify `org.jabref.preferences.ExternalApplicationsPreferences#getCiteCommand` to return a `record` having `prefix, delimiter, suffix` as string. There, the value is constructed based on the code at org.jabref.gui.push.AbstractPushToApplication#dissectCiteCommand. - No need to introduce caching there. That could be done as next step. (This code does not run for a long time, so no performance issues expected). Name the `record` `CitationCommandStringPreferences`.
1. Add test cases testing (wrong) preference `\cite`. It should work nevertheless. It should use `,` as delimiter and `{` as prefix, and `}` as suffix (as fallback if nothing was provided).  Adapt the code of `CitationKeyGenerationPreferences` accordingly. If this is successfully done, https://github.com/JabRef/jabref/issues/10568 is fixed.
1. Adapt `getCitePrefix()`, ` getDelimiter()`, and `getCiteSuffix()` to use the introduced `CitationStringPreferences`.
1. Remove `org.jabref.gui.push.AbstractPushToApplication#dissectCiteCommand`.
1. <s>Remove `org.jabref.gui.push.PushToApplication#getDelimiter`
   - Remove method
   - Change parameter at org.jabref.gui.push.PushToApplicationCommand#pushEntries to use `CitationCommandStringPreferences`s delimiter</s> This is wrong; since application's delimiter has higher precedence than the one of the citaton command.
1. Adapt `org.jabref.gui.edit.CopyMoreAction#copyCiteKey` to use the new preference

**Comment by ExpPhysU** [comment] 2023-11-04 15:19
I confirm this bug, making version 5.1.1 not usable. Revert to 5.10 and hoping, that it is corrected soon

**Comment by OvercloudX** [comment] 2023-11-07 13:41
Hello koppor, hope everything's well. This is my first time taking a issue and I wonder if I can take this one? Thanks

**Comment by keshav2025** [comment] 2023-11-11 21:52
Hello koppor, I hope you're doing well. This is my first time addressing an issue, and I'm wondering if I can handle this one. Thanks!

**Comment by ThiloteE** [comment] 2023-11-11 21:56
Sorry for the late reply. I will assign @OvercloudX, because of first come first serve.

@keshav2025 Please choose another issue. We usually only assign one issue per student to avoid trouble further down the road. I am sorry.

**Comment by OvercloudX** [comment] 2023-11-11 21:58
> Sorry for the late reply. I will assign @OvercloudX, because of first come first serve.
> 
> @keshav2025 Please choose another issue. We usually only assign one issue per student to avoid trouble further down the road. I am sorry.

Thanks u so much, im gonna start up in it

**Comment by OvercloudX** [comment] 2023-11-22 09:34
@ExpPhysU @koppor @ThiloteE 
Hello everyone, I hope you are doing well.
Could you please tell me how to reproduce the problem? It seems there was a missing image before the implementation part.
<img width="234" alt="屏幕截图 2023-11-22 101153" src="https://github.com/JabRef/jabref/assets/144207757/77174754-9960-494a-8d2f-522578b1cab8">

**Comment by ThiloteE** [comment] 2023-11-22 09:56
Indeed. Maybe your browser has issues? Could you try another one? I use Mozilla Firefox and I can see the image.

**Comment by OvercloudX** [comment] 2023-11-22 10:01
I use edge, and I tried Firefox but it had the same problem. When I click the image link it shows 404 not found.

**Comment by OvercloudX** [comment] 2023-11-22 10:02
> Indeed. Maybe your browser has issues? Could you try with another one? I use Mozilla Firefox and I can see the image. What happens, if you click on that image link?

I use edge, and I tried Firefox but it had the same problem. When I click the image link it shows 404 not found.

**Comment by ThiloteE** [comment] 2023-11-22 10:22
Ok, I think I fixed it. Apparently the links to those images was copied from a private protected GitHub repository. I uploaded new images, which you now should be able to see. Could you please confirm, if you can see them now?

**Comment by OvercloudX** [comment] 2023-11-22 10:44
> Ok, I think I fixed it. Apparently the links to those images were copied from a private protected GitHub repository. I uploaded new images, which you now should be able to see. Could you please confirm, if you can see them now?

yes, it works, thank you for your help

**Comment by koppor** [comment] 2023-11-23 11:45
> Could you please tell me how to reproduce the problem?

Can you now reproduce the issue?

You can open the example BibTeX file https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib.

And then you can go to an entry and try to do "Copy \cite{citationkey}". I think, even this context menu item text needs to be adapted based on the preferences.

**Comment by OvercloudX** [comment] 2023-11-26 18:27
> > Could you please tell me how to reproduce the problem?
> 
> Can you now reproduce the issue?
> 
> You can open the example BibTeX file https://github.com/JabRef/jabref/blob/main/src/test/resources/testbib/jabref-authors.bib.
> 
> And then you can go to an entry and try to do "Copy \cite{citationkey}". I think, even this context menu item text needs to be adapted based on the preferences.

Yes, I've succeeded reproduce the issue I think. I saw that it was different when I imported to TEX Studio using two methods.

Thank you for the help.

**Comment by OvercloudX** [comment] 2023-12-02 22:10
@koppor @ThiloteE Hello I have a question about the step3. It is said that the default prefix should be "{" but when I check the defaultCiteCommand in the java/org/jabref/preferences/ExternalApplicationsPreferences.java, I found it was "\cite{key1,key2}" so I wonder if the default prefix is "\cite{" or "{" ?

**Comment by OvercloudX** [comment] 2023-12-02 22:13
> @koppor @ThiloteE Hello I have a question about the step3. It is said that the default prefix should be "{" but when I check the defaultCiteCommand in the java/org/jabref/preferences/ExternalApplicationsPreferences.java, I found it was "\cite{key1,key2}" so I wonder if the default prefix is "\cite{" or "{" ?

Please forgive me if I made any silly mistake because I'm new in code.

**Comment by OvercloudX** [comment] 2023-12-04 21:06
> @OvercloudX Did you do step 2 - and modify org.jabref.preferences.ExternalApplicationsPreferences#getCiteCommand?
> 
> Can we see it a draft pull request?

Yes, I think I may successfully finished the part 2 and I'd like to make a draft PR to you. I changed the method and created a record(CitationCommandStringPreferences).
Now I'm stuck in testing, I used JUnit for the test.

**Comment by Siedlerchr** [comment] 2023-12-04 21:35
@OvercloudX  You probably have to mock the preferences with  prefs =   mock(ExternalApplicationsPreferences.class) and then using when(prefs.getCiteCommand).thenReturn...

**Comment by OvercloudX** [comment] 2023-12-04 21:57
> @OvercloudX You probably have to mock the preferences with prefs = mock(ExternalApplicationsPreferences.class) and then using when(prefs.getCiteCommand).thenReturn...

Thank you for the help, gonna that right now

**Comment by OvercloudX** [comment] 2023-12-04 22:05
> > @koppor @ThiloteE Hello I have a question about the step3. It is said that the default prefix should be "{" but when I check the defaultCiteCommand in the java/org/jabref/preferences/ExternalApplicationsPreferences.java, I found it was "\cite{key1,key2}" so I wonder if the default prefix is "\cite{" or "{" ?
> 
> You can reproduce by
> 
> 1. Unisntalling JabRef
> 2. Isntalling JabRef 5.10
> 3. Reset preferences in JabRef 5.10
> 4. Close JabRef
> 5. Start JabRef from maikn
> 6. Check the preference
> 
> Now, you should see `\cite` instead of `\cite{key1,key2}`.
> 
> See https://github.com/JabRef/jabref/pull/10303/files#diff-42a07fbc47ff359873a26e31184338ddf82ddcecf188dac16da1ef103eae3833R703 for the change introduced in the PR
> 
> Please note that I linked the PR **in the first words** of the issue description
> 
> You need to click on "Files changed"
> 
> ![grafik](https://private-user-images.githubusercontent.com/1366654/287695073-23e53afd-4a7d-4280-b48b-2b8db389d409.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MjQ0MjUsIm5iZiI6MTcwMTcyNDEyNSwicGF0aCI6Ii8xMzY2NjU0LzI4NzY5NTA3My0yM2U1M2FmZC00YTdkLTQyODAtYjQ4Yi0yYjhkYjM4OWQ0MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMjEwODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWEzZjc0MTMzZmY4Mzk4NmMwMDgwOGM1M2U4ZWVlYWRhYTlhOGU5ZDRmMTJmMjg0ZjBlNmRkOTFkOTE3MWEyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.utQwATu0nd_XbuAi5txlW295yLhIdBCx1nGgwGXjJSk)
> 
> Then scroll down to `src/main/java/org/jabref/preferences/JabRefPreferences.java`. You can also click a the "file explorer"
> 
> ![grafik](https://private-user-images.githubusercontent.com/1366654/287695381-ad250751-ae2d-48b7-9d01-cb4c6ef1a612.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3MjQ0MjUsIm5iZiI6MTcwMTcyNDEyNSwicGF0aCI6Ii8xMzY2NjU0LzI4NzY5NTM4MS1hZDI1MDc1MS1hZTJkLTQ4YjctOWQwMS1jYjRjNmVmMWE2MTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMjEwODQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU1OWYyYzA5MDk3YjU3ZmQwOTZmOGNlYmY3ODY5NzM5MjEwYWFiMDM4YWRhNGM2YTU4ODRhMzYzY2Y1ZjkxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tjJZHqpY4qGU7Ua404KvWsTZYRvqEFd15vCjadkHNjU)
> 
> Is it now more clear?

Thanks, that's more clear, but I still confused with these things:
1. These procedures are for me to have defaultCiteCommand as "\cite"
2. So it was \cite before the issue #10303, and after that merged PR it becomes \cite{key1,key2}

Thank you again for taking the time and effort to help me

**Comment by koppor** [comment] 2023-12-05 08:15
> Thanks, that's more clear, but I still confused with these things:

Software Engineering is also about clear requirements. It is good that you try to understand them. I would ask you to read and try to understand existing material. Please take the time to read. No rush. I assume you worked with Microsoft Word and not with LaTeX and JabRef. Then, it takes even more time to understand the whole setting.

In the statements you gave me, I can just write "yes" as answer. Do you ask about the why? From https://github.com/JabRef/jabref/pull/10303, there is https://github.com/JabRef/jabref/issues/10133 linked. I try to copy and paste from that.

>     1. These procedures are for me to have defaultCiteCommand as "\cite"

Yes. JabRef 5.10.

>     2. So it was \cite before the issue [Push to external application config #10303](https://github.com/JabRef/jabref/pull/10303), and after that merged PR it becomes \cite{key1,key2}

Yes. JabRef 5.10 to 5.11.

Quoting: https://github.com/JabRef/jabref/issues/10133 

> I use Pandoc for processing Markdown manuscripts to ODT format. Markdown cite command is `[@key]` instead of LaTeX `\cite{key}`. In case of multiple citations this is `[@key1; @key2]`. Currently the preference for cite command does not include the `{` and `}` characters, making it impossible to change it to another cite command that does not use curly brackets. Also, the separating character (`,`) cannot be modified.

Quoting https://github.com/JabRef/jabref/pull/10303 with a highlight.

![grafik](https://github.com/JabRef/jabref/assets/1366654/935bb57a-0f49-45cf-9ea8-53be3c254013)

Screenshot of today's JabRef:

![grafik](https://github.com/JabRef/jabref/assets/1366654/90c084c0-571e-4417-9dcb-dfdee8c09b4e)

Did you click on the question mark?

It leads to https://docs.jabref.org/cite/pushtoapplications

I highlight the important part. It is still worth to read the complete page.

![grafik](https://github.com/JabRef/jabref/assets/1366654/01926806-b18e-4886-854e-3f26a2b4fc76)

---

Now click on "Copy \cite{citaton key}"

![grafik](https://github.com/JabRef/jabref/assets/1366654/c162c392-04b9-45fb-b906-977c7c2875ef)

Result is:

    \cite{key1,key2}{lala}

Which is wrong. The issue is about to fix THAT behavior.

**Comment by OvercloudX** [comment] 2023-12-05 10:09
@koppor Thanks for your advice, I'll read them again.

**Comment by koppor** [comment] 2023-12-18 20:45
@OvercloudX We did not see any activity on your side. Do you intend to continue?

**Comment by OvercloudX** [comment] 2023-12-18 21:05
> @OvercloudX We did not see any activity on your side. Do you intend to continue?

Hi there, recently I don't have much time to do it. But I still have strong willing to continue after several days.

But if there's anyone who want to take this issue now, I don't mind if you give it to someone else, because I don't want to take up public resources either.

**Comment by ThiloteE** [comment] 2023-12-18 21:59
Take your time, we will be happy, if you come back to this :-)

**Closed** 2023-12-22 02:35 UTC
Labels: bug, preferences, good first issue
