### ISSUE TITLE
key generation partially broken

### ISSUE THREAD

**Issue by PUKK** [JabRef/jabref#5557] opened 2019-11-02 17:39 UTC
JabRef 5.0.0-dev--2019-11-01----4a9373423
Linux 4.12.14-lp151.28.20-default amd64 
Java 12.0.2

Since years I use the key generation pattern "[auth4:lower][shortyear]". Used to work perfectly and still does if the first author is given as "Firstname Lastname" but if it is given as "Lastname, Firstname" it now uses the first name for the key generation which is certainly not what is expected (and not what it used to be in Jabref 4). Thanks for looking into this issue!

Jabref is a great tool and time saver!!

**Comment by Siedlerchr** [comment] 2019-11-02 17:54
Duplicate of #5551

**Closed by Siedlerchr** 2019-11-02 17:54 UTC
