### ISSUE TITLE
Version 3.1. clicking on groups doesn't refresh table view

### ISSUE THREAD

**Issue by mluerig** [JabRef/jabref#642] opened 2016-01-05 12:01 UTC
when I start up jabref and click on any group in the group-panel the table view is refreshed. 
if I then click on another group the table view isn't refreshed. instead, I have to go back and select "all entries", and then click on antother group to show its elements

**Comment by oscargus** [comment] 2016-01-05 12:07
Fixed in master (duplicate of #417).

**Closed by oscargus** 2016-01-05 12:07 UTC
