### ISSUE TITLE
Download-Area: master-latest is missing

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [JabRef/jabref#5398] opened 2019-10-06 18:27 UTC
In the past there was a `https://builds.jabref.org/master/JabRef-linux-master-latest.tar.gz` but you removed it.

Now there is a `deb` file and also a `tar.gz` but not with a `linux-master-latest`.

I have a download script fetching the current `latest` version. I do not want to visit the website all the time to check out the current version number just for downloading.

**Comment by koppor** [comment] 2019-10-06 20:51
Somehow a duplicate of https://github.com/JabRef/jabref/issues/2953.

The discussion is going on there: https://github.com/JabRef/jabref/pull/5312#issuecomment-534941054 and https://github.com/JabRef/jabref/pull/5312#issuecomment-535688605

**Comment by Siedlerchr** [comment] 2019-10-07 08:36
Should be now the https://builds.jabref.org/master/JabRef-portable_linux.tar.gz

**Comment by koppor** [comment] 2019-10-07 15:30
The link you mentioned is a portable version including a JRE. The
original question demanded a plain `jar` (where one installs the JRE
by oneself - maybe due to space savings on the local machine, because
of using multiple Java-based programs)

Am Mo., 7. Okt. 2019 um 10:36 Uhr schrieb Christoph <notifications@github.com>:

**Comment by tobiasdiez** [comment] 2019-10-07 16:09
There is no such thing as JRE 11, see https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html 
>In this release, the JRE or Server JRE is no longer offered. Only the JDK is offered. Users can use jlink to create smaller custom runtimes.

Using jlink is exactly what we did (and what produces the portable version).

So the real question is: do we want to add symlinks for all installer/packages?

**Comment by Siedlerchr** [comment] 2019-10-07 16:16
The problem is that whenever we update a dependency, the jlink image might be affected and changed, if I understood this correctly.

**Comment by koppor** [comment] 2020-04-14 06:33
We discussed that maintaining links causes effort in our release. The discussed links are targeting power users always wanted the latest version. Since our filenames are now "stable" between releases, it should be a minimal effort to update the links (e.g. replacing 1 by 2 after 5.1 is released) after a release.

@Codeberg-AsGithubAlternative-buhtz Hope, this is OK for you?

**Closed by koppor** 2020-04-14 06:33 UTC
Labels: build-system, t: enhancement
