### ISSUE TITLE
Add key shortcut for global search

### ISSUE THREAD

**Issue by sciunto** [JabRef/jabref#573] opened 2015-12-23 16:12 UTC
Hi,

It would be a nice enhancement if we can have a shortcut for the global search. My use case:

I enter a keyword in the search bar in the top of the windows.
Suggestions are displayed, I eventually move with arrows and then press enter.
The word is completed
Now, I would like to press shift-enter (for example) to make a global search from that.

Thank you!

**Comment by stefan-kolb** [comment] 2016-03-20 13:43
Duplicate of #617?

**Comment by koppor** [comment] 2016-03-20 13:54
I think so, but #617 is more hard to read. Maybe, I need screenshots to fully understand #617. #617 seems to contain more than one issue, but this issue seems to be included although not with the solution to press "shift+enter".

**Comment by stefan-kolb** [comment] 2016-03-20 13:56
I suggest to close one of the issues. Which one is up to you :smile:

**Comment by koppor** [comment] 2016-04-08 06:02
I fixed the description of #617. The first part of #617 ("Keyboard shortcut for global search") is now described here. The second part of #617 ("ENTER should work as expected") is now on its own.

**Comment by bartsch-dev** [comment] 2016-07-11 16:01
I'm implementing this at the moment.
A Shortcut executes the global search and opens the result dialog (which isn't modal).
Should the same shortcut focus an old result dialog if there is one in the background? (Thus only one global search can be done at a time).

**Comment by sciunto** [comment] 2016-07-13 07:59
@bartsch-dev Thanks for looking at this!

I would answer yes to your question.

BTW, the fact that the window is not modal is really annoying for some window manager (like i3) because I can't close the window with ctrl-q or ctrl-w... If something could be done on that side too, that would be awesome.

**Comment by bartsch-dev** [comment] 2016-07-26 07:23
@sciunto In case you haven't seen it: I'm implementing it in #1549!

**Comment by sciunto** [comment] 2016-07-26 13:58
thanks @bartsch-dev

**Comment by bartsch-dev** [comment] 2016-09-24 20:49
The new shortcut is <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>F</kbd>.
This Issue can be closed.

**Comment by koppor** [comment] 2016-09-24 22:05
Thank you for reporting this issue. We think, that is already fixed in our development version.
Please use a development build from http://builds.jabref.org/master
The fix will be included in the next release.

**Closed by koppor** 2016-09-24 22:05 UTC
Labels: enhancement, search, stupro

**Comment by sciunto** [comment] 2016-09-25 05:43
Thank you!
