### ISSUE TITLE
JabRef secretly deletes entries when they have been modified via "biblatex source"

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3501] opened 2017-12-08 15:25 UTC
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

> “JabRef_macos_4_1-dev--snapshot--2017-12-08--master--6f39151a7.dmg” is damaged and can’t be opened. You should move it to the Trash.

JabRef version 4.1-dev

Steps to reproduce:

1. edit an entry in the "biblatex source" tab
2. do something
3. find out later that your entry has gone (no traces left in the bib file)
4. hope that you have a backup, restore the entry with some other editor

**Comment by Siedlerchr** [comment] 2017-12-08 16:07
@j0hannes  There is currently an issue with the codesigning, that's why the issue is there. We are working on that. In the meantime you can download the file with wget and it works

**Comment by lenhard** [comment] 2017-12-08 17:35
@j0hannes 

I've tried to reproduce this, but to no avail. I'm afraid you'll have to be more specific about "2. do something", otherwise there's no chance that we can do something.

**Comment by j0hannes** [comment] 2017-12-08 17:47
With 'do something' I mean that you finish editing the entry, e.g. by clicking on another entry or tab.

It happens infrequently that the entry is deleted then, but always when an entry vanished I had edited it in that tab before.

**Comment by lenhard** [comment] 2017-12-08 17:53
@j0hannes Thanks, but still no success in reproducing it on my side. Maybe this is a MacOS problem, I am running Windows. We'll have to see if someone else has more luck with reproduction.

**Comment by tobiasdiez** [comment] 2017-12-08 22:09
I think this bug was fixed recently. @j0hannes do you use the most recent snapshot?

**Comment by j0hannes** [comment] 2017-12-08 22:59
OSX wouldn't let me install the most recent one, as of today, because the dmg file was damaged (and I always believed that was what dmg was supposed to mean).

I can't tell you exactly which version I have installed there.

**Comment by tobiasdiez** [comment] 2017-12-08 23:07
Yes, the "file is damaged" message is known and will soon be fixed. Actually the fix is already in the pipeline #3499 and the build from https://builds.jabref.org/new-cert/ should work. Can you please try it out. Thanks! Moreover, you can find the detailed build information in the about dialog.

**Comment by Siedlerchr** [comment] 2017-12-09 10:04
If you download the dmg file with wget from the terminal, you won't get the damaged dmg file notice.sounds odd, but works

**Comment by j0hannes** [comment] 2017-12-09 17:40
Now it happened to me to a newly created entry that I didn't modify in the source tab. I just clicked on it to see the source entry. After changing to a different entry, the previous one wasn't there anymore.

**Comment by Siedlerchr** [comment] 2017-12-10 12:14
@j0hannes  With the latest dev version I cannot reproduce your error. It works as expected.

**Comment by j0hannes** [comment] 2017-12-17 12:45
It just happened again. An entry, which was there before, just secretly disappeared. I can't say when and why. This is really annoying when have to suspect your reference manager to work against you.

**Comment by Siedlerchr** [comment] 2017-12-17 13:44
@j0hannes  Sorry for the inconvenience. Unfortunately we need some more details. Do you have any filtering active? Did you check the bibfile in an external Editor to see if the entry is till there?
Any errors in the log?

**Comment by j0hannes** [comment] 2017-12-17 14:01
I checked the file and the entry wasn't there anymore. Fortunately, I have the bib file covered by versioning control so that I could get recover the entry, minus manual changes applied later on.

There was some filtering active when I last changed the entry, for sure.  I guess, what I did last was to copy another entry to the source field and merge it with the existing one. I usually only save the file when I'm done with editing and have deleted the other entry.

The only error I find in the log is this one:
```
Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Vector.elementData(Vector.java:734)
	at java.util.Vector.elementAt(Vector.java:477)
	at javax.swing.table.DefaultTableColumnModel.getColumn(DefaultTableColumnModel.java:294)
	at org.jabref.gui.maintable.MainTableSelectionListener.mouseReleased(MainTableSelectionListener.java:199)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by j0hannes** [comment] 2017-12-17 22:08
Although I don't know how to reproduce this bug, it hits me like once in an hour. I would advise anyone using the recent version to frequently check for deleting with a version control system.

**Comment by j0hannes** [comment] 2017-12-23 12:54
If you create two entries and copy&paste to the source field, the second one will overwrite the first one.

**Comment by melTr** [comment] 2018-02-09 20:37
Hi,
Got the same issue that drives me crazy. Same thing. I have 4 similar items, and they constantly write over themself, so I "loose" one.
Sorry for the really poor quality of filming, I didn't with my phone while I was typing (and no, I can't install some screenshot software on my work computer). Focus on the title and bibtexkey. At the beginning it's 4 differents. I erase the url field in the 4th one. Finally this 4th one become the second one, and I loose completely the one that was the 2nd. 

[Error1.txt](https://github.com/JabRef/jabref/files/1712342/Error1.txt)
https://www.dropbox.com/s/z9vh5o8q1rubbh9/2018-02-09%2015.14.08.mp4?dl=0

Over time, I also get other errors, but I'm not sure if they're related or not. By the way, I just one instance of Jabref. However, bib files are part of Dropbox, so they constantly sync. I don't know if it could be the problem.
[error.txt](https://github.com/JabRef/jabref/files/1712344/error.txt)

**Comment by anassal** [comment] 2018-02-11 14:36
I confirm that in JabRef 4.1 (Linux 4.13.0-32-generic amd64 Java 1.8.0_161, and also on Windows) some entries disappear while others become duplicated. This happened many time (I needed to restore 30+ deleted entries last week). The biblatex library is synced to the cloud. Unfortunately, I couldn't identify a reproducible scenario!

**Comment by tobiasdiez** [comment] 2018-02-11 16:13
@melTr @j0hannes @anassal This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks!

**Closed by tobiasdiez** 2018-02-11 16:13 UTC
Labels: waiting-for-feedback

**Comment by felker** [comment] 2018-02-15 19:48
I also noticed this issue in JabRef 4.1 using macOS High Sierra, Java 1.8.0_162, and the problem seems to have disappeared in the latest dev version for me. 

I would also agree with @j0hannes suggestion to use a VCS with your .bib database to notice and track down these errors until the next release is made.
