### ISSUE TITLE
search for x, then generate/add new entry, search filter is lost

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7833] opened 2021-06-19 13:59 UTC
JabRef 5.3--2021-06-08--9d1c448
Linux 5.12.9-300.fc34.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

*Use case*
I search for an entry with author name X.
Then I find I do not have the desired publication in the database.
Therefore I generate a new entry.
At this point the search/filter is removed.

*what should be different?*
I would not expect the search filter to be cleared.

**Comment by koppor** [comment] 2021-07-05 23:00
Refs https://github.com/JabRef/jabref/issues/4096

**Comment by Siedlerchr** [comment] 2021-12-22 11:02
I can no longer reproduce the issue in the latest release 5.4 /dev version

**Comment by ilippert** [comment] 2021-12-23 03:47
Sorry, I cannot confirm.
Issue still present in

JabRef 5.4--2021-12-20--ab44182
Linux 5.15.10-200.fc35.x86_64 amd64 
Java 16.0.2 
JavaFX 17.0.1+1

**Comment by ThiloteE** [comment] 2022-05-11 09:11
I think this was also fixed by #8717
Cannot reproduce anymore.

Closing this :-)

**Closed by ThiloteE** 2022-05-11 09:11 UTC
Labels: search, project: GSoC
