### ISSUE TITLE
aux group count not updated

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#5208] opened 2019-08-24 09:09 UTC
JabRef `master` as of today.

1. Have latex document with 0 citations
1. Compile latex document
2. Open bib in JabRef
2. Create auto group "Group containing entries cited in a given TeX file"
3. Group shows count 0
4. Add 1 cite to the latex document
5. Compile latex
6. Click group on bibtex
7. one entry shown
8. group count still 0

![grafik](https://user-images.githubusercontent.com/1366654/63635159-a55c6780-c65f-11e9-9d81-53d4bf975a04.png)

**Comment by Siedlerchr** [comment] 2019-08-24 10:03
Looks like it's a duplicate of #4441

**Closed by Siedlerchr** 2019-08-24 10:03 UTC
Labels: enhancement, good first issue
