### ISSUE TITLE
copying duplicate

### ISSUE THREAD

**Issue by DrFelder** [JabRef/jabref#5161] opened 2019-07-31 09:57 UTC
JabRef version 5.0-dev  on  MacOS 10.14.04

When I copy an entry (cmd+c) and paste it (cmd+v), two entries are created, resulting in three similar entries instead of two

The output of my jar is that I am copying and pasting two times:

```
11:56:07.715 [JavaFX Application Thread] INFO  org.jabref.gui.JabRefDialogService - Copied 1 entry.
11:56:07.719 [JavaFX Application Thread] INFO  org.jabref.gui.JabRefDialogService - Copied 1 entry.
11:56:38.260 [JavaFX Application Thread] INFO  org.jabref.gui.JabRefDialogService - Pasted 1 entry.
11:56:38.280 [JavaFX Application Thread] INFO  org.jabref.gui.JabRefDialogService - Pasted 1 entry.
```

1. copy entry in library
2. paste entry in library
3. have fun with three entries…

![grafik](https://user-images.githubusercontent.com/16526114/62202673-00b17780-b38a-11e9-8f0b-c1d5fd980e90.png)

**Comment by DrFelder** [comment] 2019-07-31 11:27
I've looked into the issue a bit, the duplicate paste is happening _everywhere_ in jabref: When I try to paste into fields of entries etc.
Funny thing is: Undo only reverts one of the paste actions.

**Comment by matthiasgeiger** [comment] 2019-07-31 17:00
Duplicate of #4845, #4699 and #4836

Hello @DrFelder 
as this seems to be a MacOS specific problem that has already been reported before. This, I'll close this issue.

Best,
Matthias

**Closed by matthiasgeiger** 2019-07-31 17:00 UTC
