### ISSUE TITLE
Preview does not show \textit{something} correctly

### ISSUE THREAD

**Issue by idadoudou** [JabRef/jabref#9309] opened 2022-10-25 11:59 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Details on version and operating system

Linux localhost.localdomain 5.19.12-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Sep 28 17:11:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. To edit a gene name in the title, I set it \textit{GeneName}.
2. I can not preview it in the IEEE preview style and other styles

For example, a citation as following
Article (Cho2017a)
Cho, Y. B.; Jones, S. I. & Vodkin, L. O.
Mutations in Argonaute5 Illuminate Epistatic Interactions of the K1 and I Loci Leading to Saddle Seed Color Patterns in Glycine max. 
Plant Cell, 2017, 29, 708-725 

I edited the title to "Mutations in {\textit{Argonaute5}} Illuminate Epistatic Interactions of the {\textit{K1}} and {\textit{I}} Loci Leading to Saddle Seed Color Patterns in {\textit{Glycine max}}." because I hope the gene name can be italic when I cite it in my manuscript.

Now I got this preview under the IEEE preview style.

Cho, Y.B., Jones, S.I., Vodkin, L.O., 2017-04. Mutations in ������������������������������������������������������5 Illuminate Epistatic Interactions of the ������1 and ������ Loci Leading to Saddle Seed Color Patterns in ������������������������������������������ ������������������. Plant Cell 29, 708–725.

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by bwakkie** [comment] 2022-10-26 08:28
It's an old unresolved bug:  See https://github.com/JabRef/jabref/issues/2784

**Comment by ThiloteE** [comment] 2022-10-26 10:39
closing as duplicate of #8522. Please keep discussion over there.

**Closed by ThiloteE** 2022-10-26 10:39 UTC
Labels: entry-preview
