### ISSUE TITLE
Changing key generator pattern doesn't work

### ISSUE THREAD

**Issue by smihael** [JabRef/jabref#6196] opened 2020-03-28 17:37 UTC
I'm using JabRef 5.0--2020-03-06--2e6f433 (Java 13.0.2) on and Ubuntu 18.04 based system (KDE neon).

1. Preferences
2. BibTeX key generator
3. Click on any row to change key pattern
4. Enter  [auth][year][veryshorttitle]

Now you can:
a) Click anywhere in the window. The input field is reset to previous value. In the case of default pattern this is [auth][year].
b) Click Save. The UI will prompt that the settings have been changed, but if you repeat from Step 1, you will notice that the pattern is still as it was before trying to change it.

**Comment by Siedlerchr** [comment] 2020-03-28 19:29
Duplicate of  #5825 You simply need to hit enter to save the field content.

**Closed by Siedlerchr** 2020-03-28 19:29 UTC
Labels: preferences, ui

**Comment by smihael** [comment] 2020-03-28 20:26
Thanks. It would be good to make it more intuitive (e.g. by showing a hover
text).
