### ISSUE TITLE
Feature request: Improve and document support for a free Java environment

### ISSUE THREAD

**Issue by jonasstein** [JabRef/jabref#3039] opened 2017-07-22 12:06 UTC
The installation instructions say:

> JabRef runs on any system equipped with the Java Virtual Machine (1.8 or newer), which can be downloaded at no cost from Oracle. 

There are several reasons why it would be good to improve the support for free Java environment in a way, that users do not have the burden to install Oracle Java.
Oracle Java is increasingly problematic:
* the code is closed source
* Oracle does not even allow to mirror or distribute the install files. This creates heavy workload for all Linux distributions, but also for other operating systems. 
* it fits better to an open source application like Jabref to rely on an open source language.
* Users can not let the package manager update Oracle Java. They have to download closed source files for every update and accept complicate licenses over and over again. 
* Less users are willing to start software which hides its sourcecode. 
* More and more companies and users are not allowed to use closed source for security reasons. 

Therefore I suggest to support a non proprietary solution in first place and other solutions on second place.

**Comment by Siedlerchr** [comment] 2017-07-22 14:13
Hello,

thanks for your interesting in using JabRef.
first of all we should clarify some things here: The Oracle JDK is completely based on the open source reference implementation, the OpenJDK and only contains some closed source extensions  [Open JDK FAQ](http://openjdk.java.net/faq/).
While most of the time JabRef works fine with OpenJDK under Linux, some users have experienced problems which could only be resolved by using the Oracle JDK.  Therefore, if some problems occur which we cannot reproduce, we recommend trying out the Oracle JDK instead.  And for some major distributions, there are some [external repositories](https://launchpad.net/~webupd8team/+archive/ubuntu/java) or scripts which automate the process of installing and updating the oracle jdk.

There is a wide variety of Linux versions and distributions outside and as we are only a small development team with limited resources, we cannot guarantee that it runs fine everywhere, although we try to do our best. As every Open Source project we encourage our users to [contribute with code or money](http://help.jabref.org/en/FAQcontributing) which keeps us going.

I hope this answer addresses your concerns. If you have further questions, feel free to contact us.

Best Regards
Christoph

**Comment by lenhard** [comment] 2017-07-22 18:16
Is this really something to discuss on the issue tracker? I think it would be more suitable to take this to the forum.

**Closed** 2017-07-22 18:21 UTC
