### ISSUE TITLE
JabRef causes permanent discrete GPU usage

### ISSUE THREAD

**Issue by ololobus** [JabRef/jabref#2470] opened 2017-01-16 18:05 UTC
JabRef version 3.8.1 on macOS 10.12.2

Steps to reproduce:

1. Run JabRef
2. Go to About This Mac -> Display
3. Check current GPU in use

JabRef requires for some reason a discrete GPU, which seriously affects a battery life. Tested with both MacOS packed .app and cross-platform .jar

Is it really necessary? Or it is possible to turn off discrete GPU dependancy in the future release?

**Comment by ololobus** [comment] 2017-01-16 18:55
I've solved the problem by adding following lines into the `info.plist`

```plist
<key>NSSupportsAutomaticGraphicsSwitching</key>
<string>YES</string>
```

It's a temporary solution, since plist will be changed on a next JabRef autoupdate, so it should be added to the configs during the app build.

**Comment by Siedlerchr** [comment] 2017-01-16 19:00
Thanks for the report and the solution!
We will try to integrate that into the App build information

2017-01-16 19:55 GMT+01:00 Alexey Kondratov <notifications@github.com>:

**Comment by stefan-kolb** [comment] 2017-01-17 21:38
The question really is why does this happen?

**Comment by ololobus** [comment] 2017-01-23 11:10
It's difficult to suggest anything, since I don't know an internal structure and technologies of JabRef (I only know that it uses Java), but for example:

```
By default, once your application creates an OpenGL context (by either calling OpenGL directly or an API that relies on OpenGL such as Core Animation, Core Image, etc), the MacBook Pro automatically switches to the higher-end discrete GPU for performance concerns and won't switch back until the application quits. On OS X 10.6 and earlier, you are not allowed to choose to run on the integrated GPU instead. Starting with OS X 10.7, you may utilize the integrated GPU on the MacBook Pros if you want to, for example, to save battery life.
```

https://developer.apple.com/library/content/qa/qa1734/_index.html

**Comment by matthiasgeiger** [comment] 2017-01-23 11:25
Hi @ololobus! 
Which Java version are you using? 
If I understand [this bugreport for OpenJDK](https://bugs.openjdk.java.net/browse/JDK-8132759) correctly the problem should be fixed since OpenJDK 1.8.0_92.

**Comment by ololobus** [comment] 2017-01-23 11:30
Hi @matthiasgeiger,

```shell
|--> java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)
```

**Comment by matthiasgeiger** [comment] 2017-01-23 11:33
Thanks! This is Oracle JDK, right?

**Comment by ololobus** [comment] 2017-01-23 11:36
Yes, it is right

**Comment by matthiasgeiger** [comment] 2017-01-23 11:40
As we don't have any developer coding on a Mac... Could you please check whether this problem is also present if you use a recent OpenJDK? 

If not, this seems to be a general Oracle Java bug and not really caused by JabRef.

**Comment by ololobus** [comment] 2017-01-23 12:00
I will try one day, but there no official fresh builds of OpenJDK for Mac (there is only a critically outdated port `openjdk6`, so I guess the only way is to build it from source). Thus, the probability that someone uses JabRef with OpenJDK under Mac OS X tends to zero.

Anyway, I clearly solved the issue for myself by adding two lines into `info.plist` of your app. If you want to solve the issue for other casual OSX users of JabRef you can do it too, but during your app build process.

**Comment by stefan-kolb** [comment] 2017-02-15 17:53
@chochreiner Does this also happen for you? Should I add this to the installer by default?

**Comment by stefan-kolb** [comment] 2017-02-15 17:59
@ololobus @chochreiner If it is a problem, it should be fixed by the latest build from http://builds.jabref.org/osx-gpu. Please confirm if possible 😄

**Comment by ololobus** [comment] 2017-02-15 18:21
@stefan-kolb just tried your dev build, works well on integrated gpu :)
To be sure compared it with a clean installation of the latest release (3.8) from website and yes, current version requires discrete gpu

**Closed** 2017-02-15 19:04 UTC
Labels: bug, build-system, jabcon, osx
