### ISSUE TITLE
Cut and Paste duplicates entry in original table

### ISSUE THREAD

**Issue by bdcaf** [JabRef/jabref#4845] opened 2019-04-03 13:29 UTC
To reproduce 

1. open two bibliographies
2. copy (Command-c) one (or more) entries from first bibliography
3. switch to second bibliography and paste with (Command-v)

Then in the entry is added to the second - but also duplicated in the first bibliography.

Info:

```
JabRef 5.0-dev--snapshot--2019-04-03--master--a273eb1fa
Mac OS X 10.14.3 x86_64 
Java 1.8.0_191
```

I think it might be linked with https://github.com/JabRef/jabref/issues/4836 - also here pasting with right click does not trigger it.

**Comment by Siedlerchr** [comment] 2019-04-03 16:58
Seems to be only a Mac issue. On Windows 10 I cannot confirm this. 
Try updating your java to 8u202. There have been several mac specific fixes.

**Comment by bdcaf** [comment] 2019-04-04 06:33
> Seems to be only a Mac issue. On Windows 10 I cannot confirm this.
> Try updating your java to 8u202. There have been several mac specific fixes.

I did the update.  However the issue is unaffected.

**Comment by Ali96kz** [comment] 2019-04-11 09:09
I have a mac os. I will investigate it.

**Comment by Ali96kz** [comment] 2019-04-11 21:27
@bdcaf  @tokkot Can't reproduce it. Run jabref via `intelliJ idea` latest master.

**Comment by Siedlerchr** [comment] 2019-08-24 10:56
Thanks to @LinusDietz  and @stefan-kolb  this issue is now fixed in the latest master!

**Closed** 2019-08-24 10:56 UTC
Labels: macOS, maintable
