### ISSUE TITLE
Don't activate group when expanding or collapsing

### ISSUE THREAD

**Issue by frantik2477** [JabRef/jabref#7982] opened 2021-08-11 13:26 UTC
When I want to assign an entry to a subgroup, I have to first expand the parent group and then drag-and-drop my entry in the appropriate subgroup. The problem is that when I expand the group, by clicking on the arrow on the right, the group gets activated (the entry table only shows the group entries) and, therefore, I have to go back to "All entries" and locate my entry again. The parent group gets activated when collapsing it as well.

This problem did not occur in earlier versions of JabRef. It would be very convenient to have this fixed. I'm using JabRef 5.3--2021-07-05 in Ubuntu 20.04. I had also reported this issue [here](https://discourse.jabref.org/t/improve-group-ui/1985).

**Comment by ThiloteE** [comment] 2021-08-11 20:40
While i agree that this is very suboptimal, a workaround for now could be to enter it manually in the bib file (the {} biblatex source field):

`groups           = {groupname 1, groupname 2, subgroup 1,},`

Btw. when i did some tests on this, i realized that subfolders ALWAYS have to have different names, otherwise the entries mix up.

What is advisable:
Parentfolder 1, Subfolder1, Subfolder 2
Parentfolder 2, Subfolder3, Subfolder 4.

The following mixes up the entries of Subfolder Y:
Parentfolder A, Subfolder Y, 
Parentfolder B, Subfolder Y,

It seems that subfolders are treated as distinct folders, instead of being hard wired to Parentfolders. Take care.

**Comment by frantik2477** [comment] 2021-08-12 15:11
Thanks for your answer, @ThiloteE.

Yes, manually adding the desired group names in the "groups" field can work, but then you have to be careful about typos etc, especially if have many groups to deal with. And yes, subgroups are not really assigned to their parent groups and hence they do all need to have different names. But this has been the case in older versions of JabRef as well, I think. Another mistake I once made was having a group containing commas in its name, without realising that commas are the group separators.

Another workaround I stumbled upon is right-clicking on the expand/collapse arrow, instead of left-clicking. The disadvantage, obviously, is that it opens the right-click menu, but it's better than activating the group and then having to find the entry again.

**Comment by ThiloteE** [comment] 2021-08-15 23:36
#3176 seems related. Very old issue.

**Comment by AEgit** [comment] 2021-12-11 15:24
I think, indeed, that this might be a duplicate of https://github.com/JabRef/jabref/issues/3176

Maybe the github-actions bot should bet set to check every year (or even longer time periods). It gets a bit annoying to have to update my bug old reports every 6 months, when they are still valid.

**Comment by Siedlerchr** [comment] 2022-05-22 15:25
Thanks to @LIM0000  this issue is now resolved in the latest development version.


We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed** 2022-05-22 15:25 UTC
Labels: ui, groups
