### ISSUE TITLE
Total Breakdown is back

### ISSUE THREAD

**Issue by oe1rsa** [JabRef/jabref#11466] opened 2024-07-09 11:07 UTC
### JabRef version

5.14 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 22.04

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

The problem does not occur with the development version, but I cannot install the development version via snap. Also the development version forgot all my settings and is not integrated into shell.
The problem appeared from transition of snap 5.13 to snap 5.14.

**Comment by Siedlerchr** [comment] 2024-07-09 11:31
I guess this is a snap thing that it stores the preferenes separately for each version

**Comment by oe1rsa** [comment] 2024-07-09 13:07
Oh, from your answer I guess my report was possibly misleading: Version 5.14 brought back the "Total Breakdown" bug. The latest release simply does not work for me, while 5.13 was fine. 5.14 throws exceptions when opening the edit making it completely unusable. 5.15, however appears to work again (but cannot be installed via snap, which is the only supported way of installing as I can see.)

**Comment by koppor** [comment] 2024-07-09 13:41
@oe1rsa I do not fully understand. I read that you use `snap` right? Then this is a duplicate of https://github.com/JabRef/jabref/issues/11465, isn't it? At the other report, I see some log file. At your report, I don't see a log file, thus it is harder for me to follow. Maybe, you can check if your log output is similar to the one of https://github.com/JabRef/jabref/issues/11465. If yes, we can close this issue as duplicate, can't we?

**Comment by oe1rsa** [comment] 2024-07-09 16:38
Ok, I try my best:

The log file in zipped form is more then 100 kB:
ls -l *.zip
-rw-rw-r-- 1 roland roland 123872 Jul  9 18:22 jabref.log.zip

I am not sure if this really will be helpful to post this into the message box. I provide a temporary link instead:
https://nx9524.your-storageshare.de/s/77mxf2RCGgzmdZa

Then, no the error is different than #1146.: jabref starts almost "normal", besides spilling out a lot of something to the console, than it looks somewhat different than how I left it before the upgrade: There are two panes. The left is the groups pane and the right the usual listing of database entries. However the split has move to the center of the screen.

Now when I click an entry I get an exception, ,opening details I further get:
![Bildschirmfoto vom 2024-07-09 18-29-29](https://github.com/JabRef/jabref/assets/3117116/b559d0b0-a885-4ced-a659-c0e37daa78e2)

The behavior is the same as described in this closed bug:  Total Breakdown #11188 

The same happened on two computers independently, both running Ubuntu 22.04LTS.

The bug obviously has been triggered by an automatic upgrade from 5.13 to 5.14. I would be glad is I could revert back to 5.13, but I am afraid snap will not let me.

**Comment by Siedlerchr** [comment] 2024-07-09 18:10
It's the same underlying issue as the other. 
As a temporary workaround try launching JabRef as follows

Go to /snap/jabref/3221/lib/runtime and run JabRef as program (right cllick "Run as program")

**Comment by Siedlerchr** [comment] 2024-07-09 18:10
Duplicate of #11465

**Closed by Siedlerchr** 2024-07-09 18:10 UTC
Labels: os: linux, os: snap

**Comment by Siedlerchr** [comment] 2024-07-09 21:32
The problem is now fixed, you can use jabref from the --edge channel until we do a new release tomorrow

**Comment by oe1rsa** [comment] 2024-07-10 16:29
Thank you for the fast fix!
