### ISSUE TITLE
Quitting JabRef throws exception and leaves zombie process

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#5946] opened 2020-02-14 09:25 UTC
JabRef 5.0-pull-5945-merge.421--2020-02-13--6cddf64
Linux 5.4.19-050419-generic amd64 
Java 13.0.2

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Start JabRef from the command line (w/o arguments)
2. Close it with `Ctrl-C` or `File->Quit` 
3. You should see an exception trace in the terminal (see below).
4. The output of `jobs` is 
[1]  + running    /opt/jabref/bin/JabRef
But JabRef should not be running anymore.
5. You can use `fg` and `Ctrl-C` to kill the process.
6. Occasionally, bib files are not closed leading to a _restore from backup_ message on startup. 

The exception trace contains the logger issue filed elsewhere but there is also an early GTK warning. Not sure whether this plays a role here or is just there because of the logger not initialised properly.

<details>
  <summary>Console output</summary>
  
  ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

(JabRef:31553): Gdk-WARNING **: 09:16:48.805: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
Exception in Application stop method
ERROR FallbackExceptionHandler Uncaught exception occurred in Thread[main,5,main]
 java.lang.RuntimeException: Exception in Application stop method
	at org.jabref.merged.module/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalAccessError: class kong.unirest.JsonObjectMapper (in module org.jabref.merged.module) cannot access class com.google.gson.Gson (in module com.google.gson) because module org.jabref.merged.module does not read module com.google.gson
	at org.jabref.merged.module/kong.unirest.JsonObjectMapper.<init>(Unknown Source)
	at org.jabref.merged.module/kong.unirest.Config.<init>(Unknown Source)
	at org.jabref.merged.module/kong.unirest.Unirest.<clinit>(Unknown Source)
	at org.jabref/org.jabref.Globals.stopBackgroundTasks(Unknown Source)
	at org.jabref/org.jabref.JabRefMain.stop(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$10(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	... 1 more

</details>

**Comment by Siedlerchr** [comment] 2020-02-14 10:08
I think the root cause is the same as in the other erorr, the gson module error

**Comment by AEgit** [comment] 2020-02-14 21:17
JabRef 5.0-beta.421--2020-02-14--ec93ad3
Linux 5.3.0-28-generic amd64 
Java 13.0.2

and 

JabRef 5.0-beta.421--2020-02-14--ec93ad3
Windows 10 10.0 amd64 
Java 13.0.2

I think this bug has been fixed in the current dev version (at least I cannot reproduce it anymore). @ytzemih : Can you confirm this?

**Comment by ytzemih** [comment] 2020-02-15 08:58
Yes, can confirm. Bug is fixed for me.

**Closed** 2020-02-18 16:21 UTC
