### ISSUE TITLE
Merge entries overwrites concurrently downloaded linked files

### ISSUE THREAD

**Issue by LinusDietz** [JabRef/jabref#3173] opened 2017-08-31 13:46 UTC
Concurrency is hard.

When incorporating a new BibEntry into the database the following can happen in der General Tab:

1) Click on "Get Fulltext", immediately after click on "Get bibtex data from DOI".
2) Start Merging the two entries.
3) The "Get Fulltext" operation is successful.
4) Confirm the merge with "Replace original BibTeX entry"

Result: The linked file is downloaded, but not linked anymore.

**Comment by stefan-kolb** [comment] 2017-09-01 11:08
I think there is just no concurrency there yet. Full text download also has problems when clicking it multilple times etc.

**Comment by tobiasdiez** [comment] 2017-10-20 08:26
I don't see a nice way to implement that the `Get bibtex data from DOI` button is disabled as soon as the user starts the fulltext search (these are two different editors and so far there is no way that two field editors communicate with each other). Since this is kind of an edge case (and in part an expected behavior), I would vote to close this issue as "wontfix".

Stefan, the fulltext search button should be replaced with a progress indicator as soon as you click it.

**Comment by lenhard** [comment] 2017-12-05 15:30
I second to tag this as won't fix.

**Comment by tobiasdiez** [comment] 2017-12-10 12:52
Ok, the consent seems to be to close this issue as wont-fix. Of course, we gladly accept PR's that improve upon the current concurrency behavior.

**Closed by tobiasdiez** 2017-12-10 12:52 UTC
Labels: bug, entry-editor, ui, wontfix
