### ISSUE TITLE
External viewer does not open

### ISSUE THREAD

**Issue by sfrankhtwk** [JabRef/jabref#556] opened 2015-12-21 15:07 UTC
With JabRef 3.0 on Windows 8.1, using jre1.8.0_66, and when the external pdf viewer is defined by MIME type, clicking the pdf symbol in the table view does not open the viewer for older pdf files in the database. Status line says "external viewer called". When setting the external application to the actual viewer (Acrobat), opening pdf on click works for all files.

**Comment by oscargus** [comment] 2015-12-27 15:02
Do you get any exceptions? (See Help -> Show error console -> Exceptions)

When you say "older", are those in the pdf-field or in the file-field?

**Comment by lenhard** [comment] 2015-12-28 15:46
@sfrankhtwk Any news regarding the questions from @oscargus ?

**Comment by sfrankhtwk** [comment] 2016-01-04 15:18
Dear Oscar,

sorry for the late reply, I could check that only after returning to my office.


-        There are no exceptions in the error log

-        The files are in the file field

Thanks for your help and kind regards

Stefan

Von: Oscar Gustafsson [mailto:notifications@github.com]
Gesendet: Sonntag, 27. Dezember 2015 16:02
An: JabRef/jabref <jabref@noreply.github.com>
Cc: Frank, Stefan <stefan.frank@htwk-leipzig.de>
Betreff: Re: [jabref] External viewer does not open (#556)


Do you get any exceptions? (See Help -> Show error console -> Exceptions)

When you say "older", are those in the pdf-field or in the file-field?

**Comment by stefan-kolb** [comment] 2016-01-25 15:46
@sfrankhtwk Could you provide an explicit example how we can reproduce this issue.
bib file, screenshots, explicit steps or anything the likes?

**Comment by stefan-kolb** [comment] 2016-02-10 23:43
@JabRef/developers I read something about older PDF files in the first post. Could this be related to the old PDF/PS fields?

**Comment by sfrankhtwk** [comment] 2016-02-18 17:36
Dear Mr. Kolb,

of course I can, please apologize my late answer.

When external file type PDF is set to application/pdf (see enclosed file not_working_settings.jpg), the following occurs:

-        Clicking on pdf symbol (red square) of an older database entry (time stamp 2014-…): status reads „external viewer called“ (Externer Betrachter aufgerufen), but pdf does not open; e.g. #14: Beese 2014 (see file pdf_does_not_open.jpg)

-        Clicking on pdf symbol of a more recent entry (time stamp 2016-…): same status, pdf opens; e.g. #1 IFLA Working Group … 2009 (see file pdf_opens.jpg)
When external file type PDF is set to the path of the pdf viewer (see file working_settings.jpg), the pdf opens in both cases, and the status ist he same

The database entries for the examples are:

@Article{114,
  Title                    = {Mit LENA zur Facharbeit : UB Chemnitz stellt Schülern virtuelle Lotsin zur Seite},
  Author                   = {Beese, Michael},
  Journal                  = {BIS : das Magazin der Bibliotheken in Sachsen},
  Year                     = {2012},
  Number                   = {2},
  Pages                    = {114-115},
  Volume                   = {5},
  File                     = {:Auskunft\\bis_5.2012.114.pdf:PDF},
  Keywords                 = {IJ. Reference work; CD. User training - promotion - activities - education; Informationsdienst; Informationskompetenz;Benutzerausbildung; E-Learning},
  Owner                    = {sfrank1},
  Review                   = {…},
  Timestamp                = {2014.08.14},
  URL                      = {http://nbn-resolving.de/urn:nbn:de:bsz:14-qucosa-89425}
}
@Book{GBV-604815212,
  Title                    = {National bibliographies in the digital age : guidance and new directions},
  Author                   = {{IFLA Working Group on Guidelines for National Bibliographies}},
  Editor                   = {\v{Z}umer, Maja},
  Publisher                = {Saur},
  Year                     = {2009},
  Address                  = {München},
  Series                   = {IFLA series on bibliographic control},
  Volume                   = {39},
  File                     = {:Literatur_NB\\nationalbibliographiesdigitalage\\9783598441844.fm.pdf:PDF},
  Owner                    = {sfrank1},
  Timestamp                = {2016-02-08}
}
Hence, the pdf is in the same field, in the same format.

I hope this helps.

Many thanks for your help.

Kind regards

Stefan

Von: Stefan Kolb [mailto:notifications@github.com]
Gesendet: Montag, 25. Januar 2016 16:47
An: JabRef/jabref <jabref@noreply.github.com>
Cc: Frank, Stefan <stefan.frank@htwk-leipzig.de>
Betreff: Re: [jabref] External viewer does not open (#556)


@sfrankhtwk<https://github.com/sfrankhtwk> Could you provide an explicit example how we can reproduce this issue.
bib file, screenshots, explicit steps or anything the likes?

**Comment by matthiasgeiger** [comment] 2016-03-02 19:07
Hi Stefan,
I'm currently investigating your reported issue but cannot reproduce it here.

As you answered directly via mail to to the notification of @stefan-kolb your attached screenshots are not visible for us at GitHub (here: https://github.com/JabRef/jabref/issues/556)

Could you please upload the screenshots there? 

What I currently understand (without seeing the screenshots) is, that the default viewer is not called correctly, but you have to provide an explicit path to the viewer to be called?

**Comment by sfrankhtwk** [comment] 2016-03-07 16:11
Dear Matthias,

here are the screenshots. 

I hope they will help you, but perhaps not -- your summary describes the problem perfectly well. Perhaps I should stress that this only occurs for data sets added before a certain (and not exactly known) time stamp. For more recent additions, everything works fine.

Thanks

Stefan

Settings with explicit path to viewer work for all data sets:
![working_settings](https://cloud.githubusercontent.com/assets/16386136/13574987/dba6d082-e486-11e5-85f5-9abfe46817cf.JPG)

Settings without explicit path to viewer do not work for older data sets:
![not_working_settings](https://cloud.githubusercontent.com/assets/16386136/13574991/e0958890-e486-11e5-8ca2-bdb6190ba783.JPG)

Status after failed call of pdf viewer:
![pdf_does_not_open](https://cloud.githubusercontent.com/assets/16386136/13574998/e646e91e-e486-11e5-8715-8fab1fedb9f3.JPG)

Status after successful call of pdf viewer (pretty much the same):
![pdf_opens](https://cloud.githubusercontent.com/assets/16386136/13575000/e9f215f2-e486-11e5-9180-7ec9bedb7845.JPG)

**Comment by tobiasdiez** [comment] 2016-03-07 16:30
Could you please also provide the bibtex code of an entry for which the pdf viewer was called successfully and for one entry where it was not successful. (I suspect you closed this issue by accident.)

**Comment by sfrankhtwk** [comment] 2016-03-07 16:43
Oops, I did.

For the BibTex code, please see my post above: data sets for Article{114} and Book {GBV-604815212}.

The error occurs irrespective of the actual subdirectory where the pdf file is stored.

**Comment by koppor** [comment] 2016-03-08 10:44
Is JabRef's log output enough to debug the issue? Can we track whether the viewer is correctly called? Can we track whether the file exsits according to JabRef?

**Comment by matthiasgeiger** [comment] 2016-03-16 08:31
@sfrankhtwk I recently fixed the bug which caused the red rectangle icons and we also worked on the calling of the external applications. Can you please check whether the problem still persists in the current development builds you can find here http://builds.jabref.org/master/.

Thank you!

**Comment by sfrankhtwk** [comment] 2016-03-22 10:22
Unfortunately, the external viewer still does not open.

**Comment by koppor** [comment] 2016-04-08 05:47
Is there any output in "Help" -> "Show error console"?

**Comment by Siedlerchr** [comment] 2016-04-10 10:46
@koppor  This could have been related to the thing I fixed in #1093
@sfrankhtwk  Could you please try again with a more recent development version?

**Comment by stefan-kolb** [comment] 2016-04-15 11:13
Could you please retry with the latest `master` build? Please try the latest build from http://builds.jabref.org/master.

**Comment by simonharrer** [comment] 2016-05-09 15:25
@sfrankhtwk can you have a look, please? Otherwise this issue will be closed in the next few days.

**Comment by simonharrer** [comment] 2016-05-10 14:18
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Closed by simonharrer** 2016-05-10 14:18 UTC
Labels: bug, waiting-for-feedback

**Comment by denoza** [comment] 2018-08-07 11:42
I am facing this issue with the latest 4.3.1 version on Linux Mint 19 Tara. It started to happen after I updated the operating system. If there are any logs that you may require, I am more than willing to provide. Thanks!

**Comment by arinik9** [comment] 2018-08-25 10:52
Like @denoza I am facing also the same issue (latest 4.3.1 version on Linux Mint 19 Tara Xfce). Actually, I am able top open an assoicated PDF file with 'Document Viewer', but I am not able to open it with 'Foxit reader'. I tought it was a permission problem, but apparently it is not since I installed Foxit with/without root permission. Thanks in advance!

**Comment by denoza** [comment] 2018-08-25 11:02
@arinik9 I was able to solve this issue on Linux Mint 19. In Options -> Manage External file types, edit PDF and write the directory address of your Foxit application, for me it was like `/home/xx/opt/foxitsoftware/foxitreader`.

**Comment by arinik9** [comment] 2018-08-25 14:06
Ok, thank you! Indeed, I was able to solve this issue by trying what you said

**Comment by kirk86** [comment] 2018-11-20 21:52
Apparently there is a bug as I understand it. And jabref devs should further investigate it. If one sets the expernal pdf viewer from Options->Preferences->External Programs then obviously it does not work. On linux it only works if one sets the viewer as recommended by @denoza. A noob question to the devs, why there's not consistency across user preferences?
