### ISSUE TITLE
About dialog hangs on OSX

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3651] opened 2018-01-19 13:27 UTC
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2-dev (on OS X)

Steps to reproduce:

1. Help > About JabRef
2. Close

The application hangs and it's only possible to "force quit" it.

**Comment by lenhard** [comment] 2018-01-19 13:39
Hi @j0hannes Please try to use meaningful issue titles.

I can't reproduce this on Windows. Since the About dialog is JavaFX, that's probably where the crash comes from.

**Comment by LinusDietz** [comment] 2018-01-19 15:21
Can't reproduce it. Did you have any entries in the log? Is is reproducible when you run it from command line? `java -jar jabref.jar` from http://builds.jabref.org/master ?

**Comment by Siedlerchr** [comment] 2018-01-19 15:23
Maybe an outdated Java version?

**Comment by j0hannes** [comment] 2018-01-19 16:24
There is no log entry, the application just doesn't respond anymore. Interestingly, closing the about window seems to be an easy task if the event log window is open at the same time.

My Java version is 1.8.0_31. I didn't upgrade to Java 9 yet because that would break compatibility with JabRef.

**Comment by lenhard** [comment] 2018-01-19 16:44
There should be a version check when starting JabRef that says that you need to have at least 1.8.0_144. Otherwise JavaFX is outdated and doesn't work. This has been discussed in multiple issues that you participated in, hasn't it? For example here: https://github.com/JabRef/jabref/issues/3505#issuecomment-350501659 I was taking for granted that you are aware of that.

Sorry, but then this issue is clearly invalid and you should update your Java version. I am a little bit annoyed that my time is being wasted like that, although you clearly could have known better.

**Comment by j0hannes** [comment] 2018-01-19 17:49
Nope, I wasn't aware of the particular version number and believed that it was up to date since my system told me so (I don't use Java at all). And yes, the application should definitely check all these things when starting. It would be even better to mention those requirements on the download page.

I also have wasted a lot of time manually restoring the entries that Jabref had secretly deleted. I can assure you that this was more than annoying to me. Nevertheless I think it is the best reference manager that I have tried so far, aside from some severe bugs that got fixed for the most part. The only way I can try to help is by reporting bugs that I detect, but I can as well stop it and save some (of my) time.

**Comment by tobiasdiez** [comment] 2018-01-19 19:03
There should actually be a version check when you start JabRef. 
Anyway, the bug you describe was reported before and was fixed in a recent Java update.

We are of course very grateful for bug reports and feature suggestions. But you should also understand that it is frustrating for us to get reports that are fixed by a simple update.

**Closed by tobiasdiez** 2018-01-19 19:03 UTC
Labels: invalid, osx

**Comment by j0hannes** [comment] 2018-02-23 13:46
The issue is back on 4.2-dev (with Java 1.8.0_161)
