### ISSUE TITLE
jabref not starting on Linux

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#7105] opened 2020-11-16 15:47 UTC
JabRef 5.2--2020-11-16--1dc91ca
Installed from rpm
Fedora Linux 33

After updating to the devel version of today the jabref fails to start with error message:

Error: Could not find or load main class org.jabref/org.jabref.gui.JabRefLauncher in module org.jabref

this is by executing /opt/jabref/bin/JabRef OR the script in /opt/jabref/lib/runtime/bin

Changing the srcript line to:
"$DIR/java"  -p "$DIR/../../app" -m org.jabref/org.jabref.gui.JabRefLauncher  "$@"
works.

**Comment by juejung** [comment] 2020-11-16 18:27
Same happens with .deb version https://builds.jabref.org/master/jabref_5.2-1_amd64.deb from 11/16/20 on Ubuntu 18.04.
Haven't tried changing the script line as suggested above.

**Comment by Siedlerchr** [comment] 2020-11-16 19:08
Hmm I did some changes yesterday,  to maybe revert some back. The script is normally auto-generated

**Comment by ilippert** [comment] 2020-11-17 06:35
Same here - does not start jabref-5.2.255-1.x86_64

**Comment by ilippert** [comment] 2020-11-17 06:40
> Changing the srcript line to:
> "$DIR/java" -p "$DIR/../../app" -m org.jabref/org.jabref.gui.JabRefLauncher "$@"
> works.
Maybe I misunderstood - I edited `/opt/jabref/lib/runtime/bin/JabRef`with the suggested line. Still does not run. 
Fedora 33.

**Comment by Siedlerchr** [comment] 2020-11-17 08:28
Can you please test the version from here? I reverted some changes, so hopeuflly it works again:
https://builds.jabref.org/pull/7107/merge/

**Comment by AtrusRiven** [comment] 2020-11-17 11:55
On Windows neither (no reaction at all). Neither with the actual master nor with the 7107 @Siedlerchr mentioned.

**Comment by juejung** [comment] 2020-11-17 14:02
Just tried https://builds.jabref.org/pull/7107/merge/
It still does not start. Tested on Ubuntu 20.04
I had to revert to the version from last Thursday (.deb package from 11/12/2020)

**Comment by sambo57u** [comment] 2020-11-17 14:27
Same here using the rpm version on Fedora 33. Here is one hint, the automatically generated script contains the line:

"$DIR/java"  -p "$DIR/../app" -m org.jabref/org.jabref/org.jabref.gui.JabRefLauncher  "$@"

note the repeated org.jabref after -m. Replacing this with:

"$DIR/java"  -p "$DIR/../app" -m org.jabref/org.jabref.gui.JabRefLauncher  "$@" 

works!

**Comment by Siedlerchr** [comment] 2020-11-17 15:31
@sambo57u  Thanks for the hint! 
Can you please all try with the new version from here? https://builds.jabref.org/pull/7107/merge/ That should be correct again

**Comment by juejung** [comment] 2020-11-17 16:05
Ok, the .deb version from https://builds.jabref.org/pull/7107/merge/  works again on Ubuntu 20.04. Thanks.

**Comment by sambo57u** [comment] 2020-11-17 16:25
It is also working (rpm version) on Fedora 33.

**Comment by AtrusRiven** [comment] 2020-11-17 16:28
Working for Win10, too. Thanks a lot!

**Comment by Siedlerchr** [comment] 2020-11-17 16:38
Thanks for the quick feedback! I merged the fix now (currently building) , so all master versions will then work again.
The culprit was a gradle update that required modifications withthe nodulebname

**Comment by ilippert** [comment] 2020-11-17 23:18
solved

**Closed** 2020-11-18 08:59 UTC
Labels: build-system, os: linux

**Comment by mlep** [comment] 2020-11-18 09:05
@ilippert With this version, and under Linux, JabRef opens but the "group" and the "web search" interfaces do not open. An exception is raised.
Do you have the same issue?

Exception details:
java.lang.IllegalStateException: Cannot load org.jabref.gui.groups.grouptree
	at org.jabref.merged.module@5.2.264/com.airhacks.afterburner.views.ViewLoader.load(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.groups.GroupSidePane.createContentPane(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.SidePaneComponent.getContentPane(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.SidePane.setComponents(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.SidePaneManager.updateView(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.SidePaneManager.show(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.SidePaneManager.toggle(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.SidePaneComponent$ToggleCommand.execute(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.2.264/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.2.264/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.264/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException: 
/org.jabref/org/jabref/gui/groups/GroupTree.fxml

	at org.jabref.merged.module@5.2.264/javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at org.jabref.merged.module@5.2.264/javafx.fxml.FXMLLoader.load(Unknown Source)
	... 52 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at org.jabref.merged.module@5.2.264/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	... 55 more
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.TreeItem.getValue()" because "<parameter1>" is null
	at org.jabref@5.2.264/org.jabref.gui.groups.GroupTreeView.getTreeItemByValue(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.groups.GroupTreeView.getTreeItemByValue(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.groups.GroupTreeView.selectNode(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.groups.GroupTreeView.selectNode(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.groups.GroupTreeView.lambda$initialize$0(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.util.BindingsHelper.bindContentBidirectional(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.util.BindingsHelper.bindContentBidirectional(Unknown Source)
	at org.jabref@5.2.264/org.jabref.gui.groups.GroupTreeView.initialize(Unknown Source)
	... 65 more

**Comment by Siedlerchr** [comment] 2020-11-18 09:10
@mlep  The group error is probably related to another issue which was fixed recently

**Comment by mlep** [comment] 2020-11-18 09:15
@Siedlerchr OK, thanks for the info. I will wait for the next build.

**Comment by ilippert** [comment] 2020-11-18 09:19
> @ilippert With this version, and under Linux, JabRef opens but the "group" and the "web search" interfaces do not open. An exception is raised.
> Do you have the same issue?

at
JabRef 5.2--2020-11-17--a335f0d
Linux 5.9.8-200.fc33.x86_64 amd64 
Java 15.0.1
I cannot use the Google Search; but I can use the groups.

**Comment by mlep** [comment] 2020-11-18 12:33
In JabRef 5.2--2020-11-18--6669a6e too, The group window does not open and an exception is raised.
@Siedlerchr: please, could you point me to the relevant issue?

**Comment by Siedlerchr** [comment] 2020-11-18 12:43
@mlep  #6999 and #7096  was the fix. Guess it may have something to do with the group color stuff

**Comment by mlep** [comment] 2020-11-19 11:00
@Siedlerchr Does it require a new issue to be created?

**Comment by Siedlerchr** [comment] 2020-11-21 16:56
@mlep  Does it work again in the latest master?

**Comment by sambo57u** [comment] 2020-11-21 17:08
Yes, it is working on the current master jabref-5.2.272

**Comment by mlep** [comment] 2020-11-21 19:35
@Siedlerchr I still have the issue with the group panel with the version
JabRef 5.2--2020-11-21--6f35c36
Linux 4.19.0-12-amd64 amd64 
Java 15.0.1

Some details: 
With the group panel initially closed,
- if no file is opened on startup, the group panel opens and closes fine.
- if a file (like https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/jabref-authors.bib) is already opened at startup, opening the group panel raises an exception:

Uncaught exception occurred in Thread[JavaFx Application Thread,5,main]
Cannot load org.jabref.gui.groups.grouptree
java.lang.IllegalStateException: Cannot load org.jabref.gui.groups.grouptree
	at org.jabref.merged.module@5.2.288/com.airhacks.afterburner.views.ViewLoader.load(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupSidePane.createContentPane(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneComponent.getContentPane(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePane.setComponents(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneManager.updateView(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneManager.show(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneManager.toggle(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.SidePaneComponent$ToggleCommand.execute(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.actions.JabRefAction.lambda$new$3(Unknown Source)
	at org.jabref.merged.module@5.2.288/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.2.288/org.controlsfx.control.action.Action.handle(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.scene.control.MenuItem.fire(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.2.288/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: javafx.fxml.LoadException: 
/org.jabref/org/jabref/gui/groups/GroupTree.fxml

	at org.jabref.merged.module@5.2.288/javafx.fxml.FXMLLoader.constructLoadException(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.fxml.FXMLLoader.loadImpl(Unknown Source)
	at org.jabref.merged.module@5.2.288/javafx.fxml.FXMLLoader.load(Unknown Source)
	... 52 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at org.jabref.merged.module@5.2.288/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	... 55 more
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.scene.control.TreeItem.getValue()" because "<parameter1>" is null
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.getTreeItemByValue(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.getTreeItemByValue(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.selectNode(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.selectNode(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.lambda$initialize$0(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.util.BindingsHelper.bindContentBidirectional(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.util.BindingsHelper.bindContentBidirectional(Unknown Source)
	at org.jabref@5.2.288/org.jabref.gui.groups.GroupTreeView.initialize(Unknown Source)
	... 65 more
