### ISSUE TITLE
Deacativating AutoCompletion disables EntryEditor

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#325] opened 2015-11-12 12:33 UTC
With the attached configuration, the editor of JabRef 2.11 does not open.

After resetting the preferences, the editor opens fine.

[jabref211_preferences_editing_not_possible.txt](https://github.com/JabRef/jabref/files/32854/jabref211_preferences_editing_not_possible.txt)

**Comment by matthiasgeiger** [comment] 2015-11-12 12:59
Confirmed  - also for master.

**Comment by matthiasgeiger** [comment] 2015-11-12 14:14
Caused by a `NullPointerException` if the autoCompletion is deactivated in the preferences.

Just fixed it in master.

**Comment by matthiasgeiger** [comment] 2015-11-13 08:37
Closing this as @koppor backported the fix to 2.11dev, too.

**Closed by matthiasgeiger** 2015-11-13 08:37 UTC
Labels: bug
