### ISSUE TITLE
Freezes under Linux

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#3234] opened 2017-09-26 01:36 UTC
JabRef 4.0-dev--snapshot--2017-09-23--master--8a420b4fc
Linux 4.10.0-35-generic amd64 
Java 1.8.0_144

And also other versions over the last ten days.

Steps to reproduce:

I don't know what to say, because it's not predictable.  Maybe when I'm editing the biblatex source tab?
I'm sorry to be so vague. If you give me instructions about scraping up a logfile, I'll gladly do it.

It's bad enough that I've gone back to JabRef version 3.8.2 for real work.  But I'm missing all the cool stuff in 4!

Dominik

**Comment by lenhard** [comment] 2017-09-26 07:26
Sorry, but based on that description there's little we can do at this end.

If there are random freezes for different releases then this sounds more like an environmental problem to me. Maybe something is broken in your distro/JRE installation?

**Comment by wujastyk** [comment] 2017-09-26 13:37
Yes, I thought that too.  I'm getting the lockups on three different
machines, but they are all similar in running Linux Mint and Oracle Java 8.

**Comment by lenhard** [comment] 2017-09-26 14:54
Ok, if you see freezes on Linux Mint, then this sounds very much like #2963

**Comment by wujastyk** [comment] 2017-10-01 01:58
Yes, it does sound like #2963.
I was able to generate a freeze in JabRef 4.0-dev--snapshot--2017-09-23--master--8a420b4fc by editing in the "biblatex source" tab and then trying to go back to "required fields".

Today I'm using 
JabRef 4.0-dev--snapshot--2017-09-29--master--6cca2ed32
Linux 4.10.0-35-generic amd64 
Java 1.8.0_144

and I haven't had any freezes.

**Comment by wujastyk** [comment] 2017-10-01 18:29
JabRef 4.0-dev--snapshot--2017-09-29--master--6cca2ed32
Linux 4.10.0-35-generic amd64 
Java 1.8.0_144

New freeze.

In the editor, I switched to the "Optional fields" tab, and selected the ISBN for copying to a website.  When I came back to JabRef, it was frozen.

**Comment by wujastyk** [comment] 2017-10-02 02:37
Same version of JabRef (29 Sept):

Just generated a freeze by trying to drag-and-drop a PDF from Nemo to the "General" tab of the editor.  After "$ killall java", I restarted JabRef and the file reference was correctly present.  So the freeze must have happened after the data was written.

**Comment by lenhard** [comment] 2017-10-05 13:40
The same problems in Ubuntu: #3261

**Comment by vsht** [comment] 2017-10-05 15:37
JabRef 4.1-dev--snapshot--2017-10-04--master--effe3349e
Linux 4.12.14-300.fc26.x86_64 amd64 
Java 1.8.0_144

I think that I found a workaround for this issue. I'm on Fedora 26 and I experienced all the issues that other users reported, i.e. version 4 freezes no matter what you do but especially when you want to use groups. I also installed Open JavaFX (`sudo dnf install openjfx`) and Oracle Java 8 but that did not help.

However, rather by accident I noticed that if I change `Class name` in `Options -> Look and Feel` from 
`com.sun.java.swing.plaf.gtk.GTKLookAndFeel` to `javax.swing.plaf.metal.MetalLookAndFeel`, then everything starts working as it should: I can use groups and do what whatever I want and JabRef does not freeze anymore. The UI of course look uglier now, but I don't really care.

So guys, try changing that option and see if it helps. To me it clearly looks like an issue with GTK.

**Comment by wujastyk** [comment] 2017-10-05 16:33
Hmm.  I've been using com.sun.java.swing.plaf.gtk.GTKLookAndFeel  all
along, and had freezes.  Maybe it's the *changing* of this setting that
improves things.  I'm experimenting with the "plastic" look.

Dominik
​

**Comment by mutlusun** [comment] 2017-10-06 08:23
Hello,

I can confirm this. Switching from the GTK theme to the default theme solved my issue of freezes after working with the source field! Thanks for your investigation!

**Comment by lenhard** [comment] 2017-10-06 08:41
That's great news overall, at least we roughly know how this can be solved now. We should include a discussion of the freeze problem under Linux and the solution (change of look and feel) in the documentation.

I am just a little weary, because I would not be surprised if the support for different look and feels varies on different Linux distributions.

**Comment by Siedlerchr** [comment] 2017-10-06 11:18
Unter XFce I could not reproduce this directly, I use com.jgoodies.looks.plastic.Plastic3DLookAndFeel

**Comment by lenhard** [comment] 2017-10-19 13:09
I have now added a note on the freezes and look and feels in the installation notes with fc73aba26ad24a5498e67ef79748b3973fb77ed3

I'll close this issue now. I would expect that freezes issues that are not solved by changing the look and feel are actual bugs and these should be tracked in separate issues.

**Closed by lenhard** 2017-10-19 13:09 UTC
Labels: documentation, linux
