### ISSUE TITLE
Hangs after editing abstract of existing entry

### ISSUE THREAD

**Issue by ziggystar** [JabRef/jabref#2489] opened 2017-01-26 11:31 UTC
## Versions

- JabRef version 3.8.1 
- on Ubuntu 16.04
 - java version "1.8.0_121" (oracle)

## Issue
The program hangs with no CPU utilization after editing an abstract (removing a HTML code and replacing it with the word 'and'). I don't know whether this is reproducible, simply editing an abstract didn't do it. 

But I have a thread dump attached. I think it's some kind of deadlock/race condition, and I hope you can diagnose it from the stack traces.
[jabref-thread-dump.zip](https://github.com/JabRef/jabref/files/732157/jabref-thread-dump.zip)

**Comment by koppor** [comment] 2017-01-26 14:18
Could you a) try to reproduce? b) provide us the abstract?

Here, I can edit the abstract without issues.

Am 26.01.2017 12:31 schrieb "ziggystar" <notifications@github.com>:

**Comment by ziggystar** [comment] 2017-01-26 22:11
I tried for a bit and I can't reproduce it. I don't know exactly what I clicked after editing the abstract. 

I looked a bit into the sources and couldn't find an obvious issue with the locking.

- The deadlock is not visible inside the stack trace, for me. Not within the Swing thread itself, and also no other thread appears to be holding a lock. This hinges on me recognizing the places where a lock is held. See next.
- I roughly checked the places where `writeLock().lock()` (by find usages on `writeLock()`) is called and they all have an `unlock()` within a `finally`, except one which could be an issue if unchecked exceptions are thrown/**caught** within the JabRef source code:
    ````
        sortedEntries.getReadWriteLock().writeLock().lock();
        comparatorChooser.appendComparator(PAD, 0, false);
        sortedEntries.getReadWriteLock().writeLock().unlock();
    ````

Here is the relevant part of the stack; apparently I hit a key that triggered the save database action. That's quite possible.

```
"AWT-EventQueue-0" #14 prio=6 os_prio=0 tid=0x00007f365c782000 nid=0x4919 waiting on condition [0x00007f36121c0000]
<snip>
	at ca.odell.glazedlists.impl.java15.LockAdapter.lock(J2SE50LockFactory.java:85)
	at net.sf.jabref.gui.maintable.MainTableDataModel$StartStopListFilterAction.update(MainTableDataModel.java:237)
	at net.sf.jabref.gui.maintable.MainTableDataModel$StartStopListFilterAction.start(MainTableDataModel.java:229)
	at net.sf.jabref.gui.maintable.MainTableDataModel.updateSearchState(MainTableDataModel.java:95)
	at net.sf.jabref.gui.search.SearchWorker.updateUIWithSearchResult(SearchWorker.java:88)
	at net.sf.jabref.gui.search.SearchWorker.done(SearchWorker.java:57)

<maybe the fact it's a timer is interesting>
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
<snip>
	at net.sf.jabref.gui.BasePanel.runCommand(BasePanel.java:1002)
	at net.sf.jabref.gui.entryeditor.EntryEditor$SaveDatabaseAction.actionPerformed(EntryEditor.java:1379)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
<snip>
```

**Comment by paulsputer** [comment] 2017-02-03 20:34
Just been debugging #2482 and found similar deadlock.  Screenshots attached for _AWT-EventQueue-0_
and _JabRef CachedThreadPool_

![awt-eventqueue-0](https://cloud.githubusercontent.com/assets/4686906/22607463/ead255f2-ea4f-11e6-94c2-dbd31480e9cc.png)


![cachedthreadpool](https://cloud.githubusercontent.com/assets/4686906/22607464/ead5679c-ea4f-11e6-9376-7e3303a0264e.png)

**Comment by paulsputer** [comment] 2017-02-03 22:07
This appears to be caused by updates to the UI on multiple threads.  @ziggystar if you can look at what the other threads are doing that may be able to track it down.  See my screenshots above to identify the deadlock (waiting for / waited by), then work down the list until you get to a call that is the JabRef code, i.e. on with a line number.

**Comment by lenhard** [comment] 2017-10-10 10:12
There's a good chance that this is solved on 4.0, because the entry editor has been largely re-written.

@ziggystar @paulsputer Can you please try out the most recent version and see if the issue persists?

**Comment by ziggystar** [comment] 2017-10-11 08:56
@lenhard I've already stated that I cannot reproduce this bug, and the stack dump is all I can provide. Apparently it's some kind of race condition.

**Comment by lynyus** [comment] 2017-10-11 10:15
Then I'll close it for now. Feel free to reopen if the problem occurs again.

**Comment by ziggystar** [comment] 2017-10-11 10:37
Quite funny. I downloaded 4.0 and used it for some minutes, then I got another deadlock. I have a thread dump attached. It occurred after I clicked "accept changes" (or similar) of the dialog you get when fetching and updating entry items using a DOI.


[thread dump](https://github.com/JabRef/jabref/files/1375222/jabref-deadlock.tdump.txt)

**Comment by lynyus** [comment] 2017-10-11 10:44
Thanks, @ziggystar!

**Comment by ramiromagno** [comment] 2017-12-31 15:40
Here's another way for jabref to hang with same symptoms..

jabref installation details:

JabRef 4.2-dev
Linux 4.14.6-1-arch amd64 
Java 1.8.0_144

Steps to reproduce the error:

1. Launch jabref
2. Use "Web Search", pick "Medline/PubMed", search with the term "pcr".
3. Deselect all hit results, and pick "Carow et al." 
_(Carow, K.; Read, C.; Häfner, N.; Runnebaum, I. B.; Corner, A. & Dürst, M.
A comparative study of digital PCR and real-time qPCR for the detection and quantification of HPV mRNA in sentinel lymph nodes of cervical cancer patients. 
BMC research notes, 2017, 10, 532 )_
4. With "Carow et al." entry selected go to the "Quality" menu and choose "Look up full text documents".
5. Press "OK" on that popup window and voila jabref is frozen.

**Comment by ramiromagno** [comment] 2017-12-31 15:42
BTW, this problem was already present in version 4.1.

**Comment by lenhard** [comment] 2018-02-06 20:19
@ramiromagno Thanks for the precise workflow. I just tried to reproduce the bug with your exact steps and JabRef did not freeze. Instead the pdf download window appeared and I could link a pdf to the entry. Maybe the freeze came from your network connection or a firewall blocking the download?

**Comment by ramiromagno** [comment] 2018-02-06 21:01
@lenhard I can't reproduce this error anymore... Sorry! I am not sure what I've done in jabref since last time that might have made the error disappear.

**Closed** 2018-02-06 21:08 UTC
Labels: waiting-for-feedback

**Comment by ziggystar** [comment] 2018-02-06 21:18
C'mon. You cannot close this issue because someone can't reproduce a race condition. And he is not the only one experiencing this.

**Comment by koppor** [comment] 2018-02-06 21:25
We currently have no money to pay someone for that ([donations page](http://donations.jabref.org)). No one of the JabRef team gets paid for JabRef. Thus, working on this really depends on the availability of our personal free time. - We really welcome feedback on our volunteer work. In case you can spend some more time (other than reporting issues), we would really like to encourage you to check https://help.jabref.org/en/FAQcontributing - especially the part asking for improvement of our [help pages](https://help.jabref.org/en/). This would help JabRef getting better as a whole. 🥇

**Comment by ziggystar** [comment] 2018-02-06 21:42
This means tickets for existing bugs must get closed, because no one is working on them. And if someone comes along in the future, maybe someone experiencing this same bug, he shall not find this thread with lots of valuable information? If you think that's a good idea…
