### ISSUE TITLE
Delete and Cut functionalities do not work anymore

### ISSUE THREAD

**Issue by AlexPars** [JabRef/jabref#6738] opened 2020-08-05 13:04 UTC
JabRef development Release as of August 5, 2020, on Windows 10

Issue: Delete and Cut functionalities do not work anymore

I was not able to delete an entry. I have tried Delete from Edit menu, Delete icon, Cut from Edit Menu

**Comment by Siedlerchr** [comment] 2020-08-05 14:24
Duplicate of #6293 This is a side effect of my recent mac fix. Will try to add a workaround.
Keyboard shortcuts do work fine

**Closed by Siedlerchr** 2020-08-05 14:24 UTC
