### ISSUE TITLE
Validation messages are displayed at wrong position

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#3145] opened 2017-08-22 14:22 UTC
Latest master. The validation messages in the entry editor are shifted to the bottom (by what appears to be a fixed constant):
![image](https://user-images.githubusercontent.com/5037600/29570175-f90a1d8c-8755-11e7-9b57-2ff7e3e7bbfa.png)

**Comment by lenhard** [comment] 2017-08-22 15:24
Confirmed, but it's not only that.

For me, DOI and URL warnings in the general fields tab are shifted upwards by a threshold.

I just reset my master branch to the beta3 and it was already broken there. Now I wonder, did the feature ever work? Were there library updates that broke this? We surely didn't change the code.

**Comment by tobiasdiez** [comment] 2017-08-23 11:50
No it never worked as desired (I just tested it with my original branch). I filed [a bug report at controlsfx](https://bitbucket.org/controlsfx/controlsfx/issues/791/update-position-of-decoration-when-target).

**Comment by lenhard** [comment] 2017-08-23 11:57
Damn :-( How did we not see that? I was very convinced that I saw it working.

What does that mean for 4.0? I would suggest that we add a preference options for enabling/disabling validation that is initially set to disabled. When the feature works properly, we can add the UI part to that allows you to enable the preference. That way, we keep the code, but do not annoy users.

**Comment by matthiasgeiger** [comment] 2017-08-23 12:09
Strangely if I click into an "invalid" editor field the sign is then positioned at the right position...  and yes: I first noticed this in the branch of @lenhard's resizing - and I was pretty sure that I have never seen it displayed in that wrong way before... 😕

**Comment by koppor** [comment] 2017-08-25 05:28
@matthiasgeiger I would assume that with the CSS patch by @lenhard leads to the initial size not being 0 and thus the issue https://bitbucket.org/controlsfx/controlsfx/issues/791/update-position-of-decoration-when-target is risen:

> The problem is that size listener is only registered if the initial size was 0

Please sign it at bitbucket and cast a vote for the issue. Maybe that helps to get the CustomFX library fixed.

**Comment by lenhard** [comment] 2017-08-25 07:44
@koppor My CSS patch is not the cause. We are talking about the master branch here and my patch is still an unmerged PR.

**Comment by lenhard** [comment] 2017-08-27 16:13
The validation feature is now masked by a preference option. It will be re-enabled once the bug is fixed in controlsfx.

**Closed** 2018-01-12 15:19 UTC
Labels: entry-editor, feature
