### ISSUE TITLE
Custom field does not allow to enter text anymore

### ISSUE THREAD

**Issue by johann-petrak** [JabRef/jabref#5083] opened 2019-06-28 12:47 UTC
Have created a new entry field on a separate tab (line "Content:content" in the set general fields config) when I starteded using JabRef at version 3. This showed the field as a big entry field over the whole space of the tab and allowed me to enter arbitrary many lines of text, with deliberate newlines added.

I am now using version 5.0-dev and the same field is just shown as a single line, centered on the tab and there is no way to enter more than one line of text. 

Saving notes, a summary of the content etc about a reference that way was a crucial feature that made me adopt JabRef, why does this not work any more as expected? Is there a new way to get that behaviour back?

Using
JabRef 5.0-dev--snapshot--2019-06-16--master--8d99db113
Linux 4.15.0-52-generic amd64
Java 1.8.0_172

**Comment by ilippert** [comment] 2019-06-28 12:55
this is the same as #5021, I think

**Comment by tobiasdiez** [comment] 2019-06-28 15:25
Duplicate of #5021

**Closed by tobiasdiez** 2019-06-28 15:25 UTC
