### ISSUE TITLE
Revive option to switch between tab-specific and global search

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#6045] opened 2020-02-28 18:01 UTC
**Is your suggestion for improvement related to a problem? Please describe.**
In JR3/4, I was able to enter a search term and change between tabs and browse the different search results (that were carried through simultaneously for each file after hitting Enter). 
I am severely missing this option in JR5. At least, I was unable to find it.
(Using JabRef 5.0-pull-5945-merge.440--2020-02-19--fcaeef1)

**Describe the solution you'd like**
I don't know whether the tab-specific search is a feature or a bug.
However, I suggest to have an option in the setting that allows one to switch between 

1. _tab-specific search_ (the search field content is changed simultaneously with the tab change) and
2. _global search_ (the search field content is applied to all open tabs like in JR3/4)

Thanks.

**Comment by Siedlerchr** [comment] 2020-03-01 18:02
Duplicate of  #4096

**Closed by Siedlerchr** 2020-03-01 18:02 UTC
