### ISSUE TITLE
The search box chokes for unknown reasons

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3866] opened 2018-03-19 18:29 UTC
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-03-12--master--586b934ba
Windows 7 6.1 amd64 
Java 1.8.0_161

With the snapshot I get strange behavior in the search box. Unfortunately I have not been able to reliably reproduce it.

![grafik](https://user-images.githubusercontent.com/9216487/37614646-9091e91a-2bab-11e8-955a-f331fc22fb98.png)
 
This time I got the shift key fixed and number turned out as parentheses. When I tried to correct, jabref got stuck. 

<details>
  <summary>Log File</summary>
  
  ```
  Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException
	at com.sun.javafx.text.PrismTextLayout.getCaretShape(PrismTextLayout.java:317)
	at javafx.scene.text.Text$TextAttribute$11.computeValue(Text.java:1787)
	at javafx.scene.text.Text$TextAttribute$11.computeValue(Text.java:1777)
	at javafx.beans.binding.ObjectBinding.get(ObjectBinding.java:153)
	at javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:50)
	at javafx.beans.property.ObjectPropertyBase.get(ObjectPropertyBase.java:132)
	at com.sun.javafx.scene.control.skin.TextFieldSkin.lambda$new$198(TextFieldSkin.java:233)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.access$000(ObjectPropertyBase.java:51)
	at javafx.beans.property.ObjectPropertyBase$Listener.invalidated(ObjectPropertyBase.java:233)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:172)
	at javafx.scene.text.Text.impl_geomChanged(Text.java:769)
	at javafx.scene.text.Text.needsTextLayout(Text.java:194)
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:189)
	at javafx.scene.text.Text.access$200(Text.java:95)
	at javafx.scene.text.Text$2.invalidated(Text.java:389)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
	at javafx.beans.property.StringPropertyBase.access$000(StringPropertyBase.java:49)
	at javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:230)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.binding.StringBinding.invalidate(StringBinding.java:171)
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389)
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393)
	at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1332)
	at javafx.scene.control.TextInputControl$TextProperty.access$1600(TextInputControl.java:1300)
	at javafx.scene.control.TextInputControl.lambda$new$162(TextInputControl.java:139)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextField$TextFieldContent.insert(TextField.java:87)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1204)
	at javafx.scene.control.TextInputControl.updateContent(TextInputControl.java:556)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:548)
	at com.sun.javafx.scene.control.skin.TextFieldSkin.replaceText(TextFieldSkin.java:576)
	at com.sun.javafx.scene.control.behavior.TextFieldBehavior.replaceText(TextFieldBehavior.java:202)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.defaultKeyTyped(TextInputControlBehavior.java:238)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.callAction(TextInputControlBehavior.java:139)
	at com.sun.javafx.scene.control.behavior.BehaviorBase.callActionForEvent(BehaviorBase.java:218)
	at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.callActionForEvent(TextInputControlBehavior.java:127)
	at com.sun.javafx.scene.control.behavior.BehaviorBase.lambda$new$74(BehaviorBase.java:135)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$null$299(EmbeddedScene.java:310)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.EmbeddedScene.lambda$keyEvent$300(EmbeddedScene.java:296)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.IndexOutOfBoundsException: Cannot get at -1 on list of size 1
	at ca.odell.glazedlists.TransformedList.get(TransformedList.java:105)
	at org.jabref.gui.maintable.MainTable.getEntryAt(MainTable.java:343)
	at org.jabref.gui.maintable.MainTable.getCellStatus(MainTable.java:476)
	at org.jabref.gui.maintable.MainTable.getCellRenderer(MainTable.java:287)
	at org.jabref.gui.maintable.MainTable.getToolTipText(MainTable.java:228)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
  ```
</details>

**Comment by Siedlerchr** [comment] 2018-03-19 19:04
Probably some threading issue due to Swing and FX stuff
That sounds really like this bug here:
https://bugs.openjdk.java.net/browse/JDK-8195739

**Comment by bernhard-kleine** [comment] 2018-03-19 21:40
With 4.1 stable(?) I get the following
![grafik](https://user-images.githubusercontent.com/9216487/37623763-1ceac9ee-2bc6-11e8-8328-9e62c1053baa.png)

the protocol box when looked at is empty (nothing shown), the same is true for
the about Jabref box (my jabref is german speaking; the termini technici might be wrong)

**Comment by wilthan** [comment] 2018-03-20 21:56
We also see this problem on a daily base and noticed it first with version 4.0.
Since then it hasn't changed, is not reproducible and the only workaround is to close quit JabRef and reopen it. Then it works again for maybe 10min or the rest of the day.

**Comment by Sethur** [comment] 2018-03-21 08:57
I see this behavior too on the latest stable version with:

JabRef 4.1
Windows 7 6.1 amd64 
Java 1.8.0_161

We have a 4.5 MiB database with around 1800 entries and the search box randomly locks up. The only resolution is a restart.

**Comment by stefan-kolb** [comment] 2018-04-06 09:02
I also expected endless loop with the search box right now:
```
11:01:45.439 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
11:01:45.455 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
11:01:45.471 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
11:01:45.487 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
```

**Comment by stefan-kolb** [comment] 2018-04-06 10:02
Maybe even when the results are empty produced by the search?!

**Comment by Siedlerchr** [comment] 2018-04-13 20:07
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Closed by Siedlerchr** 2018-04-13 20:07 UTC
Labels: bug, search, ui

**Comment by javicacien** [comment] 2018-06-07 21:07
This behavior (search box choking) appears again in version 4.3.1, with any search terms.
Pardon my ignorance, but, could this problem be related with the fixed-width nature of the search box? It should be wider to accommodate complex searches, and also its width should be variable.
System info:
Windows 7 64 bit
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) Client VM (build 25.171-b11, mixed mode)
java version:  1.8.0_171

**Comment by stefan-kolb** [comment] 2018-06-07 21:16
Please try to Upgrade Java to v172 and Report if it still occurs.

javicacien <notifications@github.com> schrieb am Do., 7. Juni 2018, 23:07:

**Comment by tobiasdiez** [comment] 2018-06-08 07:51
The search bar in the latest development build http://builds.jabref.org/master/ also expands in size when you focus it. (Please remember to make a backup of your library before trying-out this version.)

**Comment by javicacien** [comment] 2018-06-12 19:40
Please explain me exactly how to get v172. Following advice from a previous post I tried to upgrade to java v172 (my system is windows 7 64bit). First I uninstalled my current java, rebooted the system, and then downloaded and isntalled Java SE Runtime Environment 8u172, but ...
- My 32bit installation of JabRef did not find a JRE, and it refused to UNinstall because of it
- Then I downloaded and installed JabRef 64bit, reboot included
- The 64bit JabREf refuses to run because it does not find a suitable JRE ...

**Comment by Siedlerchr** [comment] 2018-06-12 19:57
Hi, 64bit JabRef requires 64bit Java 
You can get it here:
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

You don't need to uninstall JabRef. Just uninstall java and install the new version

**Comment by javicacien** [comment] 2018-06-14 16:12
At last the problem dissapears with the following combination
JabRef 4.3.1 (64bit)
Windows 7 6.1 amd64 
Java 1.8.0_172 (64bit)
The bug seems related to Java 1.8.0_171
P. D.
The windows UNistallation seems tethered to the java engine. JabRef 32bit refuses to uninstall if Java has been upgraded to 64bit. I had to manually wipe out JabRef.

**Comment by stefan-kolb** [comment] 2018-06-14 16:15
Thanks for clarification. @jabrefdevelopers we need to Upgrade to 172
again, probably...

javicacien <notifications@github.com> schrieb am Do., 14. Juni 2018, 18:13:
