### ISSUE TITLE
Cursor jumps to start of field

### ISSUE THREAD

**Issue by EtienneHanelt** [JabRef/jabref#6628] opened 2020-06-20 15:33 UTC
JabRef version 5.1--2020-06-17--ef0a6bb
 on Linux 5.6.0-1011-oem amd64 (Ubuntu 20.04)

- [y] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

When trying to type anything, the cursor jumps to the beginning of the field, making it impossible to type. This happens every time. The bug was introduced a couple of weeks ago. I tried both the snap and the .deb development snapshots.

Steps to reproduce the behaviour:
1. Open entry field, for example "Comments"
2. Type something.
3. Cursor jumps to the beginning of the first line after a second.

**Comment by Siedlerchr** [comment] 2020-06-22 05:34
Duplicate of #5904 
We are working on a fix

**Closed by Siedlerchr** 2020-06-22 05:34 UTC

**Comment by scotpatti** [comment] 2023-01-18 19:21
Version 5.9 on windows - It doesn't do this after every character or even every word consistently, but occasionally (noticed in comment field) it still happens. I'm guessing it has to do with updating the entry view.

**Comment by TimVWese** [comment] 2023-06-28 09:25
I experience the same as @scotpatti on Ubuntu.

JabRef 5.9--2023-01-08--76253f1a7
Linux 5.19.0-45-generic amd64 
Java 19.0.1 
JavaFX 19+11
