### ISSUE TITLE
Back and Forward arrows don't restore entry view tab

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2984] opened 2017-07-09 06:34 UTC
If I move around the entry history using the Back and Forward icons, Jabref does move between entries but it always shows the "Required fields" tab instead of the tab I was originally on.  For example, if I want to flip between the "Review" tabs of many papers I have recently visited, I now have to reclick "Review" every time I go to a new paper.

If I remember correctly, the previous version of JabRef would have restored the view to the "Review" tab.

JabRef 4.0.0-dev--snapshot--2017-07-07--master--eaf53f75d
Windows 7 6.1 amd64 
Java 1.8.0_131

**Comment by Siedlerchr** [comment] 2017-07-09 15:31
Duplicate of #2896

**Closed by Siedlerchr** 2017-07-09 15:31 UTC
