### ISSUE TITLE
"JabRef.app" is damaged ....

### ISSUE THREAD

**Issue by LukasCBossert** [JabRef/jabref#9594] opened 2023-02-02 19:16 UTC
### JabRef version

5.9 (latest release)

### Operating system

macOS

### Details on version and operating system

13.2

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Install JabRef (also latest nightly build)
2. Try to open it.
3. See the message:

![image](https://user-images.githubusercontent.com/12896078/216427985-de0964d9-abd5-4298-9528-75240486a49e.png)

**Comment by Siedlerchr** [comment] 2023-02-02 20:57
Duplicate of  #9553 
execute `xattr -d com.apple.quarantine /Applications/JabRef.app`

**Closed by Siedlerchr** 2023-02-02 20:57 UTC
