### ISSUE TITLE
Medline import, with italicized words, becomes faulty.

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4809] opened 2019-03-25 19:21 UTC
JabRef 5.0-dev--snapshot--2019-03-20--master--6c61664a8
Windows 7 6.1 amd64 
Java 1.8.0_201

<
- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Pubmed has added italics support and titles are shown with single words in italics. 
![grafik](https://user-images.githubusercontent.com/9216487/54947602-ffcf8b80-4f3a-11e9-917a-c65aa43fb51d.png)
The Jabref import is not capable to deal with these italics. It shows some cryptic `, javax.xml.bind.JAXBElement@64ced3bd, ` which is not help full. I copied the title line from Pubmed without problems to Jabref, the italics were gone but the words were there. Furthermore I copied the same line to an xml editor and it was shown as
`A sleep-inducing gene, <emphasis role="italic">nemuri</emphasis>, links sleep and
            immune function in <emphasis role="italic">Drosophila</emphasis>.`

1. Import PMID 30705188 into Jabref using the Websearch.
2. ...
3. ...

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by matthiasgeiger** [comment] 2019-03-25 19:39
Also creation of new entry based on Pubmed ID is affected.

**Comment by Siedlerchr** [comment] 2019-03-25 19:42
Thanks for your report. I remember that there was a simliar issue, it seem this is the same problem:
Duplicate of #4273

**Closed** 2019-03-26 20:53 UTC
Labels: bug, fetcher, import

**Comment by Siedlerchr** [comment] 2023-03-26 20:08
@bernhard-kleine  Good news. The issue with italics is fixed now in the latest main version. We are working on supporting math related tags as well.
Could you please try the latest snapshot?
http://builds.jabref.org/main/
