### ISSUE TITLE
Paste button on maintable does not work properly 

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#6293] opened 2020-04-15 13:49 UTC
JabRef 5.1--2020-04-12--771af5d
Linux 5.4.19-050419-generic amd64 
Java 14

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open two different bibfiles (A and B) with a couple of entries
2. Select and copy one or more entries from the entry table of file A (via `Ctr-C` or via the `Copy` button).
3. Switch to the entry table of file B.
4. Use the `Paste` button.
5. (For me) The entry is not inserted in file B.
6. Use `Ctr-V` instead and the entry is inserted in file B.

**Comment by AEgit** [comment] 2020-04-18 10:17
JabRef 5.1--2020-04-14--e86d415
Windows 10 10.0 amd64 
Java 14.0.1

Can confirm this issue.

**Comment by tobiasdiez** [comment] 2020-04-19 20:51
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Comment by AEgit** [comment] 2020-04-20 10:47
JabRef 5.1--2020-04-20--bc57d22
Windows 10 10.0 amd64 
Java 14.0.1

I can confirm, this has been fixed in the current dev version.

**Comment by ytzemih** [comment] 2020-04-20 11:04
JabRef 5.1--2020-04-20--d9fe981
Linux 5.4.19-050419-generic amd64 
Java 14.0.1

Can confirm, too. Thanks for the fix.

**Comment by calixtus** [comment] 2020-06-05 13:33
Let's follow the mac related issue in #6419 .

**Comment by Siedlerchr** [comment] 2020-08-02 11:42
We had to revert this fix as it is breaking copy pasting via keyboard shortcuts and results in duplicate entries on mac when you paste in a new library. Codewise this seems to be a general issue

**Comment by Siedlerchr** [comment] 2020-08-02 15:10
The problem is that on MacOSX the command + v triggers the keyEvent which is handled in MainTable and consumed.
However, afterwards it still propagates to the owner of  the keybinding, the EditAction which then is triggered like if someone had pressed the MenuItem manually.
Seems to be this bug: https://bugs.openjdk.java.net/browse/JDK-8205915

**Comment by koppor** [comment] 2020-08-04 06:40
Decision: Disable in the code only for Mac - to get it working on Windows and Linux again.

**Comment by ytzemih** [comment] 2020-08-27 08:54
I've just added an update to #6740

**Comment by calixtus** [comment] 2020-08-27 09:38
😫

**Comment by calixtus** [comment] 2020-08-27 09:39
> I've just added an update to #6740

Thanks for your update. We'll look into it.

**Comment by Siedlerchr** [comment] 2020-08-28 05:48
I guess the problem is that it doesn't work when the focus is not on the maintable
: https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/edit/EditAction.java

**Comment by ytzemih** [comment] 2020-08-28 07:43
I see, can anyone using Linux confirm this issue still being there?

**Comment by Siedlerchr** [comment] 2020-08-28 07:45
Also I noticed that the paste bug in macos is now present in the TextField. I think wee need to disable it there.

**Comment by koppor** [comment] 2020-08-30 19:56
Fixed in master, will be included in the v5.1 release. Should be released in a few hours.

**Comment by jhh931** [comment] 2020-08-31 08:55
JabRef 5.1--2020-08-30--e023aa0
Windows 10 10.0 amd64 
Java 14.0.2

Paste button does not function. Neither does ^v.

**Comment by koppor** [comment] 2020-08-31 09:13
@jhh931 What did you copy? I tried copy from the maintable and paste into it.

**Comment by ytzemih** [comment] 2020-08-31 09:15
JabRef 5.1--2020-08-30--e023aa0
Linux 5.4.19-050419-generic amd64 
Java 14.0.2

Copy and paste per button and per keyboard shortcuts works for me under Linux. 
However, what I can't do: Copy by keyboard and paste by button. So, as long as you stay with one method, it seems to work. (for me)

**Comment by jhh931** [comment] 2020-08-31 11:50
Hey - I got some fresh new insights. Steps to reproduce: 

1. Open two different bibfiles (A and B) with a couple of entries
2. Select and copy one or more entries from the entry table of file A (via Ctr-C or via the Copy button). (GUI says: "Copied x entries")
3. Switch to the entry table of file B (by clicking on the tab)
4. Right now, ^v does not work. Paste button does not work. 
5. Click _below_  the tab of file B (e.g. on the header row or in any row with an entry). 
6. Now ^v does paste the copied entries into B. So does the Paste button.

**Comment by Siedlerchr** [comment] 2020-08-31 12:05
We probably need to remove the if for the focus owner check for maintable and assume the maintable as default if not text input control
@calixtus

**Closed** 2020-08-31 15:17 UTC
Labels: os: linux, type: bug 🐛

**Comment by Siedlerchr** [comment] 2020-08-31 19:34
This issue should now  be finally fixed in the new master.
https://builds.jabref.org/master/
