### ISSUE TITLE
When typing a character for naming a subgroup, the uncaught exception error occur.

### ISSUE THREAD

**Issue by lksj12** [JabRef/jabref#9524] opened 2023-01-04 04:26 UTC
### JabRef version

5.8 (latest release)

### Operating system

macOS

### Details on version and operating system

Ventura 13.1 Apple M1 chip

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Right click of a mouse for display dropdown menu at "all entries"
2. The program doesn't show any response

**Comment by HoussemNasri** [comment] 2023-01-04 11:13
It seems you're reporting 2 issues:
1. Uncaught exception error when naming a subgroup
2. No context menu for the "all entries" group

Issue 2 was fixed in https://github.com/JabRef/jabref/pull/9497 and issue 1 I can't reproduce in the latest development version.

**Closed** 2023-01-04 11:14 UTC
