### ISSUE TITLE
Medline import produces faulty authors line 

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4114] opened 2018-06-07 09:31 UTC
JabRef version 4.1
I have imported PMID 17673668 via the Medline import. I gives a faulty author line. Adding dots to the three single letters initials remedies the situation. I wanted to try this with Snapshot
JabRef 4.4-dev--snapshot--2018-06-04--master--ee669a542, but the medline import there did not work.
Steps to reproduce:

1. open jabref and the internet search 
2. import Medling 17673668
3. look for the authors, you will see the triangle saying names are not within the Biblatex standard.
There are a three single letter initials. If you add a dot to each of them the error message disappears.

Obviously Jabref forgets to add the dots to the initials.

**Comment by tobiasdiez** [comment] 2018-06-07 12:38
That's how we get the data from Medline and in general we do not try to sanitize the data due to false positives. Please report the issue directly to Medline. You can always run the author list cleanup to add the points after the initials. There is already an issue for doing this automatically (but I cannot find it right now). Close as duplicate of this one.

**Closed by tobiasdiez** 2018-06-07 12:38 UTC
