### ISSUE TITLE
Uncaught exception occurred in thread[pool-7-thread-1,5,main]

### ISSUE THREAD

**Issue by kingwarrick** [JabRef/jabref#4972] opened 2019-05-14 15:55 UTC
JabRef 5.0-dev--snapshot--2019-05-14--master--c754a790d
Linux 4.19.0-0.bpo.4-amd64 amd64 
Java 1.8.0_172

- [x ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

The error occurs when first editing an entry, again when switching between field tabs and then editing (i.e. abstract and comments on separate tabs), and also when deleting a selection of text. The same error message appears for each occurrence.

Autocomplete is disabled in the Entry editor options.

1. Open database
2. Select an entry to edit, go to the comments tab, cursor at beginning or end, press Enter
3. Error occurs, click ok
4. Then go to abstract tab, cursor to beginning or end, press Enter
5. Error occurs
6. Cursor to end of abstract, press Enter (new line), type "blah blah", select "blah blah", Delete
7. Error occurs

<details>
  <summary>Log File</summary>
  
java.lang.IllegalStateException: Task must only be used from the FX Application Thread
	at javafx.concurrent.Task.checkThread(Task.java:1218)
	at javafx.concurrent.Task.isRunning(Task.java:985)
	at org.controlsfx.control.textfield.AutoCompletionBinding.onUserInputChanged(AutoCompletionBinding.java:333)
	at org.controlsfx.control.textfield.AutoCompletionBinding.setUserInput(AutoCompletionBinding.java:135)
	at org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.setUserInputText(AutoCompletionTextInputBinding.java:136)
	at org.jabref.gui.autocompleter.AutoCompletionTextInputBinding.lambda$new$861(AutoCompletionTextInputBinding.java:54)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389)
	at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393)
	at javafx.scene.control.TextInputControl$TextProperty.controlContentHasChanged(TextInputControl.java:1332)
	at javafx.scene.control.TextInputControl$TextProperty.access$1600(TextInputControl.java:1300)
	at javafx.scene.control.TextInputControl.lambda$new$162(TextInputControl.java:139)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.scene.control.TextArea$TextAreaContent.insert(TextArea.java:207)
	at javafx.scene.control.TextInputControl.replaceText(TextInputControl.java:1204)
	at javafx.scene.control.TextInputControl.filterAndSet(TextInputControl.java:1171)
	at javafx.scene.control.TextInputControl.access$900(TextInputControl.java:79)
	at javafx.scene.control.TextInputControl$TextProperty.doSet(TextInputControl.java:1410)
	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1323)
	at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1300)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
	at com.sun.javafx.binding.BidirectionalBinding$TypedGenericBidirectionalBinding.changed(BidirectionalBinding.java:601)
	at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:361)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.StringPropertyBase.fireValueChangedEvent(StringPropertyBase.java:103)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:110)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:65)
	at javafx.beans.property.StringProperty.setValue(StringProperty.java:57)
	at org.jabref.gui.util.BindingsHelper$BidirectionalBinding.updateLocked(BindingsHelper.java:212)
	at org.jabref.gui.util.BindingsHelper$BidirectionalBinding.changedB(BindingsHelper.java:205)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:172)
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51)
	at com.sun.javafx.collections.MapListenerHelper$Generic.fireValueChangedEvent(MapListenerHelper.java:320)
	at com.sun.javafx.collections.MapListenerHelper.fireValueChangedEvent(MapListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableMapWrapper.callObservers(ObservableMapWrapper.java:115)
	at com.sun.javafx.collections.ObservableMapWrapper.put(ObservableMapWrapper.java:169)
	at org.jabref.model.entry.BibEntry.setField(BibEntry.java:417)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanupSingleField(FieldFormatterCleanup.java:63)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanupAllTextFields(FieldFormatterCleanup.java:88)
	at org.jabref.model.cleanup.FieldFormatterCleanup.cleanup(FieldFormatterCleanup.java:32)
	at org.jabref.model.cleanup.FieldFormatterCleanups.applyAllActions(FieldFormatterCleanups.java:71)
	at org.jabref.model.cleanup.FieldFormatterCleanups.applySaveActions(FieldFormatterCleanups.java:61)
	at org.jabref.logic.exporter.BibDatabaseWriter.lambda$applySaveActions$293(BibDatabaseWriter.java:60)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.jabref.logic.exporter.BibDatabaseWriter.applySaveActions(BibDatabaseWriter.java:57)
	at org.jabref.logic.exporter.BibDatabaseWriter.savePartOfDatabase(BibDatabaseWriter.java:172)
	at org.jabref.logic.exporter.BibDatabaseWriter.saveDatabase(BibDatabaseWriter.java:143)
	at org.jabref.logic.autosaveandbackup.BackupManager.performBackup(BackupManager.java:124)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.jabref.logic.autosaveandbackup.BackupManager.lambda$new$338(BackupManager.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
</details>

**Comment by Siedlerchr** [comment] 2019-05-14 16:17
Duplicate of #4958
The underlying problem is that you have save actions defined which include a field formatter, e.g. Latex2Unicode 

Workaround is to disable the save actions in the library properties until the error is fixed.

**Closed by Siedlerchr** 2019-05-14 16:17 UTC

**Comment by kingwarrick** [comment] 2019-05-14 22:52
Disabling field formatting fixed it.

Thanks for making the link!
