### ISSUE TITLE
Commandline help text not correct (e.g.,  "-f,--fetch <FILE>" does not use a file)

### ISSUE THREAD

**Issue by baderas** [JabRef/jabref#2016] opened 2016-09-20 13:41 UTC
JabRef version 3.5 Windows 10 x64

Steps to reproduce:
1. `java -jar JabRef-3.5.jar -h`
2. Look at output

See http://help.jabref.org/en/CommandLine

`<FILE>` is always used as argument name. This is wrong for some command line items, for example `-f,--fetch <FILE>` is used as `"--fetch=Medline:cancer"`. The correct help entry would be `-f, --fetch <SearchTerm>` with an explanation how `<SearchTerm>` must be used.
For some arguments a filename and some additional information (separated by comma, e.g., for `-i`) can be given. `<FILE>`  is also not correct there.

Same problem exists for:

```
-d,--prdef <FILE>
 -i,--import <FILE>
    --importToOpen <FILE> 
-m,--exportMatches <FILE> 
-o,--output <FILE> 
```

**Comment by lenhard** [comment] 2016-09-20 14:11
Let me add that fetching alone will not do much. It will fetch, but the results will cease to exist when the invocation terminates. To get actual output, the fetch command should be chained with `-o`.

Having said that, the documentation can certainly be improved. @baderas: Could you provide a pull request? Improving the textual output of the command line is certainly a good entry point.

**Comment by koppor** [comment] 2016-09-20 14:16
We think that the command lie should be `--fetch=Medline:cancer test.bib`

**Comment by lenhard** [comment] 2016-09-23 14:05
I just noticed that this issue is in a sense a duplicate of #1850. I am closing the older one and we can track further discussion here.

**Comment by dhananjaya2007** [comment] 2018-10-08 06:03
If no one is working on this issue, may I fix it? Thanks

**Comment by dhananjaya2007** [comment] 2018-10-09 04:57
` -f,--fetch <SearchTerm>             Run fetcher with a SearchTerm, e.g.    
                                                      "--fetch=Medline:cancer"
`
Is this format ok?

**Comment by davidemdot** [comment] 2019-05-13 01:20
What do you think about this output?

![Screenshot_20190513_031750](https://user-images.githubusercontent.com/12954316/57590725-f2dc1b00-752d-11e9-9da3-8893570b9879.png)

**Comment by davidemdot** [comment] 2019-05-14 01:50
The point is that Apache Commons (library currently used) prints the argument(s) within the symbols "<" and ">". So, if we want to show the CLI help like above, it would be easy. In another case, I can program a new code for this.

**Comment by tobiasdiez** [comment] 2019-05-17 09:43
@davidemdot Looks good to me. The argument to `prdef` should be `KEY` and `-m` needs a better description. Moreover, I like the example given for `-fetch` in the description. For me this is easier to understand than e.g. the format for import or aux.

**Comment by Siedlerchr** [comment] 2019-05-18 17:04
Thanks to @davidemdot this issue is now fixed in the lastest master.


We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2019-05-18 17:04 UTC
Labels: cli, documentation, good first issue
