### ISSUE TITLE
Latex to Unicode in author field fails

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#2063] opened 2016-09-25 18:38 UTC
JabRef 3.7dev--snapshot--2016-09-25--master--40df60b
windows 10 10.0 amd64 
Java 1.8.0_101
1. author field in entry editor: Sto{\"{\i}}anova, Ivanka
2. author field in main table:  Stoanova, Ivanka
3. should be: Stoïanova, Ivanka

**Comment by Siedlerchr** [comment] 2016-09-26 11:08
Confirmed. Will take a look at it.

**Comment by Siedlerchr** [comment] 2016-09-26 11:35
Ah, I found the problem:

For some reason I don't know there exist 2 Variants of these character, `latin small letter i with diaeresis (U+00EF)`
ftp://ftp.dante.de/tex-archive/macros/xetex/latex/xecjk/xunicode-symbols.pdf

However, JabRef only supports the first one: `\^{i}`

**Comment by stefan-kolb** [comment] 2016-09-26 12:08
@oscargus is the expert here 😄

**Comment by Siedlerchr** [comment] 2016-09-26 16:31
The problem is theoretically easy to fix, but practically we have the problem that the mappings are stored in a HashMap and we have no chance to add a double entry.  Fuu.. I hate HashMaps sometimes.

**Comment by koppor** [comment] 2016-09-26 17:23
Refs https://github.com/koppor/jabref/issues/145

**Comment by Siedlerchr** [comment] 2016-09-26 18:33
@koppor  Sure. I found that piece of code. However, 

`00EF  ï  ` has two possible mappings: `\"{i}` or `\"{\i}` (notice the slash before the i) 
The latter one is used here, latest version (inlcuding unicode8)
https://www.w3.org/2003/entities/2007xml/unicode.xml (warning, file is around 5MB)

Both versions are valid. The question is: Do we find a solution to support multiple variants or do we stick with just one variant and then do nothing?

The current behaviour is more or less removing the character if no conversion possible

**Comment by tobiasdiez** [comment] 2016-09-26 20:29
I think you can just add a new entry to the `CONVERSION_LIST`. In the Unicode -> Latex direction only one of these entries is kept, but both should be added to the Latex -> Unicode map.

**Comment by Siedlerchr** [comment] 2016-09-26 20:36
That was may inital idea, too: However the point is, we have a  **HashMap**

https://github.com/JabRef/jabref/blob/ee688c44765f11344226da531b63f9df345a6585/src/main/java/net/sf/jabref/model/strings/HTMLUnicodeConversionMaps.java#L852
` public static final Map<String, String> LATEX_UNICODE_CONVERSION_MAP = new HashMap<>();`

And unicode Number is the key.. Problem: We have now 1 Unicode Number -> 2 Values.
So one would need a MultiMap or whatever

**Comment by tobiasdiez** [comment] 2016-09-26 21:06
But this map has the latex code as the key and unicode as the value, see https://github.com/JabRef/jabref/blob/ee688c44765f11344226da531b63f9df345a6585/src/main/java/net/sf/jabref/model/strings/HTMLUnicodeConversionMaps.java#L873. So there is no problem if you have different latex codes mapped to a single unicode.

**Comment by Siedlerchr** [comment] 2016-09-27 19:42
Okay, I tried the approach using @tobiasdiez approach and in theory it should work. However, through debugging I noticed that the CleanLatex String methods removes all kind of slashes and braces which result in getting the same strippedLatex key...

```
  {"239", "iuml", "{\\\"{i}}"}, // latin small letter i with diaeresis,
            //
  {"239", "iuml", "{\\\"{\\i}}"}, // latin small letter i with diaeresis,
            //                                 U+00EF ISOlat1

```
```
 private static String cleanLaTeX(String escapedString) {
        // Get rid of \{}$ from the LaTeX-string
        return escapedString.replaceAll("[\\\\\\{\\}\\$]", "");
    }
```

**Comment by oscargus** [comment] 2016-09-28 18:35
Yes, the key here used in the lookup will/should be `"i`, so both variants should work (the reason being that `{\"{i}}`, `\"{i}`, `\"{\i}`, `{\"{{\i}}}` etc should work). However, there is also some special handling of a few of the accents to allow writing e.g. `\"i`. Not sure if that may be the issue here...

**Comment by lenhard** [comment] 2017-02-10 09:09
We integrated a new library for performing the conversion in #2532: latex2unicode. As far as I have tested in the UI, the problems described here are solved now, so I am closing this issue.

Feel free to reopen in case the problem reappears!

**Closed by lenhard** 2017-02-10 09:09 UTC
Labels: bug, cleanup

**Comment by lenhard** [comment] 2017-02-10 10:51
Is now also tested with 9eef09cb3cb47539db184bbc515259fe821d2c4
