### ISSUE TITLE
Cite Special Extra information always attached to entry in LibreOffice

### ISSUE THREAD

**Issue by DrDabadu** [JabRef/jabref#2848] opened 2017-05-17 15:23 UTC
JabRef version 3.8.2 on Ubuntu 16.04

Steps to reproduce:

1. Automatically connect JabRef to LibreOffice Writer
2. Cite an author using "Cite special"
3. Input special Information
4. Cite the same author using "Cite"

The citation will show the "extra information" in the .odt document after using cite, although no special information was entered for the second citation. Removing the extra information via "Manage citations" is undone when closing that window again.

I could not reproduce the bug using 4.0.0 because it won't run on my machine (could not load main class org.jabref..JabRefMain).
I hope this was not already issued. Thanks for your work.

**Comment by Siedlerchr** [comment] 2017-05-17 16:16
Thanks for your report. The version 4.0.0 issues is well known due to the fact that you are missing some extra libs, you need to install openjfx. See the installation guide for more details.
http://help.jabref.org/en/Installation

**Comment by DrDabadu** [comment] 2017-05-18 07:30
Thanks for your support. I installed openjfx but cannot connect to LibreOffice both manually and automatically. Do I need to install a newer version of LibreOffice?
Path to executable seems right: /usr/lib/libreoffice/program/soffice
Path to library dir seems right: /usr/lib/libreoffice/program/classes

Error message: (Not all) required Open Office Jars were found inside the installation path.

**Comment by Siedlerchr** [comment] 2017-05-18 09:03
There is another package you need to install, libreoffice-java or similar,
on the help Page for the connection to libreoffice there the package is
mentioned

Am 18.05.2017 9:30 vorm. schrieb "DrDabadu" <notifications@github.com>:

**Comment by DrDabadu** [comment] 2017-05-18 09:29
I also installed Oracle Java as mentioned on the Installation page. It doesn't state any packages aside of libreoffice-java-common being required. Also the connection works in JabRef 3.8.2.
Here's a list of the installed jars in the /usr/lib/libreoffice/program/classes/ directory. 

commonwizards.jar
form.jar
java_uno.jar
juh.jar
jurt.jar
query.jar
report.jar
ridl.jar
ScriptFramework.jar
ScriptProviderForJava.jar
smoketest.jar
table.jar
unoil.jar
unoloader.jar
xmerge.jar
XMergeBridge.jar

**Comment by Doc73** [comment] 2017-05-18 16:32
I can confirm that JabRef v. 4.0.0 (both the beta and the latest development version) can't connnect with libreoffice 5.2.6-2 in my Debian 8 Amd64 system.

I've installed `libreoffice-java-common` and `openjfx` and in previous versions of JabRef the plugin was fully functional.

With the occasion, I can report that the wiki ([http://help.jabref.org/en/Installation#debian-jessie-8-and-oracle-java](http://help.jabref.org/en/Installation#debian-jessie-8-and-oracle-java)) can be corrected, at leat for Debian 8: `openjfx` is available in Jessie Backports and therefore all you need is

> sudo  apt -t jessie-backports install openjfx

**Comment by indradecastro** [comment] 2018-01-19 11:19
I found the same problem (#2848).
But I am in a hurry and can't afford dealing with the installation of JabRef 4.0.0 (openjfx is giving me a headache). So I am giving up that *potential* solution.

Instead:
How can I manually remove the _special Information_ added to my citations?
Where is this *special information* stored? any user preferences files?
Please help.

**Comment by Siedlerchr** [comment] 2018-01-24 10:34
Hi, you can always try to install the orcacle jre in the latest version;
http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

If you click on manage citations and double click on the entry, you can remove the special information.

**Comment by indradecastro** [comment] 2018-01-24 18:14
Thank you very much @Siedlerchr.
Your SECOND advice (Manage Citations -> remove special information) worked smoothly.
The references cited after that have no special information any more.
(installing Oracle was not needed)

**Comment by Siedlerchr** [comment] 2018-01-24 18:28
Glad it works for you, so I close the issue

**Closed by Siedlerchr** 2018-01-24 18:28 UTC
Labels: openoffice/libreoffice, waiting-for-feedback
