### ISSUE TITLE
 Entry Preview - Error: java.lang.IllegalArgumentException: Visible paragraphs' last index is [-1] but visibleParIndex was [0]

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#7891] opened 2021-07-06 08:35 UTC
JabRef 5.3--2021-07-05--482bed7
Windows 10 10.0 amd64 
Java 16.0.1 
JavaFX 16+8

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/main and the problem persists

Errormessage

1. Open Entry Preview
2. Choose "Modern Language Association 8th edition" (not sure if generic of only this one, i did not try others)
3. click on IEEE, then click on modern language association 8th edition, if no error yet, then click on IEEE again.
4. error

![image](https://user-images.githubusercontent.com/73715071/124568025-cc337980-de44-11eb-967e-c9d46f2bb0e3.png)

<details>
  <summary>Log File</summary>
  
  ```
 java.lang.IllegalArgumentException: Visible paragraphs' last index is [-1] but visibleParIndex was [0]
	at org.jabref.merged.module@5.3.2/org.fxmisc.richtext.GenericStyledArea.visibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.richtext.ViewActions.firstVisibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.richtext.LineNumberFactory.deleteParagraphCheck(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.richtext.LineNumberFactory.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.3.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.3.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.3.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
  ```
</details>

when i tried to do it again this happened:

![image](https://user-images.githubusercontent.com/73715071/124568744-8cb95d00-de45-11eb-9e6c-75fa5bd0ea08.png)

<details>
  <summary>Log File</summary>
  
  ```
java.lang.IndexOutOfBoundsException: 443 not in [0, 325)
	at org.jabref.merged.module@5.3.2/org.reactfx.util.Lists.checkIndex(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.reactfx.util.Lists.checkIndex(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.reactfx.collection.MemoizationListImpl.getIfMemoized(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.flowless.CellListManager.getCellIfPresent(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.flowless.CellPositioner.getCellIfVisible(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.flowless.VirtualFlow.getCellIfVisible(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.richtext.GenericStyledArea.visibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.richtext.ViewActions.firstVisibleParToAllParIndex(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.richtext.LineNumberFactory.deleteParagraphCheck(Unknown Source)
	at org.jabref.merged.module@5.3.2/org.fxmisc.richtext.LineNumberFactory.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.3.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.3.2/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source)
	at org.jabref.merged.module@5.3.2/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.3.2/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.3.2/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment] 2021-07-06 08:52
Duplicate of #7860

**Closed by Siedlerchr** 2021-07-06 08:52 UTC
