### ISSUE TITLE
Repair/optimise pixels for total count of entries with 5 digits

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#9525] opened 2023-01-04 10:34 UTC
JabRef 6.0--2023-01-03--f8c2cf6
Linux 6.0.15-300.fc37.x86_64 amd64 
Java 19.0.1 
JavaFX 19+11

Similar like https://github.com/JabRef/jabref/issues/2803 & https://github.com/JabRef/jabref/issues/2964 I encounter again the situation that the count of total entries is not fully displayed.

![Screenshot from 2023-01-04 11-33-00](https://user-images.githubusercontent.com/20518297/210536408-d4d91a0c-a277-4bf6-b977-673067e7ef05.png)

**Comment by Siedlerchr** [comment] 2023-01-04 11:14
Duplicate of #8797 We found out that this occurs if you have a different than the default font size activated

**Closed by Siedlerchr** 2023-01-04 11:14 UTC
