### ISSUE TITLE
Get password storage running on GNOME

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10274] opened 2023-09-01 22:17 UTC
- Coming from https://github.com/JabRef/jabref/pull/10044#issuecomment-1637205192
- Details https://github.com/JabRef/jabref/pull/10252#issuecomment-1702885640

**Comment by credmond** [comment] 2023-09-02 00:40
Hi -- the fault is not the keyring library, but a clash in dependencies. I can successfully use the keyring library in a simpler project, but actually I initially encountered the same problem when also using another library with a different ASM lib version.

Can be fixed by ensuring only one (and correct) version of ASM is on classpath.

See the clashes:

![image](https://github.com/JabRef/jabref/assets/1417880/55606b14-db3c-417f-970a-232b4ecbfe81)

See the error caught, swallowed, and null returned:

![image](https://github.com/JabRef/jabref/assets/1417880/bd03e185-d487-4134-89e8-30e0a466ade9)

I'm not a Gradle expert (more Maven) and I don't know the usages of the conflicting libs, etc. within Jabref -- so I'll leave the fix up to someone else, but that's definitely the problem / solution, so I hope that helps.

**Comment by Siedlerchr** [comment] 2023-09-02 00:57
TODO investitage: Either we exclude them or we try to enforce only one valid version with strictly.

**Comment by koppor** [comment] 2023-09-05 19:54
> Hi -- the fault is not the keyring library,

I am not sure about this.

In the CI of keyring, `com.github.javakeyring.BackendNotSupportedException: No available keyring backend found` is also risen. See 
https://github.com/javakeyring/java-keyring/actions/runs/6026456707/job/16349436333

> Here's how it should look (note, different project!):

Do you know which version of the keyring library is used there?

**Comment by koppor** [comment] 2023-09-05 19:59
After the commit https://github.com/javakeyring/java-keyring/commit/b81ba141d085755c2db861630adeb405a1b45bba, the CI tests of the keyring library broke.

Thus, the update from [secret-service](https://github.com/swiesend/secret-service) 1.0.0 to 1.8.1-jdk17 seems to broke something.

**Comment by koppor** [comment] 2023-09-05 20:10
Intermediate result: Version 1.8.0-jdk17 broke things:

![image](https://github.com/JabRef/jabref/assets/1366654/75a0d5e2-186d-4eb1-afc4-3c1891c5b01f)

**Comment by koppor** [comment] 2023-09-05 20:17
CHANGELOG for 1.8.x: https://github.com/swiesend/secret-service/blob/master/CHANGELOG.md#181-jdk17---2023-01-17

There is also a PR in progress trying to fix things: https://github.com/javakeyring/java-keyring/pull/91

**Comment by credmond** [comment] 2023-09-05 20:27
That failing CI test may or may not be related, I actually don't think it is. Revert back to 1.0.3, for example, it still won't work.

The screenshots were from 1.0.3 (on my own project, and the Jabref branch was still on 1.0.3 when I ran it). I had this exact same issue a few weeks ago and I just can't remember EXACTLY how I fixed it. It was library related, I do know that.

**Comment by credmond** [comment] 2023-09-05 21:15
That "No available keyring backend found" error is not very helpful as any root exception gets caught & ignored...

Ok, I rolled back (my own project) to re-create the problem I had, and it's very well hidden, and not logged. It's a root cause is this:

![image](https://github.com/JabRef/jabref/assets/1417880/6b3252db-12ad-4119-a4da-2746747c6ca5)

Same place, slightly different error to Jabref. And this only happens when a library Lombok is present as a runtime library. Lombok is not meant to be on the runtime classpath (it's a preprocessor, I'm sure you know it).

And the error occurs, because Lombok has this shaded version of the asm library:

![image](https://github.com/JabRef/jabref/assets/1417880/d21cb63f-1212-4126-b1d3-eebac4cced0c)

I fixed this because by making Lombok's scope provided, as it should be.

1.0.3 and 1.0.4 of the keyring library work fine for me on Gnome on my own project. So something slightly different, actually is going on with Jabref. But I bet it's a library issue -- it has to be.

**Comment by credmond** [comment] 2023-09-05 22:41
So, turns out we get different errors in 1.0.3, and 1.0.4. I think this is down to modules not being present no module-info.java.

For example, 1.0.4, you get this:

![image](https://github.com/JabRef/jabref/assets/1417880/7ecce4f9-4c2c-45f0-a3e8-e281ab182469)

... which can be fixed by adding this to module-info.java:

`requires org.freedesktop.dbus;`

I have confirmed this works on Gnome.

....however 1.0.4 is not officially released yet and clearly has problems.

**Comment by credmond** [comment] 2023-09-05 23:43
Interestingly, if I use Jabref and 1.0.3, to overcome the jnr-ffi error I pasted much earlier, by doing this:

`requires org.jnrproject.ffi;`

and...

`implementation 'com.github.jnr:jnr-ffi:2.2.13'`

... I get back to a ClassNotFound error (exact same as the error I get with Lombok on my own project), looking for ClassVisitor. And this can be solved with an additional:

`requires org.objectweb.asm;`

...and so, 1.0.3 actually then works on Gnome!

So clearly Java modules is making life difficult when using non-modular projects such as java-keyring. I'd say there's some conflicts also in Jabref and some load order behaviour causing this.

I'd like to fully understand the load order / behaviour causing this. E.g., I do not need either of these entries in module-info.java on a personal project. Doesn't make sense.


But anyway, this comment and the previous are two ways to get the library 1.0.4, and 1.0.3, working on Gnome, at least. We probably need proper unit tests!

**Comment by koppor** [comment] 2023-09-05 23:49
> So, turns out we get different errors in 1.0.3, and 1.0.4. I think this is down to a module not being present in module-info.java.
> 
> For example, 1.0.4, you get this:
> 
> ![image](https://user-images.githubusercontent.com/1417880/265841940-7ecce4f9-4c2c-45f0-a3e8-e281ab182469.png)
> 
> ... which can be fixed by adding this to module-info.java:
> 
> `requires org.freedesktop.dbus;`

Done at https://github.com/JabRef/jabref/issues/10274#issuecomment-1707404929.

> I have confirmed this works on Gnome.

Looking forward to your test of the build of PR 10274.

> ....however 1.0.4 is not officially released yet 

I don't get that. In my view, a release on Maven central is a official release: https://central.sonatype.com/artifact/com.github.javakeyring/java-keyring/1.0.4. OK, the tag is missing at https://github.com/javakeyring/java-keyring/tags. I'll ask the maintainer.

> and clearly has other problems.

It's not clear to me. From 1.0.3 to 1.0.4, there were "only" dependencies updated (see the diff https://github.com/javakeyring/java-keyring/compare/java-keyring-1.0.3...5ccf275893cc04d5555d6e32f651cba71977b5f4).

**Comment by koppor** [comment] 2023-09-05 23:50
> We probably need proper unit tests!

I think, a good start could be to have CI-based unit tests for secret-service. I tried at https://github.com/swiesend/secret-service/pull/43, but I failed.

**Comment by credmond** [comment] 2023-09-05 23:56
Ah ok, I didn't know it was officially released, I felt that the failing CI tests (and lack of tag) were an indicator it wasn't released yet. I thought maybe it was coming from JitPack or something...though, in hindsight, it wouldn't have been called "1.0.4", so that was a dumb idea!

Confirmed that PR works! Well done.

**Closed** 2023-09-06 08:03 UTC
Labels: type: feature
