### ISSUE TITLE
Recovery dialogue on start-up shown although saved and closed properly

### ISSUE THREAD

**Issue by ytzemih** [JabRef/jabref#6109] opened 2020-03-13 11:03 UTC
JabRef 5.1--2020-03-12--23034ce
Linux 5.4.19-050419-generic amd64 
Java 13.0.2

- [X] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. For a test bib file, delete bak/sav files if any
2. Open test file in JR
3. Do some edits, save, and close JR such that test file is automatically reopened when starting JR again (i.e. just leave the tab open)
4. Start JR again
5. Dialogue asking to recover from backup file appears although test file has been saved properly and JR been closed normally.

No (other/related) errors show on the command line. **I can only reproduce that behaviour if I actually edit the file.** Without edits the error doesn't show.

**Comment by stefan-kolb** [comment] 2020-03-13 16:59
Duplicate of #6092?

**Comment by koppor** [comment] 2020-03-13 19:16
Refs https://github.com/koppor/jabref/issues/391

**Comment by koppor** [comment] 2020-03-14 00:20
Does `"Error while deleting the backup file."` appear somewhere in the log file?

**Closed** 2020-09-01 12:17 UTC
Labels: type: bug 🐛
