### ISSUE TITLE
Saving sort order depends on crossref field

### ISSUE THREAD

**Issue by milleratotago** [JabRef/jabref#2305] opened 2016-11-21 18:33 UTC
JabRef version 3.7 on Windows 10

JabRef's sort order is influenced by whether the reference entry contains the "crossref" field. In the output, all of the references that do contain this field appear first (sorted within this group). Then, all of the references that do not contain this field follow separately (again, sorted correctly within this group).

Steps to reproduce:

1. Load a bib file that includes some references of type @InCollection for which a "crossref" field is specified.
2. Under the File menu, "Database properties" window, use "Save sort order" to request sorting by bibtexkey.
3. Save the file.  Regardless of their bibtexkey's, all of the references with "crossref" fields will be at the top.

**Comment by matthiasgeiger** [comment] 2016-11-22 07:34
Confirmed.

**Comment by matthiasgeiger** [comment] 2016-11-22 08:20
That's interesting. 

@milleratotago Have you configured the same save order in previous JabRef versions? 

According to a comment in the code this behavior is intentionally as all entries containing a `crossref` should be placed prior to other entries. And this comment is there since the beginning of the code history, i.e., 2003 :smiley:

However, from the current code base there seems to be no reason to enforce this sorting. At least our current BibTeX parser seems to handle `crossref`s correctly regardless of the position in the file... @lenhard Do you agree?

**Comment by matthiasgeiger** [comment] 2016-11-22 08:42
Okay... I now also know WHY this comment is there. See http://tex.stackexchange.com/a/12108/103488: 

> One other important remark is that cross-referenced entries must be defined after entries containing
the corresponding crossref field.

In order to have working `crossref`s when actually working the BibTeX the order is important. Thus, as this should be the normal use case for JabRef users we should keep the current behavior: entries containing a `crossref`` field should be placed prior to other entries.

But I'll document this in the source code and the [help file for the DatabaseProperties](http://help.jabref.org/en/DatabaseProperties).

**Comment by lenhard** [comment] 2016-11-22 08:47
Since this is actually desired and correct behavior, I am closing this issue as invalid

**Closed by lenhard** 2016-11-22 08:47 UTC
Labels: export, invalid
