### ISSUE TITLE
Import of bibtex to sub-group works only on first import, after which would be imported to general library

### ISSUE THREAD

**Issue by ishai-windrose** [JabRef/jabref#11270] opened 2024-04-30 19:30 UTC
### JabRef version

5.13 (latest release)

### Operating system

macOS

### Details on version and operating system

Mac OS X 13.5 Ventura

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Create new sub-group
2. Import bibtex file - works.
3. Import second bibtex file - does not work properly - imports it to general list not to the sub-group

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>

**Comment by Yery** [comment] 2024-05-01 04:14
Issue #11085 might be related/duplicate.

**Comment by Siedlerchr** [comment] 2024-05-01 11:21
Duplicate of #11085

**Closed by Siedlerchr** 2024-05-01 11:21 UTC
