### ISSUE TITLE
Entry editor missing after changing autocompletion settings

### ISSUE THREAD

**Issue by aphalo** [JabRef/jabref#1450] opened 2016-05-25 12:39 UTC
Using 3.3 release (64 bit) under Windows 10 Pro x64 Java 8 91.
Disabled autocompletion and entry editor disappeared immediately (tried C-e, double click and menu icon to no avail). Resetting settings from dialogue did not solve the problem. Neither uninstalling and reinstalling Jabref.

`java -jar JabRef-3.3.jar -d all` at the command prompt solved the problem.

importing the saved settings from just after the problem started (attached file) reproduces the problem. (My settings have a very long history as I have been using Jabref for ages...).

The bad preferences are in the file below.

[jabref.prefs.txt](https://github.com/JabRef/jabref/files/281949/jabref.prefs.txt)

**Comment by lenhard** [comment] 2016-05-25 14:25
@aphalo: Thanks for reporting!

I can confirm that importing the above preferences disables the entry editor. I can add that also importing other working preferences does not make the editor re-appear. Only the solution you described repairs JabRef"s behavior.

Starting from default preferences and disabling auto completion is all that is needed to reproduce this bug.

**Comment by matthiasgeiger** [comment] 2016-05-31 10:01
Actually the entry editor is not missing - but due to a bug it has the height of only 1 pixel. As the bug occurs when the preferences dialog is closed even restoring the default preferences was not possible using the UI.

The bug should be fixed in the references PR - please verify using a build from: http://builds.jabref.org/fix-1450/

**Closed** 2016-05-31 13:30 UTC
Labels: bug

**Comment by Dellu** [comment] 2017-02-28 23:49
I am having this issue in the Mac right now: on the latter builds. 

I was using it fine last week. Suddenly, double clicking the entry in the table doesn't open the editor. It might have sth to do with the java.

**Comment by Dellu** [comment] 2017-02-28 23:56
Restarting the computer; nor using the menu or the shortcut are helping. This is strange.

**Comment by Dellu** [comment] 2017-03-01 00:15
Resetting the Preference fixed it.
