### ISSUE TITLE
Groups no longer highlighted

### ISSUE THREAD

**Issue by lc9275** [JabRef/jabref#4295] opened 2018-08-27 13:06 UTC
In the past, when an article was selected its parent groups lit up. This does no longer be the case (or I cannot find the option in the new jabref). So as far as I can tell, there is really no way of seeing which groups an article belongs to.

JabRef 5.0-dev--snapshot--2018-08-23--master--add2b0b94
Windows 10 10.0 amd64 
Java 1.8.0_181

**Comment by tobiasdiez** [comment] 2018-08-28 07:43
Duplicate of #3112

**Closed by tobiasdiez** 2018-08-28 07:43 UTC
