### ISSUE TITLE
Spurious text included with copied previews

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5263] opened 2019-08-30 20:28 UTC
JabRef 5.0-dev--snapshot--2019-08-30--master--66b7fe3af
Linux 5.0.0-25-generic amd64 
Java 11.0.4

1. Open the entry editor
2. select the Required fields tab
3. A right column displays the formatted entry (attached image)

![Screenshot from 2019-08-30 14-17-24](https://user-images.githubusercontent.com/762246/64049536-5e281800-cb32-11e9-8d36-2cf6f9b4e061.png)

4. right-click the preview and select "copy".
5. The result in the clipboard is this:

 ```
       function highlight(text) {
            var innertxt = document.body.innerText;
            var response = innertxt.replace(new RegExp(text, 'gi'), str => `<span style='background-color:red'>${str}</span>`);
            document.body.innerHTML = response;
        }
    Acharya, D., 2006. Vācaspatimiśra’s Tattvasamīkṣā. the Earliest Commentary on Mandanamiśra’s Brahmasiddhi. Critically Edited with an Introduction and Critical Notes. Nepal Research Centre Publications. Stuttgart: Franz Steiner Verlag.
```
That spurious "function highlight(text){...} " gets included with all copies.

**Comment by Siedlerchr** [comment] 2019-08-31 10:50
The javascript code is from the highlighting for search results in the entry preview. Seems like the entry preview is copied as html. If you  use the ctrl +c and ctrl +v it should work without issues.

**Comment by AEgit** [comment] 2019-09-08 13:02
JabRef 5.0-dev
Linux 5.0.0-27-generic amd64 
Java 1.8.0_222

Cannot confirm this issue for the current snap version of JabRef. Note, that the current snap version does not incorporate the preview in the entry editor as shown above. So the issue might actually persist and if that is the case it might have been introduced with the changes made to the preview and the entry editor.

**Comment by matthiasgeiger** [comment] 2019-09-22 08:43
Sorry, need to re-open this, as it is still not working properly for me in latest dev builds...

**Comment by matthiasgeiger** [comment] 2019-09-22 08:48
Moreover: Using the "Copy Preview" functionality from the main table context menu does not work at all.

**Comment by AEgit** [comment] 2019-09-22 08:56
JabRef 5.0-dev
Linux 5.0.0-29-generic amd64 
Java 11.0.4

@matthiasgeiger I have tried to reproduce the issues that you report in https://github.com/JabRef/jabref/issues/5263#issuecomment-533861844 and https://github.com/JabRef/jabref/issues/5263#issuecomment-533862192 with the latest snap version (--edge channel), but I still do not manage to: everything works as expected for me. Can you provide a minimum example of a database, where you run into these issues?

**Comment by matthiasgeiger** [comment] 2019-09-22 09:47
Meanwhile I have performed some analysis: the problem is caused by different 'paste'-targets: when the target is able to interpret HTML formatted text it is working fine - if you use a tool supporting only plain text not (e.g. Windows editor). 
I'll try to work on a fix in the next days... 😀

**Comment by AEgit** [comment] 2019-09-22 09:50
@matthiasgeiger You are absolutely right. Now I can confirm the issues you report, if I use a simple text editor as paste target. I never thought, that the paste target would make a difference. Well spotted!

**Comment by Siedlerchr** [comment] 2019-09-22 10:51
The embedded Javascript comes from n the search highlight function. It's added when the citation style is loaded in the web view. So technically it's correct that it's also shown in paste, if the target does not interpret html.

**Comment by matthiasgeiger** [comment] 2019-09-22 12:09
Well, yes and no. The remainder of the HTML code is stripped off before, i.e. the text formatting code is not shown when pasting into a plain text editor. 
I'll try to implement the copy action in a way that the plain format does not contain any formatting information, but the HTML content is preserved for editors supporting that.
The question is what should be pasted if someone explicitly wants to copy HTML/XML/... and pastes this to a plain text editor.. the stripped version without formatting, or the code including all HTML/XML tags?

**Comment by wujastyk** [comment] 2019-09-22 16:40
Both HTML and plain "text" are offered separately already, so the "text" option should not have HTML codes.  It should be plain text.  Seem the two menu choices in the attached screenshot.

![Screenshot from 2019-09-22 09-39-28](https://user-images.githubusercontent.com/762246/65391342-edcd7a80-dd1c-11e9-867f-613df5d985c9.png)

**Comment by tobiasdiez** [comment] 2019-09-22 16:52
I think one of the problems is that these methods
https://github.com/JabRef/jabref/blob/4b39b78e4afcd6c36b385f5c46f1d9a4eac2e29b/src/main/java/org/jabref/gui/ClipBoardManager.java#L70
never set html and string together. Normally you want to use putString and putHtml together and then the target application chooses which representation it wants to use.

**Comment by tobiasdiez** [comment] 2019-10-06 09:25
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed by tobiasdiez** 2019-10-06 09:25 UTC
Labels: entry-preview, ui, waiting-for-customer-feedback

**Comment by AEgit** [comment] 2019-10-17 08:58
JabRef 5.0.0-dev--2019-10-17----e81d58c51
Windows 10 10.0 amd64 
Java 12.0.2

Can confirm that this has been fixed in the current dev version.
