### ISSUE TITLE
JabRef 4.0 Windows 32 bit installer failes to extract JabRef.exe

### ISSUE THREAD

**Issue by webbertee** [JabRef/jabref#3289] opened 2017-10-12 10:45 UTC
JabRef version 4.0 (signed on 2017-10-04) on Windows 10 64 bit, 32 bit Java

Steps to reproduce:

1. Download Windows 32 bit installer here: https://www.fosshub.com/JabRef.html
2. Run installer
2. Click continue until it installs

Error Message: JabRef.exe could not be created. Retry?
Klicking "Yes" yields the same error message.

**Comment by matthiasgeiger** [comment] 2017-10-12 13:24
Works for me without problems on a Win10 x64 machine (32bit JRE was installed during installation)...

**Comment by stefan-kolb** [comment] 2017-10-12 14:26
Works for me...Try to run the installer as administrator (rightclick -> run as administrator)?

**Comment by webbertee** [comment] 2017-10-16 08:10
I tried running as Admin, rebooting and changing the install directory, but the issue persists. I got the platform-indipendent .jar working, but I have no idea why the installer does not work. It could very well be a issue with my machine.

**Comment by lynyus** [comment] 2017-10-16 10:44
@webbertee with this amount of information, it is quite hard to tell you what is wrong. As you have pointed out it is very likely that the problem is not on our side, but somewhere in your windows environment. Therefore, I'll close this issue for now. Nevertheless, it would be good if you give us a hint what was the problem, so we can help other users.

**Closed by lynyus** 2017-10-16 10:44 UTC
Labels: waiting-for-feedback
