### ISSUE TITLE
Jabref not fechtuing in google scholar

### ISSUE THREAD

**Issue by gbfarias** [JabRef/jabref#4122] opened 2018-06-11 12:51 UTC
JabRef version 4.3.1 on Win 10 not fechting on google scholar. When trying to fecht, the new window pops up as normally does, but then it suddenly closes. It is also happening on version 4.3, 4.2 on same OS.

**Comment by tobiasdiez** [comment] 2018-06-11 13:06
Duplicate of #4027.

**Closed** 2018-06-11 13:06 UTC
