### ISSUE TITLE
Unable to start up Jabref

### ISSUE THREAD

**Issue by skanskan** [JabRef/jabref#4438] opened 2018-10-30 19:21 UTC
When I run JabRef_windows-x64_5_0-dev--snapshot--2018-10-30--master--274fed486.exe nothing happens.
The program appears on Windows task manager but there is no usable Window.
I have the same problem with several older Jabref 5.0 versions I've tried.  
Version 4 was working well.

Then I have tried to run it from the command line with
java -jar JabRefxxxx.jar and I get this error messages:

```
C:\Program Files\JabRef>java -jar JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar
20:12:24.051 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: C:\Personal\women\person-years.bib
20:12:25.617 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Could not find file: /ieee.csl
java.nio.file.NoSuchFileException: \ieee.csl
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source) ~[?:1.8.0_191]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_191]
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source) ~[?:1.8.0_191]
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source) ~[?:1.8.0_191]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_191]
        at java.nio.file.Files.newByteChannel(Unknown Source) ~[?:1.8.0_191]
        at java.nio.file.Files.readAllBytes(Unknown Source) ~[?:1.8.0_191]
        at org.jabref.logic.citationstyle.CitationStyle.createCitationStyleFromFile(CitationStyle.java:110) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.logic.citationstyle.CitationStyle.getDefault(CitationStyle.java:127) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.logic.citationstyle.CitationStyleCache.<init>(CitationStyleCache.java:29) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.gui.BasePanel.<init>(BasePanel.java:177) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1211) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1010) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:123) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:62) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.JabRefMain.start(JabRefMain.java:77) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863) ~[jfxrt.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326) ~[jfxrt.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
20:12:26.171 [JavaFX Application Thread] ERROR org.jabref.JabRefMain - Unexpected exception
java.nio.file.FileSystemNotFoundException: null
        at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171) ~[zipfs.jar:1.8.0_191]
        at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157) ~[zipfs.jar:1.8.0_191]
        at java.nio.file.Paths.get(Unknown Source) ~[?:1.8.0_191]
        at org.jabref.gui.util.ThemeLoader.addAndWatchForChanges(ThemeLoader.java:93) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.gui.util.ThemeLoader.installCss(ThemeLoader.java:82) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:153) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:62) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at org.jabref.JabRefMain.start(JabRefMain.java:77) ~[JabRef-5.0-dev--snapshot--2018-10-29--master--11a62dd5e.jar:?]
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863) ~[jfxrt.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326) ~[jfxrt.jar:?]
        at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
```

In order to try it I've added antivirus and firewall exceptions (and also tried disabling them).
I'm using Windows 10 x64 and Java(TM) SE Runtime Environment (build 1.8.0_191-b12).
I can't add a screenshot nor excerpt of log (available in the error console) because I can't even start the program.

**Comment by Siedlerchr** [comment] 2018-10-30 22:22
@florian-beetz any idea? Does it have to do with the submodule?

**Comment by xiaodongcentury** [comment] 2018-10-31 01:06
Debian 9 sid has the same error.
Jabref version: Jabref master latest.jar 2018-10-30
![image](https://user-images.githubusercontent.com/20276890/47759787-34248000-dcec-11e8-9237-40b26658404c.png)

**Comment by xiangsheng** [comment] 2018-10-31 13:36
macOS Majova has the same problem, Jabref master latest.jar 2018-10-31

**Comment by wujastyk** [comment] 2018-10-31 16:55
Me too.  My jar file is from yesterday, October 30.  

Linux 4.15.0-38-generic amd64 
Java 1.8.0_191


I get the following output, then nothing more.



$ java -jar JabRef--master--latest.jar
10:51:06.239 [JavaFX Application Thread] INFO  org.jabref.logic.importer.OpenDatabase - Opening: /home/dom/Dropbox/localtexmf/bibtex/bib/biblio4-utf8.bib
10:51:08.963 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Could not find file: /ieee.csl
java.nio.file.NoSuchFileException: /ieee.csl
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_191]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_191]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_191]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_191]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_191]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_191]
	at java.nio.file.Files.readAllBytes(Files.java:3152) ~[?:1.8.0_191]
	at org.jabref.logic.citationstyle.CitationStyle.createCitationStyleFromFile(CitationStyle.java:110) ~[JabRef--master--latest.jar:?]
	at org.jabref.logic.citationstyle.CitationStyle.getDefault(CitationStyle.java:127) ~[JabRef--master--latest.jar:?]
	at org.jabref.logic.citationstyle.CitationStyleCache.<init>(CitationStyleCache.java:29) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:177) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1211) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1010) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:123) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:62) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefMain.start(JabRefMain.java:77) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
10:51:09.605 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Could not find file: springer-humanities-author-date.csl
java.nio.file.NoSuchFileException: springer-humanities-author-date.csl
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_191]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_191]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_191]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_191]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_191]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_191]
	at java.nio.file.Files.readAllBytes(Files.java:3152) ~[?:1.8.0_191]
	at org.jabref.logic.citationstyle.CitationStyle.createCitationStyleFromFile(CitationStyle.java:110) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.PreviewPanel.updateLayout(PreviewPanel.java:223) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.PreviewPanel.<init>(PreviewPanel.java:153) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:209) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1211) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1010) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:123) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:62) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefMain.start(JabRefMain.java:77) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
10:51:09.685 [JavaFX Application Thread] ERROR org.jabref.JabRefMain - Unexpected exception
java.nio.file.FileSystemNotFoundException: null
	at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171) ~[zipfs.jar:1.8.0_191]
	at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157) ~[zipfs.jar:1.8.0_191]
	at java.nio.file.Paths.get(Paths.java:143) ~[?:1.8.0_191]
	at org.jabref.gui.util.ThemeLoader.addAndWatchForChanges(ThemeLoader.java:93) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.util.ThemeLoader.installCss(ThemeLoader.java:82) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:153) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:62) ~[JabRef--master--latest.jar:?]
	at org.jabref.JabRefMain.start(JabRefMain.java:77) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$161(LauncherImpl.java:863) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$174(PlatformImpl.java:326) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
10:51:09.690 [JavaFX Application Thread] ERROR org.jabref.logic.citationstyle.CitationStyle - Could not find file: springer-humanities-author-date.csl
java.nio.file.NoSuchFileException: springer-humanities-author-date.csl
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_191]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_191]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_191]
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214) ~[?:1.8.0_191]
	at java.nio.file.Files.newByteChannel(Files.java:361) ~[?:1.8.0_191]
	at java.nio.file.Files.newByteChannel(Files.java:407) ~[?:1.8.0_191]
	at java.nio.file.Files.readAllBytes(Files.java:3152) ~[?:1.8.0_191]
	at org.jabref.logic.citationstyle.CitationStyle.createCitationStyleFromFile(CitationStyle.java:110) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.PreviewPanel.updateLayout(PreviewPanel.java:223) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.PreviewPanel.updateLayout(PreviewPanel.java:210) ~[JabRef--master--latest.jar:?]
	at org.jabref.gui.JabRefFrame.lambda$init$3(JabRefFrame.java:279) ~[JabRef--master--latest.jar:?]
	at org.fxmisc.easybind.EasyBind.lambda$subscribe$12(EasyBind.java:263) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182) ~[jfxrt.jar:?]
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74) ~[jfxrt.jar:?]
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102) ~[jfxrt.jar:?]
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112) ~[jfxrt.jar:?]
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146) ~[jfxrt.jar:?]
	at javafx.scene.control.SelectionModel.setSelectedItem(SelectionModel.java:102) ~[jfxrt.jar:?]
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:717) ~[jfxrt.jar:?]
	at javafx.scene.control.TabPane$TabPaneSelectionModel.select(TabPane.java:735) ~[jfxrt.jar:?]
	at javafx.scene.control.TabPane$TabPaneSelectionModel.findNearestAvailableTab(TabPane.java:794) ~[jfxrt.jar:?]
	at javafx.scene.control.TabPane$TabPaneSelectionModel.lambda$new$17(TabPane.java:691) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329) ~[jfxrt.jar:?]
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73) ~[jfxrt.jar:?]
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233) ~[jfxrt.jar:?]
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482) ~[jfxrt.jar:?]
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541) ~[jfxrt.jar:?]
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205) ~[jfxrt.jar:?]
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155) ~[jfxrt.jar:?]
	at java.util.AbstractList.add(AbstractList.java:108) ~[?:1.8.0_191]
	at org.jabref.gui.JabRefFrame.lambda$addTab$12(JabRefFrame.java:1174) ~[JabRef--master--latest.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by florian-beetz** [comment] 2018-10-31 17:33
@Siedlerchr Yes, this looks like it is caused by #4431. Apparently CircleCI [does not check out the submodules automatically](https://discuss.circleci.com/t/can-not-get-submodules-to-clone-properly/22120/2). The directories in the JARs are empty.

We need to call `git submodule update --recursive --init --remote` after checking out on CircleCI.

**Comment by Siedlerchr** [comment] 2018-10-31 19:06
@florian-beetz  I think for the moment it is okay to automatically check it out. Alterantively we can use it ti pinpoint to a specific version. I will create a PR so that at least our build is fixed
https://stackoverflow.com/questions/10914022/how-do-i-check-out-a-specific-version-of-a-submodule-using-git-submodule

**Comment by Siedlerchr** [comment] 2018-10-31 19:42
Okay, one issue fixed.
The other is the Theme loading. When I run java -jar JabRef.jar it fails.
```

java.nio.file.FileSystemNotFoundException: null
        at com.sun.nio.zipfs.ZipFileSystemProvider.getFileSystem(ZipFileSystemProvider.java:171) ~[zipfs.jar:1.8.0_181]
        at com.sun.nio.zipfs.ZipFileSystemProvider.getPath(ZipFileSystemProvider.java:157) ~[zipfs.jar:1.8.0_181]
        at java.nio.file.Paths.get(Paths.java:143) ~[?:1.8.0_181]
        at org.jabref.gui.util.ThemeLoader.addAndWatchForChanges(ThemeLoader.java:93) ~[JabRef-5.0-dev--snapshot--2018-10-31--fixsubmodule--d24e4358a.jar:?]
        at org.jabref.gui.util.ThemeLoader.installCss(ThemeLoader.java:82) ~[JabRef-5.0-dev--snapshot--2018-10-31--fixsubmodule--d24e4358a.jar:?]

```

**Comment by Siedlerchr** [comment] 2018-11-01 10:46
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed** 2018-11-01 10:46 UTC
Labels: bug
