### ISSUE TITLE
JabRef 3.8.2 update removes all inactive entries from dock on OSX

### ISSUE THREAD

**Issue by cbiertue** [JabRef/jabref#2502] opened 2017-01-31 09:13 UTC
JabRef version 3.8.2
Mac OSX 10.10.5 Yosemite

I have updated JabRef from 3.8.x (don't remember) to 3.8.2 and forgot to unclick make icon in dock (not sure if this triggered it). Then, all inactive icons in my dock were gone and only 5 icons of running programs were left. A restart of the dock or computer did not help. I had to manually put all icons back.

**Comment by stefan-kolb** [comment] 2017-02-08 10:57
@chochreiner WDYT?

**Comment by chochreiner** [comment] 2017-02-08 11:49
I cannot reproduce this on MacOS Sierra 10.12.3 (16D32) by upgrading from 3.8.1 or a development version.
There may be a slight chance, that the current install4j has some issues with Yosemite, but I am not aware of any major changes for the dock in the last two years. 

Is the bug reproducible? - If yes, can you please have a look at the system logs, and check whether something unusual is happening.

**Comment by lenhard** [comment] 2017-02-15 21:03
Due to a lack of reaction and since our OSX developer cannot reproduce the issue, I am closing it.

Feel free to reopen with more information (so that we can reproduce) if you run into the error again

**Closed by lenhard** 2017-02-15 21:03 UTC
Labels: build-system, osx, waiting-for-feedback
