### ISSUE TITLE
latex-unicode conversion & capitalization in JR 5 testversion?

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#5256] opened 2019-08-28 15:21 UTC
JabRef 5.0-dev--snapshot--2019-08-27--master--84436d795
Linux 5.0.0-25-generic amd64 
Java 11.0.4

In JR 4.3.1 (current release) one can right click in a field in the entry editor and a number of highly valuable utilities are offered, including converting character encoding between LaTeX and unicode, capitalization, etc.  These features have been removed from JabRef 5.  I very much hope that they come back, since they are exceptionally useful features.

**Comment by Siedlerchr** [comment] 2019-08-30 07:19
This is odd. I was not aware that this was modified. Duplicate of #5254

**Closed by Siedlerchr** 2019-08-30 07:19 UTC
