### ISSUE TITLE
Despite checked Listen to remote operation on port 6050 new jabref sessions are created upon using jabfox

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2698] opened 2017-03-31 13:25 UTC
JabRef 4.0.0-dev--snapshot--2017-03-27--master--893f0d659
Windows 7 6.1 amd64 
Java 1.8.0_121

Steps to reproduce:

1. Check Options->Advanced->Listen to remote operation on port 6050
2. Use Jabfox with Zotero for Import from Firefox
3. Use the Task Manager to observe that a new Jabref session is created.

![grafik](https://cloud.githubusercontent.com/assets/9216487/24552089/714ede06-1625-11e7-9418-e5fb0ebac6fe.png)
the last jabref session was created while I looked in the taskmanager what happens

**Comment by bernhard-kleine** [comment] 2017-04-01 08:51
I would like to add that when starting Jabref twice (e.g. double click on the icon in the symbol bar)  only one process takes over, but the other stays and is not closed. You cannot even move to that process. Seems the same issue.

**Comment by lenhard** [comment] 2017-04-03 14:51
@bernhard-kleine I tried to fix this and was (hopefully) successful. At least it works for me locally now. Could you give it a try with a version available here http://builds.jabref.org/shutdown-duplicates/ and check that the problem is also gone on your system?

**Comment by lynyus** [comment] 2017-04-03 15:50
This functionality is already merged into master, however, I'm leaving this open until @bernhard-kleine could verify that it actually solves his problem.

If it turns out, that it is indeed resolve it can be closed and the `shutdown-duplicates` branch be deleted.

**Comment by bernhard-kleine** [comment] 2017-04-03 18:02
Importing one entry, it looks that the second process is killed after importing, There are, however, issues with duplicates, but I will raise that in an other issue.

**Closed** 2017-04-03 19:58 UTC
Labels: bug, waiting-for-feedback
