### ISSUE TITLE
Web search preferences "Custom API key" table modifications not discarded

### ISSUE THREAD

**Issue by LoayGhreeb** [JabRef/jabref#11925] opened 2024-10-12 06:27 UTC
When making changes to the "Custom API key" table in the Web search tab of the preferences, the changes are always saved even when I click **Cancel**.

Steps to Reproduce:
1. Open JabRef Preferences.
2. Navigate to the Web Search tab.
3. Make any modifications in the Custom API key table.
4. Click Cancel to close the Preferences window.
5. Reopen the Preferences and navigate back to the Web Search tab.
6. Observe that the modifications are still present.

Expected Behavior:
Clicking Cancel should discard any changes made to the Custom API Key table.

Actual Behavior:
Changes to the Custom API Key table are saved.

![Image](https://github.com/user-attachments/assets/04d4e0de-a793-4b9a-83c5-a3635f265da0)

**Comment by yeonissa** [comment] 2024-10-12 07:30
Hi! Can I take this issue please ^_^

**Comment by u7663394** [comment] 2024-10-13 01:32
Hi,

I have read through this issue and was wondering if I can be assigned to this issue. I am asking to be assigned due to a university group project.

Thank you.

**Comment by u7663394** [comment] 2024-10-16 02:21
Hello, 

When I tried to reproduce the steps described in the issue today, I found myself a bit confused: when I modify the key and then click the cancel button, the changes are discarded (which is expected). However, if I modify the key, press Enter, and then click cancel, the changes are not discarded. 

So I'd like to ask, should the desired behavior be that after modifying the key and pressing Enter, clicking cancel should discard the changes?

**Comment by u7663394** [comment] 2024-10-16 05:40
Hello, 

I have just resolved this issue and have created a PR (https://github.com/JabRef/jabref/pull/11977).

More details can be referred to the PR above. 

Thank you.

**Comment by u7663394** [comment] 2024-10-16 05:46
Additionally, when I was modifying the code, I noticed some red-highlighted errors in the `PreferencesDialogView` class. Since this is unrelated to the issue, I did not make any changes, but I believe it is worth reporting.
![Image](https://github.com/user-attachments/assets/81754b0a-bff2-4b24-be5c-3c05db06fae2)
![Image](https://github.com/user-attachments/assets/35d02724-f92b-4e4b-8d86-9a9cdfe6230d)

**Comment by koppor** [comment] 2024-10-16 08:07
> Additionally, when I was modifying the code, I noticed some red-highlighted errors in the `PreferencesDialogView` class. Since this is unrelated to the issue, I did not make any changes, but I believe it is worth reporting.

Here, it is green. It also compiles on the CI.

Could you hover on the import for KeyCode?`What is the error message?

Did you follow the steps to [enable compilation by IntelliJ](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-12-build.html#enable-compiliation-by-intellij)?

**Comment by u7663394** [comment] 2024-10-16 08:26
> > Additionally, when I was modifying the code, I noticed some red-highlighted errors in the `PreferencesDialogView` class. Since this is unrelated to the issue, I did not make any changes, but I believe it is worth reporting.
> 
> Here, it is green. It also compiles on the CI.
> 
> Could you hover on the import for KeyCode?`What is the error message?
> 
> Did you follow the steps to [enable compilation by IntelliJ](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace/intellij-12-build.html#enable-compiliation-by-intellij)?

That's a bit strange; I confirmed that I followed the steps to enable IntelliJ's compilation. It shows "cannot resolve symbol `KeyCode`".![Image](https://github.com/user-attachments/assets/6f066999-eda5-4544-9996-62d795d81f41)
![Image](https://github.com/user-attachments/assets/5008ce77-2239-4acf-aad9-73721f14616e)

**Comment by u7663394** [comment] 2024-10-16 08:31
> Let's check MainTable.java - the other symbols of `javafx.scene.input` are found?`
> 
> ![Image](https://github.com/user-attachments/assets/3378e7d7-ecd2-43a1-b216-acd5ec003998)

It shows like this - all other symbols can be found, but `KeyCode`
![Image](https://github.com/user-attachments/assets/9d8d087b-cfc3-42f8-a7fb-bdb440c309a9)

**Comment by LoayGhreeb** [comment] 2024-10-16 08:32
Can you try "Rescan Project Indexes"
![Image](https://github.com/user-attachments/assets/720fa99d-f4cf-4bea-9e7c-caa136280773)
![Image](https://github.com/user-attachments/assets/1cf4ee24-ef45-445d-94a5-a0d841ed22c3)

**Comment by u7663394** [comment] 2024-10-16 08:37
Yeah, I have tried. After clicking 'Rescan Project Indexes' and 'Reopen Project', the problem still exists.

**Comment by koppor** [comment] 2024-10-16 10:52
What if you press on the "Refresh" button on Gradle?

![Image](https://github.com/user-attachments/assets/cac99e44-7b3e-46c4-b409-9fd7b15fe459)

---

If these kind of things happen once, they might be happen on other sides. This could be an [FAQ](https://devdocs.jabref.org/code-howtos/faq.html), therefore, we ask for possible fixes etc.

**Comment by u7663394** [comment] 2024-10-16 11:08
> What if you press on the "Refresh" button on Gradle?
> 
> ![Image](https://github.com/user-attachments/assets/cac99e44-7b3e-46c4-b409-9fd7b15fe459)
> 
> If these kind of things happen once, they might be happen on other sides. This could be an [FAQ](https://devdocs.jabref.org/code-howtos/faq.html), therefore, we ask for possible fixes etc.

Hi, I just tried to refresh, but it does not worked. 
Btw, I am on Windows 11 x64 system and using Intellij IDEA 2022.3.3 version.

**Comment by koppor** [comment] 2024-10-16 11:12
> Hi, I just tried to refresh, but it does not worked. Btw, I am on Windows 11 x64 system and using Intellij IDEA 2022.3.3 version.

Your IntelliJ is pretty old. I am on 2024.2.3. Then it might be an issue of that version and we don't need to invest time. In case you are going to contribute more to the project and cannot update to 2024, we could invest time.

**Comment by u7663394** [comment] 2024-10-16 11:17
Understood, thank you for your response. I can upgrade IntelliJ IDEA, and this issue does not currently affect my normal operation with JabRef.  Cheers :)

**Closed** 2024-10-16 11:19 UTC
Labels: ui, preferences, good first issue, FirstTimeCodeContribution
