### ISSUE TITLE
Improve citation styles code

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#5246] opened 2019-08-26 18:33 UTC
1. open the preference dialog
2. the error message is immediate

<details>
  <summary>Log File</summary>
  
  ```


  ```
![grafik](https://user-images.githubusercontent.com/9216487/63713872-c7f9a680-c840-11e9-80aa-a5dcd4580ac1.png)

</details>

**Comment by stefan-kolb** [comment] 2019-08-26 20:57
I have tested the described behavior, but cannot reproduce it.

**Comment by Siedlerchr** [comment] 2019-08-26 21:14
I also had it today when I used the latest version with the installer on windows 10.
(not running from gradlew)

**Comment by stefan-kolb** [comment] 2019-08-26 21:54
Ok, does only occur with the build version not from IntelliJ.

**Comment by tobiasdiez** [comment] 2019-09-08 14:36
In the end, the problem is that there is no (supported) way of getting a list of resources matching a given pattern. There are some [workarounds](https://stackoverflow.com/questions/3923129/get-a-list-of-resources-from-classpath-directory) but no clean way that always works. Thus, I would propose the following:
- Add an automatically created index file that references all available style files (including relative paths)
- Add this index file as a resource
- Read this file and then create a list of all styles on runtime

As I have no experience how our code generation tools work, I'll leave this for somebody else. (@Siedlerchr @koppor ?).

Moreover, I noticed that because of the following line the preference tab is loaded when the preference dialog is opened instead of only when the preview tab is selected. It would be good to support a lazy loading/init to improve the performance of the preference dialog. @calixtus 
https://github.com/JabRef/jabref/blob/8bb6380e177006fd798621809ba6d99314090615/src/main/java/org/jabref/gui/preferences/PreviewTabViewModel.java#L81

**Comment by hsvia** [comment] 2019-09-08 16:54
Hi,
I use always the latest development version.
I have the same problem withe the preferences dialog since some 3 weeks ago.
There was **no change in my style file** at this time !
Currently i use:

JabRef 5.0-dev--snapshot--2019-09-08--master--373b9f5f5
Windows 10 10.0 amd64 
Java 11.0.4-bellsoft

It was installed from:
JabRef_windows-x64_5_0-dev--snapshot--2019-09-08--master--373b9f5f5.exe

The error occures only in case the preferences dialog is **opened first after JabRef is started**.
I can save the preferences, close the preferences then it works fine as I had opened it before with a running JabRef.
Then I close JabRef and opne the preferences and get the same error again.
Her once more the error listing:

 java.nio.file.FileSystemAlreadyExistsException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:344)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
	at org.jabref.logic.citationstyle.CitationStyle.discoverCitationStyles(CitationStyle.java:147)
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:46)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:122)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

I run JabRef on three different computers, twice under win10, one under win 8.1.. The problem is 3 times the same. As mentioned it did not happen some 3 weeks ago.

**Comment by Siedlerchr** [comment] 2019-10-04 13:35
In general the styles are working,  but the behavior is  a bit odd:
I am only getting the error message when running from the installer.
The problem seems to be that you cannot create the same file system twice.

The only issue is that I need to close and reopen the library if I changed the order of styles, e.g. moved the ACM style before preview.

**Comment by tobiasdiez** [comment] 2019-10-17 20:55
This should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

I'll leave this open as the code needs be improved.

**Comment by Siedlerchr** [comment] 2020-02-27 10:10
This issue should be fixed now in master. Please wait until the new build is ready. That takes approx half an hour or so. 

 We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2020-02-27 10:10 UTC
Labels: code-quality, preferences
