### ISSUE TITLE
BibTeX format differs between machines

### ISSUE THREAD

**Issue by MatthewGerber** [JabRef/jabref#823] opened 2016-02-15 20:42 UTC
I am using JabRef 3.2 on two different Macs, and I am seeing two different BibTeX formats for the same entry. First, what I see in OSX 10.10.5:

![screen shot 2016-02-15 at 3 35 41 pm](https://cloud.githubusercontent.com/assets/4643066/13059732/507003a4-d3fa-11e5-8bfc-c6bb5ab6001d.png)

Then what I see in OSX 10.11.1:

<img width="1071" alt="screen shot 2016-02-15 at 3 35 40 pm" src="https://cloud.githubusercontent.com/assets/4643066/13059723/448d871e-d3fa-11e5-824e-9a8bdfcaf26d.png">

As you can imagine, this is destroying any advantage of viewing diffs of these files. Any idea what is causing the format differences? How do I keep the formats the same across machines?

**Comment by lenhard** [comment] 2016-02-16 10:30
This likely is a different issue. JabRef 3.2 only reformats entries that have been changed during the current session. If any part of an entry is changed, the complete entry is reformatted according to your first example. If an entry is not changed, it is written back in exactly the same format as it has been read in. The target here is to modify as little in the bib file as possible.

Can you please check what happens to the entry in your second system if you perform a change and save? And just to be sure, are you *really* sure that you are using JabRef 3.2 on your second system?

**Comment by koppor** [comment] 2016-02-16 12:22
Related: [JabRef 3.2 and automatic formatting on save](http://tex.stackexchange.com/q/292528/9075).

**Comment by tobiasdiez** [comment] 2016-03-02 20:07
I think this issue can be closed since the reformatting is (probably) due to a change in the entry.

**Comment by lenhard** [comment] 2016-03-04 11:30
Ok, since @MatthewGerber does not reply, we guess about the cause. So, I am closing this issue.

Feel free to reopen if the above problem can be confirmed.

**Closed by lenhard** 2016-03-04 11:30 UTC
Labels: question
