### ISSUE TITLE
Download of files put them in subfolders

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#6589] opened 2020-06-05 21:20 UTC
Just a quick note for now: after downloading a linked online file, it was put in the folder `standardRoot/citationkey/`. Not sure why and under which conditions this is reproducible.

**Comment by Siedlerchr** [comment] 2020-06-06 07:45
Did you specify a file fit name or file dir pattern?

**Comment by Siedlerchr** [comment] 2020-06-07 15:32
I could reproduce it using some arxiv fulltext download

**Comment by Siedlerchr** [comment] 2020-06-07 15:52
The issue is here:
https://github.com/JabRef/jabref/blob/a080191bc07f51e0caa77e549c31be6ba0346786/src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java#L451

If the parameter is empty string the citeky is returned.
https://github.com/JabRef/jabref/blob/7cc57474b7aa991ef6ea148d4030d4bb68ee69bf/src/main/java/org/jabref/logic/util/io/FileUtil.java#L283-L288

**Comment by tobiasdiez** [comment] 2020-06-07 16:13
@btut could you please have a look at this. If I'm not mistaken, then you added this in https://github.com/JabRef/jabref/pull/6381. Thanks!

**Comment by Siedlerchr** [comment] 2020-06-15 05:41
Now fixed in latest master

**Closed** 2020-06-15 05:41 UTC
Labels: external files, good first issue, type: bug 🐛

**Comment by btut** [comment] 2020-06-15 19:23
Thanks!
