### ISSUE TITLE
Jabref Icon not showing well in the task bar

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2856] opened 2017-05-19 14:12 UTC
The new jabref icon is not very well recognized on my windows desktop in the task bar. As can be seen from the screenshot. Maybe you can make it more discriminatory?
![jabrefscreenicon](https://cloud.githubusercontent.com/assets/9216487/26251425/80cc18ae-3cad-11e7-85f0-d6b9febe1428.PNG)

**Comment by tobiasdiez** [comment] 2017-05-19 14:22
This is a duplicate of #2648.

**Closed by tobiasdiez** 2017-05-19 14:22 UTC
