### ISSUE TITLE
"Merge entry with DOI information" does not apply changes to entry type

### ISSUE THREAD

**Issue by darkdragon-001** [JabRef/jabref#1062] opened 2016-03-30 12:42 UTC
JabRef version 3.2

Steps to reproduce:

1. Right click on entry > Get BibTeX data from DOI
2. _Select information_
3. Replace original entry
4. _Changes are not applied!_

Maybe this has to do with the fact that the previous entry had an invalid entry type (`Other`).

**Comment by stefan-kolb** [comment] 2016-03-30 15:15
In fact it has to with the invalid entry type. Other than that it works for me. I'll investigate further.

**Comment by stefan-kolb** [comment] 2016-03-30 15:55
The problem is that the GUI suggest that you can change the type of the entry but the actual logic does only compare the fields of both entries. 

@oscargus You worked a little bit on the merge dialog?! Did you change anything or didn't we have this functionality at all?

**Comment by oscargus** [comment] 2016-03-30 16:03
I do not think I broke it at least. Might never have worked...

(The latest rework is not yet merged. I'll try to fix it there...)

**Comment by stefan-kolb** [comment] 2016-03-30 16:21
I just fixed it :smile:

**Closed** 2016-03-30 16:47 UTC
Labels: bug
