### ISSUE TITLE
Look up full text fails for recent entries

### ISSUE THREAD

**Issue by barefeg** [JabRef/jabref#1023] opened 2016-03-23 08:09 UTC
I'm having an issue when I try to look up the full text document of an Arxiv paper that came out the same day. It outputs Full text article download failed. This seems to happen only with very recent entries. If I wait a couple of days then the full text download is successful.

* JabRef version (available in the About box): 3.2
* Operating system and version: OSX 10.11
* Steps to reproduce:
  1. Add a recent entry from the arxiv 
  2. Lookup full text document

**Comment by stefan-kolb** [comment] 2016-03-23 08:45
The question is which fetcher does retrieve your paper in the end (you may take a look at the log `Help-Show error console`).
The arxiv fetcher itself only retrieves PDFs if there is a valid DOI included.
Most other papers will be retireved over Google scholar, which is probably the case here too.
And that might take a few days until they index new papers from arxiv.
Nothing we can really do about except fetching arxiv by title or anything.

**Comment by barefeg** [comment] 2016-03-23 09:22
The Log doesn't show any info on the fetcher:

Mar 23, 2016 10:16:20 AM net.sf.jabref.JabRef openBibFile

This is all I see. Is it possible to fetch by arXiv identifier? (arxiveprefix + eprint) I think this is enough to get the <link> from the arXiv API.

**Comment by stefan-kolb** [comment] 2016-03-23 09:31
The problem is, where should be get the arXiv identifier from? It could be located in any field of the entry.
If you enter the DOI of the paper the download should work instantly.
Isn't this a possibility for you?

**Comment by tobiasdiez** [comment] 2016-03-23 09:59
At least in biblatex there a dedicated fields for preprints, like eprint and eprinttype. I think a proper ArXiv fulltext fetcher is required to fix this issue.

**Comment by barefeg** [comment] 2016-03-23 11:55
Yes, the arXiv identifier is in the eprint field. When you use Fetch Inspire or Fetch ArXiv.org these fields are populated automatically. I can't use DOI because these are non-peer reviewed papers (yet).

**Comment by stefan-kolb** [comment] 2016-03-23 13:03
Hm, so what will be included inside the eprint field? `arXiv:1603.06570` or `1603.06570`?

**Comment by barefeg** [comment] 2016-03-23 13:06
Only 1603.06570. Example 
http://export.arxiv.org/api/query?search_query=id:1603.06570

**Comment by stefan-kolb** [comment] 2016-03-23 13:19
Should be resolved on `master`now. you can try it out in a few minutes at builds.jabref.org.

**Closed** 2016-03-23 13:19 UTC
Labels: waiting-for-feedback

**Comment by barefeg** [comment] 2016-03-23 13:33
Working correctly. Thanks a lot!
