### ISSUE TITLE
Uncaught exception occurred in Thread[#53,JavaFX Application Thread,5,main] (-> Run JabRef as Admin as a fix)

### ISSUE THREAD

**Issue by tmlmao** [JabRef/jabref#11151] opened 2024-04-05 09:21 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Using search and citationkey

### Appendix

...
<details>

<summary>Log File</summary>

```
Paste an excerpt of your log file here
```

</details>
Uncaught exception occurred in Thread[#53,JavaFX Application Thread,5,main]
java.lang.StringIndexOutOfBoundsException: Range [7, -2147483642) out of bounds for length 7
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at org.jabref.merged.module@5.14.4/com.sun.glass.ui.win.WinTextRangeProvider.GetText(Unknown Source)
	at org.jabref.merged.module@5.14.4/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.14.4/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Siedlerchr** [comment] 2024-04-05 11:15
Can you please try the version from here?  https://builds.jabref.org/jdk-ea/
Alternatively, try running the App as Administrator

**Comment by JanSeitz** [comment] 2024-04-05 12:13
It works when I run JabRef as administrator. However, this seems for me impractical.
But thank you very much for that idea!

**Comment by Siedlerchr** [comment] 2024-04-05 16:25
Can you please tell me wich Windows version you are running exactly? e..g best to include the version string or build number

**Comment by JanSeitz** [comment] 2024-04-05 16:32
Windows 10 Home
10.0.19045 N/A Build 19045

**Comment by Siedlerchr** [comment] 2024-04-05 16:42
Just tested on my other computer with Windows 10 Home 22H2 19045.4170  and it works fine. Do you have any accessibility stuff enabled? on screen keyboard of anything related?

**Comment by JanSeitz** [comment] 2024-04-05 16:46
No, I am not using any accessibility stuff.
My .bib document is on a network drive. Could that be a problem?

**Comment by JanSeitz** [comment] 2024-04-05 16:52
It also has problems on the local disc.

**Comment by JanSeitz** [comment] 2024-04-05 16:52
And the problem occurs when I want to add a new source.

**Comment by koppor** [comment] 2024-04-05 17:11
Let us know your graphics card, driver version and screen resolution if possible 😅

**Comment by Siedlerchr** [comment] 2024-04-05 17:13
How do you add the source? New entry? copy pasting in the entry editor?

**Comment by JanSeitz** [comment] 2024-04-05 19:24
Drag and drop to the collection, copy paste in the entry editor and name search in the entry editor.
Manual new entries work. But changing old entries also result in an error message.


Am 05.04.2024 19:13 schrieb Christoph ***@***.***>:

How do you add the source? New entry? copy pasting in the entry editor?

**Comment by koppor** [comment] 2024-04-11 20:39
I tried with auto completion enabled: Windows 11 (`Microsoft Windows [Version 10.0.22631.3447]`) with AMD Radeon works.

@JanSeitz Wild guessing: Does resetting the preferences help?

**Comment by JanSeitz** [comment] 2024-04-11 21:53
Hi Oliver,

resetting perferences also doesn’t work.
I recognized that the titlebar shows “null” lwhen I start Jabref for a short time. In my memory that wasn’t the case before.

BR
Jan

**Comment by koppor** [comment] 2024-04-12 07:28
> Hi Oliver, resetting perferences also doesn’t work. I recognized that the titlebar shows “null” lwhen I start Jabref for a short time. In my memory that wasn’t the case before. 

The `null` thing happens since years 😅. Interesting that there is a larger UI delay at your side now.

**Comment by dfw63** [comment] 2024-04-16 06:27
Same problem here
Edition	Windows 11 Home
Version	23H2
Installed	‎06.‎12.‎2022
Build	22631.3447
Windows Feature Experience Pack 1000.22688.1000.0

JabRef 5.13--2024-04-01--6bdcf63
Windows 11 10.0 amd64 
Java 21.0.2 
JavaFX 22+30

Upon entering just two digits into the New Entry ->"Select Entry Type" -> DOI:

java.lang.StringIndexOutOfBoundsException: Range [2, -2147483647) out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$1.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions$4.apply(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Unknown Source)
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)

*Running Jabref as Admin indeed works.*

**Comment by dfw63** [comment] 2024-04-16 06:40
Tested (as non-privileged user)
JabRef 5.14--2024-04-15--93e0174
Windows 11 10.0 amd64 
Java 22 
JavaFX 23-ea+12
Problem persists.

**Comment by koppor** [comment] 2024-04-16 06:50
I think, we are not the only ones in the world where this happens -- https://stackoverflow.com/q/78332309/873282

**Comment by koppor** [comment] 2024-04-16 08:01
@dfw63 I assume you installed a Windows update? And JabRef worked before? Do you have your update history at hand?

**Comment by koppor** [comment] 2024-04-16 08:22
We should need if old versions of JabRef are affected. Does [v5.11](https://github.com/JabRef/jabref/releases/tag/v5.11) (JavaFX 20) still work?

**Comment by liamsharp** [comment] 2024-04-16 08:47
We've been having the same issue in the Java app I work on. We'd never seen this issue at all until 24/03/24, and have seen an sudden increase since. We've using Java & JavaFX 17. The issue we believe is due to an Windows update, but have yet to be able to reproduce it ourselves, but have lots of customer that can. The issue also happens with Java 21 & JavaFX 21. We have an LTS relationship with [Gluon](https://gluonhq.com/products/javafx/) and they have patched JavaFX for us to stop this from happening.

**Comment by dfw63** [comment] 2024-04-16 09:58
> @dfw63 I assume you installed a Windows update? And JabRef worked before? Do you have your update history at hand?

![image](https://github.com/JabRef/jabref/assets/81810612/15ccf561-ff83-40a6-b710-5dedc9a29424)

Sorry, it is in German. Unfortunately I cannot exactly tell when the Jabref issue started for me.

**Comment by koppor** [comment] 2024-04-16 17:49
Current state: Tried to [add a hotfix](https://github.com/koppor/jfx/pull/2/commits/71dba14d82196d41d6c9014fbbfcbec3fe0d7d2e). Did [try to use in JabRef](https://github.com/JabRef/jabref/pull/11212), but did not succeed.

Thus, we need to wait that someone reports to Oracle and that they fix it.

**Comment by koppor** [comment] 2024-04-16 18:48
@Siedlerchr Does the reproducer have a text field?

The MWE from SO is:

```java
    // launch the application
    public void start(Stage s)
    {
        // set title for the stage
        s.setTitle("creating TextField");

        // create a textfield
        TextField b = new TextField();

        // create a stack pane
        StackPane r = new StackPane();

        // add textfield
        r.getChildren().add(b);

        // create a scene
        Scene sc = new Scene(r, 200, 200);

        // set the scene
        s.setScene(sc);

        s.show();
    }
```

I think, simply adding a text field to the reproducer will show the error.

**Comment by koppor** [comment] 2024-04-17 08:06
There is now a JDK issue: https://bugs.openjdk.org/browse/JDK-8330462

**Comment by koppor** [comment] 2024-04-17 08:15
@dfw63 Could you uninstall the recent update? Also das 2024-04 H2 update. Das ganz oben auf der Liste? - Das Ding ist, dass es hier auf meiner Kiste (AMD-Graphikkarte) läuft und ich hier im Blindflug rate, was es denn sein könnte :)

**Comment by koppor** [comment] 2024-04-17 08:16
@dfw63 Schreib mir auch gerne privat - Wir müssen irgendwie das konkrete Setup rausfinden, weil es bei der Mehrheit der Leute noch funktioniert.

**Comment by koppor** [comment] 2024-04-17 08:26
Please try the reproducer available at "Artifacts" at https://github.com/Siedlerchr/javafxreproducer/actions/runs/8718689729?pr=19. If it happens also there, we can enrich the reproducer to output more environment information to track down the issue.

(PR creating these artifacts: https://github.com/Siedlerchr/javafxreproducer/pull/19)

**Comment by dfw63** [comment] 2024-04-17 09:11
JabRef 5.14--2024-04-15--93e0174
Windows 11 10.0 amd64 
Java 22 
JavaFX 23-ea+12

On my machine the problem disappears as soon as I close the Deepl app (the program that allows you to open deepl typing Ctr-C twice). Once off, Jabref works normally. When on again, crash on entering DOIs or whatever again... Seems to be reproducible.

**Comment by koppor** [comment] 2024-04-17 11:09
@dfw63 Thank you so much for the reproducer. I could not resist and to post it on Mastodon: https://mastodon.acm.org/@koppor/112286143673069313. Now that the issue is reproducible, I am hoping for a fast fix.

**Comment by dfw63** [comment] 2024-04-17 11:55
It is important to switch on/off the deepl app in the residential area (system tray, lower right corner). In jabref, I can even recover from the crash by closing the deepl app in the system tray, then getting back to it by opening the app again. Pretty funny.

**Comment by andy-goryachev-oracle** [comment] 2024-04-17 16:38
https://bugs.openjdk.org/browse/JDK-8330462

**Comment by koppor** [comment] 2024-04-18 12:06
Proposed a fix at https://github.com/openjdk/jfx/pull/1442.

**Comment by VivaldoMendes** [comment] 2024-04-30 18:29
I can confirm that the problem in my case was related to the DeepL App. After removing this app, JabRef is working without OK, and the problem with the Uncaught exception is gone.

**Comment by dfw63** [comment] 2024-05-23 07:52
Tested today, no issues any more.

**Comment by Siedlerchr** [comment] 2024-08-25 17:59
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2024-08-25 17:59 UTC
Labels: os: windows
