### ISSUE TITLE
Groups only show 4 digit number of entries

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#8797] opened 2022-05-15 13:57 UTC
### JabRef version

Other (please describe below)

### Operating system

GNU / Linux

### Details on version and operating system

JabRef 5.7--2022-05-15--a90ee23 Linux 5.17.6-300.fc36.x86_64 amd64  Java 18.0.1  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

open a library with more than 9999 entries; the first digit is not shown on my system.

### Appendix

![Screenshot from 2022-05-15 15-56-15](https://user-images.githubusercontent.com/20518297/168476574-e2c8c274-c438-439c-bc26-72856f68306f.png)

**Comment by LIM0000** [comment] 2022-05-16 01:37
### JabRef version
version 5.6

### Operating system
Window 10

![ss](https://user-images.githubusercontent.com/49628911/168505280-8ec73bee-0931-44ae-b6a0-c26e1339803d.png)

It looks good with JabRef in Window 10.

**Comment by ilippert** [comment] 2022-06-14 10:37
On

JabRef 5.7--2022-06-12--e3b2ab2
Linux 5.17.13-300.fc36.x86_64 amd64 
Java 18.0.1 
JavaFX *unknown*

Fedora 36 it is still a problem

**Comment by ThiloteE** [comment] 2022-06-16 20:23
@LIM0000 would you mind sharing your database with 16 760 entries? :D

**Comment by Siedlerchr** [comment] 2022-06-16 21:47
@ThiloteE you can generate one yourself scripts/bib-file-generator.py

**Comment by ThiloteE** [comment] 2022-06-16 22:46
How can I run the script?

**Comment by LIM0000** [comment] 2022-06-16 22:58
Hi @ThiloteE , you can 
1. download python 3 from here https://www.python.org/downloads/.
2. install latest version of python 3 to your system
3. create a file name `bib-file-generator.py` using notepad and copy all the lines from https://github.com/JabRef/jabref/blob/main/scripts/bib-file-generator.py into your file
4. Open terminal and command `python3 bib-file-generator.py`

Additional note:
Please navigate to `bib-file-generator.py` directory using `cd` command, otherwise absolute path might be needed. 

Hope this helps.

**Comment by Siedlerchr** [comment] 2022-06-17 14:17
Can confirm:
<img width="518" alt="grafik" src="https://user-images.githubusercontent.com/320228/174315175-0bbbffcc-b3e3-4a7a-a7ec-7439e2b8a4ce.png">

Probably the size calculation needs to be adjusted:
https://github.com/JabRef/jabref/blob/a355534765b581861cb656c1fb18709f3e6299d0/src/main/java/org/jabref/gui/groups/GroupTreeView.java#L116-L121

**Comment by ThiloteE** [comment] 2022-07-13 08:46
refs https://github.com/JabRef/jabref/issues/6042
Might have been disabled intentionally to increase performance for large databases.

**Comment by theshashankpal** [comment] 2022-09-10 05:11
Hi @ThiloteE ,
I am a student who needs to contribute to an OpenSource project in my coursework, so I was wondering if you can assign this to me.
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by ThiloteE** [comment] 2022-09-10 07:56
Yes you can :-)

As a general advice: Check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is worth having a look at. Feel free to ask if you have any questions here on GitHub or also at JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat.

Try to open a (draft) pull request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by Siedlerchr** [comment] 2022-11-11 11:36
In yesterday's mob programming session, we could reproduce the behavior by changing the font size in the preferences (Appearance → Override default font size) 

Very likely this method needs to be adjusted
https://github.com/JabRef/jabref/blob/a1f2d5181ce1d99674c30bbd4894158f9b3d1437/src/main/java/org/jabref/gui/groups/GroupTreeView.java#L195-L225

**Comment by alescrocaro** [comment] 2022-12-12 17:25
Hey @Siedlerchr, we solved this [here](https://github.com/alescrocaro/jabref/issues/5), for a university project. Could you take a look?

**Comment by Siedlerchr** [comment] 2023-01-04 12:57
Note. The issue is not solved. I tried to check some options and the font size is set correctly for the text, I tried the following but did not succeed:

```
   if(group.isRoot()) {
                                        EasyBind.subscribe(group.getHits(), (val)-> {
                                            double width = text.getBoundsInLocal().getWidth();
                                            node.setMaxWidth(width);
                                            node.setPrefWidth(width);
                                        });
                                    }
```

**Comment by sambhav97** [comment] 2023-03-07 16:56
Hi, can I work on this issue if it's still open?

**Comment by Siedlerchr** [comment] 2023-03-07 18:20
@sambhav97  Yes, make sure to read through the thread.  Easiest way to reproduce: Change the font size in the preferences -> Appearance -> Override default font size. Change to e.g. 12

**Comment by calixtus** [comment] 2023-03-19 20:09
Hint: Controls should be sized in relation to the base font size of the main application window. See the documentation on jfx css measure units: https://docs.oracle.com/javafx/2/api/javafx/scene/doc-files/cssref.html#typelength

**Closed** 2023-03-22 07:28 UTC
Labels: type: bug 🐛, ui, os: linux, groups, good first issue
