### ISSUE TITLE
The ordering of columns in the main table was disabled?

### ISSUE THREAD

**Issue by ninfito** [JabRef/jabref#4886] opened 2019-04-14 22:22 UTC
1) Open a bib-file in JabRef. 
2) Click on the column headers in the main table and try to sort by any of the columns
3) This functionality seems to be disabled. 

How can I enable it again? Is it a bug? (Event log window is empty).

JabRef 5.0-dev--snapshot--2019-04-14--master--939cf59c2
Linux 5.0.7-1-default amd64 
Java 1.8.0_201 (build 1.8.0_201-b09)

**Comment by Siedlerchr** [comment] 2019-04-15 07:18
Thanks for the report, that is definitely a regression bug. It was working fine a few versions ago, if I remember correctly.

**Comment by Siedlerchr** [comment] 2019-04-15 07:35
@tobiasdiez  I found the issue: 
In the maintable, if I remove the bindings wrapper it works again
```
 this.setItems(BindingsHelper.forUI(model.getEntriesFilteredAndSorted()));
        // Enable sorting
        model.getEntriesFilteredAndSorted().comparatorProperty().bind(this.comparatorProperty());

```

**Comment by bernhard-kleine** [comment] 2019-05-06 19:09
The issue is not solved in the latest snapshot of today (2019-05-06 c168c4978).

**Comment by bernhard-kleine** [comment] 2019-05-11 09:29
@Siedlerchr, @tobiasdiez What is the problem with this, why is the correction not yet applied? It renders my working with Jabref very difficult. The version snapshot--2019-05-10--master--751c5b5e7 does not have sorting back.

**Comment by Siedlerchr** [comment] 2019-05-11 10:10
Please be patient!  We understand that this is an important issue. As long as the issue is not closed it's not fixed. No need to constantly question it.  Come on, you know the rules.
While the fix looks simple it might have other consequences which we need to check. But I will look at it in detail now.

**Closed** 2019-05-11 15:40 UTC
Labels: bug, maintable

**Comment by Siedlerchr** [comment] 2019-05-11 15:41
Should be fixe now in the latest master 3baa6bd 

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Comment by ninfito** [comment] 2019-05-11 15:47
Great, it works! Thanks.
