### ISSUE TITLE
Upon exiting Jabref  is still active in the Windows task manager

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#4403] opened 2018-10-23 20:14 UTC
JabRef 5.0-dev--snapshot--2018-10-23--master--eda8e2628
Windows 7 6.1 amd64 
Java 1.8.0_181 

- [ +] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

Steps to reproduce:

1. Open the last development version
2. Check in the task manager that is present
3. Exit JabRef
4. The jabref entry remains open in the task manager.
BTW the backup file .sav is not deleted upon closing the database.

This problem is not new. It causes upon opening e.g. message/question whether to use the backup version of a database or not, since the .sav file is not deleted when closing. In my humble opinion, the underlying problem is partially responsible for fact that while the port 65?? is checked in options, there are two different JabRef entries possible with JabRef 5.0dev. There is something fishy with the Windows interaction.

**Comment by Siedlerchr** [comment] 2018-10-24 12:07
Do you have autosave enabled? #4352

**Comment by bernhard-kleine** [comment] 2018-10-24 12:14
Yes I do.

**Comment by Siedlerchr** [comment] 2018-10-29 19:01
Closing this issue as duplicate of #4321

**Closed by Siedlerchr** 2018-10-29 19:01 UTC
