### ISSUE TITLE
Execution fails in Linux 

### ISSUE THREAD

**Issue by jorgman1** [JabRef/jabref#7112] opened 2020-11-21 10:00 UTC
JabRef 5.2.272-1 (2020-11-20) on Linux Mint 18.1 Cinnamon 64.bit (3.2.7)

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Try to execute jabref
2. In JabRef 5.2.194-1 (2020-10-23) I get some errors printed on the terminal, but JabRef starts

<details>
  <summary>Log in 5.2.272-1</summary>

> 	ERROR StatusLogger Unrecognized format specifier [d]
	ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [thread]
	ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [level]
	ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [logger]
	ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [msg]
	ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [n]
	ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [d]
	ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [thread]
	ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [level]
	ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [logger]
	ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [msg]
	ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
	ERROR StatusLogger Unrecognized format specifier [n]
	ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
	Exception in Application start method
	%d [%thread] %-5level %logger - %msg%n java.lang.RuntimeException: Exception in Application start method
		at com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source) ~[org.jabref.merged.module:?]
		at java.lang.Thread.run(Unknown Source) [?:?]
	Caused by: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
		at com.airhacks.afterburner.injection.Injector.initialize(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.instantiateModelOrService(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.injectMembers(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.injectMembers(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.registerExistingAndInject(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.instantiatePresenter(Unknown Source) ~[org.jabref.merged.module:?]
		at org.jabref.gui.DefaultInjector.instantiatePresenter(Unknown Source) ~[org.jabref:?]
		at com.airhacks.afterburner.views.ViewLoader.lambda$updateControllerFactory$5(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader$ValueElement.processAttribute(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader$Element.processStartElement(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader.processStartElement(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader.loadImpl(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader.loadImpl(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader.load(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.views.ViewLoader.load(Unknown Source) ~[org.jabref.merged.module:?]
		at org.jabref.gui.groups.GroupSidePane.createContentPane(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePaneComponent.getContentPane(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePane.setComponents(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePaneManager.updateView(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePaneManager.show(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePaneManager.<init>(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.JabRefFrame.init(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.JabRefGUI.openWindow(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.JabRefGUI.<init>(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
		at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
		at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
		at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
		at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source) ~[org.jabref.merged.module:?]
		... 1 more
	Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
		at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
		at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
		at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
		at com.airhacks.afterburner.injection.Injector.initialize(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.instantiateModelOrService(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.injectMembers(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.injectMembers(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.injectAndInitialize(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.registerExistingAndInject(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.injection.Injector.instantiatePresenter(Unknown Source) ~[org.jabref.merged.module:?]
		at org.jabref.gui.DefaultInjector.instantiatePresenter(Unknown Source) ~[org.jabref:?]
		at com.airhacks.afterburner.views.ViewLoader.lambda$updateControllerFactory$5(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader$ValueElement.processAttribute(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader$InstanceDeclarationElement.processAttribute(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader$Element.processStartElement(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader$ValueElement.processStartElement(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader.processStartElement(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader.loadImpl(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader.loadImpl(Unknown Source) ~[org.jabref.merged.module:?]
		at javafx.fxml.FXMLLoader.load(Unknown Source) ~[org.jabref.merged.module:?]
		at com.airhacks.afterburner.views.ViewLoader.load(Unknown Source) ~[org.jabref.merged.module:?]
		at org.jabref.gui.groups.GroupSidePane.createContentPane(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePaneComponent.getContentPane(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePane.setComponents(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePaneManager.updateView(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePaneManager.show(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.SidePaneManager.<init>(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.JabRefFrame.init(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.JabRefGUI.openWindow(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.JabRefGUI.<init>(Unknown Source) ~[org.jabref:?]
		at org.jabref.gui.JabRefMain.start(Unknown Source) ~[org.jabref:?]
		at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(Unknown Source) ~[org.jabref.merged.module:?]
		at java.security.AccessController.doPrivileged(Unknown Source) ~[?:?]
		at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source) ~[org.jabref.merged.module:?]
		at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[org.jabref.merged.module:?]
		at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source) ~[org.jabref.merged.module:?]
		... 1 more
	Failed to launch JVM
</details>

<details>
  <summary>Log in 5.2.194-1</summary>

> ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.

(JabRef:7447): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
</details>

**Comment by Siedlerchr** [comment] 2020-11-21 10:28
There seems to be something broken with the groups tree, I think @mlep had a similar problem. 
Would it be possible to share your library? It would help us to reproduce the errors 
If you don't want to share it public, you can send it to developers@jabref.org

**Comment by Siedlerchr** [comment] 2020-11-21 16:51
Thanks for reporting this issue. We found the problem was due a recent change. This issue is now fixed again in master(currently building)

**Closed** 2020-11-21 16:51 UTC
Labels: groups, status: waiting-for-customer-feedback, type: bug 🐛

**Comment by jorgman1** [comment] 2020-11-21 19:53
Thank you for the quick fix. It works with the newest master.
