### ISSUE TITLE
Dark theme: Search: case sensitive is case insensitive (and vice-versa)

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#6791] opened 2020-08-25 15:12 UTC
JabRef 5.1--2020-08-25--2ce90ad
Linux 4.9.0-13-amd64 amd64 
Java 15-ea

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

With the dark theme, if the "case sensitive" button is activated in the search bar, the search is case unsensitive.
And if the "case sensitive" button is deactivated in the search bar, the search is case sensitive. 
Note: It works as expected in the light mode.

0. activate the light theme (and restart)
1. open  https://github.com/JabRef/jabref/blob/master/src/test/resources/testbib/jabref-authors.bib
2. in the search bar, type "garrido"
3. if "case sensitive" is activated (i.e. "abc" is bold in the button), "No result found".
   if "case sensitive" is deactivated (i.e. "abc" is light in the button), "9 results found".
       (as expected)
4. now activate the dark theme (and restart)
5. in the search bar, type "garrido"
6. if "case sensitive" is activated (i.e. "abc" is bold in the button), "9 results found"
![Dark-CaseSensitiveActivated](https://user-images.githubusercontent.com/6931104/91191782-7dca3000-e6f5-11ea-9ed9-ca0a028fba4a.png)
   if "case sensitive" is deactivated (i.e. "abc" is light in the button), "No result found"
![Dark-CaseSensitiveDeactivated](https://user-images.githubusercontent.com/6931104/91191789-80c52080-e6f5-11ea-83d0-c89b2b58ad22.png)

So, in the dark theme:
1) the behavior is opposite to the one of the light theme
2) search is visually case sensitive when, in fact, it is not.

**Comment by mlep** [comment] 2020-08-26 06:30
The same goes with the button for regular expression search: when supposedly activated (i.e. button in bold), search works like if the button is not activated. And vice-versa:

- `title=modeling`  ==> "Found 7 results."
- `title=modelling`  ==> "Found 5 results."
- `title=modell?ing`  and regular expression button bold ==> "No result found."
- `title=modell?ing`  and regular expression button dimmed ==> "Found 12 results."

**Comment by Siedlerchr** [comment] 2020-08-26 07:02
Thanks for the investigation, seems like the the CSS colors/highlighing are wrong in the Dark.css 
Maybe sth with the active/armed.
https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/gui/Dark.css

**Comment by vatsal-M** [comment] 2020-10-09 16:11
Our team @ISD14-LNMIIT wants to work on this issue. Please assign this issue to us!
@Siedlerchr @mlep

**Comment by vatsal-M** [comment] 2020-10-09 16:13
We are a team of college undergrads and we have to solve an issue on Github as our project. We are following the team software process and as such it will take about 2 weeks for us to resolve the issue but we will ensure high-quality work.

**Comment by vatsal-M** [comment] 2020-10-09 16:21
We (ISD14-LNMIIT) had been assigned a different issue on jabref but one of the team members got COVID-19 and we also had our mid-term exams because of which we didn't make a pull request and when we were about to make a pull request we saw that the issue has been closed. This is a very important project and we will ensure that this issue will be resolved as soon as possible. Please consider this team as it is very important for our grades. @Siedlerchr @mlep

**Comment by vatsal-M** [comment] 2020-10-14 15:43
@Siedlerchr Can you assign @ISD14-LNMIIT this issue as I'm a part of this team?

**Comment by Siedlerchr** [comment] 2020-10-15 16:15
I can only assign persons.

**Comment by vatsal-M** [comment] 2020-10-18 09:09
@Siedlerchr Is there any acceptance test for the issue? if there is then could you tell us about that as we will run it and provide a quality solution

**Comment by Siedlerchr** [comment] 2020-10-18 10:42
Just test it manually, create a PR, then we will review the code changes and merge if all is good.

As I outlined earlier, the issue is probably a CSS issue in the Dark.css. The dark theme can be enabled in the preferences of JabRef. 
The dark.css just overwrites some properties of the Base.css

**Comment by vatsal-M** [comment] 2020-10-18 11:05
@Siedlerchr ok thank you!

**Comment by Siedlerchr** [comment] 2020-11-24 21:31
For referenes:
The ToggleButton Style in the css applies to both the regex and the case sensitvy button, e.g. both are defined as ToggleButton
The properties of the toggle button:
https://openjfx.io/javadoc/14/javafx.graphics/javafx/scene/doc-files/cssref.html#togglebutton

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-11-24 23:29
I believe the classes are set to `icon-button` in https://github.com/JabRef/jabref/blob/350ec1f1ba4dc13c3e9f5a07f4fac801e85a93dc/src/main/java/org/jabref/gui/icon/IconTheme.java#L339-L344

**Comment by tobiasdiez** [comment] 2020-11-29 16:01
Thanks to @kingmanas and his team, this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed** 2020-11-29 16:01 UTC
Labels: search, type: bug 🐛, ui

**Comment by mlep** [comment] 2020-11-30 07:29
This is now working as expected. Thank you @kingmanas!
