### ISSUE TITLE
hangs if opening one of several files

### ISSUE THREAD

**Issue by JoKalliauer** [JabRef/jabref#5882] opened 2020-01-28 12:35 UTC
JabRef version JabRef 5.0-beta.382--2020-01-28--0b53d4b on Ubuntu 18.04

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Open [watson.bib.txt](https://github.com/JabRef/jabref/files/4122314/watson.bib.txt) in JabRef on Linux (can't reproduce on Windows)
2. click on the file-bottom of the entry
3. choose the second one
4. File opens (The file must exist, otherwise the problem does not occur)
5. Mouse moves, but clicking does not do anything and keyboard also does not interact, but computer sill runs e.g. Systemmonitor does still update graphics, but does not interact with input (all programms cummulated: 30% RAM-usage, ~5%CPU usage)
6. ssh to my PC, and kill JabRef
7. everything works again, JabRef gone. (25% RAM-usage, ~5%CPU usage)

**Comment by PorcelainMouse** [comment] 2020-02-05 20:56
Symptoms sound like #5919 , except I don't understand the connection with this specific file.

**Comment by JoKalliauer** [comment] 2020-02-07 15:17
> JabRef 5.0-beta.407--2020-02-06--9407bef
> Linux 4.15.0-87-generic amd64 
> Java 13.0.2

I just checked and "alt" "F4" works (pressing twize once for the LibreOffice/PDF-viewer and second for Jabref) and Print also works, but "Windows-Key"/"apple-Key"/"super-key" (don't know the name) did not work.

![Screenshot from 2020-02-07 16-09-45](https://user-images.githubusercontent.com/15687581/74040856-d853a700-49c4-11ea-8378-37fc6d091d68.png)

![Screenshot from 2020-02-07 16-09-49](https://user-images.githubusercontent.com/15687581/74040847-d558b680-49c4-11ea-8a1c-14e1b99edfdf.png)

The error exists also with sudo swapoff -a (at least with the older version JabRef 5.0-beta.382--2020-01-28--0b53d4b )

**Comment by AEgit** [comment] 2020-02-07 20:04
JabRef 5.0-beta.407--2020-02-06--9407bef
Linux 5.3.0-28-generic amd64 
Java 13.0.2

I can confirm this issue for Linux. As far as I can tell, the problem arises when someone tries to open a file. It does not matter, what type of file - I have tried to use a different PDF and even a .txt file instead and it would still crash the application (though with the .txt file it might be necessary to use the context menu for the file (Right click -> Open) to trigger the crash).

In two cases, an error log file was generated. I am not sure, whether this error log files relate to the actual issue or whether they just show, that I had to shut down the whole system to get it back working, but in case they are useful, here they are:


Error log file 1:

`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fedce027ff6, pid=6375, tid=6428
#
# JRE version: OpenJDK Runtime Environment 
(Zulu13.29+9-CA) (13.0.2+6) (build 13.0.2+6-MTS)
# Java VM: OpenJDK 64-Bit Server VM (13.0.2+6-MTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x42ff6]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Djava.library.path=/home/osboxes/Documents/Software/JabRef-5.0-portable_linux/JabRef/lib/app:/home/osboxes/Documents/Software/JabRef-5.0-portable_linux/JabRef/bin -Djava.launcher.path=/home/osboxes/Documents/Software/JabRef-5.0-portable_linux/JabRef/bin --module-path=/home/osboxes/Documents/Software/JabRef-5.0-portable_linux/JabRef/lib/app/mods -Djdk.module.main=org.jabref org.jabref/org.jabref.JabRefLauncher

Host: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 2 cores, 3G, Ubuntu 18.04.4 LTS
Time: Fri Feb  7 14:29:01 2020 EST elapsed time: 297 seconds (0d 0h 4m 57s)

---------------  T H R E A D  ---------------

Current thread (0x00007fed742c4000):  JavaThread "JavaFX Application Thread" [_thread_in_native, id=6428, stack(0x00007fed6c026000,0x00007fed6c127000)]

Stack: [0x00007fed6c026000,0x00007fed6c127000]`




Error log file 2:

`#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f014e0feff6, pid=2067, tid=2091
#
# JRE version: OpenJDK Runtime Environment 
(Zulu13.29+9-CA) (13.0.2+6) (build 13.0.2+6-MTS)
# Java VM: OpenJDK 64-Bit Server VM (13.0.2+6-MTS, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libc.so.6+0x42ff6]
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Djava.library.path=/home/osboxes/Documents/Software/JabRef-5.0-portable_linux/JabRef/lib/app:/home/osboxes/Documents/Software/JabRef-5.0-portable_linux/JabRef/bin -Djava.launcher.path=/home/osboxes/Documents/Software/JabRef-5.0-portable_linux/JabRef/bin --module-path=/home/osboxes/Documents/Software/JabRef-5.0-portable_linux/JabRef/lib/app/mods -Djdk.module.main=org.jabref org.jabref/org.jabref.JabRefLauncher

Host: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz, 2 cores, 3G, Ubuntu 18.04.4 LTS
Time: Fri Feb  7 14:34:11 2020 EST elapsed time: 105 seconds (0d 0h 1m 45s)

---------------  T H R E A D  ---------------

Current thread (0x00007f00ec2b8800):  JavaThread "JavaFX Application Thread" [_thread_in_native, id=2091, stack(0x00007f00d9330000,0x00007f00d9431000)]

Stack: [0x00007f00d9330000,0x00007f00d9431000],  sp=0x00007f00d942ef70,  free space=1019k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x42ff6]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.sun.glass.ui.gtk.GtkApplication._runLoop(Ljava/lang/Runnable;Z)V+0 org.jabref.merged.module
j  com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Ljava/lang/Runnable;Z)V+7 org.jabref.merged.module
j  com.sun.glass.ui.gtk.GtkApplication$$Lambda$99.run()V+12 org.jabref.merged.module
j  java.lang.Thread.run()V+11 java.base@13.0.2
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 128 (SI_KERNEL), si_addr: 0x0000000000000000

Register to memory mapping:

RAX=0x000fe029c99dc860 is an unknown value
RBX=0x0000000000000001 is an unknown value
RCX=0x0 is NULL
RDX=0x00007f014e4a7c9f: <offset 0x00000000003ebc9f> in /lib/x86_64-linux-gnu/libc.so.6 at 0x00007f014e0bc000
RSP=0x00007f00d942ef70 is pointing into the stack for thread: 0x00007f00ec2b8800
RBP=0x0000000000000001 is an unknown value
RSI=0x0000000000000001 is an unknown value
RDI=0x0000000000000007 is an unknown value
R8 =0x00007f014e4a98b0: <offset 0x00000000003ed8b0> in /lib/x86_64-linux-gnu/libc.so.6 at 0x00007f014e0bc000
R9 =0x00007f00d9430700 is pointing into the stack for thread: 0x00007f00ec2b8800
R10=0x000000000000005f is an unknown value
R11=0x0 is NULL
R12=0x00007f014e4a7718: <offset 0x00000000003eb718> in /lib/x86_64-linux-gnu/libc.so.6 at 0x00007f014e0bc000
R13=0x000000000000072f is an unknown value
R14=0x00007f014e4ac628: <offset 0x00000000003f0628> in /lib/x86_64-linux-gnu/libc.so.6 at 0x00007f014e0bc000
R15=0x00000000004e3480 points into unknown readable memory: 40 8c 4e 00 00 00 00 00


Registers:
RAX=0x000fe029c99dc860, RBX=0x0000000000000001, RCX=0x0000000000000000, RDX=0x00007f014e4a7c9f
RSP=0x00007f00d942ef70, RBP=0x0000000000000001, RSI=0x0000000000000001, RDI=0x0000000000000007
R8 =0x00007f014e4a98b0, R9 =0x00007f00d9430700, R10=0x000000000000005f, R11=0x0000000000000000
R12=0x00007f014e4a7718, R13=0x000000000000072f, R14=0x00007f014e4ac628, R15=0x00000000004e3480
RIP=0x00007f014e0feff6, EFLAGS=0x0000000000010206, CSGSFS=0x002b000000000033, ERR=0x0000000000000000
  TRAPNO=0x000000000000000d

Top of Stack: (sp=0x00007f00d942ef70)
0x00007f00d942ef70:   0000000000000000`

**Comment by Siedlerchr** [comment] 2020-02-20 07:33
I just merged a fix regarding opening files. Should be fixed now in master.
Please wait some time until the new master is uploaded.-

**Comment by AEgit** [comment] 2020-02-20 09:44
JabRef 5.0-beta.432--2020-02-19--c768697
Linux 5.3.0-40-generic amd64 
Java 13.0.2

Cannot confirm for the current master version. If I right-click on a file, the context menu will open. If I then press "Open" to open the file, the application that opens the file while hang and has to be forcefully shut down.
Note, that this issue does not appear any more if the file is opened with a simple left-click. As far as I can tell, this problem only arises now, if right-click and the associated context menu are used, to open a file.

**Comment by Siedlerchr** [comment] 2020-02-20 11:58
Okay, thanks for the update. Will look into it. Might be that the context Menu calls another method which I oversaw.

**Comment by JoKalliauer** [comment] 2020-02-20 12:36
> JabRef 5.0-beta.436--2020-02-20--505fc74
> Linux 4.15.0-89-generic amd64 
> Java 13.0.2

On my PC the [example above](https://github.com/JabRef/jabref/issues/5882#issue-556180225) seems to be solved/fixed. @Siedlerchr : Thanks

I consider the issues as solved (on my Ubuntu) and could be closed.

**Comment by ilippert** [comment] 2020-07-21 12:05
JabRef 5.1--2020-07-20--9cd9390
Linux 5.7.8-200.fc32.x86_64 amd64 
Java 14.0.2

open file (F4) works for me on Fedora Linux.

In my reading, this issue can be closed.

**Closed** 2020-07-21 12:59 UTC
Labels: external files, os: linux, ui

**Comment by AEgit** [comment] 2020-07-22 09:28
JabRef 5.1--2020-07-20--9cd9390
Linux 5.4.0-42-generic amd64 
Java 14.0.2

Hmmm, it does not crash for me anymore, but there are other issues:

1) Every time I try to open a PDF, a new window "Open with" opens, which asks me which application should be used to open the PDF. Given that the default PDF reader should be set in Ubuntu (if I doubleclick a PDF in the file manager, it will automatically open, without asking me which application to use), this appears to be an undesired behaviour. Could it be linked to some sort of interaction between Snap and then Gnome Filemanager?

2) <kbd>F4</kbd> does not work for me, i. e. no file is being opened if I press <kbd>F4</kbd>. A leftclick, however, allows me to open a PDF (well, if first shows the windows mentioned in 1) and after I select the application it opens the PDF).
