### ISSUE TITLE
Jabref hangs after pasting bibtex code into source field

### ISSUE THREAD

**Issue by mutlusun** [JabRef/jabref#3261] opened 2017-10-05 11:05 UTC
JabRef version 4.0 on Ubuntu 16.04

Steps to reproduce:

1. Create a new entry (article)
2. Go to source field
3. Replace existing biblatex code through (copy/paste)
```tex
@article{Cao:2017:DSC:3101309.3076253,
 author = {Cao, Longbing},
 title = {Data Science: A Comprehensive Overview},
 journal = {ACM Comput. Surv.},
 issue_date = {August 2017},
 volume = {50},
 number = {3},
 month = jun,
 year = {2017},
 issn = {0360-0300},
 pages = {43:1--43:42},
 articleno = {43},
 numpages = {42},
 url = {http://doi.acm.org/10.1145/3076253},
 doi = {10.1145/3076253},
 acmid = {3076253},
 publisher = {ACM},
 address = {New York, NY, USA},
 keywords = {Big data, advanced analytics, big data analytics, computing, data DNA, data analysis, data analytics, data economy, data education, data engineering, data industry, data innovation, data profession, data science, data scientist, data service, informatics, statistics},
} 
```
4. Click somewhere outside of the source field
5. Jabref hangs

<details>

  <summary>Log File</summary>

No console output appears but these errors appeared after opening an entry (didn't produce any runtime problems):
```
PM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 8.0.112 by JavaFX runtime of version 8.0.60
```

</details>

**Comment by lenhard** [comment] 2017-10-05 13:38
Thanks for your report! Chances are that this is somehow due to the environment, i.e. the Java and JavaFX versions.

Might be similar to #2963

**Comment by lenhard** [comment] 2017-10-05 13:40
And I just saw that this is actually a duplicate of  #3234, although with Ubuntu instead of Mint. There's no point in two issues here, so I am closing this one in favor of the other.

**Closed by lenhard** 2017-10-05 13:40 UTC
Labels: linux
