### ISSUE TITLE
Test case testAuthorWithDiacritics fails on Mac

### ISSUE THREAD

**Issue by stevensdavid** [JabRef/jabref#6024] opened 2020-02-26 14:20 UTC
Version: JabRef development head (`JabRef/jabref:master` at 74667e9) on Mac OS X 10.15.3 and Mac OS 10.14.5 on 

The unit test case `testAuthorWithDiacritics` fails when executed on Mac devices, while it passes on tested Linux and Windows devices. This has been tested with AdoptOpenJDK 13.0.2.j9 and Oracle's SE JDK 13.0.2.

1. Build and run tests on MacOS using `./gradlew test`

Gradle log:

```gradle
Test testAuthorWithDiacritics() FAILED
  org.opentest4j.AssertionFailedError: expected: java.util.Collections$SingletonList@f4ce1d7<[src/test/resources/org/jabref/logic/importer/unlinkedFilesTestFolder/directory/subdirectory/2017_Gražulis_726.pdf]> but was: java.util.ArrayList@ebad2510<[src/test/resources/org/jabref/logic/importer/unlinkedFilesTestFolder/directory/subdirectory/2017_Gražulis_726.pdf]>
      at org.jabref/org.jabref.logic.util.io.RegExpBasedFileFinderTests.testAuthorWithDiacritics(RegExpBasedFileFinderTests.java:101)
```

**Comment by Siedlerchr** [comment] 2020-02-28 15:46
Hm. Windows running form Eclipse can't reproduce this and CI server runs on linux. 
And it's odd that it only complains the types are not equal, e.g. ArrayList vs CollectionsList. The path is otherwise equal, e.g. the diacritics, so the core functionality is working.
Therefore I will close this issue, so we can focus on other important things.

**Closed by Siedlerchr** 2020-02-28 15:46 UTC
Labels: macOS
