### ISSUE TITLE
"open folder" opens file instead of folder

### ISSUE THREAD

**Issue by evanhorn** [JabRef/jabref#9607] opened 2023-02-08 17:52 UTC
### JabRef version

5.9 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Ubuntu 20.04 with GNOME Shell 3.36.9

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select an entry associated with a file
2. Right click on entry and select `Open folder` from context menu (or ctrl-shift-O)

Instead of a file browser, the attached file is opened as though `Open file` was selected.

Note that this behavior also occurs when using the "File" field in the "General" tab.  

### Appendix

Originally observed with:
> JabRef 5.9--2023-01-08--76253f1a7
> Linux 5.15.0-58-generic amd64 
> Java 19.0.1 
> JavaFX 19+11
> 

Confirmed with development branch:
> JabRef 5.10--2023-02-07--ae84b22
> Linux 5.15.0-58-generic amd64 
> Java 19.0.2 
> JavaFX 19+11

**Comment by ThiloteE** [comment] 2023-02-08 21:14
Cannot reproduce on

1. Windows 10.

2. JabRef 5.9--2023-01-08--76253f1a7
Linux Mint 5.4.0-137-generic amd64
Java 19.0.1
JavaFX 19+11

      Linux Mint is based on Ubuntu, but the Userinterface is made to look like old Gnome 2. Linux Mint 5.4 is based on Ubuntu 2.04 i believe.
      
      I suspect what you experience may be caused by either you having misclicked on "Open file", which is right beneath or it is something peculiar to Ubuntu's file manager "Nautilus". Last year, there was a rework, which fixed "Open Folder". This fix was tested on a then very up to date Fedora system running Nautilus. Since - to my knowledge - Ubuntu 20.04 also uses Nautilus as its filemanager, but is a little older, it could be that only newer versions of Nautilus may be compatible with this "new" fix.

I would like to ask you to test JabRef with Ubuntu 22.04 or even better 22.10 and report back.

**Comment by waterflow80** [comment] 2023-02-08 22:45
@evanhorn @ThiloteE I tried it on my Ubuntu machine and the same happened for me. The `open folder` option opens the file 
attached with the entry, and not a file browser. 
If there are multiple files attached, it opens the first file that has been attached to the entry.

I will try to find out why did this happen and I'll try to fix it.

**Comment by evanhorn** [comment] 2023-02-09 00:43
This isn't a big deal, just a minor annoyance, as I don't often need to access the file's folder. However, I didn't see that anyone else had identified this issue (I did see the conversation from last year), so I wanted to pass it along.

I am glad to see that someone else is experiencing the issue, so it's not just me! It does seem to be related to Ubuntu 20.04 in some way, which surprises me, as ctrl-o opens the “Open library” dialog in Nautilus, so it _seems_ to be working OK.

If there is any more information that I can provide, please let me know.

**Comment by ilippert** [comment] 2023-02-12 20:15
Am on Fedora37

with

JabRef 5.10-PullRequest9604.122--2023-02-07--1452eb6
Linux 6.1.9-200.fc37.x86_64 amd64 
Java 19.0.2 
JavaFX 19+11

cannot confirm.

**Comment by ThiloteE** [comment] 2023-02-18 13:31
Note to myself: Linux Mint 21.10 uses Nemo as its file manager.

**Comment by DanielBiskup** [comment] 2023-05-08 14:15
Same here on Ubuntu 23.04

JabRef 5.9--2023-01-08--76253f1a7
Linux 6.2.0-20-generic amd64 
Java 19.0.1 
JavaFX 19+11

**Comment by Siedlerchr** [comment] 2023-05-08 18:21
@DanielBiskup  Can you try the latest version?
https://builds.jabref.org/main/

**Comment by evanhorn** [comment] 2023-05-09 01:45
I tried the latest version and still experience the same issue, but I have upgraded to Ubuntu 22.04.

JabRef 5.10--2023-05-08--68b72e0
Linux 6.2.0-76060200-generic amd64 
Java 20.0.1 
JavaFX 20+19

**Comment by kbauer** [comment] 2023-05-30 12:21
1. System information
2. Workaround
3. Observations

### 1. System information

Just ran into the same issue with 

    JabRef 5.10--2023-05-20--8d1bb00
    Linux 5.3.18-150300.59.106-default amd64
    Java 20.0.1 
    JavaFX 20+19

The System is an Open Suse 15.3 desktop, using the XFCE desktop environment.


### 2. Workaround

I was able to solve it for my system by configuring *File > Preferences > External Programs > Use custom file browser* to the value

    /usr/bin/dolphin %DIR

![image](https://github.com/JabRef/jabref/assets/7498468/289689a9-05ff-44ee-b790-bd56c0d0f39e)


### 3. Observations

Additionally I observed, that when opening a PDF file or opening a folder with the custom file browser, a corresponding event will be logged when executing with

    JabRef --debug --console

but when "Use custom file browser" is disabled, nothing will be logged, and the PDF file will open.

Possibly related: On my system, the "open terminal here" wasn't working.

![image](https://github.com/JabRef/jabref/assets/7498468/fe402b1a-fcf0-46df-9326-ee665871ced0)

That part I solved by setting "use custom terminal emulator" to `xfce4-terminal --working-directory=%DIR`. But it might hint at an underlying problem detecting the correct programs. Sadly, when using the default program, the command is not logged, making it harder to recognize the root of the issue.

**Comment by Siedlerchr** [comment] 2023-05-30 13:51
The terminal issue will hopefully be fixed by  #9954

**Comment by Siedlerchr** [comment] 2023-05-30 21:13
@kbauer What does the environment variable DESKTOP_SESSION print?
JabRef checks for some standard file managers and falls back to xdg open
https://github.com/JabRef/jabref/blob/2a11af042191d774cf7c68e84a2a372251721de9/src/main/java/org/jabref/gui/desktop/os/Linux.java#L99-L115 

I think the problem is that we give the path to the file and not the folder when we use xdg open as fallback!

**Comment by Siedlerchr** [comment] 2023-06-01 21:16
@DanielBiskup  can you please if this version opens the folder correctly? https://builds.jabref.org/pull/9966/merge/ 
and if it selects the file (if that is possible with thunar)?

**Closed** 2023-06-04 16:02 UTC
Labels: os: linux
