### ISSUE TITLE
Failing Look Up Full Text Document on Wiley Online Library

### ISSUE THREAD

**Issue by lecc0r** [JabRef/jabref#1543] opened 2016-07-04 12:56 UTC
JabRef version 3.4 on Windows 8

Hi there, I guess it is known that the "Look Up Full Text Document" function is not able to download PDFs from Wiley Online Library; however, I would like to place some emphasis on it.

Steps to reproduce:

Example publication: http://onlinelibrary.wiley.com/doi/10.1002/kin.550241008/abstract
I do have the required permissions to access and download the publication.

1. Select a citation entry from publisher Wiley
2. Click on "Look Up Full Text Document"
3. Getting told that that "Full text document download failed"

Best Regards
Simon

**Comment by Siedlerchr** [comment] 2016-07-04 13:12
Hi,
Beside the Error message, could you please check, if there are some more details in the Log?

At the moment JabRef only tries to fetch the fulltext from the the following sources, in this order:
1. DOI-Resolution
2. ScienceDirect
3. SpringerLink
4. ACS
5. Arxiv
6. IEEE
7. Google Scholar

As a workaround you can manually enter the url to the pdf file: General->File->Download from URL.

**Comment by stefan-kolb** [comment] 2016-10-19 15:05
We don't support fetching full-text from Wiley right now. Is caused by the way they serve their PDFs. It is hard to scrape the right PDF URL. Closing this for now.

**Closed by stefan-kolb** 2016-10-19 15:05 UTC
Labels: enhancement, fetcher
