### ISSUE TITLE
Texts in preferences are blurry since JabRef 5

### ISSUE THREAD

**Issue by systemoperator** [JabRef/jabref#6317] opened 2020-04-20 08:48 UTC
Ever since JabRef 5, the texts in the preferences are blurry. This is at least the case when running JabRef 5 under Ubuntu 16.04, where I have tested it. Affected is the right side of the preferences with the white background. Only input fields are excluded from it, as it can be seen in the following screenshot, which shows the difference quite well:

![image](https://user-images.githubusercontent.com/3658393/79732143-92378f80-82f3-11ea-8440-23593525a666.png)

**Comment by mrjoposranchik** [comment] 2020-04-24 17:58
Same thing on Windows 10 machine, however, input fields also look blurry in my case
![image](https://user-images.githubusercontent.com/18900780/80242657-f943a400-8665-11ea-8bb3-1d6bc1a05965.png)
![image](https://user-images.githubusercontent.com/18900780/80242542-cb5e5f80-8665-11ea-8bcf-b49fea6a2162.png)

**Comment by Siedlerchr** [comment] 2020-05-03 14:30
Does this only apply to the preferences or to other dialogs as well?
You could try to adapt the shdpi scaling https://github.com/JabRef/jabref/issues/6086#issuecomment-596536235

**Comment by systemoperator** [comment] 2020-05-03 17:16
In my case, only the preferences' dialog is affected, everything else is fine.

**Comment by Siedlerchr** [comment] 2020-05-03 17:30
Okay, thanks for the additional details. Could be some weird issue with the screen scaling somehow.
My Windows 10: 
2560x1440 scaling 100%, 27" monitor
![grafik](https://user-images.githubusercontent.com/320228/80921085-43b6d600-8d74-11ea-9dd3-112e0515ed11.png)

![grafik](https://user-images.githubusercontent.com/320228/80921089-50d3c500-8d74-11ea-93c6-33bd90cccea3.png)

**Comment by systemoperator** [comment] 2020-05-03 17:36
My screenshot was created with a resolution of 1920x1080, 15.4" monitor.

**Comment by systemoperator** [comment] 2020-05-03 17:43
Interesting observation: When setting a different (e.g. a bigger) font size in the configurations' dialog and restarting JabRef, the font size in other dialogs changes accordingly but the font size in the preferences does not.

**Comment by mrjoposranchik** [comment] 2020-05-03 21:05
> Okay, thanks for the additional details. Could be some weird issue with the screen scaling somehow.

Seems true, normally I use 125% screen scaling, tried to change it now and with 100% I did not notice any visible blurryness.

**Comment by systemoperator** [comment] 2020-05-03 21:15
@mrjoposranchik So you have set the screen scaling to 125% in the display settings of your operating system? I have the native setting, without any scaling.

**Comment by mrjoposranchik** [comment] 2020-05-04 09:26
> @mrjoposranchik So you have set the screen scaling to 125% in the display settings of your operating system? I have the native setting, without any scaling. What if you increase the font size in JabRef's preferences? Does the font size in the preferences increase?

1. Yes, and 125% is the recommended setting for my laptop screen (otherwise everything becomes super small and I have to squint :) ). I suppose it is increased by default for not very large in physical dimensions, but high-resolution screens.
2. Tried to set font size 12 and 15 (default is probably 9) - font size in the preferences doesn't change (in the main window everything gets expectedly bigger, text and icons)

**Comment by Siedlerchr** [comment] 2020-08-31 20:13
Is this still an issue in the current release version 5.1?

**Comment by Siedlerchr** [comment] 2020-08-31 22:03
@calixtus  Maybe you have an idea?

**Comment by mr-j-s** [comment] 2020-09-01 08:39
> Is this still an issue in the current release version 5.1?

For me seems to be still a bit blurry (checked in v. 5.2)

![image](https://user-images.githubusercontent.com/18900780/91827420-1ead7380-ec3f-11ea-950f-317eac4b50f4.png)

**Comment by calixtus** [comment] 2020-09-01 12:19
Tested it with my linux machine at 100% screen scaling and it's crisp like a fresh cookie.
It's probably a bug about screen scaling and JavaFX.
Although this is a bit annoying, but no critical bug and doesn't make JabRef unusable, I'll put this in line for future fixing efforts, as soon as the high-priority bugs are fixed. Please understand that our resources are limited, since we are working on JabRef in our free time.

**Closed** 2020-09-01 12:59 UTC
Labels: preferences, type: bug 🐛, ui

**Comment by systemoperator** [comment] 2020-09-01 13:40
For your information: In my case, it's still blurry with the current master build in the very same situations as described above.

**Comment by calixtus** [comment] 2020-09-01 15:49
Thanks, yes, I took a quick look at stackoverflow: https://stackoverflow.com/questions/23728517/blurred-text-in-javafx-textarea
Maybe it's related to scrollpanes and screen scaling.
If you like, you are always free to take a shot on fixing it, but it's hard for us to work on this issue, since we were not able to reproduce this issue on our machines.
