### ISSUE TITLE
Do not ignore exception

### ISSUE THREAD

**Issue by Ali96kz** [JabRef/jabref#7522] opened 2021-03-13 09:38 UTC
There is ignored exception that needs review. Properly handle exception, at least show information in log
<img width="707" alt="exception" src="https://user-images.githubusercontent.com/15236829/111025893-350b6780-83f8-11eb-97cd-ae6599ed56ed.png">
Note: I opened JabRef with YourKit analyzer 
<img width="1432" alt="yourkit-exceptions" src="https://user-images.githubusercontent.com/15236829/111025973-cf6bab00-83f8-11eb-8dd3-46ce83f72fb6.png">

NoSuchMethodException mostly thrown when I try to save `Library properties`

**Comment by VernonKwa** [comment] 2022-10-06 00:34
Hi there, me and my group member are students and we would like to try and tackle this issue. Is there anyone working on this now? If not, would it be possible to assign this issue to us. Thank you.

**Comment by ThiloteE** [comment] 2022-10-09 13:26
@VernonKwa Hey, you are welcome. If you really want to work on this, I think you can (although I personally don't really understand what it is about (sorry, no Programmer here) :sweat_smile: ).

Be aware, this issue is not marked as good first issue. If you are new to JabRef and students, the easiest and most recommended issues to choose from are issues with the label "[good first issue](https://github.com/JabRef/jabref/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)" or alternatively, to choose from the "[candidates for university students](https://github.com/orgs/JabRef/projects/3)" projects page

I have multiple questions:

1. this seems to be an older issue, so maybe the newest Development version of JabRef behaves differently. @Ali96kz is this still relevant? What version of JabRef did you use back then?
2. @Ali96kz could you please provide a little bit more context? In particular: How can people easily reproduce and trigger the (ignored) exception? Could you provide an example of an file, entry or action that will trigger it?

**Comment by ThiloteE** [comment] 2022-10-09 13:27
@VernonKwa As a general advice: Check out https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md for a start. Also, https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace is worth having a look at. Feel free to ask if you have any questions here on GitHub or also at JabRef's [Gitter](https://gitter.im/JabRef/jabref) chat.

Try to open a (draft) pull request early on, so that people can see you are working on the issue and so that they can see the direction the pull request is heading towards. This way, you will likely receive valuable feedback.

**Comment by VernonKwa** [comment] 2022-10-26 08:06
Hi there, we've created a draft Pull request: #9302. Can we get some feedback for it. Thank you

**Closed** 2022-12-19 20:18 UTC
