### ISSUE TITLE
Entry editor becomes unusable, no longer displays any fields

### ISSUE THREAD

**Issue by fkoglin** [JabRef/jabref#3843] opened 2018-03-13 16:34 UTC
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef 4.2-dev--snapshot--2018-03-13--master--90c7afa1c
Windows 10 10.0 amd64 
Java 1.8.0_161

**Description:**
The entry editor breaks, displaying graphical errors and no longer displaying any fields for any entry. Closing and re-opening the library fixes the problem, until steps are repeated.

**Steps to reproduce:**
1. Open entry editor for an entry.
2. Switch to the "General" panel
3. Switch to the "BibTeX source" panel
4. Close entry editor
5. Open the entry editor for an entry again.
6. Switch to any other panel.

Order of panel selection doesn't matter, i.e. first switching to the source and then to the general panel also creates the error. As does closing the entry editor between steps 2 & 3.

![image](https://user-images.githubusercontent.com/4972547/37354987-2b871238-26e3-11e8-9306-d7966ee3500a.png)

<details>
  <summary>Log File</summary>
  
  ```
  Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Unknown Source)
	at java.awt.Component.getLocationOnScreen(Unknown Source)
	at sun.awt.windows.WInputMethod$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: [-2147483648, 9) is not a valid range within [0, 9)
	at org.reactfx.util.Lists.checkRange(Lists.java:128)
	at org.reactfx.util.Lists.checkRange(Lists.java:123)
	at org.reactfx.collection.MemoizationListImpl.forget(MemoizationList.java:184)
	at org.fxmisc.flowless.CellListManager.cropTo(CellListManager.java:82)
	at org.fxmisc.flowless.CellPositioner.cropTo(CellPositioner.java:29)
	at org.fxmisc.flowless.Navigator.cropToNeighborhoodOf(Navigator.java:227)
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:200)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:129)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:864)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:940)
	at javafx.stage.Window.show(Window.java:955)
	at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58)
	at javafx.embed.swing.JFXPanel.lambda$addNotify$51(JFXPanel.java:833)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

  ```
</details>

**Comment by Siedlerchr** [comment] 2018-03-13 16:52
Duplicate of #3810. Works in the new maintabe  beta. But the beta is currently broken.

**Comment by stefan-kolb** [comment] 2018-03-14 15:25
This also happens for me when I switch the type of the entry.

**Comment by tobiasdiez** [comment] 2018-03-14 16:48
I was never able to locate the root of these issues (they result from some weird thread interaction, which happens before the GUI problems and thus are a bit hard to locate). They just disappeared in the maintable beta branch. I think we are not so far away from an early beta release and would hence vote for closing this issue.

**Comment by johann-petrak** [comment] 2018-03-17 13:27
This makes both 4.1 and and the 4.2 development versions completely unusable for me, it happens after the first or at the latest second entry I add. 
Is it necessary to go back to version 4.0?

**Comment by lenhard** [comment] 2018-03-28 14:04
I just tested this again on current master since  #3872 has been merged. It seems that the changes to the source tab have solved this error, the entry editor no longer breaks down. Hence, I am closing this issue.

**Closed by lenhard** 2018-03-28 14:04 UTC
Labels: bug
