### ISSUE TITLE
5.0 dev: CSL citation styles no longer working

### ISSUE THREAD

**Issue by matthiasgeiger** [JabRef/jabref#5386] opened 2019-10-04 11:32 UTC
JabRef version 5.0 dev (master) on Windows 10

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

Whether running from gradle, or using the builds from builds.jabref.org: the CSL styles are currently not loaded properly. 

Not sure whether this is a side effect of the new build pipeline, or whether it was already a problem before...

**Comment by tobiasdiez** [comment] 2019-10-04 11:50
Duplicate of https://github.com/JabRef/jabref/issues/5246

**Closed by tobiasdiez** 2019-10-04 11:50 UTC
Labels: bug, entry-preview

**Comment by matthiasgeiger** [comment] 2019-10-04 11:51
Ahh... Sorry! Missed that one.
