### ISSUE TITLE
typing in quick search with editor open will overwrite crossrefs

### ISSUE THREAD

**Issue by kku** [JabRef/jabref#2183] opened 2016-10-20 09:58 UTC
When I have the editor panel open, typing a search string into the quick search field will usually but not each time result in undesired changes to the entry in the editor, usually in the crossref-field, because 
After a few characters, the cursor will jump to the Crossref field in the editor all by itself - no mouse or touchpad interaction required. - and append any typed-in text to the existing entry
Pressing Ctrl-Z a couple of times will NOT undo the changes to the existing crossref completely; in particular, it will leave the "dirty flag" indicating a saveable change to the file unchanged.

JabRef version3.6  on Windows 7, Fedora 24

Steps to reproduce:
1. Open editor on some entry by clicking and typing Ctrl-E
2. Click into quick search field
3. Start typing

![jabref-search-error](https://cloud.githubusercontent.com/assets/381893/19555033/6fcde66a-96bb-11e6-9ad0-5d888e5af703.png)

**Comment by matthiasgeiger** [comment] 2016-10-20 10:02
Thank you for reporting this issue. 

This seems to be a duplicate of the issue #1938 

We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master.

**Closed** 2016-11-03 10:00 UTC
Labels: duplicate, fixed-in-devBuilds
