### ISSUE TITLE
record being wrongly deleted

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#2907] opened 2017-06-13 03:19 UTC
JabRef version 

JabRef 4.0.0-dev--snapshot--2017-06-11--master--c711a7fdf
Linux 4.10.0-22-generic amd64 
Java 1.8.0_131

Steps to reproduce:

1. open edit screen.  
2. edit  "biblatex source"
3. using ctrl-x to try to delete a string causes the whole record to be deleted!

**Comment by tobiasdiez** [comment] 2017-06-13 07:02
Duplicate of https://github.com/JabRef/jabref/issues/2855

**Closed by tobiasdiez** 2017-06-13 07:02 UTC

**Comment by wujastyk** [comment] 2017-06-13 14:25
quite right.  My apologies.  (I had an idea it had already been squashed, so I was re-reporting.)
