### ISSUE TITLE
Repeated cleaning of % sign in abstract field results in \\% which gives a LaTeX error

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2451] opened 2017-01-09 08:47 UTC
JabRef 3.8.1
windows 7 6.1 amd64 
Java 1.8.0_66

I noticed after an errorneous biber compilation that cleaning the % sign is not without risk: I found in the bib-file doublebackslashed % (`\\%`) which do help since they have the meaning of a new line and and a % sign. Obviously the cleaning does not discriminate between `\%` and `%`.

Steps to reproduce:

1. a bibentry with a % sign in the abstract like PMID 27151464
2. run Quality > Cleanup Entries ( with abstract: Latex cleanup added) twice

I may be wrong since a cannot reproduce this, but I know for sure that yesterday I found the backslash doubled and I did not anything but the cleanup.

BTW I noted also that between the % sign and the following dot a misplaced white space was added.

Perhaps someone can reproduce this issue.

**Comment by matthiasgeiger** [comment] 2017-01-09 09:09
Hi Bernhard!
Sorry, that I have not seen your post in the forum earlier - I think this problem has already been fixed in https://github.com/JabRef/jabref/pull/2445 (which is a fix for a similar reported problem https://github.com/JabRef/jabref/issues/2426) - can you please check using a development build from https://builds.jabref.org/master

Thanks!

**Comment by bernhard-kleine** [comment] 2017-01-09 10:02
Actually I can not repeat it, therefore I don't know what to do. Even the cleaning of a % sign does not work. I am stymied.

**Comment by Siedlerchr** [comment] 2017-01-20 16:10
Hi, I tested this and encountered the following behaviour (only in biblatex mode)
First Cleanup run: The % sign is correctly encoded into `&percnt; `
Second run:, I get:  `\&percnt;` with a preceding slash.
Third run, I get: `50\\&percnt;`
So each time, there is added a backslash. 

When I open the bibtex file, I see:
`50\\\\%` @lenhard

**Comment by bernhard-kleine** [comment] 2017-01-30 14:17
With 3.8.2. on a fresh database I loaded PMID 27151464 via the Medline fetcher, started Cleanup and got the status: doing cleanup for on entry, but it never finished and the % sign in the abstract was not escaped.

**Comment by Siedlerchr** [comment] 2017-02-04 18:32
I recently experienced the same with the ProtectTerms formatter. 
When you run it first, it protects the terms correctly. If you run it again, the already protected terms are protected again, by adding more braces around them...

**Comment by Siedlerchr** [comment] 2017-02-05 12:21
@bernhard-kleine  I found the problem, it was a problematic RegEx and fixed it. 
In a couple of minutes you can try the version here http://builds.jabref.org/multicleanup/

**Comment by bernhard-kleine** [comment] 2017-02-05 15:48
I have installed the file but it has errors: Cleanup does not finish, "save as" not work, I cannot confirm that the problem has been dealt with. Sorry.
(the testing was done on a fresh database with importing  the entry PMID 27151464, with contains in the abstract a 50% to be cleaned.)

**Comment by Siedlerchr** [comment] 2017-02-05 16:45
Ah I see the problem. Will fix that.

**Comment by Siedlerchr** [comment] 2017-02-05 17:56
@bernhard-kleine  Should be fixed now. You can try again to download the version from there

**Comment by bernhard-kleine** [comment] 2017-02-05 22:07
the cleanup worked thank you, but, still, no way to _save_ the bib-file in the entry, no _save as_

**Comment by Siedlerchr** [comment] 2017-02-05 22:24
Could you please open a new issue for the saving problem and give some more
details?

Do you get any errors in the log?

Am 05.02.2017 11:07 nachm. schrieb "Bernhard Kleine" <
notifications@github.com>:

**Comment by lenhard** [comment] 2017-02-10 09:17
Since the original problem described here seems to be fixed (and the fix is confirmed), I will close this issue now.

For new problems in the UI, please open a new issue, thanks!

**Closed by lenhard** 2017-02-10 09:17 UTC
Labels: biblatex, bug, waiting-for-feedback
