### ISSUE TITLE
Uncaught exception when adding optional bibtex fields

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#3431] opened 2017-11-13 14:53 UTC
jabref 4.1dev 2017-11-13. There is an exception thrown when doing the below although things
seem to work but I may be wrong:

1. BibTeX-->Customize entry types
2. In the Optional Fields choose a new entry to add and click apply
3. The exception message below appears

===============================================================
```
08:37:51.424 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
        at com.sun.javafx.text.PrismTextLayout.getRuns(PrismTextLayout.java:236) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.getRuns(Text.java:317) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.updatePGText(Text.java:1465) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.impl_updatePeer(Text.java:1500) ~[jfxrt.jar:?]
        at javafx.scene.Node.impl_syncPeer(Node.java:503) ~[jfxrt.jar:?]
        at javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2290) ~[jfxrt.jar:?]
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2419) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162-ea]
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162-ea]
```

**Comment by Siedlerchr** [comment] 2017-11-13 20:04
Hm, that is interesting.
Under Windows 10 I can not reproduce this

**Comment by derTimme** [comment] 2017-11-14 20:05
Tried to reproduce with JabRef 4.0 on Linux, but without success (i.e. no exception is thrown).

**Comment by sambo57u** [comment] 2017-11-15 03:23
Well, I tried again and can reproduce it  with the 4.1dev version (tried it multiple times):

21:16:55.057 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException: null
        at com.sun.javafx.text.PrismTextLayout.shape(PrismTextLayout.java:796) ~[jfxrt.jar:?]
        at com.sun.javafx.text.PrismTextLayout.layout(PrismTextLayout.java:1064) ~[jfxrt.jar:?]
        at com.sun.javafx.text.PrismTextLayout.ensureLayout(PrismTextLayout.java:223) ~[jfxrt.jar:?]
        at com.sun.javafx.text.PrismTextLayout.getBounds(PrismTextLayout.java:246) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.getLogicalBounds(Text.java:358) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.getYRendering(Text.java:1069) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.access$4400(Text.java:95) ~[jfxrt.jar:?]
        at javafx.scene.text.Text$TextAttribute$11.computeValue(Text.java:1785) ~[jfxrt.jar:?]
        at javafx.scene.text.Text$TextAttribute$11.computeValue(Text.java:1777) ~[jfxrt.jar:?]
        at javafx.beans.binding.ObjectBinding.get(ObjectBinding.java:153) ~[jfxrt.jar:?]
        at javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:50) ~[jfxrt.jar:?]
        at javafx.beans.property.ObjectPropertyBase.get(ObjectPropertyBase.java:132) ~[jfxrt.jar:?]
        at com.sun.javafx.scene.control.skin.TextFieldSkin.lambda$new$198(TextFieldSkin.java:233) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
        at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105) ~[jfxrt.jar:?]
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112) ~[jfxrt.jar:?]
        at javafx.beans.property.ObjectPropertyBase.access$000(ObjectPropertyBase.java:51) ~[jfxrt.jar:?]
        at javafx.beans.property.ObjectPropertyBase$Listener.invalidated(ObjectPropertyBase.java:233) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
        at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:172) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.impl_geomChanged(Text.java:769) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.needsTextLayout(Text.java:194) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.needsFullTextLayout(Text.java:189) ~[jfxrt.jar:?]
        at javafx.scene.text.Text.access$200(Text.java:95) ~[jfxrt.jar:?]
        at javafx.scene.text.Text$2.invalidated(Text.java:389) ~[jfxrt.jar:?]
        at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109) ~[jfxrt.jar:?]
        at javafx.beans.property.StringPropertyBase.access$000(StringPropertyBase.java:49) ~[jfxrt.jar:?]
        at javafx.beans.property.StringPropertyBase$Listener.invalidated(StringPropertyBase.java:230) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:137) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
        at javafx.beans.binding.StringBinding.invalidate(StringBinding.java:171) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:51) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:349) ~[jfxrt.jar:?]
        at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81) ~[jfxrt.jar:?]
        at javafx.scene.control.TextInputControl$TextProperty.fireValueChangedEvent(TextInputControl.java:1389) ~[jfxrt.jar:?]
        at javafx.scene.control.TextInputControl$TextProperty.markInvalid(TextInputControl.java:1393) ~[jfxrt.jar:?]
        at javafx.scene.control.TextInputControl$TextProperty.set(TextInputControl.java:1324) ~[jfxrt.jar:?]
        at javafx.scene.control.TextInputControl.setText(TextInputControl.java:349) ~[jfxrt.jar:?]
        at org.jabref.gui.search.GlobalSearchBar.clearSearch(GlobalSearchBar.java:309) ~[jabref:?]
        at org.jabref.gui.search.GlobalSearchBar.performSearch(GlobalSearchBar.java:337) ~[jabref:?]
        at org.jabref.gui.BasePanel$SearchListener.listen(BasePanel.java:2093) ~[jabref:?]
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[jabref:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[jabref:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[jabref:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[jabref:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[jabref:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[jabref:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[jabref:?]
        at org.jabref.model.database.BibDatabase.relayEntryChangeEvent(BibDatabase.java:582) ~[jabref:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_152]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[jabref:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[jabref:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[jabref:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[jabref:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[jabref:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[jabref:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[jabref:?]
        at org.jabref.model.entry.BibEntry.setType(BibEntry.java:247) ~[jabref:?]
        at org.jabref.model.entry.BibEntry.setType(BibEntry.java:227) ~[jabref:?]
        at org.jabref.model.entry.BibEntry.setType(BibEntry.java:220) ~[jabref:?]
        at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_152]
        at org.jabref.gui.customentrytypes.EntryCustomizationDialog.lambda$updateEntriesForChangedTypes$5(EntryCustomizationDialog.java:356) ~[jabref:?]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_152]
        at org.jabref.gui.customentrytypes.EntryCustomizationDialog.updateEntriesForChangedTypes(EntryCustomizationDialog.java:356) ~[jabref:?]
        at org.jabref.gui.customentrytypes.EntryCustomizationDialog.applyChanges(EntryCustomizationDialog.java:301) ~[jabref:?]
        at org.jabref.gui.customentrytypes.EntryCustomizationDialog.lambda$initGui$2(EntryCustomizationDialog.java:141) ~[jabref:?]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[?:1.8.0_152]
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[?:1.8.0_152]
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[?:1.8.0_152]
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[?:1.8.0_152]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[?:1.8.0_152]
        at java.awt.Component.processMouseEvent(Component.java:6533) ~[?:1.8.0_152]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[?:1.8.0_152]
        at java.awt.Component.processEvent(Component.java:6298) ~[?:1.8.0_152]
        at java.awt.Container.processEvent(Container.java:2237) ~[?:1.8.0_152]
        at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[?:1.8.0_152]
        at java.awt.Container.dispatchEventImpl(Container.java:2295) ~[?:1.8.0_152]
        at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_152]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889) ~[?:1.8.0_152]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526) ~[?:1.8.0_152]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467) ~[?:1.8.0_152]
        at java.awt.Container.dispatchEventImpl(Container.java:2281) ~[?:1.8.0_152]
        at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[?:1.8.0_152]
        at java.awt.Component.dispatchEvent(Component.java:4711) ~[?:1.8.0_152]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[?:1.8.0_152]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:1.8.0_152]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[?:1.8.0_152]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[?:1.8.0_152]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_152]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[?:1.8.0_152]
        at java.awt.EventQueue$4.run(EventQueue.java:731) ~[?:1.8.0_152]
        at java.awt.EventQueue$4.run(EventQueue.java:729) ~[?:1.8.0_152]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[?:1.8.0_152]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[?:1.8.0_152]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) ~[?:1.8.0_152]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) ~[?:1.8.0_152]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) ~[?:1.8.0_152]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:1.8.0_152]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) ~[?:1.8.0_152]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) ~[?:1.8.0_152]

**Comment by halirutan** [comment] 2017-11-15 04:41
@sambo57u I cannot reproduce this either. Can you please specify exactly the system you are running? I'm here on

```
JabRef 4.1-dev
Linux 4.4.0-98-generic amd64 
Java 1.8.0_144
```

**Comment by tobiasdiez** [comment] 2017-11-15 05:07
It is probably again a problem with the look and feel. @sambo57u which l&f do you use and can you try out a different one please?

**Comment by sambo57u** [comment] 2017-11-15 13:46
I am using JabRef-4.1-dev--snapshot--2017-11-13--master--c1d425a31.jar on Fedora 27 Linux x86_64
with java version "1.8.0_152-ea". It happens on multiple computers with similar setting. I also had a
few occasions that it did not happen. Usually after adding or removing a field and pressing the Apply
button triggers it. However, the task seems to work.

**Comment by AEgit** [comment] 2017-11-15 15:34
@sambo57u : Which "look & feel setting" did you use (see @tobiasdiez question)?

**Comment by sambo57u** [comment] 2017-11-15 16:16
I never changed the look&feel. It says the default is MetalLookAndFeel and the box next to Use other
look and feel is not checked. The box for Tweak font rendering is checked.

**Comment by Siedlerchr** [comment] 2017-11-15 16:17
@sambo57u  please try if switching to Look and Feel "Plastic" resolves this problem

**Comment by sambo57u** [comment] 2017-11-15 16:23
Hmmm.....when restarting it said it was unable to find the Plastic3D and reverted it to the default one.
However, for some reason the fonts in the menus became bold. Do we have to download these look
and feels?

**Comment by sambo57u** [comment] 2017-11-15 16:25
Is this related to issue #2393

**Comment by halirutan** [comment] 2017-11-15 16:30
I tried with the Metal L&F, still no exception. I really would like to have this as well, because I analyzed the stack trace and what really confuses me is that the exception seems to have its origin in `at org.jabref.gui.search.GlobalSearchBar.clearSearch` which is weird. What I tried is switching to Metal and then

1. Create a new Database
2. BibTeX-->Customize entry types
3. In the Optional Fields choose "address" entry and click  add and then click apply

**Comment by halirutan** [comment] 2017-11-15 16:38
@sambo57u Another question: Are you using the Oracle JVM or the Open JVM that comes with Linux?

**Comment by sambo57u** [comment] 2017-11-15 16:41
Oracle JVM,  I do have the openjdk installed too but use alternatives to select Oracle JVM, doing
java -version or javac -version points to Oracle one.

**Comment by sambo57u** [comment] 2017-11-15 16:42
Here is the screen message from not finding look and feel:

$ 10:32:36.409 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: VU_bibtex_master.bib
10:32:40.340 [AWT-EventQueue-0] WARN  org.jabref.JabRefGUI - Unable to find requested look and feel
javax.swing.UnsupportedLookAndFeelException: [The JGoodies Windows Look and Feel - © 2001-2014 JGoodies Software GmbH - com.jgoodies.looks.windows.WindowsLookAndFeel] not supported on this platform
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:526) ~[?:1.8.0_162-ea]
        at javax.swing.UIManager.setLookAndFeel(UIManager.java:583) ~[?:1.8.0_162-ea]
        at org.jabref.JabRefGUI.setLookAndFeel(JabRefGUI.java:260) ~[jabref:?]
        at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:90) ~[jabref:?]
        at org.jabref.JabRefGUI.<init>(JabRefGUI.java:63) ~[jabref:?]
        at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:198) ~[jabref:?]
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) [?:1.8.0_162-ea]
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) [?:1.8.0_162-ea]
        at java.awt.EventQueue.access$500(EventQueue.java:97) [?:1.8.0_162-ea]
        at java.awt.EventQueue$3.run(EventQueue.java:709) [?:1.8.0_162-ea]
        at java.awt.EventQueue$3.run(EventQueue.java:703) [?:1.8.0_162-ea]
        at java.security.AccessController.doPrivileged(Native Method) [?:1.8.0_162-ea]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) [?:1.8.0_162-ea]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [?:1.8.0_162-ea]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [?:1.8.0_162-ea]
F

**Comment by sambo57u** [comment] 2017-11-27 00:40
Latest dev build allowed me to change Look and Feel, so I tried 3 different ones but the exception is still there.

**Comment by sambo57u** [comment] 2017-12-19 15:01
I just tried this with the 12-19 dev version (add optional field issn and click Apply, then select issn and
click Remove). The problem is still there (tiried Metal and Plastic L&Fs):

08:58:57.828 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.NullPointerException: null
        at javafx.scene.Scene$ScenePulseListener.synchronizeSceneNodes(Scene.java:2289) ~[jfxrt.jar:?]
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2419) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162-ea]
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162-ea]
08:58:57.844 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:418) ~[?:1.8.0_162-ea]
        at java.util.ArrayList.get(ArrayList.java:431) ~[?:1.8.0_162-ea]
        at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89) ~[jfxrt.jar:?]
        at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306) ~[jfxrt.jar:?]
        at javafx.scene.Parent.updateCachedBounds(Parent.java:1591) ~[jfxrt.jar:?]
        at javafx.scene.Parent.recomputeBounds(Parent.java:1535) ~[jfxrt.jar:?]
        at javafx.scene.Parent.impl_computeGeomBounds(Parent.java:1388) ~[jfxrt.jar:?]
        at javafx.scene.layout.Region.impl_computeGeomBounds(Region.java:3078) ~[jfxrt.jar:?]
        at javafx.scene.Node.updateGeomBounds(Node.java:3579) ~[jfxrt.jar:?]
        at javafx.scene.Node.getGeomBounds(Node.java:3532) ~[jfxrt.jar:?]
        at javafx.scene.Node.getLocalBounds(Node.java:3480) ~[jfxrt.jar:?]
        at javafx.scene.Node.updateTxBounds(Node.java:3643) ~[jfxrt.jar:?]
        at javafx.scene.Node.getTransformedBounds(Node.java:3426) ~[jfxrt.jar:?]
        at javafx.scene.Node.updateBounds(Node.java:559) ~[jfxrt.jar:?]
        at javafx.scene.Parent.updateBounds(Parent.java:1719) ~[jfxrt.jar:?]
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2404) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398) ~[jfxrt.jar:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_162-ea]
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:424) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:518) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:498) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:491) ~[jfxrt.jar:?]
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319) ~[jfxrt.jar:?]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:?]
        at com.sun.glass.ui.gtk.GtkApplication.lambda$null$48(GtkApplication.java:139) ~[jfxrt.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162-ea]
08:58:57.859 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:57.876 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:57.893 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:57.909 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:57.926 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:57.942 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:57.959 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:57.975 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:57.991 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:58.008 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:58.024 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:58.041 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null
08:58:58.058 [JavaFX Application Thread] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by sambo57u** [comment] 2017-12-30 19:19
This is still there with 12-29 build. It can sometime temporarily freeze the whole computer because for a large bib file when adding an entry we seem to get an exception message for every single entry with thousands of pages scrolling.

**Comment by Siedlerchr** [comment] 2017-12-30 22:11
Are you by chance running an import to the library which produces an error?
Otherwise it might help, if you could send us your bib file to developers@jabref.org

**Comment by sambo57u** [comment] 2017-12-30 22:17
No, just using my bib file. I am attaching the file.

[VU_bibtex_master.bib.zip](https://github.com/JabRef/jabref/files/1594814/VU_bibtex_master.bib.zip)

**Comment by Siedlerchr** [comment] 2018-02-04 18:08
Hi, I tried to reproduce the issue. While I don't get an exception, I do see that it takes a long time to update the entries if you click apply. This should run somewhere in the background thread.
Could you please check out the latest version? https://builds.jabref.org/master/

**Comment by sambo57u** [comment] 2018-02-04 21:07
I used the latest master and I am still getting thousands of exceptions

**Comment by lenhard** [comment] 2018-02-06 19:50
I just tried this with your bib file on the current master (on Win7 nevermind). The longer update mentioned by @Siedlerchr is probably just down to the large size of the bib file. 

Since no one here is able to reproduce this, this might be down to the particular system configuration you are using. Maybe there is a deeper problem with Java that is really independent of JabRef.

**Comment by stefan-kolb** [comment] 2018-02-08 13:11
I have tested it, but also cannot reproduce this behavior on the current `master`. As the functionality itself is not prevented (at least that is what I get from your comments) I'm closing this for now.

**Closed by stefan-kolb** 2018-02-08 13:11 UTC
Labels: bug, linux, preferences, waiting-for-feedback
