### ISSUE TITLE
Crash pango with italic characters

### ISSUE THREAD

**Issue by sambo57u** [JabRef/jabref#5866] opened 2020-01-25 14:29 UTC
JabRef 5.0-beta.360--2020-01-21--7ddfd9f
Java(TM) SE Runtime Environment (build 13.0.2+8)
pango-1.44.7 
Fedora Linux 31

When I open jabref with the attached bib file, it opens ok but when I try to use the scroll bar to scroll down about half way through jabref crashes with the message:

Pango:ERROR:../pango/pango-context.c:1434:itemize_state_process_run: assertion failed: (state->run_end != state->run_start)
Bail out! Pango:ERROR:../pango/pango-context.c:1434:itemize_state_process_run: assertion failed: (state->run_end != state->run_start)
Aborted (core dumped)

[JacekD.bib.gz](https://github.com/JabRef/jabref/files/4112115/JacekD.bib.gz)

**Comment by Siedlerchr** [comment] 2020-01-26 17:04
I am not a LInux expert and on Windows I cannot encounter a problem, but it might be related to Font stuff. E.g. Maybe there is a problem with the font or the Unicode-italic rendering in the form here.
Maybe one of the other fedora users can reproduce this problem. 
But I would close this issue as it seems to be some javafx/linux problems which we can't do anything about here

**Comment by sambo57u** [comment] 2020-01-26 17:06
It is related to unicode characters. I am not sure why you closed it since it core dumps jabref on a stable Linux distribution and core dump is always a bug!

**Comment by Siedlerchr** [comment] 2020-01-26 17:16
Well, the problem is not in JabRef itself I think, but either in JavaFX or the pango library.
You better should report this bug to the pango team as this error dump is clearly related to pango.
https://gitlab.gnome.org/GNOME/pango/issues

You could try to change the Font in settings and see if that helps.

**Comment by sambo57u** [comment] 2020-01-29 00:20
Hi, I narrowed it down to a single reference. The attached bib file crashes jabref every time. It seems like the latex sequence in Garc\'{\i}a-Recio crashes jabref.

[crash.bib.gz](https://github.com/JabRef/jabref/files/4125547/crash.bib.gz)

**Comment by sambo57u** [comment] 2020-01-29 00:22
NOTE: Look at the actual bib file since the pasting into message missed a \

**Comment by sambo57u** [comment] 2020-01-29 13:41
It is \'{\i} that is making jabref coredump. Removing the slash works ok \'{i}

**Comment by Siedlerchr** [comment] 2020-01-29 14:29
@sambo57u  Yes, that's what I suspected as well. It's the latex command for displaying text in italics.
Could you try to convert it using the latex2unicode formatter and test if that works?

**Comment by sambo57u** [comment] 2020-01-29 14:42
Yes, using http://latex2unicode.herokuapp.com/ for interactive testing produces the correct dotless i
with French accent.

**Comment by sambo57u** [comment] 2020-01-29 14:49
I guess this is passed to Pango after conversion that somehow leads to jabref coredump. Pango I have is the latest one. And as jabref I am using today's rpm build.

**Comment by Siedlerchr** [comment] 2020-08-29 20:53
I think this issue is not in JabRef's , it's beyond our realm and we cannot do anything about this. Therefore I'm closing this issue.

**Closed by Siedlerchr** 2020-08-29 20:53 UTC
Labels: os: linux, ui

**Comment by candrews** [comment] 2020-10-07 15:05
Has anyone reported this issue to Pango? If so, can you please provide a link to it?

**Comment by Siedlerchr** [comment] 2020-10-07 15:51
It might be fixed in javafx 15 (we plan to use that soon), at least there was something I read about pango

**Comment by Siedlerchr** [comment] 2020-10-15 16:19
I just merged in the new javafx version. According to the changelog https://github.com/openjdk/jfx/blob/jfx15/doc-files/release-notes-15.md
this issue might be finally fixed

**Comment by sambo57u** [comment] 2020-10-15 16:53
I can confirm that it is fixed! Thanks.
