### ISSUE TITLE
Cannot open preferences

### ISSUE THREAD

**Issue by spicydonkey** [JabRef/jabref#4814] opened 2019-03-27 11:20 UTC
I am unable to access "Preferences" under "Options" menu. I noticed it after trying out a developer version, which had its own problems for me.

The issue is from the stable release:

JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_172

Steps to reproduce:

Cannot guarantee this step will reproduce error since I cannot seem to get "Preferences" to open anymore, even after running "uninstall.exe" found in the installation directory and fresh-installing.
1. Install stable version "JabRef_windows-x64_4_3_1"
2. Install the dev version: "JabRef_windows-x64_5_0-dev--snapshot--2019-03-20--master--6c61664a8"
3. Reinstall stable version "JabRef_windows-x64_4_3_1"

Here is the event log details:

<details>
<summary>Detail information:</summary>

```
Opening: C:\Users\David\Downloads\references.bib
Opening: C:\Users\David\Documents\phd\metro-halo\halo_mag_tomo.bib
Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "97.00426097278765"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "607.8933687628023"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "607.8933687628023"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "77.60340877823012"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "168.14071901949856"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "129.33901463038353"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "129.33901463038353"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "129.33901463038353"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "129.33901463038353"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "129.33901463038353"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "129.33901463038353"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception while setting column widths. Choosing default.
java.lang.NumberFormatException: For input string: "129.33901463038353"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.maintable.MainTable.setWidths(MainTable.java:330)
	at org.jabref.gui.maintable.MainTable.<init>(MainTable.java:159)
	at org.jabref.gui.BasePanel.createMainTable(BasePanel.java:1282)
	at org.jabref.gui.BasePanel.setupMainPanel(BasePanel.java:1393)
	at org.jabref.gui.BasePanel.<init>(BasePanel.java:228)
	at org.jabref.gui.JabRefFrame.addTab(JabRefFrame.java:1604)
	at org.jabref.gui.JabRefFrame.addParserResult(JabRefFrame.java:1304)
	at org.jabref.JabRefGUI.openWindow(JabRefGUI.java:138)
	at org.jabref.JabRefGUI.<init>(JabRefGUI.java:67)
	at org.jabref.JabRefMain.lambda$start$1(JabRefMain.java:128)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NumberFormatException: For input string: "97.00426097278765"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.preftabs.TableColumnsTab.setValues(TableColumnsTab.java:443)
	at org.jabref.gui.preftabs.PreferencesDialog.setValues(PreferencesDialog.java:258)
	at org.jabref.gui.preftabs.PreferencesDialog.<init>(PreferencesDialog.java:206)
	at org.jabref.gui.JabRefFrame.showPreferencesDialog(JabRefFrame.java:756)
	at org.jabref.gui.JabRefFrame$ShowPrefsAction.actionPerformed(JabRefFrame.java:2092)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NumberFormatException: For input string: "97.00426097278765"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.jabref.gui.preftabs.TableColumnsTab.setValues(TableColumnsTab.java:443)
	at org.jabref.gui.preftabs.PreferencesDialog.setValues(PreferencesDialog.java:258)
	at org.jabref.gui.preftabs.PreferencesDialog.<init>(PreferencesDialog.java:206)
	at org.jabref.gui.JabRefFrame.showPreferencesDialog(JabRefFrame.java:756)
	at org.jabref.gui.JabRefFrame$ShowPrefsAction.actionPerformed(JabRefFrame.java:2092)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

</details>

**Comment by tobiasdiez** [comment] 2019-03-27 14:35
Duplicate of #4579

**Closed by tobiasdiez** 2019-03-27 14:35 UTC
