### ISSUE TITLE
Opening preferences generates exception

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#5252] opened 2019-08-28 15:06 UTC
JabRef version 5.0-dev

- [x] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

There's an exception when opening the preference dialog

1. Open preference dialog

<details>
  <summary>Exception</summary>
  
  ```
java.nio.file.FileSystemAlreadyExistsException
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:102)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:344)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:293)
	at org.jabref.logic.citationstyle.CitationStyle.discoverCitationStyles(CitationStyle.java:147)
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:46)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:122)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1425)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
  ```
</details>

**Comment by Siedlerchr** [comment] 2019-08-28 15:12
Please next time look for already open issues. 
Duplicate of #5245

**Closed by Siedlerchr** 2019-08-28 15:12 UTC
