### ISSUE TITLE
Danish author name mangled in IEEE and Nature previews

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#4880] opened 2019-04-11 23:56 UTC
For the attached bibtex entry, the IEEE and Nature previews mangle the last author's name.  The entry is pasted below and a screenshot of the IEEE preview is attached.

JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_201

```
@Article{Nykvist19,
  author   = {Bj{\:o}rn Nykvist and Frances Sprei and M{\aa}ns Nilsson},
  title    = {Assessing the progress toward lower priced long range battery electric vehicles},
  journal  = {Energy Policy},
  year     = {2019},
  volume   = {124},
  pages    = {144 - 155},
  issn     = {0301-4215},
  abstract = {The aim of this study is to show the progress in attributes and prices of battery electric vehicles (BEV) and to analyse in which market segments long range BEV can be produced at comparable cost to conventional cars. We assess 48 models available to consumers since 1997, collecting data on attributes, weight and vehicle prices. We also provide an analysis of recent progress in battery pack costs. Based on this data, the share of BEV vehicle price that is related to the battery pack is modelled. To illustrate future progress we estimate when it is possible to produce a BEV with a 200 mile range in a given price percentile. We find that the price percentile where the price of a BEV is comparable to conventional cars changes in a nonlinear way when battery pack costs fall below 200–250 USD/kWh. Furthermore, we show that battery pack costs of 150 USD/kWh could imply that production costs of a BEV with a 200 mile range are cost competitive for almost 50% of the US car market segments by 2020. Finally, the most critical conditions for this development are discussed and assessed by sensitivity analysis applying conservative values to our model.},
  comment  = {A learning-rate based price forecast for long range electric cars.  Quite a bit about learning rates, actually.},
  doi      = {https://doi.org/10.1016/j.enpol.2018.09.035},
  file     = {:Nykvist19bevPriceFrcst.pdf:PDF},
  keywords = {Battery electric vehicle, Production, Attributes, Range, Market segments},
  url      = {http://www.sciencedirect.com/science/article/pii/S0301421518306487},
}
```

![image](https://user-images.githubusercontent.com/3851891/56003258-a1184a80-5c7a-11e9-95ca-615124f87078.png)

**Comment by LakminiSenanayake** [comment] 2019-05-19 07:00
Hi @tobiasdiez ,

I'm going to proceed with this issue.

Cheers

**Comment by CyraxSector** [comment] 2019-06-17 18:40
@notuntoward Is this issue still exists? I tried to reproduce this issue but I couldn't. Have I missed anything here?

**Comment by notuntoward** [comment] 2019-06-17 23:35
Hi, yes, it still happens on 4.3.1.  Screenshot below.

![image](https://user-images.githubusercontent.com/3851891/59643525-e2ffba00-911d-11e9-9fef-19c73fad9ce5.png)



JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_211

**Comment by CyraxSector** [comment] 2019-06-19 01:29
@notuntoward Great. Thanks for the prompt response. we'll carry on the investigations further.

**Comment by CyraxSector** [comment] 2019-06-20 18:15
@tobiasdiez I've tested this issue on the latest JabRef version and the observation is as follows. 

![1](https://user-images.githubusercontent.com/4902204/59871436-38092d80-93b5-11e9-8fed-75bdc14b9c39.JPG)

I couldn't see any issue with the author names. Seems this has been fixed in a later version than 4.3.1. May I proceed the investigations further on JabRef 4.3.1?

**Comment by Siedlerchr** [comment] 2019-06-20 19:24
If it's not reproducible in the latest Master the 5.x version it's good.
We can only support the latest development version.

**Comment by CyraxSector** [comment] 2019-06-21 17:58
Since this cannot be reproduced in the latest JabRef version, @notuntoward @Siedlerchr can we close this ticket?

**Comment by notuntoward** [comment] 2019-06-21 18:00
Yes, thanks, if it's fixed, then closing it makes sense.

**Comment by CyraxSector** [comment] 2019-06-21 18:02
@notuntoward cool. @Siedlerchr @tobiasdiez could you please close this since this has been fixed in the lates JabRef version.

**Closed** 2019-06-21 18:46 UTC
Labels: entry-preview
