### ISSUE TITLE
Run cleanup operations directly after import

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/jabref#1283] opened 2016-04-23 18:54 UTC
It would be nice to specify some cleanup operations which should run directly after some entries are imported (directly or using a fetcher).

**Comment by lenhard** [comment] 2017-07-18 15:13
As far as I understand, this is more or less a duplicate of #895 and we don't need two issues to track that.

**Closed by lenhard** 2017-07-18 15:13 UTC
Labels: feature, fetcher, import
