### ISSUE TITLE
Update group name in list when it's changed

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3527] opened 2017-12-13 21:15 UTC
- [x] I have tested the latest git version

JabRef version 4.1-dev

Steps to reproduce:

1. change group name via "edit group"
2. it's updated under General > Groups but not in the group tree

**Comment by Siedlerchr** [comment] 2017-12-13 21:48
You have to collapse/expand the specific group (double click)  to make the changes visible. It's a known problem. There is a similar issue about this, which I can't find atm

**Comment by j0hannes** [comment] 2017-12-13 22:29
I can't, it's a top-level group without any subgroups. Searching for 'group' and 'name' gave no results.

**Comment by tobiasdiez** [comment] 2017-12-14 10:11
Duplicate of #3189.

**Closed by tobiasdiez** 2017-12-14 10:11 UTC
