### ISSUE TITLE
Entry table: Familly name partly displayed 

### ISSUE THREAD

**Issue by mlep** [JabRef/jabref#1528] opened 2016-06-29 15:19 UTC
JabRef version JabRef 3.5dev--snapshot--2016-06-28--master--12ae6e3 linux 3.11-2-amd64 amd64  Java 1.8.0_66 on Linux Mint LMDE

If the author is entered as
`Iglesias de la Cueva, Julio José`
the entry table displays
`Iglesias de la Cueva`
which is the expected behavior.

However, If the author is entered as 
`Julio José {Iglesias de la Cueva}`
the entry table displays
`de la Cueva`
which is the incorrect.

**Comment by matthiasgeiger** [comment] 2016-06-29 19:16
I think JabRef has the same difficulties in detecting which part of this name are fornames and what is the surname :wink:

This seems to be related a duplicate of #1499 - where also names in braces are not displayed correctly.

**Closed by matthiasgeiger** 2016-06-29 19:16 UTC
Labels: duplicate
