### ISSUE TITLE
Can't export to MySQL 5.5 in JabRef 3.2

### ISSUE THREAD

**Issue by yuyaoshen** [JabRef/jabref#685] opened 2016-01-20 03:41 UTC
I'm using Jabref 3.2 and MySQL 5.5, but now I can't export my .bib to SQL database. It is fine when i am using 2.10, I don't know why.
The error is: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'INSERT INTO entries (jabref_eid, entry_types_id, cite_key, abstract, address, an' at line 1.
Can someone help me with this?

**Comment by koppor** [comment] 2016-01-21 12:19
Is it possible to post a [minimal, complete, and verifiable example](https://en.wikipedia.org/wiki/Minimal_Working_Example)? Is there a minimal bib file which is not working at your side? Which OS are you running?

**Comment by yuyaoshen** [comment] 2016-01-21 13:12
This is the example. If there is only one record, the export will fine, but if there two, it error.
I'm running Ubuntu 14.04.
[test.bib.txt](https://github.com/JabRef/jabref/files/99150/test.bib.txt)

**Comment by Siedlerchr** [comment] 2016-02-02 09:29
I'll take a look at that.

**Comment by Siedlerchr** [comment] 2016-02-05 19:55
I looked into the code and interestingly the generated statement works when it's executed directly on the Mysql Database. I will look further into this issue-

**Comment by Siedlerchr** [comment] 2016-02-12 20:43
I found the reason for the error and a fix!
The problem is, that the usage of multiple statements at once has to be specified in the Connection String. So, the solution is to simply add the parameter `?allowMultiQueries=true`.

I'll prepare a Pull Request.

[StackOverlow Answer to the Problem](http://stackoverflow.com/questions/10797794/multiple-queries-executed-in-java-in-single-statement

**Comment by yuyaoshen** [comment] 2016-02-13 11:09
so where should I add this parameter, I'm using .jar file. Thanks very much.

**Comment by Siedlerchr** [comment] 2016-02-13 11:18
@yuyaoshen  It has to be fixed in the code. Wait for a new release.

**Comment by yuyaoshen** [comment] 2016-02-13 11:21
@Siedlerchr Thanks again, waiting for the new release

**Closed** 2016-02-22 09:35 UTC
Labels: bug
