### ISSUE TITLE
Fields on two columns in the entry editor have unequal width

### ISSUE THREAD

**Issue by crystalfp** [JabRef/jabref#7055] opened 2020-10-31 09:29 UTC
JabRef 5.2--2020-10-15--13a80ba
Windows 10 10.0 amd64 
Java 14.0.2

Steps to reproduce:

1. Open any library and double click on a book entry
2. Select the "Optional fields" tab
3. Look at the entry editor and entry preview bottom half of the screen (see screenshot 1) the two columns have different width and not occupy the same amount of space.
3. Move the separator between the two to the left. The right column shrink and becomes unusable (see screenshot 2) instead of have the two columns split in half the available width.

Screenshot 1:
![image](https://user-images.githubusercontent.com/865866/97775758-827eea80-1b63-11eb-998e-b8e509617cd8.png)

Screenshot 2:
![image](https://user-images.githubusercontent.com/865866/97775781-9aef0500-1b63-11eb-9bab-f82820555780.png)

**Comment by Siedlerchr** [comment] 2020-11-08 18:24
Duplicate of #6901 
Problem/Fix is outlined here:
https://github.com/JabRef/jabref/issues/6901#issuecomment-691493493

**Closed by Siedlerchr** 2020-11-08 18:24 UTC

**Comment by crystalfp** [comment] 2020-11-09 07:16
Well, outlined. Not solved.
And #6901 has been closed too.
This means, in my opinion, that this bug will not be solved.
Also the suggestion to put the preview window as another tab **does not** remove it form the side of the "Optional fields" tab.

**Comment by Siedlerchr** [comment] 2020-11-09 07:58
No 6901 is still open!

**Comment by crystalfp** [comment] 2020-11-09 08:06
Opps! Sorry. Seen a "Closed" icon, put was for another issue...
