### ISSUE TITLE
importing preferences does not work

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#3064] opened 2017-08-01 10:14 UTC
JabRef 4.0-dev--snapshot--2017-07-31--master--ed815b4a9
Linux 4.11.11-300.fc26.x86_64 amd64 
Java 1.8.0_144

1) export preferences
2) reset preferences
saves preference file works

3) import preferences

Issue: when attempting to activate "import preferences", no import dialogue shows up.

Same happens at 
JabRef 4.0.0-beta
Linux 4.11.11-300.fc26.x86_64 amd64 
Java 1.8.0_144

**Comment by lenhard** [comment] 2017-08-01 10:22
I can confirm this on Win7. No import dialog and also no messages in the log.

@Siedlerchr There were changes to the file system dialog, right?

**Comment by Siedlerchr** [comment] 2017-08-01 10:41
You have to restart JabRef after resetting the preferences to import new ones., as the dialog says.

**Comment by lenhard** [comment] 2017-08-01 10:45
The problem is that there's no dialog. I haven't done anything with my preferences, but when I hit the button "Import preferences" then nothing happens.

It's not necessarily related to your changes. Maybe that dialog is broken since a long time.

**Comment by Siedlerchr** [comment] 2017-08-01 10:48
After a restart of JabRef the dialog appears again. I look into that

**Comment by Siedlerchr** [comment] 2017-08-01 10:50
Found the bug, the exportPath in the FiledialogBuilder is null and Files.exist(null) throws an NPE

**Comment by Siedlerchr** [comment] 2017-08-02 08:51
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you.

**Closed by Siedlerchr** 2017-08-02 08:51 UTC
Labels: bug, ui

**Comment by ilippert** [comment] 2017-08-02 20:19
works, thanks a lot!
