### ISSUE TITLE
LaTeX to unicode cleanup action does not remove backslash in title subtitle and custom fields

### ISSUE THREAD

**Issue by ThiloteE** [JabRef/jabref#8687] opened 2022-04-18 16:55 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 5.6--2022-04-11--1c782b7 Windows 10 10.0 amd64  Java 17.0.2  JavaFX 18+12

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

Before:

```
@Article{test1aBEFORE,
  title    = {\%, \$, \_, \#, \&},
  subtitle = {\%, \$, \_, \#, \&},
  url      = {https://ftp.agdsn.de/pub/mirrors/latex/dante/info/symbols/comprehensive/symbols-a4.pdf},
  abstract = {\%, \$, \_, \#, \&},
  comment1 = {Special fields (Page 15, Table 1); Backslash was manually added},
  comment2 = {BEFORE using "LaTeX to Unicode" cleanup action},
  xyz      = {\%, \$, \_, \#, \&},
}
```

After:

```
@Article{test1bAFTER,
  title    = {\%, \$, \_, \#, \&},
  subtitle = {\%, \$, \_, \#, \&},
  url      = {https://ftp.agdsn.de/pub/mirrors/latex/dante/info/symbols/comprehensive/symbols-a4.pdf},
  abstract = {%, $, \_, #, &},
  comment1 = {Special fields (Page 15, Table 1)},
  comment2 = {AFTER using "LaTeX to Unicode" cleanup action},
  xyz      = {\%, \$, \_, \#, \&},
}
```

Only characters within the `abstract` field do get converted.

I have not tested `issuetitle`, `issuesubtitle` and other similar fields, but could imagine it happens with them as well.

**Comment by Siedlerchr** [comment] 2022-04-20 06:15
Works fine for me. Did you enable Latex2Unicode for *all text fields* 
<img width="629" alt="grafik" src="https://user-images.githubusercontent.com/320228/164162675-61c2b9a9-32c4-4999-85e6-54337d8a5968.png">

**Comment by ThiloteE** [comment] 2022-04-20 08:23
I specifically only chose the `title`, `subtitle`, `abstract` and `xyz` (= the custom field) fields.
I did NOT use LaTeX2Unicode for *all text fields*

**Comment by Siedlerchr** [comment] 2022-04-20 19:04
Stil cannot reproduce this:
After:
```
@Article{,
  title    = {%, $, \_, #, &},
  abstract = {%, $, \_, #, &},
  comment1 = {Special fields (Page 15, Table 1); Backslash was manually added},
  comment2 = {BEFORE using "LaTeX to Unicode" cleanup action},
  subtitle = {%, $, \_, #, &},
  url      = {https://ftp.agdsn.de/pub/mirrors/latex/dante/info/symbols/comprehensive/symbols-a4.pdf},
  xyz      = {%, $, \_, #, &},
}
```
<img width="606" alt="grafik" src="https://user-images.githubusercontent.com/320228/164303988-ce6a2504-4c3e-4ff7-bf86-ccb7b20a7718.png">

**Comment by ThiloteE** [comment] 2022-04-20 19:08
Yes, that is exactly what I did Christoph.

Hmmm ... ok, I will try again and report back. Maybe there is some shenanigans going on with having to close and restart Jabref before they take effect? Dunno.

**Comment by Siedlerchr** [comment] 2022-04-20 19:16
Tried this in a new empty library.

**Comment by ThiloteE** [comment] 2022-04-20 19:24
These were the settings I used:

![image](https://user-images.githubusercontent.com/73715071/164307448-5d833511-051c-45d0-9e43-8a3f040db4bb.png)

**Comment by ThiloteE** [comment] 2022-04-20 19:40
Ok, I was able to reproduce your results by removing all cleanup actions. Trying to finding out which one is the culprit, I found:

- After having reset cleanup actions to default:
   - I see `All-text-fields: Replace Unicode ligatures`. No clue what It does. When removing this one, I cannot re-add it anymore. It cannot be found in the dialogue that allows me to choose from various cleanup actions. Not sure if this has anything to do with it.
   - `All-text-fields: identity` vanished and I cannot re-add it.

**Comment by ThiloteE** [comment] 2022-04-20 19:43
Ok, I think the culprit is `normalize date`.

**Comment by Siedlerchr** [comment] 2022-04-20 19:52
Have you mabye convert to bibtex/biblatex format=? 
<img width="606" alt="grafik" src="https://user-images.githubusercontent.com/320228/164311695-b668cca6-da44-497b-84e3-7a3353cf4f26.png">

**Comment by ThiloteE** [comment] 2022-04-20 19:53
No, I have not.
Ok, culprit is `All-text-fields: Cleanup URL link`

**Comment by ThiloteE** [comment] 2022-04-20 19:53
If you add that one, it will prevent doing the conversion.

**Comment by Siedlerchr** [comment] 2022-04-20 19:55
So we can close this as [PEBCAK]https://en.wiktionary.org/wiki/PEBCAK

**Closed** 2022-04-20 19:55 UTC
Labels: status: waiting-for-customer-feedback, unicode

**Comment by ThiloteE** [comment] 2022-04-20 19:56
I guess so 😅 I will make sure to limit the usage of this cleanup action to the URL field only.
