### ISSUE TITLE
Too long time for status popups

### ISSUE THREAD

**Issue by reox** [JabRef/jabref#5555] opened 2019-11-01 22:26 UTC
**Is your suggestion for improvement related to a problem? Please describe.**

I'm using the 5.x snapshots of JabRef.

My usual workflow for adding articles is like this: copy DOI, go into JabRef, press Ctrl+N, Press Ctrl+V, Enter, Press Alt+F7, Press Alt+F8.
I also have auto-saving activated.
When I do this, I see a lot of status popups / messages at the bottom, i.e.
```
Saving library...
Saved library 'file.bib'
Adding new 'Article' Entry
Saving library...
Saved library 'file.bib'
Saving library...
Saved library 'file.bib'
Looking for full text document...
Saving library...
Saved library 'file.bib'
finished full text document download for entry Foo
Saving library...
Saved library 'file.bib'
Doing a cleanup for 1 entry...
Saving library...
Saved library 'file.bib'.
Saving library...
Saved library 'file.bib'.
```

each of the popups stays for about 3 seconds, so the process of adding a new entry, which took me like 5 seconds will not produce popups for about the next minute.

**Describe the solution you'd like**
Usually I do not care about messages when saving and have the library saved. In my opinion there should be a message if it has failed but not for every auto-save action. Maybe when auto-saving is enabled, there should be no message, only if manual saving is requested.

Next, the duration is too long for certain actions. I.e. if you are looking for the text document, there should be a message saying "I found one, downloading..." (right now the user has no information that a document was found and sometimes the download takes some time) which will cancel the previous notification. Also if the document is downloaded, the message could cancel the previous one, as it made the previous notification irrelevant.
From a usability point of view, the message should be shown when the action is taken. Using a message queue is IMO only helpful when the action and message are not time related.

If all the messages are important, then a log or list of messages would probably be better or maybe stacking them into a single popup - but as you might see with the number of messages right now, this would fill up quite easily.

**Comment by tobiasdiez** [comment] 2019-11-02 14:09
Agree. Especially, the auto-save should never display a notification.

**Comment by Ka0o0** [comment] 2019-11-02 17:41
Hello,

If the issue is still not addressed, I would like to contribute.
For me the requirements were a bit unclear, so I tried to make myself my own picture in regards to notification. For me, it feels like notifications are used quite often.
Sometimes, I think they might be obsolete, as either the default expectation of a user is reported or changes are directly visible in the UI.
I summarized my questions below.

Regardless of my questions, is there any specification on how the expected behavior should be like upon which I could orientate?

Thanks in advance

---

- Is `Preferences recorded` in `PreferencesDialogViewModel` obsolete? User would expect that this happen, and should we only show a notification in error case?
- Is `Closed library` in `JabRefFrame` obsolete? Is directly represented in the view.
- Is `New library created` in `FromAuxDialog` obsolete?
- In all actions, should the `going to do something` message be replaced with a progress bar and one final notification? Actions might take long, and any thoughts about hindering the user from messing with the DB during operation?
    - SaveAllAction
    - ExportCommand
    - CleanupAction
    - GeneratingBibtexKeyAction
    - DuplicateSearch
- `This action requires one or more entries to be selected` notification looks the same as a successful notification. Should the action be disabled in the menu bar?
    - Additionally, when using `Cmd + C` no such popup is presented
- Is `Saving library` obsolete? Maybe short spinner.
- In AttachFileAction, `This operation requires exactly one entry to be selected`, can the action be disabled?
- Are the messages in `ToggleUnionIntersection` obsolete? It is directly represented in the view.
- Is `Added group` obsolete?
- Is `Modified group` obsolete?
- Is `Removed group` obsolete?
- Is `Files opened` obsolete?
- Is `File already open` obsolete? Could we just switch to the tab of the opened file?
- Can `Opening file` be replaced with a progress bar or spinner?
- Is `Opened database` obsolete? Directly visible in UI.
- Is the `Connection lost` notification obsolete, as there is a popup with the same text right afterwards anyway?

**Comment by tobiasdiez** [comment] 2019-11-02 21:07
Thanks for the throughout analysis. The notifications should be shown only if there is no visible change (or the change might be so minimal that users don't notice them). Thus, I agree with the items you listed except for the following:
- `Preferences recorded`  although expected, there is no visible feedback and it doesn't hurt to notify the user about a successful action.
- Notifications related to the groups, as these changes might be small and easily missed if you have large group trees

I also like the idea to replace the progress notifications by some spinner and/or progress bar. Not sure however how easily this can be implemented.

**Comment by reox** [comment] 2019-11-02 21:14
> I also like the idea to replace the progress notifications by some spinner and/or progress bar. Not sure however how easily this can be implemented.

Do you know [Darktable](https://www.darktable.org/)? I think they have a nice system implemented: They use stackable progressbars and system notifications.
So if you do some things after each other, the progressbars will stack up. If one item is finished you get a notification into the system bus (depending on your OS and bus system you use).

**Comment by Siedlerchr** [comment] 2019-11-02 21:34
I think eclipse also has this multiple progress bars window for tasks to be performed

**Comment by Ka0o0** [comment] 2019-11-03 09:20
Okay I think there are multiple tasks here:

- Remove obsolete notifications
- Implement Spinner/Progress notification for longer tasks
- Disable actions that are not possible

To keep this issue as small as possible, I would suggest we just remove the obsolete notifications for this issue, add another UI improvement issue for the spinner and another for disabling not possible actions. What do you think @tobiasdiez ?

**Comment by koppor** [comment] 2019-11-03 19:34
@Ka0o0 Thank you for the precise task list. Maybe you can add https://github.com/koppor/jabref/issues/96 to your list? 😇 . The third issue ("Disable actions that are not possible") is https://github.com/JabRef/jabref/issues/4795 and somehow refs https://github.com/koppor/jabref/issues/156

**Comment by Ka0o0** [comment] 2019-11-04 19:04
I've added the later two ones but I don't quite understand how koppor#96 fits into this issue?

**Comment by Siedlerchr** [comment] 2019-11-07 14:42
Thanks to @Ka0o0  this isssue should be resolved now.
There should be no longer save messages on autosvave

**Comment by koppor** [comment] 2019-11-10 00:20
https://github.com/koppor/jabref/issues/96 related to "Disable actions that are not possible". In case no database is opened, more actions are not possible. I think, one has to check if a database is opened. In this context, one could also think about a background picture. (At least it is closer to this issue than probably most other issues here ^^).

**Comment by reox** [comment] 2019-11-10 19:52
Thanks for all the fixes, it already looks much better!

I think you can also remove the "looking for full text online" status message, as there is a window too.
On another but maybe similar issue regarding status messages:
I had to use Jabref 4 recently and I noticed that there is even a dialog which shows the current progress of downloading, which seems to be removed in 5.x? Or do I have to somehow enable this?

**Comment by Siedlerchr** [comment] 2020-09-01 16:03
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2020-09-01 16:03 UTC
Labels: good first issue, type: enhancement, ui
