### ISSUE TITLE
JabRef does not save/restore window split setting

### ISSUE THREAD

**Issue by AdamWysokinski** [JabRef/jabref#11554] opened 2024-08-01 06:09 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

GNU / Linux

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Start JabRef
2. Open Groups pane
3. Set the Groups pane width to 1/3 of the JabRef window width
4. Exit JabRef
5. Start JabRef
6. Groups pane has half of the JabRef window width

**Comment by InAnYan** [comment] 2024-08-01 10:40
Can confirm, I also had this problem often. Annoying a little bit.

Hmm, but I don't have it now. 

Trying to reduce the problem and find the exact conditions where it occurrs

**Comment by LoayGhreeb** [comment] 2024-08-04 12:49
Duplicate of https://github.com/JabRef/jabref/issues/8907

**Comment by koppor** [comment] 2024-08-05 05:47
Even though it is a duplicate, let's collect OS information here.

@AdamWysokinski and @InAnYan which OS did you try? A concrete release is good. Which Window Manager? We can then try to setup a VM (https://github.com/JabRef/jabref/tree/main/scripts/vms) - or even a contributor can help to craft a Vagrant file 💪. - None of us are experts in Vagrant, but it seems to be the best solution to make reproducible VMs.

**Comment by AdamWysokinski** [comment] 2024-08-05 17:58
Linux (Debian Testing), xorg, i3 here.

**Comment by InAnYan** [comment] 2024-08-05 18:11
Linux Mint 21.3 x86_64

Kernel: 5.15.0-116-generic

Desktop Environment: Xfce 4.18 
Windows manager: Xfwm4

**Comment by ryan-carpenter** [comment] 2024-08-17 02:38
I have had this issue for since upgrading to JabRef 5.15, I believe.

JabRef 5.16--2024-08-13--1374813
Linux 6.9.9-1-default amd64 
Java 21.0.2 
JavaFX 22.0.2+4

Operating System: openSUSE Tumbleweed 20240724
KDE Plasma Version: 6.1.3
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.9-1-default (64-bit)
Graphics Platform: Wayland

**Comment by AdamWysokinski** [comment] 2024-08-17 05:52
The issue is resolved in the recent 5.16 JDK-EA builds (https://builds.jabref.org/jdk-ea/).

**Comment by ryan-carpenter** [comment] 2024-08-27 16:47
> The issue is resolved in the recent 5.16 JDK-EA builds (https://builds.jabref.org/jdk-ea/).

Confirmed on my machine. If it matters, the panel still shows wider than normal during startup, then jumps to the proper position by the time JabRef is done loading.

**Closed** 2024-09-17 09:38 UTC
