### ISSUE TITLE
Upgraded to windows 10: Bibsonomy plug-in failure

### ISSUE THREAD

**Issue by ideutsch** [JabRef/jabref#151] opened 2015-09-09 16:15 UTC
I upgraded my OS from Windows 7 to Windows 10 recently, and the JabRef does not allow me to add new entries or even edit existing entries. Whenever I tried to add new entry or tried to edit an existing entries, there popped out an "error: added_entry". The error console told me the following. See if anyone knows how to fix it:

***Log***
```
Sep 09, 2015 9:54:23 AM net.sf.jabref.plugin.PluginCore initialize
INFO: Found 8 plugin(s):
  - adssearch (jar:file:/C:/Users/qxd/.jabref/plugins/ADSsearch-0.1.jar!/plugin.xml)
  - net.sf.jabref.core (jar:file:/E:/Applications/Study/JabRef/JabRef-2.10.jar!/plugins/net.sf.jabref.core/plugin.xml)
  - INSPIREfetcher (jar:file:/C:/Users/qxd/.jabref/plugins/INSPIREfetcher-0.3.jar!/plugin.xml)
  - adsfetcher (jar:file:/C:/Users/qxd/.jabref/plugins/ADSFetcher-0.4.jar!/plugin.xml)
  - arxivrss (jar:file:/C:/Users/qxd/.jabref/plugins/arxivrss-0.5.jar!/plugin.xml)
  - org.bibsonomy.plugin.jabref (jar:file:/C:/Users/qxd/.jabref/plugins/jabref-bibsonomy-plugin-2.5.2-bin.jar!/plugin.xml)
  - net.sf.jabrefprrvp (jar:file:/C:/Users/qxd/.jabref/plugins/net.sf.jabrefprrvp.jar!/plugin.xml)
  - net.sf.jabref.export.misq (jar:file:/E:/Applications/Study/JabRef/JabRef-2.10.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)

Sep 09, 2015 9:54:25 AM net.sf.jabref.Globals logger
INFO: Opening: F:\References\Archive\Archive.bib
Sep 09, 2015 9:54:30 AM net.sf.jabref.Globals logger
INFO: Could not get key binding for "Open folder"
Sep 09, 2015 9:54:36 AM org.bibsonomy.rest.RestProperties getInstance
WARNING: unable to initialize jndi context
Sep 09, 2015 9:54:36 AM org.bibsonomy.rest.RestProperties getInstance
INFO: reading config file 'RestConfig.cfg' from classloader -> nowhere (not found)
```

***Output***
```
Found 8 plugin(s):
  - adssearch (jar:file:/C:/Users/qxd/.jabref/plugins/ADSsearch-0.1.jar!/plugin.xml)
  - net.sf.jabref.core (jar:file:/E:/Applications/Study/JabRef/JabRef-2.10.jar!/plugins/net.sf.jabref.core/plugin.xml)
  - INSPIREfetcher (jar:file:/C:/Users/qxd/.jabref/plugins/INSPIREfetcher-0.3.jar!/plugin.xml)
  - adsfetcher (jar:file:/C:/Users/qxd/.jabref/plugins/ADSFetcher-0.4.jar!/plugin.xml)
  - arxivrss (jar:file:/C:/Users/qxd/.jabref/plugins/arxivrss-0.5.jar!/plugin.xml)
  - org.bibsonomy.plugin.jabref (jar:file:/C:/Users/qxd/.jabref/plugins/jabref-bibsonomy-plugin-2.5.2-bin.jar!/plugin.xml)
  - net.sf.jabrefprrvp (jar:file:/C:/Users/qxd/.jabref/plugins/net.sf.jabrefprrvp.jar!/plugin.xml)
  - net.sf.jabref.export.misq (jar:file:/E:/Applications/Study/JabRef/JabRef-2.10.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)

Opening: F:\References\Archive\Archive.bib
Could not get key binding for "Open folder"
unable to initialize jndi context
reading config file 'RestConfig.cfg' from classloader -> nowhere (not found)
```

***Exceptions***
```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchFieldError: ADDED_ENTRY
	at org.bibsonomy.plugin.jabref.listener.PluginDataBaseChangeListener.databaseChanged(PluginDataBaseChangeListener.java:57)
	at net.sf.jabref.BibtexDatabase.fireDatabaseChanged(BibtexDatabase.java:591)
	at net.sf.jabref.BibtexDatabase.insertEntry(BibtexDatabase.java:234)
	at net.sf.jabref.BasePanel.newEntry(BasePanel.java:1802)
	at net.sf.jabref.JabRefFrame$NewEntryAction.actionPerformed(JabRefFrame.java:1220)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
error setting key: java.lang.NoSuchFieldError: ADDED_ENTRY
error setting key: java.lang.NoSuchFieldError: ADDED_ENTRY
error setting key: java.lang.NoSuchFieldError: ADDED_ENTRY
```

**Comment by i2000s** [comment] 2015-09-09 16:17
Sorry, I should use this account to post this issue...

**Comment by koppor** [comment] 2015-09-09 18:09
Please try the current development build: https://circle-artifacts.com/gh/JabRef/jabref/456/artifacts/0/home/ubuntu/jabref/build/releases/JabRefSetup.exe

**Comment by matthiasgeiger** [comment] 2015-09-09 18:10
And one other suggestion: This seems to be caused by the bibsonomy plugin you are using. Please try to uninstall this plugin and check whether JabRef is working without it.

**Comment by i2000s** [comment] 2015-09-09 18:54
I had tried disabling the bibsonomy, but still got the `Could not get key binding for "Open folder" ` error. Seems JabRef 2.9.2 works on my machine. I will try the new build later.

**Comment by matthiasgeiger** [comment] 2015-09-09 19:10
The missing key-binding should not crash the program - or disable editing. 
Is editing possible without the bibsonomy plugin?

**Comment by i2000s** [comment] 2015-09-09 19:15
When I click the bibtex key generator, it does not do anything even with the bibsonomy deleted. 

Let me know what else I can test. But, right now, I am on JabRef 2.9.2 to get some work done. After work, I can do some trials.

**Comment by matthiasgeiger** [comment] 2015-09-09 19:42
Okay.... there seem to be various issues here... 
Above you described the following: 
> JabRef does not allow me to add new entries or even edit existing entries. Whenever I tried to add new entry or tried to edit an existing entries, there popped out an "error: added_entry".

Is this solved by disabling the bibsonomy plugin?

**Comment by i2000s** [comment] 2015-09-10 04:45
@matthiasgeiger So, I just uninstalled JabRef 2.9.2 and reinstalled JabRef 2.10, seems everything works without the bibsonomy plugin. That is I can add new entries and edit. However, the 
```
Could not get key binding for "Open folder"
```
error persists. I will test the new build next.

**Comment by i2000s** [comment] 2015-09-10 04:56
@koppor I am using the setup you gave to me, and below are the error console output:

***Exceptions***
```
Sep 09, 2015 10:47:34 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "MIS Quarterly" for locale en
Sep 09, 2015 10:47:35 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: D:\Documents\User\晓东的文档\Private\Documents\oversea\Live_in_north_America\UNM\CQuICWebsites\CQuICmembers.bib
Sep 09, 2015 10:47:35 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: F:\References\Archive\Archive.bib
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
Sep 09, 2015 10:47:37 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Open %0 file" for locale en
```

***Log***
```
Sep 09, 2015 10:47:35 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: D:\Documents\User\晓东的文档\Private\Documents\oversea\Live_in_north_America\UNM\CQuICWebsites\CQuICmembers.bib
Sep 09, 2015 10:47:35 PM net.sf.jabref.JabRef openBibFile
INFO: Opening: F:\References\Archive\Archive.bib
```

No output showing up. 

While I was adding a new entry, another warning showed up:
***Exception***
```
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
Sep 09, 2015 10:51:13 PM net.sf.jabref.logic.l10n.Localization lang
WARNING: Warning: could not get translation for "Normalize to BibTeX name format" for locale en
```

All above is without the bibsonomy plugin installed. I don't think I have time to test the plugin on my machine for now, but hopefully this is helpful for your future development of a better ***JabRef***! Let me know if there is a through solution for this problem.

**Comment by matthiasgeiger** [comment] 2015-09-10 07:05
Thanks again for taking the time to test it again!

We are aware of the "Warnings" regarding the missing translations - those will be fixed for the next major release.

As your main problem seems to be caused by the bibsonomy plugin you might report your bug at the bugtracker of the bibsonomy team: https://bitbucket.org/bibsonomy/bibsonomy-jabref-plugin/issues?status=new&status=open

As we cannot fix the (potential) bug in the plug-in I close this issue here.

**Closed by matthiasgeiger** 2015-09-10 07:05 UTC

**Comment by koppor** [comment] 2015-09-10 07:36
As we dropped plugin support, I asked them to port the plugin to JabRef at https://bitbucket.org/bibsonomy/bibsonomy-jabref-plugin/issues/1912/integrate-code-in-jabref-master-branch

**Comment by i2000s** [comment] 2015-09-10 07:38
Thanks! I have also requested an issue to their team.

**Comment by koppor** [comment] 2019-12-22 23:22
Short update: We were trying to integrate it in 2016, but is was very complex. Meanwhile, we migrated our UI to a more modern technology (JavaFX), which requires a rewrite of the code again.

If someone wants to take over, the starting point could be https://github.com/JabRef/jabref/pull/2157.
