### ISSUE TITLE
Citation Key Generator not respected

### ISSUE THREAD

**Issue by DOFfactory** [JabRef/jabref#7069] opened 2020-11-03 11:24 UTC
JabRef 5.2--2020-10-29--e08ac4e
Windows 10 10.0 amd64 
Java 14.0.2

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Define a citation key generator in Preferences
2. Generate new citekey
3. missing hyphens

![image](https://user-images.githubusercontent.com/10846169/97979437-772ff700-1dcf-11eb-8462-69f4a85b5444.png)

**Comment by Siedlerchr** [comment] 2020-11-03 11:56
Duplicate of #7035 
You need to remove the hypen from the unwanted character list under Settings -> Citation key generator
![grafik](https://user-images.githubusercontent.com/320228/97982386-ff180000-1dd3-11eb-9c89-97ccbe5314fe.png)

**Closed by Siedlerchr** 2020-11-03 11:56 UTC

**Comment by DOFfactory** [comment] 2020-11-03 12:04
Oh, thanks. That was the solution! 👍
