### ISSUE TITLE
proxy authentication support

### ISSUE THREAD

**Issue by tolot27** [JabRef/jabref#388] opened 2015-11-25 07:25 UTC
There is still no support for proxy authentication. Unfortunately, username and password can not be specified by command line parameters or preferences (network tab) like it is possible for the proxy host and port (-Dhttp.proxyHost=).

The reason is that the Authenticator class has to be used.

A possible implementation is described here: http://memorynotfound.com/configure-http-proxy-settings-java.

**Comment by koppor** [comment] 2015-11-25 08:33
Would it be possible that you fork JabRef, create a patch and create a pull request?

![I can haz pull request](https://raw.githubusercontent.com/dscho/images/master/i-can-haz-pull-request.png)

Image source: https://github.com/dscho/images

**Comment by tolot27** [comment] 2015-11-27 07:28
I already tried this but gradle is a nightmare behind a proxy.

After getting it to work fetching https://services.gradle.org/distributions/gradle-2.9-all.zip by providing gradle.properties with proxy settings, it still fails to fetch the jars.
In the debug log I can see that it cannot fetch shadow-1.2.2.jar from http://maven.ej-technologies.com/repository/com/github/jengelman/gradle/plugins/shadow/1.2.2/shadow-1.2.2.jar.
It is quite obvious because there is no github directory in http://maven.ej-technologies.com/repository/com.

How to proceed?

**Comment by tolot27** [comment] 2015-11-27 07:30
Is github a virtual folder or plugin in maven which just does not work for the moment at http://maven.ej-technologies.com?

**Comment by tolot27** [comment] 2015-11-27 07:57
If I switch to another maven repository (i. e. http://repo.spring.io/libs-release-remote/), `shadow-1.2.2.jar` gets downloaded but then other plugins fail to download. There seem to be no cache because switching back to the ej-technologies repro again fails on shadow.jar.
Thats quite frustrating and a waste of time.

**Comment by matthiasgeiger** [comment] 2015-11-27 08:19
Sorry... but I cannot reproduce this... after clearing all my gradle caches to force gradle to download the libs again the following is executed:
```
$ gradlew build
Download http://maven.ej-technologies.com/repository/com/install4j/gradle-plugin/6.0/gradle-plugin-6.0.pom
Download https://plugins.gradle.org/m2/com/github/jengelman/gradle/plugins/shadow/1.2.2/shadow-1.2.2.pom
Download https://plugins.gradle.org/m2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.4.0x/coveralls-gradle-plugin-2.4.0x.pom
[...]
Download http://maven.ej-technologies.com/repository/com/install4j/gradle-plugin/6.0/gradle-plugin-6.0.jar
[...]
```
All plugins are downloaded from `https://plugins.gradle.org/m2/...` except for the install4j plugin which is downloaded from `http://maven.ej-technologies.com`

So I do not understand why this is different for you...

**Comment by tolot27** [comment] 2015-11-30 08:24
The change works well so far, but is currently limited to VM args (`-Dhttp.proxyUser`and `-Dhttp.proxyPassword`).

Interestingly, I found the following code section in `JabRef.jar`:

```java
            // currently, the following cannot be configured
            if (prefs.get("proxyUsername") != null) {
                System.setProperty("http.proxyUser", prefs.get("proxyUsername"));
                System.setProperty("http.proxyPassword", prefs.get("proxyPassword"));
            }
```

Shall we extend the configuration and GUI to include proxyUsername and proxyPassword or just support a single proxy URL aka proxyUsername:proxyPassword@proxyHost:proxyPort?

**Comment by simonharrer** [comment] 2015-11-30 08:50
- I think the effort to parse a single proxy URL correctly without bugs is much larger than just letting the user stating the four different parts separately. But the user should be able to change these things in the GUI as well next to the other proxy settings. 
- Your commit you referenced looks very strange, I think you use different line endings, causing the file to be recreated. https://github.com/tolot27/jabref/commit/28c2c06273e0677d9ab9dc557e5e7469cc863f45

**Comment by tolot27** [comment] 2015-11-30 08:53
I've discovered the same problem with the commit and reverted it. Commiting it again with git rather than with Eclipse worked well.

**Comment by tolot27** [comment] 2015-11-30 08:55
What about password encryption if it is stored in the configuration settings (or exported)? Do we care about it? I expect so and assume that's the reason why there are currently no settings for proxy authentication.

**Comment by tolot27** [comment] 2015-11-30 08:59
Regarding to the proxy URL: The scheme is fixed: `@` separates the user/password from the proxy host and port. `:` separates the user name from the password as well as the proxy host from its port. Sometimes a protocol prefix is provided which is always separated by `://`.

**Comment by simonharrer** [comment] 2015-11-30 08:59
Hm, good point. Personally, I would just make a note in the GUI that passwords are stored in the preferences. Correctly encrypting and decrypting passwords is out of scope for JabRef, I think. In addition, we could add the option that a user could pass the password as a environment parameter, if necessary.

**Comment by simonharrer** [comment] 2015-11-30 09:00
I understand that the scheme is fixed, but parsing it without errors require a huge amount of testing as users can input anything, with feedback what went wrong.

**Comment by tolot27** [comment] 2015-11-30 09:02
Parsing and checking for correct input is always a problem. I don't see any checks for proxy host and port settings as well (`NetworkTab.java`) .... So you already don't care about it.

**Comment by simonharrer** [comment] 2015-11-30 09:06
See `NetworkTab.validateSettings`, there is a check for both host name and port.

**Comment by tolot27** [comment] 2015-11-30 09:25
Okay, had overseen this, sorry.

**Comment by tolot27** [comment] 2015-11-30 12:13
I cannot see something like a preference change listener. Is there any? The problem is that a change in the proxy configuration currently requires a restart of JabRef.
Indeed, I can change the default Authenticator in the NetworkTab or JabRefPreferences class. But I really like keeping config and processing separate. Any ideas?

**Closed** 2015-11-30 21:13 UTC
Labels: asking-for-a-pull-request, feature
