### ISSUE TITLE
Entry preview as tab: Full change only takes effect after restart of program

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#5464] opened 2019-10-17 09:15 UTC
JabRef 5.0.0-dev--2019-10-17----e81d58c51
Windows 10 10.0 amd64 
Java 12.0.2

The entry preview can now also be displayed as a separate tab in the entry editor (see https://github.com/JabRef/jabref/issues/5244). To achieve this, you do the following: Options -> Preferences -> Entry preview -> Show preview as tab in entry editor -> Save

After saving, the entry preview is shown as a separate tab. BUT it is also kept as part of the entry editor itself (as introduced by https://github.com/JabRef/jabref/pull/4976). Only after restarting JabRef, the entry preview is ONLY available as tab (and no longer in the entry editor window itself).
Similarly, if you deselect "Show preview as tab in entry editor" and save this option, no entry preview at all is shown. Only after restarting JabRef, the entry preview is again part of the entry editor (not as a separate tab, but as part of the editor itself).

This behaviour is unexpected. A simple fix would be to alert the user, that the full change to the user interface is only achieved after restarting JabRef when making changes to the "Show preview as tab in entry editor" option.

**Comment by gitclone-510** [comment] 2019-10-17 15:43
Hey , hows it going? I would like to work on this issue if nobody has picked it up yet

**Comment by felipevicencion** [comment] 2020-02-26 11:05
Hey, is anyone still working on this? If not, I'd like to try to tackle this issue.

**Comment by AEgit** [comment] 2020-12-10 10:33
The issue persists in:
JabRef 5.2--2020-12-09--d1fb9e2
Windows 10 10.0 amd64 
Java 14.0.2

**Comment by MrGhabi** [comment] 2021-05-08 09:13
Hello, I have reproduced the issue. Could I have a try to fix it?

**Comment by ThiloteE** [comment] 2022-04-11 10:30
I cannot reproduce this anymore in one of the newer development versions:

JabRef 5.6--2022-04-10--93177fa
Windows 10 10.0 amd64 
Java 17.0.2 
JavaFX 18+12

1. Do: `Options -> Preferences -> Entry preview -> Show preview as tab in entry editor -> Save`

   What happens:

- Entry editor closes itself.
- When restarting the entry editor by double clicking on an entry (NOT restarting JabRef), the entry preview is shown in a new tab.

2. Disable `Options -> Preferences -> Entry preview -> Show preview as tab in entry editor -> Save`

   What happens:
   
   - Entry editor closes itself
   - Full change takes effect after reopening the entry editor. (e.g. by double clicking an entry). Restart of JabRef is not necessary.
   
@AEgit good enough, no? :-)

Closing this issue. Feel free to open if you think this has not been adequately solved.

**Closed by ThiloteE** 2022-04-11 10:30 UTC
Labels: type: enhancement, entry-preview, good first issue

**Comment by AEgit** [comment] 2022-04-11 13:13
JabRef 5.6--2022-04-08--a6489cb
Windows 10 10.0 amd64 
Java 17.0.2 
JavaFX 18+12

I can confirm this issue has been fixed in the latest dev version of JabRef. The behaviour is as described in https://github.com/JabRef/jabref/issues/5464#issuecomment-1094883425

Well done!
