### ISSUE TITLE
Automatic Bug Report - 20180102081210

### ISSUE THREAD

**Issue by a3zzat** [JabRef/jabref#3593] opened 2018-01-02 06:14 UTC
JabRef 4.1
Windows 10 10.0 amd64 
Java 1.8.0_151

Steps to reproduce:

1. ...
2. ...
3. ...

Paste your log details here.
<details>
<summary>Detail information:</summary>

```
Opening: D:\new4.bib
Info cannot be found
org.jabref.logic.importer.FetcherException: Error while retrieving data from chimbori.com: @comment{
Error fetching metadata for ISBN 9789004319288. Check if it is valid by searching at Amazon.com.
AWS.InvalidParameterValue : 9789004319288 is not a valid value for ItemId. Please change this value and retry your request.
}
	at org.jabref.logic.importer.fetcher.IsbnViaChimboriFetcher.performSearchById(IsbnViaChimboriFetcher.java:58)
	at org.jabref.logic.importer.fetcher.IsbnFetcher.performSearchById(IsbnFetcher.java:49)
	at org.jabref.gui.mergeentries.FetchAndMergeWorker.doInBackground(FetchAndMergeWorker.java:46)
	at org.jabref.gui.mergeentries.FetchAndMergeWorker.doInBackground(FetchAndMergeWorker.java:21)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Info cannot be found
org.jabref.logic.importer.FetcherException: Error while retrieving data from chimbori.com: @comment{
Error fetching metadata for ISBN 9789004319288. Check if it is valid by searching at Amazon.com.
AWS.InvalidParameterValue : 9789004319288 is not a valid value for ItemId. Please change this value and retry your request.
}
	at org.jabref.logic.importer.fetcher.IsbnViaChimboriFetcher.performSearchById(IsbnViaChimboriFetcher.java:58)
	at org.jabref.logic.importer.fetcher.IsbnFetcher.performSearchById(IsbnFetcher.java:49)
	at org.jabref.gui.mergeentries.FetchAndMergeWorker.doInBackground(FetchAndMergeWorker.java:46)
	at org.jabref.gui.mergeentries.FetchAndMergeWorker.doInBackground(FetchAndMergeWorker.java:21)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Fix SSL exceptions by accepting ALL certificates
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: [-2147483648, 15) is not a valid range within [0, 15)
	at org.reactfx.util.Lists.checkRange(Lists.java:128)
	at org.reactfx.util.Lists.checkRange(Lists.java:123)
	at org.reactfx.collection.MemoizationListImpl.forget(MemoizationList.java:184)
	at org.fxmisc.flowless.CellListManager.cropTo(CellListManager.java:82)
	at org.fxmisc.flowless.CellPositioner.cropTo(CellPositioner.java:29)
	at org.fxmisc.flowless.Navigator.cropToNeighborhoodOf(Navigator.java:227)
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:200)
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:129)
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85)
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene.preferredSize(Scene.java:1646)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58)
	at javafx.embed.swing.JFXPanel.lambda$addNotify$49(JFXPanel.java:799)
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

```

</details>

**Comment by tobiasdiez** [comment] 2018-01-02 10:47
Duplicate of #3532. (At least if you mean the second warning about index out of bounds)

**Closed by tobiasdiez** 2018-01-02 10:47 UTC
