### ISSUE TITLE
Data not being saved.

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#2906] opened 2017-06-13 02:54 UTC
JabRef version 

JabRef 4.0.0-dev--snapshot--2017-06-11--master--c711a7fdf
Linux 4.10.0-22-generic amd64 
Java 1.8.0_131

Steps to reproduce:

1. open edit screen.  
2. find "biblatex source" tab (horrible dropdown, much mouse movement and two clicks required)
3. edit data
4. move to another record, or move to the "Required fields" screen, and the edits to "biblatex source" are lost.

**Comment by tobiasdiez** [comment] 2017-06-13 07:00
Isn't this a duplicate of https://github.com/JabRef/jabref/issues/2888?

**Comment by wujastyk** [comment] 2017-06-13 14:26
yes, it is.  My apologies for not spotting that.  I did a search, but
obviously not carefully enough.

​
--
Professor Dominik Wujastyk <http://ualberta.academia.edu/DominikWujastyk>
​,​

Singhmar Chair in Classical Indian Society and Polity
​,​

Department of History and Classics <http://historyandclassics.ualberta.ca/>
​,​
University of Alberta, Canada
​.​

South Asia at the U of A:

​sas.ualberta.ca​
​​

**Closed** 2017-06-13 16:01 UTC
Labels: duplicate
