### ISSUE TITLE
"Add group" doesn't check for existing groups

### ISSUE THREAD

**Issue by buhtz** [JabRef/jabref#2695] opened 2017-03-31 08:01 UTC
Using JabRef 3.8.1 from Debian unstable. Currently it is not possible to have two or more sub-groups with the same name but different parents. This depends on the way how JabRef store group informations in the bib-file I think.

The "add group" or "add sub-group" should check If the new group still exist and warn the user about that. Currently it doesn't happen.

This is related to http://discourse.jabref.org/t/sub-groups-with-different-parents-but-the-same-name/549.

**Comment by Siedlerchr** [comment] 2017-03-31 09:00
Thanks for reporting. As the group functionality undergoes a major overhaul with the new GUI technology, we already have an issue for collecting problems and group related enhancements 
#2599  
Therefore I would close this issue here and add it to the other issue.

**Closed by Siedlerchr** 2017-03-31 09:00 UTC

**Comment by tobiasdiez** [comment] 2017-03-31 09:22
It is indeed a duplicate of #1495
