### ISSUE TITLE
About Jabref: Wrong encoding

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#1248] opened 2016-04-19 18:37 UTC
JabRef version 3.3 on Windows 10, German localization

Steps to reproduce:

1. Help | About Jabref
2. Authors (Contributors): Wrong encoding. Umlaut etc.

**Comment by Siedlerchr** [comment] 2016-04-19 18:40
Duplicate of #1178.
Problem is known, but it is a problem of the external build tool. See the issue above for details.

**Closed** 2016-04-19 19:02 UTC
Labels: duplicate
