### ISSUE TITLE
Keyboard paste does not work on MacOS

### ISSUE THREAD

**Issue by homocomputeris** [JabRef/jabref#6466] opened 2020-05-11 12:54 UTC
JabRef 5.0--2020-03-06--2e6f433 on Mac OS X 10.15.4 x86_64 Java 13.0.2

- [ ] I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Copy text in any other application
2. Try to paste it with Command-V
3. Nothing happens
4. Right click to paste via context menu

**Comment by AEgit** [comment] 2020-05-11 13:39
Possible duplicate of https://github.com/JabRef/jabref/issues/6293 (the fix was reverted, so the issue has been re-opened).

**Comment by homocomputeris** [comment] 2020-05-11 14:17
But that one says that Ctrl-V does work. On Mac Command-V does _not_ work

**Comment by Siedlerchr** [comment] 2020-05-11 14:18
@homocomputeris  It would be nice if you could check with  @Gena928 
https://github.com/JabRef/jabref/pull/6419#issuecomment-626393617

**Comment by homocomputeris** [comment] 2020-05-11 14:30
In my case the Paste from the context menu works, and there is no double paste

**Comment by Gena928** [comment] 2020-05-11 14:33
@homocomputeris 
but Ctrl+V does not work, correct?

**Comment by homocomputeris** [comment] 2020-05-11 14:37
@Gena928 No, neither Command-V nor Control-V (I've checked just in case).

**Comment by Gena928** [comment] 2020-05-11 14:56
@homocomputeris 
I just [recorded small video on my google drive](https://drive.google.com/open?id=15rnT4D5echGcsXwy-6gPynH5f262lmBB), where I try to reproduce the error. Looks like it works on my computer, and not works on yours.

Can you please install Java 14 and try to repeat the issue?

**Comment by AEgit** [comment] 2020-05-11 15:02
Note, that @homocomputeris was not using the latest development version when posting the issue. I do not know, whether that explains the difference but wanted to make both of you aware of it.

**Comment by homocomputeris** [comment] 2020-05-11 16:07
> Can you please install Java 14 and try to repeat the issue?

Java is bundled with Jabref, how do I use a newer version?

**Comment by AEgit** [comment] 2020-05-11 16:08
Download the current dev version from here:
https://builds.jabref.org/master/

Note, that since this is a dev version you should ALWAYS have a backup of your JabRef database.

**Comment by homocomputeris** [comment] 2020-05-11 16:16
I've downloaded the portable
```
JabRef 5.1--2020-05-11--754c7ee
Mac OS X 10.15.4 x86_64 
Java 14.0.1
```

1. Command-V does not work
2. Edit - Paste does not work
3. Right-click - Paste works

**Comment by AEgit** [comment] 2020-05-11 16:19
A random idea - did you originally also try the portable version? If yes, @Gena928 did you use the portable version as well? If not, maybe the issue is restricted to the portable version.

Sorry, cannot help more (I don't have a Mac).

**Comment by Gena928** [comment] 2020-05-11 16:20
I use full version. Never used portable so far. 
I'll download it and try.

**Comment by homocomputeris** [comment] 2020-05-11 16:23
@AEgit I use the brew cask version, whatever it is.

I have found the reason: I use US Dvorak. Jabref does not recognize Dvorak shortcuts, while all the other applications do. QWERTY shortcuts (that is, Cmd-J in Dvorak which is the same keys as Cmd-C in QWERTY) work

**Comment by AEgit** [comment] 2020-05-11 16:24
@homocomputeris : Cheers, well done in narrowing done the issue. So it comes down to the keyboard layout.

**Comment by Gena928** [comment] 2020-05-11 16:47
@homocomputeris,
may I ask you to insert a few records in your database?
we have another issue [No.6419 ](https://github.com/JabRef/jabref/pull/6419#issuecomment-626393617), where JabRef inserts duplicates. Please, if possible:
- open [Google Scholar site](https://scholar.google.com/scholar?hl=en&as_sdt=1%2C14&q=nlp+healthcare&btnG=)
- copy 2-3 BibTex entries, one by one from your browser and paste to JabRef.
- first one should be OK, the second and third should produce duplicates, as [stated here](https://github.com/JabRef/jabref/issues/4699#issuecomment-482848830)

Are there any duplicates in your database?

**Comment by homocomputeris** [comment] 2020-05-11 17:47
>  By default JabRef assumes ctrl+v and cmd+v for mac

When I change Paste to the Dvorak Ctrl-V, it writes Ctrl-PERIOD. However, it still accepts only Cmd-V in Qwerty (that is Cmd-J in Dvorak).

> Are there any duplicates in your database?
No, there is not. But pasting (and any other operation like opening menus and dialogues) takes about 5 seconds.

**Comment by Siedlerchr** [comment] 2020-05-11 17:49
After changing the keybindings you might need to restart jabref

**Comment by homocomputeris** [comment] 2020-05-12 12:15
I did.

**Comment by Siedlerchr** [comment] 2020-08-02 15:06
@homocomputeris  This should now be fixed in latest master
<kbd>cmd</kbd>+ <kbd>C</kbd> and <kbd>cmd</kbd>+ <kbd>V</kbd> should work now

**Comment by homocomputeris** [comment] 2020-08-02 20:47
@Siedlerchr It works for text in text fields. Thanks!

**Comment by Siedlerchr** [comment] 2020-08-02 21:25
For the paste button from the Menu, this issue is tracked here. There is a jdk/javafx bug which triggers events twice and thefore the buttons in the menu won't work on the maintable. Refs #6293

**Closed by Siedlerchr** 2020-08-02 21:25 UTC
Labels: status: waiting-for-customer-feedback

**Comment by homocomputeris** [comment] 2020-10-27 21:45
Keyboard shortcuts do not work once again
```
JabRef 5.1--2020-08-30--e023aa0
Mac OS X 10.15.7 x86_64 
Java 15
```

**Comment by Siedlerchr** [comment] 2020-10-28 06:59
They should work fine in the latest development version from builds.jabref.org/master
