### ISSUE TITLE
When mouse is over group title, inaccurate group description is displayed

### ISSUE THREAD

**Issue by psychelzh** [JabRef/jabref#3275] opened 2017-10-07 02:53 UTC
JabRef version `4.0` on  `Java 1.8.0_144`

I guess the group titles have a `mouseover` method, which displays the group descriptions. Unfortunately, they are a little bit messy here. For example, the following first screenshot suggests the description of **BART** group is **The articles about ....**, but in fact it should be **The Balloon Analogue Risk Task** (see the second screenshot).

![image](https://user-images.githubusercontent.com/13306020/31304117-4da53b18-ab4d-11e7-8879-31d1389bee3c.png)

![image](https://user-images.githubusercontent.com/13306020/31304129-9efc9f60-ab4d-11e7-92f6-0284a88d9695.png)

<details>

I do not know whether the logged details is relevant or not.
  <summary>Log File</summary>
  
  ```java
Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at org.jabref.gui.groups.GroupMatcher.matches(GroupMatcher.java:17)
	at org.jabref.gui.groups.GroupMatcher.matches(GroupMatcher.java:11)
	at org.jabref.gui.maintable.MainTable.matches(MainTable.java:545)
	at org.jabref.gui.maintable.MainTable.getCellRenderer(MainTable.java:247)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at org.jabref.gui.groups.GroupMatcher.matches(GroupMatcher.java:17)
	at org.jabref.gui.groups.GroupMatcher.matches(GroupMatcher.java:11)
	at org.jabref.gui.maintable.MainTable.matches(MainTable.java:545)
	at org.jabref.gui.maintable.MainTable.getCellRenderer(MainTable.java:247)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NullPointerException
	at org.jabref.gui.groups.GroupMatcher.matches(GroupMatcher.java:17)
	at org.jabref.gui.groups.GroupMatcher.matches(GroupMatcher.java:11)
	at org.jabref.gui.maintable.MainTable.matches(MainTable.java:545)
	at org.jabref.gui.maintable.MainTable.getCellRenderer(MainTable.java:247)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

  ```
</details>

**Comment by stefan-kolb** [comment] 2017-10-12 15:49
I cannot reproduce this issue, descriptions are displayed as expected.

Exceptions refer to `MainTable.java`:
```
    private boolean matches(int row, Matcher<BibEntry> m) {
        Optional<BibEntry> bibEntry = getBibEntry(row);

        if (bibEntry.isPresent()) {
            return m.matches(bibEntry.get());
        }
        return m.matches(null);
    }
```

Dunno why matches is called with null...

So `GroupMatcher.java` will obviously fail.
```
public class GroupMatcher implements Matcher<BibEntry> {

    public static final GroupMatcher INSTANCE = new GroupMatcher();

    @Override
    public boolean matches(BibEntry entry) {
        return entry.isGroupHit();
    }
}
```

**Comment by psychelzh** [comment] 2017-10-13 02:03
I guess it is because of one of my `.bib` file. When I switched to another one, everything is then okay.

But I really do not know that specific `.bib` file is problematic. Do you know of any tool to check it?

**Comment by lenhard** [comment] 2017-10-19 12:19
@psychelzh Could you please try out the version available here http://builds.jabref.org/fixNPE/ and let us know if it fixes the problem?

**Comment by psychelzh** [comment] 2017-10-19 13:19
Thanks. I have tested it. What I am more convinced is that I have got a corrupted copy of `.bib` database, because

1. It constantly shows that there is some modification to be saved, when, in fact, I did nothing but just opened it.
1. When it is opened, all of the opened databases will show inaccurate group description; but when I close it, other opened databases just turn normal and show the right description.

**Comment by tobiasdiez** [comment] 2017-10-20 01:42
@psychelzh If you want you can send your bib file to developers@jabref.org and we will have a look.

**Comment by psychelzh** [comment] 2017-10-20 01:48
OK, I am sending it.

**Comment by psychelzh** [comment] 2017-12-05 15:45
I have sent the copy of bibtex to you, and have you received it?

**Comment by Siedlerchr** [comment] 2018-08-29 16:27
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2018-08-29 16:27 UTC
Labels: bug, groups, ui
