### ISSUE TITLE
Jabref 4.0 beta 2 freeze after creating a new entry

### ISSUE THREAD

**Issue by zhaiyusci** [JabRef/jabref#3043] opened 2017-07-23 16:42 UTC
JabRef version 4.0 beta 2  on Linux Mint 18.2. 

After I create a new entry, the program freezes.

I also try this on JabRef 4.0.0 beta.  This problem does not happen. 

Steps to reproduce:

1. Open the downloaded jar file with `jave -jar JabRef-4.0-beta2.jar`.
2. Create a new file.
3. Create a new entry and click `Article`, for example.
4. The program freezes.  To exit, got to terminal pressing `Ctrl-C`.

Sorry for the poor English.

**Comment by lenhard** [comment] 2017-07-23 18:04
@zhaiyusci I think there is already and issue for this. It reads very much like a duplicate of #2963

Please have a look at the other issue. I'll close this one.

**Closed by lenhard** 2017-07-23 18:04 UTC
