### ISSUE TITLE
Support Citation File Format (CFF, yaml) as export format

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#10671] opened 2023-11-28 07:37 UTC
TLDR: JabRef has the functionality to import CFF (https://github.com/JabRef/jabref/issues/7945), but no functionality for export. This should be implemented.

JabRef should be able to parse Citation File Format (CFF) and export into it.

Links:

- General CFF information: https://citation-file-format.github.io/ 
- Mapping BibTeX and CFF: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#citing-something-other-than-software
- Python implementation of a converter: https://github.com/citation-file-format/cff-converter-python 
- Description of the BibTeX format: https://docs.jabref.org/advanced/fields

Implementation hints:

The export can either be done by Java code directly or creating `.layout` files.

## Export using `.layout` files:

See `yaml.*` in https://github.com/JabRef/jabref/tree/main/src/main/resources/resource/layout

Example: https://github.com/JabRef/jabref/blob/main/src/main/resources/resource/layout/yaml.layout

Documentation on .layout files: https://docs.jabref.org/collaborative-work/export/customexports

---

Acceptance criteria:

- At least `@article`  and `@inproceedings` need to be supported.

---

Note: If you dislike the .layout format, one can work on replacing that part of JabRef by Java templating engines. See https://github.com/koppor/jabref/issues/392 for details.

**Comment by Siedlerchr** [comment] 2023-11-28 08:10
Duplicate of https://github.com/JabRef/jabref/issues/10661

**Closed by Siedlerchr** 2023-11-28 08:10 UTC
Labels: good first issue
