### ISSUE TITLE
Rating colum has no header description

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#315] opened 2015-11-11 16:28 UTC
We should add a description here, especially since clicking inside the column always opens up the rating menu which is inconvenient when i just want to open the dit view of the entry which works for all other columns.

Two small columns next to rating also have no description and I don't even know what they do.

**Comment by koppor** [comment] 2015-11-11 22:18
The reason for directly changing the flags convenience for quick changing of flags and ratings. I fully agree that the columns should be labeled. As far as I remember, that seemed to be really difficult to achieve. Maybe postpone for #113?

**Comment by matthiasgeiger** [comment] 2015-11-12 08:32
The problem is not to place a header label, but the space required for this: E.g.  the column for flagging, "print status", etc. are only a few px wide - but a description would require far more space.
There is actually already the preference setting to "show one letter column headings" - which helps a bit ;-)

The best solution would be to show the "icon" of the column as header label (which should not be a problem with our new font based icon set) and provide a [tooltip when hovering over the column headers](http://docs.oracle.com/javase/tutorial/uiswing/components/table.html#headertooltip)

**Comment by matthiasgeiger** [comment] 2015-11-12 08:34
... and remove the mentioned prefs option :wink:

**Comment by oscargus** [comment] 2015-11-15 12:06
There is also a method setAlternativeDisplayName() in BibtexSingleField (in BibTexFields) which should do the trick (that is currently unused).

**Comment by matthiasgeiger** [comment] 2015-12-15 10:41
Implemented with #452 - changes are available now in current [development builds](http://builds.jabref.org/master/) and will be released with 3.1

**Closed by matthiasgeiger** 2015-12-15 10:41 UTC
Labels: enhancement, ui
