### ISSUE TITLE
docbook export skips species names that are in braces

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#3838] opened 2018-03-12 11:10 UTC
- [ ] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.1

Steps to reproduce:

1. 
this is the citation:

> Article (AW06) Audsley, N. & Weaver, R. J. Analysis of peptides in the brain and corpora cardiaca-corpora allata of the honey bee, {A}pis mellifera using MALDI-TOF mass spectrometry. Peptides, 2006, 27, 512-20.

2. Using a line like this
`java -jar C:\Programme\JabRe4.1\JabRef-4.1.jar -o cha13addBiB.xml,docbook -n true addkap13.bib`

3. I get

> <biblioentry xreflabel="Audsley und Weaver (2006)" xml:id="AW06">
>    <authorgroup>
>        <author><personname><firstname>N.</firstname><surname>Audsley</surname></personname></author>
>        <author><personname><firstname>R. J.</firstname><surname>Weaver</surname></personname></author> 
> 
>    </authorgroup>
>    <citetitle pubwork="article">Analysis of peptides in the brain and corpora cardiaca-corpora allata of the honey bee, mellifera using MALDI-TOF mass spectrometry.</citetitle>
>    <citetitle pubwork="journal">Peptides</citetitle>
> 
>    <volumenum>27</volumenum> 
> 
>    <artpagenums>512–20</artpagenums> 
>    <pubdate>2006</pubdate>  
> 
> 
>    </abstract>
> </biblioentry>

Note that the {A}pis is left out. This is valid not only for this example, but about 50% of my citations are errorneous.

**Comment by stefan-kolb** [comment] 2018-04-16 16:06
@johannes-manner Maybe you can help here, as you just worked on some exporters.

**Comment by johannes-manner** [comment] 2018-05-28 15:07
I tried to reproduce the bug, but I get a different xml-result.
Please share the .bib and .xml files with me for a further investigation of this bug.

**Comment by bernhard-kleine** [comment] 2018-05-28 17:49
I have tested this again and still some instances of braced e.g.
Drosophila are removed.

I used the following line to start the program

java -jar C:\Programme\JabRef4.2Test\JabRef-4.2Test.jar -o
testbraces.xml,docbook -n k -n <d h~hB g> k -n true testbraces.bib

JabRef4.2Test contains the files in the image
In that period I downloaded the following jabref install files:


.bib file and .xml file are attached.
Thanks for looking into this.

Bernhard
Am 28.05.2018 um 17:07 schrieb Johannes Manner:
> I tried to reproduce the bug, but I get a different xml-result.
> Please share the .bib and .xml files with me for a further investigation of this bug. 
>

-- 
spitzhalde9
D-79853 lenzkirch
bernhard.kleine@gmx.net
www.b-kleine.com, www.urseetal.net
-
thunderbird mit enigmail
GPG schlüssel: D5257409
fingerprint:
08 B7 F8 70 22 7A FC C1 15 49 CA A6 C7 6F A0 2E D5 25 74 09

**Comment by bernhard-kleine** [comment] 2018-05-29 10:38
Sorry, that I didnot take in account. The two screenshots were also omitted. I can sent them when they are neccessary. The offending lack of Drosophila is obvious in the title of paper Baggerman et al., Choi et al, Clark et al. e.g. In Dai et al. we are missing Manduca. These were obvious be checking only a small number. Not any instance of Drosophila was removed, not even those in braces (I added braces to some instances in the .bib abstracts, but those braces in the title resulted in missing words in the xml.
[testbraces.bib.txt](https://github.com/JabRef/jabref/files/2047811/testbraces.bib.txt)
[testbraces.xml.txt](https://github.com/JabRef/jabref/files/2047816/testbraces.xml.txt)

Bernhard

**Comment by bernhard-kleine** [comment] 2018-06-01 16:00
@tobiasdiez anything missing?

**Comment by bernhard-kleine** [comment] 2018-08-02 15:16
Did you manage some progress?

**Comment by tobiasdiez** [comment] 2018-08-02 15:29
@bernhard-kleine please don't post such "ping" messages because they only add unnecessary noise. Usually, you can see if there was any progress by looking at the linked pullrequests/other issues (in this case #4108 which, however, is not yet in a workable state). Please also respect that we cannot fix every bug in a timely fashion. As you know, everybody involved works on JabRef in their freetime!

**Comment by tobiasdiez** [comment] 2019-03-27 14:39
Thanks to @johannes-manner this should be fixed in the latest development version. Could you please check the build from http://builds.jabref.org/master/. Thanks! Please remember to make a backup of your library before trying-out this version.

**Closed by tobiasdiez** 2019-03-27 14:39 UTC
Labels: bug, export / save
