### ISSUE TITLE
Copy key and link doesn't copy anything

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#2983] opened 2017-07-09 06:29 UTC
If I put the cursor on an entry and run "copy BibTex key and link" with either the mouse menu or the keyboard shortcut, nothing is put into the clipboard

JabRef 4.0.0-dev--snapshot--2017-07-07--master--eaf53f75d
Windows 7 6.1 amd64 
Java 1.8.0_131

**Comment by Siedlerchr** [comment] 2017-07-09 15:30
Confirmed

**Comment by Siedlerchr** [comment] 2017-07-09 18:49
Seems like a bug with the javafx clipboard.  @tobiasdiez  any idea on this?

Maybe we need to still use a swing/awt hack?
http://elliotth.blogspot.de/2005/01/copying-html-to-clipboard-from-java.html

**Comment by tobiasdiez** [comment] 2017-07-09 19:38
@jhshinn do you have an idea why this bug occurs? (The recent changes in https://github.com/JabRef/jabref/pull/2952 are probably the source for this problem.)

**Comment by jhshinn** [comment] 2017-07-10 00:26
@tobiasdiez I'm using 4.0beta with the revision #2952 under Windonws 10 at the moment, and the function works perfectly with both the shortcut key and the mouse pop-up menu. I just guess that the javafx revision may collide with other revisions made between 4.0beta and dev-snapshot mentioned above. I hope this helps you.
@Siedlerchr Just for your information. As I mentioned in the commented-out code as invoking PR, the swing/awt method only works under Mac, not under Windows 10 and Ubuntu 16.04.

**Comment by Siedlerchr** [comment] 2017-07-10 09:21
Okay, thanks for the clarification.  As you are saying, you still use the 4.0 beta, can you tell us which corresponding java version you are using? Just to narrow the problem a bit down. 
I currently use:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

```

https://github.com/JabRef/jabref/commit/37dc46e43c9ed6b65ab05a21b9ef9864aff20e4a

**Comment by jhshinn** [comment] 2017-07-10 13:06
@Siedlerchr It seems that I'm using the same as you are. My version is as below.
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

FYI, I had manually tested the revision using 4.0beta before invoking PR, because the dev-code did not work properly under Ubuntu 16.04. (I could not edit the entry.)

**Comment by tobiasdiez** [comment] 2017-10-20 09:04
I can reproduce this problem on Windows 10 with Java 1.8.0.152. The code is correct as far as I can see and debugging (even the internal javafx code) didn't reveal any problems (according to java everything is put successfully into the clipboard).

**Comment by jhshinn** [comment] 2017-10-24 00:23
The function "copy BibTex key and link" seems to work well under below circumstatnces.
```
JabRef 4.0
Windows 10 10.0 amd64 
Java 1.8.0_151
```
I could paste the hyperlink to the new-message window of gmail.
I've tested all of the three ways to copy

- menu bar
- shortcut key
- mouse pop-up menu

**Comment by lenhard** [comment] 2018-01-17 16:07
So do I understand this thread correctly? The function is actually working? If yes, then we can close this.

**Comment by Siedlerchr** [comment] 2018-01-17 16:23
Yes, it works also in the latest dev version, I could paste it succesfully into my gmail. As @jhshinn notes, seems to work only for certain applications, 

![grafik](https://user-images.githubusercontent.com/320228/35053638-f99e44d4-fbaa-11e7-8425-5e4e0feafd9b.png)

**Closed by Siedlerchr** 2018-01-17 16:23 UTC
Labels: bug

**Comment by koppor** [comment] 2018-04-04 07:57
Refs https://github.com/JabRef/jabref/issues/549#issuecomment-166269276
