### ISSUE TITLE
 Cursor periodically bounces to top of comment window

### ISSUE THREAD

**Issue by notuntoward** [JabRef/jabref#6460] opened 2020-05-10 20:49 UTC
The cursor unpredictably bounces from the spot I'm typing in the comment window to the comment window top (upper left hand corner).  Sometimes, if I have the preview showing, the bouncing seems to happen when the preview window refreshes.

But the bouncing happens whether or not the preview window is visible.

JabRef 5.1--2020-05-08--40f908f
Windows 10 10.0 amd64 
Java 14.0.1

**Comment by AEgit** [comment] 2020-05-10 22:24
Duplicate of https://github.com/JabRef/jabref/issues/5904 (?).

**Comment by notuntoward** [comment] 2020-05-10 22:33
Yes, they sound related, maybe the same.

**Comment by Siedlerchr** [comment] 2020-05-11 11:57
It seems it's related to the Autcompletion. Maybe we should disable autocmpletion for multiline fields
In addition, I noticed a search is fired every time an entry changes. (SearchListener in BasePanel)

**Comment by Siedlerchr** [comment] 2020-05-11 17:47
Please try this version:; https://builds.jabref.org/pull/6455/merge/ 
Please report back in the other thread #5904

**Closed by Siedlerchr** 2020-05-11 17:47 UTC
Labels: entry-editor
