### ISSUE TITLE
Error when adding file containing # to entry with character

### ISSUE THREAD

**Issue by judober** [JabRef/jabref#7012] opened 2020-10-13 12:51 UTC
JabRef version 5.2--2020-10-13--fdaf25a on Windows 10

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Add bibtexentry for https://link.springer.com/book/10.1007%2F978-3-662-53281-2
2. Add file
3.  Apply format pattern: "Filename format pattern": [bibtexkey] - [title:latex_to_unicode:remove_braces_formatter:regex("/|:|,","#")]
4. Restart Jabref
5. When opening from jabref, the file is not found.
6. bilatex source file line looks weird: "file      = {:Hue17 - Leiter} # Halbleiter #{ Supraleiter.pdf:PDF},"

My setup: biblatex, keypattern: "[auth3][shortyear]"

**Comment by Siedlerchr** [comment] 2020-10-13 13:02
@k3KAW8Pnf7mkmdSMPHz27 I just merged your other PR, does this maybe fix this is as well?

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-10-13 13:19
@Siedlerchr I don't think so. I'll take a look at it. I don't know how the source file line should look...

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-10-13 13:58
I can't reproduce. I'd guess that a workaround is to use `:regex("[{}]","")` rather than `remove_braces_formatter` (the brackets in regex were only an issue for citation keys, not filenames).

@judober could you paste the bibtexentry or link to it? I am not familiar with springer's webpage and the one I got from google scholar does not match yours.
Also, I'd appreciate if you check if the workaround works for you, it might make it easier for someone to debug this particular issue.

I'd guess this is one/two bugs, I don't believe curly brackets are removed for filenames, in which case it might create an issue when they are stored in the bib-file?
There might also be an issue when the `title` special field markers attempts to remove the latex commands.

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-10-13 14:00
@Siedlerchr I don't know what is going on in this issue, but I don't think my PR should impact this.

**Comment by Siedlerchr** [comment] 2020-10-13 14:06
Okay. I think the regex or so does not make sense because the # is interpreted as bibtex string.
@judober It would be really nice if you could show how it should look like, e.g what the expected outcome shoud look like

**Comment by judober** [comment] 2020-10-13 14:43
I tested again and I think I have to close Jabref and open it again in order to reproduce (will update original post). Just added the entry through doi, loaded the pdf (probably any pdf will do) and draged in on the entry. When I click the pdf symbol after restart my documentsfolder is opened but neither the pdf folder nor the pdf. Also I have the weird file-entry in the biblatex source that causes problem when using the library (undefined label Halbleiter).

The entry:
@Book{Hue17,
  author    = {Rudolf Huebener},
  date      = {2017},
  title     = {Leiter, Halbleiter, Supraleiter},
  doi       = {10.1007/978-3-662-53281-2},
  publisher = {Springer Berlin Heidelberg},
  file      = {:Hue17 - Leiter} #  Halbleiter #{ Supraleiter.pdf:PDF},
  timestamp = {2020.10.13},
}

I would expect the file-line to be
file      = {:Hue17 - Leiter #  Halbleiter # Supraleiter.pdf:PDF},
And of course jabref to open the pdf.

My manual workaround:
remove all # from the filename and add it manually. Than I get 
  file      = {:Hue17 - Leiter Halbleiter Supraleiter.pdf:PDF},
and everything works.

I tried `[bibtexkey] - [title:latex_to_unicode:regex("[{}]",""):regex("/|:|,","#")]` but this didn't change enything.
The same for `[bibtexkey] - [TITLE:latex_to_unicode:remove_braces_formatter:regex("/|:|,","#")]`

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-10-13 15:58
I can reproduce it from the "new entry" button in the GUI.
<img width="476" alt="Skärmavbild 2020-10-13 kl  11 54 33" src="https://user-images.githubusercontent.com/2598631/95885329-22a6d800-0d4b-11eb-8424-7eefabcb5670.png">

On a side note, I also get 
`11:54:05.303 [JavaFX Application Thread] WARN  org.jabref.logic.citationkeypattern.BracketedPattern - Key generator warning: unknown modifier 'remove_braces_formatter'.`

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-10-13 19:24
It doesn't seem like there should be an issue if there is only one `#` (based on `BibDatabase#resolveContent`). The split (`{:Ham81 - Organische Leiter, Halbleiter }{und Photoleiter.pdf:PDF},`) happens as soon as you have two (e.g., you can add it to the title `Organische leiter, halbleiter ##und photoleiter`). Perhaps that's why it hasn't been an issue before?

I'd guess adding it to `FileNameCleaner#ILLEGAL_CHARS`, same as curly brackets, would be the easy solution?

**Comment by Siedlerchr** [comment] 2020-10-13 20:24
@k3KAW8Pnf7mkmdSMPHz27  Good idea to add it to the illegal chars to avoid problems

**Comment by Siedlerchr** [comment] 2020-10-13 20:44
I don't know how feasible this is, probably needs more thinking. Normally in LaTex you can escape those "illegal" chars using a backslash.  And we have already a LatexCleanUpFormatter who does this for certain things. I remember having % signs in the abstract field needed to be escaped.
I tried to escape the # using backslashes as well in the regex, but JabRef still mangles it.

Refs also #7010 

Our LatexCleanupFormattter at least fixes the % sign,
https://github.com/JabRef/jabref/blob/1b35f8cb0040fdfb515974e78532598f07e11af2/src/main/java/org/jabref/logic/formatter/bibtexfields/LatexCleanupFormatter.java

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-10-13 21:02
If this is a rarely used feature, perhaps it should be opt-in rather than opt-out? Or perhaps with some defaults for `title`, `author` instead of all STANDARD_FIELDS? (see `preferences -> file -> Resolve strings for standard BibTeX fields only` for the current settings)

**Comment by k3KAW8Pnf7mkmdSMPHz27** [comment] 2020-10-13 21:32
> I don't know how feasible this is, probably needs more thinking.

You are right. The more I look into it, the more sense it makes to solve it rather than avoiding it.

**Comment by koppor** [comment] 2020-10-14 04:58
> On a side note, I also get
> `11:54:05.303 [JavaFX Application Thread] WARN org.jabref.logic.citationkeypattern.BracketedPattern - Key generator warning: unknown modifier 'remove_braces_formatter'.`

Can you try to remove `_formatter` in the settings? Meaning, it should read `remove_braces`.

I also added an issue https://github.com/JabRef/user-documentation/issues/318 hopefully guessing right what's going on there.

**Comment by 1190201923** [comment] 2021-08-01 08:21
Hi,we are a group of 7 students from Harbin Institue of Technology.Our open source software testing class asked us to contribute to an open-source project.We'd love to help with this issue.Is anyone currently working on this issue?If not can we take it? We are all new contributors to open-source projects.If possible could we get some guidance on which part of the code we should look into first. Thanks a lot
KeXin

**Comment by koppor** [comment] 2021-08-02 23:51
This issue needs much thinking. Please read on at https://github.com/JabRef/jabref/issues/7010 to get to know the issue around JabRef's internal handling of `#`.

Deep links to methods are:

- org.jabref.logic.importer.fileformat.BibtexParser#parseFieldContent
- org.jabref.logic.bibtex.FieldWriter#write

**Comment by 1190201923** [comment] 2021-08-03 00:28
Roger, our team will go to see it right away.

**Closed** 2022-01-13 21:06 UTC
Labels: type: enhancement, good first issue

**Comment by Siedlerchr** [comment] 2022-01-13 22:00
We now changed the whole logic and enable BibTeX string resolving only for a couple of fields. This can be adjusted in the options
