### ISSUE TITLE
Fatal Error when importing into current database

### ISSUE THREAD

**Issue by hellbourne** [JabRef/jabref#742] opened 2016-01-29 07:47 UTC
Hi,

When I try to import a file (in any format, e.g. .bib, .ris) to the current database, nothing happens. I opened the error console and the error message was:

`Fatal Error] :1:1: Content is not allowed in prolog.
Jan 29, 2016 8:40:54 AM net.sf.jabref.importer.OpenDatabaseAction loadDatabase
INFO: Synchronized special fields based on keywords
`

The file I tried to import, for example (although this happens with any file I try) is located [here](https://www.dropbox.com/s/ghkoym78lm7p9sa/pmcid-PMC3654245.ris?dl=0

I am using version 3.2.

Thank you,

**Comment by lenhard** [comment] 2016-01-31 13:32
@hellbourne Thanks for reporting. Unfortunately, I get a 404 when trying to access your file. Could you check if the file is correctly uploaded? Without it, it will be hard to reproduce the error.

@JabRef/developers Since this it about importers, it sounds very much like a task for our students.

**Comment by hellbourne** [comment] 2016-01-31 13:41
I fixed the link. Also, I have just verified that this problem occurs only on a linux box but not on a Windows box.

**Comment by lenhard** [comment] 2016-01-31 14:01
Thanks, the link works now! We'll see what we can do.

**Comment by stefan-kolb** [comment] 2016-04-13 17:41
@hellbourne Could you please try a current version of JabRef from http://builds.jabref.org/master/. I cannot reproduce your issue with the latest version.

**Comment by hellbourne** [comment] 2016-04-14 07:48
I did right now. Here is the console error message:

`09:43:44.483 [Spin-0] INFO  net.sf.jabref.importer.OpenDatabaseAction - Synchronized special fields based on keywords
[Fatal Error] :1:1: Content is not allowed in prolog.
09:43:44.563 [Spin-0] ERROR net.sf.jabref.logic.xmp.XMPUtil - XMP reading failed
java.io.IOException: Error: End-of-File, expected line
	at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1519) ~[JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at org.apache.pdfbox.pdfparser.PDFParser.parseHeader(PDFParser.java:372) ~[JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:186) ~[JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1230) ~[JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1197) ~[JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.loadWithAutomaticDecryption(XMPUtil.java:129) ~[JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.readXMP(XMPUtil.java:161) ~[JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.hasMetadata(XMPUtil.java:1274) [JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at net.sf.jabref.importer.fileformat.PdfXmpImporter.isRecognizedFormat(PdfXmpImporter.java:51) [JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at net.sf.jabref.importer.ImportFormatReader.importFromFile(ImportFormatReader.java:117) [JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at net.sf.jabref.importer.ImportFormatReader.importUnknownFormat(ImportFormatReader.java:241) [JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at net.sf.jabref.importer.ImportMenuItem$MyWorker.run(ImportMenuItem.java:126) [JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at spin.Invocation.evaluate(Invocation.java:175) [JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108) [JabRef-3.3dev--snapshot--2016-04-13--master--89dcd2a.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
`

Remember that I am on Linux (Ubuntu 15.10). This does not occur on a Windows box.

**Comment by stefan-kolb** [comment] 2016-04-14 08:26
Hm, I tried it on Ubuntu and it worked for me. The errors given here are a bit misleading as they do not occur because of a bug, but the importer imports an unknown format whcih is done by just cycling through all importers. In the end the ebst result of the parsing is imported. Therefore, some importers might throw exceptions during their runtime as the PDFImporter in this case cannot import a ris file.

**Comment by stefan-kolb** [comment] 2016-04-14 08:27
I'm just not sure about this error `Synchronized special fields based on keywords [Fatal Error] :1:1: Content is not allowed in prolog.`

**Comment by koppor** [comment] 2016-04-14 11:32
I assume, either the issue is related to the existing bibliography file or you have some other files in the import directory somehow. Could you try to move the file to another directory and import from there?

Maybe we should add a logger statement stating the current file name treated at `importFromFile`.

**Comment by hellbourne** [comment] 2016-04-14 20:03
I ran JabRef with a new database file and moved the RIS file to another directory. Same result:
`[Fatal Error] :1:1: Content is not allowed in prolog.
22:00:23.357 [Spin-0] ERROR net.sf.jabref.logic.xmp.XMPUtil - XMP reading failed
java.io.IOException: Error: End-of-File, expected line
	at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1519) ~[JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at org.apache.pdfbox.pdfparser.PDFParser.parseHeader(PDFParser.java:372) ~[JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:186) ~[JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1230) ~[JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1197) ~[JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.loadWithAutomaticDecryption(XMPUtil.java:129) ~[JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.readXMP(XMPUtil.java:161) ~[JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at net.sf.jabref.logic.xmp.XMPUtil.hasMetadata(XMPUtil.java:1274) [JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at net.sf.jabref.importer.fileformat.PdfXmpImporter.isRecognizedFormat(PdfXmpImporter.java:51) [JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at net.sf.jabref.importer.ImportFormatReader.importFromFile(ImportFormatReader.java:118) [JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at net.sf.jabref.importer.ImportFormatReader.importUnknownFormat(ImportFormatReader.java:240) [JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at net.sf.jabref.importer.ImportMenuItem$MyWorker.run(ImportMenuItem.java:126) [JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_77]
	at spin.Invocation.evaluate(Invocation.java:175) [JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at spin.off.SpinOffEvaluator$1.run(SpinOffEvaluator.java:108) [JabRef-3.3dev--snapshot--2016-04-14--master--0d683f6.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]`

**Comment by oscargus** [comment] 2016-04-14 20:39
What if you select RIS as file type on import?

I agree that it is a bit confusing that all those messages are printed, but
they are indeed a consequence of JabRef trying to import in other formats
than RIS before figuring out that RIS is probably the correct one.

>

**Comment by oscargus** [comment] 2016-04-14 20:42
@stefan-kolb : That error message comes from a SAXParserException (coming from an incorrect XML-file, which is not surprising considering it is an RIS file).

**Comment by stefan-kolb** [comment] 2016-04-14 20:48
Hm ok, we should refactor this somehow as this emits unexpected errors for users. I checked the code a few days ago and I don't really like the importer code in general. But anyhow, this doesn't seem to be the problem here. For me it worked as expected under Ubuntu, so we have something else again like preferences problems or thelike?

@hellbourne If you create a new database and import directly into it. Does it work or is also nothing imported? If you reset the preferences, does that change anything?

**Comment by Siedlerchr** [comment] 2016-04-14 22:01
@stefan-kolb @oscargus  
The error message comes from "guessing" the right import format, Jabref tries all importers until the right one is found. A  first step to improve would be to try guessing the import format from the file extension.

I just tried both import into current db and new db. And it works for me in the latest master on Win7 x64
416d8494955e06c58ccad8b868563baab56a86d2

**Comment by hellbourne** [comment] 2016-04-15 19:23
@stefan-kolb @oscargus

If I create a new database and import directly to it, I get the same result - nothing happens (except for the console log). If I choose explicitly RIS in the file type, I get a message "Wrong file format" and nothing of course is imported.

Again, I stress that this happens only on my Ubuntu 15.10 machine. On my Windows machine it works fine.

**Comment by stefan-kolb** [comment] 2016-05-10 08:18
Can you try to reset your preferences on Ubuntu and check if this solves the issue. As I cannot reproduce it here it may be related to some preference problems.

**Comment by stefan-kolb** [comment] 2016-05-12 13:07
@hellbourne Can you try to reset your preferences on Ubuntu and check if this solves the issue. As I cannot reproduce it here it may be related to some preference problems.

**Comment by hellbourne** [comment] 2016-05-12 13:14
@stefan-kolb, I am terribly sorry! I have only now noticed that you'd requested this "reset preferences" check 28 days ago. I tried this now and it works!

Actually we still don't know what the problem was, but at least it is no longer there.

Thank you so much!

Hellbourne

**Comment by stefan-kolb** [comment] 2016-05-12 13:15
Can you please upload the preferences here, so we can investigate?

**Comment by stefan-kolb** [comment] 2016-05-12 13:15
@hellbourne Can you please upload the preferences here, so we can investigate?

**Comment by hellbourne** [comment] 2016-05-12 13:17
Well, now I only have the "good" ones, but here they are:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE preferences SYSTEM "http://java.sun.com/dtd/preferences.dtd">
<preferences EXTERNAL_XML_VERSION="1.0">
  <root type="user">
    <map/>
    <node name="net">
      <map/>
      <node name="sf">
        <map/>
        <node name="jabref">
          <map>
            <entry key="KeyPatternRegex" value=""/>
            <entry key="KeyPatternReplacement" value=""/>
            <entry key="abbrAuthorNames" value="true"/>
            <entry key="activeFieldEditorBackgroundColor" value="220:220:255"/>
            <entry key="allowFileAutoOpenBrowse" value="true"/>
            <entry key="allowTableEditing" value="false"/>
            <entry key="arxivColumn" value="false"/>
            <entry key="autoAssignGroup" value="true"/>
            <entry key="autoCompFF" value="false"/>
            <entry key="autoCompFirstNameMode" value="BOTH"/>
            <entry key="autoCompLF" value="false"/>
            <entry key="autoComplete" value="true"/>
            <entry key="autoCompleteFields" value="author;editor;title;journal;publisher;keywords;crossref"/>
            <entry key="autoOpenForm" value="true"/>
            <entry key="autoResizeMode" value="4"/>
            <entry key="autoSave" value="true"/>
            <entry key="autoSaveInterval" value="5"/>
            <entry key="autolinkExactKeyOnly" value="false"/>
            <entry key="avoidOverwritingKey" value="false"/>
            <entry key="backup" value="true"/>
            <entry key="bibLocAsPrimaryDir" value="false"/>
            <entry key="biblatexMode" value="false"/>
            <entry key="citeCommand" value="\cite"/>
            <entry key="confirmDelete" value="true"/>
            <entry key="ctrlClick" value="false"/>
            <entry key="defaultEncoding" value="UTF-8"/>
            <entry key="defaultLabelPattern" value="[authors3][year]"/>
            <entry key="defaultOwner" value="af3"/>
            <entry key="defaultShowSource" value="false"/>
            <entry key="dialogWarningForDuplicateKey" value="true"/>
            <entry key="dialogWarningForEmptyKey" value="true"/>
            <entry key="disableOnMultipleSelection" value="false"/>
            <entry key="doNotResolveStringsFor" value="url"/>
            <entry key="emailSubject" value="References"/>
            <entry key="enforceLegalBibtexKey" value="true"/>
            <entry key="exportInOriginalOrder" value="false"/>
            <entry key="exportInSpecifiedOrder" value="false"/>
            <entry key="exportPriDescending" value="false"/>
            <entry key="exportPriSort" value="bibtexkey"/>
            <entry key="exportSecDescending" value="false"/>
            <entry key="exportSecSort" value="author"/>
            <entry key="exportTerDescending" value="true"/>
            <entry key="exportTerSort" value="title"/>
            <entry key="extraFileColumns" value="false"/>
            <entry key="fieldEditorTextColor" value="0:0:0"/>
            <entry key="fileColumn" value="true"/>
            <entry key="fileDirectory" value=""/>
            <entry key="floatMarkedEntries" value="true"/>
            <entry key="fontFamily" value="SansSerif"/>
            <entry key="fontSize" value="12"/>
            <entry key="fontStyle" value="0"/>
            <entry key="generateKeysAfterInspection" value="true"/>
            <entry key="generateKeysBeforeSaving" value="false"/>
            <entry key="gridColor" value="210:210:210"/>
            <entry key="groupAutoHide" value="true"/>
            <entry key="groupAutoShow" value="true"/>
            <entry key="groupExpandTree" value="true"/>
            <entry key="groupKeywordSeparator" value=", "/>
            <entry key="groupShowDynamic" value="true"/>
            <entry key="groupShowIcons" value="true"/>
            <entry key="groupsDefaultField" value="keywords"/>
            <entry key="groupsVisibleRows" value="32"/>
            <entry key="importAlwaysUsePDFImportStyle" value="false"/>
            <entry key="importDefaultPDFimportStyle" value="2"/>
            <entry key="importFileNamePattern" value="\bibtexkey\begin{title} - \format[RemoveBrackets]{\title}\end{title}"/>
            <entry key="importInspectionDialogHeight" value="650"/>
            <entry key="importInspectionDialogWidth" value="650"/>
            <entry key="importWorkingDirectory" value="/home/af3/Dropbox"/>
            <entry key="incompleteEntryBackground" value="250:175:175"/>
            <entry key="invalidFieldBackgroundColor" value="255:0:0"/>
            <entry key="keyGenAlwaysAddLetter" value="false"/>
            <entry key="keyGenFirstLetterA" value="true"/>
            <entry key="lastEdited" value="/home/af3/Dropbox/NV/NVSPM.bib"/>
            <entry key="lastFocused" value="/home/af3/Dropbox/NV/NVSPM.bib"/>
            <entry key="lastUsedImport" value="__all"/>
            <entry key="listOfFileColumns" value=""/>
            <entry key="lookAndFeel" value="javax.swing.plaf.metal.MetalLookAndFeel"/>
            <entry key="mainWindowPosX" value="65"/>
            <entry key="mainWindowPosY" value="24"/>
            <entry key="mainWindowSizeX" value="1855"/>
            <entry key="mainWindowSizeY" value="1056"/>
            <entry key="markImportedEntries" value="true"/>
            <entry key="markedEntryBackground0" value="255:255:180"/>
            <entry key="markedEntryBackground1" value="255:220:180"/>
            <entry key="markedEntryBackground2" value="255:180:160"/>
            <entry key="markedEntryBackground3" value="255:120:120"/>
            <entry key="markedEntryBackground4" value="255:75:75"/>
            <entry key="markedEntryBackground5" value="220:255:220"/>
            <entry key="memoryStickMode" value="false"/>
            <entry key="namesAsIs" value="false"/>
            <entry key="namesFf" value="false"/>
            <entry key="namesLastOnly" value="false"/>
            <entry key="namesNatbib" value="true"/>
            <entry key="newline" value="&#10;"/>
            <entry key="openFoldersOfAttachedFiles" value="false"/>
            <entry key="openLastEdited" value="true"/>
            <entry key="overrideDefaultFonts" value="false"/>
            <entry key="overwriteOwner" value="false"/>
            <entry key="overwriteTimeStamp" value="false"/>
            <entry key="preferUrlDoi" value="false"/>
            <entry key="preview0" value="&lt;font face=&quot;sans-serif&quot;&gt;&lt;b&gt;&lt;i&gt;\bibtextype&lt;/i&gt;&lt;a name=&quot;\bibtexkey&quot;&gt;\begin{bibtexkey} (\bibtexkey)&lt;/a&gt;\end{bibtexkey}&lt;/b&gt;&lt;br&gt;__NEWLINE__\begin{author} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\author}&lt;BR&gt;\end{author}__NEWLINE__\begin{editor} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\editor} &lt;i&gt;(\format[IfPlural(Eds.,Ed.)]{\editor})&lt;/i&gt;&lt;BR&gt;\end{editor}__NEWLINE__\begin{title} \format[HTMLChars]{\title} \end{title}&lt;BR&gt;__NEWLINE__\begin{chapter} \format[HTMLChars]{\chapter}&lt;BR&gt;\end{chapter}__NEWLINE__\begin{journal} &lt;em&gt;\format[HTMLChars]{\journal}, &lt;/em&gt;\end{journal}__NEWLINE__\begin{booktitle} &lt;em&gt;\format[HTMLChars]{\booktitle}, &lt;/em&gt;\end{booktitle}__NEWLINE__\begin{school} &lt;em&gt;\format[HTMLChars]{\school}, &lt;/em&gt;\end{school}__NEWLINE__\begin{institution} &lt;em&gt;\format[HTMLChars]{\institution}, &lt;/em&gt;\end{institution}__NEWLINE__\begin{publisher} &lt;em&gt;\format[HTMLChars]{\publisher}, &lt;/em&gt;\end{publisher}__NEWLINE__\begin{year}&lt;b&gt;\year&lt;/b&gt;\end{year}\begin{volume}&lt;i&gt;, \volume&lt;/i&gt;\end{volume}\begin{pages}, \format[FormatPagesForHTML]{\pages} \end{pages}__NEWLINE__\begin{abstract}&lt;BR&gt;&lt;BR&gt;&lt;b&gt;Abstract: &lt;/b&gt; \format[HTMLChars]{\abstract} \end{abstract}__NEWLINE__\begin{review}&lt;BR&gt;&lt;BR&gt;&lt;b&gt;Review: &lt;/b&gt; \format[HTMLChars]{\review} \end{review}&lt;/dd&gt;__NEWLINE__&lt;p&gt;&lt;/p&gt;&lt;/font&gt;"/>
            <entry key="preview1" value="&lt;font face=&quot;sans-serif&quot;&gt;&lt;b&gt;&lt;i&gt;\bibtextype&lt;/i&gt;&lt;a name=&quot;\bibtexkey&quot;&gt;\begin{bibtexkey} (\bibtexkey)&lt;/a&gt;\end{bibtexkey}&lt;/b&gt;&lt;br&gt;__NEWLINE__\begin{author} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\author}&lt;BR&gt;\end{author}__NEWLINE__\begin{editor} \format[Authors(LastFirst,Initials,Semicolon,Amp),HTMLChars]{\editor} &lt;i&gt;(\format[IfPlural(Eds.,Ed.)]{\editor})&lt;/i&gt;&lt;BR&gt;\end{editor}__NEWLINE__\begin{title} \format[HTMLChars]{\title} \end{title}&lt;BR&gt;__NEWLINE__\begin{chapter} \format[HTMLChars]{\chapter}&lt;BR&gt;\end{chapter}__NEWLINE__\begin{journal} &lt;em&gt;\format[HTMLChars]{\journal}, &lt;/em&gt;\end{journal}__NEWLINE__\begin{booktitle} &lt;em&gt;\format[HTMLChars]{\booktitle}, &lt;/em&gt;\end{booktitle}__NEWLINE__\begin{school} &lt;em&gt;\format[HTMLChars]{\school}, &lt;/em&gt;\end{school}__NEWLINE__\begin{institution} &lt;em&gt;\format[HTMLChars]{\institution}, &lt;/em&gt;\end{institution}__NEWLINE__\begin{publisher} &lt;em&gt;\format[HTMLChars]{\publisher}, &lt;/em&gt;\end{publisher}__NEWLINE__\begin{year}&lt;b&gt;\year&lt;/b&gt;\end{year}\begin{volume}&lt;i&gt;, \volume&lt;/i&gt;\end{volume}\begin{pages}, \format[FormatPagesForHTML]{\pages} \end{pages}&lt;/dd&gt;__NEWLINE__&lt;p&gt;&lt;/p&gt;&lt;/font&gt;"/>
            <entry key="previewPanelHeight" value="200"/>
            <entry key="priDescending" value="false"/>
            <entry key="priSort" value="author"/>
            <entry key="promptBeforeUsingAutosave" value="true"/>
            <entry key="proxyHostname" value=""/>
            <entry key="proxyPassword" value=""/>
            <entry key="proxyPort" value="80"/>
            <entry key="proxyUsername" value=""/>
            <entry key="pushToApplication" value="TeXstudio"/>
            <entry key="recentFiles" value="/home/af3/Dropbox/NV/NVSPM.bib;/home/af3/Downloads/landa/bib/surface_ionization.bib"/>
            <entry key="reformatFileOnSaveAndExport" value="false"/>
            <entry key="resolveStringsAllFields" value="false"/>
            <entry key="runAutomaticFileSearch" value="false"/>
            <entry key="secDescending" value="true"/>
            <entry key="secSort" value="year"/>
            <entry key="shortestToComplete" value="1"/>
            <entry key="sidePaneWidth" value="299"/>
            <entry key="tableBackground" value="255:255:255"/>
            <entry key="tableColorCodesOn" value="false"/>
            <entry key="tableOptFieldBackground" value="230:255:230"/>
            <entry key="tableReqFieldBackground" value="230:235:255"/>
            <entry key="tableRowPadding" value="9"/>
            <entry key="tableShowGrid" value="false"/>
            <entry key="tableText" value="0:0:0"/>
            <entry key="terDescending" value="false"/>
            <entry key="terSort" value="title"/>
            <entry key="timeStampField" value="timestamp"/>
            <entry key="timeStampFormat" value="yyyy-MM-dd"/>
            <entry key="toolbarVisible" value="true"/>
            <entry key="unmarkAllEntriesBeforeImporting" value="true"/>
            <entry key="updateTimestamp" value="false"/>
            <entry key="urlColumn" value="true"/>
            <entry key="useCaseKeeperOnSearch" value="true"/>
            <entry key="useConvertToEquation" value="false"/>
            <entry key="useDefaultLookAndFeel" value="false"/>
            <entry key="useOwner" value="false"/>
            <entry key="useProxy" value="false"/>
            <entry key="useProxyAuthentication" value="false"/>
            <entry key="useRegExpSearch" value="false"/>
            <entry key="useRemoteServer" value="true"/>
            <entry key="useTimeStamp" value="false"/>
            <entry key="useUnitFormatterOnSearch" value="true"/>
            <entry key="useXmpPrivacyFilter" value="false"/>
            <entry key="validFieldBackgroundColor" value="255:255:255"/>
            <entry key="valueDelimiters" value="1"/>
            <entry key="warnAboutDuplicatesInInspection" value="true"/>
            <entry key="warnBeforeOverwritingKey" value="true"/>
            <entry key="windowMaximised" value="true"/>
          </map>
          <node name="labelPattern">
            <map/>
          </node>
          <node name="logic">
            <map/>
            <node name="labelPattern">
              <map/>
            </node>
            <node name="labelpattern">
              <map/>
            </node>
          </node>
        </node>
      </node>
    </node>
  </root>
</preferences>`

**Comment by stefan-kolb** [comment] 2016-05-12 13:21
Hm, ok so we need to close this for now...

**Closed by stefan-kolb** 2016-05-12 13:21 UTC
Labels: bug, linux, stupro, waiting-for-feedback
