### ISSUE TITLE
unable to delete an entry

### ISSUE THREAD

**Issue by amaxi99** [JabRef/jabref#6739] opened 2020-08-05 17:57 UTC
JabRef 5.1--2020-08-05--3d68514
Windows 10 10.0 amd64 
Java 14.0.2

With the latest development builds it is not possible to delete an entry. Neither "del" key nor right-click-menu "delete" do anything. This does not even work for a single entry in a newy created library.

**Comment by Siedlerchr** [comment] 2020-08-05 19:25
Duplicate of #6738

**Closed by Siedlerchr** 2020-08-05 19:25 UTC

**Comment by Siedlerchr** [comment] 2020-08-05 19:38
Wokaround should be trash icon in the toolbar. This issue is a side effect of a mac bug.  Fix is on its way
