### ISSUE TITLE
General --> File --> right mouse button --> Open Folder   opens pdf viewer

### ISSUE THREAD

**Issue by horror-vacui** [JabRef/jabref#6744] opened 2020-08-06 09:46 UTC
Clicking on Open Folder item opens my pdf viewer (okular in my case), instead of a file manager.

1. Select an entry with an attached pdf
2. Go to the General tab
3. RMB (right mouse button) on the pdf file
4. Click Open Folder
![jabref_file_open_folder](https://user-images.githubusercontent.com/31111509/89517708-6543b580-d7da-11ea-826d-0c571250f3ea.png)

There is no entry in the event log.

---
JabRef 5.1--2020-06-09--595f085
Linux 4.15.0-112-generic amd64 
Java 14.0.1

**Comment by ilippert** [comment] 2021-01-07 17:55
JabRef 5.3--2021-01-07--129abaa
Linux 5.9.16-200.fc33.x86_64 amd64 
Java 15.0.1

JabRef does not seem to react at all to the "Open Folder" Action.

**Comment by Siedlerchr** [comment] 2021-01-07 18:18
Open folder works fine for me on Mac. @LyzardKing  You looked into this file opening, do you know what is necessary for "opening folder" on linux?

**Comment by LyzardKing** [comment] 2021-01-07 20:52
@horror-vacui @ilippert 
What jabref package are you running?
I can confirm it's happening to me as well now..
I'll look into it, but the last time I looked at it it worked

**Comment by LyzardKing** [comment] 2021-01-07 21:01
@Siedlerchr 
If I set the file directory in the preferences dialog, then try to "move file to file directory" I get the error "file directory is not set or does not exist"
This is a new (to me) error, and it could be the underlying cause of the openFolder not working... could it?

**Comment by LyzardKing** [comment] 2021-01-07 21:20
If I run gladlew run I get this error.. am I missing some dependency?
> org.apache.logging.log4j.LoggingException: Unable to create Plugin Service Class org.jabref.gui.logging.plugins.Log4jPlugins

**Comment by Siedlerchr** [comment] 2021-01-07 21:34
Try executing gradlew clean before once. 
Hm did you restart jabref after changing the preferences?

**Comment by LyzardKing** [comment] 2021-01-07 21:49
Ok.. cleaning worked.. I must have forgotten to run that earlier ;)
But it's still not reading the preference correctly

**Comment by LyzardKing** [comment] 2021-01-07 21:56
https://github.com/JabRef/jabref/blob/c8f7be89ad704065474decb61851e42416caf88d/src/main/java/org/jabref/gui/fieldeditors/LinkedFileViewModel.java#L208

This seems to return an Empty... so no path is passed to the open method

**Comment by LyzardKing** [comment] 2021-01-07 22:23
The error seems to be in reading the settings database...
The path string is correct, but the database preferences returns an empty array..

**Comment by Siedlerchr** [comment] 2021-01-07 22:40
Can you try to reset your preferences and try again with a new path? Or did you have checked "Search and store files relative to library location" enabled? -> That takes precedence

**Comment by LyzardKing** [comment] 2021-01-07 23:00
It works.. The folder path was not set properly.
It must be my fault... I recently changed computer and just imported everything as is...

**Comment by ilippert** [comment] 2021-01-10 19:24
> @horror-vacui @ilippert
> What jabref package are you running?
> I can confirm it's happening to me as well now..
> I'll look into it, but the last time I looked at it it worked

I run

JabRef 5.3--2021-01-09--86852c6
Linux 5.9.16-200.fc33.x86_64 amd64 
Java 15.0.1 
JavaFX 15.0.1+1

and nothing happens when I press `Open Folder` nothing happens.

**Comment by LyzardKing** [comment] 2021-01-10 23:02
@ilippert how did you install jabref? The deb, rpm, tar, snap, or flatpak?
This could be useful to debug.
Also what distro are you running on?

**Comment by ilippert** [comment] 2021-01-11 10:20
Thanks, I run Fedora 33, installing master via rpm.

**Comment by LyzardKing** [comment] 2021-01-11 11:53
Did you verify that in settings the folder containing the files is set?
If that's the case I can try making a custom build with a debug message in the function that runs on openFolder

**Comment by ilippert** [comment] 2021-01-12 15:22
JabRef 5.3--2021-01-11--7f26a3a
Linux 5.9.16-200.fc33.x86_64 amd64 
Java 15.0.1 
JavaFX 15.0.1+1


> Did you verify that in settings the folder containing the files is set?

JabRef preferences/Linked files has a main file directory set.

**Comment by horror-vacui** [comment] 2021-01-20 07:59
> @horror-vacui @ilippert
> What jabref package are you running?
> I can confirm it's happening to me as well now..
> I'll look into it, but the last time I looked at it it worked

I've written the jabref version in the description of the issue. I was using Xubuntu 18.04 LTS than. I have the same jabref, but on 20.04 LTS now. I think, I have installed it through the deb package. 

> Did you verify that in settings the folder containing the files is set?
Sorry, but I am not sure what you mean by that...

**Comment by LyzardKing** [comment] 2021-01-20 09:28
@horror-vacui 
In Jabref:
1. open the Options Menu
2. select Preferences
3. select Linked Files form the list on the left
4. What value do you have in Main file directory? Is it the correct folder where your files are located?

**Comment by horror-vacui** [comment] 2021-01-20 09:39
> @horror-vacui
> In Jabref:
> 
>     1. open the Options Menu
>     2. select Preference> 
>     3. select Linked Files form the list on the left
>     4. What value do you have in Main file directory? Is it the correct folder where your files are located?

I've got Files, instead of Linked Files on the left hand manu, but I think they are the same. The "main file directory" field is set and it is the directory, where my pdf located.

**Comment by sankayop** [comment] 2021-04-13 13:53
> JabRef 5.3--2021-01-11--7f26a3a
> Linux 5.9.16-200.fc33.x86_64 amd64
> Java 15.0.1
> JavaFX 15.0.1+1
> 
> > Did you verify that in settings the folder containing the files is set?
> 
> JabRef preferences/Linked files has a main file directory set.

Hi there,
same as @ilippert  here.
JabRef 5.3--2021-02-01--8c3424c
Linux 5.11.6-1-manjaro amd64 
Java 15.0.2 
JavaFX 15.0.1+1

No error is visible concerning this in the terminal.
Thanks for your help :)

**Comment by ThiloteE** [comment] 2022-05-18 12:39
Closing in favour of #8679

**Closed** 2022-05-18 12:39 UTC
Labels: os: linux
