### ISSUE TITLE
regex issue

### ISSUE THREAD

**Issue by atreistm** [JabRef/jabref#9505] opened 2022-12-28 20:35 UTC
### JabRef version

Latest development branch build (please note build date below)

### Operating system

Windows

### Details on version and operating system

JabRef 6.0--2022-12-26--7fc7361 Windows 11 10.0 amd64  Java 19.0.1  JavaFX 19+11

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. ...Ran check integrity.
2
3. ...
4. ...

### Appendix

...
<details>

<summary>Log File</summary>

```
Not updating theme because it hasn't changed
Theme set to Theme{type=DEFAULT, name=''} with base css StyleSheet{jrt:/org.jabref/org/jabref/gui/Base.css}
No open database detected
Opening: 'C:\Users\avi.TREISTMAN\Downloads\citation-318741395.bib'
Opening: 'D:\Documents\Doctorate\EMailVAK\EmailVAKr1.bib'
Opening: 'D:\Documents\Doctorate\FinalPaper\Doctorate.bib'
Index path for C:\Users\avi.TREISTMAN\Downloads\citation-318741395.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\EMailVAK\EmailVAKr1.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Could not find Newton2020 - How Common Is Belief in the Learning Styles Neuromyth, and Does It Matter_ a Pragmatic Systematic Review.pdf
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Could not find bachu_review_2019 - A Review of Feature Selection and Its Methods.pdf
Could not find information-10-00150.pdf
Could not find Li2020 - A Survey on Text Classification_ from Shallow to Deep Learning.pdf
Could not find 2020-A survey on text classification-From shallow to deep learning.pdf
Could not find Bojanowski2017 - Enriching Word Vectors with Subword Information.pdf
Could not find celik_examination_2020 - Examination of Feature Selection Methods and an Application.pdf
Could not find Clark2019 - Unsupervised Dimensionality Reduction Versus Supervised Regularization for Classification from Sparse Data.pdf
Could not find cunningham15a.pdf
Could not find deshmukh_learning_2014 - A LEARNING STYLE CLASSIFICATION MECHANISM USING BRAIN DOMINANCE aND VAK METHOD iN M LEARNING ENVIRONMENT.pdf
Could not find Devlin2019 - BERT_ Pre Training of Deep Bidirectional Transformers for Language Understanding.pdf
Could not find sne_final.pdf
Could not find hoffmann_kernel_2007 - Kernel PCA for Novelty Detection.pdf
Could not find Huang2009 - A Thesaurus Based Semantic Classification of English Collocations.pdf
Could not find jolliffe_principal_1990 - Principal Component Analysis_ a Beginner's Guide I. Introduction and Application.pdf
Could not find Joulin2016 - Bag of Tricks for Efficient Text Classification.pdf
Could not find landthaler_extending_2017 - Extending Thesauri Using Word Embeddings and the Intersection Method.pdf
Could not find Levenshtein1966 - Binary Codes Capable of Correcting Deletions, Insertions, and Reversals.pdf
Could not find LpezIbez2016 - The Irace Package_ Iterated Racing for Automatic Algorithm Configuration.pdf
Could not find Melamud2016 - The Role of Context Types and Dimensionality in Learning Word Embeddings.pdf
Could not find migenda_adaptive_2021 - Adaptive Dimensionality Reduction for Neural Network Based Online Principal Component Analysis.pdf
Could not find molina_feature_2002 - Feature Selection Algorithms_ a Survey and Experimental Evaluation..pdf
Could not find Moreo2021 - Word Class Embeddings for Multiclass Text Classification.pdf
Could not find 1911.11506.pdf
Could not find Patel2017 - Towards Lower Bounds on Number of Dimensions for Word Embeddings.pdf
Could not find pennington_glove__2014 - Glove_ Global Vectors for Word Representation.pdf
Could not find peters_deep_2018 - Deep Contextualized Word Representations.pdf
Could not find W19-4328.pdf
Could not find 1711.08609.pdf
Could not find Ross1967 - Constraints on Variables in Syntax..pdf
Could not find Suji2021 - Learning Styles through Visual, Auditory and Kinesthetic (VAK) Scale.pdf
Could not find turney_frequency_2010 - From Frequency to Meaning_ Vector Space Models of Semantics.pdf
Could not find Breiman2001 - Random Forests.pdf
Could not find Gasparetto2022 - A Survey on Text Classification Algorithms_ from Text to Predictions.pdf
Could not find information-10-00150.pdf
Could not find Li2020 - A Survey on Text Classification_ from Shallow to Deep Learning.pdf
Could not find 2020-A survey on text classification-From shallow to deep learning.pdf
Could not find Louppe2015 - Understanding Random Forests_ from Theory to Practice.pdf
Could not find Newton2020 - How Common Is Belief in the Learning Styles Neuromyth, and Does It Matter_ a Pragmatic Systematic Review.pdf
Could not find Quinlan1986 - Induction of Decision Trees.pdf
Could not find Zhang2020 - A Learning Style Classification Approach Based on Deep Belief Network for Large Scale Online Education.pdf
Could not find Thawani2021 - Representing Numbers in NLP_ a Survey and a Vision.pdf
Could not find SparckJones1991 - Notes and References on Early Automatic Classification Work.pdf
Could not find Sources/sigirforum91.pdf
Could not find Crouch1992 - Experiments in Automatic Statistical Thesaurus Construction.pdf
Could not find Sources/133160.133180.pdf
Could not find Grefenstette1992 - Use of Syntactic Context to Produce Term Association Lists for Text Retrieval.pdf
Could not find Sources/133160.133181.pdf
Could not find Sources/1-s2.0-0306457388900210-main.pdf
Could not find Sources/Journal of the American Society for Information Science - June 1991 - Peat - The limitations of term co‐occurrence data for.pdf
Could not find Sources/Deep_Neural_Network_and_Pseudo_Relevance_Feedback_.pdf
Could not find Sources/Using_Word_Embeddings_for_Automatic_Query_Expansio.pdf
Could not find Sources/s11042-021-11297-x.pdf
Could not find Sources/Query_expansion_using_pseudo_r.pdf
Could not find Sources/Chapter-1---Application-and-techniques-of-opi_2020_Hybrid-Computational-Inte.pdf
Could not find Sources/N19-1352.pdf
Could not find Sources/3-37.pdf
Could not find Sources/bird2006mes.pdf
Could not find Sources/MSR.2007.35.pdf
Could not find Sources/s10639-019-09956-6.pdf
Could not find Sources/D7669049420.pdf
Could not find Sources/2017iConference--TF-IDuF-ANovelTerm-WeightingScheme--preprint.pdf
Could not find Sources/2017iConference--TF-IDuF-ANovelTerm-WeightingScheme--preprint.pdf
Could not find Sources/ResearchPaperRecommenderSystems--ALiteratureSurvey--preprint.pdf
Could not find Sources/1-s2.0-S0360131505001788-main.pdf
Could not find Sources/Anatomical Sciences Ed - 2018 - Husmann - Another Nail in the Coffin for Learning Styles  Disparities among Undergraduate.pdf
Could not find Sources/Attempted Validation of the Scores of t...pdf
Could not find Sources/978-3-642-02032-2.pdf
Could not find Sources/Aizawa-tf-idfMeasures.pdf
Could not find Sources/paper.pdf
Could not find Marwah2020 - Term Recency for TF IDF, BM25 and USE Term Weighting.pdf
Could not find Sources/Marwah2020 - Term Recency for TF IDF, BM25 and USE Term Weighting.pdf
Could not find Sources/1-s2.0-0306457388900210-main.pdf
Could not find Sources/10-1108_00220410410560582.pdf
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Copied 1 entry.
Saving library...
Library saved
Library saved
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Copied 1 entry.
Library saved
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Copied 1 entry.
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Copied 1 entry.
Library saved
Saving library...
Library saved
Library saved
Opening: 'D:\Documents\Doctorate\EMailVAKr1\EmailVAKr1.bib'
Index path for D:\Documents\Doctorate\EMailVAKr1\EmailVAKr1.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Could not find Newton2020 - How Common Is Belief in the Learning Styles Neuromyth, and Does It Matter_ a Pragmatic Systematic Review.pdf
Could not find information-10-00150.pdf
Could not find Li2020 - A Survey on Text Classification_ from Shallow to Deep Learning.pdf
Could not find 2020-A survey on text classification-From shallow to deep learning.pdf
Could not find Thawani2021 - Representing Numbers in NLP_ a Survey and a Vision.pdf
Could not find SparckJones1991 - Notes and References on Early Automatic Classification Work.pdf
Could not find Sources/sigirforum91.pdf
Could not find Crouch1992 - Experiments in Automatic Statistical Thesaurus Construction.pdf
Could not find Sources/133160.133180.pdf
Could not find Grefenstette1992 - Use of Syntactic Context to Produce Term Association Lists for Text Retrieval.pdf
Could not find Sources/133160.133181.pdf
Could not find Sources/1-s2.0-0306457388900210-main.pdf
Could not find Sources/Journal of the American Society for Information Science - June 1991 - Peat - The limitations of term co‐occurrence data for.pdf
Could not find Sources/Deep_Neural_Network_and_Pseudo_Relevance_Feedback_.pdf
Could not find Sources/Using_Word_Embeddings_for_Automatic_Query_Expansio.pdf
Could not find Sources/s11042-021-11297-x.pdf
Could not find Sources/Query_expansion_using_pseudo_r.pdf
Could not find Sources/Chapter-1---Application-and-techniques-of-opi_2020_Hybrid-Computational-Inte.pdf
Could not find Sources/N19-1352.pdf
Could not find Sources/3-37.pdf
Could not find Sources/bird2006mes.pdf
Could not find Sources/MSR.2007.35.pdf
Could not find Sources/s10639-019-09956-6.pdf
Could not find Sources/D7669049420.pdf
Could not find Sources/2017iConference--TF-IDuF-ANovelTerm-WeightingScheme--preprint.pdf
Could not find Sources/2017iConference--TF-IDuF-ANovelTerm-WeightingScheme--preprint.pdf
Could not find Sources/ResearchPaperRecommenderSystems--ALiteratureSurvey--preprint.pdf
Could not find Sources/1-s2.0-S0360131505001788-main.pdf
Could not find Sources/Anatomical Sciences Ed - 2018 - Husmann - Another Nail in the Coffin for Learning Styles  Disparities among Undergraduate.pdf
Could not find Sources/Attempted Validation of the Scores of t...pdf
Could not find Sources/978-3-642-02032-2.pdf
Could not find Sources/data-preparation-for-machine-learning-data-cleaning-feature-selection-and-data_compress.pdf
Could not find Suji2021 - Learning Styles through Visual, Auditory and Kinesthetic (VAK) Scale.pdf
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Saving library...
Library saved
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Index path for D:\Documents\Doctorate\FinalPaper\Doctorate.bib is C:\Users\avi.TREISTMAN\AppData\Local\org.jabref\JabRef\lucene94
Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.util.regex.PatternSyntaxException: Illegal repetition near index 1
{\textcopyright}[\.\s]*Cambridge[\.\s]*University[\.\s]*Press[\.\s]*2015[\.\s]*
 ^
	at java.base/java.util.regex.Pattern.error(Unknown Source)
	at java.base/java.util.regex.Pattern.closure(Unknown Source)
	at java.base/java.util.regex.Pattern.sequence(Unknown Source)
	at java.base/java.util.regex.Pattern.expr(Unknown Source)
	at java.base/java.util.regex.Pattern.compile(Unknown Source)
	at java.base/java.util.regex.Pattern.<init>(Unknown Source)
	at java.base/java.util.regex.Pattern.compile(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.journals.JournalAbbreviationRepository.lambda$findDottedAbbrFromDotless$2(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Iterator.forEachRemaining(Unknown Source)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.journals.JournalAbbreviationRepository.findDottedAbbrFromDotless(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.journals.JournalAbbreviationRepository.isAbbreviatedName(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.logic.integrity.AbbreviationChecker.checkValue(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.fieldeditors.AbstractEditorViewModel.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.8.60000/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.lambda$new$1(Unknown Source)
	at org.jabref.merged.module@5.8.60000/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.validate(Unknown Source)
	at org.jabref.merged.module@5.8.60000/de.saxsys.mvvmfx.utils.validation.FunctionBasedValidator.lambda$new$0(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.StringPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.StringPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.StringPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.StringProperty.setValue(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.util.BindingsHelper.bindBidirectional(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.util.BindingsHelper.bindBidirectional(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.fieldeditors.AbstractEditorViewModel.bindToEntry(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.fieldeditors.SimpleEditor.bindToEntry(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.entryeditor.FieldsEditorTab.setupPanel(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.entryeditor.FieldsEditorTab.bindToEntry(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.entryeditor.EntryEditorTab.notifyAboutFocus(Unknown Source)
	at org.jabref@5.8.60000/org.jabref.gui.entryeditor.EntryEditor.lambda$new$0(Unknown Source)
	at com.tobiasdiez.easybind@2.2.1-SNAPSHOT/com.tobiasdiez.easybind.EasyBind.lambda$subscribe$1(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.ObjectPropertyBase.markInvalid(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.beans.property.ObjectPropertyBase.set(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.control.SelectionModel.setSelectedItem(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.control.TabPane$TabPaneSelectionModel.select(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.scene.control.behavior.TabPaneBehavior.selectTab(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5.handle(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.event.Event.fireEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at org.jabref.merged.module@5.8.60000/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.8.60000/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

</details>
```
<details>
<summary>Detail information:</summary>

```@misc{Cambridge2015,
abstract = {treating a person or particular group of people differently, especially in a worse way from the way in which you treat other people, because of their skin colour, sex, sexuality, etc.:},
author = {Cambridge},
booktitle = {{\textcopyright} Cambridge University Press 2015},
title = {{Cambridge Online Dictionary}},
year = {2015}
}


</details>

**Comment by atreistm** [comment] 2022-12-28 21:18
Seems to be connected to booktitle. There is an open ticket on this.

**Comment by Siedlerchr** [comment] 2022-12-29 10:11
Duplicate of #9503 and #9457 
A fix is already in the pipeline!

**Closed by Siedlerchr** 2022-12-29 10:12 UTC

**Comment by Siedlerchr** [comment] 2023-01-05 13:36
@atreistm  The issue is now fixed in our latest development version and we will release a version 5.9 this week which will contain these fixes as well
