### ISSUE TITLE
Sort languages alphabetically in the preferences

### ISSUE THREAD

**Issue by Siedlerchr** [JabRef/jabref#10660] opened 2023-11-21 21:21 UTC
**Is your suggestion for improvement related to a problem? Please describe.**
In the preferences, one can change the language of the UI. The list seems to be sorted arbitrarily.

**Describe the solution you'd like**
It should be sorted alphabetically.

**Additional context**
![283370906-3bcf6027-4646-47f5-9604-95474d5bf33d](https://github.com/JabRef/jabref/assets/320228/7b1f76b9-52e5-4cf7-960e-b1c3d4211357)

**Comment by JannCamilo** [comment] 2023-11-22 09:45
Hello, we are a group of university students and we are interested in this contribution, could you assigned it to us ?

**Comment by HarikaB11** [comment] 2023-11-24 05:50
Hi @Siedlerchr, I would like to work on this issue. Please consider my request as I am working on it as a part of College project.

**Comment by newma2n** [comment] 2023-11-28 15:19
Hello, I am part of Jann Sanchez's team.Mechanically speaking, we can say the issue is resolved , but it works for languages except for those that are non-Latin (Arabic, etc.). How can we manage this case? Because we sorted them according to "displayename."

**Closed** 2023-12-10 13:21 UTC
Labels: type: enhancement, preferences, good first issue, FirstTimeCodeContribution
