### ISSUE TITLE
Tech Report sections do not properly sync with selected paper

### ISSUE THREAD

**Issue by Alexandra124** [JabRef/jabref#11018] opened 2024-03-13 16:20 UTC
### JabRef version

5.12 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 11

### Checked with the latest development build (copy version output from About dialog)

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Select a paper -> Tech Report panel opens, showing that paper
2. Select a different paper -> Tech Report panel tabs (e.g. "General", "Abstract") sometimes still display data of the previously selected paper or a mix of data from the currently and the previously selected paper (see Screenshot)
3. When switching between Tech Report panel tabs "General" and "Abstract", JabRef might show different abstracts and titles for the same element, although no other paper has been selected in the meantime

In order for the Tech Report panel to sync with the currently selected paper, I tried:
- double-clicking on the selected paper multiple times
- closing & opening the tech report panel 
- saving the bibliography
None of those approaches works.

That the panel is out of sync with the selected paper does not happen all the time but very often and leads to crucial mistakes (e.g. deleting the wrong paper)

### Appendix

...
<details>

<summary>Screenshot</summary>

```
![image](https://github.com/JabRef/jabref/assets/26545677/947ca563-6c8b-48b2-be73-e78e4ab96a8a)
```

</details>

**Comment by Alexandra124** [comment] 2024-03-13 16:25
![image](https://github.com/JabRef/jabref/assets/26545677/fb73ae05-82ac-42a5-ac4f-ce6afe2a36ef)
After switching to "Abstract" tab: a different paper is shown on the right side, not even the same (wrong) paper as in the previous screenshot, although I did not change my paper selection

**Comment by koppor** [comment] 2024-03-13 16:26
This is a duplicate of https://github.com/JabRef/jabref/issues/9172, isnt it?

**Comment by Siedlerchr** [comment] 2024-03-25 18:16
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2024-03-25 18:16 UTC

**Comment by Alexandra124** [comment] 2024-03-29 20:22
Thank you for the fix! Yes, it works great in the dev version :)
