### ISSUE TITLE
After creation of a group, the group should be focused

### ISSUE THREAD

**Issue by koppor** [JabRef/jabref#11449] opened 2024-07-04 07:44 UTC
1. Create a new library
2. Ensure that "Groups" are visible:\
   ![image](https://github.com/JabRef/jabref/assets/1366654/7b185c30-2e0e-4eb7-b2c3-f659fd73608c)
3. Create new Group "Test": Click on "Add group" (below), enter "Test" as name, click "OK"\
   ![image](https://github.com/JabRef/jabref/assets/1366654/fd43bb0d-100f-4d47-a777-39a2608b3bd9)
4. Result: Group "Test" created, group "All entries" focused:\
   ![image](https://github.com/JabRef/jabref/assets/1366654/ad0de5ae-13ee-446d-a31c-42c8bf9a3bde)

Expected result: Group "Test" focused:

![image](https://github.com/JabRef/jabref/assets/1366654/abd3b7e5-5301-4f2c-bb4d-2f0e3f6711ab)

---

This issue is very much about code reading and understanding how JavaFX and JabRef works. The fix itself probably will be three lines of code. The challenge is really: Which three lines and where to put these lines.

**Comment by Divyam2806** [comment] 2024-07-04 16:20
i am trying to recreate the issue, how do you create a new group, where is that option available?

**Comment by Divyam2806** [comment] 2024-07-04 17:49
I think i know where to add those "three lines", in src/main/java/org/jabref/gui/groups/GroupTreeViewModel.java there is a function addNewGroupToRoot() which is called when a new group is made using the "Add group button" but i cant figure out which function to call inside this function so that the newly added group should be focused. I think its maybe setSelectedGroup() function of StateManager class but i am not able to use it correctly, any help is appreciated.

**Comment by m-peeler** [comment] 2024-07-05 06:55
I've made a fork and a branch on it that is able to successfully select and focus the new node - hooray! 

However, I wonder if this actually intended behavior? In many use cases, I can imagine wanting to select a number of entries, create a new group, and add them to that group. In the current version, this is straightforward: select entries -> 'Add group' -> right click on group -> 'Add selected entries.' 

The new behavior, however, means that changing the group will deselect those entries. Now, if a person attempts to select before making the group, their selection will be lost *and* they'll have to navigate back to the previous page before they can reselect -> right-click on group -> 'Add selected entries.'

I might suggest two options, which sort of go hand-in-hand. One is a new option in the 'Add group' dialogue's 'Collection options', which would be 'From selection' and include all selected entries. The second would be that right clicking on an entry or a group of selected entries would allow the option to 'Add group from selection,' which would launch the 'Add group' dialogue with the 'From selection' option pre-selected. Both would reduce the length of time it takes to generate a group in this manner, and seem fairly straight forward to implement.

I'll submit a pull request with the current fix, but think it may be wise to implement these sorts of feature additions before it is merged into main. If this seems reasonable, I would be happy to go ahead and work to implement those changes.

**Comment by Divyam2806** [comment] 2024-07-05 10:20
> Building on Divyam's sluthing, I've made a fork and a branch on it that is able to successfully select and focus the new node.
> 
> However, I wonder if this actually desirable behavior? In many use cases, I can imagine wanting to select a number of entries, create a new group, and add them to that group. In the current version, this is straightforward: select entries -> **Add group** -> right click on group -> **Add selected entries.**
> 
> The new behavior, however, means that changing the group will deselect those entries. Now, if a person attempts to select before making the group, their selection will be lost _and_ they'll have to navigate back to the previous page before they can reselect -> right-click on group -> **Add selected entries.**
> 
> I might suggest two options, which sort of go hand-in-hand. One is a new option in the **Add group** dialogue's **Collection options**, which would be **From selection** and include all selected entries. The second would be that right clicking on an entry or a group of selected entries would allow the option to **Add group from selection,** which would launch the **Add group** dialogue with the **From selection** option pre-selected. Both would reduce the length of time it takes to generate a group in this manner, and seem fairly straight forward to implement.
> 
> I'll submit a pull request with the current fix, but think it may be wise to implement these sorts of feature additions before it is merged into main. If this seems reasonable, I would be happy to go ahead and work to implement those changes.

can i ask which function did you finally end up using to focus the added group, for my knowledge?

**Comment by m-peeler** [comment] 2024-07-05 11:08
Had to change things in three spots: 

1) In `GroupTreeViewModel.addNewSubgroup()`, add the subgroup to the parent, and use the return value to instantiate a new `GroupNodeViewModel` that you put into `GroupTreeViewModel.selectedGroups`.
```
                GroupTreeNode newSubgroup = parent.addSubgroup(group);
                selectedGroups.setAll(new GroupNodeViewModel(database, stateManager, taskExecutor, newSubgroup, localDragboard, preferences));
```
2) In `GroupTreeView`, when registering a bidirectional binding between the `treeView`'s `getSelectionModel().getSelectionItems()` and the `viewModel`'s `getSelectionGroups()`, I updated the callback function for changes in the `treeView` to clear the contents of `groupTree.getSelectionModel()` before adding new selections to it.

3) In the `StateManager`, I similarly cleared the contents of `StateManager.selectedGroups` before adding new items.

Trickiest part was that the state was being stored in three separate places, and I had to figure out how to keep the updates between the three of them accurate.

**Comment by koppor** [comment] 2024-07-05 11:23
> I might suggest two options, which sort of go hand-in-hand. One is a new option in the **Add group** dialogue's **Collection options**, which would be **From selection** and include all selected entries. The second would be that right clicking on an entry or a group of selected entries would allow the option to **Add group from selection,** which would launch the **Add group** dialogue with the **From selection** option pre-selected. Both would reduce the length of time it takes to generate a group in this manner, and seem fairly straight forward to implement.

Both are cool. I think, the first one is even more simpler to implement

![image](https://github.com/JabRef/jabref/assets/1366654/b4b4f687-8039-4db1-916a-5c0d5e3e8b38)

Add checkbox - and remember in the preference the state of the checkbox.

**Comment by m-peeler** [comment] 2024-07-05 12:26
> Add checkbox - and remember in the preference the state of the checkbox.

Yes, exactly what I was thinking. Since it really only matters as an option if you currently have entries selected, instead of messing with preferences, I think it would make more sense to pass `GroupDialogViewModel` the currently-selected entries and, if the list is not empty, default to this `From selection` option. I might also try greying out the option if there are no currently-selected entries?

**Closed** 2024-07-09 07:28 UTC
Labels: component: ui, component: groups, good first issue, 📌 Pinned
