### ISSUE TITLE
Linked files preference ignored when changed

### ISSUE THREAD

**Issue by shaman1892** [JabRef/jabref#8385] opened 2022-01-04 17:40 UTC
### JabRef version

5.4 (latest release)

### Operating system

GNU / Linux

### Details on version and operating system

Fedora 34 Linux 1 5.15.12-100.fc34.x86_64  JabRef 5.4--2021-12-20--ab44182 Linux 5.15.12-100.fc34.x86_64 amd64 Jabref v 5.4  Java 16.0.2  JavaFX 17.0.1+1

### Checked with the latest development build

- [ ] I made a backup of my libraries before testing the latest development version.
- [ ] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1.   assign a directory for all downloaded external files (pdf etc.)  Preference -> Linked Files -> Main Files Directory
2.  Open a library and work normally importing a reference useing the web extension
3.  Close Jabref
4. Run Jabref with the library just created at step 2
5. Change Linked file preferences. Select  Preference -> Linked Files -> search and store files relative to library file location.
6. Import from the web a new paper using the web extension plugin
7. verify that Jabref keeps saving the files in the old location
8. Select again the Preference -> Linked Files -> Main Files Directory and delete the string of the old directory so that the text field is empty.
9. select again  Preference -> Linked Files -> search and store files relative to library file location
10.  verify that this time the new preference is applied correctly

### Appendix

![Screenshot from 2022-01-04 18-33-46](https://user-images.githubusercontent.com/97118223/148100465-981903bf-f68f-43b0-af1d-438423d2d5f7.png)

**Comment by Siedlerchr** [comment] 2022-01-04 18:08
@calixtus  Is this related to the problem we discussed yesterday, or this is this just related to the fact that the Linked File prefs were not yet converted to the new ones?

**Comment by calixtus** [comment] 2022-01-07 11:27
Sorry for the late reply. This is related to `FilePreferences`, but it should not be affected by the bug we discussed, since that bug probably only affects complete reset of all preferences. This seems to be somehow related to the empty textfield. Maybe there is a check in the dialog tabs viewmodel or in the preferences for empty strings, that are not stored? I'll look into it.

**Comment by calixtus** [comment] 2022-01-07 11:56
No, it seems that JabRef always applies the text in the textfield, even if it's greyed out.
I suspect: `BibDatabaseContext::getFileLinks` is called somewhere in a constructor a object creation time, since 
![grafik](https://user-images.githubusercontent.com/50491877/148540530-11e2693e-d907-42cf-8d4b-8ca3de27a253.png)

Perhaps there needs to be binding somewhere the preference looked up to?

**Comment by Siedlerchr** [comment] 2022-01-07 19:38
It should be sufficient to check if the other radio button is enabled:

`if (storeFilesRelativeToBibFile.getValue() || StringUtil.isBlank(mainFileDirectory.getValue())) {`

**Comment by calixtus** [comment] 2022-01-07 19:59
Yes, but that would not solve the root cause of the problem and it's not certain, if it really solves the problem, since the value of the text field may be still be kept.

**Comment by Siedlerchr** [comment] 2022-01-07 20:02
The value of the text field might be kept, that's okay - as long as it's not used

**Comment by ThiloteE** [comment] 2022-01-08 11:24
Duplicate of this problem in the forums: https://discourse.jabref.org/t/a-strange-bug-if-i-add-a-library/3118/10

**Closed** 2022-01-16 18:06 UTC
Labels: type: bug 🐛, preferences
