### ISSUE TITLE
No utf8 encoding while fetching from Medline

### ISSUE THREAD

**Issue by bernhard-kleine** [JabRef/jabref#2060] opened 2016-09-25 11:57 UTC
JabRef 3.6
windows 7 6.1 amd64 
Java 1.8.0_66

Steps to reproduce:

1. Ensure that you have utf8 as the preferred encoding 
2. import from pubmed/medline ID 27653033
3. notice that the import does not show the alphas and betas in the title and in the abstract.

I would expect utf8 encoding for the import since the medline has really a good way to deal with the alphas and betas, as well as any other greek letters or even japanese or other languages. While the utf8 encoding does well work in jabref, it is ?ommited? in the import. Please change. 
```

**Comment by Siedlerchr** [comment] 2016-09-25 12:37
Thanks for your report. I could not reproduce that issue in the latest development version. All Betas and Alphas etc are shown correctly. Database encoding is set to UTF8.
Please try again with the latest master from here: http://builds.jabref.org/master/

**Comment by bernhard-kleine** [comment] 2016-09-25 12:51
I just installed:
JabRef 3.7dev--snapshot--2016-09-25--master--693c705
windows 7 6.1 amd64 
Java 1.8.0_66
I have utf8 default encoding for the database: Importing PMID:27653033 still gives me in the title:
title = {Effects of 17Î²-estradiol and androgen on glucose metabolism in skeletal muscle.},
instead of
Effects of 17β-estradiol and androgen on glucose metabolism in skeletal muscle.
The entry 27653033 in firefox on the shows the β as well and also the alphas in the abstract. What do I have to do for proper import?

**Comment by grimes2** [comment] 2016-09-25 13:00
JabRef 3.7dev--snapshot--2016-09-25--master--693c705
windows 10 10.0 amd64 
Java 1.8.0_101

I can confirm: Î²

**Comment by Siedlerchr** [comment] 2016-09-25 13:01
Okay, I have an idea. And I will release a fix soon.

**Comment by Siedlerchr** [comment] 2016-09-25 13:15
When I am right it should be now correct:

![utf8medline](https://cloud.githubusercontent.com/assets/320228/18815448/f9e0dde6-8331-11e6-8a19-41bd4827237a.png)

You can try this snapshot:
http://builds.jabref.org/medlineutf8/

**Comment by grimes2** [comment] 2016-09-25 13:21
Works here too. 👍

**Comment by bernhard-kleine** [comment] 2016-09-25 13:43
works! Thank you for a fast correction!

**Comment by bernhard-kleine** [comment] 2016-09-25 13:51
BTW where is the line for the DOI search in this snapshot?

**Comment by Siedlerchr** [comment] 2016-09-25 15:17
@bernhard-kleine  DOI? I don't know to what problem you refer to. The DOI ID-Fetcher (not fulltext) already uses UTF-8.

**Comment by Siedlerchr** [comment] 2016-09-25 15:20
Fixed in #2061

**Closed by Siedlerchr** 2016-09-25 15:20 UTC
Labels: fetcher

**Comment by lenhard** [comment] 2016-09-25 16:51
That was quite quick. Three ours from report to fix. Great job @Siedlerchr

**Comment by bernhard-kleine** [comment] 2016-09-25 17:10
There does not seem a DOI fetcher in the web seach list at the moment. Has it changed his place?

**Comment by Siedlerchr** [comment] 2016-09-25 17:31
@bernhard-kleine  Oh. I now understand what you mean, yeah, I can confirm this. 
There has been some work on the DOI fetcher, but It should not be gone. I will create a new issue for that.

**Comment by Siedlerchr** [comment] 2016-09-25 17:34
@bernhard-kleine  All ID-based fetchers have been moved to the New Entry dialog
New BibTeX Entry -> Id based entry generator:
![entrytype](https://cloud.githubusercontent.com/assets/320228/18817062/16fa3e70-8357-11e6-9182-9760c8cfce69.png)

**Comment by koppor** [comment] 2016-09-25 17:39
DOI Fetcher is now in the new entry dialog as it fetches a single id only

**Comment by bernhard-kleine** [comment] 2016-09-25 17:43
Seen and tested. Thank you
