### ISSUE TITLE
File links completely broken after update to v5.2

### ISSUE THREAD

**Issue by EliasBRL** [JabRef/jabref#7261] opened 2020-12-28 16:19 UTC
JabRef version 5.2 on Windows 10

- [X] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

I like to keep a local PDF copy of all papers I read. The PDFs are in the same directory as my `JabRef.bib`. In JabRef version 5.1, I linked each PDF to its JabRef entry via `General -> File -> +`.

After updating to version 5.2, all links are broken. When I click on any "PDF button" in the overview, JabRef opens my `Documents` directory (which is not the directory where I store the PDFs) instead of the PDF.

I am also unable to fix the broken links or add new links. This _appears_ to work (I can browse my files, select the desired file, and it is displayed under `General -> File`), but when I click on the "PDF button", it just opens the `Documents` directory as before... 

1. Create new entry
2. Add PDF file
3. Click on "PDF button" in the overview

**Comment by Siedlerchr** [comment] 2020-12-28 16:26
Duplicate of #7259

**Closed by Siedlerchr** 2020-12-28 16:26 UTC
