### ISSUE TITLE
Right click will change the selected entry

### ISSUE THREAD

**Issue by iTao8** [JabRef/jabref#2940] opened 2017-06-24 16:31 UTC
JabRef 4.0.0-dev--snapshot--2017-06-22--master--bee062c6a
Mac OS X 10.11.6 x86_64 
Java 1.8.0_131

1. open a .bib file
2. click an entry to make it is selected
3. right click it (the selected entry will be changed to the next)
4. choose "copy"
5. copy + v

You will find the copied entry is the next entry in the bib file.

**Comment by Siedlerchr** [comment] 2017-06-26 12:11
I tested under Xubuntu 16.10 and I can not reproduce this.
JabRef 4.0.0-dev
Linux 4.4.0-81-generic amd64 
Java 1.8.0_131

**Comment by iTao8** [comment] 2017-06-26 14:53
It appeared in some previous versions. This problem is very strange, it seems that sometimes it works well, but sometimes it does not. I restarted my computer today, and this problem disappeared. I'm not sure whether you can reproduce it at any time.

**Comment by iTao8** [comment] 2017-06-26 14:59
Now, this problem appears again, this happens on some entries, not all the entries.

**Comment by Siedlerchr** [comment] 2017-06-26 16:41
Could you please try to narrow it down and provide us the bib file?
If you do not want to upload it public, you can send it to developers@jabref.org

**Comment by notuntoward** [comment] 2017-07-03 05:36
I've seen this problem too, but also haven't been able to reliably reproduce it.

**Comment by stefan-kolb** [comment] 2017-07-20 15:01
Duplicate of #2627?

**Comment by iTao8** [comment] 2017-07-21 10:23
@stefan-kolb Yeap!

**Closed** 2017-07-21 11:03 UTC
Labels: osx
