### ISSUE TITLE
5.9 OS-X AMD binaries are not working

### ISSUE THREAD

**Issue by stephenc** [JabRef/jabref#9634] opened 2023-02-21 11:18 UTC
### JabRef version

5.9 (latest release)

### Operating system

macOS

### Details on version and operating system

Ventura 13.1 running on Intel Core i7

### Checked with the latest development build

- [X] I made a backup of my libraries before testing the latest development version.
- [X] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Download https://www.fosshub.com/JabRef.html?dwl=JabRef-5.9.dmg
2. Check the SHA256 sum of the download
  ```
  $ sha256sum ~/Downloads/JabRef-5.9.dmg 
  53db743600453ecca840547ddd43323c16d34bdd7ce69ce50b8f58bd1c27f3ad  /Users/stephenc/Downloads/JabRef-5.9.dmg
  ```
3. Try to run
<img width="372" alt="Screenshot 2023-02-21 at 11 16 31" src="https://user-images.githubusercontent.com/209336/220330655-e71e5c3c-0847-4d64-9dcf-b89903d308c2.png">

### Appendix

Version 5.8 download is fine

**Comment by Siedlerchr** [comment] 2023-02-21 17:20
It's an issue with Apple notarization. You have to open the terminal and execute

` xattr -d com.apple.quarantine /Applications/JabRef.app `

Duplicate of #9553

**Closed by Siedlerchr** 2023-02-21 17:20 UTC
