### ISSUE TITLE
4.0 Group view: freeze when organizing groups with drag&drop

### ISSUE THREAD

**Issue by JonGolcha** [JabRef/jabref#3345] opened 2017-10-25 10:16 UTC
JabRef version 4.0 on Mac OS Sierra 10.12.6

Steps to reproduce:

1. do a few drag&drops to reorganize groups
2. at some point (often after only 1 or 2 group moving) nothing happens when reorganizing groups.
3. after a few unworking tries, application freezes

**Comment by lenhard** [comment] 2017-10-25 14:20
It seems that Mac OS Sierra and JavaFX do not go together nicely. 

Please make sure that your Java8/JavaFX runtimes are up-to-date.

Also, could you have a look at #3227 and  try out the hostname solution described there?

**Comment by JonGolcha** [comment] 2017-10-30 17:01
- Installing the latest version of [Java8, update 151] https://www.java.com/en/download/mac_download.jsp) doesn't solve the group drag&drop issue.
- Installing [Java SE Runtime Environment 9](http://www.oracle.com/technetwork/java/javase/downloads/jre9-downloads-3848532.html)
leads to Jabref not loading at all (only Jabref name displayed in the menu bar, I suppose this version of Java is not currently supported).
- I also tried out the hostname solution, in vain.

**Comment by Siedlerchr** [comment] 2017-10-30 22:00
@JonGolcha  Java 9 is not supported yet.
This seems to a real Mac only problem. I can not reproduce this under Windows. It could help if you try starting JabRef from command line via java -jar JabRef.jar and see if there is any error logged when a freeze happens.

And also please try the latest dev version: http://builds.jabref.org/master/

**Comment by lenhard** [comment] 2017-11-06 08:53
Any success with the newest development version?

**Comment by JonGolcha** [comment] 2017-11-13 11:27
Sorry for long delay replying.
Same non-functionning of group drag&drop with the last development version (JabRef-4.1-dev--snapshot--2017-11-10--master--dba8db5db).

Also I tried starting JabRef from command line via java -jar JabRef.jar to see log errors, but couldn't run it:

> sudo java -jar JabRef-4.1-dev--snapshot--2017-11-10--master--dba8db5db.jar
12:22:13.610 [AWT-EventQueue-0] ERROR org.jabref.FallbackExceptionHandler - Uncaught exception occurred in Thread[AWT-EventQueue-0,6,main]
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.jabref.logic.importer.ImportFormatReader.resetImportFormats(ImportFormatReader.java:55) ~[JabRef-4.1-dev--snapshot--2017-11-10--master--dba8db5db.jar:?]
	at org.jabref.JabRefMain.start(JabRefMain.java:97) ~[JabRef-4.1-dev--snapshot--2017-11-10--master--dba8db5db.jar:?]
	at org.jabref.JabRefMain.lambda$start$0(JabRefMain.java:53) ~[JabRef-4.1-dev--snapshot--2017-11-10--master--dba8db5db.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764) ~[?:?]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[?:?]
	at java.awt.EventQueue$3.run(EventQueue.java:717) ~[?:?]
	at java.awt.EventQueue$3.run(EventQueue.java:711) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[?:?]
	... 17 more

**Comment by Siedlerchr** [comment] 2017-11-13 11:47
You are still using java 9. You have to downgrade to Java 8

**Comment by lenhard** [comment] 2017-11-24 08:55
Nothing has happened here in a while and it seems to boil down to a wrong Java version. Hence, I am closing it now.

In case the problem also appear with a recent Java 8 JRE, feel free to re-open.

**Comment by tegedo** [comment] 2017-12-27 03:31
I'd like to re-open this thread. I am using Centos 7 and installed JDK 8 from Oracle 
javafx.properties:
javafx.runtime.version=8.0.152
javafx.runtime.build=b16

Using groups is not possible as JabRef-4.1 instantly freezes. There is also an issue with the UI fonts as all descender are cut off and changes (override) in appearance does nothing.

Other than that it seems to works fine, however, I have to stick to JabRef-3.8.2 as I need to work with groups. Please post suggestions of let the rest of us know when the issues with groups and Javafx is fixed.

Thanks!

**Comment by tegedo** [comment] 2017-12-27 05:46
I'd like to re-open this thread:

Using Centos 7 and installed JRE 8 151, no luck, uninstalled; installed 152, each using rpm methods. No success, JabRef-4.0 and 4.1 freezes upon click on any group item.

JabRef 3.8.2 works fine. I see the issue with JabRef and not within the install method of Java.

**Comment by tegedo** [comment] 2017-12-27 06:18
Hi, I had the same problem with Java and JabRef, fiddled with this stuff for hours with different versions of Java, I am using Centos 7.

The problem was finally solved by changing the UI to "javax.swing.plaf.metal.MetalLookAndFeel"

Hope that helps

**Comment by lenhard** [comment] 2018-02-06 18:05
So it seems to be related to the look-and-feels. We have no action points here, so I am closing this.

**Closed by lenhard** 2018-02-06 18:05 UTC
Labels: bug, groups, osx
