### ISSUE TITLE
JabRef 4.1-dev freezes when automatically downloading PDFs on Linux 

### ISSUE THREAD

**Issue by i2000s** [JabRef/jabref#3406] opened 2017-11-06 03:15 UTC
On Windows 10, it works. On Ubuntu, there is the following issue. 

JabRef version:

JabRef 4.1-dev--snapshot--2017-11-05--master--b42825cfb

Linux 4.10.0-38-generic amd64 

Java 1.8.0_151

OS: Ubuntu 16.04.3 kernel 4.10.0-38

Steps to reproduce:

1. Open JabRef on Linux with `java -jar JabRef-4.1.jar`
2. Double click an article entry and go to the General tab
3. Click on the Download (if you have the URL for the PDF) or Auto Search for PDF download button.
4. While it's downloading files, the program freezes.

<details>
  <summary>Log File</summary>
  
  ```
  $ java -jar JabRef-4.1.jar 
  AI: INFO 05-11-2017 20:09, 20: Configuration file has been successfully found as resource
  Error parsing gtk-icon-sizes string: ''
  20:09:12.517 [AWT-EventQueue-0] INFO  org.jabref.logic.importer.OpenDatabase - Opening: 
  /media/test/References/Archive/Archive.bib
  File: grouptree.fxml not found, attempting with camel case
  File: grouptree.css not found, attempting with camel case
  ```
</details>

**Comment by lenhard** [comment] 2017-11-06 08:52
Which look and feel are you using? If it is the GTK look and feel, please try another one: https://help.jabref.org/en/Installation#freezes-when-running-jabref

**Comment by Siedlerchr** [comment] 2017-11-06 13:45
I can not reproduce this, Ubuntu 16.10 with Xfece and Plastic Look and Feel
abRef-4.1-dev--snapshot--2017-11-06--master--02c9be92c.jar

**Comment by i2000s** [comment] 2017-11-06 22:37
Interesting, switching the Look and Feeling to Plastic3D seems to have changed the behavior by a lot. However, there is still some instability happening to me--the tabs become blank after I pasted another bibtex entry.
Screenshot:
![screenshot from 2017-11-06 14-54-31](https://user-images.githubusercontent.com/3915003/32466774-550dcbfc-c305-11e7-8bd8-b9dbdb2d051c.png)

Here is what I did:
I changed the Look and Feel to Windows Plastic, and then restarted JabRef. I found it doesn't work and the program automatically reversed to the default Look and Feeling. Then I changed the Look and Feeling to the jgoodies Plastic3D one, and saved everything. It seems working ok, but there are some errors on the prompts. You can find the full log of output [here](https://paste.ubuntu.com/25906162/).

Then I restarted the program, and the failure happens in a strange way. First, I added a bibtex entry by pasting a bibtex code to the table. Downloaded the PDF using the automatic search and download button. It worked well until then, and I saved the database. I thought it wouldn't have any problems, so I opened the Preference window and exported the settings to the saved file as you can see from my linked commit to this issue. There seem to be some errors or maybe just warnings in the terminal, and I didn't think they are really causing anything fatal. Then I pasted another bibtex entry to the table, saved it, and tried to generate the bibtex key. I look down to the tabs--they are all blank now as you can see from the screenshot attached. I clicked a few buttons, including Generate bibtex key, Save, Quality --> generate bibtex key and maybe a few other buttons. It didn't return to normal. So, I closed JabRef. The full terminal record for these steps can be found [here](https://paste.ubuntu.com/25906123/). 

But this issue didn't reoccur if I just use the program normally, like adding multiple entries in a row, auto-downloading PDF files and so on. I only have 3 Look and Feeling profiles and have tried all of them. 2 didn't work at all, the Plastic3D one caused this blank window issue to me. Let me know if I can provide further information. Or, maybe it should be a separate non-crucial issue to discuss for this update.

Thanks,

Qi

**Comment by Siedlerchr** [comment] 2017-11-07 07:50
Hi, there had been some problem with the entry editor the last days. Could you please try with the latest master version?

**Comment by LinusDietz** [comment] 2017-11-07 10:14
@Siedlerchr It also happens on my system with current master. I guess this just needs more investigation. Sometimes there is a suspicious log entry (IndexOutOfBoundsException), sometimes not.

**Comment by Siedlerchr** [comment] 2017-11-07 16:20
I could reproduce this partially when executing Look up Fulltext documents in a row.

```
onHandler - Uncaught exception occurred in Thread[JavaFX Application Thread,5,main]
java.lang.IndexOutOfBoundsException: [-2147483648, 1) is not a valid range within [0, 1)
	at org.reactfx.util.Lists.checkRange(Lists.java:128) ~[reactfx-2.0-M5.jar:?]
	at org.reactfx.util.Lists.checkRange(Lists.java:123) ~[reactfx-2.0-M5.jar:?]
	at org.reactfx.collection.MemoizationListImpl.forget(MemoizationList.java:184) ~[reactfx-2.0-M5.jar:?]
	at org.fxmisc.flowless.CellListManager.cropTo(CellListManager.java:82) ~[flowless-0.6.jar:?]
	at org.fxmisc.flowless.CellPositioner.cropTo(CellPositioner.java:29) ~[flowless-0.6.jar:?]
	at org.fxmisc.flowless.Navigator.cropToNeighborhoodOf(Navigator.java:227) ~[flowless-0.6.jar:?]
	at org.fxmisc.flowless.Navigator.placeStartAtMayCrop(Navigator.java:200) ~[flowless-0.6.jar:?]
	at org.fxmisc.flowless.Navigator.visit(Navigator.java:129) ~[flowless-0.6.jar:?]
	at org.fxmisc.flowless.StartOffStart.accept(TargetPosition.java:85) ~[flowless-0.6.jar:?]
	at org.fxmisc.flowless.Navigator.layoutChildren(Navigator.java:78) ~[flowless-0.6.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1087) ~[jfxrt.jar:?]
	at org.fxmisc.flowless.VirtualFlow.layoutChildren(VirtualFlow.java:257) ~[flowless-0.6.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1087) ~[jfxrt.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
	at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:?]
	at javafx.scene.Scene.doLayoutPass(Scene.java:552) ~[jfxrt.jar:?]
	at javafx.scene.Scene.preferredSize(Scene.java:1646) ~[jfxrt.jar:?]
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720) ~[jfxrt.jar:?]
	at javafx.stage.Window$9.invalidated(Window.java:864) ~[jfxrt.jar:?]
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109) ~[jfxrt.jar:?]
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144) ~[jfxrt.jar:?]
	at javafx.stage.Window.setShowing(Window.java:940) ~[jfxrt.jar:?]
	at javafx.stage.Window.show(Window.java:955) ~[jfxrt.jar:?]
	at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58) ~[jfxrt.jar:?]
	at javafx.embed.swing.JFXPanel.lambda$addNotify$51(JFXPanel.java:833) ~[jfxrt.jar:?]
	at com.sun.javafx.application.PlatformImpl.lambda$null$172(PlatformImpl.java:295) ~[jfxrt.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_152]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$173(PlatformImpl.java:294) ~[jfxrt.jar:?]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:?]
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177) ~[jfxrt.jar:?]
```
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

**Comment by Siedlerchr** [comment] 2017-12-03 10:24
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Comment by lenhard** [comment] 2017-12-05 15:34
@Siedlerchr You forgot to actually close it ;)

**Closed by lenhard** 2017-12-05 15:34 UTC
Labels: bug, entry-editor, linux, waiting-for-feedback
