### ISSUE TITLE
Moving between entries in the main table (File annotations Tab)

### ISSUE THREAD

**Issue by stefan-kolb** [JabRef/jabref#2675] opened 2017-03-21 13:33 UTC
When moving between entries in the main table, the focus should stay on the same tab in an open entry editor if possible.
E.g., if I'm currently looking at file annotations it should stay on this tab when switching to another entry in the main table but not focus the required fields tab.

__Looks like this is a specific problem with the file annotations tab!__

**Comment by lynyus** [comment] 2017-07-14 08:50
This is now a duplicate of https://github.com/JabRef/jabref/issues/2896.

**Closed by lynyus** 2017-07-14 08:50 UTC
Labels: beginner, duplicate, enhancement, ui
