### ISSUE TITLE
Runaway process, High CPU and RAM usage for large databases when autocompletion preference is enabled 

### ISSUE THREAD

**Issue by umuen** [JabRef/jabref#6967] opened 2020-10-01 16:27 UTC
JabRef version JabRef 5.2--2020-09-29--2d92025 on Mac OS X 10.15.7

- [x] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

**Symptoms:**

- Starting JabRef results nearly always in runaway behaviour, laptop cooling system kicks in, a 'top' shows 600-800% processor used by jabref. Sometime this starts directly, sometimes only after a few minutes.
- Then finishing the programme with "Quit" sometimes closes window (sometimes not), but process still active
- has to be killed via "Force Quit" that often shows programme as "not reacting"

**Steps to reproduce the behavior:**

1. switch on JabRef
2. a normal search within a database normally triggers behaviour
3. sometimes also just clicking on an entry triggers it

Behaviour was always there, for all developer versions of jabref 5.2 and 5.1 that I tried. Also for Mac OS X 10.15.6.

Seems strongly to depend on database size. For 50 entries it seems ok, but for 500 not. My standard data base is more like 10000.

**Comment by Siedlerchr** [comment] 2020-10-03 14:05
Thanks for the report. I could partially reproduce this. I tested with a library of around 6500 entries. It seems to be related to the search. When I search the cpu goes up, but stil okay, but when I then cancel (or X the search), my laptop fan also goes  high. Trying to quit it seems not to work either. Somehow a thread is still active in the backgrond.

**Comment by chrisdebrunner** [comment] 2020-10-29 14:40
I see a similar problem with Jabref 5.1 under RHEL 7.9. I start JabRef and it uses 5-10% CPU after startup. Then I type into the search field, and CPU jumps to 600-700% and stays there even after I cancel the search (press the "x" at the right end of the search box) and if I close the GUI by clicking the close box in the upper right. I have to kill the JabRef process from the command line.

**Comment by christophe-gouel** [comment] 2020-11-03 14:13
I have exactly the same issue with JabRef 5.1 under Windows 10 and a library of around 5000 entries. A search (or just some waiting time) starts the problem and closing JabRef normally is not enough.

![image](https://user-images.githubusercontent.com/668630/97995574-f7158b80-1de6-11eb-9007-8c48645b4b6d.png)

**Comment by Siedlerchr** [comment] 2020-11-04 17:30
Thanks all for the reports. Does it help if you disable the autocompletion in the preferences?

**Comment by christophe-gouel** [comment] 2020-11-05 10:26
Yes, it seems to solve the problem. Thanks.

**Comment by umuen** [comment] 2020-11-05 10:36
Yes, indeed, everything seems fixed on my machine when autocompletion is disabled.

thanks
uwe

**Comment by chrisdebrunner** [comment] 2020-11-05 19:45
I also did not see the problem anymore after disabling autocompletion. 

I was glad to learn that autocompletion could be turned off, as it would pop up an annoying menu and disable typing whenever I typed a { or } in the Title field (and presumably the other affected fields).

Thank Siedlerchr for proposing this simple workaround.

--Chris

**Comment by christophe-gouel** [comment] 2021-05-06 06:29
Since Nov 2020, I have used JabRef without autocompletion and was very satisfied with it. To check if the issue was still relevant, I have just reactivated the autocompletion. After 30 seconds, the processors were fully saturated and closing JabRef (5.2) was not enough since it stays open in the background.

So the issue is still there, but if people are happy to work without autocompletion, which is my case, then this is not a pressing issue.

**Comment by chrisdebrunner** [comment] 2021-05-08 04:29
I was able to reproduce this error under RHEL 7 with JabRef 5.2, but not under Mac OS X 11.1 with JabRef 5.2.  Note that under RHEL 7, JabRef 5.2 crashes if I start it by executing ${JabRefRoot}/bin/JabRef, so I instead execute ${JabRefRoot}/lib/runtime/bin/JabRef.

**Comment by ilippert** [comment] 2022-08-23 08:12
This links to https://github.com/JabRef/jabref/issues/8906

**Comment by HoussemNasri** [comment] 2023-08-13 02:08
Hello everyone, please try this [build](https://builds.jabref.org/pull/10159/merge/) and see if the problem persist.

**Closed** 2023-08-13 16:32 UTC
Labels: search, autocompletion, type: performance
