### ISSUE TITLE
Auto file dowload does not access source subdirectories

### ISSUE THREAD

**Issue by HainesB** [JabRef/jabref#1127] opened 2016-04-06 20:01 UTC
In database properties, I specify this: "/storage/jabref/". This jabref directory has three subdirectories: docs, reviews and notes. Auto indexing usually, but not always sees PDFs in the docs subdirectory, but never finds them in the reviews subdirectory. 

For example, one bibtex entry is Adams1988. In /storage/jabref/reviews/ there exists the file Adams1988-Ingold-review.pdf. When I click Auto, I get the popup: "Full text article download failed". I have to index the file manually: +, Open, enter Adams1988*, when I click on Open it displays Adams1988-Ingold-review.pdf. I Open it and then Save it. Now in the File field appears reviews/Adams1988-Ingold-review.pdf.

**Comment by stefan-kolb** [comment] 2016-04-06 21:32
Duplicate of #1124. @JabRef/developers You can try to reproduce this, I could not.

**Comment by stefan-kolb** [comment] 2016-04-06 21:37
Exactly the same setup, works as expected:
![image](https://cloud.githubusercontent.com/assets/2141507/14333734/7aecee34-fc50-11e5-882a-d224a580c0b5.png)

Please try the latest dev version at http://builds.jabref.org/master/. Maybe it is an old bug already fixed on master, as you didn't provide which JabRef version you are using.

**Comment by stefan-kolb** [comment] 2016-04-15 11:03
@HainesB Does this issue also occur for you when using the latest build from http://builds.jabref.org/master/?

**Comment by stefan-kolb** [comment] 2016-05-17 19:29
Closing this issue due to inactivity :zzz: 
Please reopen the issue with additional information if the problem persists.

**Closed by stefan-kolb** 2016-05-17 19:29 UTC
Labels: waiting-for-feedback
