### ISSUE TITLE
Click "Right Click" on the local attached file button, always open the first file attached to the entry.

### ISSUE THREAD

**Issue by HIT-Modnar** [JabRef/jabref#4186] opened 2018-07-09 11:24 UTC
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

When I have attached files to an entry and click right click on the local attached file button to show the menu, it always open the first local file on the menu.
If there only one local file be attached to the entry, it will open the file automatically, and that should be normal. However, if I have attached two files on the entry, and when I click right click on the local file button, it will also automatically open the file quickly!!! Although it would show it open the menu, it even does't give me the chance to choose opening the second file on the menu.

当我绑定一个本地文件到一个条目上之后，在条目上的“本地文件”按钮上点击右键后，会弹出文件列表，并快速打开列表中第一个文件(而不是在选择打开文件后打开)。
如果某个条目只是绑定一个本地文件，那么这样的问题也可以说是正常。但是当我为一个条目绑定了多个文件后，这个问题就很明显了。当我这时在“本地文件”按钮上点击右键时，依旧会自动打开列表里的第一个文件。虽然点击右键后也会弹出“选项列表”，但此时执行的动作很明显也有“打开文件”。打开文件的速度很快，甚至没等我选择打开第二个文件，第一个文件就已经打开了。

JabRef version  on  4.3.1

This problem just occurred on my computer(OS with macOS High Sierra 10.13.3) and my partner's laptop(OS with Windows 10) hasn't occurred the problem.

目前我只是用我的电脑(系统:macOS High Sierra 10.13.3)测试出了这个问题，我的伙伴的电脑(系统:Windows 10)上并未出现这种直接自动打开文件的问题。

Steps to reproduce:

1. Attach two (or more) files on one entry.
2. Click the right click on the "local file button".
3. It would quickly open the first local file on the menu automatically.

![image](https://user-images.githubusercontent.com/22772190/42447374-35492e70-83ac-11e8-90e1-86e463619f6c.png)

As you see, there are two local files listed on the menu, while it always quickly open the first local file automatically! Even sometime it does't let me see the menu :)

可以看到，点击右键之后，文件就会被打开，这时我甚至还没从右键选项里选择打开文件。有时，弹出的文件窗口甚至会覆盖掉右键选项列表。

**Comment by stefan-kolb** [comment] 2018-07-09 13:54
Thank you for your report :+1:
However, I cannot reproduce this behavior on the current `master`. Can you please try the latest build from http://builds.jabref.org/master.
Also: it should be left click instead of right click. right clicking opens the context menu for the whole entry.

**Comment by HIT-Modnar** [comment] 2018-07-09 14:23
It truly be the right click. I know that when clicking right click, it is supposed to be context menu. And you can see the picture: the context menu is there! The picture was saved when I had clicked right click: the context was just shown but the first file had already been opened.
Thanks, I will try the latest build again.

**Comment by stefan-kolb** [comment] 2018-07-10 10:51
I also checked it on 4.3.1 and it does not occur under Windows. If the current master is ok for you, we will probably not fix this for the 4.x branch.

**Comment by Siedlerchr** [comment] 2018-08-12 18:00
Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/master and report back if it works for you. Please remember to make a backup of your library before trying-out this version.

**Closed by Siedlerchr** 2018-08-12 18:00 UTC
Labels: macOS, waiting-for-feedback
