### ISSUE TITLE
check integrity: title

### ISSUE THREAD

**Issue by grimes2** [JabRef/jabref#419] opened 2015-11-30 11:05 UTC
Check integrity complains always: large capitals are not masked using curly brackets {}
Thats not correct:  (for example) Title = {{C}urrent {C}hronicle},

**Comment by simonharrer** [comment] 2015-11-30 11:10
Cannot reproduce with test case on class that does the check. Can you please double-check?

**Comment by grimes2** [comment] 2015-11-30 11:42
My system seems to be misconfigured.
Every entry is affected.
* In Entry Editor under "Required fields" the title field shows: Current Chronice (without brackets)
* Entry Editor, "Bibtex Source" shows  Title = {{C}urrent {C}hronicle}
Under "Required fields" I have now changed Current Chronice to {C}urrent {C}hronicle and Check integrity doesn't complain anymore.
How can I transfer the brackets from "Bibtex source" to "Required fields"?

**Comment by matthiasgeiger** [comment] 2015-11-30 11:49
Ahhh.. :wink:

The braces in the Source view are marking only the begin and the end of each field: 

```
title  = { My Title With some Capital Letters }
```
If you want to escape capital letters you have to use additional curly braces:

```
title  = { {M}y {T}itle {W}ith some {C}apital {L}etters }
```
or:
```
title  = { {My Title With some Capital Letters} }
```

**Comment by grimes2** [comment] 2015-11-30 11:56
This is correct and I know this for many years, but my Source is
Title = {{C}urrent {C}hronicle}
but it complains
"large capitals are not masked using curly brackets {}"

**Comment by matthiasgeiger** [comment] 2015-11-30 12:22
Are you using the normal BibTeX or BibLaTeX mode?

**Comment by grimes2** [comment] 2015-11-30 12:23
BibTeX mode

**Comment by simonharrer** [comment] 2015-11-30 12:33
Can you attach a .bib file which contains such invalid behavior? Can you also export your settings and attach them as well?

**Comment by matthiasgeiger** [comment] 2015-11-30 12:40
I think I'm able to reproduce this... sorry for closing this issue to early.

After loading the curly braces in the source are not visible in the UI - changing the title by adding curly braces works and is correctly displayed - after changing the source directly the braces are not visible any more...

**Comment by grimes2** [comment] 2015-11-30 12:52
Yes
[grimes2_bib.txt](https://github.com/JabRef/jabref/files/47287/grimes2_bib.txt)
[grimes2_settings_xml.txt](https://github.com/JabRef/jabref/files/47288/grimes2_settings_xml.txt)

**Comment by simonharrer** [comment] 2015-11-30 13:05
When I open your bib file, it displays correctly. And also no issues are found with my preferences configuration. 

Editing in the bibtex source in the entry editor should be no problem. Works with my preferences with no problems. 

Probably an issue with the preferences. But this requires more study (and time ...)

**Comment by grimes2** [comment] 2015-11-30 13:26
I've resetted my preferences with java -jar JabRef-3.0.jar -d all.
Now everything is o.k. Thanks for your effords.

**Comment by grimes2** [comment] 2015-12-05 15:51
I can now reproduce this issue:
* Preferences | File | Store the following fields with braces around capital letters: title
* Restart.

The curly brackets are removed around the capital letters in the field title.
This is maybe, because the field title is by default a field with braces around, so the additional input of "title" in the "Store the following fields with braces around capital letters"-line is causing this trouble.

**Comment by grimes2** [comment] 2015-12-06 06:08
I found this in the FAQ of Jabref:
> Q: BibTeX converts uppercase characters to lowercase in my title field. I know this can be prevented by w rapping uppercase letters in braces, e.g. "{T}he life cycle of {A}tlantic salmon", but this is too much work. Can JabRef help?
> A: JabRef has a setting that will automatically wrap all capital letters for certain fields in { } - this will make sure they are preserved in the LaTeX output. Under Options -> Preferences -> General -> File -> “Store the following fields with braces around capital letters”, make sure the title field is included. To do this for several fields, write e.g. “title;abstract” (without the quotes). This setting automatically adds braces when saving the bib file, but you won't see the braces within JabRef.
(Source: http://jabref.sourceforge.net/faq.php)

So it is by design, that JabRef don't show the braces in the title field, but in the BibTeX-code. But then the check integrity message "large capitals are not masked using curly brackets {}" for the title field doesn't make any sense.

**Comment by lc9275** [comment] 2016-01-07 12:41
I have related issues with curly brackets (using a recent dev jabref version). To reproduce: create a new database, and do doi to bibtex from 10.1175/jamc-d-14-0299. Then:

- In the bib source the title reads " title =         {{AI}{RS}, {IASI}, and {CrIS} {R}etrieval {R}ecords at {C}limate {S}cales: {A}n {I}nvestigation into the {P}ropagation of {S}ystematic {U}ncertainty},"
- In the title field it reads: "{AI}{RS}, IASI, and {CrIS} Retrieval Records at Climate Scales: An Investigation into the Propagation of Systematic Uncertainty." It is unclear to me why some brackets are displayed and others not.
- Check integrity warns "large capitals are not masked using curly brackets".  I am really not sure why since there seem to be enough curly brackets!
- When I do clean up entries, the title field reads {AIRS}, IASI, and {CrIS} Retrieval Records at Climate Scales: An Investigation into the Propagation of Systematic Uncertainty. This is better but the integrity check still complains. 

Another doi example: 10.5194/amt-4-1383-2011

I have 100s of warnings from the integrity check on this, so I would be grateful for a solution! Thanks in advance.

**Comment by oscargus** [comment] 2016-01-07 14:40
I think this is somehow related to the preference setting "Add curly braces to capital letters". It seems like the curly braces are removed from the table view and the entry editor if this is set for a particular field, but not otherwise. It would make sense to always remove them from the table, but never from the entry editor, independent of the setting.

I'm not a big fan of the title integrity check since it is fundamentally wrong. All these things are determined by the .bst-file and it is OK to write titles in title case, one should just not expect it to stay like that. Also, the correct way is to enclose the complete word in curly brackets, not just the capital letters.

**Comment by tobiasdiez** [comment] 2016-01-07 15:12
To support the last point of @oscargus, here a small quote from the biblatex manual:
> In bib ﬁles designed with traditional BibTeX in mind, it has been fairly common to
> only wrap single letters in braces to prevent case-changing: `title = {An Introduction to {L}a{T}e{X}}`
> The problem with this convention is that the braces will suppress the kerning on
> both sides of the enclosed letter. It is preferable to wrap the entire word in braces.

**Comment by stefan-kolb** [comment] 2016-05-19 11:53
@simonharrer Didn't you remove this auto initialization logic? So we can close this now?

**Comment by simonharrer** [comment] 2016-05-19 12:38
Yes, but I think we need to update the FAQ so that save actions should be used. @mlep could you help out here?

**Comment by stefan-kolb** [comment] 2016-08-03 12:08
Can we please document this and close the issue in the near future? I'm not really into this so I'd prefer if some of the participants can fix this documentation issue.

**Comment by mlep** [comment] 2016-08-04 11:18
Previous Q&A removed by  @matthiasgeiger .
I have just added a Q&A about save actions .
This should also be documented in an help file. I have just created a specific issue for this.

**Comment by tobiasdiez** [comment] 2016-08-04 12:32
So I think we can close this.

**Closed by tobiasdiez** 2016-08-04 12:32 UTC
Labels: documentation, integrity-checker
