### ISSUE TITLE
arxiv and eprinttype

### ISSUE THREAD

**Issue by thecaligarmo** [JabRef/jabref#10474] opened 2023-10-10 07:09 UTC
**Is your suggestion for improvement related to a problem? Please describe.**
When you import from arxiv (Using "New Entry" -> ID type = Arxiv -> Arxiv id) everything works magically =D But, there's a tiny thing that could be better. Right now, when you import it does *not* create a "eprinttype = {arxiv}" part in bibtex. What this means is that when you then try and access the url link for "eprint", it fails because it doesn't have eprinttype set. 

**Describe the solution you'd like**
When creating a new entry, if the new entry is an arxiv entry, then set the eprinttype to "arxiv"

**Comment by GuSheldom** [comment] 2023-10-10 12:15
Hi, I would like to work on this issue, would you mind assign it to me, please? Thanks!

**Comment by GuSheldom** [comment] 2023-10-13 04:37
Hi, I find a bug but I cannot explain why, when I try to import a entry with arxiv ID, it will return me 'archiveprefix = {arXiv}', which should be 'eprinttype = {arXiv}' if it is correct.
![image](https://github.com/JabRef/jabref/assets/106003523/45978d77-55d9-4a44-9ce6-2d28fef07ebb)

However, when I debugging the code, I find the ArXivFetcher should run correct, 
![image](https://github.com/JabRef/jabref/assets/106003523/4c193e23-e723-459b-9f51-149c23c9f9ae)

Is that caused by the 'ArXivIdentifier' which return me the wrong identifier, or other reason, that change the eprinttype to archiveprefix?

**Comment by GuSheldom** [comment] 2023-10-13 05:26
Or it is caused by the EntryConverter

**Comment by Siedlerchr** [comment] 2023-10-13 06:06
Maybe in the post cleanup actions?

**Comment by GuSheldom** [comment] 2023-10-13 10:17
I have fix the issue, but I think it is not an enhancement but a bug

**Comment by ThiloteE** [comment] 2023-10-13 10:25
Sometimes fixing a bug is like adding a feature and sometimes introducing a feature is like adding a bug. ;-)

**Closed** 2023-10-19 19:02 UTC
Labels: type: enhancement, fetcher, good first issue, FirstTimeCodeContribution

**Comment by Siedlerchr** [comment] 2023-10-21 12:40
@thecaligarmo  Thanks to @GuSheldom this issue is now fixed in the latest developer version:

Thank you for reporting this issue. We think, that is already fixed in our development version and consequently the change will be included in the next release.

We would like to ask you to use a development build from https://builds.jabref.org/main and report back if it works for you. Please remember to make a backup of your library before trying-out this version.
