### ISSUE TITLE
Freeze on rename file action

### ISSUE THREAD

**Issue by j0hannes** [JabRef/jabref#3768] opened 2018-02-23 13:53 UTC
- [x] I have tested the latest master version from http://builds.jabref.org/master/ and the problem persists

JabRef version 4.2-dev on OSX

Steps to reproduce:

1. add file to entry
2. choose "rename file"

Jabref does not react to anything but "force quit" anymore.

**Comment by LinusDietz** [comment] 2018-02-23 15:45
I use that feature basically every days on all kinds of branches and never had problems.

**Comment by stefan-kolb** [comment] 2018-03-14 15:53
> I use that feature basically every days on all kinds of branches and never had problems.
👍

**Comment by stefan-kolb** [comment] 2018-03-14 15:55
Sorry, we cannot reproduce the issue with the current information.

**Comment by LinusDietz** [comment] 2018-03-14 15:57
I guess I'll close this for now. @j0hannes, thank you for your report. Does it happen all the times, or just sometimes?

**Closed by LinusDietz** 2018-03-14 15:57 UTC
Labels: macOS, waiting-for-feedback

**Comment by j0hannes** [comment] 2018-03-15 15:03
It happened more than once, but just now I tested it successfully. I have no idea why in some cases it led to a crash.
