### ISSUE TITLE
Show a progress indicator when dragging and dropping PDF files to JabRef

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8738] opened 2022-05-01 19:34 UTC
**Is your suggestion for improvement related to a problem? Please describe.**
When I drag a PDF document into JabRef, it often takes time for it to process it. I also have experienced exceptions for that operation.

**Describe the solution you'd like**
In general, I like to see some indicator that something is going on in the background (especially when dragging more than one file to the window).

**Additional context**
I think that Citavi has this (might not be ideal, either, but at least it is there).

**Comment by claell** [comment] 2022-05-09 10:13
@Siedlerchr another useful label for this is probably `ui`.

**Comment by claell** [comment] 2022-05-09 10:51
Apparently, there is already a UI element for background tasks. Possibly, that can be extended.
![grafik](https://user-images.githubusercontent.com/6171135/167395638-f989bd57-b435-4149-a27b-b4eb577d4736.png)

**Comment by Yu0404531** [comment] 2022-10-23 13:51
Hi , I'm a new contributor — could you please give me a permission so I can view and modify the code ?

**Comment by Yu0404531** [comment] 2022-10-29 08:47
Ues “Jabref/logic/pdg/search/indexing/indexingTaskManager “ UI   to Display  “Jabref/gui/util   ”TableRowFactory process bar.
It this way ok?

**Comment by Ravitwr** [comment] 2023-01-19 04:19
Could I be assigned this task?

**Comment by ThiloteE** [comment] 2023-01-19 11:28
@Ravitwr thanks for your enthusiasm and commitment to JabRef. I have seen that you asked to be assigned to multiple issues. Just give a word, if you think you will not manage to work on or fix all of them, then I will unassign you. That way other people will know, the issue is "free to take"

**Comment by claell** [comment] 2023-01-21 16:13
@Ravitwr Thanks for looking into this. I don't know specific files right now, let me check.

**Comment by claell** [comment] 2023-01-21 16:35
The behavior seems to have improved from 5.7 to 5.9. I still had 5.7 installed and there, if I saw it correctly, the GUI was frozen after dropping something there. After updating to 5.9 later, the GUI is no longer frozen, and potentially, also the addition of the entry is faster (might just be subjective).

**Comment by claell** [comment] 2023-01-21 16:39
Just tested again with a larger bunch of over thirty book PDFs. There, it really takes a long time (still not finished, in fact). Each entry takes from few seconds to maybe even half a minute to be added subsequently. The books sometimes have several hundred pages.

**Comment by claell** [comment] 2023-01-21 16:40
Let me know if you need more specific details in order to be able to reproduce.

**Comment by Ravitwr** [comment] 2023-01-23 18:18
@claell Thanks for the input. Earlier I was trying to enter the files which didn't had the metadata therefore it was much faster. I am able to reproduce the problem with some other files. Will try to add the progress indicator.

**Comment by koppor** [comment] 2024-04-08 21:20
Pre-condition to reproduce is to enable online-processing of PDFs:

Ensure that using GROBID is enabled:

![image](https://github.com/JabRef/jabref/assets/1366654/a120f4d7-56ce-46a0-88b9-aebcafa694e8)

**Comment by koppor** [comment] 2024-04-08 21:32
Implementation hint:

- One needs to create a `Callable` (e.g, `() -> someMethod()`)
- This is then wrapped using `BackgroundTask`: `BackgroundTask.wrap(callable)`
- I assume, this issue is about importing, then `public ImportEntriesDialog(BibDatabaseContext database, BackgroundTask<ParserResult> task) {` can be used.

**Comment by BaronMac08** [comment] 2024-10-09 12:07
Hi, we are @Thomas-Bridgart, @xiaojie2008, @BaronMac08, and Maggie Sun, students at the Australian National University. For one of our assignments, we are tasked with contributing to an open-source project. We would like to take on this issue, with me being the main contributor.

I believe I could provide a reasonably good implementation for the enhancement mentioned in this issue. 

While working, we will cross-review our code and help each other to ensure the implementation's quality and progress.

**Closed** 2024-10-27 00:00 UTC
Labels: type: enhancement, ui, external files, FirstTimeCodeContribution, 📍 Assigned
