### ISSUE TITLE
Ver 3.1 does not refresh when switching between groups

### ISSUE THREAD

**Issue by zzjjzzgggg** [JabRef/jabref#637] opened 2016-01-04 14:35 UTC
[A bib file](https://github.com/JabRef/jabref/files/77284/test.bib.zip) has several groups. When clicking on different groups, the entries are not refreshed automatically. 

I have to click a column, e.g., `year`, or scroll to force JabRef to refresh. The expected behavior is that, 
   * when a group is clicked, entries in this group are floated to the top, 
   * entries not in this group are colored grey and listed at the bottom.

```
Linux 4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux
```

**Comment by simonharrer** [comment] 2016-01-04 17:42
Duplicate of #417

**Closed by simonharrer** 2016-01-04 17:42 UTC
