### ISSUE TITLE
RIS import

### ISSUE THREAD

**Issue by asnobli** [JabRef/jabref#1647] opened 2016-07-30 07:57 UTC
1. doi import does not work with the DO or M3 (RIS standard fields)
2. patent is imported as "other"

**Comment by tschechlovdev** [comment] 2016-08-01 10:29
Thanks for reporting. Could you please write the steps to reproduce and the file(s) you have used ? That would help me a lot.

**Comment by boceckts** [comment] 2016-08-10 10:13
I can import the doi using the M3 field. Make sure the "-" sign is at the fourth position and the doi has to be in the originally specified [doi](https://en.wikipedia.org/wiki/Digital_object_identifier#Display) format. An url can not be parsed (just yet).
For example I can read a .ris file with the field `M3  - doi:10.1000/182` and the doi displayed in jabref is 10.1000/182.
However looking at the code, the DO field seems to be not specified in the current ris importer and there is only a limited set of types for the TE field supported, excluding Patent. We should definitely rework this importer.

**Comment by stefan-kolb** [comment] 2016-09-28 07:50
@tschechlovdev  @Braunch  @boceckts This was fixed in #2028?!

**Comment by tschechlovdev** [comment] 2016-09-28 09:12
Yes this was fixed, so I think this can be closed now.

**Closed** 2016-09-28 09:14 UTC
Labels: bug, stupro

**Comment by crystalfp** [comment] 2019-03-25 18:14
Well, no.

In latest version (see below) JR ignores DO field. Try importing (after changing extension to .ris) the following RIS file: [PMC3113697.txt](https://github.com/JabRef/jabref/files/3004842/PMC3113697.txt)

JabRef 4.3.1
Windows 10 10.0 amd64 
Java 1.8.0_201

**Comment by chapb** [comment] 2020-03-02 22:15
Same problem as @crystalfp. The DO field is ignored during RIS import from Mendeley.
