### ISSUE TITLE
JabRef seems to ignore the "Filename format pattern" and the "File directory pattern", and finds existing PDF files multiple times

### ISSUE THREAD

**Issue by sauliusg** [JabRef/jabref#3038] opened 2017-07-21 19:06 UTC
JabRef version JabRef 4.0-dev (commit 46f58d6)
Linux 4.4.0-53-generic amd64
Java 1.8.0_131  on  LinuxMint-18.1

Steps to reproduce:

1. Pull, compile (./gradlew build) JabRef and put the JabRef executabel into the path (from build/distributions/JabRef-4.0-dev.tar)
2. Start JabRef; set Options|Preferences:
 - untick "Open last edited libraries at startup";
 - untick "Backup old files when saving"
 - tick "Use the BIB file location ..."
 - select "Use regular expression search", type
   ```
    **/[bibtexkey].*\\.[extension]
   ```
or
    ```
    **/[year]_[auth].*\\.[extension]
    ```
as a RE
3. In the "Import" tab:
 - Set "Filename format pattern" to \year_\auth_\firstpage
 - Set "File directory pattern" to "PDF" (or put the absolute path of the PDF directory). Create the corresponding PDF  directory. Click "OK" to save settings.
4. Add the following entry to a database:
@Article{Kalas2010,
  author    = {Matúš Kalas and Puntervoll, P. and Joseph, A. and Bartaseviciute, E. and Topfer, A. and Venkataraman, P. and Pettifer, S. and Bryne, J. C. and Ison, J. and Blanchet, C. and Kristoffer Rapacki and Inge Jonassen},
  title     = {BioXSD: the common data-exchange format for everyday bioinformatics web services},
  journal   = {Bioinformatics},
  year      = {2010},
  volume    = {26},
  number    = {18},
  month     = {Sep},
  pages     = {i540--i546},
  issn      = {1460-2059},
  doi       = {10.1093/bioinformatics/btq391},
  url       = {http://dx.doi.org/10.1093/bioinformatics/btq391},
  owner     = {saulius},
  publisher = {Oxford University Press (OUP)},
  timestamp = {2017.04.02},
}
4. The buggy behavior is observed:
 - The existing "by-author/K/Kalas/2010_Kalas_i540.pdf" file is reported as found twice (see the screen-shot); if both are ticked, the file is added twice to the entry:
@Article{Kalas2010,
  author    = {Matúš Kalas and Puntervoll, P. and Joseph, A. and Bartaseviciute, E. and Topfer, A. and Venkataraman, P. and Pettifer, S. and Bryne, J. C. and Ison, J. and Blanchet, C. and Kristoffer Rapacki and Inge Jonassen},
  title     = {BioXSD: the common data-exchange format for everyday bioinformatics web services},
  journal   = {Bioinformatics},
  year      = {2010},
  volume    = {26},
  number    = {18},
  month     = {Sep},
  pages     = {i540--i546},
  issn      = {1460-2059},
  doi       = {10.1093/bioinformatics/btq391},
  url       = {http://dx.doi.org/10.1093/bioinformatics/btq391},
  file      = {:by-author/K/Kalas/2010_Kalas_i540.pdf:PDF;:by-author/K/Kalas/2010_Kalas_i540.pdf:PDF},
  owner     = {saulius},
  publisher = {Oxford University Press (OUP)},
  timestamp = {2017.04.02},
}
 - If "Get fulltext" in the tab "General" is activated, the file is still downloaded as "Kalas2010.pdf", not as "2010_Kalas_i540.pdf", and is put to the directory where the BIB file resides, and not to its PDF subdirectory.

![screenshot from 2017-07-21 22-00-28](https://user-images.githubusercontent.com/10668420/28478420-f522293e-6e60-11e7-96c9-0d5419f457d5.png)

<details>
  <summary>Log File</summary>
  
  ```
  Paste an excerpt of your log file here
  ```
</details>

**Comment by lenhard** [comment] 2017-07-27 19:27
Thanks for reporting the issue. I guess this relates to http://discourse.jabref.org/t/file-linking-functionality-update/723 and will hopefully be fixed :)

**Comment by sauliusg** [comment] 2017-08-17 08:13
Indeed, the related discussion in  http://discourse.jabref.org/t/file-linking-functionality-update/723 was initated by me and I am working on the fix in my fork. Cheers, Saulius

**Comment by lenhard** [comment] 2018-01-17 16:10
If I recall it correctly, this issue was fixed in a PR by @sauliusg and we can close it.

**Closed by lenhard** 2018-01-17 16:10 UTC
Labels: bug, pdf

**Comment by stefanct** [comment] 2018-10-12 14:04
I had some very similar issues in 4.3.1 but can't reproduce them easily right now - thus I'll just leave this comment here instead of opening another issue - sorry.
