### ISSUE TITLE
File>Import into current database> default still Windows 1252

### ISSUE THREAD

**Issue by ajbelle** [JabRef/jabref#1153] opened 2016-04-09 03:35 UTC
JabRef version <3.2> on <Windows 7>

Steps to reproduce:

1. File>Import into current database> select 'utf8 encoded'.bib (Use the file you a viewing)
2. The import inspection dialog, and Possible duplicate entries so the imported file with coding corruption. eg: ° = Â° ©=Â©   “=â€œ ...
3. My guess is that the direct import has been changed from the OS default on the Window build to utf8, but when importing into the current database it is routing via the OS default encoding.
4. Reformatting the import.bib with text editor to CP1252 fixes the problem.

Possible relevant post are issue #262 @oscargus ,  [UTF8 import from bib file ](https://sourceforge.net/p/jabref/discussion/318825/thread/92143b77/#cc76), and #1080 ,but resolution is beyond me. There seem to have been edits [here](https://github.com/JabRef/jabref/commit/312fc6f3465554d86d28cb129058bd80feca0dd8) by  @lenhard 

Repeat: file opens fine, but File>Import into current database> or File>Import into new database> sees utf8 encoded file read as CP1252.

**Comment by Siedlerchr** [comment] 2016-04-10 17:40
Maybe related? #1080

**Comment by ajbelle** [comment] 2016-04-11 02:35
Yes quite possible @Siedlerchr, and that was one of the links (I have corrected them, THX). My impression is the 'issue' is not a coding bug, but is a systems level ommision or fault.

**Comment by koppor** [comment] 2016-04-11 07:40
What is the encoding of the opened database? My guess is that it is CP1252 instead of UTF8.

Related #558.

**Comment by lenhard** [comment] 2016-04-11 10:33
If you are using JabRef 3.2 then it cannot be caused by #1080 since this change is only available in the current development version.

**Comment by ajbelle** [comment] 2016-04-13 10:32
Thank you @lenhard I am actually running JabRef_windows-x64_3_3dev--snapshot--2016-03-25--livesearch--55fc5f2 which exhibited the fault, but backloaded V3.2 and it is identical. I checked V2.1 and same problem. That is why I suspect it is an omisison in the Windows build that has been there for a long time. I didn't want to confuse my post that it is a development build bug.

Your point that it doesn't seem to be  #1080 is valid.

**Comment by tobiasdiez** [comment] 2016-05-26 15:42
It seems to be fixed in the current development version. Probably as a result of https://github.com/JabRef/jabref/pull/1207. @ajbelle can you please double check that the issue is indeed fixed? Thanks!

**Comment by stefan-kolb** [comment] 2016-05-31 11:45
@ajbelle Thank you for your report :+1:
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.

**Comment by stefan-kolb** [comment] 2016-06-02 14:07
This should be fixed in current `master`. Please try the latest build from http://builds.jabref.org/master.
Please reopen the issue with additional information if the problem persists.

**Closed by stefan-kolb** 2016-06-02 14:07 UTC
Labels: waiting-for-feedback

**Comment by ajbelle** [comment] 2016-06-29 08:40
Sorry Gents, too busy to help further beyond this post. @tobiasdiez I checked and I do not think anything has changed. Installed Ver3.4 just then, and saved my .bib file (no errors detected and very fast save). Then openned it with Ver2.1 and tried saving (takes a long time). It returned the same as my original report with rogue "#" being detected. 
![default](https://cloud.githubusercontent.com/assets/12857679/16445848/f7be3986-3e27-11e6-8d7e-5b48d8f2c352.PNG)
Due to the apparent time this checking takes it should be part of the  |Quality>Clean up entries> menu option, if it is ever re-implemented IMHO.

**Comment by matthiasgeiger** [comment] 2016-06-29 19:09
@ajbelle this comment is not really related to this issue, is it? 

A general comment: We changed a lot of stuff in the last year, but opening files saved with version 2.X in a version 3.X should always be possible. 
However, the other way round is **NOT** expected to be working - especially not if features like groups are used which are not part of "standard bibtex".

**Comment by ajbelle** [comment] 2016-06-30 00:27
Yes @matthiasgeiger, you are right. The reason ver2.1 identified the issue was in #1188 which merged with this one. It picked it up when I openned my .bib with old ver2.1  install by mistake, making me think something was no longer being checked. As I said, ver2.1 takes a lot longer to save (bad) but may save future grief when BibTeX wont typeset (Good, especially with LyX that 'hides' BibTeX faults).  The issue is not with retrospective compatibility, it is about current functionality. I personally will open in PDE and fix it, so it was purely a "does anyone on the team care/know about this" notification. @ tobiasdiez asked me to check and I did. I hope it helps work out what has been done. I will be offline for several months now.

**Comment by Dellu** [comment] 2016-10-03 21:08
I am having this issue right now on a Mac. I imported a fairly  large (3300 entries) library to it. I have waited for more than an hour. Jabref still on "saving database...".

**Comment by matthiasgeiger** [comment] 2016-10-04 09:09
Hi Dellu,
what exactly is your problem (as various things are discussed in this report)? And which JabRef Version are you using?

**Comment by Dellu** [comment] 2016-10-04 13:48
I am using the latest version: 3.6. But,  I now manage to fix it. The problem seems with the text encoding in Jabref. Importing UTF-8 library into the ISO-8859 format was causing the trouble, I guess.  It is saving fine now.
