### ISSUE TITLE
Entry editor columns not well adjusted

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#7986] opened 2021-08-15 08:41 UTC
JabRef 5.3--2021-07-16--c99d61c
Linux 5.13.8-200.fc34.x86_64 amd64 
Java 16.0.1 
JavaFX 16+8

![Screenshot from 2021-08-15 10-31-24](https://user-images.githubusercontent.com/20518297/129472287-f501822e-93ab-444a-9af8-b66424c3073a.png)

shows the three "columns" view of the entry editor with two left hand columns of fields.
This is the default view on my system.

This has been a visibility bug (for many months/years). I cannot see the left hand fields well.

**Comment by koppor** [comment] 2021-08-15 21:07
This refs #6856 and https://github.com/JabRef/jabref/issues/6191.

**Comment by Siedlerchr** [comment] 2021-08-16 07:56
See https://github.com/JabRef/jabref/issues/6901#issuecomment-691493493 for the code

**Comment by ThiloteE** [comment] 2021-09-11 15:37
**Current workaround:** 
- You can move the column to the right and "disable the Related Articles Tab and the Latex Citations tab under Options -> Entry editor."
- tick the option under `Options>Entry preview>Show preview as a tab in entry editor`

**As long as the columns can't be adjusted well, one could argue for making the latter the default view for the Linux edition.**

**Comment by xiaoxianma** [comment] 2021-11-04 04:34
@koppor I'm interested in this. Will take a look and work on it.

**Comment by xiaoxianma** [comment] 2021-11-11 04:44
The problem is that when the window width is shrinking. The three columns of the entry editor are not shrinking equally. Instead, the middle column keeps the size until a minimum width size is reached. Need to make the first and second columns grow & shrink equally.

**Comment by xiaoxianma** [comment] 2021-11-11 06:36
@koppor just pushed a fix for the issue. Feel free to review and let me know if you have any questions. Thx!

**Closed** 2021-11-13 11:33 UTC
Labels: ui, entry-editor, good first issue

**Comment by ilippert** [comment] 2021-11-13 11:34
yeah, looking forward to testing this version

**Comment by Siedlerchr** [comment] 2021-11-13 11:44
Should be ready in roughly +/- half an hour.
