### ISSUE TITLE
Automatically switch between dark and light themes in Win 10/11

### ISSUE THREAD

**Issue by ehehela** [JabRef/jabref#10045] opened 2023-06-29 11:43 UTC
**Is your suggestion for improvement related to a problem? Please describe.**
In #8729, the issue is proposed for MacOS system. I hope this feature can be realized in Windows 10/11. 

**Describe the solution you'd like**
Add an option for Windows system like "use system setting".

**Additional context**

 In Windows 11, I use Task Scheduler to automatically switch between light and dark theme according to time. Once the system theme changed, other software, like MS office suite, Edge and VS Code, will automatically change its appearance. So, I hope JabRef can also make it possible.

**Comment by koppor** [comment] 2023-06-29 22:37
Thank you for the report. I think, this is a duplicate of https://github.com/JabRef/jabref/issues/8729.

**Closed by koppor** 2023-06-29 22:37 UTC
