### ISSUE TITLE
Installation problem with 5.2.257-1 (17 Nov 2020)

### ISSUE THREAD

**Issue by wujastyk** [JabRef/jabref#7109] opened 2020-11-17 16:01 UTC
JabRef version  on 

5.2.257-1 (17 Nov 2020).  

Linux Mint 20 Cinnamon 

Can't start the program so I can't give the full version info.

- [ ] **Mandatory**: I have tested the latest development version from http://builds.jabref.org/master/ and the problem persists

1. Launch the program
2. See this error message:
```
$ ./JabRef 
Error: Could not find or load main class org.jabref/org.jabref.gui.JabRefLauncher in module org.jabref

```

The installation didn't complain:

```
$ sudo -A dpkg -i /tmp/jabref_5.2-1_amd64.deb
(Reading database ... 391979 files and directories currently installed.)
Preparing to unpack /tmp/jabref_5.2-1_amd64.deb ...
Remove jabref-JabRef.desktop default handler for text/x-bibtex mime type from /usr/share/applications/defaults.list file
/usr/share/applications/defaults.list file updated
Unpacking jabref (5.2.257-1) over (5.2.257-1) ...
Setting up jabref (5.2.257-1) ...

```

**Comment by Siedlerchr** [comment] 2020-11-17 16:34
Duplicate of #7105 
Fix is on the way.

**Closed** 2020-11-17 16:34 UTC
