### ISSUE TITLE
Exception in google scholar search

### ISSUE THREAD

**Issue by ilippert** [JabRef/jabref#5029] opened 2019-06-03 15:13 UTC
snap, latest version, fedora 30

I entered a search term in the search interface for google scholar. the search started - and then I got this exception:

org.jabref.logic.importer.FetcherException: Error while fetching from Google Scholar
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:153)
	at org.jabref.gui.importer.fetcher.WebSearchPaneViewModel.lambda$search$1139(WebSearchPaneViewModel.java:97)
	at org.jabref.gui.util.BackgroundTask$1.call(BackgroundTask.java:46)
	at org.jabref.gui.util.DefaultTaskExecutor$1.call(DefaultTaskExecutor.java:122)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://scholar.googleusercontent.com/scholar.bib?q=info:yIP-zWE6ZqwJ:scholar.google.com/&output=citation&scisdr=CgXdNNZ6GAA:AAGBfm0AAAAAXPU6xHYhRX7Xs4yGmuGvKxLqyQeM4dUC&scisig=AAGBfm0AAAAAXPU6xIu1hJIjm2jhGlAmUDqtFEKPY5fF&scisf=4&ct=citation&cd=2&hl=en
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:203)
	at org.jabref.logic.net.URLDownload.asString(URLDownload.java:217)
	at org.jabref.logic.importer.fetcher.GoogleScholar.downloadEntry(GoogleScholar.java:170)
	at org.jabref.logic.importer.fetcher.GoogleScholar.addHitsFromQuery(GoogleScholar.java:164)
	at org.jabref.logic.importer.fetcher.GoogleScholar.performSearch(GoogleScholar.java:135)
	... 10 more
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://scholar.googleusercontent.com/scholar.bib?q=info:yIP-zWE6ZqwJ:scholar.google.com/&output=citation&scisdr=CgXdNNZ6GAA:AAGBfm0AAAAAXPU6xHYhRX7Xs4yGmuGvKxLqyQeM4dUC&scisig=AAGBfm0AAAAAXPU6xIu1hJIjm2jhGlAmUDqtFEKPY5fF&scisf=4&ct=citation&cd=2&hl=en
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
	at org.jabref.logic.net.URLDownload.openConnection(URLDownload.java:319)
	... 15 more

**Comment by matthiasgeiger** [comment] 2019-06-03 19:21
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL

Refers to the problem that Google is rate limiting access to scholar in case of automated screen scraping. Thus, we cannot really do here anything on JabRef side.

**Comment by ilippert** [comment] 2019-06-03 22:09
thank you!
yes, ok, thanks - maybe a "human-readable" response would be advisable(?)

**Comment by stefan-kolb** [comment] 2020-02-21 23:38
Duplicate of https://github.com/JabRef/jabref/issues/4423

**Closed by stefan-kolb** 2020-02-21 23:38 UTC
Labels: fetcher
