### ISSUE TITLE
Saving issues including but not limited to "The library has been modified by another program"

### ISSUE THREAD

**Issue by eustomaqua** [JabRef/jabref#7275] opened 2020-12-31 04:30 UTC
**Is your suggestion for improvement related to a problem? Please describe.**
**(A clear and concise description of what the problem is. Ex. I'm always frustrated when [...])**

I got the same issue as [https://github.com/JabRef/jabref/issues/4877](https://github.com/JabRef/jabref/issues/4877) even after trying [this example](https://github.com/JabRef/jabref/issues/4877#issuecomment-501544917), here is my case:

- JabRef 5.2 (5.1 as well)
- Windows 10
- the .bib file is only 14 KB

I feel like the new version is not working as well as JabRef 3.8.2, including but not limited to the speed of saving bibs, the mistaken deletion by "The library has been modified by another program", the cannot-open-by-clicking-the-.bib-file-directly (you must open a file in JabRef), and the aesthetic of appearance.

Especially, the issue of "The library has been modified by another program" happens right after I saved my bib manually. If you choose to review the changes and accept them, it would be in all probability losing the manual change that you just saved. And If you dismiss the changes, well, I'm not sure whether JabRef saved all changes I wanted.

**Describe the solution you'd like**
**(A clear and concise description of what you want to happen.)**

I doubt that this issue is caused by .bak and .sav, because in the version of JabRef 3.8.2, it would remind you there is a backup or something like that when you open a bib file, but in the new version, it won't do the analogous thing, it just gives the "The library has been modified by another program" when you-dont-know-when-and-why.

Hope this issue would be fixed soon

**Additional context**
**(Add any other context or screenshots about the feature request here.)**

**Comment by tobiasdiez** [comment] 2021-01-02 20:55
As you say, this is a duplicate of https://github.com/JabRef/jabref/issues/4877.

**Closed by tobiasdiez** 2021-01-02 20:55 UTC

**Comment by eustomaqua** [comment] 2021-01-03 13:58
> As you say, this is a duplicate of #4877.

I'm sorry? But #4877 didn't solve the problem?

**Comment by tobiasdiez** [comment] 2021-01-03 14:14
Sorry for not writing a proper explanation. 
#4877 is still open, that means the problem is not yet fixed. Moreover, we do not want to have more than one issue for the same problem, because this makes issue management harder. Thus, I've closed this issue in favor of #4877.

**Comment by eustomaqua** [comment] 2021-01-04 07:39
Got it. (I opened the issue because #4877 was close then.)
I'll keep an eye on #4877, thanks
