### ISSUE TITLE
Library has changed: bug has reappeared

### ISSUE THREAD

**Issue by AEgit** [JabRef/jabref#5736] opened 2019-12-11 13:23 UTC
JabRef 5.0-alpha--2019-12-11--c3b7ee7
Windows 10 10.0 amd64 
Java 13.0.1

1. Open JabRef database
2. Make no changes at all to the database
3. Try to close the database
4. Message: "Library has changed" appears giving the option to "Save changes", "Discard changes", and "Return to JabRef"

I thought this issue had been solved in some previous contribution, but it appears again in the recent dev version of JabRef.

**Comment by AEgit** [comment] 2019-12-11 14:17
Update: If I use a database that has been stored using the developer version of JabRef instead of the old version 3.8.2 the issue does not appear.

The issue therefore might (?) be related to the problems reported here https://github.com/JabRef/jabref/issues/5735#issue-536363365 and here https://github.com/JabRef/jabref/issues/5734, especially considering the fact that some of the issues also appear to relate to the version in which the JabRef database was stored in (see updated descriptions in the issue reports).

If that is the case, this might explain also, why it previously had been impossible to reproduce similar error reports. Maybe, the underlying database had not been saved using the current dev version of JabRef, but an older (release) version of JabRef.

**Comment by Siedlerchr** [comment] 2019-12-11 14:26
@AEgit  It would be nice if you could send us your 3.8.2 db. Simply send it to developers@jabref.org if you don't want it to be public. When you open an older version in the new version, there are some migration steps happening, especially regarding groups.

**Comment by AEgit** [comment] 2019-12-11 14:40
@Siedlerchr Done. Thank you very much for your help!

**Comment by tobiasdiez** [comment] 2019-12-11 19:53
For the first time every, I was finally able to reproduce this error (with my own file). Let's see when I find the time to investigate this further...

**Comment by AEgit** [comment] 2019-12-11 20:43
Note, that I cannot reproduce this behaviour with the following older development version:

JabRef 5.0-alpha--2019-12-04--5dcb565
Windows 10 10.0 amd64 
Java 13.0.1

**Comment by Siedlerchr** [comment] 2019-12-14 16:04
When running current master from Eclipse I don't get a change dialog even if I modify the file ony my disk. I hardly can trigger that dialog. Still not understanding it.

**Comment by koppor** [comment] 2019-12-25 12:53
Refs https://github.com/JabRef/jabref/issues/5257

**Comment by tobiasdiez** [comment] 2020-01-11 15:35
This is essentially a duplicate of https://github.com/JabRef/jabref/issues/4877

**Closed by tobiasdiez** 2020-01-11 15:35 UTC
Labels: bug 🤹‍♂️, export / save
