### ISSUE TITLE
Exception when using an example search request

### ISSUE THREAD

**Issue by claell** [JabRef/jabref#8740] opened 2022-05-01 19:46 UTC
### JabRef version

5.6 (latest release)

### Operating system

Windows

### Details on version and operating system

Windows 10

### Checked with the latest development build

- [x] I made a backup of my libraries before testing the latest development version.
- [x] I have tested the latest development version and the problem persists

### Steps to reproduce the behaviour

1. Use JabRef
2. Search for `title|keywords = "image processing"` as described here: https://docs.jabref.org/finding-sorting-and-cleaning-entries/search#advanced

### Appendix
![grafik](https://user-images.githubusercontent.com/6171135/166162239-801ce559-e289-4fd6-a880-147de334d9fb.png)

<details>

<summary>Log File</summary>

```
java.lang.IllegalStateException: field "path" was indexed without position data; cannot run PhraseQuery (phrase=path:"imag process")
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.PhraseQuery$1.getPhraseMatcher(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.PhraseWeight.scorer(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.Weight.scorerSupplier(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.BooleanWeight.scorerSupplier(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.BooleanWeight.scorer(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.Weight.bulkScorer(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.BooleanWeight.bulkScorer(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.IndexSearcher.search(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.IndexSearcher.search(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.IndexSearcher.search(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.IndexSearcher.searchAfter(Unknown Source)
	at org.apache.lucene.core@9.1.0/org.apache.lucene.search.IndexSearcher.search(Unknown Source)
	at org.jabref@5.7.19/org.jabref.logic.pdf.search.retrieval.PdfSearcher.search(Unknown Source)
	at org.jabref@5.7.19/org.jabref.model.search.rules.GrammarBasedSearchRule.init(Unknown Source)
	at org.jabref@5.7.19/org.jabref.model.search.rules.GrammarBasedSearchRule.validateSearchStrings(Unknown Source)
	at org.jabref@5.7.19/org.jabref.model.search.rules.SearchRules.getSearchRuleByQuery(Unknown Source)
	at org.jabref@5.7.19/org.jabref.logic.search.SearchQuery.<init>(Unknown Source)
	at org.jabref@5.7.19/org.jabref.gui.search.GlobalSearchBar.performSearch(Unknown Source)
	at org.jabref.merged.module@5.7.19/org.reactfx.util.FxTimer.lambda$restart$0(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.scenario.animation.shared.TimelineClipCore.visitKeyFrame(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.scenario.animation.shared.TimelineClipCore.playTo(Unknown Source)
	at org.jabref.merged.module@5.7.19/javafx.animation.Timeline.doPlayTo(Unknown Source)
	at org.jabref.merged.module@5.7.19/javafx.animation.AnimationAccessorImpl.playTo(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.scenario.animation.shared.SingleLoopClipEnvelope.timePulse(Unknown Source)
	at org.jabref.merged.module@5.7.19/javafx.animation.Animation.doTimePulse(Unknown Source)
	at org.jabref.merged.module@5.7.19/javafx.animation.Animation$1.lambda$timePulse$0(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at org.jabref.merged.module@5.7.19/javafx.animation.Animation$1.timePulse(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(Unknown Source)
	at org.jabref.merged.module@5.7.19/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at org.jabref.merged.module@5.7.19/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

</details>

**Comment by claell** [comment] 2022-05-01 19:51
A query without a space in it seems to work fine, so I suspect it has something to do with it.

**Comment by LIM0000** [comment] 2022-05-11 04:16
Related to #8287

**Comment by Siedlerchr** [comment] 2022-05-11 06:56
@LIM0000  Thanks, it's indeed a Duplicate of #8287

**Closed by Siedlerchr** 2022-05-11 06:56 UTC
Labels: search
