### ISSUE TITLE
several searches are inoperational

### ISSUE THREAD

**Issue by leosenko** [JabRef/jabref#221] opened 2015-10-09 04:19 UTC
For ADS, ArXiv, ACM Portal search does not work, I get for ADS:
![image](https://cloud.githubusercontent.com/assets/3658579/10385735/1e1e04f4-6e1b-11e5-865a-6714957ac196.png)
For ArXiv:
![image](https://cloud.githubusercontent.com/assets/3658579/10385741/3ce8efa2-6e1b-11e5-9c14-4c04816aa33e.png)
AMC:
![image](https://cloud.githubusercontent.com/assets/3658579/10385744/4b310112-6e1b-11e5-9f28-dd174976fa2d.png)

I am surprised that no bugs are reported but the issue is serious.

Thank you.

**Comment by lenhard** [comment] 2015-10-09 08:13
@leosenko: Thanks for the notification! We only have limited time and resources, so could you provide a pull request that repairs the searches?

Otherwise, we will delete any inoperational web fetchers from the project.

**Comment by lenhard** [comment] 2015-10-09 08:33
Related #101

Seems like a working version of ADS and ArXiv are in the making.

**Comment by lenhard** [comment] 2015-10-12 08:41
ADS and ArXiv search implemented by #101

TODO:
 - Delete ACM Portal search

**Comment by matthiasgeiger** [comment] 2015-10-12 09:42
Apart from the ACM case the behavior is not a bug. 

For Arxiv.org and ADS the implemented search is not a "keyword searach" but DOIs or "arxiv keys" (e.g., `arXiv:1510.02282`) must be used (same is true for "DOI to BibTeX").

However, this really should be documented!

**Comment by matthiasgeiger** [comment] 2015-10-30 13:18
ACM Portal bug is fixed now 882ab0e - documentation still has to be improved.

**Comment by matthiasgeiger** [comment] 2015-10-30 14:53
At least ADS-DOI fetcher now shows a better error message: 

![ads-screenshot](https://cloud.githubusercontent.com/assets/676652/10848848/3c919086-7f1e-11e5-815d-65beced5d347.png) 

see ac04dcb

**Comment by matthiasgeiger** [comment] 2015-11-02 14:35
The Arxiv.org fetcher now shows the same "Note"

**Closed by matthiasgeiger** 2015-11-02 14:35 UTC
Labels: documentation

**Comment by oscargus** [comment] 2015-11-02 16:58
Is the idea that these should be fetchers only? At least ArXiv provides a search API to get XML-results, which should be quite feasible to parse and import bibtex-data from (or use a two-step approach as the Google Scholar search). I understand that it is a question of time to some extent, but just wanted to check if there is a master plan to skip searching and "only" fetch things?

**Comment by koppor** [comment] 2015-11-02 18:31
I think, currently, JabRef issues a search query and then gets a list of results (converted to bibtex if not bibtex is directly received). I think, there is no intermediate search somehow...

**Comment by matthiasgeiger** [comment] 2015-11-02 20:19
The current implementation is that a "arxiv key" such as `arXiv:astro-ph/0209314` must be inserted in the search/fetch field and the result can be added to the current database. 

Of course this could be enhanced to use the full search capabilities of arxiv.org. But my primary goal was to fix the current behavior :wink:

**Comment by oscargus** [comment] 2015-11-02 20:32
OK! Maybe there should be a distinction between fetchers and searchers? Two different windows/menu options? Or at least rename all entries as either Fetch XXX och Search YYY?

**Comment by koppor** [comment] 2015-11-02 21:34
Currently, the fetchers IMHO work seamlessly as searchers. The only exception seem to be the DOI, the ISBN, and the arXiv fetcher, aren't they? Maybe, there should be a simple fallback at a fetcher, where an invalid object identifier is presented: It should try to search.

Reason: The UI should be more simple. For instance, the "Auto" button in the "General" tab first searches locally for a file. If the file was not found, the net is searched for full text. This automatism is pretty nice.

**Comment by matthiasgeiger** [comment] 2015-11-03 08:07
"ADS from ADS-DOI" is another fetcher which requires a "key" instead of an arbitrary search term.
